### ISSUE TITLE
Update doc about how to gen client

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/community#1007]
This doc seems to be out of date.
https://github.com/kubernetes/community/blob/master/contributors/devel/generating-clientset.md

/assign @caesarxuchao

**Comment by mrbobbytables** [comment]
I think the document has been updated, but history lost in the documentation shuffle...
@mengqiy @caesarxuchao can you double check and see if this still needs to be updated?
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/generating-clientset.md

**Comment by mrbobbytables** [comment]
I'm going to go ahead and close this out. If this is still relevant, please go ahead and reopen or create a new issue.

/close
