### ISSUE TITLE
Make the cherry-pick process document easier to find

### ISSUE THREAD

**Issue by bboreham** [kubernetes/community#1025]
Currently I have been searching for ten minutes and I cannot find it at all.
#994 takes me to https://github.com/kubernetes/community/issues/cherry-picks.md which is "Not found".
Searching for things like `cherry-pick kubernetes process`, I didn't find anything definitive.

EDIT: Using GitHub search in this repo I found https://github.com/kubernetes/community/blob/master/contributors/devel/cherry-picks.md

**Comment by xiangpengzhao** [comment]
@bboreham I send a PR trying to fix this. It adds a link in k8s-merge-robot's comment.

When a PR is merged, k8s-merge-robot will comment as below.
```
k8s-merge-robot commented 2 minutes ago

Automatic merge from submit-queue
```

I modify it to be
```
k8s-merge-robot commented 2 minutes ago

Automatic merge from submit-queue. If you want to cherry pick this PR, please follow the instructions here.
```

`here` has a link to cherry-picks.md, it's shown as [here](https://github.com/kubernetes/community/blob/master/contributors/devel/cherry-picks.md).

**Comment by krzysztof-jastrzebski** [comment]
You can find documentation here:
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md
