### ISSUE TITLE
Add kubernetes to the list of "Great for new contributors" on github

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/community#1034]
>These projects have a history and reputation for being welcoming to new open source contributors. Have you had a great experience as a new contributor on an open source project? We'd love to hear about it!

https://github.com/showcases/great-for-new-contributors

I think kubernetes is such a project :) How about adding it to that list? (Not sure how to, though)

@bgrant0607 @sarahnovotny

**Comment by bgrant0607** [comment]
@xiangpengzhao Interesting idea, but I don't think we need to advertise for more contributors, and we're not yet ready to handle them. I'd at least want the contributor guide to be finished first, and the metrics dashboards so that we can observe the impact, identify bottlenecks, etc.

**Comment by xiangpengzhao** [comment]
@bgrant0607 agree. Thanks! :)
