### ISSUE TITLE
Request for new #wg-cloud-provider slack channel

### ISSUE THREAD

**Issue by jagosan** [kubernetes/community#1047]
Please create a new slack channel for the cloud provider working group. #wg-cloud-provider seems appropriate given precedent.

**Comment by xiangpengzhao** [comment]
@jagosan It would be good to also list #wg-cloud-provider in [sig-list.md](https://github.com/kubernetes/community/blob/master/sig-list.md) and create a dir "wg-cloud-provider" in root of this repo and write an introduction doc in the dir for the wg :)

**Comment by castrojo** [comment]
/close

The channel exists so I'm closing this!
