### ISSUE TITLE
Upload location for meeting videos

### ISSUE THREAD

**Issue by justinsb** [kubernetes/community#1069]
Is there a doc that describes how to upload videos?  The empty link from sig-aws reminds me that I need to upload our videos!

**Comment by justinsb** [comment]
cc @sarahnovotny

**Comment by xiangpengzhao** [comment]
@justinsb I think you may want to [Create a new channel](https://support.google.com/youtube/answer/1646861?hl=en) and then [Upload videos](https://support.google.com/youtube/answer/57407?hl=en).

**Comment by castrojo** [comment]
https://github.com/kubernetes/community/blob/master/community/K8sYoutubeCollaboration.md

^^ the workflow is there, I'll send you the playlist collab link via mail.

**Comment by castrojo** [comment]
Just follow up and close this bug when you've accepted the playlist collaboration link, thanks!

**Comment by castrojo** [comment]
@justinsb All set here, can we close this?
