### ISSUE TITLE
Design proposals have lots of broken links to other design proposals

### ISSUE THREAD

**Issue by mindprince** [kubernetes/community#1109]
https://github.com/kubernetes/community/pull/1010 moved design proposals to SIG specific directories but didn't update the internal links from one design proposal to another. So, all proposals that refer to other proposals have broken links now which makes them harder to read.

/cc @grodrigues3 @bgrant0607

**Comment by bgrant0607** [comment]
@mindprince Could you please send a PR to fix them?

**Comment by php-coder** [comment]
I'll fix them.

**Comment by xiangpengzhao** [comment]
@php-coder awesome! @zhangxiaoyu-zidif had similar idea in https://github.com/kubernetes/kubernetes.github.io/pull/5530#issuecomment-331099373

Can the tools you used in your PR automatically check the broken links referenced in other repo?

**Comment by php-coder** [comment]
> Can the tools you used in your PR automatically check the broken links referenced in other repo?

I didn't use any tools this time. It was one-liners on shell :)

**Comment by xiangpengzhao** [comment]
@php-coder thanks! If you try and find some tools workable, feel free to ping @zhangxiaoyu-zidif :)

**Comment by duglin** [comment]
sig svc-cat uses this:  https://github.com/duglin/vlinker
