### ISSUE TITLE
Consider automate check for the broken links

### ISSUE THREAD

**Issue by php-coder** [kubernetes/community#1117]
In order to be noticed about broken links quickly I suggest to automate such check. There are some useful tools for that, for example: https://github.com/dkhamsing/awesome_bot and https://www.npmjs.com/package/markdown-link-check

It's possible to run such check on each pull request or daily (see https://docs.travis-ci.com/user/cron-jobs/).

**Comment by xiangpengzhao** [comment]
cc @zhangxiaoyu-zidif

**Comment by duglin** [comment]
sig svc-cat uses: https://github.com/duglin/vlinker

**Comment by nikhita** [comment]
dupe of https://github.com/kubernetes/community/issues/359

**Comment by cblecker** [comment]
Closing as dupe of #359 
/close
