### ISSUE TITLE
Document how to update SIG-foo READMEs

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/community#1121]
We now should modify `sigs.yaml` and then run `make` to update `sig-list.md` and `sig-foo README`. But recently I saw there were several PRs whose authors didn't know this.

https://github.com/kubernetes/community/pull/931#issuecomment-323051821
https://github.com/kubernetes/community/pull/1089#issuecomment-330575222
https://github.com/kubernetes/community/pull/1120#discussion_r140520897

We should document this. I suggested to add some description into `sigs.yaml` and then `make` to add the description to the doc header of each sig README.

cc @jamiehannaford @cblecker

**Comment by xiangpengzhao** [comment]
cc @kubernetes/sig-contributor-experience-feature-requests

**Comment by jamiehannaford** [comment]
@xiangpengzhao Yeah totally agree. Feel free to assign me to this and I'll try to get around to it next week.

We actually have tests in `./hack/verify.sh` that would bubble up these errors, but AFAIK we haven't added the necessary GitHub hooks for them yet.

@cblecker Do you think we can add them?

**Comment by xiangpengzhao** [comment]
@jamiehannaford github didn't allow me to assign this to you, but feel free to work on it. Thanks a lot!
