### ISSUE TITLE
api_changes.md: add protobuf definitions to the Frobber struct

### ISSUE THREAD

**Issue by php-coder** [kubernetes/community#1159]
Most of the [examples with the `Frobber` struct](https://github.com/kubernetes/community/blob/master/contributors/devel/api_changes.md#on-compatibility) has only JSON definitions while some of them also have a protobuf definitions. In order to make the doc consistent, all the examples should be written in am uniform way.

**Comment by php-coder** [comment]
/sig cluster-api
@kubernetes/sig-cluster-api-feature-requests,

**Comment by nikhita** [comment]
/remove-lifecycle stale

I think we should remove the examples with proto in them because proto definitions are generated. They are not expected to be written manually.
