### ISSUE TITLE
SIG list doesn't help with /sig command

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/community#1172]
When the k8s-merge-bot tells me to add a /sig label ([example](https://github.com/kubernetes/kubernetes/issues/53683#issuecomment-335624804)), It redirects me to this list: https://github.com/kubernetes/community/blob/master/sig-list.md

But this list is all human-readable names e.g. "Contributor Experience" but I can't use this in /sig command. It's unclear to find out which one is the correct value:
- /sig Contributor Experience
- /sig "Contributor Experience"
- /sig contributor-experience

I had to visit https://github.com/kubernetes/kubernetes/labels to find out which values are valid.

**Comment by liggitt** [comment]
> There are no sig labels on this issue. Please add a sig label

Oh, the irony

**Comment by cblecker** [comment]
(comment to try and trigger the bots)
