### ISSUE TITLE
Two documents with too similar titles

### ISSUE THREAD

**Issue by porridge** [kubernetes/community#1212]
- "Kubernetes Developer Guide": https://github.com/kubernetes/community/blob/master/contributors/devel/README.md
- "Development Guide": https://github.com/kubernetes/community/blob/master/contributors/devel/development.md

*please* retitle one of them

**Comment by porridge** [comment]
@kubernetes/sig-docs-bugs

**Comment by porridge** [comment]
Actually, @kubernetes/sig-contributor-experience-bugs might be a better
audience.

**Comment by grodrigues3** [comment]
The README.md looks more like a table of contents or a sitemap with links to actual content.

What about calling it a Table of Contents or Index or something of that nature?

**Comment by castrojo** [comment]
cc @guineveresaenger we need to take this into account when we land the contributor guide.
