### ISSUE TITLE
Wrong order of workflow steps

### ISSUE THREAD

**Issue by porridge** [kubernetes/community#1213]
The [workflow instructions](https://github.com/kubernetes/community/blob/master/contributors/devel/development.md#workflow) suggest to first run `make verify` and later commit the change.

However `make verify` will stop asking for the commit:

```
Verifying hack/make-rules/../../hack/verify-staging-godeps.sh

Unexpected dirty working directory:

   M pkg/kubelet/pleg/generic.go

Commit your changes in another terminal and then continue here by pressing enter.
```

so it would be more useful to advise to commit first, and later `--amend` as necessary.

**Comment by porridge** [comment]
@kubernetes/sig-contributor-experience-bugs

**Comment by grodrigues3** [comment]
@kubernetes/sig-testing-bugs do you guys own the make verify script?

**Comment by xiangpengzhao** [comment]
for the very `verify-staging-godeps.sh`, ping @deads2k :)

**Comment by cblecker** [comment]
This isn't a bug in the scripts -- they need things to be committed to check for dependency changes.

This is an issue with the docs needing to be updated.

**Comment by nikhita** [comment]
/remove-lifecycle rotten

I think the same goes for docs for updating dependencies. We need to commit the changes before update deps for staging.

https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md#saving-deps-in-staging-repos

**Comment by nikhita** [comment]
/remove-lifecycle stale

still relevant
