### ISSUE TITLE
Move release docs to release repo?

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/community#1229]
We have some release associated docs here:
https://github.com/kubernetes/community/tree/master/contributors/devel/release

Do we need to move these docs to https://github.com/kubernetes/release ?

/cc @bgrant0607 @enisoc

**Comment by enisoc** [comment]
I think the plan is to move these to https://github.com/kubernetes/sig-release

cc @calebamiles

**Comment by xiangpengzhao** [comment]
Yeah I see some similar docs here: https://github.com/kubernetes/sig-release/tree/master/ephemera

Are we planning to combine the diff to there and remove these docs in this repo?

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-release-pr-reviews

**Comment by nikhita** [comment]
related https://github.com/kubernetes/community/issues/1760

**Comment by cblecker** [comment]
I believe this is complete.
