### ISSUE TITLE
Document process for becoming an approver

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/community#1234]
It would be really nice to have a section that outlines the process for each different type. We have some details around the approver role, but a section like 

### Process to become an Approver

May help with the readability of the document.

I literally skimmed over the single section that says submit a PR.

The content is readable, just a bit more organization into sections would be nice.

**Comment by castrojo** [comment]
cc @parispittman , who is working on this.

**Comment by cblecker** [comment]
/remove-lifecycle stale
Still relevant

**Comment by chris-short** [comment]
Does this not cover it? https://github.com/kubernetes/community/blob/master/community-membership.md

**Comment by stp-ip** [comment]
For members that seems to be the case. For the other roles it just defines the requirements in a sense of checkpoints for someone reviewing such a role switch imo. The great thing about the members requirements section is that it also works as a how to move to a member role.

**Comment by nikhita** [comment]
/remove-lifecycle stale

Can someone edit the title to say "Document process for becoming an approver" or something like that?

/cc @parispittman 
who is focussing on mentoring initiatives for the same.

**Comment by mrbobbytables** [comment]
This has been open for some time, but I think it's been sorted out --
We've fleshed out the approver section in our community membership doc: 
https://github.com/kubernetes/community/blob/master/community-membership.md#approver

Several SIGs/subprojects have started to spell things out more specifically as well:
https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/CONTRIBUTING-ROLES.md

I'm going to go ahead and close this out, but we can reopen and discuss further if needed.

Thanks!
/close
