### ISSUE TITLE
Steering Committee GitHub team

### ISSUE THREAD

**Issue by idvoretskyi** [kubernetes/community#1239]
As the Steering Committee has been elected, I would propose to update @kubernetes/steering-committee with the new list of members:
@spiffxp 
@michelleN 
@derekwaynecarr 
@timothysc 
@pwittrock 
@quinton-hoole 

Also, we may consider removing existing members from the team.

cc @dankohn

**Comment by bgrant0607** [comment]
All 13 members are now in that team.

Don't understand why we'd remove existing members.

**Comment by idvoretskyi** [comment]
> Don't understand why we'd remove existing members.

Are they still the Steering Committee members? I'm not against of their participation, just would like to avoid the confusion where unnecessary.

**Comment by bgrant0607** [comment]
Yes.

**Comment by bgrant0607** [comment]
https://github.com/kubernetes/steering/blob/master/charter.md#establishment-of-a-steering-committee

**Comment by idvoretskyi** [comment]
@bgrant0607 thanks.
