### ISSUE TITLE
Complete Install etcd in the Development Guide

### ISSUE THREAD

**Issue by alessbn** [kubernetes/community#1256]
The Development Guide in the [Woorkflow section](https://github.com/kubernetes/community/blob/master/contributors/devel/development.md#install-etcd) describes how to install `etcd` as follows:
#### Install etcd
`hack/install-etcd.sh`

I propose to complete the instruction as is described in the [Testing guide](https://github.com/kubernetes/community/blob/master/contributors/devel/testing.md#install-etcd-dependency), including _$working_dir_ that has been previously defined in the development guide:

#### Install etcd
Kubernetes integration tests require your `PATH` to include an [etcd](https://github.com/coreos/etcd/releases) installation. Kubernetes includes a script to help install etcd on your machine.
```sh
cd $working_dir/kubernetes
hack/install-etcd.sh  # Installs in ./third_party/etcd
echo export PATH="\$PATH:$working_dir/kubernetes/third_party/etcd" >> ~/.profile  # Add to PATH
```

**Comment by nikhita** [comment]
@alessbn Any updates?

**Comment by alessbn** [comment]
Hi @nikhita
I submit my PR, could you review it?
