### ISSUE TITLE
document OWNERS options field and no_parent_owners feature

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#1286]
We changed the code lets change the docs while we're at it https://github.com/kubernetes/test-infra/issues/5197

/assign @mml @BenTheElder

**Comment by cjwagner** [comment]
Note that these options won't be used until we switch approval handling to Prow. kubernetes/test-infra#5115

**Comment by spiffxp** [comment]
https://github.com/kubernetes/test-infra/pull/5571 turned this feature on for k/k

https://github.com/kubernetes/community/blob/master/contributors/devel/owners.md is due for a refresh, it'd be helpful to document the destination state we're migrating to (prow handles things, not mungegithub, and there are some new owners features), and link in issues that describe in-progress migration
