### ISSUE TITLE
api_changes could be improved

### ISSUE THREAD

**Issue by php-coder** [kubernetes/community#1297]
1) Quote from https://github.com/kubernetes/community/blob/a0d81523e35af4a29843e0410d53fe35ef0fde6b/contributors/devel/api_changes.md#generate-code:

> To invoke these generators, you can run `make generated`, which runs a bunch of scripts.

But there is no `make generated`:
```console
$ make generated
make: *** No rule to make target 'generated'.  Stop.
```

2) Also I know that there is a concept of "cohabiting resources", but the documentation doesn't mention it at all.

**Comment by php-coder** [comment]
I don't know what SIG is responsible for the API.

**Comment by cblecker** [comment]
I think the doc just needs to be updated. The make target is `generated_files`

**Comment by php-coder** [comment]
One more point: looks like we should update `defaulting_test.go` when we're adding a new API group.

**Comment by nikhita** [comment]
xref. https://github.com/kubernetes/kubernetes/issues/46404 (feature gate deprecation policy).

**Comment by nikhita** [comment]
Related https://github.com/kubernetes/community/issues/1159.

**Comment by php-coder** [comment]
More places that should be updated for a new API were discovered:
- `pkg/master/import_known_versions.go` (this file has a comment "These imports are the API groups the API server will support")
- `test/integration/etcd/etcd_storage_path_test.go`

**Comment by nikhita** [comment]
I'll try looking at some of them.

**Comment by nikhita** [comment]
Closing this in favour of https://github.com/kubernetes/community/issues/3211. Please reopen if needed.

/close
