### ISSUE TITLE
architecture/principles.md broken link

### ISSUE THREAD

**Issue by ms4720** [kubernetes/community#1317]
in https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/principles.md

link: API conventions.

points to: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/devel/api-conventions.md

should point to: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md

I will fix

**Comment by jdumars** [comment]
Thanks for your contribution!  This has been merged.
