### ISSUE TITLE
Scalability guidelines recommend etcd version out of sync with community CI results

### ISSUE THREAD

**Issue by countspongebob** [kubernetes/community#1321]
This is a tracking issue for the discussion at the 11/2/17 Sig Scalability meeting. Etcd 3.0.17 is what passed community CI at the 5000 node level. The "3.1.8 minimum" recommendation is out of sync with actual test results.

I will plan to open a PR.

https://github.com/kubernetes/community/blob/master/sig-scalability/provider-configs.md

Question: Should this issue cover release notes, or should we open a separate issue?

@spiffxp @timothysc

**Comment by spiffxp** [comment]
I would suggest a separate issue for for release notes

https://github.com/kubernetes/community/blob/master/contributors/devel/release/scalability-validation.md#concretely-define-test-configuration says "Any non-default config used" but we would greatly appreciate some guidance on how to find the default config if not explicit definition for things like external dependencies.  ie: etcd version, etcd cluster, container runtime, container runtime version, etc.

**Comment by timothysc** [comment]
I think the release notes should call out full versions for sure.
