### ISSUE TITLE
Update sigs.yaml to include wg-cloud-provider

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#1333]
There is a https://groups.google.com/forum/#!forum/kubernetes-wg-cloud-provider but I wouldn't know it by looking at this repo.  I had to go searching in kubernetes-dev to uncover [this thread](https://groups.google.com/forum/#!searchin/kubernetes-dev/wg|sort:date/kubernetes-dev/iO0NXYodMsE/RMUkhX6vAAAJ) 

Who are the leads for this WG, when does it meet? etc.

**Comment by spiffxp** [comment]
/sig-aws
/sig-azure
/sig-openstack
/sig-gcp
Should there be a `wg` label for this?

**Comment by spiffxp** [comment]
/sig aws
/sig azure
/sig openstack
/sig gcp
Should there be a `wg` label for this?

**Comment by wlan0** [comment]
/assign wlan0 jagosan

@spiffxp Thanks for raising this issue. I'm co-leading this with @jagosan 

FYI, We meet every Wednesday at 10am PT 
Video call link: https://zoom.us/my/cloudprovider
Meeting notes: https://docs.google.com/document/d/1OZE-ub-v6B8y-GuaWejL-vU_f9jsjBbrim4LtTfxssw
Mailing list: https://groups.google.com/forum/#!forum/kubernetes-wg-cloud-provider

We have a area label

/area cloudprovider
