### ISSUE TITLE
Need update some links in docs of "devel"

### ISSUE THREAD

**Issue by xialonglee** [kubernetes/community#134]
I found that the docs of project path <code>kubernetes/docs/devel/</code> was imported to 
this project path <code>community/contributors/devel/</code>.
But some links should update in file devel/README.md :
<code>
It assumes some familiarity with concepts in the [User Guide](../user-guide/README.md) and the [Cluster Admin
Guide](../admin/README.md).
</code>
The links of User Guide and Cluster Admin Guide are  relative paths of "(../user-guide/README.md)" and "(../admin/README.md)", but the <code>kubernetes/docs/user-guide/</code> is not imported to this kubernetes community yet.
Though it's a minor problem... 
i think update the links to http://kubernetes.io/docs/user-guide/ and http://kubernetes.github.io/docs/admin/ is a good idea for perfection.

**Comment by bgrant0607** [comment]
cc @grodrigues3

**Comment by grodrigues3** [comment]
links looked fixed.  Thanks!

/close

**Comment by grodrigues3** [comment]
@fejta can you remind me why `/close` doesn't assign me and close the issue.   

Nit: /assign followed by /close doesn't work
