### ISSUE TITLE
Document advice about generation/observedGeneration for controllers

### ISSUE THREAD

**Issue by kargakis** [kubernetes/community#135]
Moved from https://github.com/kubernetes/kubernetes/issues/35036

For some kinds of controllers, it's important to know which generation the status is valid for. I don't think it's strictly needed for all controllers, but its worth some thought to determine whether it's easier to apply the rule for everyone or if that would cause unnecessary controller churn for meaningless changes.

Also, if you have multiple controllers working off the same object (service accounts as a for instance), then each individual one would need to manage their own observedGeneration.

**Comment by bgrant0607** [comment]
ref https://github.com/kubernetes/kubernetes/issues/14961, https://github.com/kubernetes/kubernetes/issues/7328

**Comment by kargakis** [comment]
We also need to document that controllers should not set owner refs when parents have been marked for deletion.
