### ISSUE TITLE
Document List of Organizations

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/community#1407]
I was attempting to look for a list of the GitHub organizations that are part of Kubernetes and couldn't find any form list. This caught my attention because of CLA checking and formalities. From the Prow configuration I captured:

* kubernetes
* kubernetes-incubator
* kubernetes-security

There are other organizations that exist including, but not limited to:

* kubernetes-ui
* kubernetes-client
* kubernetes-up-and-running
* kubernetes-incubator-retired
* kubernetes-digitalocean-terraform
* kubernetes-helm
* kubernetes-contrib

And... possibly others.

Are there any others aside from the top 3 that are part of the Kubernetes project?

**Comment by cblecker** [comment]
cc: @kubernetes/steering-committee

**Comment by dankohn** [comment]
For [DevStats](devstats.k8s.io), we do the following.

For data starting from 2015-01-01 it is:
https://github.com/cncf/devstats/blob/master/projects.yaml
Which lists organizations: "kubernetes,kubernetes-client,kubernetes-incubator,kubernetes-helm"
Before 2015-01-01 this is a special config:
https://github.com/cncf/devstats/blob/master/kubernetes/kubernetes.sh
It lists single repos (not orgs): "GoogleCloudPlatform/kubernetes,kubernetes,kubernetes-client"
The same repos "GoogleCloudPlatform/kubernetes,kubernetes,kubernetes-client" are also included for 2015-01-01 - 2015-08-14

If we're missing some, we'll correct.

**Comment by bgrant0607** [comment]
kubernetes-ui, kubernetes-up-and-running, kubernetes-digitalocean-terraform, and kubernetes-contrib are not ours.

**Comment by spiffxp** [comment]
I've been using https://github.com/kubernetes/community/issues/1527 to try and cover all repos that are part of this project.  Thus far I have opened PR's for all repos in:
- [kubernetes](https://github.com/kubernetes)
- [kubernetes-client](https://github.com/kubernetes-client)
- [kubernetes-helm](https://github.com/kubernetes-helm)
- [kubernetes-incubator](https://github.com/kubernetes-incubator)

Based on discussion above and some educated guesses from [this github user search](https://github.com/search?p=3&q=kubernetes-&type=Users&utf8=%E2%9C%93) it seems like I'm missing:
- [kubernetes-csi](https://github.com/kubernetes-csi)
- [kubernetes-graveyard](https://github.com/kubernetes-graveyard)
- [kubernetes-retired](https://github.com/kubernetes-retired)
- [kubernetes-ui](https://github.com/kubernetes-ui)

There are also a number of kubernetes-foo orgs that have no (public) repos or members, but I suspect we preemptively created, or are holding for future use.  Including, but not limited to:
- [kubernetes-addons](https://github.com/kubernetes-addons)
- [kubernetes-approvers](https://github.com/kubernetes-approvers)
- [kubernetes-apps](https://github.com/kubernetes-apps)
- [kubernetes-brigade](https://github.com/kubernetes-brigade)
- [kubernetes-charts](https://github.com/kubernetes-charts)
- [kubernetes-community](https://github.com/kubernetes-community)
- [kubernetes-contributors](https://github.com/kubernetes-contributors)
- [kubernetes-controllers](https://github.com/kubernetes-controllers)
- [kubernetes-demos](https://github.com/kubernetes-demos)
- [kubernetes-developers](https://github.com/kubernetes-developers)
- [kubernetes-ecosystem](https://github.com/kubernetes-ecosystem)
- [kubernetes-examples](https://github.com/kubernetes-examples)
- [kubernetes-extensions](https://github.com/kubernetes-extensions)
- [kubernetes-federation](https://github.com/kubernetes-federation)
- [kubernetes-incubator-retired](https://github.com/kubernetes-incubator-retired)
- [kubernetes-ingress](https://github.com/kubernetes-ingress)
- [kubernetes-internals](https://github.com/kubernetes-internals)
- [kubernetes-maintainers](https://github.com/kubernetes-maintainers)
- [kubernetes-owners](https://github.com/kubernetes-owners)
- [kubernetes-playground](https://github.com/kubernetes-playground)
- [kubernetes-providers](https://github.com/kubernetes-providers)
- [kubernetes-reviewers](https://github.com/kubernetes-reviewers)
- [kubernetes-security](https://github.com/kubernetes-security)
- [kubernetes-sidecars](https://github.com/kubernetes-sidecars)
- [kubernetes-testing](https://github.com/kubernetes-testing)
- [kubernetes-utils](https://github.com/kubernetes-utils)
- [kubernetes-tools](https://github.com/kubernetes-tools)
- [kubernetes-universe](https://github.com/kubernetes-universe)

And let's not forget [kubernetes-tacos](https://github.com/kubernetes-tacos)

**Comment by spiffxp** [comment]
There are also orgs for repos/subprojects I believe to be part of kubernetes that don't have "kubernetes-" in their name, eg:
- https://github.com/helm vs. https://github.com/kubernetes-helm
- https://github.com/kops vs. https://github.com/kubernetes/kops

**Comment by mattfarina** [comment]
For reference, Helm started out in the helm org. This is prior to the existence of the CNCF. Once helm became popular it was invited to merge with deployment manager in a new helm v2 that lived in the Kubernetes org. After that the CNCF was founded.

The helm org comes from the history of helm.

As far as I know, everything in the helm org aside from helm-www is obselete. helm-www is used to generate the helm.sh website.

**Comment by chrislovecnm** [comment]
@spiffxp I have not idea who owns https://github.com/kops  org ... @justinsb any idea?

**Comment by bgrant0607** [comment]
On Mon, Jan 1, 2018 at 5:49 PM, Aaron Crickenberger <
notifications@github.com> wrote:

> I've been using #1527
> <https://github.com/kubernetes/community/issues/1527> to try and cover
> all repos that are part of this project. Thus far I have opened PR's for
> all repos in:
>
>    - kubernetes <https://github.com/kubernetes>
>    - kubernetes-client <https://github.com/kubernetes-client>
>    - kubernetes-helm <https://github.com/kubernetes-helm>
>    - kubernetes-incubator <https://github.com/kubernetes-incubator>
>
> Based on discussion above and some educated guesses from this github user
> search
> <https://github.com/search?p=3&q=kubernetes-&type=Users&utf8=%E2%9C%93>
> it seems like I'm missing:
>
>    - kubernetes-csi <https://github.com/kubernetes-csi>
>
> Not ours, AFAIK. The one public member is not a storage SIG lead.

>
>    - kubernetes-graveyard <https://github.com/kubernetes-graveyard>
>    - kubernetes-retired <https://github.com/kubernetes-retired>
>    - kubernetes-ui <https://github.com/kubernetes-ui>
>
> kubernetes-ui isn't really ours, either.

>
>
> There are also a number of kubernetes-foo orgs that have no (public) repos
> or members, but I suspect we preemptively created, or are holding for
> future use. Including, but not limited to:
>
How did you find these OOC?

>
>    - kubernetes-addons <https://github.com/kubernetes-addons>
>
> Yes, squatting.

>
>    - kubernetes-approvers <https://github.com/kubernetes-approvers>
>
>
>    - kubernetes-apps <https://github.com/kubernetes-apps>
>
>
>    - kubernetes-brigade <https://github.com/kubernetes-brigade>
>
> Don't know about these 3.

>
>    - kubernetes-charts <https://github.com/kubernetes-charts>
>
> Yes, squatting.

>
>    - kubernetes-community <https://github.com/kubernetes-community>
>    - kubernetes-contributors <https://github.com/kubernetes-contributors>
>    - kubernetes-controllers <https://github.com/kubernetes-controllers>
>    - kubernetes-demos <https://github.com/kubernetes-demos>
>    - kubernetes-developers <https://github.com/kubernetes-developers>
>    - kubernetes-ecosystem <https://github.com/kubernetes-ecosystem>
>    - kubernetes-examples <https://github.com/kubernetes-examples>
>
> Don't know about any of the above.

>
>    - kubernetes-extensions <https://github.com/kubernetes-extensions>
>    - kubernetes-federation <https://github.com/kubernetes-federation>
>    - kubernetes-incubator-retired
>    <https://github.com/kubernetes-incubator-retired>
>
> Yes, squatting on these 3.

>
>    - kubernetes-ingress <https://github.com/kubernetes-ingress>
>    - kubernetes-internals <https://github.com/kubernetes-internals>
>    - kubernetes-maintainers <https://github.com/kubernetes-maintainers>
>    - kubernetes-owners <https://github.com/kubernetes-owners>
>    - kubernetes-playground <https://github.com/kubernetes-playground>
>
> Don't know about these.

>
>    - kubernetes-providers <https://github.com/kubernetes-providers>
>
> Squatting.

>
>    - kubernetes-reviewers <https://github.com/kubernetes-reviewers>
>
> Don't know about this one.

>
>    - kubernetes-security <https://github.com/kubernetes-security>
>
> Private.

>
>    - kubernetes-sidecars <https://github.com/kubernetes-sidecars>
>
> Squatting.

>
>    - kubernetes-testing <https://github.com/kubernetes-testing>
>
>
>    - kubernetes-utils <https://github.com/kubernetes-utils>
>
> Don't know.

>
>    - kubernetes-tools <https://github.com/kubernetes-tools>
>
> Squatting.

>
>    - kubernetes-universe <https://github.com/kubernetes-universe>
>
> And let's not forget kubernetes-tacos
> <https://github.com/kubernetes-tacos>
>
Don't know.

Also squatting on:
kubernetes-test

**Comment by idvoretskyi** [comment]
@mattfarina @spiffxp @bgrant0607 

FYI, I'm working on collecting all the GitHub organizations, that include the word "kubernetes" in their naming (to proceed with the further actions).

To reconfirm, all the orgs below are the "official" Kubernetes ones, right?

- [kubernetes](https://github.com/kubernetes)
- [kubernetes-client](https://github.com/kubernetes-client)
- [kubernetes-helm](https://github.com/kubernetes-helm)
- [kubernetes-incubator](https://github.com/kubernetes-incubator)
- [kubernetes-csi](https://github.com/kubernetes-csi)
- [kubernetes-graveyard](https://github.com/kubernetes-graveyard)
- [kubernetes-retired](https://github.com/kubernetes-retired)

cc @kubernetes/steering-committee @dankohn

**Comment by lukaszgryglicki** [comment]
This returns 645 users: https://github.com/search?utf8=✓&q=kubernetes&type=Users
And this returns 105: https://github.com/search?utf8=✓&q=kubernetes-&type=Users

But please take a look, it also searches for users tags, name, description etc.
So returned list contains all users (mean users or orgs) that has "kubernetes" anywhere in their profile.
This is not the orgs list
Attached screenshots:
![screen shot 2018-01-09 at 20 36 24](https://user-images.githubusercontent.com/2469783/34739545-e81a36ac-f57c-11e7-96db-4b88d2281b33.png)
![screen shot 2018-01-09 at 20 36 27](https://user-images.githubusercontent.com/2469783/34739546-e8361e12-f57c-11e7-85db-cefcef78e9e3.png)

I think this is the real list of orgs having kubernetes in their name.
Google BigQuery, analyses from 2014-01-01:
```
select
  org.login as org,
  count(1) as cnt
from
  [githubarchive:month.201801],
  [githubarchive:year.2017],
  [githubarchive:year.2016],
  [githubarchive:year.2015],
  [githubarchive:year.2014]
where
  LOWER(org.login) like '%kubernetes%'
group by
  org
order by
  cnt desc,
  org
;
```
Results are here (sorted by the number of events on a given org desc):
https://docs.google.com/spreadsheets/d/1DU0qSu3_DgWjWteEwGHF2MHKS-XmSyvuIpjQKP3BTA8/edit?usp=sharing

It returns 49 orgs.

**Comment by idvoretskyi** [comment]
Lukasz, thank you for pointing out.

**Comment by spiffxp** [comment]
I've heard no disagreement that these orgs are considered part of the project:
- [kubernetes](https://github.com/kubernetes)
- [kubernetes-client](https://github.com/kubernetes-client)
- [kubernetes-helm](https://github.com/kubernetes-helm)
- [kubernetes-incubator](https://github.com/kubernetes-incubator)

I am relatively confident this should be considered part of the project. eg: [this repo](https://github.com/kubernetes-csi/external-attacher) bills itself as part of the the Kubernetes implementation of CSI and has commits from a member of @kubernetes/sig-storage-*
- [kubernetes-csi](https://github.com/kubernetes-csi)

These orgs are part of the project, intended for code that is no longer maintained (goal is to replace "graveyard" with "retired")
- [kubernetes-graveyard](https://github.com/kubernetes-graveyard)
- [kubernetes-retired](https://github.com/kubernetes-retired)

Based on feedback from Brian, this is a private org that is part of the project:
- [kubernetes-security](https://github.com/kubernetes-security)

Based on feedback from Brian, we are squatting on these orgs:
- [kubernetes-addons](https://github.com/kubernetes-addons)
- [kubernetes-charts](https://github.com/kubernetes-charts)
- [kubernetes-extensions](https://github.com/kubernetes-extensions)
- [kubernetes-federation](https://github.com/kubernetes-federation)
- [kubernetes-incubator-retired](https://github.com/kubernetes-incubator-retired)
- [kubernetes-providers](https://github.com/kubernetes-providers)
- [kubernetes-sidecars](https://github.com/kubernetes-sidecars)
- [kubernetes-test](https://github.com/kubernetes-test)
- [kubernetes-tools](https://github.com/kubernetes-tools)

I recently created orgs corresponding to ours sigs, so we are squatting on:
- [kubernetes-sig-foo](https://github.com/kubernetes-sig-foo) for many values of foo

**Comment by mattfarina** [comment]
@spiffxp aside from the sig specific ones, shall I update #1569 with the rest? Only being conservative on the sig ones until the steering committee makes a call on a proposal for those.

**Comment by idvoretskyi** [comment]
@lukaszgryglicki any idea why some organizations (eg. `kubernetes-sig-foo`, as @spiffxp mentioned) are not returned after your query?

**Comment by idvoretskyi** [comment]
Based on the spreadsheet by @lukaszgryglicki, I've create a spreadsheet to track the "*kubernetes*" orgs on GitHub - https://docs.google.com/spreadsheets/d/1MQwsWGuQvJc_RepCFgQ9HleQD2m3-_2k8utGcPaVHKY/edit#gid=289132963

@spiffxp - can you please review and update if needed?

**Comment by lukaszgryglicki** [comment]
should I update DevStats config (https://github.com/cncf/devstats/blob/master/projects.yaml#L6) when this is approved, confirmed and made official, right?

**Comment by spiffxp** [comment]
I discussed this during sig-architecture meeting this morning.  I would like to have sign off from @bgrant0607 on whether we have captured the list of orgs that are part of the project today, and I need help from @thockin to further collect the list of orgs we are squatting on today.

**Comment by idvoretskyi** [comment]
I've shared the spreadsheet above with the @kubernetes/steering-committee. @spiffxp @thockin @bgrant0607 can you update it if you have any extra data?

**Comment by idvoretskyi** [comment]
@lukaszgryglicki yes, please.

**Comment by bgrant0607** [comment]
@spiffxp Do you agree the spreadsheet is what I should update and sign off on?

**Comment by bgrant0607** [comment]
The list here: https://github.com/kubernetes/community/issues/1407#issuecomment-356445729
looks right to me, and I updated the spreadsheet to match that (modulo formatting).

kubernetes-incubator-retired and kubernetes-graveyard should be folded into kubernetes-retired

**Comment by mattfarina** [comment]
I'll update the PR based on that list.

**Comment by thockin** [comment]
I am squatting on a lot, but it's not obvious to me how to get a list...

**Comment by bgrant0607** [comment]
@thockin 

https://github.com/thockin

you should see icons for all your orgs under Organizations on the lower left. Hover over the icons

**Comment by cblecker** [comment]
@thockin @bgrant0607 They're also listed on https://github.com/settings/organizations for the logged in user

**Comment by idvoretskyi** [comment]
@thockin and feel free to update https://docs.google.com/spreadsheets/d/1MQwsWGuQvJc_RepCFgQ9HleQD2m3-_2k8utGcPaVHKY/edit#gid=289132963

**Comment by spiffxp** [comment]
I would like to see us PR in the list of orgs we're squatting on with instructions to contact steering@kubernetes.io, instead of using a spreadsheet as the source of truth

**Comment by mattfarina** [comment]
We shouldn't have community documentation in a spreadsheet as folks can't search for it. +1 for a PR with that direction from @spiffxp

**Comment by idvoretskyi** [comment]
@spiffxp I can submit a PR. Where is the best place for it?

**Comment by idvoretskyi** [comment]
PTAL https://github.com/kubernetes/community/pull/1754

**Comment by idvoretskyi** [comment]
@mattfarina is it effectively fixed by https://github.com/kubernetes/community/pull/1923?

**Comment by mattfarina** [comment]
I think this can be considered closed now. Any additional changes can happen separately from this issue.

/close
