### ISSUE TITLE
Add documentation to assist with First Time Contributors troubleshooting CLA bot problems

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/community#1410]
A lot of first-time contributors have this experience:

1. push a PR
1. the bot adds the note they have not signed the CLA
1. they go sign the CLA
1. they next scratch there head on why the bot has not updated there PR

It would be helpful to link a doc on how to troubleshoot an issue with the CLA bot.

1. you have to have a matching email address in your git commit.  Many people use different email addr when signing the CLA
1.  git commit --amend --reset-author
1. git push

/sig contribex

**Comment by tpepper** [comment]
s/have to have/must have/

Also suggest calling out the specific config fixing commands when you're in a k8s repository, eg:
* git config user.name "Mona Lisa"
* git config user.email "mlisa@example.com"
(or for all your repos by adding also "--global" on those command lines).
