### ISSUE TITLE
code-of-conduct.md

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/community#1414]
We seem to reference the code-of-conduct but we do not actually have a file in here.  https://github.com/kubernetes/kubernetes/blob/master/code-of-conduct.md

/assign @sarahnovotny

Any reason for that?  It is part of the base template for Kubernetes GitHub projects.

**Comment by xiangpengzhao** [comment]
Seems like all of the CNCF projects reference to CNCF Code of Conduct currently.
For example:
https://github.com/containernetworking/cni/blob/master/CODE-OF-CONDUCT.md
https://github.com/prometheus/prombench/blob/master/code-of-conduct.md
https://github.com/fluent/fluentd/blob/master/code-of-conduct.md

xref:
https://github.com/cncf/foundation/issues/2
https://github.com/kubernetes/kubernetes/pull/35142

/cc @dankohn

**Comment by chrislovecnm** [comment]
/assign @parispittman 

Does someone want me to PR?  @dankohn who is the legal guru that lays this stuff out?

**Comment by xiangpengzhao** [comment]
>@dankohn who is the legal guru that lays this stuff out?

I'm not sure, but I guess @dankohn has some more contexts.

**Comment by dankohn** [comment]
I believe this is working as designed. We want the K8s CoC to cite by reference the CNCF CoC, just as the other 13 CNCF-hosted projects do. That way, if and when we revise the CoC in the future, all CNCF projects will automatically be updated. 

Of course, we won’t change the CoC without first getting buy-in from the maintainers of all of the projects. 

Can we close the issue?

**Comment by chrislovecnm** [comment]
we do not have the file @dankohn in this repo :)

**Comment by cblecker** [comment]
You mean adding it to the kubernetes/community repo itself?

**Comment by chrislovecnm** [comment]
correct we do not have the file in this repo, and we should ...

**Comment by chrislovecnm** [comment]
Let me PR it and we can discuss on the PR ... 😆

**Comment by xiangpengzhao** [comment]
>we do not have the file @dankohn in this repo :)

Oh, sorry for my incorrect wording. I didn't mean this :)

@dankohn I'm so sorry about this.

**Comment by chrislovecnm** [comment]
Hey my English was horrible on that comment, I am surprised anyone understood that comment

**Comment by chrislovecnm** [comment]
@xiangpengzhao see https://github.com/kubernetes/community/pull/1457

**Comment by xiangpengzhao** [comment]
@chrislovecnm haha, I believe I misunderstood around :)
