### ISSUE TITLE
Support namespace listing based on kubernetes rolebindings or clusterrolebindings

### ISSUE THREAD

**Issue by traghave** [kubernetes/community#1486]
Whenever I perform 'kubectl get namespace'
I either get all the namespacelist or none based based on the resource type "namespaces" added to the kubernetes roles.

Is there any way where I'll get the authorized namespace list when any user does "kubectl get namespaces"

**Comment by traghave** [comment]
@kubernetes/sig-contributor-experience-feature-requests

**Comment by traghave** [comment]
Scenario 1:

When I try with below yaml

++++++++++++++++++++++++++++++++++++++++++++++++++
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespaceList
rules:
- apiGroups: [""] # "" indicates the core API group
  resourceNames: ["default", "kube-system", "kube-public"]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]

++++++++++++++++++++++++++++++++++++++++++++++

and the binding yaml as below
++++++++++++++++++++++++++++++++++++++++++++++

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespaceListBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespaceList
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: https://master:9443/oidc/endpoint/OP#user1

++++++++++++++++++++++++

when i do get namespaces it throws error 

# kubectl get ns
Error from server (Forbidden): namespaces is forbidden: User "https://master:9443/oidc/endpoint/OP#user1" cannot list namespaces at the cluster scope

++++++++++++++++++++++++++

**Comment by traghave** [comment]
but when i try to set the clusterrolebiding with namespace resource, it will list all namespaces but not just the namespaces the user is authorized to.

+++++++++++++++++++++++++++
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespaceListBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespaceList
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: https://mycluster.icp:9443/oidc/endpoint/OP#shajeer
+++++++++++++++++++++++++++

and get namespaces list all namespaces

>> kubectl get ns
NAME          STATUS    AGE
default       Active    5d
kube-public   Active    5d
kube-system   Active    5d
platform      Active    4d
services      Active    4d

+++++++++++++++++++++++++++++

Could you help how i can restrict the list of namespaces returned using kubernetes role/rolebindings.

**Comment by liggitt** [comment]
What you are describing is acl-filtered list, which is desired, but not able to be implemented without breaking watch semantics. If the content of a list call depends on two dimensions (actual resources present AND current state of ACL), a single resourceVersion will not represent the results correctly.

Additionally, if the API server does not have a way to know when ACLs have changed, it does not know when to react by sending add events for newly granted resources or remove events for newly denied resources)

There are a couple related issues or projects:

* https://github.com/openshift/kube-projects is an add-on API server that can be aggregated in that exposes the behavior you are looking for (`kubectl get projects` shows ACL-filtered namespaces based on RBAC permissions). It does best-effort watch support, but still has the issues described above, and only works with the RBAC authorizer.

https://github.com/kubernetes/kubernetes/issues/40403 discusses possible API approaches toward improving the ability to discover or watch specific resources
