### ISSUE TITLE
Community office hours should be added to calendar

### ISSUE THREAD

**Issue by rothgar** [kubernetes/community#15]
I randomly found The [community office hours](https://www.youtube.com/watch?v=nKHYnvTr7LE) video from [@sarahnovotny's retweet](https://twitter.com/surajd_/status/748091857071026176)

They should be added to the [shared calendar](https://calendar.google.com/calendar/embed?src=cgnt364vd8s86hr2phapfjc6uk%40group.calendar.google.com&ctz=America/Los_Angeles) so people can get involved, ask questions, etc.

**Comment by sarahnovotny** [comment]
aaah!  i'd added them to the community events, not community meetings calendar.  I'll be sure to add them to both next time. thanks for the reminder.
