### ISSUE TITLE
2 vagrant.md exists

### ISSUE THREAD

**Issue by lichen2013** [kubernetes/community#150]
We have 2 vagrant.md file:
contributors/devel/developer-guides/vagrant.md
contributors/devel/local-cluster/vagrant.md

They're very much alike, I think we should maintaine only one, and remove the other one.

**Comment by jessfraz** [comment]
would you be willing to submit a pull request to combine both of these with a redirect to the other, I agree this is redundant

**Comment by lichen2013** [comment]
This should been fixed by commit  [Clean up contributors/devel docs](https://github.com/kubernetes/community/commit/acd6a3ce2f9306770b3ae8e39c3330f51f538275).
