### ISSUE TITLE
README.md needs to be rescoped and rewritten

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#1516]
Part of #1413

There will now be duplicated content in the README and the contributor guide, we need to decide what's appropriate to put there, what cross-linking is appropriate, and what we should cut out.

/sig contributor-experience

**Comment by castrojo** [comment]
Looking at this I think we need to get more things in place before we revise this document, it's pointing to a bunch of resources and removing it now doesn't make sense until we have a nicer replacement. Perhaps revist this in a few week.

**Comment by nikhita** [comment]
@guineveresaenger Should this be closed? I'm not sure if https://github.com/kubernetes/community/pull/1807 addresses this completely.

**Comment by guineveresaenger** [comment]
I support this closing, since the related PR merged. @nikhita any objections?

**Comment by nikhita** [comment]
> There will now be duplicated content in the README and the contributor guide, we need to decide what's appropriate to put there, what cross-linking is appropriate, and what we should cut out.

@guineveresaenger yeah, I think this de-duplication is fixed so it should be fine to close this. :+1:
