### ISSUE TITLE
Create 'help wanted' guidelines page

### ISSUE THREAD

**Issue by cblecker** [kubernetes/community#1522]
The guidelines for a 'help wanted' issue need to be documented. They are outlined in Brian's comment here: https://github.com/kubernetes/community/issues/860#issuecomment-321861134

We should create a document at `contributors/devel/help-wanted.md` outlining these points.

**Comment by nikhita** [comment]
The irony of this issue having the `help wanted` label :)

**Comment by chrislovecnm** [comment]
The problem is they are not help wanted issues. We need good first contribution label which I think we have. Is a title change for this issue appropriate?

**Comment by cblecker** [comment]
Fixed in #1532
