### ISSUE TITLE
Refer to kubernetes/community as authoritative source for code of conduct

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#1527]
There are miscellaneous copies of a code-of-conduct.md file scattered across repos in kubernetes and kubernetes-incubator.  I'd like to change them to a redirect to the code-of-conduct.md file living in this repo as the authoritative source.

```
kubernetes/cluster-registry/code-of-conduct.md
kubernetes/community/code-of-conduct.md
kubernetes/dns/code-of-conduct.md
kubernetes/frakti/code-of-conduct.md
kubernetes/gengo/code-of-conduct.md
kubernetes/git-sync/code-of-conduct.md
kubernetes/heapster/code-of-conduct.md
kubernetes/helm/code-of-conduct.md
kubernetes/ingress-nginx/code-of-conduct.md
kubernetes/k8s.io/code-of-conduct.md
kubernetes/kompose/code-of-conduct.md
kubernetes/kops/code-of-conduct.md
kubernetes/kubeadm/code-of-conduct.md
kubernetes/kubectl/code-of-conduct.md
kubernetes/kubernetes-template-project/code-of-conduct.md
kubernetes/metrics/code-of-conduct.md
kubernetes/minikube/code-of-conduct.md
kubernetes/perf-tests/code-of-conduct.md
kubernetes/utils/code-of-conduct.md
kubernetes-incubator/bootkube/code-of-conduct.md
kubernetes-incubator/client-python/code-of-conduct.md
kubernetes-incubator/cluster-proportional-autoscaler/code-of-conduct.md
kubernetes-incubator/cluster-proportional-vertical-autoscaler/code-of-conduct.md
kubernetes-incubator/cri-containerd/code-of-conduct.md
kubernetes-incubator/cri-o/code-of-conduct.md
kubernetes-incubator/cri-tools/code-of-conduct.md
kubernetes-incubator/custom-metrics-apiserver/code-of-conduct.md
kubernetes-incubator/descheduler/code-of-conduct.md
kubernetes-incubator/external-dns/code-of-conduct.md
kubernetes-incubator/external-storage/code-of-conduct.md
kubernetes-incubator/ip-masq-agent/code-of-conduct.md
kubernetes-incubator/kube-arbitrator/code-of-conduct.md
kubernetes-incubator/kube-aws/code-of-conduct.md
kubernetes-incubator/kubespray/code-of-conduct.md
kubernetes-incubator/metrics-server/code-of-conduct.md
kubernetes-incubator/nfs-provisioner/code-of-conduct.md
kubernetes-incubator/node-feature-discovery/code-of-conduct.md
kubernetes-incubator/rktlet/code-of-conduct.md
kubernetes-incubator/service-catalog/code-of-conduct.md
kubernetes-incubator/spartakus/code-of-conduct.md
```

See https://github.com/kubernetes/kubernetes-template-project/pull/13 for an example of what I'd like to use

There is also the question of whether repos that currently lack a code-of-conduct.md should have one. 

/assign
/sig contributor-experience

**Comment by jbeda** [comment]
SGTM

**Comment by cblecker** [comment]
I support this 👍

**Comment by spiffxp** [comment]
PR's have been opened for all kubernetes and kubernetes-incubator repos.  I also went ahead and did this for all kubernetes-client repos.  

Do all of these repos represent the complete set of projects that are covered by our code of conduct, or have I left something out?

**Comment by spiffxp** [comment]
@kubernetes/kubernetes-staging-publish-cops have I done this correctly for repos that are published from kubernetes/kubernetes/staging?  I assumed I should PR directly into the repos that are published from there

eg: I PR'ed into https://github.com/kubernetes/client-go since its root contains more files than live in  https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go

**Comment by sttts** [comment]
> I assumed I should PR directly into the repos that are published from there

Into k/k's staging/ please, not into the single repos.

**Comment by spiffxp** [comment]
Opened PR's against kubernetes-helm/* repos as well per https://groups.google.com/a/kubernetes.io/forum/#!topic/steering/p1mquHULobQ

**Comment by cblecker** [comment]
56 open, 10 closed without merge, 21 merged, 87 total. Maybe they'll all be done by 1.10? ;)

**Comment by spiffxp** [comment]
Opened PR's against all repos in kubernetes-ui and kubernetes-csi

**Comment by spiffxp** [comment]
Closing kubernetes-ui PR's

**Comment by spiffxp** [comment]
Have pinged on all remaining open PR's

**Comment by spiffxp** [comment]
/close
All remaining open PR's have been merged.  I updated instructions in the kubernetes-template-project to refer to this code of conduct file.  https://github.com/kubernetes/kubernetes-template-project/pull/14
