### ISSUE TITLE
incorrect wording

### ISSUE THREAD

**Issue by jpoley** [kubernetes/community#1538]
you have it listed as on premise.  a premise is a thought or idea, what is meant is premises.  not exactly the same thing, and this mistake is very common.

https://github.com/kubernetes/community/blob/master/sig-list.md#master-sig-list

**Comment by cblecker** [comment]
@kubernetes/sig-onprem-misc

**Comment by vbmade2000** [comment]
@cblecker Let me work on that if you don't mind.

**Comment by nikhita** [comment]
@vbmade2000 Are you still interested in working on this?

**Comment by vbmade2000** [comment]
@nikhita Apology for delay. Thanks for reminder. I'll create PR asap.

**Comment by vbmade2000** [comment]
I think it requires corrections in more than sig-list.md

**Comment by cblecker** [comment]
fixed in #2025
