### ISSUE TITLE
Proposal: Allow TerminationMessagePath to be more useful to arbitrary software

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/community#154]
TerminationMessagePath on containers is a mechanism to allow a container to write a useful, human or machine readable message to a file in the container that will be surfaced via the pod container status after container termination.  This data can then be displayed in a UI (to know what the result of a job or server crash was) or gathered by an API client to perform analysis on the reasons containers crash/stop/complete.

Today, it is hard for arbitrary software (images taken at random from DockerHub, general software web frameworks) to populate the termination message path, because the idea of writing to a known file on termination is a fairly unusual concept.  Like health checks, many "normal" applications have no mechanism to perform this function, which means the value of the platform is diminished.  In Kubernetes, we traditionally recognize this as an "adaptation" problem - to show value, we meet users and software where they are by providing helpful affordances to leverage the value without having to change their software.

To better realize the value of terminationMessagePath for the broad range of software, Kubernetes should:

1. Allow log output to be a candidate for the termination message
2. Allow a large class of users to benefit from log based termination messages without requiring all applications to specify they want log output directly
3. Preserve behavior for terminationMessagePath-aware applications (a client using termination message path today may expect the resulting message to *only* contain the contents of message path logs).

Because of 3, we cannot change the semantics of terminationMessagePath to include log output if the terminationMessagePath file is empty after pod termination - that would result in a behavior change.  We *could* support a new field on container that defaults to true to include logs on empty message path - that would allow a client to opt out, but may be considered a breaking change.

Proposed change:

```
type Container struct {
  ... 
  TerminationMessagePath string `json:"terminationMessagePath"`
  // NEW: UseLogsForTerminationMessage if true indicates that an empty termination message file will be populated with the recent logs from the container.
  UseLogsForTerminationMessage *bool
}
```

Users could then opt in to this behavior (and we would encourage that to happen via `kubectl run`, Helm, OpenShift templates and new-app, and docs) to populate UIs.

**Comment by smarterclayton** [comment]
@kubernetes/sig-apps @bgrant0607 @kubernetes/rh-ux @kubernetes/sig-cli leveraging termination message path in UIs is a clear win for users and provides richer debug tools in simple cases.  This would enable us to make use of termination message more widespread and also support software that does not know about terminationMessagePath.

**Comment by erictune** [comment]
+1

**Comment by erictune** [comment]
Controllers and/or UIs should aggregate termination messages to show "recent" or "frequent" termination messages.

Since we need to aggregate events about pods of a controller too, maybe the termination message should be part of a Pod termination Event message.

**Comment by enisoc** [comment]
How much of the log will be *tail*ed? Would it make sense to specify a `TerminationMessageLogLines` count instead of a boolean?

**Comment by bgrant0607** [comment]
I am in favor.

There will need to be a hardcoded byte limit in addition to or instead of a line limit.

FYI @kubernetes/sig-node

**Comment by erictune** [comment]
It is useful to be able to extract a limited cardinality snippet from the
TerminationMessage to allow for grouping, while also providing a more
detailed, specific message. (like Reason and Message in events).  Is it
reasonable to allow users to provide both types of messages or is that
asking too much?

**Comment by erictune** [comment]
Okay, so all of that is too big to fit in an event message.

**Comment by smarterclayton** [comment]
I have a separate PR that will be part of this proposal to limit number of bytes for container termination message.  I think the limit has to be around 5-15k because we have a hard limit in etcd and size is very important.  Algorithm would probably be max size / containers per container.

**Comment by smarterclayton** [comment]
The limit has to apply to both the file and the log lines, so I'd prefer a byte limit (hardcoded at first with some flexibility across the pod) that applies to both.  Right now you can destroy an api server and kubelet by writing a sufficiently long termination message, which we have to fix.

**Comment by smarterclayton** [comment]
For size:

The current experimental is 4096 bytes per container. That's potentially a lot. I think 20-40 lines of backtrace in a normal log file would provide a fair amount of context, which is probably ~1600 bytes on average. For termination files, we would want to accept more, since every byte belongs to something the user intends to send. Overall, we can't accept more than probably 5k-20k per pod (the upper end of that range might be 5-10x the average pod size).

How about for simplicity sake we apply the following limits:

1. For reading logs we read 2k bytes or 40 lines, whichever is smaller (from the end of the logs)
2. For termination logs we allow up to 4k bytes (from the beginning of the file)
3. If all container messages take up more than 12k bytes, we truncate messages proportionally from the beginning of the message (rather than doing something more complicated which mixes beginning and end truncation).

All of those limits would be imposed at the kubelet, but mentioned in the API docs.

**Comment by bamb00** [comment]
Will this make it into 1.5.4 or 1.6.x? Is there documentation or examples for these new features?
Thanks.

**Comment by bamb00** [comment]
Ooops! Just saw the new field terminationMessagePolicy in the 1.6 API references.

**Comment by bgrant0607** [comment]
@smarterclayton Can this be closed?

**Comment by smarterclayton** [comment]
Yes it was implemented.

**Comment by sudheerpodila** [comment]
I am using below configuration to log the abrupt disruption in pods using terminationMessagePath as terminationMessagePath: /tmp/message-log and terminationmessagePolicy as terminationMessagePolicy: FallbackToLogsOnError
but when the pods are getting restarted I am just seeing the path getting created as:
-rw-rw-rw- 1 root root 0 Sep 12 18:13 message-log

but file size is always of 0 byte.
Is this a bug in k8 version EKS 1.19
