### ISSUE TITLE
Develop documentation for creating a new API server

### ISSUE THREAD

**Issue by pmorie** [kubernetes/community#155]
One fundamental primitive in the Kubernetes world is the API server.  The process for creating a new API server should be as accessible and simple as possible, and work is being done to facilitate this currently.  This issue is to begin documenting the process of creating a new API server at a conceptual and applied level (where practical).  This area is in active development and the documentation will need to be kept up to date. I suggest that this issue be scoped to bootstrapping the documentation, after which, the maintainers of this area should provide upkeep.

I know that @MHBauer has some notes from his recent efforts in SIG service-catalog.

cc @kubernetes/sig-api-machinery

**Comment by duglin** [comment]
There's also this: https://github.com/kubernetes/kubernetes/blob/master/docs/devel/adding-an-APIGroup.md

**Comment by pmorie** [comment]
@duglin That is for adding a new API group to an existing API server.  We probably need something eventually that ties everything together in the form of:

1.  How to make an API server
2.  Conventions for API objects (now that you have a server)
3.  How to add a new API group

**Comment by markyjackson-taulia** [comment]
@vishakhanihore This also falls under #3064

**Comment by mrbobbytables** [comment]
Is this still relevant? It's been open and frozen for some time now.
I'm going to mark it as rotten for now, if it should be left open please update or re-freeze it 👍  

/remove-lifecycle frozen
/lifecycle rotten
