### ISSUE TITLE
Remove "outside collaborator" role in favor of lowering requirements for "member" role

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#1565]
ref: https://github.com/kubernetes/community/pull/1330#issuecomment-355467738

The additional role makes the contributor ladder more complicated.  It's also just as much if not more effort to administer the role, and more difficult to audit across repos and orgs.

The only real benefit the additional role adds is constraining people's ability to use certain commands to specific repos instead of all repos in the org they're a member of (eg: /lgtm, /close, /assign).  

When discussed during a sig-contribex meeting, there was agreement on simplifying and cutting the role.  Unfortunately, this agreement didn't land in meeting notes, and I haven't seen the video recording hit youtube yet.

I think we could benefit from a survey of where and how extensively the role is used today across kubernetes/* and kubernetes-incubator/* repos.  This is something only people with... write? admin? access to said repos can do.  But IMO anyone is free to tackle modifying community-membership.md and I'm happy to review PR's to that effect.

FYI @kubernetes/sig-contributor-experience-proposals

**Comment by idvoretskyi** [comment]
This makes sense to me.

**Comment by cblecker** [comment]
I agree with this. One question though.. what about the member requirements would need to be lowered? I think it's a pretty easier bar for people to meet.

**Comment by thockin** [comment]
I am naturally anxious about this, but I have been chided for being a little too control-oriented, so I am willing to let the collective wisdom prevail.

**Comment by grodrigues3** [comment]
@parispittman I think you might have recorded last week's contribx.  Can you please upload to youtube?  Yeah, I believe the general consensus was to phase out the collaborator role.

**Comment by philips** [comment]
Is there currently anyone that holds this role? If not seems OK to me.

**Comment by bgrant0607** [comment]
"Outside collaborator" was not intended to be a rung in the contributor ladder. It's a github construct. A number of repos, most notably helm, add outside collaborators as a way to bypass the need for org membership and to manage their own permissions.

My current thinking is that org member, outside collaborator, and maintainer should be removed from the ladder and moved to a github governance doc.

**Comment by bgrant0607** [comment]
There are 16 outside collaborators on helm, but it looks like they could all be added to the repo teams: https://github.com/kubernetes/helm/settings/collaboration

I know there are some on other repos, which also were added before we had a membership process.

**Comment by bgrant0607** [comment]
A couple pages of collaborators here:
https://github.com/orgs/kubernetes/outside-collaborators?page=1&query=&utf8=%E2%9C%93
