### ISSUE TITLE
Propose replacing github label priority/failing-test with kind/failing-test

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#1579]
As CI Signal Lead for 1.9 I often found myself filing issues with `priority/critical-urgent` `priority/failing-test`.  Having two priorities assigned to an issue seems... weird.  I think the idea was to encourage folks to prioritize failing tests as the most important thing.  I'm not sure how well that has worked in practice.

It would make more sense to me if we called it `kind/failing-test`, to separate from `kind/bug` or `kind/flake`.  I could then say that https://github.com/kubernetes/test-infra/issues/6095 holds true, that an issue should only ever have one priority label applied to it.

I went digging through devstats and maybe it hurts my case.  It does look like `priority/failing-test` issues get closed a little more quickly than `priority/critical-urgent` issues.  That said, I would argue it comes from effectively triaging failing tests into a bucket, not so much that the bucket has the word "priority" in it.
- [issues age|repo:kubernetes priority/failing-test](https://k8s.devstats.cncf.io/dashboard/db/issues-age?orgId=1&from=now-2y&to=now&var-period=w&var-repogroup_name=Kubernetes&var-repogroup=kubernetes&var-sig_name=All&var-kind_name=All&var-prio_name=failing-test&var-sig=all&var-kind=all&var-prio=failing_test)
- [issues age|repo:kubernetes priority/critical-urgent](https://k8s.devstats.cncf.io/dashboard/db/issues-age?orgId=1&var-period=w&var-repogroup_name=Kubernetes&var-repogroup=kubernetes&var-sig_name=All&var-kind_name=All&var-prio_name=critical-urgent&var-sig=all&var-kind=all&var-prio=critical_urgent&from=now-2y&to=now)
- [issues age|repo:kubernetes](https://k8s.devstats.cncf.io/dashboard/db/issues-age?orgId=1&from=now-2y&to=now&var-period=w&var-repogroup_name=Kubernetes&var-repogroup=kubernetes&var-sig_name=All&var-kind_name=All&var-prio_name=All&var-sig=all&var-kind=all&var-prio=all)
- [issues age|repo:kubernetes kind/bug priority/failing-test](https://k8s.devstats.cncf.io/dashboard/db/issues-age?orgId=1&from=now-2y&to=now&var-period=w&var-repogroup_name=Kubernetes&var-repogroup=kubernetes&var-sig_name=All&var-kind_name=bug&var-prio_name=failing-test&var-sig=all&var-kind=bug&var-prio=failing_test)
- [issues age|repo:kubernetes kind/bug priority/crticial-urgent](https://k8s.devstats.cncf.io/dashboard/db/issues-age?orgId=1&from=now-2y&to=now&var-period=w&var-repogroup_name=Kubernetes&var-repogroup=kubernetes&var-sig_name=All&var-kind_name=bug&var-prio_name=critical-urgent&var-sig=all&var-kind=bug&var-prio=critical_urgent)
- [issues age|repo:kubernetes kind/bug](https://k8s.devstats.cncf.io/dashboard/db/issues-age?orgId=1&from=now-2y&to=now&var-period=w&var-repogroup_name=Kubernetes&var-repogroup=kubernetes&var-sig_name=All&var-kind_name=bug&var-prio_name=All&var-sig=all&var-kind=bug&var-prio=all)

ref: trying to make github issue labels more sane kubernetes/kubernetes#57911

WDYT? @kubernetes/sig-contributor-experience-misc-use-only-as-a-last-resort

**Comment by tpepper** [comment]
While one might argue simply that all tests must pass and any failure is gating, failing test and criticality are orthogonal to me here especially in light of your discussion in the SIG-testing session at KubeCon: if there are highly fail-likely scenarios that go unaddressed for a long time, those will dilute or confuse critical prioritization.  The proposal makes sense.

Do you see kind/flake as probably a second level triage assessment?  For example a kind/failing-test is probably the first determination, and then with some more understanding of variability of the test's outcome it gets further classified as a flake?  I suppose there's utility in having both.

**Comment by spiffxp** [comment]
Personally I would probably use `kind/failing-test` when the test has failed N runs in a row, vs. `kind/flake` when the test is flipping back and forth between passing/failing.  I had some ~sleep~ human-induced hysteresis when it came to opening issues against test failures.

**Comment by cblecker** [comment]
Opened https://github.com/kubernetes/test-infra/pull/6642 to actually do this.

**Comment by jberkus** [comment]
@cblecker you opened a PR for this, then closed it.  How were you planning to proceed from here?  I'd like to get this settled.

**Comment by spiffxp** [comment]
Note to self: none of the devstats links work anymore, I think the dashboard got renamed

**Comment by spiffxp** [comment]
/assign
I'm interested in reducing CI Signal toil, I'll aim to have a rollout proposal out next week

**Comment by jberkus** [comment]
Ah, I was going to write one up today, but am happy to wait for you.

**Comment by spiffxp** [comment]
Opening PR's to change docs per https://github.com/search?q=org%3Akubernetes+priority%2Ffailing-test&type=Code

**Comment by spiffxp** [comment]
kubernetes-dev thread asking for comment: https://groups.google.com/d/msg/kubernetes-dev/W_LfpE1iGlE/o8-M_J5xBgAJ

Will roll out sometime after 3pm PT Wed 7/25 if I hear no objections

**Comment by bgrant0607** [comment]
The reason I proposed priority/failing-test originally was because the auto-filing bot was DoSing other priority labels, and the issues were piling up without action -- clearly they weren't being treated as urgent, and many weren't actually urgent. 

If the issues are being filed by humans and are actually treated as urgent, it's fine to use other priorities.

**Comment by spiffxp** [comment]
I've removed holds from the linked PR's.  Will e-mail out once I see the label_sync has happened

**Comment by spiffxp** [comment]
Migration complete:
- [org:kubernetes label:priority/failing-test](https://github.com/issues?utf8=%E2%9C%93&q=org%3Akubernetes+label%3Apriority%2Ffailing-test+) - 0 results
- [org:kubernetes label:kind/failing-test](https://github.com/issues?utf8=%E2%9C%93&q=org%3Akubernetes+label%3Akind%2Ffailing-test+) - 25 open

/close
