### ISSUE TITLE
API Machinery SLIs/SLOs - Watch latency

### ISSUE THREAD

**Issue by zcahana** [kubernetes/community#1582]
[discussion moved from [google docs](https://docs.google.com/document/d/1Q5qxdeBPgTTIXZxdsFILg7kgqWhvOwY8uROEf0j5YBw/edit?ts=5a54e869#heading=h.8ftey72as5p) regarding the [API Machinery SLIs/SLOs for watch latency](https://github.com/kubernetes/community/blob/master/sig-scalability/slis/apimachinery_slis.md#watch-latency)]

@zcahana:
> Would it be reasonable to extend this definition (perhaps as SLI2) to measure the e2e watch latency, i.e. from the moment a POST/PUT/PATCH/DELETE is invoked, and until the corresponding watch notification is sent to each/all watchers?
>
>This would allow to reason about the latencies perceived both by individual watchers, and by the entire system.
>
>A derived SLO, if defined, can place a bound on latency, depending on the number of watchers.

@wojtek-t:
> Re this particular thing: I'm open to suggestions, but it's not easy to do in general. First: when does it start? I imagine that when the request reaches apiserver (which already makes it not really e2e). Second, how would you like to solve the problem of HA setups and clock skew.

@zcahana:
> Regarding "when does it start":
Ideally we'd start measuring when the client issues the API call, but obviously that requires some synchronization - of the clocks, a well as correlating the timestamps recorded at client/server sides.
If that turns up too complex, we can start measuring when the API server receives the request. That's indeed "less" e2e-ish, but anyway the dominant factor is expected to be the time it takes to disseminate the watch notification to the watchers.
>
> Regarding clock skews:
(handwaving) I guess we can use NTP to get a milliseconds-order synchronization in an HA setup, which is probably accurate enough for the subject matter, given the expected latencies at scale.

@wojtek-t:
> We don't require users to have any kind of NTP. And we don't want ot introduce this requirement to make some metrics reliable.

@zcahana:
> I probably misunderstood your question about clock skews. My answer was with respect to how we setup the test environment, involving multiple servers, such that their clocks are "synchronized enough" so we can derive durations (latencies) from start/end timestamps reported from different servers. That doesn't impose any requirements on users - only on the test setup.

**Comment by zcahana** [comment]
I've tried tagging @kubernetes/sig-scalability, but it's invisible to me.

**Comment by wojtek-t** [comment]
We want to be able to measure the SLO in live clusters too, not just in tests.

**Comment by zcahana** [comment]
So, if we can't relax the requirement to measure it in live clusters too (as per the [goals and non-goals](https://github.com/kubernetes/community/blob/master/sig-scalability/extending_slo.md#goal) section), then we can start measuring from when the request arrives at the API server. This will clearly simplify the setup - it mainly boils down to API server instrumentation.

**Comment by zcahana** [comment]
Agree, multiple apiservers make it more difficult. Do the current benchmarks run in a multiple-masters setup?

**Comment by wojtek-t** [comment]
Some of them will be running soon.

**Comment by cblecker** [comment]
There is still activity here it looks like
/remove-lifecycle rotten
