### ISSUE TITLE
Doc mungers need to be updated; "how-to-doc.md" needs to be updated

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/community#159]
Many doc [mungers](https://github.com/kubernetes/kubernetes/tree/master/cmd/mungedocs) can be removed, but these three are still needed:
* to [validate links](https://github.com/kubernetes/community/blob/master/contributors/devel/how-to-doc.md#how-to-write-links)
* to [keep examples update-to-date](https://github.com/kubernetes/community/blob/master/contributors/devel/how-to-doc.md#how-to-include-an-example)
* to [generate TOC](https://github.com/kubernetes/community/blob/master/contributors/devel/how-to-doc.md#how-to-get-a-table-of-contents)

First two mungers need to be refactored, because the structure of the repositories have changed.

The [how-to-doc.sh](https://github.com/kubernetes/community/blob/master/contributors/devel/how-to-doc.md) needs to be updated after mungers are fixed.

ref https://github.com/kubernetes/kubernetes/pull/38309

@bgrant0607 @david-mcmahon

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-docs-maintainers
