### ISSUE TITLE
Does we need add CONTRIBUTING.md file for every sig

### ISSUE THREAD

**Issue by stewart-yu** [kubernetes/community#1593]
According to website docs:  [https://kubernetes.io/docs/imported/community/guide/#sig-structure](https://kubernetes.io/docs/imported/community/guide/#sig-structure part, we should add CONTRIBUTING.md file for every sig.

**Comment by cblecker** [comment]
This bit of text was fixed here: #1587. It will be fixed in kubernetes.io on the next docs import.

/assign @chenopis

**Comment by guineveresaenger** [comment]
@chenopis @stewart-yu can either of you close this issue?
