### ISSUE TITLE
time.is site reliance

### ISSUE THREAD

**Issue by rothgar** [kubernetes/community#16]
I found [links to time.is](https://github.com/kubernetes/community/tree/master/community) for checking timezones in localtime. The site is currently down.

It's not a big deal but maybe we could move to something more reliable. [Google search perhaps](https://www.google.com/search?q=1000+am+in+pst)? :clock10:

**Comment by idvoretskyi** [comment]
@rothgar for me this site is up.

Double-checked with http://www.isup.me/http://time.is/.

**Comment by rothgar** [comment]
It's up for me now too. It was down for at least 30 minutes while I was poking around this repo and doing other things.

**Comment by idvoretskyi** [comment]
Google search sounds reasonable.

cc @sarahnovotny

**Comment by philips** [comment]
@rothgar Can you submit a PR to use Google?
