### ISSUE TITLE
when listing objects, the returned list has kind:None for all items

### ISSUE THREAD

**Issue by cristifalcas** [kubernetes/community#1605]
Example:

    ret = v1b1e.list_deployment_for_all_namespaces()
    for i in ret.items:
        print("kind: %s" % (i.kind)

Returns:

    kind: None

This is the same for v3 and v4. Also, object type doesn't matter (daemonset, replicationcontroller, statefulset, deployment)

**Comment by cristifalcas** [comment]
This was supposed to go to python bindings

**Comment by liggitt** [comment]
See https://github.com/kubernetes/kubernetes/issues/3030
