### ISSUE TITLE
SIG-cli CONTRIBUTING.md should point at contributor guide

### ISSUE THREAD

**Issue by guineveresaenger** [kubernetes/community#1613]
The new  [contributor guide](https://github.com/kubernetes/community/tree/master/contributors/guide) is in working condition. Any SIG-specific CONTRIBUTING.md files should first point to the contributor guide, and then mention SIG-specific extra guidelines.
The goal is to have the contributor guide be the single source of truth for general contributing rules.

Make sure to:
- avoid duplication of instruction (for example, don't point people at the CLA signing document; point them to the contributor guide)
- verify all other information given is up to date and fits logically with the contributor guide.

This is in partial completion of #1413.

/sig cli

**Comment by fanzhangio** [comment]
cc @seans3 @mengqiy I would like to take this

**Comment by guineveresaenger** [comment]
@fanzhangio please! it would be appreciated. :)

**Comment by guineveresaenger** [comment]
/area contributor-guide

Also, if @fanzhangio has gotten swamped in the meantime, I'm happy to do this.

**Comment by nikhita** [comment]
@fanzhangio Are you still interested in working on this? :)

**Comment by nidorano** [comment]
Hi! I would like to work on this issue. If I understand correctly, the idea is to have something like in [here](https://github.com/kubernetes/community/blob/master/CONTRIBUTING.md), isn't it?

**Comment by nikhita** [comment]
@nidorano Yes, linking to that document and removing any duplicate information. :+1:

**Comment by guineveresaenger** [comment]
Closing this as it was added in #1887 - thanks @nidorano!
