### ISSUE TITLE
Link to developer guide from the contributor guide

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#1632]
We need to sync with RyanJ or someone else working on the developer guide and at least link to whatever they have so far as a starting point

/sig contributor-experience
/area contributor-guide

**Comment by nikhita** [comment]
/remove-help
Removing the `help-wanted` label on this. Please re-add it again if this issue is still valid for a new-ish contributor.

/cc @ryanj

**Comment by nikhita** [comment]
@castrojo I'm trying to understand what this issue better -- does this mean just adding a link to the developer guide from the contributor guide or hashing out some more things? If its the former, we could add back the good-first-issue label.

The developer guide has also gone through a major overhaul (thanks to @eduartua!).

**Comment by parispittman** [comment]
@nikhita - pretty sure it's just a link to the main devrel readme when its ready

**Comment by nikhita** [comment]
> when its ready

@parispittman Thanks. Do you think we can link it even today? What does ready mean here? :)

**Comment by mrbobbytables** [comment]
I think this is done? This section links to the root of devel - https://github.com/kubernetes/community/tree/master/contributors/guide#setting-up-your-development-environment

We could potentially be more explicit about linking to devel -- like linking to the readme directly the root makes it easier to browse. ¯\_(ツ)_/¯

**Comment by nikhita** [comment]
> We could potentially be more explicit about linking to devel -- like linking to the readme directly the root makes it easier to browse. ¯\(ツ)/¯

SGTM. Let's close the issue once this is done. If anything else is needed, let's create follow-up issues with more details.

Adding the good first issue label back. 

/good-first-issue

For anyone who takes this up -- the link [here](https://github.com/kubernetes/community/tree/master/contributors/guide#setting-up-your-development-environment) should point to https://github.com/kubernetes/community/blob/master/contributors/devel/README.md#setting-up-your-dev-environment-coding-and-debugging instead.

**Comment by thecrudge** [comment]
#3574

And I have signed the CLA, I just didnt setup my email *smh*

**Comment by thecrudge** [comment]
@castrojo @nikhita @parispittman @idealhack ^^^^^

**Comment by idealhack** [comment]
@thecrudge thank you!

/close
