### ISSUE TITLE
Changing affiliation needs to be documented

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#1636]
It's unclear what we should do when someone changes affiliation. There's sigs.yaml but it's not just about updating it, people need to run make, etc. 

We should probably have document these bits as devstats for the person needs to be updated as well. This feel like an area where we should be consistent across the CNCF. 

/cc @idvoretskyi 
/sig contributor-experience
/area contributor-guide

**Comment by idvoretskyi** [comment]
+1, I agree.

We have a few samples of outdated info about the company affiliation.

**Comment by cblecker** [comment]
Should we also open up an issue against devstats?

**Comment by idvoretskyi** [comment]
@cblecker Yes, please, just a reference is enough.

**Comment by castrojo** [comment]
Ok so it's not hard to change the CNCF affiliation, I blogged about it here: https://blog.jorgecastro.org/2018/01/29/updating-your-cncf-developer-affiliation/

We just need to take that and generalize it somewhere.

**Comment by guineveresaenger** [comment]
@castrojo the above blog entry is a bit unclear on the exact steps you took to change your affiliation.
If you can give a bit more detail, we can make this a good first issue.
It should probably be linked to in https://github.com/kubernetes/community/tree/master/contributors/guide#sign-the-cla
and documented here:
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by parispittman** [comment]
/remove-lifecycle stale

i don't think this has been addressed. if it has, we can close.

**Comment by guineveresaenger** [comment]
haha I'm going through this literally right now. will try to follow up!
