### ISSUE TITLE
"Setting up a development environment" needs to be documented

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#1644]
Right now we just dump people to an index. 

We need to do something like:
- Setting up your laptop for mac, windows, and linux
- Installing the right tools (the github workflow deals with checking out and stuff, so this doesn't need to be detailed.
- Real world tips from existing developers. 

/sig contributor-experience
/area contributor-guide

**Comment by castrojo** [comment]
Some existing resources:

- https://github.com/kubernetes/community/blob/master/contributors/devel/development.md
- https://thenewstack.io/tutorial-configuring-ultimate-development-environment-kubernetes/
- https://abhishek-tiwari.com/local-development-environment-for-kubernetes-using-minikube/
- https://blog.giantswarm.io/getting-started-with-a-local-kubernetes-environment/
- https://github.com/kubernetes/community/blob/master/contributors/devel/vagrant.md

**Comment by castrojo** [comment]
Note to selves: even though it's in beta let's include the docker/kubernetes work as that will simplify our instructions quite a bit.

**Comment by nikhita** [comment]
/remove-lifecycle frozen
/remove-help

> Setting up your laptop for mac, windows, and linux

We have https://github.com/kubernetes/community/blob/master/contributors/devel/development.md today. 

> Real world tips from existing developers.

This isn't sufficiently actionable for help-wanted. :grimacing: @castrojo do you think we can close this issue? if not, could you add more details on what needs to be added?

**Comment by vishakhanihore** [comment]
@markyjackson-taulia Can I help in this issue ?

**Comment by markyjackson-taulia** [comment]
@vishakhanihore I would add this under the documentation umbrella for #3064

**Comment by hh** [comment]
Do we have any numbers for OS starting points: 

- Windows 10
- OSX
- Linux

I bought an Mac so I could help in this area, and I also thought of setting up VMs to walk through from scratch on each OS as well.

**Comment by hh** [comment]
@nevermyuk came across a windows dev setup written by @PatrickLang 
- https://github.com/PatrickLang/kubernetes-windows-dev#setting-up-a-devbuild-environment

Might be good to have some folks run through it a few times and create podcast or recording of going through that flow. Might be interesting to try and consolidate a flow that works across Mac/Linux/Windows.
