### ISSUE TITLE
Move assigned reviewers snippet from collab.md somewhere else.

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#1645]
I've merged the parts of collab.md that are relevant into community-expectations.md, this snippet on assigned reviews should live somewhere else though.

```
## Assigned reviews

Maintainers can assign reviews to other maintainers, when appropriate. The
assignee becomes the shepherd for that PR and is responsible for merging the PR
once they are satisfied with it or else closing it. The assignee might request
reviews from non-maintainers.
```

**Comment by guineveresaenger** [comment]
@castrojo could it maybe be incorporated into this?https://github.com/kubernetes/community/blob/master/contributors/devel/owners.md

**Comment by guineveresaenger** [comment]
@castrojo two thoughts:
1. this should be part of the "Code Reviews the Kubernetes Way"
2. it is also covered in part in https://github.com/kubernetes/community/pull/1761

**Comment by guineveresaenger** [comment]
also, collab.md should be removed in favor of conciseness and clarity.

**Comment by nikhita** [comment]
> /remove-lifecycle stale

help and stale labels don't go hand in hand :)

**Comment by guineveresaenger** [comment]
This snippet should go into work from #1514, the Reviewers' Edition.

**Comment by nikhita** [comment]
This is isn't sufficiently actionable to be help-wanted. Please add more details about what needs to be done, if the label should be added.

/remove-help

**Comment by cblecker** [comment]
/remove-help
@markyjackson-taulia: As @nikhita stated, this should have a clear description of what needs to be done before it's eligible for help/good first issue.
