### ISSUE TITLE
Proposal: Allow kubectl create configmap to accept env files

### ISSUE THREAD

**Issue by fraenkel** [kubernetes/community#165]
Now that a container can provide configmaps as an environment variables, we need to make it easier to build a configmap from a file containing key/value pairs.

The use cases are varied and not entirely agreed to. Below are excerpts from https://github.com/kubernetes/community/pull/148 and https://github.com/kubernetes/kubernetes/pull/37295

From @dhoer
I want k8s to be able read in an env file like this:

Create configmap:
kubectl create configmap game-config --from-file=./env/game.env

Reference configmap:

- envFrom:
      configMap: game-config/game.env
Comments and blank spaces would be handled automatically, just like in docker env-file:
https://docs.docker.com/compose/env-file/.

For consistency, it would be nice for secrets to have the same behavior.

Create secret:
kubectl create secret game-config --from-file=./secret/too-many-secrets.env

Reference secret:

- envFrom:
      secret: game-config/too-many-secrets.env
This eliminates the required preprocessing step to convert name value pairs into configmap or secret, e.g., https://github.com/dhoer/k8s-env-gen.

From @thockin 
if there were a kubectl create configmap mode that read a file an env file and created the equivalent configmap (1 key per key), would you be satisfied?

From @fraenkel
The behavior is a bit tricky. In a simple world, I can point to a directory of env files and say kubectl create configmap --from-file somedir. Duplicates are where things become tricky. What order are we processing the files in the directory? Are we sorting them? Or letting the filesystem hand them in some random order?
I will also assume you can provide multiple directories to allow overrides.

From many
For directory, I would assume whatever order it reads today, where on duplicated keys, the last one wins. They can use multiple --from-file entries to get the order they want. Subsequent --from-file entries are will overwrite any repeating key values.

From @thockin 
I was thinking --from-env-file=filename and only allowing one, and not a directory.

From @kad
If we already touching this part of API spec, it might be good also to add one thing: referenced ConfigMap might be optional. By default this option will be false, so if ConfigMap referenced and it is missing, it will lead to error. If optional parameter set to true, and referenced ConfigMap not found, it will continue normally. Use case for such behavior:

- Application developer can prepare Application deployment with referencing ConfigMap with default values. Developer also can reference optional ConfigMap with parameters that can be overridden in e.g. testing cluster, or regional cluster. If those overrides not found or not used, application will get all the rest of default values from ConfigMap of defaults, shipped with Deployment spec.
- Same deployment in public and private cloud: *_proxy variables.. Developer can write spec that will be referencing ConfigMap with some agreed name, e.g. "cluster-proxies". In case of deployment of this application in private cluster this ConfigMap would contain http_proxy, https_proxy, no_proxy and other variables specific to this cluster. Same deployment sent to cluster in public cloud with direct internet access will be referencing non-existing optional ConfigMap, so containers will be run without pre-populated proxy variables.

From @thockin 
We may yet end up with "if present" configmap volumes - it would actually
simplify a whole swath of scenarios.  But we should do that and this in
tandem.

From @fraenkel
Doing some investigation on the --from-env-file, I noticed that the current create configmap support does not allow duplicate keys. I realize that we can have this behave differently but reading the use cases, people expect to be able to override yet you cannot do that today with what is currently there.

**Comment by pmorie** [comment]
cc @derekwaynecarr

**Comment by bgrant0607** [comment]
This wasn't the right way to make a proposal, but it has been implemented and merged already, so closing.
