### ISSUE TITLE
README.md references 2015 stats

### ISSUE THREAD

**Issue by tpepper** [kubernetes/community#1663]
https://github.com/kubernetes/community/tree/master/sig-contributor-experience/README.md includes "we need to break the commit-rate ceiling we hit in July 2015, and we need to get the monotonically growing PR merge latency and numbers of open PRs and issues under control."

Does devastates show the commit-rate ceiling?  Has the 2015 ceiling been broken?

Either way, it might be a more clear charter to indicate the abstract ongoing commitment to software engineering process refinements to minimize development friction around metrics such as commit rate, PR merge latency, number of open PRs and issues, and numbers of individuals at the various levels of the membership ladder.

**Comment by cblecker** [comment]
/remove-lifecycle stale
Still relevant.

cc: @parispittman @Phillels @grodrigues3

**Comment by nikhita** [comment]
> https://github.com/kubernetes/community/tree/master/sig-contributor-experience/README.md includes "we need to break the commit-rate ceiling we hit in July 2015, and we need to get the monotonically growing PR merge latency and numbers of open PRs and issues under control."

This is now gone! :tada:

Closing.
/close
