### ISSUE TITLE
Community meeting invite workflow needs to be revised

### ISSUE THREAD

**Issue by tpepper** [kubernetes/community#1665]
There's some signs of issues and vestigial limbs here.

Why does this google group exist: https://groups.google.com/forum/#!forum/kubernetes-community-video-chat

Why does one need to email @castrojo or @parispittman to get an invite?

And...I didn't actually get an invite after @castrojo added me.

This should be streamlined and the results better documented for example in the results of PR #1660 as that evolves/merges.

**Comment by castrojo** [comment]
@parispittman said in another issue: "What are thoughts on messaging everyone in that group that we are sunsetting this google group / process and to copy calendar from kubernetes.io/community?"

+1 to this, we need to test that it works.

**Comment by castrojo** [comment]
Let's fix #1666 first so that we get a new calendar meeting on the schedule.

**Comment by castrojo** [comment]
Fixing with: 

https://github.com/kubernetes/community/pull/1827
https://github.com/kubernetes/website/pull/7472

**Comment by castrojo** [comment]
@parispittman Do we have access to edit this text? 

https://groups.google.com/forum/#!forum/kubernetes-community-video-chat

**Comment by parispittman** [comment]
@tpepper - do you think the work with the lifecycle doc, latest doc changes around communication, etc are good for this or do we need more work?

cc/ @castrojo

**Comment by tpepper** [comment]
Compared to when I first went through it the current documentation (for example: https://github.com/kubernetes/community/blob/master/sig-wg-lifecycle.md ) is much cleaned up, old stuff is removed, single points of failure are removed.
