### ISSUE TITLE
Community resources need to be managed by more than one person

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#1666]
We have individual admin accounts for:

Zoom
YouTube
Google Calendar
Slack? 
Too many documents on google drive to list here. 

And so on, we need to de-bus-factor this so that one person isn't in the gatekeeper for the community resources. Perhaps something like `community@k8s.io` and that with a rotating set of trusted people there for admin purposes. 

/sig contributor-experience

**Comment by cblecker** [comment]
Related: https://github.com/kubernetes/community/blob/master/sysadmin.md

**Comment by spiffxp** [comment]
/area community-management
😱 I added another area label to this repo by hand, please let me know if I did a bad thing

**Comment by spiffxp** [comment]
/area community-management
😱 I added another area label to this repo by hand, please let me know if I did a bad thing

**Comment by idvoretskyi** [comment]
I second this.

We can start with creating a Google Group.

**Comment by idvoretskyi** [comment]
cc @parispittman @jdumars

**Comment by idvoretskyi** [comment]
UPD.

We have a @kubernetes/community-admins group, so we may start from this list of people.

**Comment by jdumars** [comment]
Yes, please let me know if I can help.

**Comment by yogeshmsharma** [comment]
I agree with having Google group.

**Comment by idvoretskyi** [comment]
PTAL @spiffxp

**Comment by castrojo** [comment]
We just documented this and there's no longer a SPOF, I think we can close this.

https://github.com/kubernetes/community/blob/master/communication/moderators.md
