### ISSUE TITLE
SIG lead lifecycle needs to be documented

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#1693]
When a SIG lead moves on we need to document a few things. There are [pending governance things](https://github.com/kubernetes/steering/blob/master/backlog.md) here but this issue will document the technical changes at a minimum.

- Old lead 
  - unsubscribe from their sig leaders list.
  - Removal as leader from sigs.yaml
- New lead
  - Subscribe to the sig leaders list. 
  - Need the Zoom credentials to record meetings
  - Need Youtube collaboration URL, perhaps a new one should be generated? 
  - Addition as leader in sigs.yaml and then [regenerate the pages](https://github.com/kubernetes/community/tree/master/generator). 

Announcements to:

- That SIG's internal list
- kubernetes-dev list
- Mention in the announcements of a community meeting

**Comment by castrojo** [comment]
Marking as contrib-ex but blocking on SIG charters, governance, etc. 

/sig contributor-experience

**Comment by castrojo** [comment]
See also: https://github.com/kubernetes/community/pull/1650

**Comment by cblecker** [comment]
Governance stuff should be done, but the process stuff might need to still go in.
/remove-lifecycle stale

**Comment by parispittman** [comment]
@jonasrosland + @castrojo will work on proposing a solution after SC election

**Comment by mrbobbytables** [comment]
Would some of these items be good for the Chair & TL documentation being put together? ref: https://github.com/kubernetes/community/pull/4461

**Comment by mrbobbytables** [comment]
I think this can be accomplished this cycle, we need to add more items to the chairs and TLs guides
/milestone v1.20

**Comment by mrbobbytables** [comment]
Review this and determine if this can be closed - 
Ref: https://github.com/kubernetes/community/blob/master/contributors/chairs-and-techleads/leadership-changes.md

**Comment by mrbobbytables** [comment]
/unassign @jonasrosland @castrojo 
/assign @alisondy @mrbobbytables 
looping in  so we can document that change over.

**Comment by mrbobbytables** [comment]
We should convert the leadership change doc into an issue template that is closed when all items are checked off.
