### ISSUE TITLE
Proposal: Allow containers to specify optional ConfigMaps for environment variables

### ISSUE THREAD

**Issue by fraenkel** [kubernetes/community#170]
From @kad
If we already touching this part of API spec, it might be good also to add one thing: referenced ConfigMap might be optional. By default this option will be false, so if ConfigMap referenced and it is missing, it will lead to error. If optional parameter set to true, and referenced ConfigMap not found, it will continue normally. Use case for such behavior:

Application developer can prepare Application deployment with referencing ConfigMap with default values. Developer also can reference optional ConfigMap with parameters that can be overridden in e.g. testing cluster, or regional cluster. If those overrides not found or not used, application will get all the rest of default values from ConfigMap of defaults, shipped with Deployment spec.
Same deployment in public and private cloud: *_proxy variables.. Developer can write spec that will be referencing ConfigMap with some agreed name, e.g. "cluster-proxies". In case of deployment of this application in private cluster this ConfigMap would contain http_proxy, https_proxy, no_proxy and other variables specific to this cluster. Same deployment sent to cluster in public cloud with direct internet access will be referencing non-existing optional ConfigMap, so containers will be run without pre-populated proxy variables.
From @thockin
We may yet end up with "if present" configmap volumes - it would actually
simplify a whole swath of scenarios. But we should do that and this in
tandem.

**Comment by fraenkel** [comment]
I can see the value by allowing optional EnvFromSource which would allow anything like ConfigMaps, Secrets or whatever to be optional. But why are we saying that EnvFromSource can be optional but EnvVars cannot? An EnvVar may select a single item from a ConfigMap and expose it, shouldn't that be optional. Obviously it would allow either the ConfigMap to not be present or the key to be missing but that is an implementation detail.

**Comment by thockin** [comment]
I think optional configmaps seem useful.

**Comment by bgrant0607** [comment]
cc @pmorie

**Comment by bgrant0607** [comment]
Not-present dependencies should not lead to error in the API. The consuming component should wait for it to be created.

This seems like it would create unpredictable behavior.

**Comment by thockin** [comment]
Optional configmaps went in months ago.
