### ISSUE TITLE
Bot should respond with the final step when a PR is accepted 

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#1702]
A new contributor gave me some bot feedback. All the intermediate steps were fine (bot had links to docs, etc.) but one thing he wasn't clear on was what the next step when his PR got accepted. 

Perhaps something like "Your PR has been accepted, you're done! No action is required on your part. Check the _merge queue_ if you're interested in more details" 

/sig contributor-experience

**Comment by cblecker** [comment]
@spxtr @cjwagner @fejta @spiffxp 
Some feedback that might be helpful to keep in mind for tide (and it's status context).

**Comment by cblecker** [comment]
/remove-lifecycle stale
/remove-help

I don't think this is help wanted yet, because we don't have feedback on approach.

Do you still think this is a good idea, @castrojo? If so, I can put it in the backlog to discuss (trying to collect our issues together)

**Comment by nikhita** [comment]
Has there been any discussion on this? 

Will this lead to too much spam? Maybe if we could figure out that the PR is sent by a new contributor (https://github.com/kubernetes/test-infra/issues/3083), we can put this info in the onboarding information?

**Comment by fejta** [comment]
I think the intent here is to make the details for the tide context display this info for a given PR
