### ISSUE TITLE
Proposal: Move kubedns addon code to its own repository under Kubernetes

### ISSUE THREAD

**Issue by bowei** [kubernetes/community#172]
# Overview
The kube-dns pod currently consists of the `kube-dns` daemon, `dnsmasq` and their healthcheck sidecars (`exec-healthz` and `dnsmasq-metrics`). The code is spread over both main `kubernetes/` and `contrib/` repositories. Images for each of the containers are currently versioned separately. For example, the `kube-dns` that ships with Kubernetes v1.5 is v1.9, `dnsmasq-metrics` v1.0 etc. 

Note: exec-healthz is being removed from the pod shortly.

It would be more coherent to move all of the related code into the same respository. `kube-dns` consumes only public APIs and the release of all Kubernetes maintained code can be unified.

# Plan of action 
* Create a new repository in kubernetes called `dns`
* Copy code (keeping history) of `kubernetes/pkg/dns` to `dns/pkg/dns`
* Copy code (keeping history) of `kubernetes/cmd/kube-dns` to `dns/cmd/kube-dns`
* Copy code (keeping history) of `contrib/dnsmasq-metrics` to `dns/cmd/kube-dns-sidecar`, adjusting `pkg` and `cmd` appropriately
* Copy code (keeping history) `contrib/dnsmasq` to `dns/dnsmasq`
* Use the [standard build template](https://github.com/thockin/go-build-template) for the verification and build infrastructure
* e2e testing of DNS will remain in the Kubernetes repo. I would defer any potential movement of e2e tests until the [separation of e2e from the main repo](https://github.com/kubernetes/kubernetes/issues/36624) has been concretized.
* `kubernetes/cluster/addons` will remain for now.
* Add hook to run e2e against current kube-dns build. Note: this is not done today in the kubernetes repo itself.

# Impacts
* Kubernetes cluster/addon will refer to externally built image. This is already the case, as the CI system does not pick up changes to the kube-dns code. The referenced image on gcr.io is used instead.
* kube-dns is a leaf project, output of `git grep 'k8s.io/kubernetes/\(cmd\|pkg\)/dns/' | grep -v '^\(pkg/dns\|cmd/kube-dns\)'` shows only one e2e test as an external dependency which will be removed.

**Comment by bowei** [comment]
@kubernetes/sig-network

**Comment by thockin** [comment]
Why the "kube-dns-sidecar" name?  isn't it more like a dnsmaq-sidecar?

Should you also move the dnsmasq repo (which is basically a dockerfile), too?

**Comment by thockin** [comment]
I am in favor of this move, FWIW - it gives permissions to the people doing the real work on the right granularity.

**Comment by bprashanth** [comment]
It would be  great if we had feedback from a failing e2e to prevent merges in the new repo. I assume we'll run godep restore+build+unit/integration tests via build template invoked through travis? We might want to pull some of the mungers for docs etc, for the sake of consistency.

**Comment by bowei** [comment]
updated regarding dnsmasq -- didn't realize this had its own build

**Comment by bgrant0607** [comment]
ref https://github.com/kubernetes/kubernetes/issues/24343

**Comment by thockin** [comment]
Next step here if no objections?

Bowei if you tell me what name you want and who you want to have admin
access to it, I can create the repo.  You'll need to populate it with
boilerplate as per the incubation guidelines

**Comment by bowei** [comment]
repo: kubernetes/dns

Add @MrHohn as a admin (and yourself)

**Comment by thockin** [comment]
Repo created.
