### ISSUE TITLE
ContribEx Guide Needs to Recommend Mailing List Best Practices

### ISSUE THREAD

**Issue by chris-short** [kubernetes/community#1724]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
As a Kubernetes community member, it is difficult to attain a good signal-to-noise ratio with regards to GitHub notifications and mailing list messages. 

**What you expected to happen**:
I'd like to get some guidance on how to be an effective communicator in the Kubernetes community. In other words, not be deluged by all the e-mail. Specifically, what to do with GitHub and Gmail to surface the pertinent content and purge the less personally meaningful content.

**How to reproduce it (as minimally and precisely as possible)**:
Join as a Member, help out with more than one SIG.

**Anything else we need to know?**:
N/A

**Environment**:
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others:

cc @castrojo @bgrant0607 @idvoretskyi 
/sig contributor-experience
/area contributor-guide

**Comment by idvoretskyi** [comment]
https://groups.google.com/forum/#!msg/kubernetes-dev/5qU8irU7_tE/aZov0LpCBwAJ

**Comment by guineveresaenger** [comment]
Motion: while this is important to do, it shouldn't be a blocker to publishing the contributor guide.

**Comment by bgrant0607** [comment]
My conclusion is that notifications are hopeless. I'd be fine with getting rid of all the SIG-related github teams and mailing-list mirrors.

**Comment by bgrant0607** [comment]
To be clear: I'm am completely DoSed by notifications, so it's all white noise to me.

**Comment by castrojo** [comment]
I'd like to take this on as part of the mailing list moderator work. I can write something up to make this better, and we should probably take a hard look at having multiple teams and lists per SIG.  

I don't have a solution for github notifications, it feels like we're all over it, and the best way to handle that is to interface with the github folks directly.

**Comment by nzoueidi** [comment]
/remove-lifecycle frozen
/lifecycle active

I am working on this.
