### ISSUE TITLE
Doc building script needs to be automatic

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#1726]
We are currently getting the contrib guide, mentorship guide, and KEPs imported into the doc site.

To do this we must checkout the website repo locally, run `./update-imported-docs community.yml`, then submit a PR to the docs team to update these docs. 

It would be nice if this script did:

- Make it so we don't have to specify each and every page in `community.yaml`, we should just be able to say "build everything in contributor/guide". So, specifying a directory should be enough.

**Comment by grodrigues3** [comment]
@kubernetes/sig-docs-maintainers

**Comment by grodrigues3** [comment]
Looks like the files specified currently are not all in one directory.   What's the plan? 

Is it to build everything in contributor/guide and the keps dir and the mentoring dir?

**Comment by zacharysarah** [comment]
@grodrigues3 👋 I added the import script to SIG Docs' upcoming deep dive for Hugo migration.

**Comment by guineveresaenger** [comment]
/remove-lifecycle stale
@grodrigues3 @castrojo - this is in the publishing area; is it being tracked elsewhere?

**Comment by nikhita** [comment]
/remove-lifecycle frozen

@mrbobbytables @castrojo I think this relates to the contributor website...is this still relevant today?

**Comment by mrbobbytables** [comment]
Nope! no longer relevant :) Thanks! 👍 
/close
