### ISSUE TITLE
/contributors/devel/development.md needs a rewrite

### ISSUE THREAD

**Issue by guineveresaenger** [kubernetes/community#1756]
This document should focus on the technical aspects and caveats of working on an issue. It should link to the contributor guide for all contributing-specific questions (like signing the CLA, adhering to community standars) and it should be clear on its technical purpose.
/area contributor-guide

**Comment by ryanj** [comment]
Duplicate issue #1919 (@ryanj)

**Comment by nikhita** [comment]
Closing this as a dupe of https://github.com/kubernetes/community/issues/1919 (since it has more comments and content).

/close
