### ISSUE TITLE
/contributors/devel/help-wanted.md needs to be incorporated elsewhere

### ISSUE THREAD

**Issue by guineveresaenger** [kubernetes/community#1757]
This is a very short stub doc that should be deleted and the information incorporated in documentation on how to file/label issues somewhere. It currently is linked from nowhere.
/sig contributor-experience
/area contributor-guide

**Comment by cblecker** [comment]
It is currently linked from here: https://github.com/kubernetes/test-infra/blob/cb87afa612ef6d8c63e69602d8b76bb009f6d2d6/prow/plugins/help/help.go#L36

**Comment by guineveresaenger** [comment]
@cblecker good to know, thanks! (I must remember to check the overall project. My bad.)

**Comment by cblecker** [comment]
It's used in the bot message:
> This request has been marked as needing help from a contributor.
>
>Please ensure the request meets the requirements listed [here](https://git.k8s.io/community/contributors/devel/help-wanted.md).
>
>If this request no longer meets these requirements, the label can be removed
by commenting with the /remove-help command.

**Comment by guineveresaenger** [comment]
I still think it should be a subsection of guidelines on labeling Issues, as it's a relevant decision to make while filing/triaging an issue.

**Comment by carolynvs** [comment]
Testing out the latest prow changes on this issue. Hope that's okay!

/good-first-issue

**Comment by nikhita** [comment]
Created https://github.com/kubernetes/community/pull/2960 to add the help wanted guidelines in the issue triage doc.
