### ISSUE TITLE
Calendar procedure is too complex

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#1759]
We need to restructure this.

- [x] Document steps
- [ ] Update https://github.com/kubernetes/community/blob/master/sig-governance.md#sig-creation-procedure
- [x] Update widget on k8s.io/community
- [x] Fix instructions on k8s.io/community

/sig contributor-experience

**Comment by castrojo** [comment]
The openstack folks do this: http://eavesdrop.openstack.org/#LOCI_Development_Meeting

And they use https://github.com/openstack-infra/yaml2ical

**Comment by idvoretskyi** [comment]
cc @kubernetes/community-admins

**Comment by jdumars** [comment]
@parispittman has the answer.

**Comment by castrojo** [comment]
Ok we've made it easy for people to subscribe to the community meeting and now have updated instructions on k8s.io/community, which point here: https://github.com/kubernetes/community/blob/master/events/community-meeting.md

Sharing from SIGs is more complicated than I'd like but we can't seem to find a simpler way. At least for end users it's much easier, so closing this.
