### ISSUE TITLE
cherry-picks.md in /contributors/devel is a duplicate

### ISSUE THREAD

**Issue by guineveresaenger** [kubernetes/community#1760]
Sig-release has a duplicate of the cherry-picks document here:
https://github.com/kubernetes/sig-release/blob/master/ephemera/cherry-picks.md

We should
1. remove it from community/contributors/devel
2. find all references throughout the org and fix any links
/sig contributor-experiece
/area contributor-guide
/help-wanted

**Comment by nikhita** [comment]
ref https://github.com/kubernetes/community/issues/994. We should also include some more information in the doc.

**Comment by spiffxp** [comment]
I would suggest we nuke the sig-release doc. Cherry picking is a contribution process not a sig-release-specific process.

Most recent doc is here: https://github.com/kubernetes/community/blob/afc5171643fabbd498ce29bc45a668a5d8f20225/contributors/devel/cherry-picks.md

Seems like if you're trying to move all things "how do I contribute" to the contributor guide, this should go there (with an appropriate redirect tombstone)

**Comment by guineveresaenger** [comment]
@chris-short are you still able to work on this? It would be awesome!
