### ISSUE TITLE
CLA.md needs to be more clear about the difference between signing up as employee vs. individual

### ISSUE THREAD

**Issue by guineveresaenger** [kubernetes/community#1794]
Problem:

The steps for signing the CLA are clearly documented for individual contributors.

It is unclear what to do when your company has signed a CLA. Does the contributor need to sign anything? Obtain a Linux Foundation ID? What if the contributor's github email is different from company email?

Furthermore, if no action on part of a company-approved contributor is necessary, this needs to be clearsly stated in the contributor guide.

/sig contributor-experience
/area contributor-guide

**Comment by castrojo** [comment]
We need to add this to the README of the contributor guide, at the top level so it's obvious to people that the CLA document covers individuals and organizations.

**Comment by guineveresaenger** [comment]
Related: #2012

**Comment by nikhita** [comment]
/remove-lifecycle stale

cc @idvoretskyi

**Comment by guineveresaenger** [comment]
Closing this via https://github.com/kubernetes/community/pull/2893.
