### ISSUE TITLE
Membership doc should point new contributors to contributors guide

### ISSUE THREAD

**Issue by guineveresaenger** [kubernetes/community#1797]
Bug:
The following section points at an ancient, still open, issue.
https://github.com/kubernetes/community/blob/master/community-membership.md#new-contributors

Fix:
Make that link point to the contributor guide instead.

/help
/sig contributor-experience
/area contributor-guide

**Comment by vaibhavsingh97** [comment]
@guineveresaenger Can I fix this? This will be my first small bug fix in K8s community :P

**Comment by guineveresaenger** [comment]
@vaibhavsingh97 please do! Thank you!
