### ISSUE TITLE
Documenting the revert process (Avoid the github revert button)

### ISSUE THREAD

**Issue by dims** [kubernetes/community#1809]
- Use `git revert SHA` where SHA is the hash of the commit you wish to revert
- Push this commit to a new branch in your own repo
- Use the commit/branch to file a PR

Essentially avoid pushing the button in github web UI. This creates unnecessary branches in the kubernetes main repository that someone has to go clean up. The bots notice such merges and notifies kubernetes-dev channel as well. following process above will avoid that notifications too

**Comment by cblecker** [comment]
/sig contributor-experience
+1 to this

**Comment by guineveresaenger** [comment]
/help
Good for anyone comfortable with git.
