### ISSUE TITLE
KEP0005: Contributor Site discussion

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#1819]
- https://github.com/kubernetes/community/blob/master/keps/sig-contributor-experience/0005-community-site.md

**Comment by castrojo** [comment]
https://github.com/kubernetes/community/pull/1814
/sig contributor-experience

**Comment by jbeda** [comment]
Thanks for merging the start of the KEP.

Generally, with the KEP process I’m thinking we want to have follow on issues/PRs be more specific wrt the topics in question.

To start with I’d love to get the following locked down:
* We should do a separate site vs. try and do a Rube Goldberg thing with the main k8s site.
* We should outline the first set of features a that we want to have on the site (KEPs, community engagement, list of SIGs, place contributor guide)
* We come up with a name/URL.  I’m thinking community.kubernetes.io and we make it clear this is for folks that are developing k8s and not just using it.  We’d aim to replace/redirect from k8s.io/community.

Thanks for merging all!

As for @parispittman’s comment on waiting until this main docs site shakes out — my one comment here is that I feel some urgency.  I wanted to start getting this done in December and between the various discussions and my own lack of time it hasn’t made progress.  As things stand this is one of the graduation requirements I’ve set for us to move the KEP process out of beta.  I’d rather do a more full featured community oriented site but we can do something more targeted (keps.kubernetes.io) if we can’t come up with a decision.

While it is great to align with the main site, one of the main advantages of doing this as a separate site is that we can get something up and working right away.  If we want to merge it back in at some point (not sure that’ll happen, but who knows) we can always do that in the future and redirect.

**Comment by castrojo** [comment]
Ok I feel like this is taking too long and is starting to block work, for each of the three issues brought up:

- Let's just do a separate site, contributors.k8s.io
- From running a `tree` in the community repo we should probably surface/generate:

```
├── CLA.md
├── code-of-conduct.md
├── committee-steering
├── communication
│   ├── K8sYoutubeCollaboration.md
│   ├── README.md
│   └── slack-guidelines.md
├── communication.md
├── community-membership.md
├── CONTRIBUTING.md
├── contributors (all of it)
├── events
├── governance.md
├── incubator.md
├── keps
│   ├── 0000-kep-template.md
│   ├── 0001-kubernetes-enhancement-proposal-process.md
│   ├── 0002-controller-manager.md
│   ├── NEXT_KEP_NUMBER
│   ├── OWNERS
│   ├── README.md
│   ├── sig-apps
│   │   ├── OWNERS
│   │   └── README.md
│   └── sig-cluster-lifecycle
│       ├── 0003-cluster-api.md
│       ├── 0004-bootstrap-checkpointing.md
│       ├── OWNERS
│       └── README.md
├── mentoring
│   ├── google-summer-of-code.md
│   ├── group-mentee-guide.md
│   ├── group-mentoring.md
│   ├── meet-our-contributors.md
│   ├── OWNERS
│   └── README.md
├── org-owners-guide.md
├── README.md
```

And then each sig and wg has a directory that we should probably generate so that each SIG and WG has a "home page" for end users.

**Comment by parispittman** [comment]
We haven't heard from LF and I believe this to be a priority for surfacing docs and creating a centralized point for contributors. Let's go.

+1 - happy to be an approver; @jbeda , @castrojo - pls be reviewers. This is my first KEP, too, so help with process would be great @jbeda

/lgtm

**Comment by jbeda** [comment]
Thanks!

I'll put a PR in to add you as approver and Jorge as a reviewer.  

I'll then open another PR (hopefully tomorrow) that starts filling in some details.  Once we are happy (probably a couple more PRs) we can move it to `implementable`.

**Comment by castrojo** [comment]
TODO: I need to PR scope and maintenance plan.

**Comment by mattfarina** [comment]
@castrojo Where is this KEP at? It's listed as _implementable_ but I see a repo at https://github.com/kubernetes-sigs/contributor-site. Is status noted somewhere?

Also, where is this planned on being operated out of?

**Comment by mrbobbytables** [comment]
I'll ping ya on slack :)

**Comment by mrbobbytables** [comment]
I think we can actually close this issue in favor of the KEP and the current issues etc under the contributor site repo.

Any objections?

**Comment by justaugustus** [comment]
Go for it!
