### ISSUE TITLE
Require all k/* repositories to have CONTRIBUTING.md

### ISSUE THREAD

**Issue by guineveresaenger** [kubernetes/community#1832]
All K8s subrepositories should have a CONTRIBUTING.md file, which at the minimum should point to 
https://github.com/kubernetes/community/blob/master/contributors/guide/README.md. Care should be taken that all information is in sync with the contributor guide.

Subrepositories may also have contributing guidelines specific to that repository. They should be explicitly documented and explained in the CONTRIBUTING.md.

The first step to working on this issue is to create a task list of k/subrepositories that need to have issues/PRs filed against to rectify this.

/sig contributor-experience
/area contributor-guide
/help

**Comment by chris-short** [comment]
Here are the following k/subrepositories with no CONTRIBUTING.md in their root dirs:

autoscaler
cloud-provider-aws
cloud-provider-azure
cloud-provider-gcp
cloud-provider-openstack
common
dashboard
examples
features
federation
gengo
kube-openapi
kube-state-metrics
kubernetes-anywhere
kubernetes-bootcamp
node-problem-detector
publishing-bot
repo-infra
sig-release
utils

**Comment by nikhita** [comment]
@guineveresaenger Could this be a good first issue as well? :)

The approach I see here is:

1. Go to each repo (from @chris-short's list above) and create an issue about adding a `CONTRIBUTING.md` to their repo. Mention that they can point to https://github.com/kubernetes/community/blob/master/contributors/guide/README.md if they don't want to include any specific contributing guidelines.
2. If the maintainers of the repo decide not to create specific contributing guidelines, perhaps even send a PR creating a `CONTRIBUTING.md` which has a link to https://github.com/kubernetes/community/blob/master/contributors/guide/README.md.

**Comment by guineveresaenger** [comment]
I think this is an excellent first issue!
/good-first-issue

**Comment by nikhita** [comment]
@aojea THIS. IS. AWESOME. :heart:

**Comment by parispittman** [comment]
Yes, @aojea - thank you! If you are on the Kubernetes slack, DM me so we can coordinate a swag delivery. :)

**Comment by roycaihw** [comment]
Thanks for improving the contributor experience. I just want to point out that we also have client libraries under https://github.com/kubernetes-client, and project incubators under https://github.com/kubernetes-incubator. Do they also need to have CONTRIBUTING.md? AFAIK some of them don't have the file now.

**Comment by nikhita** [comment]
>  I just want to point out that we also have client libraries under https://github.com/kubernetes-client, and project incubators under https://github.com/kubernetes-incubator. Do they also need to have CONTRIBUTING.md? AFAIK some of them don't have the file now.

@roycaihw thanks for pointing that out! IMO they should have CONTRIBUTING.md files as well since they are official Kubernetes repos. I'll create PRs for them. :+1:

**Comment by guineveresaenger** [comment]
There are some missing ones in kubernetes-sigs as well. I'll add those.

**Comment by justaugustus** [comment]
There's some prior art from @jessfraz as well to handle `SECURITY_CONTACTS`: https://github.com/jessfraz/secping

We should consider using that and expanding the scope to handle all of the expected files for a k8s repo.

**Comment by guineveresaenger** [comment]
@justaugustus thank you for linking to that <3

**Comment by justaugustus** [comment]
Also, we should `/assign` if someone is officially taking up this effort.

**Comment by nikhita** [comment]
> Also, we should /assign if someone is officially taking up this effort.

/assign
Assigning myself because I've created PRs against repos against the kubernetes org. Have created some more in kubernetes-client (some more are remaining, which I'll do today). All PRs reference this issue and can be seen above.

I'll also send PRs to kubernetes-incubator, unless someone gets to it sooner.

> There are some missing ones in kubernetes-sigs as well. I'll add those.

/assign @guineveresaenger
