### ISSUE TITLE
Contributor guide README should clarify special subrepository contributing guidelines

### ISSUE THREAD

**Issue by guineveresaenger** [kubernetes/community#1833]
See also #1832 .

Certain subrepositories of the Kubernetes Project may have (and will have) additional or special contributing guidelines. Currently, the contributor guide only mentions that SIGs may have additional guidelines, but is silent about subrepositories.

Add clarifying language that contributors should double check if the particular repository they're contributing to has additional requirements or differnet processes.

/sig contributor-experience
/area contributor-guide

**Comment by nikhita** [comment]
I think this could be a good first issue? :)

/good-first-issue

**Comment by nikhita** [comment]
For anyone who decides to work on this, the change would be here: https://github.com/kubernetes/community/tree/master/contributors/guide#open-a-pull-request

`...and following any SIG specific contributing guidelines...`

**Comment by palash25** [comment]
I would like to work on this. Requesting assignment.

**Comment by cblecker** [comment]
/remove-help

@palash25 it's all yours.
