### ISSUE TITLE
#azure Slack channel without full blown SIG

### ISSUE THREAD

**Issue by colemickens** [kubernetes/community#188]
cc: @sarahnovotny 

Is it possible to get an `#azure` Slack channel without going through the full SIG process?

**Comment by kris-nova** [comment]
I knew it was coming..

**Comment by sarahnovotny** [comment]
we additionally have this request -- https://github.com/kubernetes/community/pull/36.  i'd rather combine them and go sig-azure.  a topic for discussion on thursday?

**Comment by colemickens** [comment]
cc: @brendandburns 

I think the full SIG makes sense, just no one has yet written/submitted the proposal. I will attend the Thursday meeting in case this comes up.

**Comment by brendandburns** [comment]
Sure, SIG sounds fine with me, it seems a shame not to have the slack channel in the meantime b/c it's an easy place to meetup with users, but I'm happy to follow the SIG process.

**Comment by pidah** [comment]
A sig-azure slack channel now exists. We can close this issue now.
