### ISSUE TITLE
disable reviewable for kubernetes repos that don't use it

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#1881]
Discussion here: https://groups.google.com/forum/#!topic/kubernetes-dev/0RhWYvxW2XI

https://reviewable.kubernetes.io/repositories claims it's enabled for
- kubernetes/client-go (doesn't make sense, PR's to this repo aren't accepted)
- kubernetes/contrib
- kubernetes/frakti
- kubernetes/gengo
- kubernetes/git-sync
- kubernetes/heapster
- kubernetes/helm (no webhook)
- kubernetes/ingress-nginx
- kubernetes/k8s.io
- kubernetes/kops (webhook is disabled)
- kubernetes/kube-state-metrics
- kubernetes/kubernetes (all webhook deliveries are erroring)
- kubernetes/node-problem-detector 
- kubernetes/test-infra (webhook is disabled)
- kubernetes/website (webhook is disabled)

I heard objections to disabling reviewable for kubernetes/kubernetes, so I will leave that enabled.  But I'm not actually sure it's properly hooked up given the webhook errors.

**Comment by spiffxp** [comment]
Based on [this query](https://github.com/pulls?utf8=%E2%9C%93&q=%22unresolved+discussions%22++is%3Apr+user%3Akubernetes+sort%3Aupdated-desc+-repo%3Akubernetes%2Fwebsite+-repo%3Akubernetes%2Fkubernetes+) of PR's, gengo also recently used a reviewable review.  Other uses of reviewable date back to Oct 2017.

I used the reviewable UI at https://reviewable.kubernetes.io/repositories to disable reviewable for all repos, except for:
- kubernetes/gengo
- kubernetes/kubernetes (shows "repository not found" error through the ui)

**Comment by spiffxp** [comment]
/assign thockin
I probably need @thockin's help to troubleshoot why it's not working for k/k if there is a desire to use it there.  I'm guessing it must have stopped working a few months back and we just never noticed.

**Comment by thockin** [comment]
I disabled the integration for all.  Given that it wasn't working, I have a hard time claiming it is needed.
