### ISSUE TITLE
Other unanswered questions in cherry-picks.md

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/community#1894]
I made a PR against the master branch of kubernetes, and it needs to be cherry-picked to some older releases.  I have read https://github.com/kubernetes/community/blob/master/contributors/devel/cherry-picks.md but it leaves me with some questions.

cherry-picks.md says, in the section on "Propose a Cherry Pick", that "Cherrypicks are managed with labels and milestones", and the last part is a hyperlink to https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md --- which is probably not what is intended.

I am very much in the dark regarding labels and milestones.  cherry-picks.md says "first ensure the following labels are on the original master branch PR" but I do not know how to make that happen.  I do not even know whether it is something I do for myself (if so, how?) or something that I get somebody else to do (if so, who?).

When there are multiple releases that need a cherry-pick, cherry-picks.md does not say whether they are done serially  or in parallel.  As noted in #994, cherry-picks.md does not say how to handle multiple cherry-picks.

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-contributor-experience-bugs

**Comment by cblecker** [comment]
cc: @spiffxp

**Comment by nikhita** [comment]
/remove-lifecycle stale

There is a PR open to improve the cherrypicks doc.

**Comment by nikhita** [comment]
The cherry-pick doc recently went through a round of improvements in https://github.com/kubernetes/community/pull/2408 and https://github.com/kubernetes/community/pull/1980. It was also updated from the test-infra side so that the bot reacts with useful comments for cherry-pick PRs https://github.com/kubernetes/test-infra/pull/9128.

Closing as this is now done.
/close
