### ISSUE TITLE
Umbrella issue for reviews

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#1899]
This tracks issues/content for the "How to do reviews the Kubernetes Way" section of the contributor's guide:

Known Docs:
- [Tim’s (thockin) Live Code Review](https://docs.google.com/document/d/1WVobATuodV0T3F22CXhsdYpOk5K7D-uKO9j-0QUuLdU/edit#heading=h.2oi459gj6360)
- Clayton's Review Notes will go here. 
- [BPs for better, faster reviews](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md#best-practices-for-faster-reviews)
- [Collaboration](https://github.com/kubernetes/community/blob/master/contributors/devel/collab.md)
- [GoLang Code Reviews](https://github.com/golang/go/wiki/CodeReview)
- [GoLang Code Review Comments](https://github.com/spiffxp/community/blob/09604a27aa2c50defe42592305b742649d74b577/contributors/devel/owners.md)
- [Code Reviews using OWNERS files](https://github.com/spiffxp/community/blob/09604a27aa2c50defe42592305b742649d74b577/contributors/devel/owners.md)
- [K8s Coding Conventions (file location may change)](https://github.com/kubernetes/community/blob/master/contributors/devel/coding-conventions.md)
- [Cherry Pick Reviews](https://github.com/kubernetes/community/blob/master/contributors/devel/cherry-picks.md)
- PR workflow [.dia](https://github.com/kubernetes/community/blob/master/contributors/devel/pr_workflow.dia) and [.png](https://github.com/kubernetes/community/blob/master/contributors/devel/pr_workflow.png)
- [K8s Bot Commands](https://github.com/kubernetes/test-infra/blob/master/commands.md)
Watching for release-note needed changes, how to feed into the docs process

### Docs/Guides/Content Needed
Common problems?
Discourse in / on PRs, issues, etc. - good, bad, ugly?

### Kops
- Vendoring is different between subprojects. kubernetes/kubernetes uses godep, we use submodules, and maybe dep soon
- docs are generated differently in kubernetes/kubernetes and this causes some confusion with new contributors with code generated docs.
- CI is different with Travis runs, and e2e is sorta the same, but tests kops differently
- our integration testing framework with terraform is unique, because how we are testing that install works, instead of testing that k8s works
- API modifications and additions are far less formal in kops than other projects but are still reviewed with a lot of deliberate focus.

### Charts

[Helm Charts](https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md)

### Docs

[Tech Reviewers for Docs](https://docs.google.com/presentation/d/1RxXC2V74c4b6DBJwsgAn-y33WlDLk1_XRLc-fxWm9y0/edit?usp=sharing_eil&ts=5a9d06d1)

### External Resources (that can be used?)

[Practical Lessons in Code Reviews](https://medium.com/@salsita/practical-lessons-in-peer-code-review-b4dbc84e88d3)
[@math_rachel tweet](https://twitter.com/math_rachel/status/939968380202762240) - reach out to paris for credit copy

**Comment by parispittman** [comment]
Note - we are scheduling Clayton for an API live code review session. We will have those notes to add, too.

**Comment by guineveresaenger** [comment]
Related issues:
#1645 
#1514

1514 should be scrubbed for any content that isn't duplicate here, and then closed, it feels like it's the same issue.

**Comment by markyjackson-taulia** [comment]
@vishakhanihore this also falls under #3064 Do you want to take this as well?

**Comment by mrbobbytables** [comment]
closing this, should be resolved by #3064 4831 👍 

/close
