### ISSUE TITLE
Deprecate kubernetes-incubator in favor of kubernetes-sigs

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#1922]
/committee steering
/sig contributor-experience
/assign
ref: kubernetes/test-infra#7184

We have https://github.com/kubernetes/community/blob/master/kubernetes-repositories.md sorta spelling out kubernetes-sigs, and we have https://github.com/kubernetes/community/blob/master/incubator.md spelling out kubernetes-incubator.

There's been lots of mailing list and meeting talk about deprecating incubator and instead using kubernetes-sigs as the way forward.  But we're sorta lacking in official looking docs

I'd like to:
- ~add a note to incubator calling it deprecated~
- add a note to our list of orgs calling out kuberentes-sigs in use
- spell out the process to get a new repo created in kubernetes-sigs
  - consensus from sig leads
  - (process debt cleanup) spell out subprojects owned by sig
  - e-mail steering committee asking for repo to be created
  - start repo based on kubernetes-template-project

**Comment by spiffxp** [comment]
https://github.com/kubernetes/community/pull/1979 calls incubator deprecated

**Comment by spiffxp** [comment]
/lifecycle frozen
Bumping in recency as this came up during the most recent steering meeting

**Comment by spiffxp** [comment]
/area github-management
There are 15 repos left in kubernetes-incubator.
- [kubernetes-incubator/apiserver-builder-alpha](https://github.com/kubernetes-incubator/apiserver-builder-alpha) - sig-api-machinery
- [kubernetes-incubator/bootkube](https://github.com/kubernetes-incubator/bootkube) - sig-cluster-lifecycle
- [kubernetes-incubator/cluster-capacity](https://github.com/kubernetes-incubator/cluster-capacity) - sig-scheduling
- [kubernetes-incubator/cluster-proportional-autoscaler](https://github.com/kubernetes-incubator/cluster-proportional-autoscaler) - sig-autoscaling
- [kubernetes-incubator/cluster-proportional-vertical-autoscaler](https://github.com/kubernetes-incubator/cluster-proportional-vertical-autoscaler) - sig-autoscaling
- [kubernetes-incubator/custom-metrics-apiserver](https://github.com/kubernetes-incubator/custom-metrics-apiserver) - sig-instrumentation
- [kubernetes-incubator/descheduler](https://github.com/kubernetes-incubator/descheduler) - sig-scheduling
- [kubernetes-incubator/external-dns](https://github.com/kubernetes-incubator/external-dns) - sig-network
- [kubernetes-incubator/external-storage](https://github.com/kubernetes-incubator/external-storage) - sig-storage
- [kubernetes-incubator/ip-masq-agent](https://github.com/kubernetes-incubator/ip-masq-agent) - sig-network
- [kubernetes-incubator/kube-aws](https://github.com/kubernetes-incubator/kube-aws) - sig-cluster-lifecycle
- [kubernetes-incubator/metrics-server](https://github.com/kubernetes-incubator/metrics-server) - sig-instrumentation
- [kubernetes-incubator/reference-docs](https://github.com/kubernetes-incubator/reference-docs) - sig-docs
- [kubernetes-incubator/rktlet](https://github.com/kubernetes-incubator/rktlet) - sig-node
- [kubernetes-incubator/spartakus](https://github.com/kubernetes-incubator/spartakus) - unowned?

The automation between these orgs is the same.  I think it's time for us to reach out to the owning sigs and ask them to migrate or retire these repos

**Comment by parispittman** [comment]
i thought steering owned spartakus? https://github.com/kubernetes/community/tree/master/committee-steering

**Comment by neolit123** [comment]
> kubernetes-incubator/kube-aws - sig-cluster-lifecycle

from the readme:
https://github.com/kubernetes-incubator/kube-aws#kubernetes-incubator

> SIG: sig-aws

recently there was a discussion with the slack user `dominic` (can't find the link), who wanted to ask if the repo can be graduated out of incubator. sig cluster-lifecycle probably won't take the project as it overlaps with kops, but i cannot speak for the chairs.

on the other hand, Andrew Kim gave feedback that SIG Cloud Provider can potentially take it.
(sig-aws folded into sig-cloud-provider).

**Comment by spiffxp** [comment]
@neolit123 I'm going off of what is currently listed in sigs.yaml and shows up in each SIG's README.md

**Comment by jimangel** [comment]
:wave: Hey! I just opened this issue to kick off the migration of our ref-docs: https://github.com/kubernetes/org/issues/1158

I would like to wait until 1.16 goes out the door and have some docs folks review the permissions suggested... but we should be good to go after that!

**Comment by mrbobbytables** [comment]
descheduler has now been migrated to kubernetes-sigs
ref: https://github.com/kubernetes/org/issues/1176

**Comment by mrbobbytables** [comment]
reference docs has now been migrated to kubernetes-sigs
ref: https://github.com/kubernetes/org/issues/1158

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/community/pull/4700 to suggest that the kubernetes-incubator/cluster-proportional* projects move to sig-network

**Comment by spiffxp** [comment]
https://cs.k8s.io/?q=kubernetes-incubator&i=nope&files=&repos= there are still many references, need a human to verify which of these shouldn't be renamed (history) vs. which should (or could)

**Comment by mrbobbytables** [comment]
If you remove the kubernetes-incubator/kube-aws repo from the list it looks like its a lot less. Quite a few in k/website blog posts which we can ignore

[Massive Query URL](
https://cs.k8s.io/?q=kubernetes-incubator&i=nope&files=&repos=kubernetes-client/.github,kubernetes-client/c,kubernetes-client/csharp,kubernetes-client/gen,kubernetes-client/go,kubernetes-client/go-base,kubernetes-client/haskell,kubernetes-client/java,kubernetes-client/javascript,kubernetes-client/perl,kubernetes-client/python,kubernetes-client/python-base,kubernetes-client/ruby,kubernetes-csi/.github,kubernetes-csi/cluster-driver-registrar,kubernetes-csi/csi-driver-fibre-channel,kubernetes-csi/csi-driver-flex,kubernetes-csi/csi-driver-host-path,kubernetes-csi/csi-driver-image-populator,kubernetes-csi/csi-driver-iscsi,kubernetes-csi/csi-driver-nfs,kubernetes-csi/csi-driver-smb,kubernetes-csi/csi-lib-fc,kubernetes-csi/csi-lib-iscsi,kubernetes-csi/csi-lib-utils,kubernetes-csi/csi-proxy,kubernetes-csi/csi-release-tools,kubernetes-csi/csi-test,kubernetes-csi/docs,kubernetes-csi/driver-registrar,kubernetes-csi/drivers,kubernetes-csi/external-attacher,kubernetes-csi/external-health-monitor,kubernetes-csi/external-provisioner,kubernetes-csi/external-resizer,kubernetes-csi/external-snapshotter,kubernetes-csi/kubernetes-csi.github.io,kubernetes-csi/livenessprobe,kubernetes-csi/node-driver-registrar,kubernetes-sigs/alibaba-cloud-csi-driver,kubernetes-sigs/apiserver-builder-alpha,kubernetes-sigs/apiserver-network-proxy,kubernetes-sigs/application,kubernetes-sigs/aws-alb-ingress-controller,kubernetes-sigs/aws-ebs-csi-driver,kubernetes-sigs/aws-efs-csi-driver,kubernetes-sigs/aws-encryption-provider,kubernetes-sigs/aws-fsx-csi-driver,kubernetes-sigs/aws-iam-authenticator,kubernetes-sigs/azuredisk-csi-driver,kubernetes-sigs/azurefile-csi-driver,kubernetes-sigs/blob-csi-driver,kubernetes-sigs/bootkube,kubernetes-sigs/boskos,kubernetes-sigs/cli-experimental,kubernetes-sigs/cli-utils,kubernetes-sigs/clientgofix,kubernetes-sigs/cloud-provider-azure,kubernetes-sigs/cloud-provider-baiducloud,kubernetes-sigs/cloud-provider-huaweicloud,kubernetes-sigs/cluster-addons,kubernetes-sigs/cluster-api,kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm,kubernetes-sigs/cluster-api-provider-aws,kubernetes-sigs/cluster-api-provider-azure,kubernetes-sigs/cluster-api-provider-digitalocean,kubernetes-sigs/cluster-api-provider-docker,kubernetes-sigs/cluster-api-provider-gcp,kubernetes-sigs/cluster-api-provider-ibmcloud,kubernetes-sigs/cluster-api-provider-openstack,kubernetes-sigs/cluster-api-provider-packet,kubernetes-sigs/cluster-api-provider-vsphere,kubernetes-sigs/cluster-capacity,kubernetes-sigs/cluster-proportional-autoscaler,kubernetes-sigs/cluster-proportional-vertical-autoscaler,kubernetes-sigs/contributor-playground,kubernetes-sigs/contributor-site,kubernetes-sigs/controller-runtime,kubernetes-sigs/controller-tools,kubernetes-sigs/cri-tools,kubernetes-sigs/custom-metrics-apiserver,kubernetes-sigs/dashboard-metrics-scraper,kubernetes-sigs/descheduler,kubernetes-sigs/discuss-theme,kubernetes-sigs/downloadkubernetes,kubernetes-sigs/etcdadm,kubernetes-sigs/execution-hook,kubernetes-sigs/external-dns,kubernetes-sigs/gcp-compute-persistent-disk-csi-driver,kubernetes-sigs/gcp-filestore-csi-driver,kubernetes-sigs/gluster-block-external-provisioner,kubernetes-sigs/gluster-file-external-provisioner,kubernetes-sigs/go-open-service-broker-client,kubernetes-sigs/image-builder,kubernetes-sigs/ingress-controller-conformance,kubernetes-sigs/ip-masq-agent,kubernetes-sigs/iptables-wrappers,kubernetes-sigs/k8s-container-image-promoter,kubernetes-sigs/kind,kubernetes-sigs/krew,kubernetes-sigs/krew-index,kubernetes-sigs/kube-batch,kubernetes-sigs/kube-storage-version-migrator,kubernetes-sigs/kubebuilder,kubernetes-sigs/kubebuilder-declarative-pattern,kubernetes-sigs/kubebuilder-release-tools,kubernetes-sigs/kubefed,kubernetes-sigs/kubespray,kubernetes-sigs/kustomize,kubernetes-sigs/legacyflag,kubernetes-sigs/mdtoc,kubernetes-sigs/metrics-server,kubernetes-sigs/minibroker,kubernetes-sigs/multi-tenancy,kubernetes-sigs/mutating-trace-admission-controller,kubernetes-sigs/nfs-ganesha-server-and-external-provisioner,kubernetes-sigs/nfs-subdir-external-provisioner,kubernetes-sigs/node-feature-discovery,kubernetes-sigs/node-feature-discovery-operator,kubernetes-sigs/poseidon,kubernetes-sigs/reference-docs,kubernetes-sigs/release-notes,kubernetes-sigs/scheduler-plugins,kubernetes-sigs/seccomp-operator,kubernetes-sigs/secrets-store-csi-driver,kubernetes-sigs/service-apis,kubernetes-sigs/service-catalog,kubernetes-sigs/sig-storage-lib-external-provisioner,kubernetes-sigs/sig-storage-local-static-provisioner,kubernetes-sigs/sig-usability,kubernetes-sigs/sig-windows-tools,kubernetes-sigs/slack-infra,kubernetes-sigs/structured-merge-diff,kubernetes-sigs/vsphere-csi-driver,kubernetes-sigs/wg-policy-prototypes,kubernetes-sigs/windows-gmsa,kubernetes-sigs/windows-testing,kubernetes-sigs/yaml,kubernetes-sigs/zeitgeist,kubernetes/.github,kubernetes/api,kubernetes/apiextensions-apiserver,kubernetes/apimachinery,kubernetes/apiserver,kubernetes/autoscaler,kubernetes/cli-runtime,kubernetes/client-go,kubernetes/cloud-provider,kubernetes/cloud-provider-alibaba-cloud,kubernetes/cloud-provider-aws,kubernetes/cloud-provider-gcp,kubernetes/cloud-provider-openstack,kubernetes/cloud-provider-sample,kubernetes/cloud-provider-vsphere,kubernetes/cluster-bootstrap,kubernetes/cluster-registry,kubernetes/code-generator,kubernetes/community,kubernetes/component-base,kubernetes/controller-manager,kubernetes/cri-api,kubernetes/csi-api,kubernetes/csi-translation-lib,kubernetes/dashboard,kubernetes/dns,kubernetes/enhancements,kubernetes/examples,kubernetes/frakti,kubernetes/funding,kubernetes/gengo,kubernetes/git-sync,kubernetes/ingress-gce,kubernetes/ingress-nginx,kubernetes/k8s.io,kubernetes/klog,kubernetes/kompose,kubernetes/kops,kubernetes/kube-aggregator,kubernetes/kube-controller-manager,kubernetes/kube-openapi,kubernetes/kube-proxy,kubernetes/kube-scheduler,kubernetes/kube-state-metrics,kubernetes/kubeadm,kubernetes/kubectl,kubernetes/kubelet,kubernetes/kubernetes,kubernetes/kubernetes-template-project,kubernetes/legacy-cloud-providers,kubernetes/metrics,kubernetes/minikube,kubernetes/mount-utils,kubernetes/node-api,kubernetes/node-problem-detector,kubernetes/org,kubernetes/perf-tests,kubernetes/publishing-bot,kubernetes/release,kubernetes/repo-infra,kubernetes/sample-apiserver,kubernetes/sample-cli-plugin,kubernetes/sample-controller,kubernetes/security,kubernetes/sig-release,kubernetes/steering,kubernetes/system-validators,kubernetes/test-infra,kubernetes/utils,kubernetes/website)

**Comment by mrbobbytables** [comment]
I've [created an issue](https://github.com/kubernetes/website/issues/24380) on k/website wrt to updating references to incubator. With that out of the way, do you think we can go ahead and close this issue?

**Comment by nikhita** [comment]
> I've created an issue on k/website wrt to updating references to incubator. With that out of the way, do you think we can go ahead and close this issue?

There were a few migrated repos in k-sigs that still referenced kubernetes-incubator. I have created issues (linked above) in each of these repos.

The repo maintainers can follow up on those separately. Going to close this issue! :tada: 

/close
