### ISSUE TITLE
ContribEx SIG Leadership Composition Changes

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#1924]
Per the new charter template guidance from the Steering Committee, this issue is to change the following after we need to gain consensus via mailing list:
- [] README.md
- [] sigs.yaml
- [] anything else?

Changing SIG Lead title to Chair:
@Phillels and @parispittman

Nominating @cblecker to Technical Lead
Moving @grodrigues3 to Technical Lead from SIG Lead

Declaring subproject owners:
SIG Planning (/sig-contributor-experience)
Chairs and TLs

Contributor Documentation (/contributors)
@castrojo 

Contributor Automation and Workflow
TLs

Events (/events)
@castrojo @parispittman

Mentoring (/mentoring)
@parispittman

Communication Channels (/communication)
@castrojo, @parispittman

DevStats (setting up README info soon)
@phillels

After the consensus via mailing list is achieved, we will update the above docs and close this issue.

/sig contributor-experience

**Comment by jdumars** [comment]
Approving @cblecker to the SIG-Leads group per this thread.
