### ISSUE TITLE
Improve docs for generators

### ISSUE THREAD

**Issue by php-coder** [kubernetes/community#1965]
Documentation for generators could be improved by explaining more details about how it works.

**Steps to reproduce:**
- Read https://github.com/kubernetes/community/blob/master/contributors/devel/api_changes.md#generate-clientset
- Read https://github.com/kubernetes/community/blob/master/contributors/devel/generating-clientset.md
- Try to move internal types from one API group to another

**Expected result:**
PROFIT!

**Actual result:**
Generated [clientsets use old types and don't compile](https://github.com/kubernetes/kubernetes/pull/61608#issuecomment-375765633):

> W0323 18:55:08.870] pkg/client/clientset_generated/internalclientset/typed/extensions/internalversion/podsecuritypolicy.go:38:42: undefined: extensions.PodSecurityPolicy

In this case, it's unclear what the logic it uses and why it doesn't use types from a new API group.

@kubernetes/sig-api-machinery-misc

**Comment by php-coder** [comment]
My initial problem was resolved by manually removing some files. IMHO we still need more detailed documentation.

**Comment by sttts** [comment]
@php-coder which files did you remove?

**Comment by php-coder** [comment]
- `pkg/client/listers/extensions/internalversion/podsecuritypolicy.go`
- `pkg/client/informers/informers_generated/internalversion/extensions/internalversion/podsecuritypolicy.go`
- `pkg/client/clientset_generated/internalclientset/typed/extensions/internalversion/podsecuritypolicy.go`
- `pkg/client/clientset_generated/internalclientset/typed/extensions/internalversion/fake/fake_podsecuritypolicy.go`
