### ISSUE TITLE
possible relnotes improvements

### ISSUE THREAD

**Issue by tpepper** [kubernetes/community#1971]
While reviewing the draft 1.10 release notes I had the following thoughts for future enhancements:

* add a table of contents:  this does appear to happen as they render elsewhere later in the publication flow, but would make some aspects of review easier on this very long document
* add a security section (could relate to issue #1568 to have a special notation so these are easily queried for the notes)
* add sections for new alpha, graduated alpha to beta, and graduated beta to ga items
* build a linter to check basic misspeillings, backticking of dash dash command line parameters, probably many many other things the rel note wrangler regularly manually does

/sig docs

**Comment by nikhita** [comment]
> build a linter to check basic misspeillings

I think we already have a script like this in k/k and probably k/community.

**Comment by tpepper** [comment]
Yep I think in early May 2018 or so misspell came into checks.

**Comment by jeefy** [comment]
@tpepper Do you think this issue could be closed? It was kind of an umbrella issue and a lot of these things have or are being addressed/tracked in separate issues. 🤔

**Comment by jeefy** [comment]
Created an issue for the final unfinished part of this list. Everything else has been or is in the process of being addressed. :)
