### ISSUE TITLE
Improve Documentation - What is a sig and what the sigs are

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/community#1976]
/sig contribex

I would love to see a document that basically can guide a new member to what sigs they should attend.  Elevator pitch for each sig, and a blurb about what a sig is.

https://github.com/kubernetes/community/blob/master/sig-list.md

I think is all we have now, but to a new user wth is this sig actually do.  Big question.

**Comment by parispittman** [comment]
This is documented here -> https://github.com/kubernetes/community/blob/master/governance.md

There is work going on in several issues, #1986 #1994 , et al around sig process, wg defintion, etc. and once that is complete, we will rework the top of the sig list doc to add better discoverability to those definitions once they are set. @chrislovecnm - ok to close knowing this?
