### ISSUE TITLE
CLA "edge cases" and how to approach them

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/community#2012]
Howdy! I wanted to open this up in `k/community`, but there's also a superset-ey, omnibus issue around CLAs in kubernetes/kubernetes#27796.

I'm not sure if this is the best place to discuss this, but some interesting cases for contributors are when they:
- transition from individual contributor to employee contributor (or vice versa)
- transition to another company e.g., Red Hat acquisition of CoreOS

I'm personally still under the CoreOS CLA, because I'm concerned that there isn't a well defined process for transitioning to another company, and I don't want to impede my ability to contribute.

There are some great comments on that omnibus thread that ask similar questions:
- https://github.com/kubernetes/kubernetes/issues/27796#issuecomment-327943347
- https://github.com/kubernetes/kubernetes/issues/27796#issuecomment-365554340

It appears that the silver bullet is to contact helpdesk@rt.linuxfoundation.org for assistance, but it would be nice to actually document some of these use cases, so people know what to expect when hitting them (which I'm happy to help do).

Some things I noticed about the Linux Foundation ID:
- one username
- if you're using GitHub as your auth provider (which I did, not sure if that's strictly required or not) then it would make sense that you could only connect that GH account to a single LF identity
- required to use my work email to sign up for the account and the CKA exam
- doesn't appear to support transitioning the account to a different company CLA without helpdesk intervention

It would be cool if I could sign up for one account that held multiple identities (personal, work, etc.) and supported transitioning between different contributor types.

(I'm happy to move this somewhere else, if there's a more appropriate place for this issue.)

cc: @dankohn 

ref:
- #1794 
- kubernetes/kubernetes#27796

/sig contributor-experience
/area contributor-guide

**Comment by dankohn** [comment]
We're in the process of finishing development of an open source replacement for the CLAbot. It will still have corner cases where you'll need to escalate things to the helpdesk, but hopefully less over time.

I'd suggest reaching out to @alanapost who is the product manager for the development. I can connect you by email if you email me. In general, we'd be happy to hear your use case and see if we could better accommodate either when we roll out the new CLAbot or in a later update.

**Comment by guineveresaenger** [comment]
#1636 is related and can be incorporated in a fix for this issue, I think.

**Comment by nikhita** [comment]
/remove-lifecycle stale

cc @idvoretskyi

**Comment by parispittman** [comment]
any edge cases need to go to the LF at this time and that documentation has no been entered into docs and bots

/close
