### ISSUE TITLE
Add several already-in-use kind labels to official list

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#2013]
The following kind/ labels are already in wide use in the project, have meaning, and as such should be available in the official master list of labels:

* kind/cleanup: A refactoring, API reorganization, dependency version upgrade, or other "maintenance" code change.
* kind/design: Specifications, API designs, plans for new components and APIs.
* kind/api-change: changes to an existing API, important to track for conformance/compatibility.  Used by SIG-arch, SIG-API
* kind/new-api: brand new APIs, should be pretty rare, but important.  Used by SIG-arch

This is in addition to kind/failing-test and kind/flake, as proposed in #1579.

The following two kind labels are also in use, but should be marked as "deprecated" as they are duplicative of other labels:

* kind/enhancement: duplicates kind/feature
* kind/technical-debt: duplicates kind/cleanup

If this is approved, I'll open a PR against test-infra with the changes.

**Comment by jberkus** [comment]
I actually want to modify this issue, based on how kind/ label usage changed in 1.11

**Comment by spiffxp** [comment]
Can we close this in favor of https://github.com/kubernetes/community/issues/2032 ?

**Comment by jberkus** [comment]
It's part of 2032

**Comment by jberkus** [comment]
UPDATED to include kind/api-change and kind/new-api per discussion
