### ISSUE TITLE
Lable kind/support should be renamed to triage/*

### ISSUE THREAD

**Issue by spzala** [kubernetes/community#2014]
We now have a series of triage labels towards identifying and closing issues that do not need an actual fix. These labels also provides a way to measure such issues. https://github.com/kubernetes/test-infra/pull/7554
Since kind/support is for issue triage it should be renamed with prefix triage and have it as part of triage series of labels e.g. rename it to triage/support-request. We had some discussion around it under kubernetes/community#1970 and I am opening this issue to have discussion around it separately.
@spiffxp @cblecker @jberkus @parispittman

**Comment by cblecker** [comment]
Closing this as part of #2032
