### ISSUE TITLE
Moderation docs for mailing lists

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#2028]
Contributor Experience is going to take on the moderation of non-sig/wg community mailing lists. This includes k-dev and k-users. We need to write down some basic moderation guidelines for it - the how, who, and what we do. One of two things: 1-new file under /communication for this or 2-combine with slack guidelines for a main moderation doc. 

/sig contributor-experience

**Comment by castrojo** [comment]
Something like this perhaps: https://support.mozilla.org/en-US/kb/moderation-guidelines

**Comment by bgrant0607** [comment]
Why not moderate the sig/wg lists also?

**Comment by parispittman** [comment]
We would need to be set to admin on all of those lists. If that's the direction that we should go in, we'll need to get all of the chairs/leads to give us permission and also figure out how to divvy up the work since there are so many lists.

**Comment by bgrant0607** [comment]
We should do that. It would reduce the bus factor, also.

**Comment by castrojo** [comment]
https://github.com/kubernetes/community/blob/master/communication/moderation.md is our first draft for it, is there anything specific we need to add?

**Comment by parispittman** [comment]
We need to add the mailing list guidelines and specifics on moderation. ie - add us to their mailing lists as owners, lock the thread before banning/removing someone so that no replies come in, etc.

**Comment by castrojo** [comment]
The ownership bits are covered here: https://github.com/kubernetes/community/blob/master/sig-governance.md#creating-a-mailing-list

I'll work up a PR on closing a thread.

**Comment by castrojo** [comment]
This is completed.
