### ISSUE TITLE
godep moved

### ISSUE THREAD

**Issue by grantbow** [kubernetes/community#2037]
`kubernetes/community/contributors/devel/development.md` line 156 is
`Kubernetes uses [`godep`](https://github.com/tools/godep) to manage`

`tools/godep/Readme.md` says to use `golang/dep` for go 1.9 and above.

/sig contributor-experience
/area contributor-guide

**Comment by cblecker** [comment]
We do currently use godep. godep and dep are completely different utilities, and we have not yet migrated from godep to dep. Not a documentation issue.

**Comment by grantbow** [comment]
I thought that might be the case, thank you very much for the clarification here. It might be able to describe this more clearly for newcomers like me who don't understand when they first see this. My first quick read of the information gave me a different impression. Then I reread it.

**Comment by cblecker** [comment]
@grantbow Feel free to open a PR to improve the wording. I'd gladly review it :)
