### ISSUE TITLE
Add link to relevant code tree(s) for each SIG

### ISSUE THREAD

**Issue by shubheksha** [kubernetes/community#2043]
It'll be very helpful to have a link to the code tree(s) from the repo(s) in the readme for each SIG to specify what part of the code they're responsible for.

**Comment by shubheksha** [comment]
As an addition, food for thought: would it make sense to add the open issues/PRs as well? Those are relatively easier to find compared to the code tree, but can be useful!

**Comment by shubheksha** [comment]
@chris-short, something like the code section here: https://github.com/kubernetes/community/blob/master/sig-storage/README.md#links

**Comment by nikhita** [comment]
@shubheksha Bump about https://github.com/kubernetes/community/issues/2043#issuecomment-440950469 :)
