### ISSUE TITLE
guidance on commit message style

### ISSUE THREAD

**Issue by michelleN** [kubernetes/community#2050]
Would be great to add some guidance on what your commit message should look like when contributing a PR to [kubernetes/kubernetes](github.com/kubernetes/kubernetes) if there is a format/convention. Some repos have a specific commit message style that helps with generating release notes. See [this one](http://docs.deis.io/en/latest/contributing/standards/#commit-style) as an example.

**Comment by shubheksha** [comment]
We can expand the section or maybe spin a sub-section here: https://github.com/kubernetes/community/tree/master/contributors/guide#code-review?

**Comment by cblecker** [comment]
I don't believe we have any convention for commit messages to k/k. We handle release notes through the Github PR body.

**Comment by castrojo** [comment]
I agree that this should part of the contributor guide. 

@tpepper - you spent some time mentoring me with some great tips, maybe we can work on this together as a default recommendation? 

/area contributor-guide

**Comment by tpepper** [comment]
I like the Deis example, although I'm not sure why there's a "footer", unless it was meant to be preceded by a line with '''---''' for '''git-send-email''' usage as described for example in the section '''The canonical patch format''' of the [linux kernel patch submission guidelines](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/submitting-patches.rst).  Also [this one](https://github.com/ciao-project/ciao/blob/master/CONTRIBUTING.md) from a past project I worked on.

I feel like the internet has sort of resolved onto [Chris Beams' write up](https://chris.beams.io/posts/git-commit/) as the canonical answer to this problem.  That's referenced in the [code review](https://github.com/kubernetes/community/blob/master/contributors/guide/README.md) section of the contrib guide.  There we opted to be concise, arguably to a fault.  I think more details would fall nicely into the [pull request doc](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md).

**Comment by tpepper** [comment]
Also it's worth noting that there hasn't been / is not a rigorous format convention today if you look though k/k and other k/* repos.  I for one would very very very much welcome the start of a format convention like those linked above.  But does that become something for steering?  There's bound to be at least some push back to the idea and it only becomes convention if it's widely used, which at one end of the spectrum argues for test automation or at the other end buy in from sufficient number of approvers to accomplish equivalent less forcefully.  Personally I like automation because it's clear and immediate feedback, especially when enabled on your own forks' branches.

**Comment by nikhita** [comment]
Bumping this again.

Looks like this should go as an email to the steering and the sig-contribex lists.

**Comment by nikhita** [comment]
> Would be great to add some guidance on what your commit message should look like

maybe the contributor guide could just "suggest" the changes and not enforce a certain style? Enforcing a certain style doesn't provide any tangible benefit per se (with respect to release notes, etc) but is a nice-to-have.

**Comment by vishakhanihore** [comment]
> > Would be great to add some guidance on what your commit message should look like
> 
> maybe the contributor guide could just "suggest" the changes and not enforce a certain style? Enforcing a certain style doesn't provide any tangible benefit per se (with respect to release notes, etc) but is a nice-to-have.

Noted, Working on it. 

/assign
