### ISSUE TITLE
Add link to sig-list when an incorrect `sig/` command OR when the `needs-sig` label is added to an issue/PR

### ISSUE THREAD

**Issue by shubheksha** [kubernetes/community#2083]
Not sure if this is the correct repo for this issue. If it isn't, please let me know what would be the right place to file it.

Whenever the @k8s-ci-robot adds a `needs-sig` label, can we link to the list of sigs as well? A lot of people aren't aware of what a SIG is or what labels exist, so some background about that would be very useful while filing issues. It would save overhead while triaging. I often see ppl using `sig/pod`, `sig/networking` etc., 
OR can we display the sig list in response to an incorrect sig label being added?

**Comment by cblecker** [comment]
@shubheksha If you click the "Details" link above, there should be a link to the group list. Did you know that before? I'm thinking we just need to make that more discoverable.

**Comment by shubheksha** [comment]
@cblecker, nope, I didn't - that's a good idea.

**Comment by nikhita** [comment]
> I'm thinking we just need to make that more discoverable.

Is something still needed to be done here? Would non-toggling "Details" make it too spammy?

**Comment by shubheksha** [comment]
I believe this was addressed. It's not toggled anymore and is much more intuitive, so closing this :)
<img width="790" alt="image" src="https://user-images.githubusercontent.com/7693422/45955447-8efff300-c02d-11e8-9cef-93407e04c787.png">
