### ISSUE TITLE
write/admin access for cloud-provider-openstack

### ISSUE THREAD

**Issue by dims** [kubernetes/community#2088]
Can you please add the sig leads of sig-openstack as admins for cloud-provider-openstack? they are listed here:

https://github.com/kubernetes/community/tree/master/sig-openstack

/assign @spiffxp

**Comment by dims** [comment]
cc @hogepodge

**Comment by hogepodge** [comment]
Not sure if the sig-openstack label is appropriate for this issue, since it impacts us but we're not responsible for the merge. Add if necessary.

**Comment by cblecker** [comment]
Based on https://github.com/kubernetes/community/blob/master/org-owners-guide.md#team-guidance, I've created the teams https://github.com/orgs/kubernetes/teams/cloud-provider-openstack-admins and https://github.com/orgs/kubernetes/teams/cloud-provider-openstack-maintainers.. I'll let @spiffxp review give the thumbs up on ensuring the right people are added to those teams

**Comment by spiffxp** [comment]
Thanks for creating the teams @cblecker 

After discussing with @dims on slack, I added the leads from sig-openstack who are in https://github.com/kubernetes/cloud-provider-openstack/blob/master/OWNERS

They're in @kubernetes/cloud-provider-openstack-admins and @kubernetes/cloud-provider-openstack-maintainers as team maintainers so they can add/remove people from those teams as they see fit

/unassign
/assign @dims 
to verify this looks good and /close if so

**Comment by dims** [comment]
Looks good. thanks @spiffxp 

/close
