### ISSUE TITLE
The content of the new contributor workshop should be available online

### ISSUE THREAD

**Issue by thkoch2001** [kubernetes/community#2100]
[events/2018/05-contributor-summit/new-contributor-workshop.md](https://github.com/kubernetes/community/blob/master/events/2018/05-contributor-summit/new-contributor-workshop.md) looks like a great agenda to cover everything a new contributor wants to know. Are we sure that all of this is also documented and easily discoverable?

**Comment by jberkus** [comment]
We need to add a whole bunch of notes to the slides, at which point they will be available too.

**Comment by guineveresaenger** [comment]
We have a slide deck from Seattle linked in https://github.com/cncf/presentations/tree/master/kubernetes
and we will also have a recording somewhere.

I will come up with a good place to make this discoverable in the new year!

**Comment by idealhack** [comment]
https://github.com/kubernetes-sigs/contributor-playground/pull/213

**Comment by guineveresaenger** [comment]
Closing this because content is posted in contributor playground:
https://github.com/kubernetes-sigs/contributor-playground/tree/master/presentations
/close
