### ISSUE TITLE
Update SIG PM Representatives list

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/community#2122]
I noticed that the [SIG PM Representatives list](https://github.com/kubernetes/community/blob/master/sig-product-management/SIG%20PM%20representatives.md) looks to be a little out-of-date.

Could everyone pop on this [Google Sheet](https://docs.google.com/spreadsheets/d/1ZlGoJtziFD-5JYTGlRjTvrAhY836G5nVwPxuba1yisM/edit?usp=sharing) and update any contact info (name, email, github handle, secondaries) and then I'll PR an update to the list?

Pinging the SIGs that are already on the list:
- [ ] @kubernetes/sig-api-machinery-misc 
- [ ] @kubernetes/sig-apps-misc 
- [ ] @kubernetes/sig-auth-misc  
- [ ] @kubernetes/sig-autoscaling-misc  
- [ ] @kubernetes/sig-aws-misc 
- [x] @kubernetes/sig-azure-misc 
- [ ] @kubernetes/sig-cli-misc 
- [x] @kubernetes/sig-cluster-lifecycle-misc  
- [ ] @kubernetes/sig-cluster-ops-misc
- [ ] @kubernetes/sig-contributor-experience-misc-use-only-as-a-last-resort  
- [x] @kubernetes/sig-docs-maintainers 
- [ ] @kubernetes/sig-multicluster-misc (from sig-federation)
- [ ] @kubernetes/sig-instrumentation-misc 
- [ ] @kubernetes/sig-network-misc 
- [ ] @kubernetes/sig-node-misc
- [ ] @kubernetes/sig-onprem-misc 
- [ ] @kubernetes/sig-openstack-misc  
- [x] @kubernetes/sig-scalability-misc 
- [ ] @kubernetes/sig-scheduling-misc 
- [ ] @kubernetes/sig-service-catalog-misc 
- [ ] @kubernetes/sig-storage-misc 
- [ ] @kubernetes/sig-testing-misc 
- [ ] @kubernetes/sig-ui-misc 
- [ ] @kubernetes/sig-windows-misc 

Feel free to check the box next to SIG, if your info is up-to-date! :)

/assign
/sig pm
/kind cleanup

**Comment by chenopis** [comment]
Done for @kubernetes/sig-docs-maintainers

**Comment by k82cn** [comment]
done for sig-scheduling :)

**Comment by justaugustus** [comment]
Bumping this for updates to the [SIG PM representatives contact sheet](https://docs.google.com/spreadsheets/d/1ZlGoJtziFD-5JYTGlRjTvrAhY836G5nVwPxuba1yisM/edit?usp=sharing)!

**Comment by luxas** [comment]
Done for SIG Cluster Lifecycle as well

**Comment by cjcullen** [comment]
Done for sig-auth.
