### ISSUE TITLE
Define responsibilities of a SIG PM representative

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/community#2130]
In the [SIG Governance / Creation doc](https://github.com/kubernetes/community/blob/master/sig-governance.md#sig-governance), we mention:
> Represent the SIG for the PM group

We should better define the responsibilities of a SIG PM representative, as this doesn't seem to be documented.

(this was a comment from @rsdcastro on this [Google Sheet](https://docs.google.com/spreadsheets/u/2/d/1ZlGoJtziFD-5JYTGlRjTvrAhY836G5nVwPxuba1yisM/edit?usp=sharing))

ref: #2122 
/assign @calebamiles @apsinha @idvoretskyi

**Comment by jdumars** [comment]
There is a lot in this that needs to be re-examined. First, SIG-PM is not in an organized enough state to demand such representation. Also, it is my belief that SIG-PM should be staffing the SIGs as needed, and not the other way around. Having an identified contact for SIGs with features in a release makes sense when questions arise, but I'm not sure of the other value.  @idvoretskyi may have a different opinion.

**Comment by parispittman** [comment]
+1 to Jaice's comment - In contribex, our members attend other sig meetings and spread the word as advocates. We tell folks to monitor our comms(mailing lists, etc.) but don't assign representation.
