### ISSUE TITLE
broken link in E2E docs on version skewed testing

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/community#2151]
The docs on doing version skewed e2e testing have a broken link.
https://github.com/kubernetes/community/blob/master/contributors/devel/e2e-tests.md#version-skewed-and-upgrade-testing

The link is to https://git.k8s.io/test-infra/jenkins/e2e-image/e2e-runner.sh but I can't find any e2e-runner.sh that talks about version skew testing.

/sig testing

**Comment by nikhita** [comment]
IIRC `e2e-runner.sh` was removed and it is recommended to use kubetest.

/cc @BenTheElder

**Comment by nikhita** [comment]
xref https://github.com/kubernetes/test-infra/issues/2829

**Comment by BenTheElder** [comment]
yes, using kubetest directly would be preferable, e2e-runner.sh is long gone AFAIK.
