### ISSUE TITLE
openshift

### ISSUE THREAD

**Issue by gbvikas** [kubernetes/community#2157]
How can we enable HPA in openshift 3.9? 

I tried the steps specified in https://github.com/stefanprodan/k8s-prom-hpa with few tweaks but 
doesnt work. The resources are not listed

oc get --raw "/apis/custom.metrics.k8s.io/v1beta1"
{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"custom.metrics.k8s.io/v1beta1","resources":[]}

oc get --raw "/apis/rbac.authorization.k8s.io/v1beta1"
{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"rbac.authorization.k8s.io/v1beta1","resources":[{"name":"clusterrolebindings","singularName":"","namespaced":false,"kind":"ClusterRoleBinding","verbs":["create","delete","deletecollection","get","list","patch","update","watch"]},{"name":"clusterroles","singularName":"","namespaced":false,"kind":"ClusterRole","verbs":["create","delete","deletecollection","get","list","patch","update","watch"]},{"name":"rolebindings","singularName":"","namespaced":true,"kind":"RoleBinding","verbs":["create","delete","deletecollection","get","list","patch","update","watch"]},{"name":"roles","singularName":"","namespaced":true,"kind":"Role","verbs":["create","delete","deletecollection","get","list","patch","update","watch"]}]}

/sig scalability

**Comment by cblecker** [comment]
Openshift is independent, and not supported by the Kubernetes project. You can find more information at https://www.openshift.org/.
---
/kind support
/close
