### ISSUE TITLE
update sigs.yaml with more wg info

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#2176]
It would be good to see if the WG is horizontal, domain-specific, etc. and maybe what SIGs they cross into on the [sigs/wg list](https://github.com/kubernetes/community/blob/master/sig-list.md). if folks are in agreement, we'd need to update sigs.yaml.

ie:

name  |  horizontal (y/n) OR list of cross cutting SIGs  |  contact  |  meeting info
---  |  ---  |  ---  |  ---

**Comment by jdumars** [comment]
+1

This distinction is becoming more important as sigs proliferate.

**Comment by parispittman** [comment]
I put the 'what it would look like' at the bottom of the issue. 
name  |  horizontal (y/n) OR list of cross cutting SIGs  |  contact  |  meeting info
---  |  ---  |  ---  |  ---

If it's the wg apply it would be something like:
apply | sig api machinery, sig foo | contact info | meeting info

We need this info to make sure we are getting regular updates from the wg's at the community meetings, auditing, and reviewing wgs, etc. and this would be an easy way to figure out that information.

**Comment by parispittman** [comment]
in order for a working group to be formed, they need to have sponsoring sigs so they are defined.

**Comment by cblecker** [comment]
If all WGs need sponsoring sigs, would listing "sponsoring sigs" work? I guess it's the "OR" bit that's confusing and unclear to me.

**Comment by parispittman** [comment]
Ah - I meant OR as a suggestion of a title - I'm 100% ok with "sponsoring sigs".

**Comment by cblecker** [comment]
/assign
I'll take a stab, probably next week.

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/steering/issues/27

**Comment by spiffxp** [comment]
We discussed during steering and were ok with adding a field.  Uncertain how clearly defined this list of sigs is for each wg

**Comment by zjs** [comment]
I looked through the resources linked to from the [sig-list](https://github.com/kubernetes/community/blob/master/sig-list.md) and organized the information about the relationships in the following table:

| Working Group | Working Group Name | Status | Relevant SIGs |
|--|--|--|--|
| wg-app-def | Application Definition | Inactive [[1]] | sig-api-machinery, sig-apps, sig-cli [[2]] |
| wg-apply | Apply | Unclear [[3]] | sig-cli [[3]] |
| wg-container-identity | Container Identity | Inactive [[4]] | sig-auth [[4]] |
| wg-iot-edge | IoT Edge | Active [[5], [6]] | sig-networking, sig-multicluster [[5]] |
| wg-kubeadmn-adoption | Kubeadm Adoption | Inactive [[7]] | sig-cluster-lifecycle [[7]] |
| wg-machine-learning | Machine Learning | Active [[8]] | sig-apps, sig-big-data, sig-node [[9]] |
| wg-multitenancy | Multitenancy | Active [[10]] | sig-auth, sig-api-machinery, sig-networking, sig-node, sig-scheduling, sig-storage [[11]] |
| wg-policy | Policy | Active [[12]] | sig-architecture, sig-auth, sig-network, sig-node, sig-on-premise, sig-multicluster, sig-scheduling, sig-storage, wg-multitenancy*, wg-resource-management* [[13]] |
| wg-resource-management | Resource Management | Active [[14]] | sig-autoscaling, sig-instrumentation, sig-networking, sig-note, sig-scheduling, sig-storage [[15]] |
| wg-security-audit | Security Audit | Active [[16]] | |

\*  - These are other working groups, but are included for completeness.

[1]:https://docs.google.com/document/d/1Pxc-qwAt4FvuISZ_Ib5KdUwlynFkGueuzPx5Je_lbGM/edit
[2]:https://docs.google.com/document/d/1J4NSpNCg0gj-Spg4ooUzSejZel8wH2WKpySCOrrtq0g/edit
[3]:https://docs.google.com/document/d/1j_UqnJRvB7AywfZauHybVVNCOoDDA1AGWGxzPGE08ko/edit
[4]:https://docs.google.com/document/d/1uH60pNr1-jBn7N2pEcddk6-6NTnmV5qepwKUJe9tMRo/edit
[5]:https://github.com/kubernetes/community/blob/master/wg-iot-edge/README.md
[6]:https://docs.google.com/document/d/1Yuwy9IO4X6XKq2wLW0pVZn5yHQxlyK7wdYBZBXRWiKI/edit
[7]:https://docs.google.com/document/d/1KdXsLYiJYJdiRbtgZsx6qbHF4g_K-gAScB9Zs4avgzg/edit
[8]:https://docs.google.com/document/d/1t2zTAehIEu3Xy8VJ6dc_cgODO4WGN-FDwpAfBjYCKc4/edit
[9]:https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-dev/lOeMjOLilxI/wuQayFDvCQAJ
[10]:https://docs.google.com/document/d/1fj3yzmeU2eU8ZNBCUJG97dk_wC7228-e_MmdcmTNrZY/edit
[11]:https://docs.google.com/document/d/1SkVdOPR4jozYDT8ro51hU3yrf1sHS8Gez73xM3PCsVo/edit
[12]:https://docs.google.com/document/d/1ihFfEfgViKlUMbY2NKxaJzBkgHh-Phk5hqKTzK-NEEs/edit
[13]:https://groups.google.com/forum/#!topic/kubernetes-dev/_xQBGm7IYs8
[14]:https://docs.google.com/document/d/1j3vrG6BgE0hUDs2e-1ZUegKN4W4Adb1B6oJ6j-4kyPU/edit
[15]:https://github.com/kubernetes/community/blob/master/wg-resource-management/README.md
[16]:https://github.com/kubernetes/community/blob/master/wg-security-audit/README.md

**Comment by nikhita** [comment]
@zjs Thanks!

/commitee steering
I guess steering still needs to weigh in on this (?)

**Comment by nikhita** [comment]
Created https://github.com/kubernetes/community/pull/3069 to try to move this forward. I think we still need input from steering and/or each WG on their stakeholder SIGs -- but I created the PR so that we can either iterate or start the discussion on it.

**Comment by parispittman** [comment]
@zjs - want to PR in each one of these individually for those that are still blank and then tag the appropriate chairs of the wg as the approvers? I'll send you a shirt or swag item of your choice after if you'd like. :)

**Comment by zjs** [comment]
@parispittman - I'd be happy to help with that, assuming it's not urgent; I'm on vacation next week, and I'm not sure I'll get to it before I leave.

**Comment by timothysc** [comment]
@parispittman - what else needs to get done here?

**Comment by parispittman** [comment]
hey @zjs - back from vacation and want to PR this?

**Comment by zjs** [comment]
Yes, @parispittman, I'll take a stab at that — and thank you for the ping.

**Comment by zjs** [comment]
@timothysc, the remaining work as I understand it is to generate a PR for each WG that doesn't have any stakeholder SIGs listed on the [SIG/WG list](https://github.com/kubernetes/community/blob/master/sig-list.md) based on our best guess (https://github.com/kubernetes/community/issues/2176#issuecomment-444623488) and get review from the chairs of the WG.

**Comment by zjs** [comment]
I've posted a set of PRs to fill in the blanks.

| Working Group | Pull Request | Notes |
|--|--|--|
| wg-apply | #3495 |  |
| wg-iot-edge | #3496 | See https://github.com/kubernetes/community/pull/3496#issuecomment-475094997 |
| wg-machine-learning | #3497 |  |
| wg-multitenancy | #3498 |  |
| wg-policy | #3499 | See https://github.com/kubernetes/community/pull/3499#issuecomment-475095091 |
| wg-resource-management | #3500 |  |

**Comment by nikhita** [comment]
@zjs just want to explicitly say thank you for all the work! And for the pretty table linking each pull request! :heart_eyes:

**Comment by nikhita** [comment]
Just needs one more PR for wg-security-audit and then this can be closed. :+1:

**Comment by nikhita** [comment]
/good-first-issue

@zjs if you want to take up wg-security-audit, feel free to remove the good first issue and help wanted label :)

**Comment by cji** [comment]
👋 Hello from wg-security-audit! I was reach out to on the kube slack by @nzoueidi about this issue and wanted to try and provide some clarification and ask questions about what makes sense to include for our WG.

The origin of the WG came from the proposal by CNCF and the PST starting with members of sig-auth to construct the wg. While sig-auth is definitely a stake holder in our results then, the audit being conducted is something that covers many (if not all) sig's in its results. 

Trying to better understand the intent here - Would it make sense to list them all? keep it to sig-auth as the originator? and/or use the new CNCF sig-security instead?

**Comment by parispittman** [comment]
@cji - i would just do sig-auth then. intent is for mapping sigs to wgs so we can get updates, points of contact, flow of info, etc. for organizational purposes.

**Comment by cji** [comment]
Thank you @parispittman !
