### ISSUE TITLE
Add two new Kubernetes repos for Korean and Japanese internationalization

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/community#2221]
## What we're asking for

SIG Docs would like to create two repos for localization of Kubernetes docs in Korean and Japanese: 

Language | Repo name
---|---
Japanese | kubernetes-docs-ja
Korean | kubernetes-docs-ko

The names match the existing format of kubernetes-docs-<[ISO 639-2 language code](https://www.loc.gov/standards/iso639-2/php/code_list.php)>. 

## Point(s) of contact

- @zacharysarah or @chenopis (SIG Docs leads) for docs process questions
- [Korean translation team channel](https://kubernetes.slack.com/messages/CA1MMR86S/details/) on Slack
- [Japanese translation team channel](https://kubernetes.slack.com/messages/CAG2M83S8/details/) on Slack

**Comment by cblecker** [comment]
Looking at our [current rules](https://github.com/kubernetes/community/blob/master/kubernetes-repositories.md#rules-1), this should be fine as long as sig-arch is good with it. This is in line with what we're already doing for CN localization.

cc: @kubernetes/sig-architecture-proposals

**Comment by chenopis** [comment]
Are we using country codes or language codes? `cn` is the country code for China, whereas `zh` is the language code for Chinese. `ko` is the language code for Korean, and `kr` is the country code for South Korea. If we go w/ the language code, then we should rename the `/content/cn` directory to `/content/zh`.

**Comment by zacharysarah** [comment]
@chenopis Good observation. If we go by language code, it also means renaming the Chinese repo to `kubernetes-docs-zh`, but I think that language is the more accurate way.

So:
Language | 2-letter code | Content directory | Official repo name
----------|---------------|------------------|---------------
Chinese | zh | `/content/zh/` | kubernetes-docs-zh (rename `kubernetes-docs-cn`)
Korean | ko | `/content/ko/` | kubernetes-docs-ko

**Comment by zacharysarah** [comment]
I just received a request to open a repo for a Japanese translation as well--updating the OP and comments with relevant info.

**Comment by bgrant0607** [comment]
How are we dealing with reviewers in the other languages? I found the cn docs just copied the en reviewers, which probably isn't of much use.

**Comment by zacharysarah** [comment]
@bgrant0607 Good question--I think it's reasonable to ask translation teams to strip reviewer/approver blocks from the front matter of individual files. Otherwise, as internationalizations scale up, reviewers will get increasingly bombarded by `@mentions`.

**Comment by nasa9084** [comment]
I'm translating into Japanese in [kubernetes-docs-ja/website](https://github.com/kubernetes-docs-ja/website) repository and want to merge when official repository is created or transfer ownership of this repository.

**Comment by zacharysarah** [comment]
@calebamiles @ixdy 👋 Bumping for action

**Comment by ixdy** [comment]
I don't have permissions to do this. As @cblecker noted above, it looks like you might need someone from sig-architecture to own this.

Tangentially: I'm guessing you want separate repos rather than using branches in the main docs repo because it makes things generally easier to deal with?

**Comment by cblecker** [comment]
@zacharysarah I can help you with this from a permissions standpoint, but repo creation in the `kubernetes/` org requires sign off from sig-architecture.

/unassign @calebamiles @ixdy 
/assign @bgrant0607 @jdumars 
Assigning to Brian and Jaice so they see this as still pending action.

**Comment by zacharysarah** [comment]
@ixdy 👋 
> Tangentially: I'm guessing you want separate repos rather than using branches in the main docs repo because it makes things generally easier to deal with?
Correct, partly because:
1. It makes sense for localization teams to review their own translation PRs, and the English docs team would only slow things down; and
2. Language-specific repos make it easier to automate content imports to [language-specific directories](https://gohugo.io/content-management/multilingual/) in k/website.

**Comment by zacharysarah** [comment]
@jdumars @bgrant0607 👋 Bumping for review.

**Comment by jdumars** [comment]
Approved SIG Architecture 7/12/18

**Comment by zacharysarah** [comment]
@cblecker 👋 Ping

**Comment by cblecker** [comment]
Created repos:
- https://github.com/kubernetes/kubernetes-docs-ja
- https://github.com/kubernetes/kubernetes-docs-ko

Created teams:
- @kubernetes/kubernetes-docs-ja-admins
- @kubernetes/kubernetes-docs-ja-maintainers
- @kubernetes/kubernetes-docs-ko-admins
- @kubernetes/kubernetes-docs-ko-maintainers

PR created for automation:
- https://github.com/kubernetes/test-infra/pull/8792

**Comment by cblecker** [comment]
I should also note, I copied the OWNERS file from the main website repo, and I also used the CC licence instead of the Apache 2.0, in line with our guidelines.
