### ISSUE TITLE
Broken links in serverside apply doc

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/community#2236]
I wanted to learn about this interesting work. But most of the links under proposal are broken.

https://github.com/kubernetes/community/blob/master/keps/0006-apply.md#proposal

**Comment by tamalsaha** [comment]
cc: @lavalamp @apelisse

**Comment by apelisse** [comment]
Thanks for reporting!

**Comment by tamalsaha** [comment]
Thanks for the quick fix.
