### ISSUE TITLE
There should be a field in sigs.yaml for location of charter

### ISSUE THREAD

**Issue by pmorie** [kubernetes/community#2243]
Currently the charter link is sprinkled into mission statement in many cases, while there is no first-class field for the location of a charter. We should add a first-class field for this information.

**Comment by nikhita** [comment]
Isn't the location of the charter of a sig always at community/sig-YOURSIG/charter.md? Ref: https://github.com/kubernetes/community/blob/master/committee-steering/governance/README.md#steps-to-create-a-sig-charter

**Comment by nikhita** [comment]
However, I guess it would be nice to mention the link to the charter in the sig readme though. Perhaps something like this in `sig_readme.tmpl`?

```
### Charter
The [charter](https://git.k8s.io/community/{{.Dir}}/charter.md) defines the scope and governance of SIG-{{.Name}}.
```

**Comment by pmorie** [comment]
> Isn't the location of the charter of a sig always at community/sig-YOURSIG/charter.md

A month or so ago, there wasn't a uniform term for this document that was in use. I think there are likely a couple different conventions in use. My own subjective opinion is that it's probably best to have an explicit field for this.

**Comment by carolynvs** [comment]
Making it a dedicated field will also help prompt people to fill it in. 😀

**Comment by cblecker** [comment]
Opened #2262 with this change.
