### ISSUE TITLE
Propagate Labels to Events

### ISSUE THREAD

**Issue by andersjanmyr** [kubernetes/community#2267]
I think it would be very useful for the labels of resources to propagate to the events.
If I create a `Deployment`, the labels propagate to the `ResultSet` and to the `Pods`, but not to the `Events` created by any of those resources.
It would be very nice to list events by labels and get everything related to my deployment.

**Comment by justaugustus** [comment]
Hey @andersjanmyr, thanks for opening a feature request!
Looks like this would be better suited as an issue opened in [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes).

I'm going to close this out, but you can open the request by clicking this link instead: https://github.com/kubernetes/kubernetes/issues/new

/close

**Comment by andersjanmyr** [comment]
Okay, my mistake. Thanks.
