### ISSUE TITLE
Old version of docker recommended in the kubeadm install documentation

### ISSUE THREAD

**Issue by strajansebastian** [kubernetes/community#2292]
Hello

https://kubernetes.io/docs/tasks/tools/install-kubeadm/ section 'Installing Docker':
_On each of your machines, install Docker. Version 17.03 is recommended, but 1.11, 1.12 and 1.13 are known to work as well. Versions 17.06+ might work, but have not yet been tested and verified by the Kubernetes node team. Keep track of the latest verified Docker version in the Kubernetes release notes._

Since version 17.03 (last stable release was made in 2017-03-27) other stable versions have been released and the latest is 18.03.1 for the community edition (release date: 2018-04-26).
Also Docker has stable releases planned each quarter according to their release page (https://docs.docker.com/install/), but in some cases they seem to make intermediate releases.
So the version from the documentation is more than 1 year old. Also quite soon a new stable version should be released for this quarter.

Is somebody going to run some tests before the documentation is changed to the latest version?
If no can I propose an update for the latest version in the link from above?

Also what do you think about installing the latest stable version available at the time of the install for kubeadm?
This is the recommended installation for a CentOS/RHEL/Fedora environment, but not for the Ubuntu, Debian or HypriotOS.

Thanks,
Sebastian

**Comment by stp-ip** [comment]
Latest doc link: https://kubernetes.io/docs/setup/independent/install-kubeadm/#installing-docker

**Comment by neolit123** [comment]
hello,
> https://kubernetes.io/docs/tasks/tools/install-kubeadm/ 

the document was evaluated in 1.11 and is up to date with what version of Docker Kubernetes supports.
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/system/docker_validator_test.go#L65

the validation is performed by sig-node and when a new version is supported the document will update accordingly. when is that going to happen, i cannot answer.

there is a multitude of similar requests in the `k/kubernetes` repository and some blockers as well:

https://github.com/kubernetes/kubernetes/issues/53221
https://github.com/kubernetes/kubernetes/issues/65089

please follow up in there. thanks.

/close

**Comment by nathansmyth** [comment]
Latest doc link: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-runtime

**Comment by neolit123** [comment]
latest version that we support is 18.09
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/system/docker_validator.go#L49
