### ISSUE TITLE
Inputs for CONTRIBUTING.md

### ISSUE THREAD

**Issue by VineethReddy02** [kubernetes/community#2293]
Contributing page would be a great entry point for beginners in getting started with there respective interest groups.

These following are some of the basic elements of a contributing page, feel free to add more.
- Before you begin 
- Adopting an issue
- Bug lifecycle
       1)Filing a bug
       2)Sending a fix
- Feature Request
- Feature lifecycle
- Merge state meanings
- Use of @meanings

Or else we will at least have pointer to generalized contributing page
https://github.com/kubernetes/community/blob/master/contributors/guide/README.md

**Comment by castrojo** [comment]
I think creating a link is the way to go, if we kept stuff in contributing.md then that'd be one more file we'd have to check when fixing something.

**Comment by parispittman** [comment]
@VineethReddy02 would you like to put a help wanted label on this and see if we can get a contributor to do what @castrojo is suggesting? Or do you have a different direction in mind?

**Comment by nikhita** [comment]
We have a [CONTRIBUTING.md](https://github.com/kubernetes/community/blob/master/CONTRIBUTING.md) file which has links to the contributor guide and other useful resources.

Closing. Please reopen if needed.
/close
