### ISSUE TITLE
Automate generator for sigs.yaml

### ISSUE THREAD

**Issue by jdumars** [kubernetes/community#2295]
With as many changes go into sigs.yaml, it would be preferred for the regeneration of markdown files to be the responsibility of automation.  Additionally, it simplifies the process for submitters who would no longer need to run code in order to make a simple yaml change.

**Comment by nikhita** [comment]
Sometimes it is also helpful for me to run `make generate` and see how the README files would be updated. If we move to automation, would the Makefile still be kept?

(No strong opinions on this, just curious.)
