### ISSUE TITLE
Define triage and tracking process for `kind/feature` issues / PRs in `k/k`

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/community#2307]
There are currently [605 open issues](https://github.com/kubernetes/kubernetes/issues?q=is%3Aopen+is%3Aissue+label%3Akind%2Ffeature) in the kubernetes/kubernetes repo labelled as `kind/feature`.

Unfortunately, our Features tracking process (as it exists today), doesn't actively cull these issues.
I'm opening this issue up because I'd like to illicit some discussion around how we can eventually:
* ~deprecate this label~
* build a process around converting a `kind/feature` into a full-fledged Feature issue / KEP, which is actively tracked and PM-ed by both SIG PM and the relevant SIGs.

I know we've had some discussion around this particular problem, so I'm cc-ing a few people to jumpstart the convo.

/cc @idvoretskyi @jdumars @calebamiles @jberkus @tpepper

**Comment by justaugustus** [comment]
(I'll also be opening a separate issue later around bolstering the existing Features process.)

**Comment by cblecker** [comment]
`kind/feature` isn't just for active features in the process, it's also for feature requests. Not all of them are accepted by the sig as features they want to implement (and therefor kick off a features or kep process), but this is how we currently accept requests.

Also, our automation is set up in such a way that we have a standard set of labels across all repos, and this is one of them. Changing or removing this label would have a project-wide impact, as opposed just impacting k/k.

**Comment by justaugustus** [comment]
@cblecker -- do we have documentation for the process of:
* a SIG accepting a feature request
* a SIG placing this feature on their roadmap
* converting a `kind/feature` from k/k into k/features or a KEP

**Comment by cblecker** [comment]
I don't know the answer to that :)

**Comment by justaugustus** [comment]
@cblecker -- that's the perfect answer; means I have something to work on ;)

**Comment by idvoretskyi** [comment]
> do we have documentation for the process

not well-defined. It has to be clarified here https://github.com/kubernetes/features/blob/master/README.md

**Comment by idvoretskyi** [comment]
> Also, our automation is set up in such a way that we have a standard set of labels across all repos, and this is one of them. Changing or removing this label would have a project-wide impact, as opposed just impacting k/k.

This is a major blocker, IMO.

**Comment by cblecker** [comment]
Yes, @idvoretskyi. Deprecating `kind/feature` I don't think will work.. but having more defined process and automation around features is something I can completely get behind.

**Comment by justaugustus** [comment]
Features automation also mentioned [here](https://github.com/kubernetes/features/issues/590#issuecomment-405777788) by @liggitt:
> Can sig-release/sig-pm look into pulling snapshot reports of milestone items from the features repo automatically? A bot that scrapes the milestone items daily/weekly/whenever and snapshots that as a committed md file would stay up to date and show change over time.

**Comment by jberkus** [comment]
Also, your proposal doesn't make it clear what we'd be replacing kind/feature *with*.  

For the last year we've been discouraging people from using kind/enhancement and asking them to use kind/feature instead.

**Comment by markyjackson-taulia** [comment]
Ping @justaugustus Is this still valid? Is this not covered by the KEP process?
/remove-lifecycle frozen

**Comment by LappleApple** [comment]
Heya, doing some organising of info and scanned this issue — been some casual chatting lately around looking at our labelling structure and this issue seems valid in that it's related to apparently unresolved label mechanics. FWIW there are now 698 items with the `kind/feature` label (as of this typing), up from 605 when SA created this back in 2018.
