### ISSUE TITLE
github: establish new github team structure

### ISSUE THREAD

**Issue by cblecker** [kubernetes/community#2323]
We currently have 303 GitHub teams, with 164 of them being related to SIGs. We sent up a number of teams per sig, and then also set up mirror accounts and Google Groups for them to mirror the notifications.

This doesn't appear to be heavily used, and it also suffers from long upkeep and spam issues.

We need a new GitHub team structure for sigs, and to migrate away from the mirror accounts.

ref: https://github.com/kubernetes/community/issues/720

**Comment by cblecker** [comment]
I'd like to suggest a team structure like:
```
sig-foo
|_ sig-foo-leads
|_ sig-foo-pr-reviews
```

sig-foo and sig-foo-pr-reviews would be open for anyone in the org to join/leave (pending automation). The sig-foo-leads would be the chairs/TLs of the sig, for escalation. PR Reviews would be the front line notification for the sig, the leads the escalation point, and the main sig team would be the bat signal to notify anyone in the sig that is available.

Thoughts?

**Comment by enj** [comment]
Does it matter how it is structured if the source of truth is https://git.k8s.io/test-infra/prow/cmd/peribolos ?

**Comment by cblecker** [comment]
peribolos would be how we could manage it, but we want some consistency between the sigs

**Comment by justaugustus** [comment]
+1 to the proposed structure for notifications.
Would being part of the nested teams grant any magic powers or will that be entirely relegated to peribolos?

**Comment by justaugustus** [comment]
Any updates on this?

**Comment by spiffxp** [comment]
Agree with pr-reviews and the use of hierarchy

I have questions but no opinionated answers yet, what do other folks think?

[sigs don't have leads](https://github.com/kubernetes/community/blob/master/committee-steering/governance/sig-governance.md#roles), so... sig-chairs? sig-tls / sig-tech-leads?

subprojects (which own a collection of N dirs in M repos) as teams:
-  hierarchically under the sig-foo team as sig-foo-subproject eg: `sig-contribex` -> `sig-contribex-community-management`?
- hierarchically under the sig-foo team as subproject, eg: `sig-contribex` -> `community-management`?
- not hierarchically at all

repo management as teams, we currently have:
- `foo-admins` - for admin access to a repo
- `foo-maintainers` - for maintainer access to a repo

Keep them independent of sig teams? Replace with subproject teams? Abandon entirely and allow arbitrary mixes of [sig,subproject]-teams/members/collaborators?

**Comment by tpepper** [comment]
Regarding https://github.com/kubernetes/community/issues/2323#issuecomment-406015867 

While there aren't "sig leads" per se, we do have http://groups.google.com/forum/#!aboutgroup/kubernetes-sig-leads and need that type of easy contact bucket.   I feel like without drifting right back toward a large list of teams under a sig's team hierarchy the "sig-foo-leads" name is a basic plain english phrase and can be a short and easy to type bucket for the various types of leaders who represent SIG.  Is there a major issue here with the optics of having such a bucket?  Or is the problem that the membership criteria for such a bucket is complicated and needs clearly documented per sig?

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/org/issues/336 for "what would it take for peribolos to manage this"

**Comment by spiffxp** [comment]
It's unclear to me whether we want to shuffle around teams first, or consider automating the following:
- using teams in OWNERS files (instead of OWNERS_ALIASES)
- managing team ACLs (repo access, project board access)

I am personally still not sold on hierarchical teams (I don't know if peribolos supports these or not)

Maybe a good start would be to prune the existing teams down if they're not being used?

**Comment by spiffxp** [comment]
We should address https://github.com/kubernetes/org/issues/1051 as part of this

**Comment by cblecker** [comment]
Our draft plan, as discussed in the subproject meeting:

Create a PR (one per SIG/WG) to do the following:
- Collapse all sig teams other than "pr-reviews" into a sig-foo team
- Create a sig-foo-leads team (with the chairs and tech leads) as a child team of sig-foo
- Move sig-foo-pr-reviews as a child team of sig-foo

Assign this PR to the sig chairs asking for their LGTM. If they ask for minor changes right off the bat, we can accommodate, but if they ask for a delay as they want time to audit, suggest that they approve this as is, and then they are welcome to open their own PR as follow up when they're ready.

**Comment by johnbelamaric** [comment]
Also sig-arch needs cleanup: https://github.com/kubernetes/org/issues/1798

**Comment by justaugustus** [comment]
> Also sig-arch needs cleanup: [kubernetes/org#1798](https://github.com/kubernetes/org/issues/1798)

SIG Arch is cleaned up here: https://github.com/kubernetes/org/pull/1799

**Comment by justaugustus** [comment]
Opened another for SIG Scalability: https://github.com/kubernetes/org/pull/2056

**Comment by spiffxp** [comment]
I'm moving this to Blocked because it's unclear whether we want to announce and Just Do This, or shard this out as recommended path forward
