### ISSUE TITLE
Clean up github service accounts

### ISSUE THREAD

**Issue by cblecker** [kubernetes/community#2324]
I'd like to clean up the following GitHub service accounts:

- cadvisorJenkinsBot 
- k8s-bot
- k8s-cherrypick-bot
- k8s-external-contributor
- k8s-mirror-api-machinery-api-reviews
- k8s-mirror-api-machinery-bugs
- k8s-mirror-api-machinery-feature-rqusts
- k8s-mirror-api-machinery-misc
- k8s-mirror-api-machinery-pr-reviews
- k8s-mirror-api-machinery-proposals
- k8s-mirror-api-machinery-test-failures
- k8s-mirror-api-reviews
- k8s-mirror-architecture-api-reviews
- k8s-mirror-architecture-bugs
- k8s-mirror-architecture-feature-request
- k8s-mirror-architecture-misc
- k8s-mirror-architecture-pr-reviews
- k8s-mirror-architecture-proposals
- k8s-mirror-architecture-test-failures
- k8s-mirror-auth-api-reviews
- k8s-mirror-auth-bugs
- k8s-mirror-auth-feature-requests
- k8s-mirror-auth-misc
- k8s-mirror-auth-pr-reviews
- k8s-mirror-auth-proposals
- k8s-mirror-auth-test-failures
- k8s-mirror-azure-api-reviews
- k8s-mirror-azure-bugs
- k8s-mirror-azure-feature-requests
- k8s-mirror-azure-misc
- k8s-mirror-azure-pr-reviews
- k8s-mirror-azure-proposals
- k8s-mirror-azure-test-failures
- k8s-mirror-cli-api-reviews
- k8s-mirror-cli-bugs
- k8s-mirror-cli-feature-requests
- k8s-mirror-cli-misc
- k8s-mirror-cli-pr-reviews
- k8s-mirror-cli-proposals
- k8s-mirror-cli-test-failures
- k8s-mirror-cluster-lifecycle-api-review
- k8s-mirror-cluster-lifecycle-bugs
- k8s-mirror-cluster-lifecycle-feature-re
- k8s-mirror-cluster-lifecycle-misc
- k8s-mirror-cluster-lifecycle-pr-reviews
- k8s-mirror-cluster-lifecycle-proposals
- k8s-mirror-cluster-lifecycle-test-failu
- k8s-mirror-gcp-api-reviews
- k8s-mirror-gcp-bugs
- k8s-mirror-gcp-feature-requests
- k8s-mirror-gcp-misc
- k8s-mirror-gcp-pr-reviews
- k8s-mirror-gcp-proposals
- k8s-mirror-gcp-test-failures
- k8s-mirror-ibmcloud-misc
- k8s-mirror-release-api-reviews
- k8s-mirror-release-bugs
- k8s-mirror-release-feature-requests
- k8s-mirror-release-misc
- k8s-mirror-release-pr-reviews
- k8s-mirror-release-proposals
- k8s-mirror-release-test-failures
- k8s-mirror-scalability-api-reviews
- k8s-mirror-scalability-bugs
- k8s-mirror-scalability-feature-requests
- k8s-mirror-scalability-misc
- k8s-mirror-scalability-pr-reviews
- k8s-mirror-scalability-proposals
- k8s-mirror-scalability-test-failures
- k8s-mirror-storage-bugs
- k8s-mirror-storage-feature-requests
- k8s-mirror-storage-misc
- k8s-mirror-storage-pr-reviews
- k8s-mirror-storage-proposals
- k8s-mirror-storage-test-failures
- k8s-mirror-testing-api-reviews
- k8s-mirror-testing-bugs
- k8s-mirror-testing-feature-requests
- k8s-mirror-testing-misc
- k8s-mirror-testing-pr-reviews
- k8s-mirror-testing-proposals
- k8s-mirror-testing-test-failures
- k8s-mirror-vmware-bugs
- k8s-mirror-vmware-misc
- k8s-mirror-vmware-proposals
- k8s-mirror-vmware-test-failures
- k8s-mirror-wg-iot-edge
- k8s-oncall
- k8s-publish-robot
- k8s-reviewable
- k8s-sig-onprem-api-reviews
- k8s-sig-onprem-bugs
- k8s-sig-onprem-feature-requests
- k8s-sig-onprem-misc
- k8s-sig-onprem-pr-reviews
- k8s-sig-onprem-proposals
- k8s-sig-onprem-test-failures
- k8s-sig-openstack-api-reviews
- k8s-sig-openstack-bugs
- k8s-sig-openstack-feature-requests
- k8s-sig-openstack-pr-reviews
- k8s-sig-openstack-proposals
- k8s-sig-openstack-test-failures
- k8s-slack

Does anyone have any objections to this?

cc: @kubernetes/sig-testing-misc @kubernetes/sig-contributor-experience-misc-use-only-as-a-last-resort

**Comment by cblecker** [comment]
also cc: @calebamiles @idvoretskyi @grodrigues3

**Comment by cblecker** [comment]
@bgrant0607

**Comment by BenTheElder** [comment]
I'd suggest maybe holding onto the *bot accounts, we can only pack so much
automation on to each and I know @fejta at least is building new tools to
automate GitHub toil.

On Jun 27, 2018 11:11, "Christoph Blecker" <notifications@github.com> wrote:

@bgrant0607 <https://github.com/bgrant0607>

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/community/issues/2324#issuecomment-400778637>,
or mute the thread

**Comment by justaugustus** [comment]
Azure mirrors (excluding `k8s-mirror-azure-misc`) have been destroyed as part of #2313: https://github.com/kubernetes/community/pull/2313#issuecomment-400189640

**Comment by cblecker** [comment]
On the bots topic, I know we need to keep:
@k8s-ci-robot - k8s-ci-robot 
@k8s-merge-robot - Kubernetes Submit Queue  k8s-merge-robot

I'm proposing that we kick the following bots out of the org:
@cadvisorJenkinsBot - cadvisorJenkinsBot
@k8s-bot - Kubernetes Bot  k8s-bot
@k8s-cherrypick-bot - k8s-cherrypick-bot
@k8s-publish-robot - k8s-publish-robot  k8s-publish-robot
@k8s-slack - k8s-slack

If we need more tokens for future automation, we can either re-add these accounts, or make new ones. I don't think we should have privileged tokens just hanging around if we aren't actively using them.

**Comment by cblecker** [comment]
I'm also going to put a time box on this.. Leaving open for comment until July 11 at 5pm PDT as I know a lot of people are OoO for the July 4th holiday.

**Comment by BenTheElder** [comment]
Can't we delete the tokens [1] / de-privilege the accounts while still
reserving the usernames / accounts (though perhaps not cadvisorJenkinsBot)?

I'm also not sure, what account does the publisher robot use?
k8s-publish-robot sounds like it.

[1] https://blog.github.com/2013-05-16-personal-api-tokens/

**Comment by cblecker** [comment]
Kicking the bots out of the org doesn't delete the accounts or release the names. We could re-add the accounts to the org at any time. It just means they don't have any privileges.

The staging repo publishing bot is @k8s-publishing-bot (don't want to kick it out)

**Comment by BenTheElder** [comment]
Ah, thanks. I misunderstood "clean up the following GitHub service
accounts" as 'delete the following accounts'. 👍

SGTM

**Comment by spiffxp** [comment]
This is followup to https://github.com/kubernetes/community/pull/2302.  Is there an umbrella issue to catch cleaning up detritus related to that?  ie: I think devstats needs a touchup, I personally would like to nuke the k8s-mirror accounts I have credentials for, we're not sure what to do about the teams and renaming and the bots that apply labels based on their usage, etc.

**Comment by cblecker** [comment]
All the accounts listed above have been removed from the org. We should decide which ones are worth going back and deleting, but as of now, they don't have access to anything in kubernetes/

**Comment by spiffxp** [comment]
I removed the sig-testing accounts https://groups.google.com/forum/#!topic/kubernetes-sig-testing/h9MnFx348Gs

**Comment by spiffxp** [comment]
@idvoretskyi ping

what's the plan to call this issue done?
- do nothing
- update sigs.yaml to remove references to non-existent google groups
- for the k8s-mirror, k8s-sig users
  - delete all referenced github accounts
  - delete all referenced google groups

- or some combination of the above?

**Comment by idvoretskyi** [comment]
@spiffxp 

> update sigs.yaml to remove references to non-existent google groups
> 
> for the k8s-mirror, k8s-sig users
> 
> delete all referenced google groups

This - immediately.

> delete all referenced github accounts

This - after I'll collect the 2FA keys from the github account owners.

**Comment by spiffxp** [comment]
I will be adjusting the doc generator / sigs.yaml to stop linking the mirror google groups in a PR later today

**Comment by spzala** [comment]
FYI, I have just deleted `k8s-mirror-ibmcloud-misc` GitHub account.

**Comment by liggitt** [comment]
sig-auth mirror accounts and secondary mailing lists have been removed

**Comment by bgrant0607** [comment]
k8s-external-contributor has been deleted

**Comment by idvoretskyi** [comment]
Sent out the notification to https://groups.google.com/d/msg/kubernetes-sig-contribex/rzwrLOLHgR8/P8A8nuqhFQAJ; the deadline to reach the lazy consensus is Feb 1st.

**Comment by idvoretskyi** [comment]
> * k8s-sig-onprem-api-reviews
> * k8s-sig-onprem-bugs
> * k8s-sig-onprem-feature-requests
> * k8s-sig-onprem-misc
> * k8s-sig-onprem-pr-reviews
> * k8s-sig-onprem-proposals
> * k8s-sig-onprem-test-failures
> * k8s-sig-openstack-api-reviews
> * k8s-sig-openstack-bugs
> * k8s-sig-openstack-feature-requests
> * k8s-sig-openstack-pr-reviews
> * k8s-sig-openstack-proposals
> * k8s-sig-openstack-test-failures

I can confirm that I can remove the above ^

**Comment by idvoretskyi** [comment]
SIG-Release is done - https://github.com/kubernetes/sig-release/issues/353

**Comment by idvoretskyi** [comment]
SIG-OnPrem GitHub accounts and mailing lists are successfully deleted.

**Comment by idvoretskyi** [comment]
The following groups own the mailing lists that still exist:

@kubernetes/sig-api-machinery-misc 
@kubernetes/sig-architecture-misc-use-only-as-a-last-resort 
@kubernetes/sig-autoscaling-misc 
@kubernetes/sig-aws-misc 
@kubernetes/sig-cli-misc 
@kubernetes/sig-cloud-provider 
@kubernetes/sig-cluster-lifecycle 
@kubernetes/sig-multicluster-misc 
@kubernetes/sig-release 
and SIG-VMware.

I can delete these mailing lists after at least +1 from a SIG-lead of the respective group.

**Comment by nikhita** [comment]
I'll take care of removing the GitHub teams.

**Comment by spiffxp** [comment]
This has been sitting open for a while.  What is our definition of done here?

There are lots of incremental updates here, but I no longer have a sense of:
- whether all the github accounts have been deleted
- whether all the associated mailing lists have been deleted
- whether there is a desire to delete all of the associated prefixed teams (it's not clear to me how to gather data on whether these teams are being used or not)

The most recent update talks about a few stragglers from a mailing list perspective
https://github.com/kubernetes/community/issues/2324#issuecomment-462736648

**Comment by spiffxp** [comment]
/remove-priority important-soon
/priority important-longterm
Given the speed with which we've been moving on this.  Ideally I would like to scope this down to something we can close out this release cycle.  I am comfortable calling the remaining accounts and mailing list abandoned detritus if necessary, but would like to at least understand what remains

**Comment by nikhita** [comment]
I think I had agreed to work on this to remove GitHub teams in a contribex meeting but revisiting this now, I'm confused...did we intend to delete the GitHub accounts listed in the main PR body or also the prefixed GitHub teams for each SIG? 

> whether there is a desire to delete all of the associated prefixed teams (it's not clear to me how to gather data on whether these teams are being used or not)

Anecdotally, some SIGs use the prefixed teams heavily, some don't use that much. Don't really have any data on this. :/
I feel like there is some value in having these teams but it could use an audit -- though this feels like a separate issue to me.

If we intended to delete the GitHub accounts: @idvoretskyi, do you have access to all google groups/emails behind these accounts? Or is that only SIG leads?

**Comment by nikhita** [comment]
Related: issue for establishing team structure for SIGs (https://github.com/kubernetes/community/issues/2323)

**Comment by devmarcomcentral** [comment]
This is the most commented topic so I support it! Devs need to communicate.

**Comment by mrbobbytables** [comment]
Will follow up at the next github admin meeting.
