### ISSUE TITLE
Non-Code Contributor Guide addition

### ISSUE THREAD

**Issue by jonasrosland** [kubernetes/community#2325]
Currently the contributor guide is focused on how to contribute to Kubernetes by writing and submitting code. There are many other ways to contribute to an open source project though, and we want to make it easy for all contributors to do so.

The intent of the work done for the Non-Code Contributor Guide is to make Kubernetes a welcoming project for individuals with a vast array of different skillsets, and make it easy to find information on how they can collaborate on and improve the project.

Some examples of roles and skills that can propel the project forward include:

- Technical project leadership
  - Such as being a part of a SIG
- Leading contributor communities
  - Helping out in local Kubernetes communities, mentorship programs etc
- Recognition of people and projects
  - Making sure people are recognized for their hard work
- Managing communication tools
  - Zoom, Slack, Discourse, ...
- Writing articles/blogs
- Creating artwork
  - Maybe for different parts of the project, or aligned projects, or conferences
- Answering questions from community members
  - On Slack, discuss.k8s.io
- Updating documentation
  - Get specific enough so that someone would have an entrypoint to get started and take ownership
  - Funneling more people to SIG-Docs, everyone wins!
- Operations or aligned technologies that is generally not considered “dev”
  - Automation, monitoring, security hardening tools
- Onboarding and enabling new people
  - You only get one chance to see this onboarding process for the first time, so a steady stream a fresh eyes is important

This work is being done as a subproject under the Contributor Guide in @kubernetes/sig-contributor-experience

The current reference document for new contributors can be found here:
https://github.com/kubernetes/community/blob/master/contributors/guide/README.md#find-something-to-work-on
And the current Development Guide is here:
https://github.com/kubernetes/community/blob/master/contributors/devel/development.md

**Comment by castrojo** [comment]
Initial PR: https://github.com/kubernetes/community/pull/2327

**Comment by parispittman** [comment]
Catching up on your work, @jonasrosland, and the notes from the other noncode folks and honestly, I think what you've written in this issue is a good start to a doc. Pop that into a .md file with some more details and you've got a WIP. Could be something good to build off of...

**Comment by jonasrosland** [comment]
@parispittman I think the merged file from #2598 is a good start, so let's keep iterating on that.

**Comment by jonasrosland** [comment]
The Non-Code Contributor's Guide has now been added to the GitHub repository, and the following communications have gone out:

Blog: https://kubernetes.io/blog/2018/10/04/introducing-the-non-code-contributors-guide/

Distribution lists:
https://groups.google.com/forum/#!topic/kubernetes-dev/v3CMiElT8T8
https://groups.google.com/forum/#!topic/kubernetes-sig-leads/MVqHr_4F9KI

Discuss:
https://discuss.kubernetes.io/t/kubernetes-io-blog-introducing-the-non-code-contributor-s-guide/3025

Will close this issue and create new ones as needed after we collect feedback from the community, and start adding more roles to the Role Board:
https://discuss.kubernetes.io/c/contributors/role-board
