### ISSUE TITLE
Contributor guide needs to mention Meet Our Contributors

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#2326]
We need to mention [Meet our Contributors](https://github.com/kubernetes/community/blob/master/mentoring/meet-our-contributors.md) in the contributor guide. 

This is a good issue for anyone wanting to work on their first contribution. Add a link and description to the event above in the events or mentoring section of the [Kubernetes Contributor Guide](https://github.com/kubernetes/community/tree/master/contributors/guide)

/help
/good-first-issue

**Comment by jennac** [comment]
Hi! I'm interested in tackling this

**Comment by cblecker** [comment]
Hi @jennac! Go for it 🚀 

--
/remove-help

**Comment by parispittman** [comment]
hi again @jennac - i found you on slack and reached out to you there. let me know how I can help.

**Comment by RajatVaryani** [comment]
Hi. Let me have a go at it. Is there any clarity where we have to add because we already have the link under (mentoring section)[https://github.com/kubernetes/community/blob/master/mentoring/README.md]

**Comment by ignertic** [comment]
Hello is this issue still open?

**Comment by ignertic** [comment]
Has this issue been tackled or is there anyone working on this, im willing to tackle if no is working on it

**Comment by nikhita** [comment]
> is there anyone working on this, im willing to tackle if no is working on it

@ignertic Noone is working on it right now.

> Has this issue been tackled

@castrojo Looks like the contributor guide [links to the mentoring page](https://github.com/kubernetes/community/tree/master/contributors/guide#mentorship) (which has information about Meet Our Contributors). Is this enough or did you have something more in mind?

**Comment by nikhita** [comment]
> @castrojo can i be assigned for this /good-first-issue

@ignertic Only organization members can be assigned issues. However, please consider yourself assigned and feel free to work on it.

**Comment by nikhita** [comment]
Fixed by https://github.com/kubernetes/community/pull/2870. Thanks, @ignertic!

/close
