### ISSUE TITLE
document / explain github assignment restrictions

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/community#2344]
We often see new contributors looking to take on issues labeled with `help wanted` / `good first issue` asking to be assigned ([example in test-infra/8413](https://github.com/kubernetes/test-infra/issues/8413#issuecomment-402637462)), but we cannot assign them because of the GitHub limitation that assignees must be Org members or at least repo collaborators.

We should document / explain this in a friendly way we can link to, and we should have prow automatically link to the docs when assignment fails.

Separately it might be worth exploring options to side-step this, [when discussing this in #sig-contribex slack](https://kubernetes.slack.com/archives/C1TU9EB9S/p1530808490000450) @nikhita brought up the `@k8s-external-contributor` account.

/cc @guineveresaenger @nikhita 
/area contributor-guide

**Comment by nikhita** [comment]
cc @cblecker
