### ISSUE TITLE
Write a tool for on demand mapping between github-handle, email and slack-handle

### ISSUE THREAD

**Issue by neolit123** [kubernetes/community#2349]
this was discussed in the recent 1.11 Retro part 2 meeting:
https://youtu.be/sZekfvgIx28?list=WL&t=2076

me and @BenTheElder had a discussion about this today on slack:
https://kubernetes.slack.com/archives/C2C40FMNF/p1530819530000300
RAW copy-pasta of the discussion:
https://gist.github.com/neolit123/00835a9eec63de997329f0edf83977f6

also @dims proposed this tutorial about writing an Slack app.
https://github.com/slackapi/Slack-Python-Onboarding-Tutorial

The idea here is that sig-release need a tool to be able to find the email and/or slack handle of a user that submitted a PR, in case they need to directly contact said user about a certain PR related action.

one potential way of doing this is over a "slack-app", which is like a bot, except it has more power of what it can do. querying the slack app in the lines of `give-me-email-and-slack-of <github-handle>` or `give-me-details-about-this-pr <PR#>` would supposedly result into the app cloning the github repo and extracting email details for this committer. then it would also try to match the email used for the commit to the email used for the slack registration.

one big pitfall here is if the user has decided to set a dummy email in his `git config user.email`, which is not that uncommon.

right now, one reliable but manual way of finding the email of a member is by going here:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/kubernetes-membership

searching for a github handle or a individual name and clicking over a user email and saying "i'm not a robot". 

as suggested by Ben, i'm opening this is issue in `k/community` for a discussion about the options we have. possibly the implementation itself would go in `k/test-infra`.

/help
/kind feature
/cc @tpepper @jberkus 
/cc @kubernetes/sig-testing-feature-requests 
/cc @kubernetes/sig-release-feature-requests

**Comment by cblecker** [comment]
/remove-help

Removing help wanted, as there isn't an agreed to direction yet (doesn't meet the [requirements](https://git.k8s.io/community/contributors/devel/help-wanted.md) for help wanted.

**Comment by neolit123** [comment]
in the meantime here is a quick script for the author/comiter emails from PRs:

https://gist.github.com/neolit123/f769f3c0c1d37f3e268cf71a1ffde1ab

```
# a shell script for retrieving emails from commits in kubernetes/<repo> PRs
# example usage:
#
# 	$ chmod +x ./get-pr-emails.sh
#	$ ./get-pr-emails.sh kubernetes <some-pr-#>
#
#	getting username and branch...
#	username = johndoe314314
#	branch = some-feature-branch
#	getting email addresses...
#	"name": "John Doe",
#	"email": "johndoe@thedoe.org",
#
```

**Comment by jberkus** [comment]
@neolit123 hey, thanks!

For some reason, on some PRs that shell script pulls in the full text of the patch.  Haven't figured out why yet ...

**Comment by neolit123** [comment]
hi, @jberkus 
i wrote it very quickly and it might not always work.

can you give me an example PR #?

**Comment by jberkus** [comment]
#64662

**Comment by neolit123** [comment]
@jberkus 
thanks, script updated:
https://gist.github.com/neolit123/f769f3c0c1d37f3e268cf71a1ffde1ab

it's still possible for extra info to get `grep`-ed, but now it's less likely.

also:
```
# NOTE: the script uses unauthorized GitHub API access and has a rate limit
#       of 60 requests per hour.
```

**Comment by jberkus** [comment]
If someone needs more than 60 mappings per hour, they're not using it for the purpose we intended

**Comment by nikhita** [comment]
Bumping this -- do we still want to have this? If yes, it'd be nice to have an agreed direction and then add the help wanted label. :grimacing:

**Comment by neolit123** [comment]
i must admit i never had the need for such a tool, so it's up to sig-release to plan and own this item.

**Comment by cblecker** [comment]
/lifecycle frozen

If this isn't actively being worked on by sig release, then this should be allowed to close.

**Comment by nikhita** [comment]
> If this isn't actively being worked on by sig release, then this should be allowed to close.

@cblecker I'm guessing you wanted to remove the frozen label so...

/remove-lifecycle frozen

**Comment by nikhita** [comment]
Given the past activity on this, I don't think this is really needed. Closing, but please reopen if needed.

/close
