### ISSUE TITLE
Kubernetes REST API documentation link broken

### ISSUE THREAD

**Issue by heckj** [kubernetes/community#235]
https://github.com/kubernetes/community/tree/master/contributors/devel includes a link under *Developing against the Kubernetes API* for the Kubernetes REST API. I tried to follow it (`https://github.com/kubernetes/community/blob/master/contributors/api-reference/README.md`), and the one after it (`https://github.com/kubernetes/community/blob/master/contributors/user-guide/annotations.md`) - those links both resolve to Github 404s

I tried to locate the new/updated location, but it doesn't appear to be in this community repository any longer.

Where can I find the REST API documentation? (I'd be happy to make a PR to update the link, just don't know where to send it or find it)

**Comment by ymqytw** [comment]
I guess you are looking for these two.
https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/api-reference/README.md
https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/annotations.md

**Comment by heckj** [comment]
thanks @ymqytw  - I tossed up a PR with links to the website/docs location that those generate to fix the README
