### ISSUE TITLE
Document new-subscriber policy for  mailing list

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#2366]
We now turned on "New member posts are moderated" in the google group `kubernetes-dev`. New users will have their messages put in a queue and be sent the following response: 

"Since you're a new subscriber you're in a moderation queue, sorry for the inconvenience, a moderator will check your message shortly. " 

We need to document this in the moderation guidelines for everyone.

**Comment by idvoretskyi** [comment]
cc @kubernetes/sig-contributor-experience-proposals

**Comment by parispittman** [comment]
closing in favor of #2028 

/close
