### ISSUE TITLE
Contributor Guide needs a glossary

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#2370]
The communication section needs a glossary. During many of our meetings we use terms like "lgtm", "prow", "tide", and so on and we don't have a place that explains what all this stuff is. 

We should keep it separate from the user glossary so that there's a clean separation from k8s itself and then the meta 

/sig contributor-experience
/area contributor-guide

**Comment by parispittman** [comment]
https://kubernetes.io/docs/reference/glossary/?fundamental=true

link that?

**Comment by nikhita** [comment]
> link that? there is a community tab there.

Unfortunately, https://kubernetes.io/docs/reference/glossary/?fundamental=true&community=true doesn't have things like `lgtm`, `tide`, etc; instead it has things like `Init Container`, `kube-proxy`, etc. IMO terms like `init containers` shouldn't really be under "community". Wdyt?

**Comment by parispittman** [comment]
Make sure you have the fundamentals tab not blue; those words will show if it is. Only Community should be selected. We can file an issue to see if we can turn multiple tab selection off if that makes for a better experience. 

If we ask for those to be added, they will or we can PR them in. Here is the main list: https://github.com/kubernetes/website/tree/master/content/en/docs/reference/glossary

**Comment by nikhita** [comment]
> Make sure you have the fundamentals tab not blue; those words will show if it is.

Oh yeah, that worked. :)

Clicking on https://kubernetes.io/docs/reference/glossary/ defaults to selecting fundamental as true. I clicked on community after that, which selected both of them. :woman_facepalming:

**Comment by castrojo** [comment]
Nice find, I had no idea this was there! I started a gdoc that was collecting terms, what I'll do is directly PR them into this doc.
