### ISSUE TITLE
Autoscaler owners link broken

### ISSUE THREAD

**Issue by Rajat-0** [kubernetes/community#2392]
Link to owners under Subproject Autoscaler section is broken, it shows 404 not found error.

**Comment by nikhita** [comment]
@Rajat-0 good catch!

There is no OWNERS file for autoscaler: https://github.com/kubernetes/autoscaler.

For reference, the broken link exists here: https://github.com/kubernetes/community/tree/master/sig-autoscaling#subprojects.

**Comment by Rajat-0** [comment]
I am working on this.

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/community/issues/1721

**Comment by spiffxp** [comment]
/close
Was fixed by https://github.com/kubernetes/autoscaler/pull/1174
