### ISSUE TITLE
Github Teams links in main sig-node page are broken

### ISSUE THREAD

**Issue by raravena80** [kubernetes/community#2393]
The following are broken:

<img width="915" alt="screen shot 2018-07-18 at 11 46 00 pm" src="https://user-images.githubusercontent.com/7659560/42925971-d32b3b80-8ae4-11e8-8d01-c1b73c1c2bf1.png">

**Comment by nikhita** [comment]
For reference, this is the link: https://github.com/kubernetes/community/tree/master/sig-node#github-teams.

@raravena80 you will not be able to view the links in the "details" section if you are not a Kubernetes org member. 

But some google groups do not exist in the above link. @cblecker do we still want these google groups to exist? I remember there was a discussion about removing service accounts.

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/community/issues/2324#issuecomment-409930362

**Comment by nikhita** [comment]
The team link will give a 404 to someone who is not part of the Kubernetes org. The service accounts have been removed (at least from the READMEs).

Closing.
/close
