### ISSUE TITLE
kubernetes-sigs/cluster-api-provider-gcp subproject needs to be added to sigs.yaml

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#2419]
Ownership of this code must fall on a single sig. I assumed it was sig-cluster-lifecycle, given that's where cluster-api-provider-openstack lives. Can you please clarify and update sigs.yaml accordingly?

/sig gcp
/sig cluster-lifecycle
@kubernetes/sig-gcp-misc @kubernetes/sig-cluster-lifecycle-misc

/assign @roberthbailey 
as the originator of the repo
/assign @timothysc 
since I believe this is sig-cluster-lifecycle

**Comment by roberthbailey** [comment]
Yes, kubernetes-sigs/cluster-api-provider-gcp falls under cluster lifecycle. I'll update sigs.yaml.

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/community/issues/2464
