### ISSUE TITLE
document maintenance of kubernetes-milestone-maintainers GH team

### ISSUE THREAD

**Issue by tpepper** [kubernetes/community#2424]
Who should be added to and removed from the kubernetes-milestone-maintainers GH team, and when, needs documented.

https://github.com/kubernetes/sig-release/blob/1b389936697e0881dfc343f634da2d37f03604ff/release-team/role-handbooks/ci-signal/README.md previously referred to but that and https://github.com/kubernetes/community/blob/master/project-managers/README.md#joining-the-group now 404's as https://github.com/kubernetes/community/pull/2357 removed it.  The documentation there perhaps was more about joining the kubernetes-pm team, but should have been superseded by a process for kubernetes-milestone-maintainers.

It's now possible (see https://github.com/kubernetes/test-infra/commit/19b225c9d44c8d2390317cc7cf46a4c101c10703) for repos to have their own milestone maintainers lists, but kubernetes-milestone-maintainers remains the default and is managed in an ad hoc by SIG-Release and the release team lead.  But that's likely excessive in most cases.

Probably a simple process here works fine if it’s a limited number of people per sig/repo and we have a simple process like sig lead tells release lead who to add/remove…something light weight could work just fine I reckon.  Only if sigs are rapidly adding/removing lots of people, then probably better for them to manage their own milestone team.

**Comment by justaugustus** [comment]
Great minds, @tpepper: https://github.com/kubernetes/features/issues/590#issuecomment-406127490

**Comment by justaugustus** [comment]
RFC for `milestone-maintainers` notes: https://github.com/kubernetes/sig-release/pull/239

**Comment by justaugustus** [comment]
Added in https://github.com/kubernetes/sig-release/pull/239
/close
