### ISSUE TITLE
document some testgrid analysis workflows

### ISSUE THREAD

**Issue by tpepper** [kubernetes/community#2441]
Testgrid is a bit mysterious to folks when they first approach it.  It could use better documentation.

For the release team this week we did a couple walk throughs of test grid:
https://youtu.be/K997_QKYKc8?t=1598
https://youtu.be/0tIFzATBCfM?t=1278
showing how we navigate it and tunnel into assessing status and triaging to a specific SIG for next level help.

In our discussion around that we've come up with a number of things that might be more broadly useful to the community:
* section in developer and/or contributor guide minimally describing navigating test grid
* a more proper scripted and recorded video posted to youtube covering some basics of test grid usage and triage workflows
* a screen shotted and annotated version of same posted to the website
* a blog post announcing any or all of that

**Comment by nikhita** [comment]
The testgrid introduction from the 2018 Contributor Summit is being added to the testgrid README: https://github.com/kubernetes/test-infra/pull/10483, maybe we can cross reference it here later.

/cc @fejta @michelle192837

**Comment by markyjackson-taulia** [comment]
@vishakhanihore this also falls in to the dev guide work under #3064  Do you want to take this as well?

**Comment by parispittman** [comment]
michelle did a test grid video and presentation at the contributor summit. we can document that and it would be great for this.
