### ISSUE TITLE
Add the contributor job board to the contributor guide

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#2455]
This is a good issue if you want to practice learning how to contribute: 

The [contributor guide](https://github.com/kubernetes/community/tree/master/contributors/guide) has a "Find something to work on" section. Add a sentence in there mentioning the [contributor job board](https://discuss.kubernetes.io/c/contributors/contributor-job-board) so that new users can find and post job postings. 

/sig contributor-experience
/area contributor-guide
/good-first-issue

**Comment by cblecker** [comment]
Closing this for right now :)
