### ISSUE TITLE
Communication & Collaboration Platform Sprawl Assessment

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#2466]
We've discussed the sprawl of kubernetes communication and collaboration platforms on several different mediums as being a problem for the community with pushing messaging and participating in conversations. Contribex has begun making small improvements that are low hanging fruit but in order to make larger more impactful change we need the following to continue:
 
1- Identify [current state / inventory of all communication and collaboration platforms](https://docs.google.com/spreadsheets/d/1Pmlj5nN_QJ3rRlc-HKOLfRdYY5qCWPMjnNPAdZZ22tg/edit?usp=sharing)
This includes all platforms listed on communication.md and others. This will identify owners, audience/reach, engagement, etc. Also, will identify collaboration platforms and owners of calendar invites from sig meetings, etc. so we can potentially centralize those services.

2- [Survey](https://docs.google.com/document/d/1s8op9D-qjNczDiFHIS01-2kDxyiLJHPB3qzW889f-W0/edit?usp=sharing) contributors to see what is working and what isn't for them according to their preferences. Granted we will not be able to appease everyone and meet them where they are but we can identify trends and problematic spaces for us. 

From there, we can formally identify the gaps, research solutions, and make decisions. I'll continue to set issues to break down the work and will close this issue after the inventory and survey are complete. 

The above docs can be accessed if you are a member of the contributor experience mailing list. They are work in progress and would very much appreciate comments/contributions.

**Comment by parispittman** [comment]
/good-first-issue

putting the good first issue label on. i will happily guide someone through the exercise for #1.

**Comment by ameukam** [comment]
@parispittman can i be a volunteer?

**Comment by parispittman** [comment]
@ameukam most definitely. want to chat with me on k8s slack and we can either have a meeting there or get on a call? (slack id: paris)

**Comment by parispittman** [comment]
Update: survey was sent out on Tuesday (sept 11) and will be live for two weeks.

**Comment by parispittman** [comment]
Artifacts to come from this:

-an enhanced communication.md with complete roadmap of our channels, audience, owners, where/how/why to post

-either an addendum to the above, our mod guidelines, or completely separate doc on comms behavior (ie- GitHub etiquette, only @here in Slack for $reason, etc.)

**Comment by parispittman** [comment]
Update: survey data is in. In progress of awarding all swag to those who submitted an email address and then sanitizing the data for publicly posting it.

**Comment by parispittman** [comment]
@ameukam and I would love more help for the first listed task if you are reading this and would like to get more involved (or want to see this issue progress further)

**Comment by parispittman** [comment]
update: all 68 respondents who left their email have been sent codes for water bottles. 🎉 thanks again!

data sanitizing is done; preparing survey sheet for data fun. will post publicly in the contribex folder in the k/community repo. 


the inventory and discovery doc can use some more eyes and hands. feel free to jump in for columns with green.

**Comment by parispittman** [comment]
inventory is complete and linked above. survey went out and results are [here](https://docs.google.com/presentation/d/1HwDpEsv1WKxUtq9fVu4xu1w4x5OFKaKvziG2PBKvkIs/edit?usp=sharing)

Blog post is starting-> https://docs.google.com/document/d/1U6tgPVsOVlDcsxCSXz7lBFyQc8KIdglTRrk2uuf-PG0/edit?usp=sharing
