### ISSUE TITLE
kubernetes-sigs/contributor-site subproject needs to be added to sigs.yaml

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#2472]
ref: #2464 

Ownership of this code must fall on a single sig.  In this case it's sig-contributor-experience, and I'm pretty sure this is a new subproject, ref: https://groups.google.com/a/kubernetes.io/forum/#!topic/steering/fnM_YG5ImKE

/sig contributor-experience
@kubernetes/sig-contributor-experience-misc-use-only-as-a-last-resort 

/assign @castrojo 
you asked for the repo, this is part of the follow up on your end

/assign @Phillels @parispittman 
as sig-contributor-experience chairs

/area github-management

**Comment by castrojo** [comment]
Do we want this as a subproject or can we file it under the community subproject? I ask because in order to make a subproject I need to get concensus from the list, 72 hour voting period, etc.

**Comment by cblecker** [comment]
I think this would fall under the contributor site subproject, wouldn't it?

**Comment by cblecker** [comment]
ref:
https://github.com/kubernetes/community/blob/master/sig-contributor-experience/README.md
https://github.com/kubernetes/community/blob/master/sig-contributor-experience/projects.md

**Comment by parispittman** [comment]
This should fall under the community management subproject IMO

**Comment by parispittman** [comment]
If we could rename the contributor guide subproject to"contribute documentation" then it would be an ok fit there too
