### ISSUE TITLE
kubernetes-sigs/architecture-tracking repo needs to be added to sigs.yaml and have an OWNERS file

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#2476]
ref: #2464
ref: #1721

Ownership of this code must fall on a single sig.  In this case it's sig-architecture.  The repo is also lacking OWNERS files.

I recognize this repo is pretty much just for the project boards, but it's got two files in it and some open PR's.

/sig architecture
@kubernetes/sig-architecture-misc-use-only-as-a-last-resort 

/assign @jdumars

/area github-management

**Comment by jdumars** [comment]
https://github.com/kubernetes-sigs/architecture-tracking/pull/46 is in and I'll add the info to sigs.yaml when this gets merged.

**Comment by jdumars** [comment]
This work is complete.
