### ISSUE TITLE
kubernetes-incubator/cluster-proportional-autoscaler needs to be added to sigs.yaml

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#2477]
ref: #2464

Ownership of this code must fall on a single sig.  I'm taking a total guess that it's sig-autoscaling based on https://github.com/kubernetes/community/blob/master/sig-autoscaling/README.md 

This isn't an attempt to voluntold repos to a sig, just a guess. If I'm wrong, help me figure out which SIG should own these.

/assign @thockin @erictune @MrHohn @bowei  
you're all listed as approvers in the repo's OWNERS file

/assign @mwielgus @DirectXMan12 
sig-autoscaling chairs

/area github-management

**Comment by DirectXMan12** [comment]
Adding it as part of #2425

**Comment by spiffxp** [comment]
/close
closed by https://github.com/kubernetes/community/pull/2534
