### ISSUE TITLE
Enabling 2FA on kubernetes-clients

### ISSUE THREAD

**Issue by cblecker** [kubernetes/community#2496]
2FA is not enabled on the @kubernetes-client org. This is against our org policy.

I will be enabling this on **Friday, Aug 10 at 5pm PT**.

If you're listed on the below list, and have not enabled 2FA before Friday, you will lose access to the kubernetes-client/ org.

- [ ] @mccullya
- [x] @skuda
- [x] @strigazi
- [ ] @tomplus

If you no longer need access to the kubernetes-client/ org, then no action is required. If you still require access, please follow the directions [here](https://help.github.com/articles/securing-your-account-with-two-factor-authentication-2fa/) to enable 2FA on your account.

cc: @kubernetes/owners

**Comment by skuda** [comment]
@cblecker same here, I already enabled 2FA, any other action is needed? Thanks

**Comment by skuda** [comment]
awesome! thanks @cblecker

**Comment by spiffxp** [comment]
:clock5:

**Comment by cblecker** [comment]
This is now complete. The following users have been removed from @kubernetes-client:
- @mccullya
- @tomplus

**Comment by tomplus** [comment]
@cblecker sorry, I was on my vacation. I've just enabled 2FA, could you recovery my access. Thanks.

**Comment by cblecker** [comment]
@tomplus I've sent you an invite back to the org.
