### ISSUE TITLE
sig-auth needs to spell out its subprojects in sigs.yaml

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#2505]
/assign @liggitt 
ref: https://github.com/kubernetes/community/pull/2431#discussion_r205987820

/sig auth
/assign @mikedanese @tallclair 
as sig-auth chairs

/sig contributor-experience
/area github-management
/committee steering

**Comment by mikedanese** [comment]
@liggitt @tallclair Do we feel like the subprojects document is a reasonable starting point? If this is just coalescing the doc into the sig.yaml format, I'm happy to take that on.

**Comment by liggitt** [comment]
I think it's probably ready to translate into a PR. There might be some personnel swaps, but I think it's a good starting point.
