### ISSUE TITLE
Replace e-mailing kubernetes-membership@ as the path to org membership

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#2510]
/kind cleanup
/sig contributor-experience
/area github-management
FYI @kubernetes/owners @kubernetes/sig-contributor-experience-misc-use-only-as-a-last-resort

The [currently documented way of becoming a kubernetes org member](https://github.com/kubernetes/community/blob/master/community-membership.md#member) is to e-mail kubernetes-membership@googlegroups.com

We want to replace this with interaction with the kubernetes/org repo.  We have an [issue template for this](https://github.com/kubernetes/org/issues/new?template=membership.md).  We're also working on a PR-based process backed by automation.

How should we proceed?
1. update docs to use the issue template for now, wait until automation is ready, update docs to use a PR process that is fully automated
2. wait until automation is ready, update docs to use a PR process that is fully automated
3. update docs to use a PR process, have github admin team members manually implement what automation would do, turn on automation when ready

Mostly opening this issue to give a heads up to @mistyhacks since I see https://kubernetes.io/docs/contribute/participating/#members duplicates content we'll want to change when we go through whatever course of action we decide

**Comment by cblecker** [comment]
I soooooo want to do this ASAP. I very much dislike the e-mail list.

I'm kind of leaning toward moving to the issue template ASAP, and then we manually invite or "fixes #xxxx" it with a PR to close the issue. The main reason for that is I think that when we turn up peribolos, there might be some initial bumps. Or we might change the format/layout of the files.. I'd like to enforce alpha sorting the user list, but that's not really there yet. And if someone misaligns whitespace or doesn't alpha sort their user, I'm not sure I want that to hold up their membership request. Also, rebases.

There's just some things about the PR flow that I don't quite want to create friction.. but also I really want to get away from the e-mail list ASAP. Open to thoughts.

**Comment by spiffxp** [comment]
I think I also would rather go the issue-based route

**Comment by philips** [comment]
@cblecker you could do something like one file per username in a directory to avoid merge conflicts.

**Comment by fejta** [comment]
Issue + someone else more familiar with the repo creates the PR sounds like a fine approach to me

**Comment by fejta** [comment]
FWIW we should have the automation up next week

**Comment by cblecker** [comment]
I opened up https://github.com/kubernetes/community/pull/2521 to modify the user-facing procedure.
