### ISSUE TITLE
Steering Committee 2018 Election Process Kick Off

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#2517]
*please do not use this issue as official election documentation. this is a WIP to get us to the official documentation.*

Moving some next step comments from [issue in steering repo](https://github.com/kubernetes/steering/issues/63) that kicks off the 2018 election cycle for steering committee members.

Election Officials:
@idvoretskyi @castrojo and @parispittman

- [x] get [steering committee process doc](https://git.k8s.io/community/events/elections#steering-committee)'s [PR is merged](https://github.com/kubernetes/steering/pull/68). This has updated information on election officials, eligible voters, and drafted schedule of events:

August
21th - election announcement: eligible voters, exception process for those not listed as eligible, and a request for nominations (depending where you are in the world, you may have received it on the 22nd)

September
14th - all candidate bios / statement of intent is due. also, all voting exceptions are due.
19th - voting begins; voters sent poll via email for selection

October
3rd - voting ends; poll closed and votes are tallied. Election officials
4th - results are announced in weekly community meeting by a steering committee member

- [x] Eligibility List is ready and pulled as of 12:07AM PT August 15th. ---- Prepare members of standing spreadsheet with emails associated to receive ballots and election information. Date to run the latest information and have a cut off: August 15th.  
- [x] Prepare exception voting form 
- [x] Put together a communication channel strategy and prepare to start
- [x] Prepare copy for info email to go out on August 15th 

special note - there are only 12 seats for the next year. thockin's seat does not get backfilled. next october will bring a steering committee of 7 and not the original 13. we are voting on three seats this year.

**Comment by jberkus** [comment]
Does this mean that we pull the list of who is eligible to vote on the 15th?  Or is that later?

**Comment by parispittman** [comment]
@jberkus we will pull on the 15th. updating the issue to reflect, too.

**Comment by parispittman** [comment]
adding as a note for later. thockins original notice of steering elections last year: https://groups.google.com/forum/#!topic/kubernetes-dev/piPuoqFkJwA

**Comment by parispittman** [comment]
Bumped the announcement to tomorrow for proper reviews and changes in place on the steering committee updates happening on [#68](https://github.com/kubernetes/steering/pull/68) and #2547.

**Comment by parispittman** [comment]
announcement has been bumped to Monday. August 20th to make sure that it doesn't get lost in the email shuffle of the week. announced on the 8/16 community call that we were going to send next week.

**Comment by parispittman** [comment]
blocked on three election related docs sitting with steering committee. if we don't have by 2pm PT, we will punt announcement to Aug 21st (tomorrow, Tuesday).

**Comment by parispittman** [comment]
bumping to tomorrow. /steering/elections.md (#68) looks to be wrapping up final comments and obtaining approvals to merge but we will need at least an hour to test the voting and candidacy processes and then any final edits. if it merges before 10am PT tomorrow, aug 21st, we can send out by noon PT.

**Comment by idvoretskyi** [comment]
The correct link mentioned in the message above (wrong repo) - https://github.com/kubernetes/steering/pull/68.

**Comment by parispittman** [comment]
announcement was made yesterday, August 21st (depending on where you are in the world could have been the 22nd). closing this issue as we have now completed the kick off. 

/close
