### ISSUE TITLE
Deliver a weekly "newsletter" to SIG Chairs/TLs

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#2518]
Chairs/TLs see at least 3 pieces of email a week to the sig leads distro. If we funnel all news through a weekly digest, it would reduce the volume and provide a one stop shop. Tips would include: best practices, how tos, gh process changes, etc. 

We can use discuss.k8s.io for this or some other service including plain old email. It would be nice to have multiple contributors from contribex help out but would need to collate before sending out.  

Maybe target 7 tips a week to play on the k8s theme of 7.

**Comment by justaugustus** [comment]
This would be awesome to have! :)

**Comment by parispittman** [comment]
note to self - include a link to last week in k8s dev

**Comment by jberkus** [comment]
Did you want to put this under LWKD?

I think 7 new items per week might be ambitious.

**Comment by parispittman** [comment]
Doing this on the slack channel now vs email

/close
