### ISSUE TITLE
Audit zoom license holders 

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#2536]
Audit all zoom license holders (chairs/leads of SIG/WGs) to make sure they are using the right meeting set up feature and have updated version for moderation purposes. Follow up with individual SIG/WG chairs after audit if there is a concern.

**Comment by parispittman** [comment]
Audit is finished.

Need to work with the following SIGs/WGs individually to get them using the right moderation features:

Apps
AWS
Azure
Big Data
CLI
Cloud Provider
IBMCloud
Instrumentation
Multicluster
Node
PM
Scheduling
Service Catalog
Windows
WG Cloud Provider
WG IoT Edge

Will close this issue once they have all been contacted.

**Comment by parispittman** [comment]
Need more info from API Machinery and Cluster Lifecycle.

**Comment by timothysc** [comment]
@parispittman we have shared sig-cluster-ops zoom for years, before I was involved.

**Comment by parispittman** [comment]
Sent an email to the following leads of these groups:
Big data
Instrumentation
Ibmcloud
Multicluster
Wg iot leads

**Comment by castrojo** [comment]
SIG windows is all set, I'll ask chairs/TLs to comment here when they've moved over.

**Comment by spzala** [comment]
SIG IBMCloud is set too. @castrojo thanks for helping out with the set up.

**Comment by parispittman** [comment]
update - the labels shown (except contribex - we are good; there for project board) are still using personal meeting ID.

**Comment by parispittman** [comment]
API Machinery needs a new zoom login entirely. adding this to document.

**Comment by parispittman** [comment]
good news - personal meeting IDs can at least put folks on hold at this point. so if chairs are still using personal meeting IDs, the only annoying thing that will happen is they can't start the meeting without the host, which is their choice and not a safety problem. 

im closing this issue as we are good now with moderation features and compliance.
