### ISSUE TITLE
Need Zoom channel for Shanghai organizers 

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#2562]
Per earlier Slack discussion:

We need a zoom channel for meetings of the Shanghai Contributor Summit organizers.  For efficiency, we could probably just use a general Contrib Summit channel.  Regardless, I need to know what it is and have moderation powers on it.

Deadline: Wednesday.

@parispittman

**Comment by parispittman** [comment]
Delivered to Josh via slack with link on 8/21/2018. Will email with full information today - 8/22/2018.

/close
