### ISSUE TITLE
Help request: documentation on implementing API changes in k8s

### ISSUE THREAD

**Issue by casusbelli** [kubernetes/community#2585]
Hi!
Is there a document describing the build / dev process for API changes or something similiar?
I'm currently working on a bugfix for a k8s pkg bug. This fix requires an additional field in an API VolumeSource struct. However such a change seems to require additional conversion impls and does not correctly propagate through the different API layers (core, v1, etc.). I read the API conventions document [1] but so far i'm not grasping where exactly changes to the api have to be made and how to propagate them fully to the required generated classes.
I'm happy to get pointers to additional docs or other hints.
Thanks

[1] https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md

**Comment by nikhita** [comment]
@casusbelli There is https://github.com/kubernetes/community/blob/master/contributors/devel/api_changes.md. Does that document answer your questions or is there something we should be including in it? Suggestions welcome! :)

**Comment by nikhita** [comment]
/remove-sig docs
/kind documentation

I guess this should be
/sig architecture

**Comment by casusbelli** [comment]
@nikhita api_changes looks like a bulls eye, thanks a lot!
