### ISSUE TITLE
move aws-csi-driver-ebs as sig-aws subproject

### ISSUE THREAD

**Issue by d-nishi** [kubernetes/community#2587]
We would like to move the ebs csi driver project that AWS, Redhat and Docker engineers are working on to kubernetes-sigs as a sig-aws subproject.

We would like to add proper testing to the code as it is being developed under sig-aws. 
Also mirror GCP' process of hosting the project under sig-gcp gcp-compute-persistent-disk-csi-driver

Can I get some comments/thoughts on this?

@jsafrane @gnufied @justinsb @bertinatto @saad-ali

**Comment by d-nishi** [comment]
@bertinatto

**Comment by leakingtapan** [comment]
bertinatto/ebs-csi-driver#1
