### ISSUE TITLE
Request for the public gcs bucket to store conformance test result to testgrid

### ISSUE THREAD

**Issue by tizhou86** [kubernetes/community#2594]
Hi, @BenTheElder 
According to https://github.com/kubernetes/community/blob/master/keps/sig-cloud-provider/0018-testgrid-conformance-e2e.md#requesting-a-gcs-bucket, I represent baiducloud, which is the CNCF gold member, to request for the public gcs bucket to store the conformance test result which will be used by testgrid, thanks!

**Comment by BenTheElder** [comment]
Hi, happy to help with this :-) -- Could I get back to you ~ later this week? I'm hoping to roll out an improved process for this soon :tm:

**Comment by BenTheElder** [comment]
Hey, sorry about that. I was hoping we'd be able to sort out something related to https://cloud.google.com/blog/products/gcp/google-cloud-grants-9m-in-credits-for-the-operation-of-the-kubernetes-project once it was out, but we still need to sort out some policy and things around how we manage these. We can wait a bit more or I can go ahead and set one up under Google now (I also have more time again) and migrate it later.

**Comment by dims** [comment]
@BenTheElder let's use the same strategy we had for openstack for this bucket too. since we have a bunch of things to migrate anyway one more won't be too much trouble (right?)

**Comment by BenTheElder** [comment]
yeah it shouldn't be too bad, @amwat and I are working on a doc outlining plans for that sort of thing. I'll try to get to this by EOD, along with some other providers :+1:

**Comment by BenTheElder** [comment]
I'll be reaching out shortly, just setup DO's.

**Comment by BenTheElder** [comment]
Actually, please reach out to me (BenTheElder on Kubernetes slack, or email in [my profile](https://github.com/BenTheElder) / on [my site](https://bentheelder.io/)) to arrange transferring a service account key for the bucket.

`gs://k8s-conformance-baiducloud` has been created, we just need to get your CI setup with the key :-)

**Comment by tizhou86** [comment]
I'll ping you on slack, thanks!

**Comment by tizhou86** [comment]
Got the key, close the ticket now. :-)
