### ISSUE TITLE
Zoom guidelines need screen sharing recommendations.

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#2599]
We need https://github.com/kubernetes/community/blob/master/communication/zoom-guidelines.md to have a section on how to do screensharing properly.

The ideal section will include links to the Zoom documentation, and a set of common sense recommendations wouldn't hurt like "Make sure you turn off your notifications", "Close your email client", etc.

I'll get to this eventually but this wouldn't be a bad place for a new contributor to dive in!  

/sig contributor-experience
/good-first-issue
/help

**Comment by MAKOSCAFEE** [comment]
I can work on this. Please assign me.
