### ISSUE TITLE
communication: README refers to kubernetes.slackarchive.io which redirects to Github

### ISSUE THREAD

**Issue by dholbach** [kubernetes/community#2605]
It looks like https://kubernetes.slackarchive.io is not actually archiving Slack conversations. It's merely a redirect to https://github.com/dutchcoders/slackarchive

Not sure if Slack Archive is available or not, if it isn't, it'd be good to remove the bit from https://github.com/kubernetes/community/blame/master/communication/README.md#L28 and following.

**Comment by idvoretskyi** [comment]
Fixed in https://github.com/kubernetes/community/pull/2607

**Comment by dholbach** [comment]
Might make sense to remove the integration in Slack too. The bot seems to at least still be there still.
