### ISSUE TITLE
some urls in sig-api-machinery/README.md can not access

### ISSUE THREAD

**Issue by bruceauyeung** [kubernetes/community#2613]
https://raw.githubusercontent.com/kubernetes-client/community/master/OWNERS
https://raw.githubusercontent.com/kubernetes-client/typescript/master/OWNERS
above two urls can not access and return “404 not found”
they have moved  to somewhere or have been removed？
Could I commit a pr to remove them in README.md ? 

 /sig API-Machinery

**Comment by cblecker** [comment]
Yeah, these can both be removed. They were removed.

**Comment by nikhita** [comment]
>  they have moved to somewhere or have been removed

The community repo was deleted. The typescript repo is in kubernetes-retired but it should be removed from the README. :+1: 

>  Could I commit a pr to remove them in README.md ?

@bruceauyeung Please feel free to send a PR! :tada:

**Comment by nikhita** [comment]
Ah, just noticed https://github.com/kubernetes/community/pull/2621. :)

**Comment by nikhita** [comment]
Fixed by https://github.com/kubernetes/community/pull/2621

/close
