### ISSUE TITLE
sig-scalability needs to declare tech leads in sigs.yaml

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#2616]
/committee steering
/sig scalability
/priority important-soon
/kind cleanup
/assign @wojtek-t 

They are referenced in the charter as key decision makers, so we should list who they are

ref: https://github.com/kubernetes/community/pull/2149#discussion_r214440211

**Comment by wojtek-t** [comment]
It's fixed already - we already have TLs defined:
https://github.com/kubernetes/community/blob/2c0aa4bfa1d7159832a85d286a1f044befdc738c/sigs.yaml#L1734

We should probably have more, but as long as it's not a bottleneck it's probably fine (as it;s where we are now).

/close
