### ISSUE TITLE
Request to join the Kubernetes org

### ISSUE THREAD

**Issue by lucperkins** [kubernetes/community#2618]
I make this request as a CNCF employee, SIG DOCS member, and Netlify admin for https://kubernetes.io and other k8s-related sites.

cc @zacharysarah

**Comment by zacharysarah** [comment]
@lucperkins Happy to sponsor you. Please make sure to [follow the checklist](https://github.com/kubernetes/community/blob/master/community-membership.md) for this issue.

**Comment by spiffxp** [comment]
/close
Looking forward to having you as part of our community! Please follow the checklist linked above and file an issue in [kubernetes/org](https://github.com/kubernetes/org)
