### ISSUE TITLE
Subproject details in sigs.yaml

### ISSUE THREAD

**Issue by timothysc** [kubernetes/community#2619]
Subprojects need to have more details available other then OWNERS link 

e.g. slack and lead details. 

Currently I can't seem to add that to a sub-project.

**Comment by cblecker** [comment]
/sig contributor-experience

Can you mock up what the yaml might look like? Should be easy to implement.

cc: @spiffxp

**Comment by justaugustus** [comment]
@timothysc -- I have a PR up that addresses this: https://github.com/kubernetes/community/pull/2731

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/community/issues/1673

**Comment by nikhita** [comment]
This is currently blocked on Steering, since we need docs for what a subproject "lead" means and the processes around it before we can add fields for it in sigs.yaml.

Ref: https://github.com/kubernetes/steering/issues/36#issuecomment-471732144

**Comment by dims** [comment]
proposal
---------
- A sub project can have one or more leads.
- The lead keeps track of things to do
- The lead coordinates work among interested parties
- The lead runs the meetings, ensures there are notes/recordings
- The lead reports back updates to the parent SIG.

Does that help?

**Comment by nikhita** [comment]
@dims :+1: :+1: :+1: Would be cool to see this PR'd in. :)

For reference, we also have docs on what a "Subproject Owner" means today: https://github.com/kubernetes/community/blob/master/committee-steering/governance/sig-governance.md#subproject-owner

**Comment by dims** [comment]
adding here https://github.com/kubernetes/community/pull/3413

**Comment by bgrant0607** [comment]
Let's please not use the term "lead". I commented on #3413.

**Comment by nikhita** [comment]
@spiffxp @timothysc can this be closed?

**Comment by spiffxp** [comment]
/close
https://github.com/kubernetes/community/pull/3483 addressed this by adding a `Contacts` field to the Subproject struct, which allows for subprojects to have a slack channel, mailing list, and github teams (with examples of all three)
