### ISSUE TITLE
Please create repository named cli-runtime and sample-cli-plugin under kubernetes github org

### ISSUE THREAD

**Issue by dims** [kubernetes/community#2626]
In https://github.com/kubernetes/kubernetes/pull/67658, we added staging/src/k8s.io/cli-runtime/* in the main k/k repository, we don't yet have 
- a corresponding github repo : https://github.com/kubernetes/cli-runtime
- vanity urls to match

Same deal for https://github.com/kubernetes/kubernetes/pull/67938 that added staging/src/k8s.io/sample-cli-plugin/*

**Comment by dims** [comment]
Request from @pohly on slack

```
pohly [12:18 PM]
Where is the git repo for the "k8s.io/cli-runtime" package? I'm running into a problem where "dep" fails to find the source code for that package. This can be reproduce with "go get k8s.io/cli-runtime/pkg/genericclioptions": it tries to check out https://github.com/kubernetes/cli-runtime, but that repo does not exit.

I know that the original source code is in kubernetes/kubernetes, but shouldn't it get mirrored?
For example, k8s.io/apiserver is mirrored at https://github.com/kubernetes/apiserver.
kubernetes/apiserver
Library for writing a Kubernetes-style API server.
Stars
112
Language
Go
kubernetes/apiserverJan 13th, 2017Added by GitHub
Oh, it's brand-new (created August 21st), so it probably simply hasn't been mirrored yet.
```

**Comment by spiffxp** [comment]
/sig cli
/sig architecture
We need sign off from the above sigs (pinging @kubernetes/sig-cli-feature-requests  and @kubernetes/sig-architecture-feature-requests)

You may want to contact them on other channels as well and send them to this request.

Per the requirements: https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#core-repositories

**Comment by dims** [comment]
@soltysh  @pwittrock  @AdoHe - can you please approve on behalf of the @kubernetes/sig-cli-maintainers ?

**Comment by jdumars** [comment]
We don't have a formal decision-making system established in SIG-Architecture, so my feeling is to bring this and #2627 to our next meeting.

**Comment by sttts** [comment]
/xref https://github.com/kubernetes/org/issues/58

Same topic.

**Comment by sttts** [comment]
@dims please compare the required permission documented in kubernetes/org#58

**Comment by spiffxp** [comment]
Same as https://github.com/kubernetes/community/issues/2627#issuecomment-418523398 we'll need these requests opened in k/org, but happy to use this issue as a place to link to for the decisions/approvals

**Comment by bgrant0607** [comment]
SIG Arch signed off on this via email.

**Comment by soltysh** [comment]
I think this can be close now.
/close
