### ISSUE TITLE
Please create repositories for component config types for - controller-manager/proxy/scheduler/kubelet

### ISSUE THREAD

**Issue by dims** [kubernetes/community#2627]
In the following PR(s), we added new directories under staging/src/k8s.io/ for holding component config api types

- https://github.com/kubernetes/kubernetes/pull/67263
- https://github.com/kubernetes/kubernetes/pull/66916
- https://github.com/kubernetes/kubernetes/pull/67688
- https://github.com/kubernetes/kubernetes/pull/67469

More specifically we need 4 new repositories to hold them:

- [k8s.io/kubelet](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kubelet)
- [k8s.io/kube-proxy](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kube-proxy)
- [k8s.io/kube-scheduler](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kube-scheduler)
- [k8s.io/kube-controller-manager](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kube-controller-manager)

And we need to update the bot that sync(s) the directories to the corresponding repos as well

**Comment by dims** [comment]
cc @luxas @dixudx @Lion-Wei @stewart-yu @bsalamat  @derekwaynecarr @dchen1107 @k82cn @thockin @dcbw @caseydavenport Folks, please +1 the request

@kubernetes/sig-node-pr-reviews @kubernetes/sig-network-pr-reviews @kubernetes/sig-scheduling-pr-reviews

**Comment by sttts** [comment]
@dims kube-controller-manager is missing.

**Comment by dims** [comment]
Added. thanks @sttts

**Comment by sttts** [comment]
@dims also please compare the required permissions documented in https://github.com/kubernetes/org/issues/56.

Also note that this was already approved by sig-arch through [KEP 14](https://github.com/kubernetes/community/blob/master/keps/sig-cluster-lifecycle/0014-20180707-componentconfig-api-types-to-staging.md).

**Comment by sttts** [comment]
For the publishing bot please create a PR like https://github.com/kubernetes/publishing-bot/pull/93.

**Comment by sttts** [comment]
@spiffxp with csi-api I saw you copied some repo template. Can we have another repo template just for staging repos? They should not have any files and the permissions are special, compare kubernetes/org#56.

**Comment by spiffxp** [comment]
@sttts are you asking for a completely blank repo, or do you need these to be empty repos with an initial commit? what will give me confidence is if I can see valid copies of those files in the staging repo that's going to sync to them, and get cc'ed on something that tracks the first sync happening (issue, pr, whatever)

@dims the actual requests for these repos should be made against kubernetes/org FWIW

**Comment by sttts** [comment]
> are you asking for a completely blank repo, or do you need these to be empty repos with an initial commit?

@spiffxp a first empty commit if possible.

The new repos are all in https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io and have those default files.

**Comment by luxas** [comment]
This is now done, thanks everyone 🎉 !!
