### ISSUE TITLE
Move from CLA to DCO

### ISSUE THREAD

**Issue by dims** [kubernetes/community#2649]
Following up on an old email thread [1]. I understand that Kubernetes was using Google CLA before and hence naturally moved to using CNCF CLA [2].

- Since CNCF does allow projects to use DCO, is there a possibility that Kubernetes can move to it?
- What are the pros and cons of DCO vs CLA?
- Will using DCO help attracting a larger set of contributors? (we have anecdotal evidence of folks unable to create PR(s) or not following up on PR(s) when the bot marks them red)

[1] https://groups.google.com/forum/#!msg/kubernetes-sig-apps/71c1FHem3-Y/hy9AnS34BgAJ
[2] https://docs.google.com/document/d/1LIwyn5PDSYu8kh-7hH8688lt1cvwATkZmhec13nhp1c/edit#heading=h.tm8xljbp3pt0

**Comment by neolit123** [comment]
one good benefit of CLA is that it's integrated per github account.

i've been helping with reviews for the DCO integration:
https://github.com/kubernetes/test-infra/pull/9197#issuecomment-416931231

overall DCO is more fragile for contributors:
- DCO has to be manually added per each commit.
- auto-squash semantics nuke the DCOs and GPGs. this is quite bad and the project needs to outline this in the contributor guide. but then if the DCO is nuked, how is the contributor allowed to contribute to the project?
- contributors can give a completely invalid email in their `Signed-off-by:` line and probably nobody would have the time to verify it. also they can use [this](https://help.github.com/articles/about-commit-email-addresses/) which i'm pretty sure conflicts with the DCO definition.

**Comment by cblecker** [comment]
I think this discussion may need to start with the steering committee to see if it's even a possibility from their perspective. I personally like the CLA approach, but think there is value in discussing the pros/cons.

**Comment by cblecker** [comment]
cc: @kubernetes/steering-committee

**Comment by thockin** [comment]
There are real legal implications.  From what I understand (IANAL) the
CLA nd a DCO are *not* equivalent.  Fun reading:

https://opensource.google.com/docs/cla/policy/

https://opensource.com/article/18/3/cla-vs-dco-whats-difference

"If you're a juicy target for litigation and you want some cover, a
CLA might be the right approach"

There are many articles in the other direction, too, but the main
argument seems to be "make it easier for contributors".  I do not
think that CLA is in the top 50 things that make our contributors'
experiences difficult.

**Comment by parispittman** [comment]
side note to thockins comment: there is a cla question going out on the contributor experience survey (launching this afternoon PT time). it's not a standalone question but ranks 1-5 how much of a challenge it is for the contributor.

**Comment by spiffxp** [comment]
I asked about this Jan 2018: https://groups.google.com/a/kubernetes.io/d/msg/steering/B32ZXpw8EG8/aCx5yhdfCwAJ

Final response from thockin was:
>I spoke with Google legal, who feel strongly that NOT having a CLA 
represents a liability to all consumers of the project, and urge every 
CNCF project to adopt the CLA.

**Comment by philips** [comment]
Personally I am apathetic. CLA is a one time horrible UX. DCO is an ongoing horrible UX.

**Comment by dims** [comment]
@philips true enough. The intent was about making things easier for occasional contributors.

**Comment by cblecker** [comment]
If all things were equal legally (I understand that they probably aren't), it would be a disruption to take our existing contributor base and change their workflow. While CLA is a one-time impact on new contributors, DCO would require workflow changes from everyone. There would need to be a bunch of added value IMO to consider doing this.

**Comment by cblecker** [comment]
Closing per https://github.com/kubernetes/steering/issues/74
