### ISSUE TITLE
SIG-Architecture to do: Conformance test profile definitions

### ISSUE THREAD

**Issue by jdumars** [kubernetes/community#2651]
From the SIG Architecture meeting on September 6th, 2018 [see [video](https://www.youtube.com/watch?v=fmlXkN4DJy0) and [notes](https://docs.google.com/document/d/1BlmHq5uPyBUDlppYqAAzslVbAO8hilgjqZUTaNXUhKM/edit?ts=5b92c0c4) ] 

Privileged operation tests might be part of a specific conformance test profile, and other use cases e.g. cloud provider may have profiles as well.   A good example of a profile-based test would be node failure implementation across clouds. To start the profile discussion, we need to start classifying/categorizing and documenting these implementation scenarios so we know what profiles we need to build. We need to limit the total number of profiles to ideally less than a dozen, otherwise "conformance" will lose all meaning because of test matrix complexity.

**Comment by bradtopol** [comment]
What is driving this need for profiles?  Can we get this conversation in sync with the conformance workgroup?  There are many of us involved in the workgroup who feel conformance loses all meaning as soon as you introduce the notion of profiles.  cc @dankohn @WilliamDenniss

**Comment by brendandburns** [comment]
@jdumars @bgrant0607 in SIG-Arch today you mentioned that there was a PR for profiles somewhere? Do you have a pointer to the PR? I searched community but I couldn't find it...

**Comment by spiffxp** [comment]
Refreshing state...

There's now a KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-architecture/1618-conformance-profiles
And a tracking issue to go along with it: https://github.com/kubernetes/enhancements/issues/1618

A suggestion of what Base/Privileged might look like: https://github.com/kubernetes/community/pull/4994

And to help frame where SIG Architecture is currently at with profiles philosophically, Thoughts on Conformance Profiles: https://docs.google.com/document/d/1eVEVAH8-kt95hbSTJi8qRosgvSvBAEgKz4Tx1xsjt4I/edit

/close
I think the KEP and its issue is a better place to track progress on conformance profiles going forward
