### ISSUE TITLE
AWS cert manager cert sometimes needs replacing on a k8s service elb

### ISSUE THREAD

**Issue by dmcnaught** [kubernetes/community#2654]
@d-nishi asked me to raise the issue here from slack #sig-aws 

We have an issue with AWS cert manager certificates “disappearing” from the a kubernetes service ELB (deis-router).
We currently see the problem in K8s 1.9 (we’ve upgraded 3/5 clusters to 1.10 now and not sure if I’ve seen the problem there yet) installed/upgraded with kops 1.9.1
The cert is on the deis-router kubernetes service, and the cert isn’t defined in the service description since I also change some ports so that 443 is pointing to what was defined as 80 on the pod (from the way deis workflow recommends to up the router: https://github.com/teamhephy/workflow/blob/master/src/managing-workflow/platform-ssl.md#installing-ssl-on-a-load-balancer).
Does anyone know why sometimes (not even every month), the AWS cert manager cert needs replacing on the k8s service elb?

**Comment by d-nishi** [comment]
@M00nF1sh -- can you check this issue for the user?

**Comment by M00nF1sh** [comment]
Hi Duncan, How did you setup your loadbalancer? via aws-alb-ingress or other mechanism?
Can you send me(yyyng@amazon.com) your k8s yaml for your loadbalancer setup?

**Comment by dmcnaught** [comment]
Is it a deis-router elb - set up by the workflow project using helm, and then modified with the instructions I pasted in the OP.
Sending the yaml now.

**Comment by cblecker** [comment]
@d-nishi Is this a bug, do you think? Bugs are typically tracked in the repo with the code (k/k or otherwise). k/community isn't the right place for this.

**Comment by M00nF1sh** [comment]
Get it, i'll investigate and get back to you 😄

**Comment by d-nishi** [comment]
@dmcnaught sorry but this issue needs to be reported here: https://github.com/kubernetes-sigs/aws-alb-ingress-controller -- please close the issue here.

Please follow the issue here: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/604
