### ISSUE TITLE
TestNamespaceAuthorization link broken under Testing Conventions

### ISSUE THREAD

**Issue by darshanramu** [kubernetes/community#266]
The following link is not found under Testing Conventions.
TestNamespaceAuthorization -> https://github.com/kubernetes/community/blob/master/test/integration/auth/auth_test.go

**Comment by pmorie** [comment]
It's inherently fragile to link to specific code constructs in this manner -- we should either link to a specific git commit (ugly) or embed an example directly in the documentation.

This is another case for a link checker #359

**Comment by cblecker** [comment]
This is fixed.
