### ISSUE TITLE
First Time Contributors

### ISSUE THREAD

**Issue by sahitpj** [kubernetes/community#2661]
Kubernetes being a huge community with a lot of documentation, I feel it is easy to get lost and tough to find to whom to interact first in order to understand how to go about. 

I think there should be a first time contributors doc/file specially dedicated to them with FAQs and basic resources, and probably a first-time-contributor slack channel too. This could easily help them be more open and merge in easily with the existing community

**Comment by idvoretskyi** [comment]
@kubernetes/sig-contributor-experience-bugs 

/cc

**Comment by idvoretskyi** [comment]
@sahitpj FYI, we have the Kubernetes Contributor Guide available on Kubernetes website https://kubernetes.io/docs/community/guide/, which is an absolutely first getting started point for the new contributors.

**Comment by sahitpj** [comment]
Thanks @idvoretskyi found it really hard to find that website, the first time I approached the docs.

**Comment by idvoretskyi** [comment]
@sahitpj 

It's accessible from the docs home page (https://kubernetes.io/docs/home/), just follow the interactive guide (contributors -> code contributor).

**Comment by parispittman** [comment]
hi @sahitpj - we have a contributors folder on the community repo too that is a great place for all of this information. https://git.k8s.io/community/contributors/guide

We are going to surface this docs on a contributor website in the next few months as well. :)

**Comment by nikhita** [comment]
@sahitpj thanks for raising this issue! :)

> We are going to surface this docs on a contributor website in the next few months as well. :)

Closing this issue since this is related to the creation of a contributor website and it is tracked in https://github.com/kubernetes/website/issues/7795.

Please feel free to reopen if this seems to address other issues as well.

/close
