### ISSUE TITLE
Audit usage of Youtube

### ISSUE THREAD

**Issue by ameukam** [kubernetes/community#2667]
As described in #2466, an audit is conducted to identify the current state of all communication and collaboration platforms. We have identified that some SIG/WG lacking of recordings of their meetings or have restricted the access. 

Need to work with the following SIGs/WGs individually to get them applying the [uploading guidelines](https://github.com/kubernetes/community/blob/master/communication/K8sYoutubeCollaboration.md#uploading-guidelines-for-collaborators): 

Autoscaling
AWS
Big Data
IBMCloud
Instrumentation
Multicluster
Testing
UI
WG App Def
WG IoT Edge
WG Apply
WG Container identiy

cc @parispittman 

/area community-management
/sig contributor-experience

**Comment by parispittman** [comment]
cc @castrojo

**Comment by castrojo** [comment]
Yeah we need to do this but haven't found the time unless people complain. @ameukam would you be willing to help us chase down some SIGs? I could really use a hand here.

**Comment by parispittman** [comment]
@castrojo I'll help

**Comment by parispittman** [comment]
Sent an email to the following leads of these groups:
Big data
Instrumentation
Ibmcloud
Multicluster
Wg iot leads

**Comment by parispittman** [comment]
Also emailed - autoscaling, testing, ui, wg app def, and container identity

**Comment by parispittman** [comment]
/close

we are recreating the community audit for q3&4, a new issue about youtube will be created
