### ISSUE TITLE
Create a file listing support channels

### ISSUE THREAD

**Issue by shubheksha** [kubernetes/community#2703]
There is no file to link to in support requests in the issue tracker for k/k and k/website. The closest thing I found was [this](https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#support-structures) section in the issue triage docs.
It'd make sense to add a file listing the various support channels to point people to.

/kind documentation
/sig contributor-experience

**Comment by parispittman** [comment]
an artifact of this #2466  may answer this

**Comment by nikhita** [comment]
@shubheksha @parispittman We have all communication mediums listed here: https://github.com/kubernetes/community/blob/master/communication/README.md. The doc also includes what each medium is used for.

We also have issue templates which contain information about support channels in case someone wants to open a support request.

Do you think this covers it? If not, where do you think we should document support channels?

**Comment by nikhita** [comment]
This exists today: https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
