### ISSUE TITLE
Add `@kubernetes/sig-docs-zh-owners` github team

### ISSUE THREAD

**Issue by chenrui333** [kubernetes/community#2707]
It looks like we have other github teams like `@kubernetes/sig-docs-ko-owners` and `@kubernetes/sig-docs-ja-owners` in [here](https://github.com/kubernetes/community/tree/master/sig-docs#github-teams).

It would be good to have a Chinese one.

**Comment by spiffxp** [comment]
/close
@chenrui333 Please file an issue in kubernetes/org along with a list of who you would like to be added to this team as Team Maintainers
