### ISSUE TITLE
Where does the effort to move k8s infra to CNCF fall?

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#2715]
/committee steering

We have #k8s-infra-team on slack

There is a recurring meeting with a running agenda doc https://docs.google.com/document/d/1r0nydnBoU7o_L7Hnjdc9SZrWe9zosbz64ZUUPn0XwXk/edit

Discussion during the team's first meeting (I wasn't around for the second) was a recognition that this effort needs to be formalized, but we didn't want to impede its initial progress around such formalization

Ideas to consider:
- a "subproject" under a single SIG, ie: the "release team" is a subproject of SIG Release that involves effort from areas across the project
- a "working group", this spans the work of multiple sigs (contribex, testing, release)
- a "team " akin to the "product security team", which has more stringent requirements for membership and responsibilities
- a "sig" because this group could potentially own code/assets
- something that falls under CNCF's purview rather than Kubernetes (to my knowledge CNCF only has working groups)
- we would want to ensure rules are in place to ensure no single entity dominates leadership/ownership of this effort

FYI @dims @thockin @idvoretskyi @brendandburns @cblecker @BenTheElder

**Comment by spiffxp** [comment]
If we go the working group route, we need to resolve https://github.com/kubernetes/steering/issues/27

**Comment by BenTheElder** [comment]
+cc @amwat (I'm sure others as well...)

**Comment by cblecker** [comment]
cc: @kubernetes/k8s-infra-team

**Comment by spiffxp** [comment]
Discussed during today's steering committee meeting

We are going to act as a working group, and delegate code ownership to the SIGS that make the most sense.  I will try to add extra verbiage if need be to ensure our "no single entity dominates" concern is addressed.

This may ultimately follow the model blazed by sig-cloud-provider, which started as a WG but turned into a SIG when it was clear it wasn't temporary and a useful home for code ownership.  I will work with @pwittrock to ensure this meets other concerns around WGs that were discussed today.

**Comment by thockin** [comment]
Great!  Did we decide whether we want to be a subdir of an existing repo or
a new repo?  I could put it in the k8s.io/ repo and be happy

**Comment by spiffxp** [comment]
subdir of k8s.io is fine

**Comment by spiffxp** [comment]
We discussed during today's meeting and @dims and I will act as chairs for the WG.  We discussed whether we want a charter given that no other WG has one, but we feel it's important to be explicit about in-scope/out-of-scope here, so will do a charter.  I will consider this issue closed once we have merged a PR with said charter.
