### ISSUE TITLE
Conformance of the names of the conferences

### ISSUE THREAD

**Issue by ameukam** [kubernetes/community#2716]
As mentioned by @castrojo in [Slack](https://kubernetes.slack.com/archives/C1TU9EB9S/p1537888968000100), the term `KubeCon/CloudNativeCon` is the right one to reference the event. 
Most of the time, the term `kubecon` is used. 

cc @castrojo, @parispittman 
/sig contributor-experience
/good-first-issue

**Comment by eduartua** [comment]
I'll be working on this.

**Comment by eduartua** [comment]
Job done, I think this can be closed.
/fixed

**Comment by parispittman** [comment]
thanks again @eduartua!

/close
fixed in #2860

**Comment by saurav-malani** [comment]
@ameukam this issue is not much clear. Can you please clarify it a bit, so that I can work on it.
