### ISSUE TITLE
Move the logo dir from k/k to the community repo

### ISSUE THREAD

**Issue by nikhita** [kubernetes/community#2718]
k/k contains a `logo/` dir at the root of the repo: https://github.com/kubernetes/kubernetes/tree/master/logo. We already have an `icons/` dir in the community repo, which is similar: https://github.com/kubernetes/community/tree/master/icons.

We can move it from k/k to k/community to house all icons and logos in one place.

With this change, all [these links](https://github.com/search?q=org%3Akubernetes+org%3Akubernetes-incubator+org%3Akubernetes-client+org%3Akubernetes-sigs+org%3Akubernetes-csi+%22master%2Flogo%22&type=Code) would need to be updated.

/sig contributor-experience

/cc @thockin @cblecker @castrojo @ameukam

**Comment by nikhita** [comment]
@ameukam let's not add the help wanted label now. We still need to decided if we want to do this. :)

**Comment by cblecker** [comment]
I think this is probably unneeded. The logo itself is historical, should be discoverable in the main project, and has specific usage guidelines.. none of these apply to the icon set.

Open to arguments in the other direction though :)

**Comment by nikhita** [comment]
I don't have any strong opinions about this. ¯\\\_(ツ)\_/¯

**Comment by thockin** [comment]
I don't think this is worth doing.  Some folks deep-link to it already.
Dan wants us to EOL it in favor of a repo owned by CNCF.  I say we just
leave it.

**Comment by nikhita** [comment]
Ack. Closing.
