### ISSUE TITLE
Perform survey of KEPs and identify those needing update to directory format

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/community#2725]
Work item for https://github.com/kubernetes/features/issues/617

/kind feature
/sig pm
/milestone v1.13
/assign @calebamiles

**Comment by nikhita** [comment]
@justaugustus :wave: Just wanted to bump this again, and check what's remaining here and if this can be closed?

**Comment by savitharaghunathan** [comment]
Hi @justaugustus/ @calebamiles, I am a part of sig-contribex-triage team and wanted to check if either of you have any updates on this issue? Thanks! :)

**Comment by mrbobbytables** [comment]
/remove-lifecycle rotten
Hoping to tackle this between the 1.18 and 1.19 release next year.

**Comment by mrbobbytables** [comment]
/remove-lifecycle stale

The ongoing discussion for this is happening in this PR to update 617
https://github.com/kubernetes/enhancements/pull/1545

**Comment by mrbobbytables** [comment]
/remove-lifecycle stale
This has become the standard, do we want to leave this open till all of them are converted?

**Comment by justaugustus** [comment]
/unassign @mrbobbytables @justaugustus 
/assign @kikisdeliveryservice 
ref: https://kubernetes.slack.com/archives/C2C40FMNF/p1601408420103200?thread_ts=1601403539.085300&cid=C2C40FMNF

**Comment by jeremyrickard** [comment]
/retitle Perform survey of KEPs and identify those needing update to directory format

**Comment by kikisdeliveryservice** [comment]
I feel that this is mostly done and tracked by the issue here: https://github.com/kubernetes/community/issues/2725

I can formally go thru the sub-dirs to get status but on a quick perusal this is very close to done.

**Comment by kikisdeliveryservice** [comment]
I feel that this is mostly done and tracked by the issue here: https://github.com/kubernetes/enhancements/issues/2220

I can formally go thru the sub-dirs to get status but on a quick perusal this is very close to done.

**Comment by mrbobbytables** [comment]
I think this is safe to close, the activity has been happening in k/enhancements.

**Comment by mrbobbytables** [comment]
I went through the subdirs, everything is good 🎉 
/pony party
/close
