### ISSUE TITLE
Enable cross-SIG project tracking

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/community#2727]
Work item for https://github.com/kubernetes/features/issues/617

/kind feature
/sig pm
/milestone v1.14
/assign

**Comment by nikhita** [comment]
@justaugustus Can this issue be closed? If not, could you add more details to the issue body? It's not immediately clear to me what this issue entails :thinking:

**Comment by justaugustus** [comment]
Good point, @nikhita! This is superceded by #3267, which has much more detail.
/close
