### ISSUE TITLE
Move KEPs to k/enhancements

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/community#2730]
Work item for https://github.com/kubernetes/features/issues/617

/kind feature
/sig pm
/milestone v1.13
/assign

**Comment by justaugustus** [comment]
The migration has been completed.

Capturing the commands for posterity...

**Extracting KEPs from k/community**
```bash
git clone git@github.com:justaugustus/community.git kep-forklift
cd kep-forklift
git remote add up git@github.com:kubernetes/community.git
git remote update
git reset --hard up/master
git checkout -b kep-forklift
git filter-branch --prune-empty --subdirectory-filter keps/
mkdir keps
git mv 0* NEXT_KEP_NUMBER OWNERS README.md sig* keps/
git add keps/
git commit --signoff 
git push origin kep-forklift 
```

**Pulling KEPs into k/enhancements**
```bash
git clone git@github.com:justaugustus/features.git
cd enh
git remote add up git@github.com:kubernetes/enhancements.git
git remote add kep git@github.com:justaugustus/community.git
git remote update
git reset --hard up/master
git checkout -b keps
git pull kep kep-forklift --allow-unrelated-histories 
git push origin keps
```

Before considering this complete, we need to:
- Tombstone all KEP files in k/community: #3002 
- Prevent future KEPs from landing in k/community: https://github.com/kubernetes/community/issues/2726

**Comment by justaugustus** [comment]
Tombstones and blockade are in place, so we can close this out now.
/close

**Comment by taamit1** [comment]
Please Unsubscribe me from this thread.
