### ISSUE TITLE
SIG Meet and Greet @New Contributor Workshop KubeCon2018 Seattle

### ISSUE THREAD

**Issue by guineveresaenger** [kubernetes/community#2745]
**This issue will be used as a means to track mentor volunteers - if you could drop your contact information in a comment here or via k8s Slack to me `@gsaenger` you will earn karma points, my eternal gratitude, and new members for your SIG.**

Do you need more SIG members? Are there many outstanding Good First Issue and Help Wanted labels in your SIG’s projects? Are you running out of Reviewers in your OWNERS files? Will members of your SIG attend the Contributor Summit at KubeCon Seattle?

This is the opportunity for you and your SIG!

We need one or more of your members to volunteer 30 - 50 minutes of their time to meet interested new contributors in person. You'll find our their skills, how they can add value, and talk about a first issue they can try. If you've ever been to a Speed Networking session (KubeCon has them - plug!), it's very similar except you both have the same goal. You - to find more contributors; Them - to find a SIG to be a part of.

Requirements:

- Member of SIG***
- Available Monday Dec 10 at 3:00pm at KubeCon Contributor Summit Seattle
- Familiarize yourself with your SIG’s needs, and maybe a few good first issues
- Willingness to follow up and be available for questions by new folks.
- Add your name/contact information via comment to this github issue: https://github.com/kubernetes/community/issues/2745

***This person need NOT be a SIG Chair or Maintainer, just someone willing to be a friendly face, show folks around the repo via chat, and generally bridge the gap for new contributors from “this is where I want to contribute” to “here’s how I can contribute”. In fact, this might be an opportunity for other people in your SIG to grow.

/area community-management
/sig contributor-experience
/assign

**Comment by derekwaynecarr** [comment]
I should be available.

**Comment by dchen1107** [comment]
I plan to go too.

**Comment by zacharysarah** [comment]
I will attend.

**Comment by kmova** [comment]
I will be available

**Comment by roberthbailey** [comment]
I can be there.

**Comment by soltysh** [comment]
Count me in.

**Comment by dims** [comment]
Sounds like fun. count me in

**Comment by juanvallejo** [comment]
Will attend as well

**Comment by childsb** [comment]
will attend for sig-storage

**Comment by seans3** [comment]
I will be available (SIG CLI)--thanks.

**Comment by detiber** [comment]
I will attend for sig-cluster-lifecycle :) I'll reach out over slack for contact info.

**Comment by aanm** [comment]
I will be there as well

**Comment by Huang-Wei** [comment]
I will attend for sig-scheduling.

**Comment by shyamjvs** [comment]
I can be there for sig-scalability.

**Comment by dstrebel** [comment]
I can be there for Sig-Azure

**Comment by quinton-hoole-2** [comment]
I can be there for sig-multicluster. @pmorie, @marun, @irfanurrehman @shashi

**Comment by spzala** [comment]
I will be there for sig-ibmcloud /cc @duglin Thanks @guineveresaenger

**Comment by quinton-hoole-2** [comment]
cc @shashidharatd

**Comment by mrbobbytables** [comment]
Just a reminder for those that are volunteering. If you did not get a confirmation email regarding Contributor Summit Registration last Friday (10/26/2018). Please register by filling out the [Contributor Summit Registration Form](https://docs.google.com/forms/d/e/1FAIpQLSclBl56mToh4pm_CXgTc4MvOj1bjD_OxC_L8A9ZS1CtdJHS-A/viewform).  It says it is currently waitlisted, but go ahead and select the current-contributor track option and we'll switch it to be approved behind the scenes.

**Comment by tpepper** [comment]
I'm happy to contribute for SIG-Release.

**Comment by jberkhahn** [comment]
I'll be around for SIG Service Catalog

**Comment by mcrute** [comment]
I'm happy to attend for sig-aws

**Comment by mrbobbytables** [comment]
@derekwaynecarr @dchen1107 @zacharysarah @kmova @childsb @quinton-hoole-2 - When you get a moment, please complete the [Contributor Summit RSVP](https://docs.google.com/forms/d/e/1FAIpQLSclBl56mToh4pm_CXgTc4MvOj1bjD_OxC_L8A9ZS1CtdJHS-A/viewform). It will say waitlisted, but we will take care of that behind the scenes.

**Comment by mrbobbytables** [comment]
@quinton-hoole-2  Thanks! Link has been fixed.

**Comment by kmova** [comment]
Thanks @mrbobbytables. Done.

**Comment by k82cn** [comment]
I'll be there for SIG Scheduling as well.

**Comment by DirectXMan12** [comment]
I'll be there for SIG Autoscaling

**Comment by guineveresaenger** [comment]
You are all amazing and wonderful people. ❤️ ❤️ ❤️ 
I will update this thread and send emails as well as the event comes closer.

For now, the plan is:

We will put signs with SIG names on tthe tables in the room. This way, you and the new folks will be able to find each other easily, and you can start talking, answering questions, showing off your repo(s), maybe setting folks up with their first issue if they're ready for that.

It's not very formal - the format will be up to you and what questions you get. I will come up with some prompts to help get things going.

Also - suggestions and questions welcome! I am so excited!

**Comment by gyuho** [comment]
Hope it's not too late. I'll be there for SIG AWS. Please email leegyuho@amazon.com.

**Comment by M00nF1sh** [comment]
I'll be there for sig aws. Email yyyng@amazon.com 😄

**Comment by d-nishi** [comment]
I will be there too! 
Email: dnishi@amazon.com

**Comment by leakingtapan** [comment]
Would like to join for sig aws. Contact: chengpan@amazon.com

**Comment by Rajakavitha1** [comment]
I would be happy to attend for sig-docs.

**Comment by parispittman** [comment]
to summarize attendance: aws, autoscaling, scheduling, node, release, multicluster, ibmcloud, azure, scalability, network, storage, cluster lifecycle, cli, architecture, and contribex.

**Comment by guineveresaenger** [comment]
Dear SIG meet-and-greeters,

thank you again for being available to welcome new contributors into our community.

Here's a quick update on the details:

What: Be ready to chat with newcomers about their interests, be ready to exchange email/slack handles, set up SIG meeting invites, have a few "good first issues" or starting strategies on hand.

How: We will have table signs for each SIG and I will instruct new contributors to find you! After that, it's all informal Q&A.

Where: Room 605

When: Please plan to arrive early, at 3:20 pm; the planned start time is 3:30 but we may finish up the prior session early and I want to make sure the new contributors can find you and feel welcomed.

I am super excited for this event to happen - it should help everyone.

**Comment by Jeffwan** [comment]
Would like to join for sig aws. please email seedjeffwan (at) gmail.com

**Comment by nikhita** [comment]
Thanks for making this happen, everyone! :heart: 

Closing since this is now done.
/close
