### ISSUE TITLE
Automated removal of inactive members

### ISSUE THREAD

**Issue by tmrts** [kubernetes/community#276]
An "automated" cron job that enumerates the list of members that became inactive in the last 30 days window using the GitHub API to a [GitHub Org Owner in Kubernetes](https://github.com/kubernetes/community/blob/master/governance.md) for removal should suffice (Fully automating organization modifications might cause headaches).

cc @bgrant0607 @philips 

related to #142

**Comment by cblecker** [comment]
/remove-lifecycle stale
Still relevant

**Comment by nikhita** [comment]
A little tangential but somewhat related: auditing OWNERS files - https://github.com/kubernetes/community/issues/2878.

**Comment by nikhita** [comment]
Closing in favour of https://github.com/kubernetes/community/issues/3179 - since that has slightly more details.

/close
