### ISSUE TITLE
README: link to repository policy for working groups

### ISSUE THREAD

**Issue by philips** [kubernetes/community#2766]
In the README explaining working groups [recommend an associated repo](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#associated-repositories) instead of current language, as of https://github.com/kubernetes/community/pull/1994, about "not owning code".

**Comment by jbeda** [comment]
I can take this on if no one else does. Thanks for getting #1994 in so that we can just tweak it now.

**Comment by philips** [comment]
go for it @jbeda

**Comment by jbeda** [comment]
Looks like this'll be largely covered in https://github.com/kubernetes/community/pull/2702 but after that goes in I'll be sure to update it with a pointer to that suggestion as a way to incubate code outside of SIGs.  @pwittrock has already seen enough back and forth there that I'm happy to make this a delta after that is merged.

**Comment by philips** [comment]
Closed via https://github.com/kubernetes/community/pull/2702 I believe.

**Comment by philips** [comment]
@spiffxp fixed now? https://github.com/kubernetes/community/pull/3104
