### ISSUE TITLE
Finalize governance.md

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/community#277]
We've been iterating on governance.md to document how the project has been operating and to capture discussions from multiple issues, merged and unmerged PRs, and mailing-list discussions:
https://github.com/kubernetes/community/blob/master/governance.md

I created a Google doc to facilitate comments:
https://docs.google.com/document/d/1UKfV4Rdqi8JcrDYOYw9epRcXY17P2FDc2MENkJjMcas/edit

Please join kubernetes-dev, kubernetes-pm, or kubernetes-wg-contribex googlegroups if you want to access. Sharing requests will be ignored.

Once we take comments on the doc, changes will be pushed into a PR.

**Comment by tmrts** [comment]
cc @thockin @philips

**Comment by bgrant0607** [comment]
cc @smarterclayton

**Comment by bgrant0607** [comment]
cc @spiffxp

**Comment by bgrant0607** [comment]
cc remaining top-level approvers:
@jbeda @brendandburns @lavalamp @dchen1107

**Comment by bgrant0607** [comment]
The draft has been restructured to make it easier to read.

**Comment by bgrant0607** [comment]
I created a PR: #286

**Comment by idvoretskyi** [comment]
@bgrant0607 is it better to comment Google document or the PR?

**Comment by bgrant0607** [comment]
@idvoretskyi Please comment on the doc

**Comment by bgrant0607** [comment]
Another example:
https://github.com/nodejs/node/blob/master/GOVERNANCE.md

**Comment by tmrts** [comment]
This one is from GitHub: https://opensource.guide/

It includes detailed sections about maintainers, building communities, leading communities and so on, its a good read.

**Comment by bgrant0607** [comment]
Doc is deprecated. Now PR is primary.

**Comment by bgrant0607** [comment]
Superseded by the governance effort.
