### ISSUE TITLE
Transition all SIG-{cloud provider} to WG-{cloud-provider} under SIG-Cloud-Provider

### ISSUE THREAD

**Issue by hogepodge** [kubernetes/community#2770]
Under the charter of the recently founded SIG-Cloud-Provider, global code ownership will transition from individual cloud sigs to sub-projects (or working groups) within SIG-Cloud-Provider.

Tracking issue for this work.

https://github.com/kubernetes/community/blob/master/sig-cloud-provider/CHARTER.md#subprojects--areas-of-focus

/sig-cloud-provider
/sig-aws
/sig-azure
/sig-gcp
/sig-ibmcloud
/sig-openstack
/sig-vmware

**Comment by hogepodge** [comment]
In recent discussions with SIG-Cloud-Provider participants at KubeCon Seattle, it was indicated that many providers would like to keep their SIGS, or SIG-like structures, intact for further cross-SIG development and user support. This will be an ongoing topic of discussion and we can use this as a tracking issue for it.

**Comment by d-nishi** [comment]
@hogepodge we discussed the idea of sub sigs under sig cloud provider. 

Is that discussion being moved forward?

**Comment by hogepodge** [comment]
The discussion will be moving forward, no decision has been made on any particular course of action yet.

**Comment by andrewsykim** [comment]
I'm working on a proposal that will be reviewed by steering committee, but would be great to get everyone in the SIG (and other provider SIGs) to review first :).

**Comment by d-nishi** [comment]
@andrewsykim let’s work together on the proposal if that’s fine by you. Would love to help!

**Comment by andrewsykim** [comment]
Sounds good! I'll share a template of it soon :)

**Comment by justaugustus** [comment]
@andrewsykim -- happy to review as well!
/assign

**Comment by GeetikaBatra** [comment]
@hogepodge is this related to these two: https://github.com/kubernetes/cloud-provider-openstack and https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack

I see two places where the cloud providers reside. Also, I see that https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack lacks some tests. If that's okay I would like to take it up.

**Comment by andrewsykim** [comment]
@GeetikaBatra yes, this effort is related to that. 

Regarding test in the open stack provider, we can probably discuss that in a separate issue. I've created one here https://github.com/kubernetes/kubernetes/issues/74894 and pinged the appropriate people

**Comment by justaugustus** [comment]
## Consolidation Tracking   

### Prerequisites for SIG Retirement
- [x] SIG’s retirement decision follows the decision making and communication processes as outlined in their charter

### Steps:
- [x] Send an email to kubernetes-dev@googlegroups.com and community@kubernetes.io alerting the community of your intentions to disband or merge.
- [ ] Archive the member and lead/chair mailing lists
- [x] Check the [slack-guidelines.md] for latest process on archiving the slack channel
  - Renamed Slack channels
- [ ] Deactivate the zoom license(s)
- [ ] Delete your shared SIG/WG/UG calendar
- [ ] Ensure that the [youtube-guidelines.md] links are removed and you've uploaded all SIG/WG/UG meetings to date
- [ ] Move the existing SIG directory into the archive in `kubernetes/community`
- [ ] GitHub archiving/removing/other transactions:
   - [ ] Move all appropriate github repositories to an appropriate archive or a repo outside of the Kubernetes org
   - [ ] Each subproject a SIG owns must transfer ownership to a new SIG, outside the project, or be retired
   - [ ] File an issue with kubernetes/org if there are multiple repos
   - [ ] Retire or transfer any test-infra jobs or testgrid dashboards, if applicable, owned by the SIG. Work with SIG-Testing on this.
   - [ ] Migrate/Remove/Deprecate any SIG/WG labels in labels.yaml
   - [ ] Remove or rename any GitHub teams that refer to the SIG
   - [ ] Update sigs.yaml to remove or rename

**Comment by mrbobbytables** [comment]
I think all the tasks have been completed outside of the remaining ML / Zoom / Calendar tasks.

**Comment by mrbobbytables** [comment]
Jorge and I will finish the tasks out on this one.
/assign @castrojo @mrbobbytables 
/remove-lifecycle frozen

**Comment by mrbobbytables** [comment]
I believe all AIs have been completed, going to go ahead and close this issue for now.

/close
