### ISSUE TITLE
Contributor Experience Survey Results

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#2802]
- [x] post results
- [x] post README for results
- [x] follow up with everyone who wanted a water bottle
- [ ] respond to everyone who left an email that had follow up questions, needs more 411 on a topic, etc. 
- [ ] write a blog post
- [x] process pretty graphs
- [ ] turn survey angst and cheers into actionable items

**Comment by nikhita** [comment]
@parispittman do we want to target this for the current milestone?

I guess...
/kind feature
/priority important-longterm

**Comment by parispittman** [comment]
working on the blog post here -> https://docs.google.com/document/d/1U6tgPVsOVlDcsxCSXz7lBFyQc8KIdglTRrk2uuf-PG0/edit?usp=sharing
