### ISSUE TITLE
working group governance feedback

### ISSUE THREAD

**Issue by philips** [kubernetes/community#2803]
Address remaining feedback on wg-governance.md now that it is merged.

https://github.com/kubernetes/community/pull/2702#pullrequestreview-164511723

/assign @pwittrock

**Comment by nikhita** [comment]
> Address remaining feedback on wg-governance.md now that it is merged.

This was addressed in https://github.com/kubernetes/community/pull/2814. Closing. Please reopen if needed.

/close
