### ISSUE TITLE
Code Base Tours - Videos

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#2812]
need to do more code base tours as part of meet our contributors and otherwise. @sttts did one recently - https://youtu.be/yqB_le-N6EE - that has 400 views already and folks have given great praise that have watched it. 

what other repos outside of k/k should we do a code base tour that would be beneficial to people who want to help out with triage and other helpful ways? or people who want a quick view inside? Can we cut k/k up into deeper dive sessions?

If you have suggested repos, please list here. You do not need to volunteer to give the tour but bonus swag points if you do.

**Comment by shubheksha** [comment]
I believe the kubectl codebase would make for a good component for this as there are ongoing efforts to complete isolate it from k/k.

**Comment by soltysh** [comment]
@parispittman yeah, I can do that one.

**Comment by castrojo** [comment]
I ran a poll: https://discuss.kubernetes.io/t/poll-what-kind-of-small-one-topic-videos-would-you-like-to-see/3200/2

So far "As k8s-Controllers or Operators use workqueue to keep its state. It would be nice to go quick deep-dive into the workqueue package to understand its implementation and how it is used by controllers." would be a good one as well.

**Comment by parispittman** [comment]
CSI code base tour happened on April 3rd

**Comment by nikhita** [comment]
@parispittman looks like we have got sufficient traction on code base tours now :rocket: 

Should this issue still be kept open?

**Comment by parispittman** [comment]
@nikhita I wanted to keep open to collect other suggestions for code base tours but can be convinced to close. i can do a discuss thread or something - open to other suggestions, too.

**Comment by nikhita** [comment]
> i can do a discuss thread or something 

why_not_both.gif :wink: 

> I wanted to keep open to collect other suggestions for code base tours

I guess we can keep it open so there is a place where people can chime in. We can revisit this later as well.

**Comment by mrbobbytables** [comment]
If it's going to remain open as a more long term item, it might be worth pulling out of May milestone and turn this into more of an umbrella issue.

**Comment by alejandrox1** [comment]
Update on this:
Here is the playlist for all code base torus: https://www.youtube.com/playlist?list=PL69nYSiGNLP0gugLYzpNR1ueyUj9GjzpK

Other than that, please request any additional code tours you want to see here!
Currently, we should do
* [ ] kubectl
* [ ] workqueue - as per [discuss poll](https://discuss.kubernetes.io/t/poll-what-kind-of-small-one-topic-videos-would-you-like-to-see/3200)
* [ ] CSI -this one is done just need to add it to the playlist

**Comment by alejandrox1** [comment]
I know there are more code base tours in the previous meet our contributors sections so I will go through them and get them in the playlist.

**Comment by parispittman** [comment]
@alejandrox1 
kubectl is in may with maciej
garbage collection in june with david

**Comment by alejandrox1** [comment]
Thank you @parispittman 
kubectl just went live. I'll start working on the garbage collection one then!

**Comment by mrbobbytables** [comment]
@justaugustus did a good break down image builder and some other things yesterday during the release engineering meeting that would be worth breaking out on its own:
https://www.youtube.com/watch?v=xZREdD35Kh0

**Comment by alejandrox1** [comment]
> @justaugustus did a good break down image builder and some other things yesterday during the release engineering meeting that would be worth breaking out on its own:
> https://www.youtube.com/watch?v=xZREdD35Kh0

Will start working on it :+1:

**Comment by mrbobbytables** [comment]
We have a [playlist for code-walkthroughs](https://www.youtube.com/watch?v=EImWsMI-I48&list=PL69nYSiGNLP0gugLYzpNR1ueyUj9GjzpK) and add useful vids as they come in. 
I think this is safe to close as long as we continue that pattern?

**Comment by parispittman** [comment]
this doesn't get much traction anymore so I'll think about using the discuss board or some other way to generate ideas here. 

/close
