### ISSUE TITLE
SIG Chair/TL Training 

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#2813]
Develop a video and/or in person training followed up by new documentation creation and doc clean up of existing materials. Improve the onboarding experience for new chairs/tls so they have all of the information they need to be awesome at their role.

**Comment by justaugustus** [comment]
I created another issue, which overlaps with some of this: https://github.com/kubernetes/community/issues/2847

**Comment by parispittman** [comment]
Do you mind if I update this issue with some of your comments and then close #2847 ? All of your concerns from there I think will be covered in here.

**Comment by justaugustus** [comment]
From #2847 (Create explicit instructions on SIG leadership access hygiene):
> While we do a pretty good job of defining [what's required to create a SIG](https://github.com/kubernetes/community/blob/master/sig-governance.md#sig-creation-procedure), I'm not sure that I've seen documentation on what to do when SIG leadership changes.
> 
> Some ideas would include:
> 
> * Sharing / rotating:
>   * credentials for Zoom
>   * YouTube playlist link
>   * SIG calendar access
>   * Google Group ownership
> * required lists to join
> * sigs.yaml updates

**Comment by parispittman** [comment]
other topics 
- where to find and what governance docs to read as a chair/tl
- slack tips for your channel(s)
- code of conduct

**Comment by parispittman** [comment]
-surveymonkey (surveys)

**Comment by parispittman** [comment]
@tpepper @jberkus - any materials that we should include for release that chairs need to know?

**Comment by parispittman** [comment]
we tested this at the last contributor summit (seattle 2018) and it had some bumps but went well. setting a new issue to address the iteration. purpose of this issue has been achieved.
