### ISSUE TITLE
Kick off Speed Mentoring planning for KubeCon Seattle 

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#2815]
Start planning for KubeCon Seattle Speed Mentoring activity. 

Had kick off call with LF/CNCF and @tpepper recently. We hashed out some generalities and started looking at dates times. Decided that we should do two events vs one and keep them in the AM or PM to avoid major schedule conflicts. 

This issue will close once we have posted the advert for the event.

**Comment by tpepper** [comment]
Meetings ongoing.

Call for mentors and mentees about to go out, including survey of info desired by mentees.

Later this month we will compare the mentor list with the desired info, and possibly reach out to target a few community members who can fill any gaps.

**Comment by nikhita** [comment]
@parispittman @tpepper Thanks for making this happen! :heart: 

Closing since this is now done.
/close
