### ISSUE TITLE
Propose replacing Graph & KEP of the week w/ automation focused slot

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#2818]
Naming is hard: automation of the week? bot command of the week? contribex tips?

Basically I think the Graph of the Week slot has outlived its utility to the community.  We've shown all the graphs, but I don't know if people are using them.  I'd rather replace that 5min slot with something that shows people how to do stuff on our project, or a piece of our automation, etc.  I think this should be SIG Contribex's time to share whatever improvements we've made to the workflow, or whatever things are out there that people may not know about.

I'm also not sure if KEP of the Week is worth keeping around.  The last time we had one was August 30th.

Some of these I've probably already done, but ideas include:
- a tour across PR's, deck, gubernator, and testgrid
- /lifecycle + why @fejta-bot uses it
- /help + /good-first-issue
- /hold + [wip]
- /kind and /sig vs. needs-kind and needs-sig
- /lgtm + tree hashes: squash commits, nothing changes, lgtm stays on (this is being piloted in test-infra)
- filing issues on kubernetes/org to get github stuff done
- updating labels.yaml to add labels to your repo (or to all repos)
- updating branch protection and required contexts for your repo

Opening an issue for discussion.  I think closure happens when:
- we reach agreement
- I update the community meeting template
- we have a backlog of topics

etc.

/kind feature
/sig contributor-experience
/area community-management

FYI @parispittman @castrojo as subproject owners

FYI @mattfarina @nikhita @Phillels as people I remember +1'ing the idea during the most recent sig-contribex meeting

**Comment by jeefy** [comment]
+1

I like the sound of "Contributor Tips". 

It feels inclusive and casts a wide net toward the desired target audience.

**Comment by spiffxp** [comment]
FYI @jberkus 
What about any "graphs" we might want to present? IMO they should be meaningful and actionable from a contributor perspective, and can fit into this slot.  We could also talk about them in Announcements, as we often have spare room then.

FYI @justaugustus @calebamiles 
What about any "KEPs" we might want to present?  I think we often have time at the end in Announcements and they could go there.  We could also encourage SIG's to present KEPs during their update (pretty sure this is already in the slide template)

**Comment by castrojo** [comment]
I feel like KEPs should be a top primitive. The community meeting is cross-SIG by nature and having someone present a KEP is a good way to make sure they're getting eyeballs.

For the "Contributor Tips" I think we should just have a list of things we could be rotating on:
- Chart/Devstats o' the week.
- Bot-o-logy - Something bot/automation related. "Did you know you can foo?" 
- Some other community metric of the week - slack, discuss, youtube, etc. 
- And then a catchall slot for something that might be a recurring thing that is more important than a typical announcement.

We could also perhaps make it more useful by not just assuming "5 minute slot" to encourage quick, good tips. For example:

- "ok thanks for the demo, this week's tip by Jorge" 
- "Spelling-fix typos got you down? Did you know we have a trivial edit policy? Here's the link to the wording/policy to help you out."
- "Wow that's great, moving on!" 

That way it's quick and TLDR and it doesn't make people feel like they have to put together slides, etc.

**Comment by jberkus** [comment]
I think we can drop Graph O' The Week.  I may keep doing it for LWKD, but it doesn't need to be part of the community meeting.

I think we should keep KEP of the week, *provided* that we can make it the job of SIG-PM to supply us with one.  Since having a KEP of the week is directly related to successfully promoting the KEP concept, they should be eager to do this.  If they're not, I think it spells trouble for KEPs as an idea.

**Comment by justaugustus** [comment]
This has ballooned into "Let's define the exact shape of the Community Meeting" as opposed to "Let's remove some things". Could we update the title to reflect that?

In my mind, I see the following:
- Announcements
- Demo
- SIG Updates
- KEP preso
- Did you know? / Contributor Tips / `_____` O' The Week
- Shoutouts

I think SIG Updates are good for who we are, what's going on, upcoming work, and how to get involved.

The KEP presentation should be a "deeper" dive into a specific KEP.
@castrojo and I discussed on some call a little while ago and yes, KEPs should absolutely be a top-level primitive of the meeting as opposed to an afterthought.

That said, while defining / improving / facilitating the KEP process is a function of SIG PM, I would hope that SIGs are excited about the work they're doing and willing / able / available to present that work to a wider audience.

I'm happy to do some additional legwork, but SIGs should be seeding a backlog of KEPs to discuss and capable presenters, as opposed to SIG PM chasing them down.

> Since having a KEP of the week is directly related to successfully promoting the KEP concept, they should be eager to do this.

While that is true, there's a significant amount of work happening in the background (see [here](https://github.com/kubernetes/enhancements/issues/617) and [here](https://github.com/orgs/kubernetes/projects/5)) to make KEPs successful, that is of higher priority than finding weekly KEP presenters.

cc: @calebamiles @jdumars

**Comment by parispittman** [comment]
Can we nuke the future topics section, too? [scope creep - I'll see myself out]

**Comment by spiffxp** [comment]
>This has ballooned into "Let's define the exact shape of the Community Meeting" as opposed to "Let's remove some things". Could we update the title to reflect that?

No no no please let's not scope creep this.

I'll just drop GoTW for this since I seem to have gotten consensus there.  We can see how KEP of the week continues to play out.

**Comment by jberkus** [comment]
@justaugustus if SIG-PM *isn't* going to help schedule KEPs, I'd argue that we should drop them from the community meeting.

Speaking as a rotational moderator, I have too little insight into KEPs to schedule them.  I'm happy to follow-up/confirm, but I need SIG-PM to create the intial schedule.

**Comment by spiffxp** [comment]
/assign
/unassign @castrojo 
I'm going to ensure the community meeting template is updated and then close this out

**Comment by jberkus** [comment]
Having said the above, I just hunted down and scheduled a KEP for this week.

**Comment by spiffxp** [comment]
On the subject of KEPs specifically, I'm willing to work with 1.14 release team and sig arch to identify relevant high profile KEPs to be discussed in community

**Comment by jberkus** [comment]
I think we can do a KEP of the week, we just can't do it every week.

**Comment by spiffxp** [comment]
/close
Yes, good
