### ISSUE TITLE
[Doc fix] [Minor] Fix number of comments on pull requests in month for active contributors

### ISSUE THREAD

**Issue by moizjv** [kubernetes/community#283]
I was reading docs and under community expectations, the following is missing. 

[Commented on more than ?? pull requests in the previous month, or more than 50 pull requests in the previous 12 months.](https://github.com/kubernetes/community/blob/master/contributors/devel/community-expectations.md#code-review)

I can fix it, but i do not know how many comments on PRs required in previous month 

Thanks,
Moiz

**Comment by xiangpengzhao** [comment]
This was fixed in https://github.com/kubernetes/community/pull/418.

So can we close this issue now? @bgrant0607 @moizjv

**Comment by moizjv** [comment]
Yes thanks!
