### ISSUE TITLE
Changes to SIG Governance should require some concensus from SIGs

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#2833]
This merged PR from SIG PM adds new requirements to other SIGs that imposes requirements on them: https://github.com/kubernetes/community/pull/2289

I feel like this sets a bad precedent for the following reasons:

- We shouldn't retcon new requirements onto SIGs unless they have a say in those requirements.
- New requirements of other SIGs should perhaps at least be discussed on k-dev and documented in the PR or document. 
- Do we have a consensus model on how to approve changes to SIG governance? What if half the SIGs want this but the other half doesn't?
- What role (if any) should steering have on determining new requirements for SIGs. 

Also how should we as a project enforce cross-cutting SIG asks to other SIGs? I know these are open questions that's why I filed the issue. 💃

**Comment by justaugustus** [comment]
(Hmm, that PR feels like a throwback for me.)

The original intent was to actually remove a requirement, namely, having specified SIG PM reps within the SIG.
While I agree with the spirit of this issue, the things added to that PR should have been things that a SIG was already doing and at present, I think only 50% actually happens.

Stepping away from that PR and just considering the general case, what does consensus look like for cross-SIG concerns? 

The general function of Steering is to delegate decision making to the appropriate SIG and make decisions when another governing body doesn't exist to do so. Right?

That said, we have a few horizontal SIGs, which are specifically in the business of affecting cross-SIG change e.g., PM, Arch, Release, ContribEx. So how can we ensure those SIGs have the agency to make decisions within their purview without undue friction?

Email to k-sig-leads + lazy consensus + wider announcement to k-dev seems reasonable?

(Thinking retrospectively, the current me wouldn't merge the PR you mentioned without at least some combination of that. :) )

**Comment by nikhita** [comment]
/remove-lifecycle rotten

> Email to k-sig-leads + lazy consensus + wider announcement to k-dev seems reasonable?

:+1:

**Comment by nikhita** [comment]
Let's document this. 

/kind documentation
/help

**Comment by nikhita** [comment]
Maybe even 

/good-first-issue

**Comment by thecrudge** [comment]
As a brand spanking new contributor, Im not entirely sure this needs to be labeled “good first issue”, there is a lot of history here and is very hard to determine context, even after reading through the related PRs and Issues. I would be hesitant to comment aside from what I am putting here.

**Comment by castrojo** [comment]
/assign @justaugustus 
/remove-good-first-issue

This section should just be revised to line up with SIG PM's new charter and the KEP process, so just assigning it to Stephen since he's sitting in the venn diagram of keps, PM, and contribex.

**Comment by celanthe** [comment]
Hi @castrojo, @justaugustus  I am working on contribex issue triage, and wanted to circle back as to the status of this PR.

If you have any updates as to where it's at in the process, or if it can be closed or frozen, that would be great.

If this issue needs to be escalated or there is someone else I should loop in, please let me know so that I can get this moving again! Thank you so much!

**Comment by celanthe** [comment]
Hi @castrojo, @nikhita, @justaugustus--I'm at the docs sprint at the contributor summit doing some issue triage (yay!) and I just wanted to circle back on this and see if we found a resolution for this yet, or if it can be closed, or should it get tagged with another SIG label for attention? TYSM for any help you can provide! :D
