### ISSUE TITLE
Create explicit instructions on SIG leadership access hygiene

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/community#2847]
While we do a pretty good job of defining [what's required to create a SIG](https://github.com/kubernetes/community/blob/master/sig-governance.md#sig-creation-procedure), I'm not sure that I've seen documentation on what to do when SIG leadership changes.

Some ideas would include:
- Sharing / rotating:
  - credentials for Zoom
  - YouTube playlist link
  - SIG calendar access
  - Google Group ownership
- required lists to join
- sigs.yaml updates 

rel: https://github.com/kubernetes/community/issues/2813
/sig contributor-experience
/help

**Comment by justaugustus** [comment]
I coulddddd work on this, but I'm just as happy to review someone else's PR :)
/cc @parispittman @castrojo

**Comment by parispittman** [comment]
Can we cover this in #2813 @justaugustus

**Comment by justaugustus** [comment]
@parispittman totes. just dropped a comment over there. :)
/close
