### ISSUE TITLE
Establishing Community Content Style Guide

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#2850]
This issue came to light recently while reviewing content on the [WIP contributor site](https://contributor.kubernetes.io/). Currently much of the docs within the community repo do not follow a consistent set of rules with regard to tone and formatting. There are a few suggestions here or there such as the [Markdown link style guide](https://git.k8s.io/community/sig-contributor-experience/markdown-link-style-guide.md). However, forming a more comprehensive general style guide, say similar to the general [Kubernetes Docs Style Guide](https://kubernetes.io/docs/contribute/style/style-guide/) would likely be quite beneficial, especially before the start of the [Outreachy](https://www.outreachy.org/communities/cfp/kubernetes/) project to revamp the Developer Guide.

Additionally, going back and updating the current content to conform to the established style guide would provide a series of 'good first issues' for new contributors. A part of this task could include fixing links or other minor issues that should hopefully cut down on the amount of [trivial pull request flooding](https://github.com/kubernetes/community/pull/2602).

/cc @parispittman @castrojo 
/sig contributor-experience
/area community-management

**Comment by parispittman** [comment]
thanks for filing!

**Comment by parispittman** [comment]
https://hackmd.io/Fe8YTu5XSUyt4dP3P2MGkg?view -author: @mrbobbytables

**Comment by mrbobbytables** [comment]
closed by #3125 

/close
