### ISSUE TITLE
CNCF CoC Translations Needed for Discuss Regional Boards

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#2855]
Tracking Issue.

With the goal of making the [Kubernetes Discuss Forums](http://discuss.kubernetes.io) more welcoming and inclusive for non-english native speakers, we have planned to launch regional specific categories moderated by trusted community members fluent in those languages. As the forums are governed by the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md), we would like to provide a translation of the CoC for each regional category before officially making them public. 

There is an [open issue for the translation request](https://github.com/cncf/foundation/issues/15) in the [CNCF/foundation](https://github.com/cncf/foundation/) repo.

/sig contributor-experience
/area community-management

**Comment by rootsongjc** [comment]
That's a good idea but the website [Kubernetes Discuss Forums](https://discuss.kubernetes.io/top/all) is too slow in China.

**Comment by castrojo** [comment]
We can for sure bump up to the plan that offers a CDN, I'll investigate.

**Comment by castrojo** [comment]
@rootsongjc It would help if we knew which parts of the site were slow, can you provide any more information?

**Comment by idealhack** [comment]
I haven't noticed it's slow, maybe it's because I have cached those js and images from `discourse-cdn-sjc2.com` before. When I am refreshing the site with cache disabled, sometimes it's quite slow. So this may affect some new visitors.

**Comment by tao12345666333** [comment]
```
HTTP/2 200                                                                                                                 
server: nginx/1.13.11                                                                                                      
date: Thu, 25 Oct 2018 16:38:48 GMT
content-type: text/html; charset=utf-8
vary: Accept-Encoding                             
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff           
x-download-options: noopen                 
x-permitted-cross-domain-policies: none
referrer-policy: strict-origin-when-cross-origin
x-discourse-route: list/top_all
cache-control: no-cache, no-store                                                                                         
x-request-id: d18129d2-b9cd-439c-a2d6-97eb511a655e                                                                        
x-runtime: 0.235471                                                                                                       
x-discourse-trackview: 1                                                                                                  
discourse-proxy-id: app-router-tiehunter02                                                                                
strict-transport-security: max-age=17280000      

Body stored in: /tmp/tmp6je5xj1z

  DNS Lookup   TCP Connection   TLS Handshake   Server Processing   Content Transfer                                      
[    509ms   |      238ms     |     572ms     |       725ms       |       536ms      ]                                    
             |                |               |                   |                  |                                    
    namelookup:509ms          |               |                   |                  |                                    
                        connect:747ms         |                   |                  |                                    
                                    pretransfer:1319ms            |                  |                                    
                                                      starttransfer:2044ms           |                                    
                                                                                 total:2580ms                             

(MoeLove) ➜  ~

```

It's my visit detail. For comparison, `ks8.io` only takes 704ms.

**Comment by mrbobbytables** [comment]
With the translations provided and the launch of the regional boards, I'm inclined to close this issue but I don't want to disregard the site slowness.

The kubernetes discussion board hosting is provided by [Discourse](https://discourse.org). If users are experiencing consistent site slowness, our best bet is to gather up as **MUCH** information as we can in a thread on the forum or as an issue here to provide Discourse and their backing CDN ([keycdn](https://www.keycdn.com)). Preferably including how long it took to load, when it occurred, their general geographic location and which browser they're using.

If they don't mind doing a bit more detective work to pop open something like chrome dev tools to see how long specific elements (like the js files being loaded from https://discourse-cdn-sjc2.com) would be incredibly helpful and good evidence to take back as well.
