### ISSUE TITLE
Increasing the cluster limits

### ISSUE THREAD

**Issue by chaitanyaenr** [kubernetes/community#2856]
The cluster limits including pods per namespace, deployments per namespace were lowered in https://github.com/kubernetes/community/pull/2231. We ran some scale tests where we created 48k pods per namespace and couldn't see any abnormal spikes in time duration and resource usage by control plane when we increased the pod count from 3k to 48k.

I wanted to check if there are any known issues stopping us from bumping the pods per namespace limit to 48k or 50k provided there are enough resources available on the nodes.

**Comment by chaitanyaenr** [comment]
@wojtek-t PTAL.
/cc @sjug @jeremyeder

**Comment by chaitanyaenr** [comment]
@shyamjvs PTAL.

**Comment by chaitanyaenr** [comment]
@shyamjvs @wojtek-t thanks for looking into this, we will test the limit on kubernetes when we get a chance and let you guys know. Sorry for the delayed response.

**Comment by nikhita** [comment]
Closing this issue. Please reopen and add next steps if this shouldn't have been closed :)

/close
