### ISSUE TITLE
de-dupe sig-governance.md files, rename root copy to sig-lifecycle

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#2857]
addresses: https://github.com/kubernetes/community/issues/2029#issuecomment-431925933
by covering this work: https://github.com/kubernetes/community/pull/2832#issuecomment-432345332

I took an action item to followup on this in the latest steering committee meeting.

/committee steering
/sig contributor-experience
/kind cleanup
/kind documentation
/priority important-soon
/assign

**Comment by parispittman** [comment]
I'm working on a lot of this now and will PR some and mention in here what was not done.

**Comment by parispittman** [comment]
[shared with k-dev ML]
[1st round of PRs listed here](https://docs.google.com/document/d/192ct2e2u_yjvhg_WD-96xBtmc-f8M_FMbt4OfA9vvN4/edit?usp=sharing)
2nd round will be combo'ing the leftovers of sig-gov at the root and sig-gov at /committee-steering

**Comment by parispittman** [comment]
@spiffxp do you think the work done in #3287 answers this?

**Comment by parispittman** [comment]
@spiffxp friendly ping - is this ok to close?

**Comment by spiffxp** [comment]
/close
- #3601 removes the dupe files or tombstones I see in kubernetes/community
- I've verified nothing links to /sig-governance.md within kubernetes/*
