### ISSUE TITLE
Track Facilitators needed for Contributor Summit at Kubecon Seattle

### ISSUE THREAD

**Issue by qedrakmar** [kubernetes/community#2862]
Several people will be needed to manage running sessions and directing attendees to various locations.  There are at least 5 stations that will need to be covered.  Volunteers from those already attending the Contributor Summit should respond in the comments below.

**To ensure volunteers do not miss the sessions they want to attend, please reference the current Summit schedule, which is available [here](https://github.com/kubernetes/community/tree/master/events/2018/12-contributor-summit)**

Tasks include (but are not limited to) the following:
- Act as timekeeper for rooms, ensuring sessions start and end on time, including providing verbal and/or visual warnings for 10, 5, and 2 minutes remaining
- Ensure session recording is running smoothly
- Ensure all recorded sessions are at least displaying a slide with the session name
- Go find assistance, in the case of any room or A/V problems that are not immediately solvable
- Provide directions to attendees regarding the schedule and other relevant locations
- Remind attendees to write down action items and takeaways, if any
- Remind groups to include any attendees who want to, but have not yet had a chance to speak
- Generally be available and helpful for attendees

Expected Stations:
- Main Track
- New Contributor Summit
- Hallway + Contributor Lounge
- Hallway + Docs Sprint
- Unconference Area
- possibly more

A post will also be made on the Discuss role board that will point back to this issue.

This issue will be closed after the Contributor Summit in Seattle.

**Comment by onyiny-ang** [comment]
I'd like to help out! :raising_hand_woman:

**Comment by mhausenblas** [comment]
Happy to help out.

**Comment by chris-short** [comment]
Count me in.

**Comment by archyufa** [comment]
Will be happy to help. Count on me.

**Comment by shubheksha** [comment]
I can help out!

**Comment by idealhack** [comment]
I'd like to help 🙋‍♂️

**Comment by qedrakmar** [comment]
Scheduling all interested parties will take place AFTER Kubecon Shanghai (Nov 19th or so).

**Comment by qedrakmar** [comment]
I'm closing this issue.  I will contact everyone in the next week or so for scheduling.
