### ISSUE TITLE
Audit/groom OWNERS files

### ISSUE THREAD

**Issue by mml** [kubernetes/community#2878]
We have a lot of OWNERS files, and entries in those files can become stale as people leave the project or are no longer suitable owners in an area (e.g. the area has since moved in new directions and they are contributing elsewhere.)

This is an audit mainly for suitability and correctness of the owners.  We want to ensure that these people are considered suitable by the community to do reviews or approve PRs.  Presumably it means they are knowledgeable in the area, have shown good judgement, and are in good standing and at the appropriate level on the contributor ladder.  It's not about PR review latency.  That is the focus of #2873.

I don't think *this* process can be fully automated, because there's nothing quantitative that definitively shows whether or not person X is a good or bad choice.  Examples: they may have written or reviewed a lot of PRs in the past year in this area, but have just transferred to a new project; they may have done no reviews in this area, but there may also be no change in this area; the project may be brand new, the person may be a co-owner, but so far there's not enough volume to show that they "contribute" in the area.

Given those requirements: (1) audit for correctness, (2) difficult (at best) to automate, I propose we simply ask owners to review owners.

Proposal

0. (Base case) Begin with an owner from the root OWNERS file.
1. This owner will audit the OWNERS file in question, making additions or removals as appropriate.
2. (Induction step) This owner will, for each subdirectory, choose an owner whom they trust from *that* OWNERS file to begin the process from step 1.
3. At each stage, the chosen owner from the parent directory is expected to review and understand the justification for all changes, and to generally come to consensus with the sub-reviewer about the content of their file.
4. In the base case, we could choose an alternate root owner to act as the reviewer.  Or all other root owners or a quorum of root owners.

(This is spun out of #2873.  We want to focus #2873 on making sure we have good review latency.  That might mean adding reviewers or tweaking the weights for auto-assignment or other things, but it's explicitly not about making sure that we have the right people in the right OWNERS file.)

cc @dims

**Comment by bgrant0607** [comment]
"A lot" of OWNERS file is an understatement. The last time I counted, it was nearly 5000. 

We should (a) consider reducing the number of unique OWNERS files and (b) make most of the files (at least "top level" ones) refer to centrally maintained lists of approvers and reviewers for each subproject (related to #1673).
