### ISSUE TITLE
Plan Outreachy participation for the Dec 2018 - March 2019 round

### ISSUE THREAD

**Issue by nikhita** [kubernetes/community#2880]
Kubernetes is participating in the [Outreachy](https://github.com/kubernetes/community/blob/master/mentoring/outreachy.md) internship program for the Dec 2018 - March 2019 round. This issue will act as a landing page to all planning related to Outreachy.

The Kubernetes page on the Outreachy website can be found [here](https://www.outreachy.org/communities/cfp/kubernetes/).

**List of things that need to be done:**

- [x] Send an [email to the kubernetes-dev mailing list](https://groups.google.com/d/topic/kubernetes-dev/wrbjJD9_vQo/discussion) for a Call for mentors, projects and sponsor organizations.
- [x] Figure out sponsors for Outreachy interns.
  - CNCF is sponsoring 2 interns and Google is sponsoring 1 intern.
- [x] Sign up Kubernetes as a community/org on the Outreachy website.
  - @parispittman and @nikhita are coordinators for Kubernetes.
- [x] Add projects and sign up mentors on the Outreachy website.
  - "Adding advanced features to Kubernetes client libraries" mentored by @brendandburns 
  - "Improve the integration of Kubernetes client libraries with existing language documentation" mentored by @brendandburns 
  - "Revamp Kubernetes Developer Guide" mentored by @parispittman 
- [x] Create a channel on slack to help all Outreachy applicants with getting started, answering questions, etc.
  - Created the #outreachy-apps channel on Slack.
- [x] Help applicants with their application and make sure that all applicants have submitted their application on the Outreachy website by November 6.
- [x] Work with mentors to select interns.
- [x] Announcement of results on November 16.
  - @eduartua will be working on the dev guide :tada: 
  - Unfortunately, applicants to other projects were ineligible as per Outreachy.

We will consider this issue closed once all interns have been selected and announced.

/sig contributor-experience
/area mentorship-planning

**Comment by parispittman** [comment]
Thanks for this @nikhita! 

For those who are reading that may be interested in an internship, please visit the outreachy.org site and complete the application process through there first. All application instructions will be listed there.

**Comment by nikhita** [comment]
Selection is done - @eduartua will be working with us on the developer guide project! :tada: :tada: :tada: 

Closing this issue since selection is over.
