### ISSUE TITLE
Clarify that membership in non-`kubernetes` orgs doesn't imply the inverse

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/community#2883]
ref: 
- https://github.com/kubernetes/org/issues/174#issuecomment-431137034
- https://github.com/kubernetes/org/pull/212#issuecomment-434924300

/cc @spiffxp @cblecker 
/help

**Comment by mrbobbytables** [comment]
Just adding a bit more information to the thread  -- The membership requests in the referenced links are specifically related to the migration of the kubespray  project from incubator to sigs as a subproject under sig-cluster-lifecycle (https://github.com/kubernetes/org/issues/208).
