### ISSUE TITLE
discuss.k8s.io guidelines

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#2884]
draw up discuss.kubernetes.io guidelines like zoom-guidelines.md, slack-guidelines.md, etc. and include other information about it in our communication folder. cc/ @castrojo

**Comment by castrojo** [comment]
The moderation workflow is the same as a list, I think we can get away with just a section in moderation.md (under mailing lists), I'll work up a PR on this next weekish.

**Comment by castrojo** [comment]
Not really, it has documentation, perhaps we can riff on something like this? https://meta.discourse.org/t/discourse-moderation-guide/63116?u=erlend_sh&source_topic_id=65817

**Comment by parispittman** [comment]
the guidelines should link to that and then also take the discuss stuff for creation of lists from sig-governance. we need a canonical source of truth for all things discuss to link to that instead of talking about it in several docs across the community repo.
