### ISSUE TITLE
zoom to youtube automation pipe

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#2923]
we are exploring paths from zoom recordings to the kubernetes youtube account for auto uploading. 

contribex has access to [this file](https://docs.google.com/document/d/1-8kyEQkWATJbNZtW2wrkAil38RakXdV4LDY-clHVVdA/edit?usp=sharing) for goals/non goals and preliminary documentation.

**Comment by nikhita** [comment]
Since this was "In Progress", I'm going to add the milestone.

/milestone May

**Comment by parispittman** [comment]
splain has been explored and currently in use by many sigs. closing this issue.

/close
