### ISSUE TITLE
End to end testing documentation - key information missing

### ISSUE THREAD

**Issue by sirkubax** [kubernetes/community#2931]
https://kubernetes.io/docs/getting-started-guides/ubuntu/validation/
https://github.com/kubernetes/community/blob/master/contributors/devel/e2e-tests.md

On the following websites I cannot find a key information:
What is 'test'? Where can I see the test code? 
Are some tests generic? How can I re-use them?
How to define my new 'test'.
How to test 'my service' with 'some test'....

Please point me to some docs 
@kubernetes/sig-testing

**Comment by sirkubax** [comment]
@kubernetes/sig-testing

**Comment by cblecker** [comment]
Closing as duplicate
/triage duplicate
/close
