### ISSUE TITLE
Ability to get accessible namespaces based on RBAC

### ISSUE THREAD

**Issue by mwringe** [kubernetes/community#2942]
With RBAC its possible to restrict user access to only specific namespaces, but there doesn't appear to be anyway to get a list of namespaces that a user has permission to access.

Our main usecase here is to be able to provide in a UI a list of namespaces that a user has access to.

We do have options such as the SelfSubjectRulesReview which will allow a user to get a list of actions a user can perform in a specific namespace. Can we not have a similar command to get a list of namespaces where we have something which is accessible?

Note: I am aware this has been brought up a few times in the past. Especially with https://github.com/kubernetes/community/issues/1486 and the comment from @liggitt here seems to say its not possible https://github.com/kubernetes/community/issues/1486#issuecomment-350741039

I don't think we need something like a watchable list here (like what OpenShift does with projects) which is the main argument against this. Something similar to the SelfSubjectRulesReview where we need to post to get the data should be enough for our usecase.

**Comment by liggitt** [comment]
please open feature requests against https://github.com/kubernetes/kubernetes, not the community repo

this particular request has been made in https://github.com/kubernetes/kubernetes/issues/48537, https://github.com/kubernetes/kubernetes/issues/58262, and https://github.com/kubernetes/kubernetes/issues/61958 and the objections described there still hold

I still don't think a special acl-filtered list-only API belongs in core kubernetes, but am happy to hear dissenting opinions from sig-api-machinery/sig-auth/sig-architecture

/close
