### ISSUE TITLE
Math help 

### ISSUE THREAD

**Issue by vallard** [kubernetes/community#2948]
I'm trying to understand the [resources readme](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/resources.md) where it shows equivalent values.  There is a sentence that says:

"For example, the following represent roughly the same value: 128974848, "129e6", "129M" , "123Mi"."

Can you help me understand the `123Mi`?  I thought it would be 128974848 / 1024 = 126Mi instead of 123Mi?   I'd like to at least update the docs so its more clear if I can. 

Thanks for any clarification /sig docs

**Comment by vallard** [comment]
ah, that explains.  So slowly:
128974848 bytes = 125,952 kilobytes = 123 megabytes correct?  

Thank you!

**Comment by idealhack** [comment]
@pcarver we have `M` and `Mi`
