### ISSUE TITLE
SIG Chairs need a handbook

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#2951]
We need a guidebook for SIG Chairs and TLs. Something that lists which lists to be on, how to get access to resources they need, how to manage their existing resources, etc. This would also be a place for existing chairs to leave tips, document lifecycle/handover procedures, etc. 

I can work on this after Kubecon. 

/assign
/sig contributor-experience

**Comment by parispittman** [comment]
reverse engineer the sig-wg-lifecycle.md doc and that's everything a sig chair will need to know and be acquainted with, have access to, etc.

**Comment by mrbobbytables** [comment]
ref: https://github.com/kubernetes/community/pull/4461
Start of one is being built there^^

**Comment by markyjackson-taulia** [comment]
per @castrojo 
/close
