### ISSUE TITLE
Proposal: KEP Encrypted Container Images Support

### ISSUE THREAD

**Issue by lumjjb** [kubernetes/community#2970]
@stefanberger, @harche, @estesp and I have been working on OCI image encryption/decryption feature for containerd/kubernetes.

We have prepared a KEP for the feature. We think that it is relevant for sig-node and would like to share this with the group, and also get some feedback on the KEP - we are good to give a demo of the feature!

Here’s a link to the KEP draft (demo included): https://docs.google.com/document/d/1NjM58FZFRLtK2qh90WYnk-1nd8ili1d433d8pGwri6g/

@kubernetes/sig-node-proposals

**Comment by smarterclayton** [comment]
Please make the doc commentable by the node sig group.

**Comment by harche** [comment]
@smarterclayton sorry. Just added `kubernetes-sig-node@googlegroups.com` to that doc's ACL. Let me know if it works for you now.

**Comment by harche** [comment]
@smarterclayton let me know if the doc is commentable for you now.

**Comment by lumjjb** [comment]
@smarterclayton we have a demo that we'd like to show for this KEP if you think it'd be a good idea for us to share this at one of the sig weekly sync-ups?

**Comment by nikhita** [comment]
Going to close this since KEPs are being tracked in the enhancements repo. Feel free to reopen if needed.

/close

**Comment by harche** [comment]
@nikhita Thanks.

I have opened the new issue in the enhancements repo to track this effort. https://github.com/kubernetes/enhancements/issues/1067
