### ISSUE TITLE
Steering charter is in separate repo

### ISSUE THREAD

**Issue by tpepper** [kubernetes/community#2975]
In discussion around the placing of SIG Release's charter document (initially proposed for k/sig-release repo), there seemed to be consensus all key charters should be in k/community for common discoverability.

This is an outlier:
https://github.com/kubernetes/steering/blob/master/charter.md

Does it make sense to have that in k/community?  Should there be Committees in sigs.yaml and sig-list.md?

**Comment by nikhita** [comment]
cc @kubernetes/steering-committee
