### ISSUE TITLE
Is it required to deploy flexvolume plugin to the master for volume resizing?

### ISSUE THREAD

**Issue by sun7927** [kubernetes/community#3013]
According to the flexvolume volume resizing design, the flexvolume plugin has to be installed on master node to get ExpandVolume() call. If the plugin can't be installed on master because of some restrictions, is there any workaround or solution for it?

@xingzhou 
/sig storage

**Comment by gnufied** [comment]
No, it is not required to have flexvolume plugin installed on the master. If plugin is not installed on the master then control-plane call is basically a NOOP and resizing will be done on the node. There should be a follow up PR for updating flexvolume.md . cc @aniket-s-kulkarni

**Comment by brahmaroutu** [comment]
@gnufied Opened an issue on the community docs to update the feature information.
https://github.com/kubernetes/community/issues/3014

**Comment by sun7927** [comment]
@gnufied thanks for your reply. Is the flexvolume resizing feature ready in kubernetes 1.13 now? I didn't see it in the release notes.
