### ISSUE TITLE
Document FlexVolume resize feature

### ISSUE THREAD

**Issue by brahmaroutu** [kubernetes/community#3014]
For clarity on the feature, this feature needs to be documents as suggested in the docs PR: https://github.com/kubernetes/website/pull/10097

Please update the relevant information into the document on how to use this feature.
 https://github.com/kubernetes/community/blob/master/contributors/devel/flexvolume.md

**Comment by nikhita** [comment]
Going to add help-wanted since the website PR exists here for reference: https://github.com/kubernetes/website/pull/10097

/help
