### ISSUE TITLE
About contributing EFS CSI Driver 

### ISSUE THREAD

**Issue by khacminh** [kubernetes/community#3019]
Hi,

Currently, Kubernetes (and EKS) doesn't support EFS mounting using **amazon-efs-utils** package. The only way to connect to EFS is using NFS Persistent Volume. In this way, the advances of EFS cannot be used, such as TLS connection.

**It would be great if AWS can contribute an EFS CSI Driver for Kubernetes.**

Thanks

@kubernetes/sig-aws-feature-requests

**Comment by d-nishi** [comment]
@khacminh this is in the roadmap plan for SIG AWS
@leakingtapan and @bertinatto are on point for this.

/assign @leakingtapan @bertinatto

**Comment by cblecker** [comment]
@d-nishi is there a more appropriate repo for this? If so, I can move it over.

**Comment by d-nishi** [comment]
@cblecker - this can be moved under aws-csi-ebs-driver for now.

**Comment by cblecker** [comment]
Oh, darn. Looks like the issue transfer (which is still in beta) only works to other repos in the org.

**Comment by d-nishi** [comment]
We can close here and can ask the creator to recreate in the correct location?

**Comment by leakingtapan** [comment]
@khacminh @gregsidelinger Here is the EFS CSI Driver repo: https://github.com/aws/aws-efs-csi-driver Please create issues/feature requests there. Thx

/close
