### ISSUE TITLE
Contributor workflow etiquette doc

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#3032]
This is a follow-up to a discussion on Slack / at KubeCon. As a part of the revamped Developer Guide, there should be a short cheatsheet or "TL;DR" edition that covers common project/git etiquette. A few examples of what should be included would be the information on "[Trivial Edits](http://git.k8s.io/community/contributors/guide/pull-requests.md#10-trivial-edits)" and "[Squashing and Commit Titles](http://git.k8s.io/community/contributors/guide/pull-requests.md#6-squashing-and-commit-titles)". 

This document could then be translated and used as a starting point for new non-native english speaking contributors.

/cc @cblecker @justaugustus @parispittman 

/sig contributor-experience
/area contributor-guide

**Comment by parispittman** [comment]
Can we add to this one? https://github.com/kubernetes/community/blob/master/contributors/guide/contributor-cheatsheet.md

**Comment by mrbobbytables** [comment]
I would say so :)

**Comment by mrbobbytables** [comment]
Title has been updated to better reflect goal. 

After some quick discussion, it should be a separate doc. The intent is not to be a larger "cheatsheet" for the project, but more of a focused doc on developer/git community practices.

**Comment by parispittman** [comment]
@eduartua - can you add this need to your doc

**Comment by parispittman** [comment]
@eduartua - let's talk about this at our next 1:1. I can help you with this and we can crowdsource it. Would be a great add to the set. 

thanks for putting this to the top @cblecker

**Comment by eduartua** [comment]
Sure, I'll add it to the dev guide section.

**Comment by mrbobbytables** [comment]
closed by #3213 
/close
\o/
