### ISSUE TITLE
Moderators.md needs a travel section

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#3035]
Every single list/discuss/youtube moderator was in Kubecon Seattle. 

We were too busy to constantly check our properties, we need to document a procedure for major events so that people not attending can keep an eye on our online presence. This could simply just be a planning checklist for each event. 

/sig contributor experience
/assign

**Comment by castrojo** [comment]
Working on this here: https://github.com/kubernetes/community/pull/3212

**Comment by jberkus** [comment]
We should probably have a gcal for moderators, which is visible only to the collective moderators and admins.  Because people are going to have a lot more out-of-town/off-the-grid events than Kubecon.

**Comment by mrbobbytables** [comment]
> We should probably have a gcal for moderators, which is visible only to the collective moderators and admins. Because people are going to have a lot more out-of-town/off-the-grid events than Kubecon.

Agreed. With that though we will definitely want a uniform means of contacting the moderators. I know a "moderators@kubernetes.io" account is being pursued via the [gsuite proposal](https://groups.google.com/d/msg/kubernetes-sig-contribex/81vRGlfBLZA/DbJircVxFwAJ), but without that, the  _"who"_ to contact when will become quite a bit more fuzzy.

**Comment by nikhita** [comment]
Does Moderators Pro Tempore https://github.com/kubernetes/community/blob/master/communication/moderation.md#moderators-pro-tempore cover this?

**Comment by mrbobbytables** [comment]
I think it does..the only tidbit might be if we want to firm up scheduling/notification of when a regular admin becomes unavailable. Right now it's the general guideline of "let other mods know you'll be away". I'd say give it a go without a calendar and if something does occur we can revisit setting up a calendar or some other means of coordinating "away".

My main thought on that is it'd essentially be something else that people will have to sync and it's likely things be missed.

**Comment by castrojo** [comment]
We have way more moderators than before, I'd like to try this without a calendar first, then reopen if it becomes a problem.
