### ISSUE TITLE
Single google group or alias for all org members

### ISSUE THREAD

**Issue by dims** [kubernetes/community#3038]
At ASF, there's a `committers@apache.org` which is auto-magically maintained with a list of everyone with CLAs.

Similarly can we please have an alias/group that we can populate with all the org members of various github orgs under our aegis?

Thanks,
Dims

**Comment by cblecker** [comment]
/sig contributor-experience

This is supposed to be what k-dev is for (it's a requirement for getting membership)

**Comment by nikhita** [comment]
@dims does https://github.com/kubernetes/community/issues/3038#issuecomment-448300802 sgty? is there anything else needed to be done here?

**Comment by dims** [comment]
/close

i think we are good here.
