### ISSUE TITLE
Wrap up contributor summit 2018

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3044]
- [x] survey (2 different surveys - separate one for ncw that @jberkus completed)

- [ ] blog post

- [x] wrap up email to all attendees

- [x] picture album

- [x] youtube videos

- [ ] meet with cncf re: budget and responsibilities

**Comment by parispittman** [comment]
josh has some responses already collected from seattle, shanghai for ncw. thinks they will have some content restructuring for it next year.

**Comment by jberkus** [comment]
I need to get the Shanghai NCW survey data from the CNCF because it was on Surveymonkey.  Requested.

**Comment by chris-short** [comment]
I can do the blog post if no one is already working on it. @parispittman @jberkus @nikhita Please let me know.

**Comment by parispittman** [comment]
@chris-short happy to have you. shared the doc with you. 50% of the words on paper so happy to co-author. thank you!

**Comment by chris-short** [comment]
Well, I've done a really terrible job at this and I apologize for cookie licking.

WIP: https://docs.google.com/document/d/1_mbqanj3ZnNJ6fCObOyDQzEHKVBd9iWQqqrmuIhUz_U/edit

Can anyone help me push this over the line?

**Comment by parispittman** [comment]
@chris-short - no worries. it was refactored into a 2019 summit post and closing this issue now. https://github.com/kubernetes/website/pull/13209

/close
