### ISSUE TITLE
Ensure all repos have the CoC

### ISSUE THREAD

**Issue by nikhita** [kubernetes/community#3053]
I wrote up some quick Go code for identifying repos that don't have the `CONTRIBUTING.md` file for https://github.com/kubernetes/steering/issues/28. Used the same one for finding missing LICENSE files (https://github.com/kubernetes/steering/issues/57#issuecomment-450132738) and CoC.

The following repos don't have the file `code-of-conduct.md` at their root:

**kubernetes:**
kubernetes/website
kubernetes/klog
kubernetes/cloud-provider-sample

**kubernetes-sigs:**
kubernetes-sigs/aws-alb-ingress-controller
kubernetes-sigs/aws-iam-authenticator
kubernetes-sigs/mutating-trace-admission-controller

We should probably automate this like secping? Thoughts about how to go about this? I see two options right now:

- Create a new tool like secping in test-infra (because **sec**ping seems only for SECURITY_CONTACTS :stuck_out_tongue: )
- Extend secping to support all mandatory files as per https://github.com/kubernetes/kubernetes-template-project.

/cc @cblecker @fejta @spiffxp @BenTheElder @jessfraz 
/sig contributor-experience
/committee conduct

**Comment by nikhita** [comment]
Created PRs for all repos with missing CoC:

- https://github.com/kubernetes/website/pull/11919
- https://github.com/kubernetes/klog/pull/33
- https://github.com/kubernetes/cloud-provider-sample/pull/1
- https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/792
- https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/186
- https://github.com/kubernetes-sigs/mutating-trace-admission-controller/pull/6

All PRs are referenced above. Will report back once all have been merged.

**Comment by BenTheElder** [comment]
SGTM 👍 
No real opinions on the tool itself, whatever @jessfraz prefers regarding secping.
If we can write less new code, great! 💯  If not, it wouldn't be much more new code in test-infra 🙃

**Comment by fejta** [comment]
Using her code sgtm, but I think the tool should have a different name than secping, although it wouldn't be the end of the world if that happens.

**Comment by nikhita** [comment]
Come to think of it...I don't think we need a tool for the CoC anymore. All new repos are created by the github-mangement team and the initial commit is from https://github.com/kubernetes/kubernetes-template-project (which contains the CoC). We won't need this unless someone removes the CoC explicitly - which I don't think will happen.

Closing this. Please reopen if needed.
/close
