### ISSUE TITLE
Broken link in governance.md

### ISSUE THREAD

**Issue by Zyqsempai** [kubernetes/community#3059]
Link to `kubernetes repository guidelines` is broken in governance.md, Repository guidelines section.
I can easily fix it, but since Kubernetes incubator is deprecated now, wouldn't it be good to exchange "Repository guidelines" with "Kubernetes subprojects" description and link?

**Comment by Zyqsempai** [comment]
@calebamiles Sorry, I choose your name from owners list, what do you think about this topic??

**Comment by nikhita** [comment]
@Zyqsempai Good catch about the broken link!

> since Kubernetes incubator is deprecated now, wouldn't it be good to exchange "Repository guidelines" with "Kubernetes subprojects" description and link?

The document at the old link has been moved to https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md. The term "repository guidelines" in governance.md indicates guidelines that each repo needs to follow.

We don't really have a term "Kubernetes subprojects" -- we only have subprojects under each SIG. Each repo needs to be a subproject under a SIG. This information is already present in the [`kubernetes-repositories.md`](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md) doc.

I think the right fix here is just to update the link to point to the new location. :)

**Comment by Zyqsempai** [comment]
Ok. thanks, will open PR soon.

**Comment by cblecker** [comment]
fixed by #3060
/close
