### ISSUE TITLE
Umbrella issue - deflaking kubernetes e2e tests

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#3071]
/assign @mariantalla @jberkus @spiffxp 
/area deflake
/sig release
/sig testing

NOTE: I'm not actually sure an umbrella issue makes sense here. I'm creating one so I have something to link to from the [1.13 Retro](https://bit.ly/k8s113-retro)

>Break issues out of Deflaking notes and file them in the appropriate repos

We had a session on deflaking e2e tests at the Kubecon Seattle Contributors Summit.  We also had an impromptu meeting later at Kubecon Seattle.  I rambled a lot, let's see if we can convert into actionable issues.

Some random high level thoughts on organization:
- I added an `area/deflake` label (ref: https://github.com/kubernetes/test-infra/pull/10624) so if nothing else, you can use an [`org:kubernetes label:area/deflake` github query](https://github.com/issues?q=org%3Akubernetes+label%3Aarea%2Fdeflake+sort%3Aupdated-desc)
- Any kubernetes org member can make an org-level GitHub Project, if we feel like it'd be helpful to have a board with columns to drag issues/PR's around
- Deflaking seems like an effort that is: time-bounded, fixed-scope, cross-sig... all things that make it sound like a working group

**Comment by nikhita** [comment]
> Any kubernetes org member can make an org-level GitHub Project, if we feel like it'd be helpful to have a board with columns to drag issues/PR's around

nit: I am an org member but don't have write access and I can see the "New Project" button on https://github.com/orgs/kubernetes/projects but I can't move cards/issues/PRs in a board....so managing a board would need also need write access. :upside_down_face:

**Comment by mariantalla** [comment]
Started populating [projects/7](https://github.com/orgs/kubernetes/projects/7), please pardon the dust (and let me know for feedback! 🙏🏻) while I add more issues.

**Comment by nikhita** [comment]
@spiffxp @mariantalla @justaugustus Given that the project board is setup now, is there anything else to be done here?

> Deflaking seems like an effort that is: time-bounded, fixed-scope, cross-sig... all things that make it sound like a working group

I feel like this issue can be closed, and if deflaking needs to be a working group, we should move it to another issue. :eyes:

**Comment by markyjackson-taulia** [comment]
@spiffxp @mariantalla @justaugustus Is this still a valid issue or anything I can help with?

**Comment by jberkus** [comment]
it's always an issue.  Let's talk about it in release meeting, or better CI subproject.

**Comment by spiffxp** [comment]
/close
This is the only remaining open issue on https://github.com/orgs/kubernetes/projects/7

So I'm closing this issue and I'm closing the board.

I agree that test flakiness is always an issue.  I think it would be great if there was a (staffed) subproject or working group dedicated to addressing some of the more systemic issues we have with flakes.  But I don't think keeping this issue or the board open will substantively change that.
