### ISSUE TITLE
create more roles for contribex

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3076]
Creating more roles will help our SIG in the following ways:
- breaking down work, assigning tasks, ownership
- create opportunities for contributors
- recognition

Will discuss further on our weekly update calls with follow ups here and mailing list for discussion. Need to define scope, responsibilities, align with subprojects, and document. 

Role ideas:
- New contributor ambassador (for our SIG; not the project)
   - example: once a month office hours for slotting people directly to open issues, 15 min hangout/zoom sessions with new contributors for a quick q&a to plug them in
- Triage captain (for k/community; not the project)
   - example: apply labels like help-wanted, project board, assign people, etc. 
- Moderation Lead(s)
- Retrospective Lead (we offer retros as a service to SIGs)
- Blogger (kubernetes and other outlets)
- Social Media Lead (when we get twitter and other accounts set up)
- Explicit event roles
- APAC or EU contribex liaison that helps with mirroring programs / strategies for contributors there
- Marketing
- Other ideas?

This issue will close when we know the roles we are looking for and have SIG consensus; mostly keeping this up for contribex member thoughts. Follow up issues will reflect tasks for those.

**Comment by coderanger** [comment]
Role ideas from meeting: blogger, contrib summit related roles, marketing/outreach?

**Comment by idealhack** [comment]
also from the meeting: localization-related roles

**Comment by parispittman** [comment]
thanks for those @idealhack and @coderanger - added!

**Comment by jberkus** [comment]
Do we already have a role for Process Change Notification?  That is, if we roll out a change to merges, labels, etc., making sure that all contributors are informed and have a chance to give feedback?

**Comment by parispittman** [comment]
@jberkus i figured that could be the blogger and the marketing person

**Comment by jberkus** [comment]
Paris: not the same thing, at all.  Blogger/marketing is outward-focussed.  Process Change Notification works internally with the SIG leads, SIG-PM, SIG-Release, etc.

It's sounding like I should think about this role ...

**Comment by jonasrosland** [comment]
Regarding the Marketing role, would that then have Blogger, Event, and Social Media rolling up to them? I'm imagining a facilitator role to make sure everyone's on the same page.

**Comment by parispittman** [comment]
@jonasrosland that would be a good idea imo - marketing lead

**Comment by parispittman** [comment]
events-team has been set and housed under /events, marketing under /communication, new contrib ambassador under /sig-contributor-experience (which is also the future home of a future @nikhita PR for /issue-triage-team, captain.md, PR/Issue wrangler.md)

this issue will close when nikhita is done with the issue triage PR. we can follow up with other issues when we want to create other roles.

**Comment by parispittman** [comment]
events-team, marketing-team, and triage-team is in flight (will update with PRs)

**Comment by parispittman** [comment]
The one role I'd like to see get some attention before we close this issue is the APAC coordinator/council. We are making movements and have merged many of these and this issue can be closed soon.

**Comment by parispittman** [comment]
/close 

will open a specific issue for APAC coordinator
