### ISSUE TITLE
Umbrella issue - Project Management improvements for sig-contribex

### ISSUE THREAD

**Issue by mattj-io** [kubernetes/community#3079]
This issue will track the development of project management tooling/workflow for sig-contribex. As I understand it, we currently have a number of issues 

1. Github's kanban's are not necessarily very effective for non-code project management - no dependency tracking, lack of subtasks etc. etc. 
2. Issues in this area can be defined too broadly, making the definition of done difficult to assess
3. There is currently no resource tracking, so it's difficult to get a feel for forward progress or the velocity capabilities within a given timeframe
4. Partly due to 3, it's difficult to set manageable goals over a specific timeframe

**Comment by mattj-io** [comment]
First open question as devils advocate - why use github for non-code project management ? It doesn't have the full set of features that something like Trello or JIRA would have. Non-devils advocate, I can also see the benefit of keeping everything for the project within a single system.

**Comment by mattj-io** [comment]
Within the github ecosystem, there are a number of addons which improve the project management capabilities eg. codetree and waffle. 

Waffle ( https://waffle.io/ ) is free for open source 
Codetree ( https://codetree.com/ ) costs 💵 

Both add sizings, dependency tracking etc.

**Comment by mattj-io** [comment]
Aside from tooling, the issues I can see already are 

1. Need a definition of sizing and some way of allocating it
2. Some issues are too widely defined and need breaking down into smaller units
3. Discuss having a deliverable timeframe ( per Contributor Summit was suggested in Seattle ) and plan only for that in order to timebox work
4. How to handle dependencies other than manually noting them

**Comment by parispittman** [comment]
Wanted to document my excitedness for organization lol :) thank you @mattj-io

Will thoroughly read and respond in a few hours

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/sig-release/issues/432 for the GitHub/Airtable stuff I just mentioned in contribex meeting

**Comment by idvoretskyi** [comment]
> Within the github ecosystem, there are a number of addons which improve the project management capabilities eg. codetree and waffle.
> 
> Waffle ( https://waffle.io/ ) is free for open source
> Codetree ( https://codetree.com/ ) costs 💵

@mattj-io I made a brief review of these solutions, +1 on Waffle!

**Comment by mattj-io** [comment]
Yeah I liked waffle as well, although I imagine that has to be installed at the organisation level and I'm not sure what the complexity of getting that approved is. It may also be that we don't actually need all that feature set ..

**Comment by mattj-io** [comment]
for those who missed it, you can also see a live version of waffle at https://waffle.io/waffleio/waffle.io - big ticket features are dependency tracking, sizings, configurable swim lanes and a bunch of other cool stuff.

**Comment by idvoretskyi** [comment]
> Yeah I liked waffle as well, although I imagine that has to be installed at the organisation level and I'm not sure what the complexity of getting that approved is. It may also be that we don't actually need all that feature set ..

For some reason, Waffle is already installed for k/k, but was used a long time ago (1.2-1.3 timeframe).

**Comment by zjs** [comment]
ZenHub (https://www.zenhub.com/) may also be worth considering, and is free for public repositories. One unique (AFAIK) thing about it is that it uses an optional browser extension to overlay the additional information/functionality directly in the GItHub UI.

**Comment by BenTheElder** [comment]
IIRC zenhub is blocked in the kubernetes org due to the oauth scopes it requests from users being too broad.

**Comment by idvoretskyi** [comment]
@mattj-io any updates on this?

Are there any specific issues with the current GitHub Projects workflow that require us to move to a different tool ASAP?

**Comment by mattj-io** [comment]
Sorry folks, got caught up in real life work and haven't been able to make the weekly meetings for a couple of weeks. Judging from the responses on the mailing list thread our best option is to look at Github Projects workflows as opposed to external tooling. Next steps are : 

- Look at the current board and break down issues into smaller components
- Track dependencies through references
- Investigate sizing through labels

I'd suggest we do this as a collaborative effort in real time - and that we take a couple of issues as test items. @parispittman - the best way to do this first step might be to have a separate call outside of the weekly meeting and work through an example, once I've looked at using labels ? I can get to the label investigation today, but will be out of action for a week after that as I'm travelling to the US and have a very full calendar next week with our yearly Sales Kick Off event.

**Comment by idvoretskyi** [comment]
@mattj-io let's schedule a brief call next week (I assume you'll have more capacity). It would be great to move forward with this.

/cc @parispittman

**Comment by mattj-io** [comment]
Sounds good. I'm back in the UK from Tuesday.

**Comment by idvoretskyi** [comment]
Waffle is not an option anymore - https://blog.waffle.io/farewell-from-waffle-%EF%B8%8F-794da4a72851.

**Comment by nikhita** [comment]
:wave: Are there any updates on this? 

Btw...we've seen an increase in the number of GitHub project boards across the orgs. We also have policy around it now: https://github.com/kubernetes/community/blob/master/github-management/org-owners-guide.md#project-board-guidance.

**Comment by idvoretskyi** [comment]
I'd close in favor of https://github.com/kubernetes/community/issues/3267

**Comment by imkin** [comment]
While working on the board with @tpepper it felt that the kanban board is very limited in features. 

- It would be easier to triage the issues to the board for tracking, If the automation supported labels to sort the issues into columns. That way labeling the issues will automatically bring it to the board's attention.
- It is difficult to define "InProgress" for non-reviewable issues. Apart from labels/review-state if there was a different way to define the progress it would help. I do not yet have a suggestion on what it could be. If anyone has ideas please share.

**Comment by parispittman** [comment]
@nikhita matt is stepping away for a second to work on some other things right now so I'd close this issue in favor of #3267

**Comment by nikhita** [comment]
Ack.

/close
