### ISSUE TITLE
The Contributor Guide pull request doc conflates developer and non-developer personas

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#3087]
/area contributor-guide
/kind documentation

Summarizing a [thread in #sig-contribex](https://kubernetes.slack.com/archives/C1TU9EB9S/p1547230614247500)

We view the contributor guide as a place where all contributors - developers, writers, etc can get the same information and if anything speaks to solely the developers persona, it should go in a dev guide.

We need to edit the contributor guide PR doc:
- A lot of folks who only want to contribute to our contributing docs and end up getting stuck on the dev environment pieces that they don't need.
- Need to add disclosures / separate code/non-code concerns
- There are also significant "setting up your dev environment" steps in there that should just live elsewhere, not really in a "how to pull request" doc!

(ref: https://github.com/kubernetes/community/issues/1413 for the origin story of the contrib guide)

https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md is the doc in question, some content probably belongs in:
- https://github.com/kubernetes/community/blob/master/contributors/devel/development.md
- https://github.com/kubernetes/community/blob/master/contributors/devel/testing.md
- [etiquette](https://github.com/kubernetes/community/issues/3032)

/help
/assign @guineveresaenger @parispittman 
Please /unassign and delegate as needed

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/community/issues/3064 for the developer guide

**Comment by Sai-Adarsh** [comment]
@spiffxp Shall I work on this issue?

**Comment by guineveresaenger** [comment]
@Sai-Adarsh yes please! Happy to answer questions and help. I’m gsaenger on k8s slack. ❤️

**Comment by guineveresaenger** [comment]
Hi @Sai-Adarsh! I think the meat of the content we should put into https://github.com/kubernetes/community/blob/master/contributors/devel/development.md 
is actually in this file:
https://github.com/kubernetes/community/blob/master/contributors/guide/github-workflow.md#build

as I can't find too much actual conflation in `/guide/pull-requests.md`.
