### ISSUE TITLE
Document how to suggest improvements to devstats

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#3094]
/sig contributor-experience
/area devstats
/kind documentation
/assign @jberkus @Phillels 

ref: [thread in #sig-contribex](https://kubernetes.slack.com/archives/C1TU9EB9S/p1547481917266500)

Let's document what the path is for suggesting improvements to devstats.  Apparently one of our most prolific contributors didn't even know https://github.com/cncf/devstats was a thing

**Comment by jberkus** [comment]
Any thoughts on where this documentation should go?  The new contributor site?

**Comment by spiffxp** [comment]
IMO I would update https://github.com/kubernetes/community/tree/master/sig-contributor-experience/devstats
