### ISSUE TITLE
docs team review and automation requirements

### ISSUE THREAD

**Issue by cblecker** [kubernetes/community#3100]
I'd like to meet with the docs team to review their automation setup, and review requirements.

We want to figure out how we meet the goals of a consistent experience across the organization (things like `/approve` settings), *AND* have the review structure in place that the docs team requires.

cc: @parispittman @Phillels @nikhita @mistyhacks @jaredbhatti

**Comment by idealhack** [comment]
Can I add some notes here? I have two items related to this stared by myself on Slack. I haven't got the chances to put them on issues/PRs yet.

- Enforcement docs freeze for `k/website` repo during the release cycle. ref: https://kubernetes.slack.com/archives/CA1MMM1HU/p1543595245003200
- Customized TTL of fejta-bot jobs for `k/website` repo. ref: https://kubernetes.slack.com/archives/CA1MMM1HU/p1544749282211900

**Comment by nikhita** [comment]
/priority important-longterm

"Longterm" because Christoph is on vacation.

**Comment by nikhita** [comment]
Sort of...

/area github-management
