### ISSUE TITLE
StatefulSet resiliency to failed volumes 

### ISSUE THREAD

**Issue by sabanas** [kubernetes/community#3118]
one of the main downsides of using a StatefulSet is the lack of ability to handle failures such as failed volumes (failed EBS drive for example), which would require creating a new volume and mapping it to the PVC of the specific pod that's failing. this could be solved in theory if it was possible to scale down a specific pod in the set. 
@kubernetes/sig-apps-misc i'm curious what are your thoughts about this problem, what current workarounds exist and what future work is planned?

thanks

**Comment by nikhita** [comment]
@sabanas A good place to discuss this would be the SIG Apps ML or an issue in the main kubernetes/kubernetes repo. :)

Closing since this isn't in the scope of the community repo.
/close
