### ISSUE TITLE
Add suggestions on global .gitignore to developer guide

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/community#3127]
Ref: https://github.com/kubernetes/enhancements/pull/702#issuecomment-456191648
/cc: @PatrickLang @pohly 

/sig contributor-experience
/help
/good-first-issue

**Comment by pohly** [comment]
@nikhita a global (aka per-user) .gitignore isn't in the individual repo, so there's no risk of it getting committed accidentally.

**Comment by nikhita** [comment]
> @nikhita a global (aka per-user) .gitignore isn't in the individual repo, so there's no risk of it getting committed accidentally.

@pohly Yeah, I meant it as "it's a good thing we are going to have it in the official docs \o/". Sorry, should have been clearer. :)

**Comment by cblecker** [comment]
This can also backfire.. I've seen some weird things in folks local files. I definitely prefer the repo having firm definitions of things it doesn't want in it.

**Comment by nikhita** [comment]
> This can also backfire.. I've seen some weird things in folks local files. I definitely prefer the repo having firm definitions of things it doesn't want in it.

:eyes: Do we want this documented then? Or should we leave this to the discretion of the repo owners? (no strong opinions from me)

In any case, since the direction isn't completely clear, I will remove the help-wanted labels from this.

/remove-help

**Comment by nikhita** [comment]
> This can also backfire.. I've seen some weird things in folks local files. I definitely prefer the repo having firm definitions of things it doesn't want in it.

I think we can leave this to the discretion of the repo owners. Any objections?

**Comment by nikhita** [comment]
Going to close this in favor of discretion of the repo owners. Please reopen if needed.

/close
