### ISSUE TITLE
Survey and data deep dives for contributor site

### ISSUE THREAD

**Issue by geekygirldawn** [kubernetes/community#3129]
High level [planning doc](https://docs.google.com/document/d/1_4qnfu5kNCxfO3yjaoBO6LM9KfqxGC4HnAvVakIQM-I/edit?usp=sharing) [sig contribex permissions] - part of umbrella issue #2987.

Details to be added when we begin the analysis.

**Comment by geekygirldawn** [comment]
@parispittman I don't think that I have permissions to assign the 2 of us or update the labels, so if you or someone else could do it, that would be grand :)

**Comment by idealhack** [comment]
@geekygirldawn Thanks for this! You can do it by telling the bot:

/assign @geekygirldawn @parispittman 
/sig contributor-experience

**Comment by nikhita** [comment]
/area community-management

I guess...
/kind feature

**Comment by parispittman** [comment]
+1 to dawn's data - that came through in other questions on the contributor experience survey as well as past contributor summit surveys. 

some other bits worth noting and respective questions:

- 25% of respondents are new to oss - maybe we should list resources for these folks?
- time zone ID reflects usage in devstats - how can we highlight the groups that have meetings that are APAC and EU friendly?
- slack is the biggest place that people find news - can we have a slack feed of k-dev on the site? how can we make k-dev the canonical place to find contributor news? subproject owners heavily read k-dev. (slide 35)
- 12% of people who took the survey didn't know that community-membership.md was a thing, also lots of comments about being hard to grow into a member (when the first step is pretty easy, means we aren't doing a good job of communicating this)
- not enough time in the week and doesn't know enough were the leaders in mentoring blockers which means we need to advertise the opportunities that aren't time burdens, promote hands on learning like the playground and more support channels. 
- we should pull in good-first-issue, help-wanted, and the contributor role board from discuss and display them on the site for all repos. if you add the three versions of no in the responses (didn't know they were there, forgot, etc.)., it's almost half of the respondents. 
- top four important contribex projects: mentoring (already mentioned above with other stuff), gh management (how can we talk about that on the site?, 
- the highest trends in how to make contributing easier involved surfacing docs around dev guide, identifying good first issues and help wanted, 
- top 5 trends in doc suggestions that would be good to surface from the open ended 'how can we make contributing easier' question: Good-first-issue, dev env docs specifically development.md, review response/process/expectations, help with github notifications/tips and tricks, mentoring
- top three most important projects according to contributors: mentoring, github management, and tie between contrib summits and getting a contrib site. - we should surface some of the gh management stuff but not the whole doc - i like how current docs describe the repos that are in the org and the structure there which could be surfaced. 


slide # references in the deck; graphs - https://docs.google.com/presentation/d/1Mdbx8OthahFzA7zg4L6vQ2WjdW8a-aUxE0ZXTugB1aA/edit?usp=sharing

**Comment by parispittman** [comment]
@geekygirldawn i updated the planning doc with the discovered info filed under the personas section. looks like we have a really great first start to what's important out of the gate.
