### ISSUE TITLE
Create a recurring zoom meeting for the sig-testing kind subproject

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#3139]
ref: https://kubernetes.slack.com/archives/CEKK1KTN2/p1548192461363600

>After looking at responses from everyone @munnerz and I are planning to start at project meeting 11AM PST on Mondays, starting next week hopefully.

I'm going to take this opportunity to try setting up sig-testing meetings correctly.

/sig contributor-experience
hey look I'm finally doing the zoom stuff

/sig testing
/kind cleanup
/priority important-soon

**Comment by spiffxp** [comment]
/assign
ok, trying to setup the kind meeting real quick

**Comment by spiffxp** [comment]
Meeting settings in zoom (minus the link)
![screen shot 2019-01-28 at 9 06 35 am](https://user-images.githubusercontent.com/49258/51852952-072c3d00-22dc-11e9-89a4-6921d3e13712.png)

![screen shot 2019-01-28 at 9 05 36 am](https://user-images.githubusercontent.com/49258/51852913-f7145d80-22db-11e9-81ae-4c7b3d370a86.png)

**Comment by spiffxp** [comment]
To create the calendar invite:
- I let zoom add it to my gmail.com calendar (then removed access because I'm paranoid like that)
- I should not be trusted to own this thing so I sent an ownership change request to @BenTheElder 
- I invited [kubernetes-sig-testing@](https://groups.google.com/forum/#!forum/kubernetes-sig-testing)

**Comment by spiffxp** [comment]
/assign @BenTheElder 
to confirm ownership of this meeting now

**Comment by parispittman** [comment]
@spiffxp you should create a shared calendar and then transfer ownership of that invite to the shared calendar. add sig-testing-leads to the shared calendar with change perms and everyone will be able to edit the meeting.

Also, the waiting room is optional these days and only for hosts comfort. not required so take that as you will.

**Comment by BenTheElder** [comment]
Thanks @spiffxp, I accepted the transfer link and see edit rights on the calendar entry, I believe (?) that confirms.

**Comment by spiffxp** [comment]
@parispittman that makes sense, is this something I overlooked in the docs?

**Comment by parispittman** [comment]
@spiffxp i dont see anything in the docs that indicates turning it on although that was the previous recommendation at one point. can you point to where you saw that so I can make the change?

**Comment by BenTheElder** [comment]
[noting that we need to fix the calendar entry -- seems only I and maybe @spiffxp can see it, also the zoom meeting didn't seem to actually allow join before host :confused: ]

**Comment by parispittman** [comment]
@BenTheElder - that's because the waiting room was enabled. Needs to be one or the other.

**Comment by BenTheElder** [comment]
I believe I've just fixed the calendar entry to properly invite kubernetes-sig-testing@googlegroups.com based on all the auto-rsvp-reject emails in my inbox 😂
I think the zoom meeting still needs fixing and this needs to go in the SIGs metadata.

**Comment by spiffxp** [comment]
I disabled the waiting room, meeting worked as expected today

**Comment by spiffxp** [comment]
Just to close the loop on "did I read the docs", I saw something about the waiting room at https://git.k8s.io/community/communication/zoom-guidelines.md#moderation and assumed that was a thing I needed to enable.  The doc shared with kubernetes-sig-leads@ mentions it, but only as an "if you have it enabled"

Why this is still open: I need to actually make a sig-testing shared calendar and put the meeting there

**Comment by parispittman** [comment]
the doc is currently showing that the waiting room is what happens when you put someone on hold. we told folks to initially to enable that before we had the security under control but have since edited out those instances on all docs.

**Comment by BenTheElder** [comment]
I think this is done? :-)

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/close
Yeah this has been done for a while (I did the shared calendar thing under https://github.com/kubernetes/community/issues/3345)
