### ISSUE TITLE
Setup a kubernetes community youtube playlist for wg-k8s-infra

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#3144]
We've been uploading our wg-k8s-infra meetings to @dims' personal youtube channel, but there is AFAIK no youtube playlist for the community to find

Would like a playlist (WG k8s-infra) on kubernetes community and uploading rights for @dims and myself (similar to WG LTS and WG Apply)

/wg k8s-infra
/sig contributor-experience

**Comment by spiffxp** [comment]
We now have https://www.youtube.com/playlist?list=PL69nYSiGNLP2Ghq7VW8rFbMFoHwvORuDL&jct=CrK47n3guCIiVUh9hvrcfB2evZnGVw

/assign @dims 
I added the previously uploaded videos, but would like them to be named [following the guidelines](https://github.com/kubernetes/community/blob/master/communication/K8sYoutubeCollaboration.md)

eg: today's video is "Kubernetes WG K8s Infra 20190123"

**Comment by castrojo** [comment]
Anything left for this one? Looks like your playlist is working fine?

**Comment by dims** [comment]
/close

yes thanks @castrojo
