### ISSUE TITLE
Promote PM Group to Product Management SIG

### ISSUE THREAD

**Issue by countspongebob** [kubernetes/community#315]
Not a new proposal, has been discussed in the community and generally agreed as appropriate. I'm writing this us to formalize the discussion. Pros/cons my attempt at summarizing the discussion.

Pros: 
- PM group is no longer a "good idea", it is now integral to the functioning of the community.
- SIG guidelines around scheduling and transparency are working well, and should be adopted.

Cons:
- PM group may not need meet regularly.
     Rebuttal 1: There is plenty of ongoing work to manage.
     Rebuttal 2: It's fine to cancel meetings if there is no content. Other SIGs do this.

Proposed timing: Effective two community meetings from now, pending announcement during the upcoming meeting.

**Comment by idvoretskyi** [comment]
Mailing list discussion ref: https://groups.google.com/d/msgid/kubernetes-pm/CANhi8oAH7dwmpxu%2BR_2Zch8NqCKQxLOVMZadRc%2BjejBpGsTX6Q%40mail.gmail.com?utm_medium=email&utm_source=footer

**Comment by idvoretskyi** [comment]
At the Community meeting 2/2 we have agreed that PM group will be promoted to the SIG status.

I will draft the official proposal about this.

**Comment by countspongebob** [comment]
@idvoretskyi happy to review if you want to write something up more formally. Not sure we need much other than formal agreement as the SIG guidelines are pretty clear. You could add notes here.

**Comment by idvoretskyi** [comment]
@countspongebob Bob, just FYI - the SIG-PM has been already established (thank you for highlighting this) and the description is already at the Community repo - https://github.com/kubernetes/community/blob/master/sig-pm/README.md.

**Comment by stp-ip** [comment]
There is another iteration on the README, but as no action or discussion is needed here:
Close?!

**Comment by calebamiles** [comment]
closing this issue, let's move the discussion of when to schedule the SIG meetings to the [mailing list](https://groups.google.com/forum/#!forum/kubernetes-pm) or the Community Meeting.
