### ISSUE TITLE
Non-code contributors meeting isn't listed in sig-contributor-experience's README

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#3158]
I feel like if there's a recurring non-code contributor guide meeting with [kubernetes-sig-contribex@](https://groups.google.com/forum/#!forum/kubernetes-sig-contribex) on the invitees, either the SIG or one of its subprojects should have that info in sigs.yaml so it shows up in the SIG's README

/sig contributor-experience

**Comment by mrbobbytables** [comment]
/cc @qedrakmar

@qedrakmar has been the one spearheading  the non-code initiative. Things were put on hold around kubecon, but have started to pick back up again.

**Comment by qedrakmar** [comment]
/assign
I'll batch this with a couple other related documentation changes I need to make.
