### ISSUE TITLE
Resolve/Unify permission issues with SIG Meeting Notes in a way that is transparent.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/community#3159]
We currently have several meeting agenda google docs which *aren't open to the public*....

Since we're 100% community driven, that should be changed soon, IMO across the board so that

- all mtng agendas are publically available to anyone on the interweb, 
- the development process and any communication we note down should be 100% non-dependent on google-specific logins.  

I've made a quick list here.  

I can reach out to the individual SIGs about this over the next few days.

## Closed : Need to be made public 

- [ ] apimachinery https://docs.google.com/document/d/1x9RNaaysyO0gXHIr1y50QFbiL1x8OWnk2v3XnrdkT5Y/edit
- [ ] auth https://docs.google.com/document/d/1woLGRoONE3EBVx-wTb4pvp4CI7tmLZ6lS26VTbosLKM/
- [ ] contrib-ux https://docs.google.com/document/d/1qf-02B7EOrItQgwXFxgqZ5qjW0mtfu5qkYIF1Hl4ZLI/edit
- [ ] docs https://docs.google.com/document/d/1Ds87eRiNZeXwRBEbFr6Z7ukjbTow5RQcNZLaSvWWQsE/edit
- [ ] GCP https://docs.google.com/document/d/1mtmwZ4oVSSWhbEw8Lfzvc7ig84qxUpdK6uHyJp8rSGU/edit
- [ ] IBM cloud https://docs.google.com/document/d/1qd_LTu5GFaxUhSWTHigowHt3XwjJVf1L57kupj8lnwg/edit
- [ ] Instrumnentation https://docs.google.com/document/d/17emKiwJeqfrCsv0NZ2FtyDbenXGtTNCsDEiLbPa7x7Y/edit
- [ ] OpenStack https://docs.google.com/document/d/1iAQ3LSF_Ky6uZdFtEZPD_8i6HXeFxIeW4XtGcUJtPyU/edit?usp=sharing_eixpa_nl&ts=588b986f

## Open : No action required.

- (apps) https://docs.google.com/document/d/1LZLBGW2wRDwAfdBNHJjFfk9CFoyZPcIYGWU7R1PQ3ng/
- (arch) 
https://docs.google.com/document/d/1BlmHq5uPyBUDlppYqAAzslVbAO8hilgjqZUTaNXUhKM/edit
- (aws)
https://docs.google.com/document/d/1-i0xQidlXnFEP9fXHWkBxqySkXwJnrGJP9OGyP2_P14/edit
- (azure) https://docs.google.com/document/d/1SpxvmOgHDhnA72Z0lbhBffrfe9inQxZkU9xqlafOW9k/edit
- (bigdata) https://docs.google.com/document/d/1pnF38NF6N5eM8DlK088XUW85Vms4V2uTsGZvSp8MNIA/
- (multicluster-sig) https://docs.google.com/document/d/18mk62nOXE_MCSSnb4yJD_8UadtzJrYyJxFwbrgabHe8/
- (network) 
https://docs.google.com/document/d/1_w77-zG_Xj0zYvEMfQZTQ-wPP4kXkpGD8smVtW_qqWM/edit
- (node) 
https://docs.google.com/document/d/1_w77-zG_Xj0zYvEMfQZTQ-wPP4kXkpGD8smVtW_qqWM/edit
- (Release)https://docs.google.com/document/d/1Fu6HxXQu8wl6TwloGUEOXVzZ1rwZ72IAhglnaAMCPqA/edit
- (Scalability) https://docs.google.com/document/d/17xlpkoEbPR5M6P5VDzNx17q6-IPFxKyebEekCGYiIKM/edit
- (Testing) https://docs.google.com/document/d/1z8MQpr_jTwhmjLMUaqQyBk1EYG_Y_3D4y4YdMJ7V1Kk/edit
- UI https://docs.google.com/document/d/1PwHFvqiShLIq8ZpoXvE3dSUnOv1ts5BTtZ7aATuKd-E/edit
- VMWare & Windows
- PM https://github.com/kubernetes/community/blob/master/sig-pm/README.md
- *Storage* https://docs.google.com/document/d/1-8KEG8AjAgKznS9NFm3qWqkGyCHmvU6HVl0sk5hwoAE/edit (whoops ! Sorry @saad-ali  , fixed :))

**Comment by castrojo** [comment]
/sig contributor-experience

Thanks for working on this!

**Comment by cblecker** [comment]
/cc @parispittman @Phillels @nikhita 

Is there a reason for some being closed vs open? were we having moderation issues?

**Comment by parispittman** [comment]
@cblecker - some where probably created by googlers where we have restricted sharing perms. in those cases, they most likely shared it with their mailing list only and not k-dev. someone will need to audit this and then have them share with k-dev, too, if you can't see them.

**Comment by parispittman** [comment]
if they want it open to the public and not just k-dev, they will need to be copied and transferred over to a new owner that doesn't have permissions issues like a @gmail account. This will need to be documented, too, at the top of the document because if this person would leave, they take the doc with them.

**Comment by parispittman** [comment]
it may be worthwhile holding on this until we can get the contribex gsuite ironed out and then we can figure out team drive for centralized ownership of documents. i think we may still have "public" issues with access to that though.

**Comment by jayunit100** [comment]
How about copy/paste -> New doc ?  At least in the short term, that will solve the existing issue.

**Comment by parispittman** [comment]
we will need to find all of the dependancies where we link to our meeting notes - one of which is the meeting invites. will need to regen those, too. if we could get a checklist of what a sig lead needs to do here, that will be best. another example - only give edit rights to those in your mailing list, etc.

**Comment by parispittman** [comment]
@mrbobbytables can you add this to: https://github.com/kubernetes/community/pull/3160?

**Comment by mrbobbytables** [comment]
Updated to include a note on sharing the docs.

**Comment by liggitt** [comment]
most of the docs are intentionally shared with specific mailing lists (kubernetes-dev and the sig mailing list). most of the anonymously visible docs referenced above share zoom meeting ids, which goes against the guidelines at https://github.com/kubernetes/community/blob/master/communication/zoom-guidelines.md#setting-up-your-meeting-and-moderation

**Comment by lavalamp** [comment]
At least for api machinery, I object to describing it as "closed"; it's shared with kubernetes-announce, kubernetes-dev, and kubernetes-sig-api-machinery.

The title, which used to be viewable just by clicking on the link, has joining instructions, but it seems it's no longer visible without logging in :(

**Comment by jayunit100** [comment]
Per https://github.com/kubernetes/community/pull/3160/files#diff-3dd56b6252307b3ebd4082bdd70317a1R119 , the *view* permissions need to be modified.  

Or revert that merge.

**Comment by parispittman** [comment]
@jayunit100 - we have some zoom issues that we are addressing right now. once that is cleared up re: #2536, we will be able to fully implement those new view perm guidelines.

**Comment by jayunit100** [comment]
+1 , we can keep it open till then

**Comment by mourya007** [comment]
Agree with the point, because most of the places google mails are not easy to access. So we should have a public process for everyone.

**Comment by saad-ali** [comment]
@jayunit100 SIG Storage meeting notes ([link](https://docs.google.com/document/d/1-8KEG8AjAgKznS9NFm3qWqkGyCHmvU6HVl0sk5hwoAE/edit?usp=sharing)) are shared publicly and have always been (see attached screenshot). Can you please clarify why we are listed as `Closed : Need to be made public`?

![sig-storage-notes-access](https://user-images.githubusercontent.com/10052848/52096620-54c6d500-257c-11e9-9f80-fc9e93652e4c.png)
)

**Comment by jayunit100** [comment]
@saad-ali  your right ! Fixed, sorry, alot of links there.  no idea how that slipped into the wrong bin.

**Comment by castrojo** [comment]
I wanted to add some comments from slack:

So I think the issue here is the governance isn't explicit:
https://github.com/kubernetes/community/blob/master/sig-governance.md#sig-governance (edited) 

> - Keep up-to-date meeting notes, linked from the SIG's page in the community repo
> - Announce meeting agenda and minutes after each meeting, on their SIG mailing list
> - Record SIG meeting and make it publicly available

We only really say that the recording must be made publically available. Now, I personally would assume that that means that there's an implied task that if your meeting recording is public, then clearly your meeting notes should be.

However, you could also interpret that as "I shared it my with list, so people who care about my SIG notes already have access."

This is all a symptom of initial SIG docs being used with work gsuites with restrictive sharing, so we cheat by ACLing in a mailing list to allow anyone on the list to access the document. Because if I'm a chair I have better things to do than managing sharing gdoc requests from the entire internet. 

Perhaps a solution is perhaps "Do users have the ability to figure out how to get to your notes? Mentioned in the SIG readme, or slack channel pinned topic or something along those lines. Maybe something like "SIG Agenda Notes (link) (New users, join _this list_ to get access to our discussions") or something wordsmithed better to show that  it's a tool workaround problem, not a SIG trying to hide something from you.

I've mentioned this in a contribex mailing list post in the past, we have spent some time looking into fixing this problem but nothing quite fixes it for us, or we would end up migrating to a new tool and open a different set of problems that might be worse or make everyone have to open a new account on a new service, etc. So the mantra so far has unfortunately been stick with the bugs you know unless we for sure have something that will make it easier for everyone.

**Comment by jayunit100** [comment]
+1 for renaming the issue, thats probably a better title for it .  Thanks for helping move this along @castrojo

**Comment by parispittman** [comment]
I'm seeing the perms on contribex as anyone on the internet can find and view. What's the error that is displaying?

<img width="360" alt="screen shot 2019-02-04 at 1 32 04 am" src="https://user-images.githubusercontent.com/5912992/52200172-ddfc3700-281c-11e9-995c-87c12bb6905f.png">

**Comment by jayunit100** [comment]
> I'm seeing the perms on contribex as anyone on the internet can find and view. What's the error that is displaying?
> 
> <img alt="screen shot 2019-02-04 at 1 32 04 am" width="360" src="https://user-images.githubusercontent.com/5912992/52200172-ddfc3700-281c-11e9-995c-87c12bb6905f.png">

Hmm, looks closed to me (contrib-ux, right?) : https://docs.google.com/document/d/1qf-02B7EOrItQgwXFxgqZ5qjW0mtfu5qkYIF1Hl4ZLI/ ?

**Comment by parispittman** [comment]
Yes, that is correct. That's where I took the above screenshot - you should be able to view it.

**Comment by jayunit100** [comment]
hmmm, no it wont let me
<img width="706" alt="screen shot 2019-02-06 at 7 38 43 am" src="https://user-images.githubusercontent.com/826111/52352875-49433600-29e2-11e9-80b5-03aeadcc87d4.png">

**Comment by nikhita** [comment]
What else needs to be done here?

Do we _require_ the meeting notes to be viewable to the Public? I don't think we impose that, from https://github.com/kubernetes/community/blob/master/communication/mailing-list-guidelines.md#mailing-list-creation.
