### ISSUE TITLE
Kick off Contributor Summit Shanghai Planning

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#3177]
Current plans:

1. We will have an NCW, lead by Yang Li.
2. We will have a 1-day, 1-room current contributor summit
3. We will have doc sprints
4. We will not have an evening event (tentative, needs discussion)

Registration will be through a separate page, in order to reduce the "I registered because it's free" problem.

Current status:

* we have a volunteer docs team headed by @zacharysarah 
* we have a volunteer contrib summit team including @idealhack Puja, and Rui.  
* rooms are confirmed with Megan.
* have not begun planning meetings

**Comment by idealhack** [comment]
cc @puja108 @chenrui333 @xiangpengzhao

**Comment by chenrui333** [comment]
👍
