### ISSUE TITLE
github: audit and remove stale org members

### ISSUE THREAD

**Issue by cblecker** [kubernetes/community#3179]
We have no policy around inactivity for org members.

We should do something like:
- establish standard for what defines "inactivity" (6 months perhaps?)
- determine a way to get a report of who's inactive (devstats?)
- create a policy on how often we check for inactivity, how do we notify those contributors, and then the actual process for PRing the removal

**Comment by nikhita** [comment]
/kind documentation

Since this revolves around creating the policy first.

**Comment by nikhita** [comment]
> determine a way to get a report of who's inactive (devstats?)

One example of this for OWNERS files: https://github.com/kubernetes/kubernetes/issues/76269

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/community/issues/1808 for owners files

**Comment by nikhita** [comment]
xref https://github.com/kubernetes/org/issues/966

**Comment by BenTheElder** [comment]
Discussed again today, we seem to have a lot of these.
How do we get consensus on the standards? Sounds like @mrbobbytables already more or less has the data.

**Comment by BenTheElder** [comment]
Is there a related issue for "get SIGs to add new OWNERS"? I haven't found it yet.

**Comment by spiffxp** [comment]
/milestone v1.19
We discussed a proposal from @mrbobbytables during github-management meeting today, agreed to bring it forward to sig-contributor-experience next

**Comment by mrbobbytables** [comment]
The members have been removed, there are a few blocks on on updating owners with code freeze etc but those will be resolved soon.
With that, I think this is good enough to call done \o/

**Comment by mrbobbytables** [comment]
Going to go ahead and close it 👍  If there is any other follow up please go ahead and reopen
/close
