### ISSUE TITLE
SIG/WG Chair/TL Training pt 2

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3183]
Clean up the first version of the SIG/WG Chair/TL training that @castrojo and I did at the last contributor summit.

This issue will close when we've done:
- [ ]  a new video that's been distributed

**Comment by nikhita** [comment]
/priority important-longterm
/area community-management

I guess..
/kind feature

**Comment by parispittman** [comment]
/remove-lifecycle rotten

still needs to happen at some point

**Comment by mrbobbytables** [comment]
ref: https://github.com/kubernetes/community/pull/4461
I think that is the start of it

**Comment by parispittman** [comment]
moving to close this issue as I don't have the time to do exactly whats scoped here but we are moving towards something like this with the addition of the sig chair folder and the meetings. if others disagree and/or can work on it, feel free to reopen.

/close
