### ISSUE TITLE
WG-Kubeadm-adoption has moved to a subproject

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#3185]
This WG served it's purpose and hasn't had updated notes since October 2017.

Please follow: https://github.com/kubernetes/community/blob/master/sig-governance.md#sigwg-retirement

I think most of these don't apply since it's basically all just SIG Cluster Lifecycle at this point and has kubeadm as a subproject. We should howerver make sure we're not leaving zombie working groups in the repo. 

/assign @kubernetes/sig-cluster-lifecycle

**Comment by detiber** [comment]
+1

**Comment by timothysc** [comment]
It's a subproject for a long time now.

**Comment by timothysc** [comment]
fwiw, it's not really sunsetting.  It was restructured year+ ago but this is a leftover.

**Comment by luxas** [comment]
> It was restructured year+ ago but this is a leftover.

Agreed, we transferred it to the kubeadm Office Hours as part of the SIG as a subproject more than a year ago, but we just forgot to remove it from k/community. Thanks @castrojo let's fix it

**Comment by luxas** [comment]
> Work with SIG Contributor Experience to:

ref @kubernetes/sig-contributor-experience-feature-requests 
(don't know what exact team to tag for sunsetting...)

TODO list:

 - [x] Archive the mailing list/group
    - Not applicable, I don't remember we had one (not 100% sure though)
 - [x] Archive the leads mailing list/group
    - Not applicable, we never had one
 - [x] Archive the slack channel
    - Not applicable, we never had one
 - [x] Deactivate the group's Zoom license
    - Not applicable, we never had an own account, just used SIG Cluster Lifecycle's
 - [x] Move all appropriate github repositories to an appropriate archive or a repo outside of the Kubernetes org
    - Not applicable, we never had our own repo
 - [x] File an issue with kubernetes/org if multiple repos that need to be retired
    - Not applicable, we never had our own repo
 - [x] Coordinate with SIG Testing on the following topics (if necessary)
    - Not applicable, we never had our own repo
 - [x] Clean up and remove all GitHub teams that refer to that SIG/WG
    - Not applicable, we never had any teams
 - [ ] Migrate/Remove/Deprecate any SIG/WG labels in labels.yaml
    - TODO: `wg/kubeadm-adoption` needs to be removed
 - [ ] Ensure that the YouTube Collaboration links are removed
    - TODO: I think I was added as a collaborator, and maybe @justinsb at the time. With the new automation and stuff, should our permissions be removed or preserved?
 - [ ] Remove SIG Calendar and events from the community calendar
    - TODO: I think @justinsb sent the original invite, so he shall remove it
 - [ ] Update sigs.yaml to reflect the removal of the SIG/WG
    - TODO: Somebody's gotta do it ;)

**Comment by justinsb** [comment]
I believe I have now removed the calendar invite - let me know if anyone still has it!

**Comment by castrojo** [comment]
I've taken care of youtube, sigs.yaml and labels.yaml have a PR in flight, thanks everyone!

**Comment by luxas** [comment]
Thanks a lot @castrojo :clap:!
