### ISSUE TITLE
Ensure working groups in sigs.yaml reflect actual usage

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#3188]
Working groups are supposed to be temporary, some have moved to subprojects under a SIG or otherwise moved on. This week I've done or am doing: 

- [x] [Cluster Ops](https://github.com/kubernetes/community/issues/2031)
- [x] [Kubeadm Adoption](https://github.com/kubernetes/community/issues/3185)
- [x] App def
- [x] Container Identity

The important thing is for us to make sure that if there was an extra mailing list or other community resource used that we [follow the procedures](https://github.com/kubernetes/community/blob/master/sig-governance.md#sig-creation-and-maintenance-procedure) so we don't have open lists that can be spammed, etc. 

I'm working on this when I have the time but if you see one feel free to open an issue on it and link to this issue as an umbrella. 

/sig contributor-experience

**Comment by castrojo** [comment]
Tracking: 

- https://github.com/kubernetes/community/issues/3228
- https://github.com/kubernetes/community/issues/3227
- https://github.com/kubernetes/community/issues/3185

**Comment by castrojo** [comment]
These have been pruned from github but still need mailing list closure, so I'll keep this open until that's complete.

**Comment by nikhita** [comment]
Issue for tracking wg machine learning: https://github.com/kubernetes/community/issues/3396

**Comment by castrojo** [comment]
/close

There are a few WGs doing the transition to user groups, but that's out of scope for this issue.
