### ISSUE TITLE
SIG/WG lifecycle doesn't address archiving community repo artifacts

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#3189]
https://github.com/kubernetes/community/blob/master/sig-governance.md#sigwg-retirement needs to mention what we do with an old SIG or WG's directory in the community archive. These are moved into archive/ ... the sig-governance doc just needs to document that.

**Comment by kikisdeliveryservice** [comment]
I opened PR #3203 to close this issue 😄

**Comment by nikhita** [comment]
/remove-help

There is a PR open (thanks @kikisdeliveryservice! :))
