### ISSUE TITLE
Barcelona Contributor Summit Planning Kick Off

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3190]
Sent out the first round of invites to the team:
Mondays @ 9am PT - strategy, content, and creative
Fridays @ 1030a PT - logistics, venue, and cncf sync

This issue will close when we have:
- [x] a skeleton event page in /events
- [x] a label for area/contributor-events
- [ ] venue and date(s)/time(s) are set
- [x] sigs.yaml has been updated with the Monday (our main session) time for this subproject "events"

**Comment by parispittman** [comment]
/help

the label and the sigs.yaml entry can be a good quick PR if anyone is looking, the rest can't be filled by a quick PR

**Comment by idealhack** [comment]
Trying to make this clearer, we have the label `area/contributor-summit` (added by https://github.com/kubernetes/test-infra/pull/10901), do we want `area/contributor-events` along with it or replace it?

**Comment by parispittman** [comment]
oh good 😅 totally forgot about that. thanks @idealhack ! checking that off now.

**Comment by parispittman** [comment]
area/contributor-summit

**Comment by mrbobbytables** [comment]
Just updating, These tasks should be complete:
* a skeleton event page in /events done (#3243)
* sigs.yaml has been updated with the Monday (our main session) time for this subproject "events" (#3217)

The last issue - _"venue and date(s)/time(s) are set"_, should be soon.

**Comment by parispittman** [comment]
waiting on venue confirmation to close - hope to have that by this Friday
