### ISSUE TITLE
slack.k8s.io - down; needs a 404 page

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3198]
we took down slack.k8s.io due to an incident and needs a 404 page created. it also resides in the google owned infra that is being transferred over with wg-k8s-infra's project. thockin and that crew can put up the page once created. 

I believe Noah K (@coderanger but not a member yet) volunteered for this. Need to follow up.

**Comment by nikhita** [comment]
> @coderanger but not a member yet

Wait..what?! @coderanger if you can open an issue against k/org for the membership request, I'll happily +1 it. :)

**Comment by nikhita** [comment]
/cc @BenTheElder @spiffxp 
since you have access to slack.k8s.io

**Comment by mrbobbytables** [comment]
> @coderanger but not a member yet

Would be happy to +1 as well :)

**Comment by BenTheElder** [comment]
The DNS condig for what this points to is public in k8s.io. If we want just a 404 page we can stick that up somewhere and then point to it.

**Comment by coderanger** [comment]
Landing page has been set up by rewriting the existing deployment to use `kantrn/k8s-slackin-tmp:v1` as the image which is `FROM nginx` and some static content.

**Comment by cblecker** [comment]
Source is now here: https://github.com/kubernetes/k8s.io/tree/master/slack.k8s.io/offline
