### ISSUE TITLE
WG Application Definition needs to be retired

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#3227]
Looks like this WG hasn't had a meeting in a while, so we need to archive the resources used: 

https://github.com/kubernetes/community/blob/master/sig-governance.md#sigwg-retirement

The process for closing a SIG/WG is as follows:

- [x] Chairs agree to disband. This decision should follow the decision making process of the SIG's Charter.
- [ ] Send a email to kubernetes-dev to let people know the SIG has either closed or merged with another SIG. This will let SIG Contributor Experience know that they need to help you archive/deactivate project resources.
  - [ ] Consider sending a [closing summary](https://docs.google.com/document/d/1qZcAvuWBznR_oEaPWtwm7U4JNT91m8r9YOUvInU-src/edit#heading=h.jsw0l2t0ra8) to the list. 
- Work with SIG Contributor Experience to:
  - [x] Archive the mailing list/group
  - [x] Archive the leads mailing list/group
  - [x] Archive the slack channel
  - [x] Deactivate the group's Zoom license
  - [x] Move all appropriate github repositories to an appropriate archive or a repo outside of the Kubernetes org
    - [x] Each subproject a SIG owns must transfer ownership to a new SIG, outside the project, or be retired
    - [x] File an issue with kubernetes/org if multiple repos that need to be retired
  - Coordinate with SIG Testing on the following topics (if necessary) 
    - [x] Retire or transfer any test-infra jobs owned by the SIG
    - [x] Retire or transfer any testgrid dashboards owned by the SIG
  - [ ] Clean up and remove all GitHub teams that refer to that SIG/WG
  - [x] Migrate/Remove/Deprecate any SIG/WG labels in [labels.yaml](https://git.k8s.io/test-infra/label_sync/labels.yaml)
  - [x] Ensure that the YouTube Collaboration links are removed
- [ ] Remove SIG Calendar and events from the community calendar
- [x] Update `sigs.yaml` to reflect the removal of the SIG/WG
    - [x] Move the existing SIG directory into the [archive](/archive) in kubernetes/community

/assign @ant31 @bryanl @garethr 

I'll be working with you on these, many probably won't apply so please just check them off if they don't.

**Comment by ant31** [comment]
@castrojo yes, we already agreed to terminate it during our the last meeting. 
we wanted to do a blog post with what the wg has achieved and where the work continue (sig apps/sig cli) and announce the retirement of the WG. 
Maybe it's time to do it :)

**Comment by bgrant0607** [comment]
I followed the list archiving instructions, except I didn't send a message to the list, since no messages have been posted since last July.
https://github.com/kubernetes/community/blob/master/communication/mailing-list-guidelines.md#archive-a-mailing-list

In particulary, posting is now disabled and joining is invitation only.

**Comment by castrojo** [comment]
@ant31 Everything is pretty much set, if someone could send that summary to the list we could close this out.

**Comment by nikhita** [comment]
/lifecycle active
/milestone May

Adding the milestone because it looks like only some bits are left.

**Comment by castrojo** [comment]
/close

This is all set as the mail to the list is an optional item, also doublechecked with Ant that the lists are closed.
