### ISSUE TITLE
WG Container Identity needs to be retired

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#3228]
This group was folded back into SIG auth, retro doc is here: https://docs.google.com/document/d/1qZcAvuWBznR_oEaPWtwm7U4JNT91m8r9YOUvInU-src/edit#heading=h.jsw0l2t0ra8

We just need to close out the small details. 

- [x] Chairs agree to disband. This decision should follow the decision making process of the SIG's Charter.
- [x] Send a email to kubernetes-dev to let people know the SIG has either closed or merged with another SIG. This will let SIG Contributor Experience know that they need to help you archive/deactivate project resources.
  - [x] Consider sending a [closing summary](https://docs.google.com/document/d/1qZcAvuWBznR_oEaPWtwm7U4JNT91m8r9YOUvInU-src/edit#heading=h.jsw0l2t0ra8) to the list. 
- Work with SIG Contributor Experience to:
  - [x] Archive the mailing list/group
  - [x] Archive the leads mailing list/group
  - [x] Archive the slack channel
  - [x] Deactivate the group's Zoom license
  - [x] Move all appropriate github repositories to an appropriate archive or a repo outside of the Kubernetes org
    - [x] Each subproject a SIG owns must transfer ownership to a new SIG, outside the project, or be retired
    - [x] File an issue with kubernetes/org if multiple repos that need to be retired
  - Coordinate with SIG Testing on the following topics (if necessary) 
    - [x] Retire or transfer any test-infra jobs owned by the SIG
    - [x] Retire or transfer any testgrid dashboards owned by the SIG
  - [ ] Clean up and remove all GitHub teams that refer to that SIG/WG
  - [x] Migrate/Remove/Deprecate any SIG/WG labels in [labels.yaml](https://git.k8s.io/test-infra/label_sync/labels.yaml)
  - [x] Ensure that the YouTube Collaboration links are removed
- [ ] Remove SIG Calendar and events from the community calendar
- [x] Update `sigs.yaml` to reflect the removal of the SIG/WG
    - [x] Move the existing SIG directory into the [archive](/archive) in kubernetes/community

/assign @smarterclayton @destijl 

I'll be helping you with this, most of these won't apply to you, I've checked off the ones that are completed. 

/sig contributor-experience

**Comment by destijl** [comment]
I think we've done most/all of these already, check out the thread "Turning down container identity WG" with paris.

**Comment by castrojo** [comment]
I can finish most of these for you (started today!), but mostly I need one of you to ensure that the main google group and corresponding -leads group is set to read-only.

**Comment by castrojo** [comment]
Can you set the google group to read only?

https://groups.google.com/forum/#!forum/kubernetes-wg-container-identity

**Comment by nikhita** [comment]
/area community-management
/priority important-soon
/kind cleanup

@castrojo feel free to update the priority if that's not correct

**Comment by destijl** [comment]
I removed the checkboxes for allow post by email and by web. Hopefully that's what you wanted.

**Comment by nikhita** [comment]
/lifecycle active
/milestone May

Adding the milestone because it looks like only some bits are left.

**Comment by castrojo** [comment]
That works, thanks!
