### ISSUE TITLE
None of the links works.

### ISSUE THREAD

**Issue by RajatVaryani** [kubernetes/community#3232]
Hello everyone. I landed on a page https://github.com/kubernetes/community/tree/master/sig-contributor-experience wherein some links are mentioned at the bottom (**Github team**). None of them works. Ideally where should they be pointing to? Would like to raise PR for the same.

**Comment by nikhita** [comment]
@RajatVaryani The links will only work for members of the Kubernetes GitHub org. The line "Note that the links to display team membership will only work if you are a member of the org" in the doc essentially means that.

If you are still interested in contributing, please take a look at the issues with the label `good-first-issue`. Thanks! :)

/close
