### ISSUE TITLE
Standardize obs streaming config

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#3237]
This follow-up to a conversation with @castrojo and @jeefy.

We should standardize and check in an [OBS](https://obsproject.com/) streaming config similar to what was done for [TGIK](https://github.com/heptio/tgik/tree/master/obs-config). This will make it easier for others to step in and stream things such as office hours or meet our contributors in the event either @castrojo or @jeefy is unavailable.

/cc @castrojo @jeefy 
/sig contributor-experience

**Comment by chris-short** [comment]
Aside from copying the Settings and Profile directories and tar'ing them up somewhere the only thing I think we could do is write a doc. But, last I checked, I used the default settings.

**Comment by mrbobbytables** [comment]
IIRC @castrojo was going to add some bumpers etc for use
