### ISSUE TITLE
When will slack re-open for invites?

### ISSUE THREAD

**Issue by kyeett** [kubernetes/community#3247]
Hi!

I'm just getting started with Kubernetes and would like to join the [K8s slack](http://slack.k8s.io/), which is unavailable due to "recent attacks". Since it doesn't say for how long the invites have been unavailable, I don't know if I should expect it to never open again, or should I check back in another week.

Some information that could be useful: 
1. How long has it been down (a few days, weeks, years?)
2. In what time frame will it re-open? (if known, or guessed)

/sig contributor-experience

Sorry, don't know the proper way of adding labels here

**Comment by kyeett** [comment]
@kubernetes/sig-contributor-experience-proposal

**Comment by nikhita** [comment]
cc @parispittman @coderanger @idvoretskyi @jdumars

**Comment by JasonvanBrackel** [comment]
@kyeett In the meantime, you're welcome in the the Rancher slack. We have some great Kubernetes practitioners in the general and kubernetes channels. Many of us are in both Slack workspaces.  I'm jvb over there and in the Kubernetes slack as well.  http://slack.rancher.io/

**Comment by kyeett** [comment]
@JasonvanBrackel Thank you! I'll join.

**Comment by AndrewSav** [comment]
According to https://discuss.kubernetes.io/t/requesting-invite-to-slack/5393/3 the invites should be up "early next week".

**Comment by SeanPSnyder** [comment]
Noooooow

**Comment by kyeett** [comment]
Looking forward to it! 

I had a look at http://slack.k8s.io/ and the information with the timeline is a lot better! If someone wants to close this ticket, I'm fine with that. Otherwise I will close it once the invites are finally up :-)

**Comment by dims** [comment]
folks, watch this space https://github.com/kubernetes/community/issues/3384

**Comment by SeanPSnyder** [comment]
Oh it's open

**Comment by dims** [comment]
It's open now http://slack.k8s.io/ (please refresh your browser cache)
