### ISSUE TITLE
Update SIG PM charter

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/community#3266]
We (SIG PM) owe a new charter.
@idvoretskyi and I working on an updated one, just putting an issue up for tracking purposes.
We'll put up a PR when this is ready for review.

ref: https://github.com/kubernetes/steering/issues/31, https://github.com/kubernetes/community/pull/2068

/sig pm
/assign @idvoretskyi @justaugustus

**Comment by justaugustus** [comment]
cc: @calebamiles @jdumars

**Comment by idvoretskyi** [comment]
_Game of Milestones ^_

**Comment by justaugustus** [comment]
Obsolete with the retirement of SIG PM: https://github.com/kubernetes/community/issues/4721
/close
