### ISSUE TITLE
Discuss project grooming

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/community#3267]
In recent discussions in Steering and [SIG PM](https://youtu.be/7N2U27pTebw), I mention the possibility of having SIG PM assist with backlog grooming for project-wide groups e.g., Steering, PM, Architecture, ContribEx.

Overall, there's been positive reception so far, but I'd like to document the intent and open the floor for comments. This is something that would get added as something in-scope for the forthcoming SIG PM charter.

Some thoughts:
- Socialize the idea (happening now)
- Create a `project-board-maintainers` team - initially @jdumars and myself - https://github.com/kubernetes/org/pull/496
- Assign the `project-board-maintainers` team write permissions to the following projects:
  - Steering: https://github.com/kubernetes/steering/projects/1
  - PM
    - SIG PM: https://github.com/orgs/kubernetes/projects/14
    - KEP Implementation Tracking: https://github.com/orgs/kubernetes/projects/5
  - Architecture:
    - KEP Tracking: https://github.com/kubernetes-sigs/architecture-tracking/projects/2
    - API Reviews: https://github.com/orgs/kubernetes/projects/13 (ref: https://github.com/kubernetes/community/pull/3261#pullrequestreview-204503307)
- Expand `project-board-maintainers` team
- Onboard additional boards

Additionally, there is some chatter around [project mgmt improvements in ContribEx](https://github.com/kubernetes/community/issues/3079). We should work to consolidate that discussion under SIG PM.

/sig pm architecture contributor-experience
/committee steering

/assign @jdumars @justaugustus 
cc: @calebamiles @idvoretskyi @sarahnovotny @bgrant0607 @liggitt @cblecker

**Comment by justaugustus** [comment]
cc: @parispittman

**Comment by justaugustus** [comment]
Question for peribolos wizards (@cblecker, @fejta, @cjwagner, @spiffxp):
Is it possible to manage project board permissions with peribolos? It would be cool if this `project-managers` group was automatically added to org-level boards in the future.

**Comment by nikhita** [comment]
> Is it possible to manage project board permissions with peribolos?

No, this is not possible today.

**Comment by cblecker** [comment]
Yeah, as Nikhita said, no, this is not possible... but I think that's okay, mostly for the reason of this being "opt-in". Like, a sig should be able to say "yes, I would love sig-pm's help to maintain my board" or "no thank you, we would like to maintain our board ourselves".

The other tricky bit is for boards that are repo-scoped, rather than org-scoped. I wish all boards were just org-scoped, because we can then be explicit with granting perms.. The only way to grant perms to repo-scoped boards is to grant write access to the repo itself (which is not ideal).

**Comment by justaugustus** [comment]
> Yeah, as Nikhita said, no, this is not possible... but I think that's okay, mostly for the reason of this being "opt-in". Like, a sig should be able to say "yes, I would love sig-pm's help to maintain my board" or "no thank you, we would like to maintain our board ourselves".

SGTM. 
While we're staffing, I'd only want to sign us up for managing a few boards (Steering, SIG PM, KEP Implementation Tracking, API Reviews, KEP Tracking). Those are in-scope for what @jdumars and myself have already been doing. From there, we would probably bring a few more people on and look at helping out SIG ContribEx next.

> The other tricky bit is for boards that are repo-scoped, rather than org-scoped. I wish all boards were just org-scoped, because we can then be explicit with granting perms.. The only way to grant perms to repo-scoped boards is to grant write access to the repo itself (which is not ideal).

I'd prefer the boards we manage be org-scoped as well. In addition to being explicit about permissions, org-level boards are more discoverable than the repo-scoped ones. We can look at moving them once we lock this in.
API Reviews has already made that move (https://github.com/kubernetes-sigs/architecture-tracking/projects/3 --> https://github.com/orgs/kubernetes/projects/13), as an example.

**Comment by idvoretskyi** [comment]
@justaugustus 

Please, update the OP after the naming changes discussed here - https://github.com/kubernetes/org/pull/496#issuecomment-464932769.

**Comment by idvoretskyi** [comment]
> I'd prefer the boards we manage be org-scoped as well. In addition to being explicit about permissions, org-level boards are more discoverable than the repo-scoped ones. We can look at moving them once we lock this in.

I disagree that org-scope should be mandatory (let's agree that it's a default and preferred behaviour, but not mandatory). There may be cases, when repo-wide boards are a preferred way to go.

**Comment by justaugustus** [comment]
Not implying that we should mandate org-level boards; they're just easier from the mgmt perspective for horizontal groups. Repo-scoped boards definitely work well for work that is tightly scoped to code.

**Comment by bgrant0607** [comment]
It looks like it's now possible to access control org-level project boards? The lack of team-based ACLs is what previously drove us to create repos to contain projects, like architecture-tracking.
https://help.github.com/articles/project-board-permissions-for-an-organization/

**Comment by liggitt** [comment]
> It looks like it's now possible to access control org-level project boards? The lack of team-based ACLs is what previously drove us to create repos to contain projects, like architecture-tracking.

Yes. Examples for the API review project:

Org members can be scoped to read access:

![screen shot 2019-02-20 at 12 04 24 am](https://user-images.githubusercontent.com/980082/53067666-31b88280-34a3-11e9-905b-299ccb274c25.png)

And specific teams in the org given other levels of access:

![screen shot 2019-02-20 at 12 04 35 am](https://user-images.githubusercontent.com/980082/53067679-3f6e0800-34a3-11e9-9adb-462d8ce676ae.png)

**Comment by justaugustus** [comment]
Yep. I've noticed the defaults for the project boards are:
- visibility: private
- permission: write

I'm thinking these should be:
- visibility: public
- permission: read

Opened a separate issue for that: https://github.com/kubernetes/community/issues/3280

**Comment by bgrant0607** [comment]
Oh, right. Org-level boards also used to only be visible to org members

**Comment by mattfarina** [comment]
Regarding the KEP board, because we merge early and often the PRs for those are not a useful thing to track on a board. We need to come up with a plan (short and long term) to get these wrangled.

A possible short term plan would be to have an issue for every KEP. Each of the PRs could be associated with the issue. A label could be used to track state (e.g., `provisional`, etc).

It would be nice of all of this were automated in a custom system. That's a long term goal.

@justaugustus I'm happy to put in time to get this wrangled. If we go with a board/short term solution I'm happy to do the work to get this up and going. The long term solutions is something I'll try to get more info on in the coming week. I'm not completely up to speed on where it is.

**Comment by spiffxp** [comment]
>A possible short term plan would be to have an issue for every KEP

Sounds like the tracking issues that the release team uses.  I agree there is much that could be done to improve them, but I would start there.

**Comment by mattfarina** [comment]
@spiffxp That is a good place to start. We also need to consider the features that are not in a k8s/k8s release but are a KEP. Thanks for the reminder.

**Comment by markyjackson-taulia** [comment]
remove-lifecycle stale

**Comment by spiffxp** [comment]
/remove-committee steering
For steering, this is the bosun's responsibility

/close
All that's happened here over the last year is `/remove-lifecycle`

If we want to discuss improving the state of project board management, I would suggest opening up more granular well-scoped issues.
