### ISSUE TITLE
Create a project board for WG LTS

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/community#3268]
Spoke with @imkin on Friday and he requested a project board to track WG LTS efforts.
I've created that here: https://github.com/orgs/kubernetes/projects/15

Before handing that off to WG LTS, I'd like to see a GH team for WG LTS created, so we can give that group write access to the board.
Optionally, a `wg/lts` could also be created to make it easier to search issues.

/assign @imkin @tpepper 
/wg lts
/sig pm

**Comment by nikhita** [comment]
>  Optionally, a `wg/lts` could also be created to make it easier to search issues.

Created https://github.com/kubernetes/test-infra/pull/11487 for this. :)

**Comment by neolit123** [comment]
> https://github.com/orgs/kubernetes/projects/15
>
> Before handing that off to WG LTS, I'd like to see a GH team for WG LTS created, so we can give that group write access to the board.

erm, i already have write access to this project board.

**Comment by nikhita** [comment]
There is a wg-lts team now: https://github.com/kubernetes/org/blob/master/config/kubernetes/wg-lts/teams.yaml.

The project board has write access for all org members. @justaugustus @imkin What else needs to be done here? Do you want to restrict write access to the team and enable only read access to members?

/assign @imkin

**Comment by imkin** [comment]
Yes please restrict the write access to wg-lts team.

While working on the board with @tpepper it felt that the kanban board is very limited in features. 

- It would be easier to triage the issues to the board for tracking, If the automation supported labels to sort the issues into columns. That way labeling the issues will automatically bring it to the board's attention.
- It is difficult to define "InProgress" for non-reviewable issues. Apart from labels/review-state if there was a different way to define the progress it would help. I do not yet have a suggestion on what it could be. If anyone has ideas please share.

**Comment by nikhita** [comment]
> Yes please restrict the write access to wg-lts team.

Done.

@imkin let's discuss alternate project board tools in https://github.com/kubernetes/community/issues/3079. :)

/close
