### ISSUE TITLE
Create Event Website for Barcelona Contributor Summit

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3271]
- [ ] figure out the event site mechanism - github pages, cvent reg page, etc. 
- [ ] engage a designer with CNCF for a basic layout
- [ ] put up initial copy

this issue will close when we go live with a site

**Comment by jonasrosland** [comment]
This has also been completed, issue can be closed.

**Comment by nikhita** [comment]
> This has also been completed, issue can be closed.

\o/

/close
