### ISSUE TITLE
Create the Project Boards for Kubernetes Contributor Summits

### ISSUE THREAD

**Issue by idvoretskyi** [kubernetes/community#3272]
- [x] - Kubernetes Contributor Summit EU 2019 (Barcelona)
- [x] - Kubernetes Contributor Summit CN 2019 (Shanghai)
- [x] - Kubernetes Contributor Summit NA 2019 (San Diego)

/area contributor-summit
/sig contributor-experience
/assign @idvoretskyi

**Comment by idvoretskyi** [comment]
Done:

- Kubernetes Contributor Summit EU 2019 (Barcelona) - https://github.com/kubernetes/community/projects/4

- Kubernetes Contributor Summit CN 2019 (Shanghai) - https://github.com/kubernetes/community/projects/5

- Kubernetes Contributor Summit NA 2019 (San Diego) - https://github.com/kubernetes/community/projects/6

**Comment by cblecker** [comment]
/reopen

@idvoretskyi These should probably be org-level boards, as you can't grant access to move things around on the board without giving full write access to the repo.

**Comment by idvoretskyi** [comment]
@cblecker this initiative was discussed at the regular Contributor Summit planning meeting, where we agreed to have these boards repo-wide (no necessity to keep them org-wide).

**Comment by nikhita** [comment]
> we agreed to have these boards repo-wide (no necessity to keep them org-wide).

Who all are intended to have write access to the contributor summit project boards? My understanding is that folks who are involved in organizing need to have access to it too. In that case, it's easier to give them access to the project board if the project board is org-level. If not, we'll need to grant all of them organizers write access to the community repo (which we'd like to limit in general).

cc @parispittman

**Comment by mrbobbytables** [comment]
> In that case, it's easier to give them access to the project board if the project board is org-level. If not, we'll need to grant all of them organizers write access to the community repo (which we'd like to limit in general).

As someone who would be on the events team list, I agree. It'd be nice if GH boards had more granular access-control, but  as they do not, I think org level boards would be a better option overall.

**Comment by nikhita** [comment]
Relevant to the discussion here: I have created https://github.com/kubernetes/community/pull/3300 to document some guidelines regarding project boards. PTAL. :)

**Comment by idvoretskyi** [comment]
@nikhita I see.

@cblecker @justaugustus is it possible to migrate the project boards to org-level if needed?

**Comment by nikhita** [comment]
> is it possible to migrate the project boards to org-level if needed?

No...but you can copy the column names, description and automation settings to org-level. The cards would not be copied.

https://help.github.com/en/articles/copying-a-project-board

**Comment by idvoretskyi** [comment]
@nikhita thanks. Let's agree on our board strategy at the meeting ContribSummit today.

**Comment by idvoretskyi** [comment]
Boards recreated at the org-wide level:

EU 2019 - https://github.com/orgs/kubernetes/projects/19
CN 2019 - https://github.com/orgs/kubernetes/projects/20
NA 2019 - https://github.com/orgs/kubernetes/projects/21

/close
