### ISSUE TITLE
Create a Content Proposal for Contributor Summit Barcelona 2019

### ISSUE THREAD

**Issue by idvoretskyi** [kubernetes/community#3273]
- [ ] - Contributor Summit Barcelona 2019 Content Proposal to be drafted
- [ ] - Content Proposal to be reviewed and signed off by the Contributor Summit team
- [ ] - PR to be submitted to https://github.com/kubernetes/community/tree/master/events/2019/05-contributor-summit 

/assign @geekygirldawn

**Comment by guineveresaenger** [comment]
Made edits to the doc with a tentative outline for teaching content

Still needs approximate time slots

My suggestion is to put all the community information at the beginning and have both tracks attend together, since this is nontechnical content meant to explain how we work.

**Comment by jonasrosland** [comment]
This has been completed, issue can be closed.
