### ISSUE TITLE
Create a Contributor Summit EU 2019 blog post

### ISSUE THREAD

**Issue by idvoretskyi** [kubernetes/community#3274]
- [x] - Draft a Contributor Summit EU 2019 blog post
- [x] - The blog post draft to be reviewed
- [x] - Define the timeline for publishing 
- [x] - The blog post is published 🎉 

This issue can be closed after the Contributor Summit will be officially announced via the Kubernetes blog.

/assign @parispittman @jonasrosland 
/area contributor-summit
/sig contributor-experience

**Comment by idvoretskyi** [comment]
Submitted here - https://github.com/kubernetes/website/pull/13209

**Comment by jonasrosland** [comment]
Blog post has been published:
https://kubernetes.io/blog/2019/03/20/a-look-back-and-whats-in-store-for-kubernetes-contributor-summits/
