### ISSUE TITLE
Core Infrastructure Initiative for Kubernetes - Move to next level above "passing"

### ISSUE THREAD

**Issue by dims** [kubernetes/community#3277]
We currently have a "passing" grade for Kubernetes at https://bestpractices.coreinfrastructure.org/en/projects/569

https://github.com/coreinfrastructure/best-practices-badge has more information about the initiative. This was also presented in the CNCF TOC meeting on Feb 19th.

We should research if we can move to the "silver" [1] (and then "gold") and see what we may be missing in what we do. The best practices captured are designed to help projects produce better/secure software.

[1] https://github.com/coreinfrastructure/best-practices-badge#silver

**Comment by nikhita** [comment]
/priority important-longterm

I guess...
/kind feature

**Comment by nikhita** [comment]
cc @kubernetes/steering-committee

**Comment by philips** [comment]
My rough guess at what things we would need to do:

- [x] Use a DCO or similar
- [x] Define/document project governance
- [x] Another will have the necessary access rights if someone dies
- [x] "Bus factor" of 2 or more
- [x]  Document security requirements ([I think this covers it](https://github.com/kubernetes/community/blob/master/contributors/guide/bug-bounty.md))
- [x] Have an assurance case explaining why security requirements are met
- [x] Have a quick start guide https://kubernetes.io/docs/tutorials/kubernetes-basics/
- [ ] Follow accessibility best practices
- [x] Pick & follow coding standards (go fmt, linters, etc)
- [ ] Monitor external dependencies to detect/fix known vulnerabilities (this doesn't exist for Go really)
- [ ] Tests have 80%+ statement coverage xref https://github.com/kubernetes/test-infra/issues/5231
- [ ] Project releases for widespread use are cryptographically signed xref https://github.com/kubernetes/kubernetes/issues/70132
- [ ] Check all inputs from potentially untrusted sources for validity (using a whitelist)

**Comment by nzoueidi** [comment]
I can help with this. I will collect my researches about the enhancements that we could do to the code and let you know.

Maybe, we should fix a regularly meeting under sig-contribex in the near future where we can discuss all the possible points?

**Comment by nikhita** [comment]
This is part of "gold": https://github.com/coreinfrastructure/best-practices-badge#gold but re security review: https://www.cncf.io/blog/2019/08/06/open-sourcing-the-kubernetes-security-audit/

**Comment by nikhita** [comment]
> Maybe, we should fix a regularly meeting under sig-contribex in the near future where we can discuss all the possible points?

@nzoueidi sorry for the late response! I think this isn't limited to just contribex but spread across various repos/sigs like testing, etc. Broadly speaking, I think this would come more under steering.

**Comment by bgrant0607** [comment]
See also: https://github.com/cncf/toc/issues/196

**Comment by justaugustus** [comment]
I can start looking at some of the Release Engineering components for this post-KubeCon.

/assign
/remove-lifecycle stale
/lifecycle frozen
/sig release
/area release-eng
/milestone v1.18

**Comment by savitharaghunathan** [comment]
Follow-up updates on test coverage: @BenTheElder , @hh , @Katharine has been working on improving e2e and unit tests, and api endpoint coverage ( https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-coverage-e2e-gci-gce/1192188001996771329, https://prow.k8s.io/?job=ci-kubernetes-coverage-e2e-gci-gce)

**Comment by BenTheElder** [comment]
er, @Katharine has worked on collecting the values by setting up the above linked jobs, I've been very minimally involved.

we could always use more coverage, but at this time I don't think Katharine or I are working on that aspect :sweat_smile:
