### ISSUE TITLE
Set default org-level project board permissions

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/community#3280]
In discussing [project grooming](https://github.com/kubernetes/community/issues/3267#issuecomment-465425845), I noticed that the default visibility for org-level project boards are private and default permissions are write. Ideally, these would be `public` and ~`read`~ `write`.

![screenshot from 2019-02-20 00-44-22](https://user-images.githubusercontent.com/567897/53069121-db4e4280-34a8-11e9-8d0d-4b493a7158ab.png)

I checked on my own org and there doesn't seem to be a way to set defaults for project boards.
Is this something we can maybe enforce for each board via peribolos?

/sig pm
/area peribolos

**Comment by nikhita** [comment]
>  Is this something we can maybe enforce for each board via peribolos?

It's not possible today but I think it should be possible to add a feature for this: https://developer.github.com/v3/projects/#update-a-project.

/cc @cblecker @fejta

**Comment by nikhita** [comment]
For now, if there is consensus, we can flip the settings for all boards so that they are Public and org members have Read access.

**Comment by justaugustus** [comment]
@nikhita -- I'm in favor of that. 
Can you list the project board admins for org-level projects here so we can get their approval? I don't believe I have the rights to do that myself.

**Comment by nikhita** [comment]
The following org-level project boards are Private and have Write access for org members:

- 1.14 CI Signal - @mariantalla 
- SIG NETWORK - @bowei 

The following org-level project boards are Private and have Read access for org members:

- Kubernetes Infrastructure Team - @dims and @cblecker 

The following org-level project boards are Public and have Write access for org members:

- cncf-k8s-conformance-wg - @spiffxp + kubernetes/cncf-conformance-wg@ 
- SIG-Windows - @PatrickLang 
- Deflaking kubernetes e2e tests - @mariantalla 


Rest of the boards are Public and have Read access for org members.

**Comment by spiffxp** [comment]
I'm more of a fan of Write being the default, because it means contributors can move and add cards themselves.  Please leave as such for the cncf-k8s-conformance-wg board, and I would prefer the same for the Deflaking board.

**Comment by PatrickLang** [comment]
+1 to write being the default. We want members to be able to update the SIG-Windows board on their own as they take work items. It's good having this board in the org instead of a separate Trello because it's discoverable and doesn't require separate permissions.

**Comment by justaugustus** [comment]
@spiffxp / @PatrickLang -- Right you are; just looked over the permissions again. Let's go with visibility: public and permissions: write for the org-level boards. Will update the description.

**Comment by nikhita** [comment]
I have updated https://github.com/kubernetes/community/issues/3280#issuecomment-465492138 to list access options for all org-level project boards. IMO we should go for Public + Write as a default, but not enforce this on all boards.

For example, I don't think everyone should have write access to the API Reviews project board and this should only be scoped to the API reviewers/approvers. cc @liggitt 

IIRC this was also a reason why write access to the Contributor Experience project board was limited to only a few folks. cc @cblecker @parispittman 

@justaugustus does this sound ok to you from a PM perspective?

**Comment by liggitt** [comment]
> For example, I don't think everyone should have write access to the API Reviews project board and this should only be scoped to the API reviewers/approvers. cc @liggitt

correct, the current permissions are desired (read access for public and org members, write access for approvers/reviewers teams)

**Comment by spiffxp** [comment]
Given that people have preferences that are more or less restrictive than the proposed defaults, and we can't actually set a default, this sounds like guidelines / docs more than automated enforcement

**Comment by nikhita** [comment]
> this sounds like guidelines / docs more than automated enforcement

Created #3300

**Comment by nikhita** [comment]
I think we can close this issue once we make all org-level boards Public.

@mariantalla any objections for making the 1.14 CI Signal board public?

@bowei any objections for making the SIG Network board public?

I can flip the settings from Private to Public if this sgty.

**Comment by justaugustus** [comment]
Looks like all the boards are public now. Thanks for working on this and writing up what was discussed here, @nikhita! :)

/close

**Comment by nikhita** [comment]
SIG Network was still Private but I've flipped it to Public.
