### ISSUE TITLE
Process for requesting community surveys

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/community#3281]
Occasionally, contributors and SIGs are interested in surveying the community.
Currently, AFAIK, we don't a defined process around requesting surveys and the comms involved in the process.

A few things to consider:
- Who should have access to Survey Monkey? We need to minimize sharing the credentials as it's a single-user account.
- Should we investigate a team account? Does the demand support this (probably not, at the moment)?
- How do people request surveys?
- How long should surveys stay open for submission?
- What are the best avenues for allowing a survey to reach their target audience?
- Should we have a survey template?
- Guidance for formulating questions, including questions to avoid
- How do we allow groups to preview draft surveys?
- How do/should we share survey results with the group that requested them?

/sig pm contributor-experience
cc: @idvoretskyi @parispittman @castrojo

**Comment by parispittman** [comment]
@idvoretskyi has access to SurveyMonkey. CNCF should remain holding this. He can create the survey for you and then give you collaboration access. We link the final data from a google drive (team drive tbd as requested through a gsuite in cncf service desk yesterday) in a file like this: https://github.com/kubernetes/community/blob/master/sig-contributor-experience/contribex-survey-2018.md

**Comment by parispittman** [comment]
this is technically a team account. we requested it specifically for kubernetes from cncf.

**Comment by justaugustus** [comment]
Just to clarify for passerbys, the intention is to document the process around generating a survey and the associated administrivia. Ihor, Paris, and myself have access to the Survey Monkey account.

---
> this is technically a team account. we requested it specifically for kubernetes from cncf.

@parispittman -- We actually have an individual account and share the creds. Survey Monkey has team plans as well.

**Comment by castrojo** [comment]
/assign

I'm working on this as part of https://github.com/kubernetes/community/issues/1693 with a section on how SIGs can request survey resources. It's currently empty but when I submit the draft PR I'll circle back around for the process.

**Comment by nikhita** [comment]
Oops...
/remove-kind feature
/kind documentation

**Comment by idvoretskyi** [comment]
@justaugustus @castrojo do we plan to move on with this?

**Comment by onlydole** [comment]
I'm happy to help document and get merged if anyone has time to help denote the current process!

**Comment by mrbobbytables** [comment]
This came up recently again in #sig-contribex.
I can answer some of these questions, we just need to further document it better:
 
> Who should have access to Survey Monkey? We need to minimize sharing the credentials as it's a single-user account.
Should we investigate a team account? Does the demand support this (probably not, at the moment)?

The CNCF has a single user account. The group accounts are too expensive and it is not used enough to warrant it.

> How do people request surveys?

I think an issue template would be good. It needs to hit two groups. the upstream marketing team and when the survey is ready, a ticket should be filed with the LF (or ping @idvoretskyi) to move it over to the CNCF account for distribution.

> How long should surveys stay open for submission?

I would say TBD depending on the survey.

> What are the best avenues for allowing a survey to reach their target audience?

Probably engage with the marketing team on this one. The two personas I can think of really are contributor or user. One should be like k-dev, slack etc, and the other should be more wide-spread with discuss/twitter.

> Should we have a survey template?

Maybe for the yearly annual contributor survey, the others are pretty different.

> Guidance for formulating questions, including questions to avoid.

This I think a few best practices can be written. Avoid leading language etc.

> How do we allow groups to preview draft surveys?

This one is difficult with survey monkey =/ You can make surveys using the pro features but not publish them until its moved over to a paid account. I think a person would need to take point on it, possibly share their screen and then when ready share it with the CNCF account for larger group preview. It should be done at that point though.

> How do/should we share survey results with the group that requested them?

Dump to csv or uploaded to a google sheet. The big thing would be if email or other PII is included in the survey where access should actually be limited.

---


The best process I've found for creating surveys is for the person to create an SM account and build the survey themselves, when complete share it with the cncf account. This lets you use all the pro features for building the survey, but not having to pay the $$$.

**Comment by idvoretskyi** [comment]
> The best process I've found for creating surveys is for the person to create an SM account and build the survey themselves, when complete share it with the cncf account. This lets you use all the pro features for building the survey, but not having to pay the $$$.

This makes sense, thanks @mrbobbytables

**Comment by mrbobbytables** [comment]
/assign @jberkus 
/milestone v1.20
We should document this in our communications directory.

**Comment by jberkus** [comment]
@mrbobbytables, where on the Contributor Site structure should this live?

We will also need an kind/survey label for this repo.

**Comment by mrbobbytables** [comment]
This was completed in #5343 
Going to go ahead and close this out 👍 
/close
