### ISSUE TITLE
create project boards for all contribex subprojects

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3283]
we should have a project board for each subproject and then a main contribex one that is catching the umbrella and stuff that is left over. 

Our main one now is too busy and not easy to figure out. Breaking this down will also help with meetings and standups.

**Comment by spiffxp** [comment]
What is the board <-> subproject mapping?

I see many more subprojects here: https://github.com/kubernetes/community/tree/master/sig-contributor-experience#subprojects

...than I do boards here: https://github.com/orgs/kubernetes/projects

FWIW, it's also a bit difficult to tell which of these 19 boards belong to sig-contributor-experience. I wonder if we want to some consistency in naming

**Comment by parispittman** [comment]
for those following along the following subprojects wont have their own board unless we see increased activity and can't manage it through our weekly meetings:
k8s.io
devstats
repo-infra

everything else is done/at a wip state

/close
