### ISSUE TITLE
It would be nice if the "icons" directory included an icon for the kubernetes logo

### ISSUE THREAD

**Issue by herbrandson** [kubernetes/community#3296]
I realize there's already a logo elsewhere in the kubernetes repo, but the styling isn't quite the same as these (i.e. it's missing the white border)

**Comment by nikhita** [comment]
For reference, the main Kubernetes logo exists here: https://github.com/kubernetes/kubernetes/tree/master/logo.

> It would be nice if the "icons" directory included an icon for the kubernetes logo

This was discussed previously and it was decided to leave the main kubernetes logo in the kubernetes/kubernetes repo.

> but the styling isn't quite the same as these (i.e. it's missing the white border)

@herbrandson I'm trying to understand this better -- do you mean that the main kubernetes logo does not have the border or the icons in the `icons` directory? I can see a Kubernetes logo with a white border here - https://github.com/kubernetes/kubernetes/blob/master/logo/logo_with_border.png

/sig contributor-experience

**Comment by herbrandson** [comment]
logo_with_border.svg was exactly what I was looking for! So sorry. Not sure how I missed that :(

**Comment by nikhita** [comment]
No problem! Glad you found it. :)
