### ISSUE TITLE
REQUEST: New moderator for mrbobbytables of slack

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#3310]
### GitHub Username
@mrbobbytables 

### Property you'd like to Moderate
Slack - Happy to moderate others, but will limit this request to just slack for now.

### Username on Property Requested
mrbobbytables

### Requirements

- [x] I am a Kubernetes Org member already
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines]((https://git.k8s.io/community/communication/moderation.md))
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @parispittman 
- @coderanger
- @castrojo 

### List of qualifications for this position
- I am already a [moderator/admin](https://discuss.kubernetes.io/about) of https://discuss.kubernetes.io

**Comment by castrojo** [comment]
/lgtm

Thanks for volunteering!

**Comment by jdumars** [comment]
/lgtm

Thank you!!
