### ISSUE TITLE
REQUEST: New moderator for Katharine of slack

### ISSUE THREAD

**Issue by Katharine** [kubernetes/community#3316]
### GitHub Username
@Katharine

### Property you'd like to Moderate
Slack

### Username on Property Requested
Katharine

### Requirements

- [x] I am a Kubernetes Org member already
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines]((https://git.k8s.io/community/communication/moderation.md))
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @parispittman 
- @castrojo 

### List of qualifications for this position

- Prior moderation experience
  - Owner / primary moderator of the 12,600-member Pebble developer community Discord (formerly Slack) chat
  - channel operator on the #pebble freenode channel (now defunct)
  - Former moderator on the (old) official Second Life forums

**Comment by parispittman** [comment]
Katharine will be great

/approve
will wait for the other sponsor(s) to lgtm

**Comment by castrojo** [comment]
/lgtm

Thanks for volunteering!

**Comment by jdumars** [comment]
Thank you!!
