### ISSUE TITLE
REQUEST: New moderator for jeefy of Slack

### ISSUE THREAD

**Issue by jeefy** [kubernetes/community#3321]
### GitHub Username
@jeefy

### Property you'd like to Moderate
Slack

### Username on Property Requested
@jeefy

### Requirements

- [ x ] I am a Kubernetes Org member already
- [ x ] I have read and will abide by the policies mentioned in the [Moderation Guidelines]((https://git.k8s.io/community/communication/moderation.md))
- [ x ] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [ x ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @parispittman 
- @castrojo 

### List of qualifications for this position

- Current moderator of YouTube and Discuss

**Comment by castrojo** [comment]
/lgtm

+1 to this but I'd like to slot you as a protempore for geographical diversity reasons. As more APAC/EU people join I'd like to ensure our timezone is not overrepresented, but we can cross that bridge when we get there.
