### ISSUE TITLE
REQUEST: New moderator for idealhack of Slack

### ISSUE THREAD

**Issue by idealhack** [kubernetes/community#3329]
### GitHub Username

@idealhack 

### Property you'd like to Moderate

Slack (happy to moderate others, but this is what we are short for now)

### Username on Property Requested

@idealhack 

### Requirements

- [x] I am a Kubernetes Org member already
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @parispittman 
- @jeefy

### List of qualifications for this position

- would like to help out in CST (UTC+8)
- current moderator of [Discuss](https://discuss.kubernetes.io/badges/4/leader?username=idealhack)
- regular contributor/reviewer of sig-contribex/sig-docs

**Comment by nikhita** [comment]
Non-binding +1

**Comment by castrojo** [comment]
Ok please PR yourself into moderators.md, thanks!
