### ISSUE TITLE
REQUEST: New moderator for alejandrox1 of slack

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/community#3332]
### GitHub Username
@alejandrox1 

### Property you'd like to Moderate
slack

### Username on Property Requested
`@Jorge`

### Requirements

- [x] I am a Kubernetes Org member already
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines]((https://git.k8s.io/community/communication/moderation.md))
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @spiffxp 
- @nikhita  
- @castrojo 

### List of qualifications for this position

- I've been a Kubernetes contributor for some time and I am familiar with the code of conduct. I will do my best to help maintain a positive culture.

**Comment by nikhita** [comment]
+1 from sponsor

(I am a moderator for k-dev and steering mailing lists)

**Comment by idealhack** [comment]
Hey `@Jorge`... TIL Slack handles are case insensitive.

**Comment by nikhita** [comment]
> TIL Slack handles are case insensitive.

They are also not unique :(

**Comment by castrojo** [comment]
+1 from second sponsor. I'll toggle the proper slack bits, thanks for volunteering!
