### ISSUE TITLE
create placeholder website for barcelona contributor summit

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3341]
information to be included:
dates
venue
basic description of event activities
email sign up for more info

**Comment by nikhita** [comment]
/milestone May
/lifecycle active
/priority important-soon

Isn't this done? :thinking:

**Comment by jonasrosland** [comment]
Yup, this is completed, issue can be closed.

**Comment by nikhita** [comment]
> Yup, this is completed, issue can be closed.

/close
