### ISSUE TITLE
Marketing Kick Off - Barcelona Contributor Summit

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3343]
The following channels will get comms after blog post has been published:

- [x] kubernetes twitter [paris to coordinate with cncf]
- [x] k-dev mailing list [jonas to post]
- [ ] discuss.kubernetes.io [jonas to post]

no later than March 10th

**Comment by jonasrosland** [comment]
Posts to k-dev and Discuss were done today, to coincide with the blog post:
https://groups.google.com/forum/#!topic/kubernetes-dev/65FROCRfhOs
https://discuss.kubernetes.io/t/join-us-for-contributor-summit-in-barcelona/5565
https://discuss.kubernetes.io/t/contributor-summit-in-barcelona-is-now-open-for-registration/5563

This is now complete, issue can be closed.

**Comment by mrbobbytables** [comment]
I think this is safe to close. All comms channels have been advertises on. :)
/pony happy 
/area eu-summit
/close
