### ISSUE TITLE
REQUEST: New Moderator Pro Tempore for @DylanGraham of Slack

### ISSUE THREAD

**Issue by DylanGraham** [kubernetes/community#3344]
### GitHub Username
@DylanGraham 

### Property you'd like to Moderate
Slack (Initially)

### Username on Property Requested
@DylanGraham

### Requirements

- [x] I am a Kubernetes Org member already
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jdumars
- @nikhita 

### List of qualifications for this position
Community Meetup organiser
Launched #aus-nz-users
APAC timezone

**Comment by nikhita** [comment]
+1

More APAC mods!
/pony awesome

**Comment by jdumars** [comment]
+1 from me.

**Comment by castrojo** [comment]
Welcome, please submit a PR to add yourself into moderators.md!
