### ISSUE TITLE
SIG Testing meeting hygiene

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#3345]
Miscellaneous things I keep forgetting to do:
- ~make a shared SIG Testing calendar owned by all SIG Testing chairs~
- ~ensure all SIG Testing meetings and subproject meetings live on that calendar~
  - ~sig testing weekly~
  - ~kind~
  - ~testing-commons~
- ~ensure all SIG Testing subprojects use the same meeting template~
  - ~sig testing weekly~
  - ~kind~
  - ~testing-commons~ (close enough)
- ~ensure the weekly SIG Testing meeting uses a weekly recurring zoom meeting, and that it automatically records to the cloud~

/sig testing
/kind cleanup

/assign @spiffxp 
FYI @timothysc @stevekuznetsov @fejta 
As SIG testing chairs

**Comment by spiffxp** [comment]
/assign @timothysc 
Can you make the testing-commons meeting notes editable by (at least) kubernetes-sig-testing-leads@?

**Comment by timothysc** [comment]
done.

**Comment by spiffxp** [comment]
Created a shared calendar, with full rights given to kubernetes-sig-testing-leads@ and sc[1-3]@kubernetes.io, and event rights given to @BenTheElder

**Comment by spiffxp** [comment]
Created a "sig-testing weekly" recurring meeting in zoom:
- enable join before host
- mute participants on entry
- record to cloud automatically

**Comment by BenTheElder** [comment]
I've moved the event from my calendar to the sig-testing calendar

**Comment by spiffxp** [comment]
Removed the old kubernetes-sig-testing-weekly invite from my personal calendar, created a new "SIG Testing Weekly" one on the shared calendar (I was getting lots of bounces from the last meeting I canceled so I'm hoping this purge helps)

**Comment by spiffxp** [comment]
Updated description, testing-commons is all that remains

**Comment by spiffxp** [comment]
/close
All done yay
