### ISSUE TITLE
Create a Local Build and Test Demo for Contributor Workshop

### ISSUE THREAD

**Issue by guineveresaenger** [kubernetes/community#3346]
For Contrib Workshop edition 201, we should provide a controlled dev environment for people to try hacking on k/k locally.

Suggested Steps:

- [x] Use the build scripts from [here](https://github.com/kubernetes/kubernetes/tree/master/build#key-scripts) ~to create a container with all necessary dependencies~ to demonstrate a contribution workflow on k/k

- [x] Create a playbook for a live code runthrough ~using said container~

~- [ ] Push a Docker image to DockerHub for workshop participants to download pre-workshop~

**Comment by guineveresaenger** [comment]
UPDATE:

So, after a long and exhausting adventure with DinD and alpine, I have decided that it will serve new contributors better if we actually work through (some of) the build scripts together, as they already provide controlled build and test environments.

This does mean that everyone will have to use MacOS or Linux (I'm okay with this because that is unfortunately close to the current state of affairs, besides which using build containers in the first place is, as far as I understand it, already pretty difficult to do with Windows).

I think using the build scripts will create a realistic experience that participants can immediately use after leaving the workshop.

**Comment by guineveresaenger** [comment]
FURTHER UPDATE:

0. Contributor playground demonstration of bot commands and label gathering
1. Codebase walkthrough
2. Use the [quick start instructions](https://github.com/kubernetes/community/blob/master/contributors/devel/development.md#quick-start) to build some binaries (anticipating some local complications)
2a. Attempt using the [build scripts](https://github.com/kubernetes/kubernetes/tree/master/build#key-scripts) to do the same (anticipating some docker vm memory issues)
3. Demonstrate a k/k PR workflow using the real-world example of https://github.com/kubernetes/kubernetes/issues/68026#issuecomment-487635715
4. Participants can follow along, or find their own linter issue to practice on (anticipating needing `ok-to-test`)

Points to consider:
- how to assign a reviewer
    - use #pr-reviews on Slack
    - use `sigs.yaml` to determine which SIG to tag
- more?

**Comment by ameukam** [comment]
Use the `OWNERS` file ? :thinking:

**Comment by idvoretskyi** [comment]
@guineveresaenger can this be closed (the bulletpoints in the OP are checked)?

**Comment by parispittman** [comment]
event is over. thanks for adding this demo! 

/close
