### ISSUE TITLE
Issue match for New Contributor Workshop Participants

### ISSUE THREAD

**Issue by guineveresaenger** [kubernetes/community#3349]
For the 101 track of the NCW, we should give people a paved path toward their first contribution. We trust 201 participants to find their own things to work on, but people with less open source experience and less outgoing personalities will struggle with this. We can and should match 101 contributors with their first issue.

Because of the size of the workshop, this should be doneby grouping contributors by interest and skillset.

This will take some work.

- [ ] Create and send out with registration a questionnaire asking participants' experience level, about interest/skill in docs, golang, containers, "Dont' know" is an ok answer too

- [ ] Group people by interest (2-5 people per group?)

- [ ] Find a good first issue for each group in real k8s/* or k8s-sigs/* repos and reserve it

- [ ] Match and guide folks during the final part of the NCW. Collaborative PRs can still have a level of authorship, I believe? 

The group aspect makes this a little trickier; but I hope to avoid matching 100 people to 100 issues; that's not scalable.

Another possibility is to have a live demo of a real PR, either with someone from the audience, or by the presenter.

/sig contributor-experience
/area contributor-summit
/cc @jberkus @idealhack

**Comment by guineveresaenger** [comment]
Suggested form item to ask 101 participants:

"Please let us know from the following list of topics where you might want to start contributing. To help you choose, think about where you might have prior experience or what topics you might want to learn more about
."
- APIs/Cluster Resource Definitions/Operators
- CLI
- Docs
- Community management and governance (note: I feel release work goes here as well)
- Multicluster 
- Networking
- Testing
- Storage
- other (please elaborate):

**Comment by guineveresaenger** [comment]
@mrbobbytables  ^^

**Comment by mrbobbytables** [comment]
follow-up from slack, here is the question and options we wound up going with:

Please select from the following topics as an interest that you'd like to contribute to or learn more about as part of your contribution:

- APIs/CRDs/Operators
- CLI
- Community & Governance
- Docs
- Multicluster
- Networking
- Release
- Storage
- Testing
- UI
- Don't know
- Other:

**Comment by parispittman** [comment]
what about cluster lifecycle? thinking about the sigs that will be onsite

**Comment by guineveresaenger** [comment]
Here's a pretty easy accessible k/k issue that will provide at least some folks with something to work on immediately:
https://github.com/kubernetes/kubernetes/issues/68026
/cc @tpepper

**Comment by guineveresaenger** [comment]
SIGs are being asked to bring some good first issues to the SIG Meet-and-Greet to match with new contributors.

**Comment by guineveresaenger** [comment]
Closing this issue.

We will discuss rounding out more active SIG participation for future SIG-Meet-and-Greets to handle more onramp options to cover the "last mile" from workshop to happy new SIG member.
