### ISSUE TITLE
appointment/election process for new CoCC members

### ISSUE THREAD

**Issue by michelleN** [kubernetes/community#3353]
In August, 3 CoCC seats will complete their term as per the bootstrapping doc. The current process for electing new CoCC members is that the Steering Committee (SC) nominates and then votes on members. If we want to stick with that process then the SC will need to start the nomination process in June for 4 weeks and then vote on the candidates by the end of July, and notify/collect confirmations from the new appointments to ensure there is a successful transition on August 7th.

- Would the current CoCC like to amend that process? If so, please present a proposal to the Steering Committee so we can come to a consensus. If not, I'm happy to document this process and dig deeper on the details.
- If Steering is still handling the nomination/election/appointment of the CoCC, then we'll want to select someone on Steering to be responsible for this work to ensure it is documented and carried out properly.
- Does the CoCC feel this timeline is appropriate? If so, I'm happy to add it to the documentation. If not, we(steering + cocc) should discuss what is an appropriate timeline/schedule and come to a consensus.

cc/ @jdumars @carolynvs @parispittman @eparis @Bradamant3

**Comment by jdumars** [comment]
I am ok with the current election process. We are targeting merge of the charter well before the election, so if there are changes we need, they will appear there.

**Comment by carolynvs** [comment]
I think the current process is just fine or at least nothing so far has made us go "Ah! 🔥" 😀

**Comment by spiffxp** [comment]
/remove-lifecycle stale
This is being codified in the charter (ref: https://github.com/kubernetes/community/pull/3663), I believe this can be closed once the charter has merged

**Comment by spiffxp** [comment]
After re-reading the charter, I'm not sure it answers any of the questions posed by this issue, except terms and staggering.

**Comment by michelleN** [comment]
@spiffxp yea that's correct. let's ask @kubernetes/code-of-conduct-committee to add the selection/appointment process to their charter as a follow up item?

**Comment by michelleN** [comment]
Michelle to send out email to kubernetes-dev and community asking for nomination.
Community members can email steering-private to nominate people.

**Comment by Bradamant3** [comment]
Let's redirect this issue toward the recent request that the current CoCC document election procedures separately from the charter itself. See #3663 and comments therein.
