### ISSUE TITLE
Content Transparency for Contributor Summit Barcelona 2019

### ISSUE THREAD

**Issue by geekygirldawn** [kubernetes/community#3357]
Make the content from the contributor summit available for people who could not attend.

- [x] Video Recording: Arrange to have both NCW rooms recorded.
- [x] Transcriptions: Arrange to have transcriptions of video (inclusivity).
- [x] Video Editing: @guineveresaenger to provide details about where to make the cuts to the video team before the event for sections of each workshop.
- [x] Video Editing: Edit videos into logical chunks for easier consumption.
- [x] Uploads: Upload video, transcripts, and slides.

**Comment by geekygirldawn** [comment]
A few assumptions and questions:

- Assuming that the CNCF event team will handle video recording logistics - @debgiles is checking on this.
- For transcriptions, I've used rev.com for other Linux Foundation projects, and they handle technical language pretty well. We could use them unless we have other ideas? I assume we have budget somewhere to cover this?
- Do we have someone who can do the video editing to edit them into more consumable chunks, rather than one massive video? Would the people doing the recording automatically handle this?

**Comment by mrbobbytables** [comment]
re:video editing
At least historically - This is has been done by contribex post recording so that we may handle uploading it to the kubernetescommunity youtube channel.

**Comment by parispittman** [comment]
/close

complete - thank you @castrojo and @geekygirldawn !
