### ISSUE TITLE
SIG F2F Process for Contributor Summit Barcelona 2019

### ISSUE THREAD

**Issue by geekygirldawn** [kubernetes/community#3358]
- [x] Put together some guidelines for what we will / will not provide.
- [x] Create a form allowing SIG Chairs to request a F2F.
- [x] Send request form to SIG Chairs
- [x] Allocate space for requested F2F meetings.
- [x] Communication with additional details about F2F logistics
- [x] Move SIG F2F guidelines from Gdoc to repo. PR submitted, waiting for merge
- [x] Final reminder 1-2 weeks out to SIG Leads

**Comment by geekygirldawn** [comment]
@debgiles will we need attendees for the SIG F2F meetings to register to allow us to plan for food, space, etc.? If so, any thoughts on how we want to handle registration for these meetings?

**Comment by mrbobbytables** [comment]
@geekygirldawn Registration will cover if they are going to just the social or both the social and the contributor summit. We should be good on getting numbers for food etc without requiring additional info on the F2F meetings.

**Comment by debgiles** [comment]
Correct, as long as they indicated they're coming on Monday, I don't need exact numbers in each SIG F2F.  Most of the space is all a similar size, so everyone will receive a similar amount of space for the SIG F2Fs.  Thanks!

**Comment by geekygirldawn** [comment]
SIG F2F Details for room allocations.

Confirmed:

1. SIG UI, Half day, 5-10 people, @jeefy 
2. SIG CLI, Half day, 10-15 people, @soltysh 
3. SIG Windows, Half day, 10-15 people, @michmike 

Requested, but details unconfirmed:

4. SIG PM, TBD, 10?? people, @idvoretskyi 
5. SIG Cluster Lifecycle, TBD, 15-30?? people, @timothysc 
6. SIG Networking, TBD, 15?? people, @thockin 
7. SIG Cloud Provider, TBD, 8?? people, @andrewsykim 
8. SIG KubeBuilder, TBD, 5-10?? people, @DirectXMan12 
9. SIG Scheduling, TBD, 10-15?? people, @bsalamat & @ravisantoshgudimetla

**Comment by geekygirldawn** [comment]
/close

The reminder is going out with the SIG lead email. Note that the SIG F2F rooms will actually have projectors / beamers!
