### ISSUE TITLE
REQUEST: New moderator for lledru of slack

### ISSUE THREAD

**Issue by lledru** [kubernetes/community#3360]
### GitHub Username
@lledru 
### Property you'd like to Moderate
slack
### Username on Property Requested
@lledru 
### Requirements

- [x] I am a Kubernetes Org member already
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jdumars 
- @castrojo 

### List of qualifications for this position

- Prior moderation experience: no
- Links to public discussions showing your moderation experience (if available)
- Any other qualifications: member of Release 1.14, contrib SIG-DOC French Team ( animator on #kubernetes-docs-fr channel )

**Comment by castrojo** [comment]
+1 from me, thanks for volunteering!

**Comment by jdumars** [comment]
HUGE +1 on this!!

**Comment by castrojo** [comment]
Ok can you submit a PR yourself into moderators.md? I'll start the other process on slack, thanks!
