### ISSUE TITLE
gsuite process and guidelines

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3362]
contributor experience has a gsuite now - contributors@kubernetes.io

We need guidelines around what we use this for, why, who has access, etc. Doc will grow over time but need some initial guidance.

**Comment by nikhita** [comment]
/kind documentation
/cc @castrojo 

I don't know what's Alex's github username... @Phillels can you cc him here? Afaik he was also working on this. :)

**Comment by nikhita** [comment]
/area community-management
/priority important-soon

@parispittman do we want to target this for the current milestone?

**Comment by parispittman** [comment]
jorge filed servicedesk ticket for us to talk to google gsuite solutions architect/support folks about how we can better set this up, workflows, potential automation that would be helpful for us, etc.

**Comment by idvoretskyi** [comment]
cc @idvoretskyi

**Comment by idvoretskyi** [comment]
I'll follow up on the ServiceDesk request.

**Comment by parispittman** [comment]
/remove-lifecycle stale

this needs to get done but can't take it on myself

**Comment by savitharaghunathan** [comment]
@idvoretskyi , Hi! This is Savitha from sig-contribex-triage team and following up to see if you had a chance to get any updates from ServiceDesk team?

**Comment by idvoretskyi** [comment]
@savitharaghunathan I am the CNCF ServiceDesk team :)

I assume we have solved this, @parispittman please confirm.

**Comment by savitharaghunathan** [comment]
@idvoretskyi - Thank you for the update :)

**Comment by mrbobbytables** [comment]
/lifecycle frozen
Still ned to do this :( Just bandwidth issues.

**Comment by parispittman** [comment]
now that we have sig-k8s-infra, we can get this from them
/close
