### ISSUE TITLE
Contributor guide needs to mention the playground

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#3372]
The contributor guide should mention the playground so people can "practice" doing pull requests. 

https://github.com/kubernetes-sigs/contributor-playground/

/sig contributor-experience
/area contributor-guide
/help
/good-first-issue

**Comment by parispittman** [comment]
if the contributor could also link the playlist that would be good, too. https://www.youtube.com/playlist?list=PL69nYSiGNLP3M5X7stuD7N4r3uP2PZQUx and then this issue will close -> #2100
