### ISSUE TITLE
REQUEST: New moderator for rlenferink of Slack

### ISSUE THREAD

**Issue by rlenferink** [kubernetes/community#3373]
### GitHub Username
@rlenferink 

### Property you'd like to Moderate
Slack

### Username on Property Requested
@rlenferink

### Requirements

- [x] I am a Kubernetes Org member already
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@castrojo
@jdumars 

### List of qualifications for this position

- Prior moderation experience: Apache Celix mailing list moderation (dev@ / private@ / commits@)
- Links to public discussions showing your moderation experience (if available)
- Any other qualifications

/area community-management
/sig contributor-experience

**Comment by nikhita** [comment]
+1

**Comment by rlenferink** [comment]
Thanks @nikhita 😃

**Comment by jdumars** [comment]
+1

**Comment by castrojo** [comment]
Welcome! Please PR yourself into moderators.md and I'll follow up with you on slack, cheers!
