### ISSUE TITLE
REQUEST: New moderator for puja108 of Slack

### ISSUE THREAD

**Issue by puja108** [kubernetes/community#3377]
### GitHub Username

@puja108 

### Property you'd like to Moderate

Slack

### Username on Property Requested

@puja

### Requirements

- [x] I am a Kubernetes Org member already
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @castrojo 
- @mrbobbytables 

### List of qualifications for this position

- Used to be an IRC admin on a few IRC servers (and moderator in channels) back when IRC was still a thing; currently I'm a moderator for German and Chinese Regions of Kubernetes Discuss
- The above mentioned Discuss regions did not need much moderation, yet
- I organize (new) contributor summit on some KubeCons and do regularly Kubernetes Office Hours

**Comment by nikhita** [comment]
+1

/pony welcome

**Comment by nikhita** [comment]
@Katharine feature request for https://github.com/kubernetes/community/issues/3377#issuecomment-470885495 :stuck_out_tongue: :pray:

**Comment by idvoretskyi** [comment]
+1, welcome @puja108!

**Comment by mrbobbytables** [comment]
Big +1 from me~

/pony yay

**Comment by castrojo** [comment]
I'll ping you in slack with the details, thanks!
