### ISSUE TITLE
moderators.md requires more easy-readable per-region grouping

### ISSUE THREAD

**Issue by idvoretskyi** [kubernetes/community#3380]
Every person in [moderators.md](https://github.com/kubernetes/community/blob/master/communication/moderators.md) is active in a specific timezone, and this timezone is reflected near their name/ID.

At the same time, the timezones are barely understandable, so additional per-region grouping is likely (APAC, EMEA, NA).

/assign
/sig contributor-experience
/area community-management

**Comment by nikhita** [comment]
/kind documentation
/priority important-soon

Adding "important-soon" because we are adding lots of moderators now. Would be good to make it consistent so the newly added moderators can add their timezone in the correct format themselves.

**Comment by idvoretskyi** [comment]
This is WIP.

**Comment by mrbobbytables** [comment]
I'll get this sorted out today.

/assign

**Comment by idvoretskyi** [comment]
@mrbobbytables no need, I'm already working on this :)

https://github.com/kubernetes/community/pull/3453

**Comment by mrbobbytables** [comment]
fixed by #3453 and #3494 :)
/pony party
/close
