### ISSUE TITLE
REQUEST: New moderator for mrbobbytables of youtube/zoom/mailing list

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#3381]
### GitHub Username
@mrbobbytables

### Property you'd like to Moderate
![allthethings](https://i.imgur.com/6gpMXrg.jpg)
youtube, zoom, mailing list.
I am happy to help moderate any of the kubernetes communication channels :)

### Username on Property Requested
@mrbobbytables
can PM emails 

### Requirements

- [x] I am a Kubernetes Org member already
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @parispittman 
- @castrojo 

### List of qualifications for this position
- moderator of other community communication channels

**Comment by jeefy** [comment]
It's an old meme but it checks out.

+1

**Comment by idvoretskyi** [comment]
+1

**Comment by castrojo** [comment]
Working on this, just been busy with slack, welcome Bob!

**Comment by castrojo** [comment]
Ok PR yourself into moderators.md, we'll work out the rest in slack.
