### ISSUE TITLE
Steps needed to re-open the Slack inviter 

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#3384]
Ok we're pretty close now so I'd like to have this issue open as a source of truth: 

- [x] Ack from steering that we should try this plan
- [x] Getting 3 more moderators for EU, and 3 more moderators for APAC (minimum) 
- [x] Contact information and escalation guidelines for the existing moderators 
- [x] Faster admin access to the slack.k8s.io signing page so we can more responsively take down this page if needed
- [x] Use the regex rules for filtering out known attacker email domains
- [x] Slack /me issue is resolved

As of now we need 2 more APAC folks. Not sure if the `/me` issue is solved to our satisfaction so I'll leave it to @coderanger to gives up a thumbs up/down. Anything else we need to reopen the slack inviter?

/sig contributor-experience

**Comment by coderanger** [comment]
Yes, the `/me` issue is now fully resolved to the best of my ability to confirm.

**Comment by castrojo** [comment]
Alright, we now have enough EU and APAC moderators to unblock this. We'll try to open it up today.

**Comment by castrojo** [comment]
Ok, slack reopened, I'll send a note to k-dev.
