### ISSUE TITLE
REQUEST: New moderator for mkumatag of slack

### ISSUE THREAD

**Issue by mkumatag** [kubernetes/community#3385]
### GitHub Username
@mkumatag 

### Property you'd like to Moderate
slack

### Username on Property Requested
@mkumatag 

### Requirements

- [x] I am a Kubernetes Org member already
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @dims 
- @castrojo 

### List of qualifications for this position

- Prior moderation experience
- Links to public discussions showing your moderation experience (if available)
- Any other qualifications

**Comment by nikhita** [comment]
+1

/pong yay

**Comment by dims** [comment]
+1 from me!

**Comment by nikhita** [comment]
oops....

/pony yay

**Comment by castrojo** [comment]
Awesome, thanks for volunteering, please submit a PR adding yourself to moderators.md, and I'll follow up with you on slack.
