### ISSUE TITLE
REQUEST: New moderator for alejandrox1 of YouTube and Zoom

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/community#3387]
### GitHub Username
@alejandrox1

### Property you'd like to Moderate
Youtube and Zoom

### Username on Property Requested
alarcj137@gmail.com

### Requirements

- [x] I am a Kubernetes Org member already
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @nikhita 
- @castrojo 

### List of qualifications for this position

I'm already a Slack moderator and would love to help out wherever possible in YouTube and Zoom

Adding this to cheer up any readers:
/joke

**Comment by castrojo** [comment]
+1 from this, when you get the next +1 please PR yourself into the right places in moderators.md, thanks!

**Comment by nikhita** [comment]
+1 :tada:
