### ISSUE TITLE
/community site redesign final steps/questions

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3388]
- [x] need a new masthead image. the one currently showing is all googlers.
- [x] need another take at the 'about us' on the top
- [ ] need a process/instructions on how to add events 
- [x] review the video process (how do we get the most updated videos from the playlist to show?)
- [x] is the twitter stream catching kubernetes as a hashtag and/or other things? a: kubernetesio@

https://deploy-preview-13046--kubernetes-io-master-staging.netlify.com/community/

**Comment by zacharysarah** [comment]
@parispittman 👋 Here's a quick guide to community content in k/website:

What | Where
---|---
Content on k8s.io/community | https://github.com/kubernetes/website/tree/master/content/en/community
Masthead images/layout for k8s.io/community | https://github.com/kubernetes/website/tree/master/layouts/community

**Comment by parispittman** [comment]
hey @zacharysarah i should have filed the issue against the website repo and not here. ill move it there. once we pic a new image, we'll file it to the masthead section (thanks for that). working with alex to get this wrapped up and present at an upcoming sig-docs meeting.

**Comment by chris-short** [comment]
@parispittman Can you send/share the original photo from Contributor Summit?

**Comment by chris-short** [comment]
New masthead image?
https://drive.google.com/open?id=1FDfY2c_Hy61xvv2gfk2oKwLiQim7O1cu

**Comment by parispittman** [comment]
@chris-short i think that would be good for the contributor site

**Comment by mrbobbytables** [comment]
Here are a few other masthead suggestions from previous KubeCons:
- https://www.flickr.com/photos/143247548@N03/44541989060/in/album-72157704599428714/
- https://www.flickr.com/photos/143247548@N03/45581565324/in/album-72157704599428714/
- https://www.flickr.com/photos/143247548@N03/31365927607/in/album-72157704599428714/
- https://www.flickr.com/photos/143247548@N03/44488379080/in/album-72157704599428714/
  - I like this one
- https://www.flickr.com/photos/143247548@N03/46304815101/in/album-72157704599428714/
  - and this one (because "keep cloud native caffeinated")
- https://www.flickr.com/photos/143247548@N03/41235598734/in/album-72157696369579365/
- https://www.flickr.com/photos/143247548@N03/41952800451/in/album-72157696369579365/
- https://www.flickr.com/photos/143247548@N03/28082564468/in/album-72157696369579365/
- https://www.flickr.com/photos/143247548@N03/44082932550/in/album-72157675636279468/

**Comment by mrbobbytables** [comment]
Just as a quick follow-up. I think if we have the masthead picture updated and the about-us updated we could push to make it live. The only caveat would be related to the twitter feed. It supports [profiles, likes, lists, collections or moments](https://help.twitter.com/en/using-twitter/embed-twitter-feed). We could attach it to [kubernetesio](https://twitter.com/kubernetesio), [kubecon_](https://twitter.com/kubecon_), not sure about the third...[cloudnativefdn](https://twitter.com/CloudNativeFdn)? If we do start using one a contributor twitter account could also embed that.

**Comment by parispittman** [comment]
@mrbobbytables sorry i haven't updated this issue - alex @ cncf found a welcome image from a past kubecon and we also updated the about us text. she is going to give us a new preview with this info. 

as for twitter, i would agree to kubernetesio and kubecon_. need to check with alex on the rest of the items.

**Comment by mrbobbytables** [comment]
Awesome! Could also just use those 2 twitter accounts for now and change the alignment so they're a bit more equally spread.

**Comment by mrbobbytables** [comment]
Following up the discussion in slack. There is a slight issue at large window sizes where the text in boxes for discuss, twitter, github and stackoverflow will go outside the box or be misaligned (the stackoverflow text). I wouldn't call it a show-stopper, but something that should be looked into eventually.
![Screen Shot 2019-04-15 at 9 24 06 AM](https://user-images.githubusercontent.com/6500863/56173859-8c5eee00-5fbd-11e9-96ac-ffc55837d2c7.png)

**Comment by mrbobbytables** [comment]
PR for the page is here:
https://github.com/kubernetes/website/pull/13046

**Comment by parispittman** [comment]
we are rounding the corner here. need formatting changes that are located in the PR bob pointed to. 

we also need to figure out a process/access to the community calendar for people to add events.

**Comment by cblecker** [comment]
/remove-help
The scope of work here isn't clear for a newcomer.

**Comment by parispittman** [comment]
I'm closing this issue as we are now live and have some smaller issues set related in the website repo. kubernetes.io/community

I'll also set an issue regarding the process for adding events to the community calendar. 

/close
