### ISSUE TITLE
REQUEST: New moderator for @anguslees of slack

### ISSUE THREAD

**Issue by anguslees** [kubernetes/community#3393]
### GitHub Username
@anguslees 

### Property you'd like to Moderate
slack

### Username on Property Requested
guslees 

### Requirements

- [x] I am a Kubernetes Org member already
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [ ] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

(This issue is my request for sponsorship.  Feel free to accept/reject as you feel appropriate)
- @dims 
- ?

### List of qualifications for this position

- Prior moderation experience

I have no prior moderation experience (that I can recall) :)
I am/was a list owner of several email lists over the years, but none that required active/formal moderation. (It was in the days before we invented trolls)

- Any other qualifications

I am in APAC :)

I would much prefer a Pro Tempore role, since I'm sure my employer would much prefer I did not commit large blocks of ongoing time to moderation.  Happy to help out wherever I can, however.

**Comment by dims** [comment]
@anguslees i'd be happy to sponsor you for this!

**Comment by parispittman** [comment]
@anguslees - happy to sponsor you too, thanks for stepping up!

**Comment by castrojo** [comment]
Thanks Gus! Please PR yourself into moderators.md, I'll follow up with you on slack.
