### ISSUE TITLE
REQUEST: New moderator for pontiyaraja of k8s-slack

### ISSUE THREAD

**Issue by pontiyaraja** [kubernetes/community#3394]
### GitHub Username
@pontiyaraja 

### Property you'd like to Moderate
k8s-slack

### Username on Property Requested
@Pandiya

### Requirements

- [x] I am a Kubernetes Org member already
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @dims 
- @nikhita 

### List of qualifications for this position

- Prior moderation experience
- Links to public discussions showing your moderation experience (if available)
- Any other qualifications

**Comment by nikhita** [comment]
+1

@pontiyaraja would be a slack admin in the APAC timezone (India).

**Comment by dims** [comment]
+1 thanks!

**Comment by castrojo** [comment]
Thanks for volunteering, please PR yourself into moderators.md, I'll follow up with you on slack!
