### ISSUE TITLE
retire wg-machine-learning

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#3396]
This WG hasn't met since last September, any one have any more information? From looking at the notes it was active about a year ago. 

https://docs.google.com/document/d/1t2zTAehIEu3Xy8VJ6dc_cgODO4WGN-FDwpAfBjYCKc4/edit#

**Comment by SeanPSnyder** [comment]
Let me out of here or die a horrible death

**Comment by nikhita** [comment]
/cc @vishh @kow3ns @balajismaniam @ConnorDoyle 
wg-machine-learning organizers

**Comment by nikhita** [comment]
/kind cleanup

cc @kubernetes/steering-committee

**Comment by balajismaniam** [comment]
We have been on a hiatus due to dearth of topics. We had a meeting today. One of the topics we discussed was to change the ML WG meeting to monthly one. I'm not sure what it entails to be a user group. If there is less interest from participants in the working group, we can look into transitioning the WG to a user group. WDYT?

**Comment by marpaia** [comment]
If folks are open to it, I would be interested in participating in the ML WG's leadership and helping refocus a little bit. For the first time in a while, I won't be on the Release Team and I've been doing a lot of Machine Learning at work lately so this feels like an exciting intersection of interests for me.

Specifically, I think some concrete goals for the WG could be expanding the website documentation with answers to common questions about training and serving models with Kubernetes, both from the perspective of the cluster operator and the data scientist. References, happy paths, and comparisons between popular ecosystem tools might be helpful as well. I also think working with SIG Node to document GPU interactions and the configuration required might be useful for a certain demographic of ML engineer.

I'm really just spitballing here; K8s is already quite popular for training and serving. If this group continues on, I think we would be most impactful making sure the whole experience is well documented and well advertised.

**Comment by bgrant0607** [comment]
If the group is not operating, I suggest discontinuing it. We're in the process of archiving inactive groups.

@marpaia Thanks for offering to help, but I don't think any type of official advice about other software should be offered on kubernetes.io. One simple reason is that in the past we've been unable to keep such documentation up to date (e.g., to ensure that any tutorials still worked). But I'd also like to avoid what happened with the CNCF landscape, where all projects and products wanted to be mentioned. Coming up with acceptance criteria and curating such documentation could easily become a full-time job. Offhand, I'm not sure what other places to suggest, though.

More general documentation would be fine and appreciated.

**Comment by bhack** [comment]
What is the status?

**Comment by vishh** [comment]
+1 on discontinuing the group as there isn't critical momentum yet to improve k8s itself for the purpose of ML/data science. There are other communities like Spark & Kubeflow that are attempting to build around k8s which have sufficient momentum.

**Comment by ConnorDoyle** [comment]
+1 to disband. The group hasn’t met regularly for lack of interest / topics.

**Comment by spiffxp** [comment]
/assign @ConnorDoyle @vishh 
Thanks for helping us reduce our wg sprawl!

https://github.com/kubernetes/community/blob/master/sig-wg-lifecycle.md#retirement says your first step is

>Send an email to kubernetes-dev@googlegroups.com and community@kubernetes.io alerting the community of your intentions to disband or merge.

and folks can help you with the rest of the steps from there

**Comment by k82cn** [comment]
Sorry to have more comments at the last minutes :)

If we retire this WG only because of topics, I'd like to collect the requirements and be committed to pulling content together bi-weekly or monthly.

Some items in my pipeline:

1. work with kubeflow/common for `SchedulingPolicy`, a scheduler CRD for ML workload ([kf/common#46](https://github.com/kubeflow/common/issues/46))
1. GPU topology from kubeflow-cn forum
1. CSI for local cache to speed up training
1. GPU share + fair-sharing scheduling for inference workload
1. ...

**Comment by nikhita** [comment]
FYI it was mentioned in the Community Meeting on [October 3](https://docs.google.com/document/d/1VQDIAB0OqiSjIHI8AWMvSdceWhnz56jNpZrLs6o7NJY/edit#heading=h.mt6ckbh4j4u0) that WG Machine Learning will be sunset soon.

**Comment by bhack** [comment]
Check also https://github.com/kubeflow/community/issues/89

**Comment by nikhita** [comment]
xref https://github.com/kubernetes/community/pull/4287

/remove-lifecycle stale

**Comment by spiffxp** [comment]
Per @nikhita's comment, it looks like the group isn't retiring but instead rotating leadership

/remove-committee steering
I'm taking this off of our radar as the WG is taking care of this

**Comment by mrbobbytables** [comment]
They have changed leadership 👍 
@k82cn has been effectively leading it and there is now sign off from previous chairs. in https://github.com/kubernetes/community/pull/4287

With that I'm going to go ahead and close :) If there is an issue, please feel free to reopen.

/close
