### ISSUE TITLE
REQUEST: New moderator for Rajakavitha1 of  slack

### ISSUE THREAD

**Issue by Rajakavitha1** [kubernetes/community#3401]
### GitHub Username
 @Rajakavitha1 

### Property you'd like to Moderate
slack

### Username on Property Requested
@Rajakavitha1 

### Requirements

- [x] I am a Kubernetes Org member already
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @nikhita 
- @dims 

### List of qualifications for this position

- Prior moderation experience
- Links to public discussions showing your moderation experience (if available)
- Any other qualifications

**Comment by Rajakavitha1** [comment]
I would like to moderate the slack channels for India.

**Comment by Rajakavitha1** [comment]
I would like to be a moderator for the Slack India channels

**Comment by nikhita** [comment]
+1

@Rajakavitha1 is awesome!!

**Comment by dims** [comment]
+1 from me!

**Comment by castrojo** [comment]
Welcome! Please PR yourself into moderators.md and I'll follow up with you on slack.
