### ISSUE TITLE
REQUEST: New moderator for munnerz of slack

### ISSUE THREAD

**Issue by munnerz** [kubernetes/community#3407]
### GitHub Username
e.g. @munnerz

### Property you'd like to Moderate
e.g. Slack

### Username on Property Requested
e.g. U0EC03FTN (munnerz)

### Requirements

- [x] I am a Kubernetes Org member already
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @castrojo 
- @parispittman 

### List of qualifications for this position

- Run & moderate the [cert-manager](https://github.com/jetstack/cert-manager) project, incl. #cert-manager Slack channel.
- Help run the [sigs.k8s.io/kind](https://github.com/kubernetes-sigs/kind) project
- Attend regular Kubernetes meetings and familiar with the CoC
- Run various community forums in the past

**Comment by castrojo** [comment]
+1 from me!

**Comment by nikhita** [comment]
Of course yes :)

**Comment by nikhita** [comment]
> e.g. U0EC03FTN (munnerz)

<3 for listing the slack ID

**Comment by munnerz** [comment]
> <3 for listing the slack ID

I definitely have feelings about Slack's "nobody needs usernames" blog post 🙄

**Comment by castrojo** [comment]
Welcome, please PR yourself into moderators.md and then I'll follow up with you on slack.
