### ISSUE TITLE
REQUEST: New moderator for chris-short of Zoom/Slack/YouTube

### ISSUE THREAD

**Issue by chris-short** [kubernetes/community#3410]
### GitHub Username
[chris-short](https://github.com/chris-short/)

### Property you'd like to Moderate
Zoom, Slack, and YouTube. To be honest, I can do anything but email. I declare Inbox Bankruptcy too often to properly manage e-mail.

### Username on Property Requested

Zoom: chris@chrisshort.net
YouTube: chris@chrisshort.net 
Slack: chris@chrisshort.net (ChrisShort)

### Requirements

- [X] I am a Kubernetes Org member already
- [X] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [X] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application ([sorry, not sorry](https://kubernetes.slack.com/archives/C1TU9EB9S/p1552415959283900))

### Sponsors

- @parispittman 
- @castrojo 

### List of qualifications for this position

- Prior moderation experience: A cat herder of many Ansible properties/accounts, moderated multiple k8s community meetings/bofs/etc, and I even moderated before Y2K (see [Microsoft Chat](https://en.wikipedia.org/wiki/Microsoft_Comic_Chat)) 🎤💧(can probably come up with more if needed)
- Links to public discussions showing your moderation experience (if available): https://docs.google.com/document/d/1VQDIAB0OqiSjIHI8AWMvSdceWhnz56jNpZrLs6o7NJY/edit
- Any other qualifications: Previous Meetup organizer/co-organizer, DevOpsDays volunteer, etc.

**Comment by nikhita** [comment]
That's a weird yes...

/pony lgtm

**Comment by nikhita** [comment]
Oops, looks like you are not a @kubernetes org member yet. Can you apply for membership [here](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E)? Happy to +1 you! :)

**Comment by mrbobbytables** [comment]
I'd +1 your org membership request too :D

/pony yay

**Comment by mrbobbytables** [comment]
hm...less yay than intended. Will go for party...

/pony party

**Comment by chris-short** [comment]
Pending https://github.com/kubernetes/org/issues/627

**Comment by castrojo** [comment]
+1 for zoom and youtube -- for slack I'd like to queue you up and rotate you in in the summer/fall so we can get a rotation going.

**Comment by chris-short** [comment]
I'm good with that. What's next?

**Comment by chris-short** [comment]
Good to go with YouTube
Figuring out Zoom bits
Rotating into Slack later this year.
