### ISSUE TITLE
REQUEST: New moderator for aditya-konarde of slack

### ISSUE THREAD

**Issue by aditya-konarde** [kubernetes/community#3411]
### GitHub Username
@aditya-konarde 

### Property you'd like to Moderate
Kubernetes Slack

### Username on Property Requested
aditya

### Requirements

- [x] I am a Kubernetes Org member already
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@nikhita 
@dims 

### List of qualifications for this position

- Prior moderation experience
- Links to public discussions showing your moderation experience (if available)
- Any other qualifications
I'm in IST, and want to help with slack moderation :)

**Comment by nikhita** [comment]
+1 from me!

Aditya has offered to help with moderation for APAC (Indian timezone)

**Comment by castrojo** [comment]
+1 thanks for volunteering, please PR yourself into moderators.md and we'll take it from there!
