### ISSUE TITLE
Add #pr-reviews slack channel to contributor guide

### ISSUE THREAD

**Issue by dims** [kubernetes/community#3417]
There is a `#reviews` on gophers slack that is pretty popular. Could we try to set up one too?

We can promote peer-to-peer reviewing and help figure out which SIGs need to sign off, help people find reviewers and approvers. will especially help newbies i think.

WDYT?

**Comment by nikhita** [comment]
+1

If the volume for the channel becomes low (which I doubt will happen), we can always collapse into #kubernetes-dev, so I don't see any harm in having this. :+1: 

As a side note: we should also document this in our contributor guide, etc.

**Comment by nikhita** [comment]
(let's close this once we add the channel in the relevant docs)

**Comment by munnerz** [comment]
Channel created as #pr-reviews 😄

**Comment by nikhita** [comment]
I've updated the issue title to reflect that the task now includes documenting the channel.

/good-first-issue

**Comment by nzoueidi** [comment]
Well, I can help with adding the slack channel to the contributor guide.
