### ISSUE TITLE
REQUEST: New moderator for JoelSpeed of Slack

### ISSUE THREAD

**Issue by JoelSpeed** [kubernetes/community#3420]
### GitHub Username
@JoelSpeed

### Property you'd like to Moderate
Slack

### Username on Property Requested
joelspeed (U9D0X16M8)

### Requirements

- [x] I am a Kubernetes Org member already (Waiting on https://github.com/kubernetes/org/issues/596)
- [x] I have enabled 2FA on my account for the property I would like to moderate (if applicable).
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @castrojo 
- @munnerz 

### List of qualifications for this position

- Run and moderate open source projects such as [pusher/oauth2_proxy](github.com/pusher/oauth2_proxy) and [dexidp/dex](github.com/dexidp/dex)
- Office hours panelist

**Comment by munnerz** [comment]
+1! Joel helps out all over the place already, and is also in GMT 😄

**Comment by nikhita** [comment]
@JoelSpeed feel free to create a PR to add yourself to https://github.com/kubernetes/community/blob/master/communication/moderators.md#slack
