### ISSUE TITLE
How to manage signups for my corporation? 

### ISSUE THREAD

**Issue by GodloveD** [kubernetes/community#3432]
I've signed up to become a corporate representative [here](https://github.com/kubernetes/community/blob/master/CLA.md#the-contributor-license-agreement).  Now, how do I add members of my organization to become contributors?

**Comment by GodloveD** [comment]
@kubernetes/sig-contributor-experience

**Comment by mrbobbytables** [comment]
@GodloveD If you've configured it for your organization - any member who wishes to contribute will just need to have their corporate email account associated as an address with their github account and then go through the CLA process with that email address.

/sig contributor-experience

**Comment by GodloveD** [comment]
Rock and roll.  Thanks @mrbobbytables!  I'll verify that a member of Sylabs is able to go through that process and then I'll close this issue.

**Comment by mrbobbytables** [comment]
Great! If you do have any problems, the LF helpdesk will be the best group to contact. They can be reached here: `helpdesk@rt.linuxfoundation.org`

**Comment by mrbobbytables** [comment]
verified with vendor, they're all set! 👍 
/close

**Comment by GodloveD** [comment]
This worked like a charm.  Thank you.
