### ISSUE TITLE
Build San Diego Contributor Summit Team

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3445]
We'll need to fill the following core roles + shadows to get the ball rolling on strategy and venue selections. Core team will decide on subteam roles (ie - marketing lead will determine if a writer is needed) based on the direction of the event. 

[Event Team Folder](https://github.com/kubernetes/community/tree/master/events/events-team)

Self nominations from current and past contributor summit staff for the first week for lead roles. Shadows do not need to have Kubernetes event experience but should be ok with taking a lead role within the next 12 months of events.  (Inspired by the Release Team)

| Role | Volunteer Name | Shadow Name | Notes |
| --- | --- | --- | --- |
| Event Lead | Paris | Jeff |  |
| Project Manager | Jamie |  himanshu | |
| Registration Lead | Bob | Nabarun | |
| Marketing Lead | Jonas |  claimed by someone in the comments that I need to reconcile :) | there will be many roles here to open post initial planning stages |
| CNCF Events Manager | Deb Giles | n/a | CNCF/LF employee |
| Overall Content Lead | Josh | Yang | there will be many roles here to open post initial planning stages |
| New Contributor Workshop Lead | Guin |  Rael and/or Allison | dawn foster to lead the sig meet and greet |
| Accessibility, Inclusiveness, and Diversity | Jamie |  Arnaud | |

This event will close when we have scheduled our first core team meeting.

**Comment by JamieRachel** [comment]
Hi Paris, 
I would like to volunteer for the roles project manager and accessibility, inclusiveness, and diversity for KubeCon NA. Can't wait for a great event :)

**Comment by guineveresaenger** [comment]
@alisondy expressed interest in helping with the contributor workshop,
also I think @raelga has experience and would be awesome as a shadow!

**Comment by alisondy** [comment]
I would be keen with volunteering for contributor workshop ✨ thanks for pinging me @guineveresaenger

**Comment by jeefy** [comment]
I volunteer to shadow Lead. :)

**Comment by jberkus** [comment]
I'm good with overall content lead.

**Comment by idealhack** [comment]
I'm interested in shadowing Overall Content :)

**Comment by coderanger** [comment]
I might nominate myself for siteops again even though it's not on the list, since I will probably end up doing it anyway :)

**Comment by coderanger** [comment]
Also we should probably not have anyone taking on more than one role if possible, each one is pretty time consuming.

**Comment by chris-short** [comment]
Sign me up, please.

Chris Short
Web <https://chrisshort.net/> | Newsletter <https://devopsish.com/> |
Twitter <https://twitter.com/ChrisShort>

**Comment by ameukam** [comment]
I'm interested in the _Accessibility, Inclusiveness, and Diversity_ shadow role. :-)

**Comment by palnabarun** [comment]
Hello everyone,

Is there a document where the role responsibilities are written down? Also, is it possible for someone to shadow a role if the person is uncertain about attending KubeCon NA?

Thanks

**Comment by krmayankk** [comment]
i am interested in helping with new contributor workshop @parispittman

**Comment by parispittman** [comment]
@palnabarun we are building that live as we speak. check out what we have so far here -> https://github.com/kubernetes/community/tree/master/events/events-team

**Comment by palnabarun** [comment]
Thank you @parispittman for pointing out the document.

**Comment by palnabarun** [comment]
I would love to be a shadow for the Project Manager or Registration Lead. Both roles are really interesting.

**Comment by parispittman** [comment]
awesome @palnabarun - can you DM me on slack with your best email and I'll add you to the meeting poll?

**Comment by hpandeycodeit** [comment]
Is Project Manager shadow role still open or Overall Content Lead?

**Comment by tariq1890** [comment]
Interested in volunteering at the Contributor Workshop.

**Comment by tashimi** [comment]
Hey - I'm happy to help, including shadow the project lead if that is helpful, or future roles that open up.

**Comment by nzoueidi** [comment]
@parispittman feel free to put my name in any available spot. I will be there :)

**Comment by qedrakmar** [comment]
Count me in!  "Team Noah", FTW?

**Comment by irabinovitch** [comment]
Looks like all the roles are full, but would be happy to lend a hand where ever it is needed.

**Comment by parispittman** [comment]
Thanks everyone!! Love the demand to help out with this event - it's my favorite of the year. :) 

The core team is going to meet over the next few weeks and start to plan out workstreams which will open up some other roles and contribution points. We will use this issue to get more contributors and also make a shout on k-dev mailing list. 🚀

**Comment by parispittman** [comment]
core team meetings on mondays @ 10am unless otherwise noted. we will update sigs.yaml with the details and invite more folks along the ride with us as roles open up. watch this issue- #3177 for more kick off details.

closing this issue but will reach out to all of those who offered to volunteer as we go. reach out to us in #summit-staff on slack if you need anything.

/close

**Comment by arnaudmz** [comment]
Hi I'm not sure why my name appeared in the volunteer list. I don't think I did volunteer.
Can you remove me from the list?

**Comment by parispittman** [comment]
hi @arnaudmz sorry - wrong arnaud!! :D I meant for @ ameukam
