### ISSUE TITLE
REQUEST: New Slack channel: #cluster-addons

### ISSUE THREAD

**Issue by dholbach** [kubernetes/community#3446]
**GitHub Username:** @dholbach
**Slack Username:** dholbach
**What Type of Request is it (Channel, Bot, Token, or Webhook)?** Channel
**Name of Requested Resource:** `#cluster-addons`
**Description of Request:**

In the SIG Cluster-Lifecycle meeting of 12th March it was decided to create a subproject to drive the specification and implementation of the https://github.com/kubernetes/enhancements/pull/746.

The naming of the subproject (and Slack channel) was discussed in `#sig-cluster-lifecycle` [here](https://kubernetes.slack.com/archives/C13J86Z63/p1552667179275500).

As I offered to help with the logistics, I'm asking for the Slack channel to be set up. Lead of the subproject is going to be @justinsb.

CCing @luxas and @timothysc so they're aware.

**Comment by mrbobbytables** [comment]
+1

**Comment by lledru** [comment]
+1

**Comment by mrbobbytables** [comment]
Channel has been created. :)

/close
