### ISSUE TITLE
BCN summit: determine day of ops staffing 

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3451]
- [x] determine how many and what staffing needs we will have for the event (ops, TAs for workshops, etc.)
- [x] recruit and send out communications

issue will close when all needs are filled

**Comment by jonasrosland** [comment]
Adding our wonderful workshop assistants to the issue for tracking:
@ameukam 
@jeefy 
@bartsmykla 
@rosti 
@smourapina 
@kmova
@raelga 

Thank you so much for volunteering!
/cc @guineveresaenger @tpepper

**Comment by idvoretskyi** [comment]
@jonasrosland can this be closed?

**Comment by guineveresaenger** [comment]
@jonasrosland can you add full names to the "Workshop Facilitators" slide?

Then we can close it (unless other staffing needs must be addressed here)

**Comment by jonasrosland** [comment]
We'll have the all-hands call on Thursday, I think it's fair to close it by then as all comms have been sent out then.
