### ISSUE TITLE
Nuke 'triage' labels / replace them with 'lifecycle' or other 

### ISSUE THREAD

**Issue by nikopen** [kubernetes/community#3455]
Triage labels are a bit old and unused. Following discussions on https://groups.google.com/forum/#!topic/kubernetes-sig-contribex/BvGmOQ0v5f0 , the proposal is to instantiate a new workflow roughly defined at the discussion above and here kubernetes/test-infra#11818 (comment) - introduce a new label that allows SIGs to sort new issues and filter valid ones / label them / organize upcoming work in an approximately scheduled way.

As a first step, the proposal is to nuke and reclaim 'triage' labels so they are not confusing anyone.

Further idea for a replacement is to use the 'lifecycle' labels, which can be reworked and actively used more.

Roughly:

1. Auto-label 'lifecycle/active' (which means 'in progress') when someone is assigned into an issue.
2. 'lifecycle/stale' automatically kicks in in 90 days currently - might be useful to have something milder for 30 days, only when 'lifecycle/active' is already there
3. 'lifecycle/active' gets removed when issue is closed.
4. Perhaps rename 'lifecycle/active' to 'lifecycle/inprogress' to be more clear
5. Absorb any 'triage' labels that can be useful into 'lifecycle'.
    Current triage labels from the (outdated) https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#closing-issues:
```
    triage/support: Indicates an issues is not a bug but a support request.
    triage/duplicate: Indicates an issue is a duplicate of other open issue.
    triage/not-reproducible: Indicates an issue can not be reproduced as described.
    triage/needs-information: Indicates an issue needs more information in order to work on it.
    triage/unresolved: Indicates an issue that can not be resolved.
```
/sig release pm contribex
/milestone v1.15

**Comment by nikhita** [comment]
I think this still needs discussion + communicating with lazy consensus after any changes have been made. We definitely won't get this in for the current milestone with KubeCon around the corner.

/milestone Next

**Comment by nikhita** [comment]
PR to add the `needs-triage` workflow - https://github.com/kubernetes/test-infra/pull/19272

**Comment by nikhita** [comment]
Closing since we have the `needs-triage` and `triage/accepted` workflow now. Please reopen if needed.

/close
