### ISSUE TITLE
Kubernetes 'Supported releases' docs arbitrarily mention GKE versioning

### ISSUE THREAD

**Issue by geerlingguy** [kubernetes/community#3469]
I was reading through the [Supported releases and component skew](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew) documentation in the Versioning section today, and noticed that the policy of supporting the three most recent minor releases is, and I quote:

> in line with [GKE's supported upgrades policy](
https://cloud.google.com/container-engine/docs/clusters/upgrade).

It seems like it might be okay to drop that last line in the docs, as I'm not sure why Kubernetes should tie its own versioning policies to a specific vendor's versioning policies. It would be better if we could reference a more general industry rule, or just mention that "supporting more than three minor versions would place an undue burden on the Kubernetes maintainers". But appealing to some docs for one particular vendor doesn't really seem to hold as much water for me (especially considering I don't currently run any clusters on GKE and don't have plans to at this time).

**Comment by geerlingguy** [comment]
@kubernetes/sig-docs-maintainers

**Comment by kaushikchaubal** [comment]
Hi @geerlingguy, I can pick up this issue and create a PR. This is going to be my first PR to the community so if anything is incorrect, please shout out.
