### ISSUE TITLE
group mentoring automation and formation

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3479]
Cut from original issue #2659 for a smaller sized issue: 
 
We have information that someone wants to know to a level higher in their community membership journey and is interested in group mentoring - now what?

- [ ] an automated process that lets SIG chairs/TLs/subproject POCs know when people want to go to the next membership level so they can start a group. 
   - [ ]  a script that will see who is doing the work where (self-service; this could be as simple as sharing a spreadsheet but would not feel comfortable sharing contributor info to those not applicable to their SIG)
-OR-
   - [ ] an automated weekly report of everyone that has signed up for group mentoring at a certain level for a specific SIG/WG and someone on the mentoring team will help form if the self service option (above) is not moving smoothly.

/help

**Comment by markyjackson-taulia** [comment]
After reviewing I think it would be best to have an automated weekly report of everyone that has signed up for group mentoring bu this requires SIG/WG lead participation. I will take this action item start the discussion with a few SIG/WG and see if I can from that templatize/codify this issue task

**Comment by markyjackson-taulia** [comment]
@jberkus During the last mentoring sub-project meeting you and @parispittman were assigned this issue. Is it ok if I assign it to you? I didn't want to do that without your approval 😺

**Comment by parispittman** [comment]
/remove-lifecycle rotten

i'm going to put this in as TODOs on the doc and then close this issue

**Comment by parispittman** [comment]
rescoped the issue to reflect todays needs

**Comment by markyjackson-taulia** [comment]
/remove-lifecycle rotten.
Rotten
