### ISSUE TITLE
docs: meet our contributors

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3480]
meet-our-contributors-md need to be updated. 

- [x] times
- [x] list the playlist
- [x] more language around the purpose and what folks get out of it
- [x] a note about steering committee - we used to do them (maybe links to the most recent edition) but we don't anymore because of public meetings bi-weekly. we will still have SC members on as guest mentors though!

**Comment by celanthe** [comment]
#4163 https://github.com/kubernetes/community/pull/4163

**Comment by parispittman** [comment]
4163 and 4435 cover this - thanks @celanthe !

/close
