### ISSUE TITLE
youtube: meet our contributors updates

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3481]
- [ ] need a transcript per episode or at least a document of questions and the times of their answers. need to figure this out so it's sustainable. 

- [ ] clip out more good questions like the code base tour for shorter, digestible soundbite clips

**Comment by castrojo** [comment]
I've started to schedule office hours streams (under events in the live stream section of youtube) instead of just going live on the main channel. 

This lets you schedule them in advance, and more importantly, they each get a unique URL, so like, you can start to market them ahead of time, and then users can set a reminder in youtube to remind them when it goes live.

There's a "copy from this live event" button on my scheduled sessions, all you have to do is click that and adapt to your needs, set a new date, etc. and youtube does the rest.  Gonna try this for a while to see how it goes, just thought I'd share.

**Comment by alejandrox1** [comment]
> need a transcript per episode or at least a document of questions and the times of their answers. need to figure this out so it's sustainable.

@mrbobbytables I can start working on this, if you dont mind

**Comment by alejandrox1** [comment]
Also removing help from this one since there are people assigned to it now
/remove-help

**Comment by onlydole** [comment]
I'd love to take this one or pair with anyone working on it!
/assign @onlydole

**Comment by markyjackson-taulia** [comment]
/assign @onlydole 

I can help you if you want to pair

**Comment by parispittman** [comment]
I can also help by talking your ear off :)

**Comment by alejandrox1** [comment]
ha needed an update on this: I've been working on this on the background.
Slowed down because of the holidays but still around :smile:

**Comment by alejandrox1** [comment]
and since this is an ongoing effort
/lifecycle frozen

**Comment by mrbobbytables** [comment]
Do we actually want to pursue #1?  If so I'd go the route we use for office hours and keep a running hackmd of the questions. They could be added to the ep description when its published.

For #2 on the list. I think we're doing a pretty good job of that ad-hoc. We have enough people keeping an eye out for that sort of content that we clip it or add it to the right playlist.

**Comment by onlydole** [comment]
For item number 1, would there be any issue with asking the CNCF if we can get funds for using a service to handle the transcriptions? I agree with @mrbobbytables on item number 2.

**Comment by parispittman** [comment]
ad hoc doesn't scale. needs to be a process. im going to add into the host guide that they need to alert the youtube admins post the meeting about which items need to be clipped out. im guessing this will be ok to do in slack? (will add this explicitly to the guide). i also see a few code base tours that are missing from the playlist so im clearly not doing well on the adhoc part. 

im also going to add to the host guide that they should be documenting the questions in a notepad, time of the question, and then upload that to the video comments so we can have a better search and youtube admins can determine other questions that can be clipped out at that time. i think we lose 3-4 good nuggets a meeting right now. we can use those for twitter and social later on. 

can we keep this open for now so i can have a reminder to do the above?

**Comment by mrbobbytables** [comment]
No prob with keeping it open 👍 
As far as process goes, Can ping youtube-admins in slack or open an issue tagging `@`kubernetes/youtube-admins . Slack will definitely get eyes on it quicker, but could fall-back to GH if no one is immediately available.

**Comment by markyjackson-taulia** [comment]
Is this still relevant? It's been open and frozen for some time now.
I'm going to mark it as rotten for now if it should be left open please update or re-freeze it 👍

/remove-lifecycle frozen
/lifecycle rotten

**Comment by parispittman** [comment]
It’s definitely still relevant because we aren’t doing any of the above now and need more help.

**Comment by jberkus** [comment]
Prospective workflow:

1. File an issue for each MOC
2. Volunteer sumarizes notes in the issue
3. member of Youtube team copy-and-pastes
