### ISSUE TITLE
REQUEST: New Slack <[channel|]> <#sig-performance>

### ISSUE THREAD

**Issue by aakarshg** [kubernetes/community#3490]
**GitHub Username:**

**Slack Username:**

**What Type of Request is it (Channel, Bot, Token, or Webhook)?**
Channel

**Name of Requested Resource:**
#sig-performance

**Description of Request:**
Requesting a slack channel to discuss performance of k8s and distributions

**Comment by mrbobbytables** [comment]
`sig-` prefixed channels are reserved for official [SIGs](https://git.k8s.io/community/sig-list.md). 

However, if you're looking for performance related topics I would check out [`#sig-scalability`](https://git.k8s.io/community/sig-scalability).

**Comment by aakarshg** [comment]
@mrbobbytables Would it be possible to perhaps get a #kubernetes-performance channel in that case then? 
We're currently working on a [benchmark-operator](https://github.com/jtaleric/benchmark-operator), and looking for a mode of communication apart from github to allow open discussion about performance and also the project itself. We're all new to kubernetes and are looking for more users to engage in the discussion regarding performance and running workloads to benchmark. Although performance and scale are mostly coupled together, and usually go hand in hand. I was looking at a channel to focus purely on performance and couldn't find any.

**Comment by mrbobbytables** [comment]
We generally prefer to have tool/topic discussions in the related sig channels till they have grown to be a large enough community to warrant a channel of their own. Keeping the discussion in the sig related channel is a good way to begin to engage with others that are focused on the same area.

**Comment by aakarshg** [comment]
Okay I understand, I'll try to interact with folks on #sig-scalability then. Thank you, I'm closing the PR.
