### ISSUE TITLE
Improve documentation about community norms and processes 

### ISSUE THREAD

**Issue by pmorie** [kubernetes/community#350]
The [incubator process](https://github.com/kubernetes/community/blob/master/incubator.md) is currently very light on details about a number of facets of the community.  As an example, the role of the Champion is defined as:

> Potential Champions come from the set of all Kubernetes approvers and reviewers with the hope that they will be able to teach the Incubator Project about Kubernetes community norms and processes. The Champion is the primary point of contact for the Incubator Project team; and will help guide the team through the process. The majority of the mentorship, review, and advice will come from the Champion. Being a Champion is a significant amount of work and active participation in the sponsored project is encouraged.

The 'community norms and processes' referred to are very sparsely defined.

Since we are attempting to control growth and sprawl in `kubernetes/kubernetes`, it is logical to assume that in the future many people will make their entrance into the development part of our community via the incubator process.  We should ensure that newcomers have a way to understand the community norms and processes in a way that:

1.  Doesn't depend on the personal knowledge level of an incubator repo Champion
2.  Doesn't depend on the personal bandwidth of an incubator repo Champion
3.  Is accurate, high-fidelity, and maintained by the community

Our experience from SIG service catalog has been that:

1.  Newcomers to the community who make contact first with an incubator do not have an easy way to familiarize themselves with the community norms and processes
2.  Because the norms and processes knowledge exists across the minds of many different individuals and has been transmitted via oral history, few people fully know what the established norms and processes are
3.  Knowledge transmission via retelling and answering individual questions is extremely inefficient and time consuming
4.  Motivation and rationale behind norms are not always clear to people who are familiar with the norms and processes

I think it would improve things if we:

1.  Clearly define the most important norms and process that should be followed; there are probably different ones that become important at different levels of maturity
2.  Clearly define which norms and processes must be adopted as exit criteria to incubation
3.  Document each norm and process from the above clearly, with onboarding instructions for things that require setup (bots, CI, etc)

Specific norms and processes from our experience in SIG service catalog:

1.  Code review / approval process:
    1.  Whose approval is needed for a particular change?
    2.  Pointers to automation for reviews and approvals
2.  Overall approach to generated code:
    1.  What code is generated?
    2.  Which generated code is commited to source control?
3.  Dependency management and vendoring code:
    1.  Which dependency management tool should be used?
    2.  Are dependencies vendored?
4.  Overall system architecture patterns:
    1.  What is the lifecycle of an API request?
    2.  How does one construct an API server?
    3.  How does one create a new controller?
5.  Testing
	1.  What level of testing is expected/required?
	2.  What dependencies can a repository require for testing? Viz: must an incubator repo be testable on a laptop without an internet connection?  With an internet connection?

Though this issue has already mentioned the following, I want to note again for emphasis that in addition to the facts for these, it is also critical to document the rationale behind the facts.

Specific asks for this issue:

1.  Let's add some specificity about the areas I've cited that we had some trouble with in the service catalog SIG
    1.  Note: it's totally possible that we won't wind up wanting to be prescriptive in certain areas -- we should be explicit about those too
2.  Let's try to have (1) done by the time 1.6 is released

**Comment by erictune** [comment]
+1 to having a graduation requirement of "uses common review and automation standards".

**Comment by idvoretskyi** [comment]
cc @bgrant0607 @philips @calebamiles as we have already had the thoughts about enhancing the Incubator.

**Comment by sarahnovotny** [comment]
cc @philips as well.

**Comment by derekwaynecarr** [comment]
+1 on the need for common code review patterns within reason.  I am not
sure if every incubator needs to follow OWNERS files yet for example.

**Comment by spiffxp** [comment]
awaiting deployment of https://github.com/kubernetes/test-infra/pull/4089 to take away the `needs-sig` label
