### ISSUE TITLE
LF Help Desk Email changed

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3502]
per @idvoretskyi in todays community meeting, LF's new contact information is through the website.

"The Linux Foundation HelpDesk email is not valid anymore. Instead, please visit https://support.linuxfoundation.org/"

if this is the case, we will need to change references in docs and CLA bot that list the email.

**Comment by idvoretskyi** [comment]
Mentioned on line #8 here - https://identity.linuxfoundation.org/migration-faq.

**Comment by idvoretskyi** [comment]
Fixed with https://github.com/kubernetes/community/pull/3503

Thanks @mrbobbytables!

**Comment by cblecker** [comment]
/reopen

Hey Ihor,
Can we get the right process into our docs somewhere? Is https://jira.linuxfoundation.org/servicedesk/customer/portal/4/create/88 the link to create the right time of ticket?

We also need to update the bot prompt with either direct information, or an updated link to the doc on how to get support:
https://github.com/kubernetes/test-infra/blob/master/prow/plugins/cla/cla.go#L36-L54

Thanks!

**Comment by idvoretskyi** [comment]
@cblecker 

> Is https://jira.linuxfoundation.org/servicedesk/customer/portal/4/create/88 the link to create the right time of ticket?

Yes, but I prefer us using the https://support.linuxfoundation.org/ - the internal JIRA URL may accidentally change.

**Comment by mrbobbytables** [comment]
@cblecker @idvoretskyi 
Are there any other places that you know of that should be updated? I **think** this can be closed  now that https://github.com/kubernetes/test-infra/pull/12343 has been merged.

**Comment by cblecker** [comment]
I can't see any others, but if I do we can reopen. Thanks both of you!
/close
