### ISSUE TITLE
Create Registration form for Contributor Summit

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#3505]
As discussed, we need to have separate registration for the contributor summit.  This means creating a bilingual page and all of the requirements for registration on it.

We should also coordinate with sig-docs on this.

**Comment by mrbobbytables** [comment]
/sig contributor-experience
/kind feature
/area contributor-summit
(for now until the other labels get approved)

re: translation for reg form. I think LF has handled that in the past and with reg being managed by LF this time around I think that is something they could swing.
/cc @debgiles

**Comment by debgiles** [comment]
Yes, we will help with translations for all things related to the China event.

@jberkus Did you need it to be a separate registration form for China?  Or did including it in the registration form last year work okay for China and we just need to increase the capacity for attrition?  

I had heard it worked okay last year within the same form, but I'm open to your feedback.

If we need a separate form, attached is what it will look like with translations added as an example.
![Screen Shot 2019-03-22 at 12 53 50 PM](https://user-images.githubusercontent.com/39927820/54843123-abf64580-4ca1-11e9-85c4-25701b9f4cde.png)

**Comment by mrbobbytables** [comment]
One other thing that came up today that might be useful on the reg form is preferred language. There's a ballpark idea from last year, but having an actual number to track might be worthwhile going forward.

/area cn-summit

**Comment by jberkus** [comment]
Deb:

I'm afraid you heard wrong.  We had a 70% noshow rate, because attendees selected it because it was free (I interviewed a couple).  This is why we need a separate form (this should include the Doc Sprints as well); needing to follow a link to somewhere else will cut down on the "because it was free" crowd.

Also, we do want to ask people questions beyond what you have above.

**Comment by jberkus** [comment]
Tagging @zacharysarah here too for Doc Sprints content.

/sig docs

**Comment by zacharysarah** [comment]
@jberkus 👋 We'd definitely like to add at least one or two questions for folks interested in doc sprints. What's the deadline for providing input?

/cc @hanjiayao

**Comment by jberkus** [comment]
@debgiles per meeting yesterday, please make sure that the text of the summit registration includes a statement like:

"This event is co-located with KubeCon Shanghai 2019"

**Comment by jberkus** [comment]
This was done a while ago.
