### ISSUE TITLE
REQUEST: New Slack channel #kubernetes-docs-de

### ISSUE THREAD

**Issue by bene2k1** [kubernetes/community#3507]
**GitHub Username:** @bene2k1

**Slack Username:** @benedikt

**What Type of Request is it (Channel, Bot, Token, or Webhook)?** Channel

**Name of Requested Resource:** #kubernetes-docs-de

**Description of Request:** Channel for translation of Kubernetes documentation in German

**Comment by rlenferink** [comment]
+1 good to see a German translation for our docs 🎉

**Comment by mrbobbytables** [comment]
/cc @zacharysarah 

looping in for visibility

**Comment by rlenferink** [comment]
ref: https://github.com/kubernetes/website/pull/13340

**Comment by zacharysarah** [comment]
Excellent!

**Comment by mrbobbytables** [comment]
+1 go for it!

**Comment by rlenferink** [comment]
Perfect! `kubernetes-docs-de` just got created 🎉 

/close
