### ISSUE TITLE
REQUEST: New Slack channel ::: meetup-penang

### ISSUE THREAD

**Issue by kylix3511** [kubernetes/community#3509]
**GitHub Username:**
kylix3511
sujaypillai

**Slack Username:**
kylix
Sujay Pillai

**What Type of Request is it (Channel, Bot, Token, or Webhook)?**
Channel 

**Name of Requested Resource:**
meetup-penang

**Description of Request:**
We would like have a channel for people who are like minded to learn, speak, spread and enjoy Kubernetes and it’s power in Penang and Butterwoth Areas.

**Comment by mrbobbytables** [comment]
+1 👍

**Comment by jeefy** [comment]
+1

**Comment by mrbobbytables** [comment]
@kylix3511 After some discussion, would `#malaysia-users` be okay? It looks like we don't have any groups represented from there currently and it might serve as a better catch-all.

**Comment by kylix3511** [comment]
@mrbobbytables ```#malaysia-users``` is little wired :) We will inherit ```kubernetes``` with ```malaysia``` ... something like ```#kubernetes-malaysia``` or ```#malaysia-kubernetes``` ? Will that be possible or acceptable ?

**Comment by mrbobbytables** [comment]
It follows the pattern we've typically used for local communities. 
Usually in the form of:
`[country code|country|region]-[users|dev]`.
For example we have:
- `de-users` - German community
- `malta-users` - Malta community
- `aus-nz-users` - Australia/New Zealand community

**Comment by kylix3511** [comment]
Oh OK. In that case, #malaysia-users works.

**Comment by mrbobbytables** [comment]
It has been created :)
Just ping back in here or in slack if theres anything else you need.

Thanks!

/assign
/close
