### ISSUE TITLE
A question regading "Allocatable" computation

### ISSUE THREAD

**Issue by hamiBU** [kubernetes/community#3510]
Hello

I'm tryinh to find out that how kubernetes calculate the allocation of resources? Actually, I cannot find it in the source code.
 In one of the post allocatable has been calculated as  [Allocatable] = [Node Capacity] - [Kube-Reserved] - [System-Reserved] - [Hard-Eviction-Threshold]. Could you please help me to find the related source codes?

Cheers

**Comment by mrbobbytables** [comment]
@hamiBU You might be better off asking your question to the [Kubernetes-dev mailing list](https://groups.google.com/forum/#!forum/kubernetes-dev) or the [kubernetes-dev slack channel](https://kubernetes.slack.com/messages/C09R23FHP/). Both places will get you more relevant eyes on the question.
