### ISSUE TITLE
Links are broken for page "community/sig-contributor-experience/"

### ISSUE THREAD

**Issue by sasachan** [kubernetes/community#3512]
Page community/sig-contributor-experience/ has section GitHub Teams - It seems to have broken links.

![image](https://user-images.githubusercontent.com/12516416/54874121-f515d900-4e0a-11e9-84a9-a8b25ce76280.png)

/sig contributor-experience
/cc @nikhita

**Comment by mrbobbytables** [comment]
@sasachan To view the teams, you must be a member of the org. If you wish to see who is a part of each team, you can view the [sig-contributor-experience team config](https://github.com/kubernetes/org/blob/master/config/kubernetes/sig-contributor-experience/teams.yaml) in [kubernetes/org](https://github.com/kubernetes/org).

**Comment by sasachan** [comment]
Thanks @mrbobbytables

**Comment by mrbobbytables** [comment]
Sure thing! :) It can be confusing coming in stumbling across those links without knowing that sort of thing ahead of time.
