### ISSUE TITLE
SIG Meet and Greet @New Contributor Workshop KubeCon2019 Barcelona

### ISSUE THREAD

**Issue by guineveresaenger** [kubernetes/community#3516]
This issue will be used as a means to track mentor volunteers - if you could drop your contact information in a comment here or via k8s Slack to me @gsaenger you will earn karma points, my eternal gratitude, and new members for your SIG.

Do you need more SIG members? Are there many outstanding Good First Issue and Help Wanted labels in your SIG’s projects? Are you running out of Reviewers in your OWNERS files? Will members of your SIG attend the Contributor Summit at KubeCon Barcelona?

This is the opportunity for you and your SIG!

We need one or more of your members to volunteer 30 - 50 minutes of their time to meet interested new contributors in person. You'll find our their skills, how they can add value, and talk about a first issue they can try. If you've ever been to a Speed Networking session, it's very similar except you both have the same goal. You - to find more contributors; Them - to find a SIG to be a part of.

Requirements:

Member of SIG***
Available at at KubeCon Contributor Summit Barcelona in the afternoon
Familiarize yourself with your SIG’s needs, and maybe a few good first issues
Willingness to follow up and be available for questions by new folks.
Add your name/contact information below via comment to this issue.

***This person need NOT be a SIG Chair or Maintainer, just someone willing to be a friendly face, show folks around the repo via chat, and generally bridge the gap for new contributors from “this is where I want to contribute” to “here’s how I can contribute”. In fact, this might be an opportunity for other people in your SIG to grow.

/area contributor-summit
/area eu-summit
/sig contributor-experience
/cc @parispittman 
/cc @geekygirldawn 
/assign

**Comment by spzala** [comment]
@guineveresaenger cool, please count me in for IBM Cloud SIG. Thanks!

**Comment by dims** [comment]
@guineveresaenger count me in.

**Comment by soltysh** [comment]
I'll try to show up too for sig-cli.

**Comment by vllry** [comment]
I'll volunteer for sig-network.

**Comment by cmluciano** [comment]
I'll be there to assist @vllry with SIG-Net too.

**Comment by spiffxp** [comment]
I'll be there for SIG Testing

**Comment by hogepodge** [comment]
I’ll be available for both SIG-Cloud-Provider and SIG-OpenStack

**Comment by parispittman** [comment]
I'll be there for ContribEx

**Comment by guineveresaenger** [comment]
THANK YOU EVERYONE for showing up and welcoming our new contributors! 🎉
