### ISSUE TITLE
Proposal to make a subproject for the kubernetes.io/blog

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#3524]
https://github.com/kubernetes/community/blob/master/sig-docs/charter.md#cross-cutting-and-externally-facing-processes
>Kubernetes blog: SIG Docs hosts the Kubernetes blog and provides tooling and workflow support for publishing the blog, **but does not directly review blog posts or work with blog contributors.**

https://github.com/kubernetes/community/blob/master/sig-contributor-experience/charter.md#cross-cutting-and-externally-facing-processes
>Communication platforms that are **out of our scope** for maintenance and support but we may still have some influence: **kubernetes blog**

It appears as though there is no explicit part of the Kubernetes project that owns the blog.  I raised the issue during steering, and suggested we formalize this effort as a subproject that can be staffed by reviewers and approvers who work for more companies than LF/CNCF.

There are existing policies and people in charge of this stuff, and all of these currently live in a repo that is owned by sig-docs, so I think this should be a sig docs subproject.  This is not to put the onus on sig-docs chairs, but to instead recognize the folks that are already doing this as part of the community, and documenting any gaps to ensure others can help out if they're interested

/priority important-soon
I can't drop everything to do this today, but I think it's reasonable to accomplish this before KubeCon EU

/committee steering
Since I mentioned it here, and it closes a gap

/sig docs
Since I think this is the SIG that should own the subproject

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/steering/issues/40 for the issue where this came up

**Comment by parispittman** [comment]
should this issue live against the website repo?

**Comment by spiffxp** [comment]
Involves subproject creation, that's sigs.yaml and community-related.  Treating this as umbrella issue.  Doesn't need to be tracked against contribex's milestones

**Comment by zacharysarah** [comment]
@parispittman 👋 
> should this issue live against the website repo?

Once we agree about subproject ownership, we can open an issue in k/website to change the relevant `OWNERS*` files for permissions. For now I think we're OK to treat this like an umbrella issue as @spiffxp suggests, given the changes to `sigs.yaml`.

**Comment by parispittman** [comment]
cc/ @jaredbhatti @kbarnard10 

fyi - some docs folks are meeting tomorrow (friday) to discuss the formation of an editorial group that would own this subproject. more soon.

**Comment by zacharysarah** [comment]
We met today to discuss. Per the [SIG Docs charter](https://github.com/kubernetes/community/blob/master/sig-docs/charter.md#subproject-creation), the chairs agreed to form a SIG Docs subproject for the Kubernetes blog. 

- @kbarnard10 will lead the subproject
    - @kbarnard10 will update SIG Docs info in k/community:
        - https://github.com/kubernetes/community/tree/master/sig-docs
        - https://github.com/kubernetes/community/blob/master/sig-docs/charter.md

Other members of SIG Docs and SIG contribex will [take on supporting tasks](https://docs.google.com/document/d/1-XWPHvd-Y141JnOurLD6pyk50rJ_fwPQgjmYomB8_9Q/edit#) to create the subproject.

**Comment by spiffxp** [comment]
/close
This was fixed by https://github.com/kubernetes/community/pull/3640, thanks a bunch!
