### ISSUE TITLE
REQUEST: New Slack channel k14s

### ISSUE THREAD

**Issue by cppforlife** [kubernetes/community#3527]
**GitHub Username:** @cppforlife
**Slack Username:** `dkalinin`
**What Type of Request is it (Channel, Bot, Token, or Webhook)?**: channel
**Name of Requested Resource:** `#k14s`

**Description of Request:**
We've recently open sourced a few Kubernetes related tools (ytt, kapp) under https://github.com/k14s. We think having presence in Kubernetes slack will be convenient for existing Kubernetes users to ask questions, discuss project features, bugs, direction.

cc @nimakaviani

**Comment by jeefy** [comment]
👍 from me

**Comment by mrbobbytables** [comment]
+1

**Comment by jeefy** [comment]
Heya @cppforlife -- #k14s has been created in the Kubernetes Slack workspace. 

Please keep in mind that while this is a channel to support your project, you must adhere to the [Kubernetes Code of Conduct](https://github.com/kubernetes/community/blob/master/code-of-conduct.md). If you need anything else slack-related, please hop into the #slack-admins channel.

Thanks!

/assign
/close
