### ISSUE TITLE
Broken link in "SIG Roles and Organizational Governance"

### ISSUE THREAD

**Issue by bagrat** [kubernetes/community#3530]
In the first bullet-point list, the last item has a broken link to `[forums provided]`. See the screenshot below:

<img width="936" alt="Screen Shot 2019-03-29 at 3 27 43 AM" src="https://user-images.githubusercontent.com/3033265/55199243-ce70ed00-51d2-11e9-9f86-c1955437ba5a.png">

**Comment by nikhita** [comment]
/remove-sig docs
/sig contributor-experience

The doc with the broken link is https://github.com/kubernetes/community/blob/master/committee-steering/governance/sig-governance.md.

The correct link should be https://github.com/kubernetes/community/blob/master/communication/README.md

/good-first-issue
