### ISSUE TITLE
Building On-Prem Kubernetes Hybrid Cluster ( with windows and linux worker nodes)

### ISSUE THREAD

**Issue by sanjaymore** [kubernetes/community#3533]
Hi I am trying to build Kubernetes Hybrid Cluster in virtual environment on my host carrying windows 10 pro.
I am using Hyper-v-manager to to build three vm.
Two of them are running Ubuntu 18.04 Server ( Master and Worker Node)
One is running Windows 2019 Server ( evaluation version) to be deployed as Windows Worker Node.
I could build the K8s Cluster with Linux node, but having an issue adding windows node.
Kubectl version being used is **1.14.0**
Docker version being used us **18.09.2**
I am following further guide to add windows node..
https://kubernetes.io/docs/setup/windows/user-guide-windows-nodes/

Though when run the start.ps1 script as follows ..
.\start.ps1 -ManagementIP 10.102.195.109 -NetworkMode overlay  -ClusterCIDR 10.244.0.0/16 -ServiceCIDR 10.96.0.0/12 -KubeDnsServiceIP 10.96.0.10 -LogDir C:\k

Getting following error ..
`E0329 00:47:51.307381    4244 kubelet.go:2244] node "winkubnode" not found
E0329 00:47:51.413893    4244 kubelet.go:2244] node "winkubnode" not found
E0329 00:47:51.449011    4244 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://10.102.194.138:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dwinkubnode&limit=500&resourceVersion=0: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")`

Can someone help me understand where exactly am I going wrong ?

**Comment by nikhita** [comment]
This looks like an issue with the docs. @sanjaymore can you open an issue on https://github.com/kubernetes/website instead? Sorry for the back-and-forth :grimacing: 

/close

**Comment by sanjaymore** [comment]
> This looks like an issue with the docs. @sanjaymore can you open an issue on https://github.com/kubernetes/website instead? Sorry for the back-and-forth 😬
> 
> /close

Thanks Nikhita .. let me see what can be done wrt writing back to Kubernetes.
Meanwhile a link to correct document (if someone has followed in the past) would be of great help.

**Comment by nikhita** [comment]
>  Meanwhile a link to correct document (if someone has followed in the past) would be of great help.

I'd suggest asking on the #sig-windows channel on the Kubernetes slack.

**Comment by sanjaymore** [comment]
> > Meanwhile a link to correct document (if someone has followed in the past) would be of great help.
> 
> I'd suggest asking on the #sig-windows channel on the Kubernetes slack.

Thanks again Nikhita .. will give it a try.
