### ISSUE TITLE
REQUEST: New Slack channel #kubernetes-docs-es

### ISSUE THREAD

**Issue by raelga** [kubernetes/community#3538]
**GitHub Username:** @raelga

**Slack Username:** rael

**What Type of Request is it?** Channel

**Name of Requested Resource:** `#kubernetes-docs-es`

**Description of Request:**

In the `#es-users` channel we started looking for contributors to work on the Spanish of the website and the documentation. Having a dedicated channel will help on joining forces to coordinate the localization and avoid filling with docs related discussion the main `#es-users` channel.

We've been discussing in the `#sig-docs` slack channel about starting this initiative and the initial localization PR is already going on at https://github.com/kubernetes/website/pull/13543.

The naming of the channel follows the naming convention used for the other localization initiatives.

CCing @sieben, @zacharysarah and @Rajakavitha1 that were part of the conversation at `#sig-docs` channel.

**Comment by mrbobbytables** [comment]
+1 \o/

**Comment by jeefy** [comment]
+1 🎉

**Comment by mrbobbytables** [comment]
Channel has been created :)
/assign
/close

**Comment by sieben** [comment]
+1

Em sáb, 30 de mar de 2019 20:21, Jeffrey Sica <notifications@github.com>
escreveu:
