### ISSUE TITLE
current community infra issues / gsuite

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3541]
we have contributors@kubernetes.io (and many others)

following up on steering committee meeting re: issues with current set up/gsuite, reasons why we want to talk to someone at gsuite, etc. 

UPDATE: @mrbobbytables added community mailing lists to a k8s.io group that auto feeds into the calendar now. This could be an ok solution for right now.  
**1- calendaring:** some sigs are following the guidelines we've laid out as best practice but how can we make this better? this requires 40+ shared calendars with chairs needing to keep up on access perms and maintenance of their calendars. can we centralize this and still share ownership with sigs/chairs/people who need it? can we use the gsuite api to make this better? can sigs.yaml power the calendar? 
**why this is an issue/past issues:** sig meetings not showing up on community calendar, calendar owner is no longer here - temp or perm - to edit/cancel/delete/reschedule, invite not set up correctly (transparency perms, no info, etc.)

UPDATE: still an issue 
**2- documentation ownership:** individuals own docs vs the project. can we centralize this and still share ownership with sigs/chairs/people who need it? can we use the gsuite api to make this better? can we use team drive in places that make sense like storing of contribex files that don't go in a github repo? Current issue with gsuite: we don't have access to create team drives. 
**why this is an issue/past issues:**: can't transfer ownership of document after someone goes MIA, permissions issues when creating, sharing issues

UDPATE: still an issue 
**3- more youtube automation research:** zoom cloud to google contributor@ sig buckets -> youtube playlists.
currently use splain but can have problems; zoom cloud is a back up if something fails and we need to manually upload

**Comment by parispittman** [comment]
@philips - is this enough to warrant a call with google now? anything else needed? i talked to a gsuite customer rep at NEXT and told them the situation and they said that this is what they do and can help us. supposedly there are features for nonprofits, like a ton more users than standard, that we can take advantage of. just want to get someone on the phone.

**Comment by philips** [comment]
> 5- can we automate github processes like rewards and rec systems to use gsuite to generate emails, calendar events, etc.?

What is this? Can you expand this?

I think all of these requests are reasonable and the scope seems tight enough to have a good conversation. Any other input @michelleN ?

**Comment by philips** [comment]
@parispittman  I have the ability to make support requests via the Gsuite admin console. Could you draft the email you want me to send to them?

**Comment by cblecker** [comment]
related: https://github.com/kubernetes/k8s.io/issues/228

**Comment by parispittman** [comment]
@philips sorry ive been out; super sick. 

how's something like this?

We wanted to talk to someone about our current organizational structure and how we can best use gsuite to accomplish our goals. We’ve run into some roadblocks with our current gsuite configuration. One example, is the current issues surrounding accounts that should be shared by a group to give them one voice (e.g. contributor@kubernetes.io). Currently this requires passing around credentials; it works, but does not feel sustainable. We also have docs that are owned at individual levels and would like to potentially use team drive for this; however, we can't figure out how to enable Team Drive on the account. We are also managing 40 individual calendar entries on a shared calendar that isn't owned by our gsuite and would like to know how to better manage this or if what we are doing is the right path.

**Comment by philips** [comment]
![image](https://user-images.githubusercontent.com/33544/56699237-8fd33300-66a9-11e9-983b-9fe9cfbc4cfc.png)

@parispittman sent.

**Comment by dims** [comment]
fyi the k8s-infra working group will be using the google groups under kubernetes.io for granting permissions to community resources (switching over from using public google groups). please see https://github.com/kubernetes/k8s.io/issues/228 for details

**Comment by parispittman** [comment]
gsuite got back to philips with this:

Basically to cover your first query about shared accounts I would like to suggest for you to read up on the Collaborative inbox, as this is in my opinion closes I've found to compensate for the shared account accessible by certain users. You can read up in more detail in this article here:
https://support.google.com/a/answer/167430?hl=en
**action for us: need an owner for this or I'll pick back up when I get extra cycles. problems are above and can discuss further, too. we need a plan on how we should set up users. (example: should sigs have lists under here and so that they aren't individually owned and project owned?)**

To cover your second query related to Team Drive enabling in short words the basic edition of G Suite does not support Team Drives, hence the reason why you were unable to locate the options for this. The edition supporting Team Drive feature are G Suite Enterprise, Business, or Education editions. More details on Team Drives can be found here:
https://gsuite.google.com/learning-center/products/drive/get-started-team-drive/#!/
**actions for us: if we want team drive, we need to upgrade gsuite and get new approvals?**

And lastly to cover your query about Shared Calendar not owned by your G Suite I can suggest export of the Calendar, and Import to your domain. This will copy the events (if by calendar entries you mean events) and make your G Suite owner of it for easier management, however from that point on wards your users would need to make events on the newly imported and re-shared Calendar as there is no way to link them to do this automatically. Steps and guides for exporting can be found here:
https://support.google.com/calendar/answer/37111?hl=en
and for importing here:
https://support.google.com/calendar/answer/37118
**action: needs an owner. someone with access to the contributors@ account needs to test this.**

**Comment by parispittman** [comment]
conversations around security and the use of zoom has come up around the community. one possible solution would be the use of meet chat on gsuite which now has a capacity for 100 on the editions mentioned by the gsuite rep above. the positive would be easy livestreaming via youtube and records of all SIG meetings without individuals owning them. need to look into further: global access

**Comment by parispittman** [comment]
/remove-lifecycle stale

most of this is still applicable. the priority would be the team drive so we can play with splain's automation features for youtube which is a more solid connection than the current pipe.

**Comment by spiffxp** [comment]
It looks like contributors@kubernetes.io has Group Admin privileges for kubernetes.io.  That means it can create, read, update, and delete groups.  Now that we have automated managed of kubernetes.io groups and their membership via [k8s.io/groups/groups.yaml](https://github.com/kubernetes/k8s.io/blob/master/groups/groups.yaml), I'd like to suggest we revoke this permission.  

The ability of contributors@k8s.io members to manage specific groups would still be preserved, as specified in groups.yaml.

**Comment by parispittman** [comment]
@spiffxp pls do revoke. community@ would be an example of one group that they should still manage though but that is probably lumped into your perserved note.

**Comment by spiffxp** [comment]
OK, I just revoked the Group Admin role.  If you find you are suddenly unable to do what you need, please open an issue in kubernetes/k8s.io and ping us #wg-k8s-infra on slack

**Comment by nikhita** [comment]
> sig meetings not showing up on community calendar

https://github.com/kubernetes/steering/issues/166 should help with this

**Comment by spiffxp** [comment]
/reopen
/remove-lifecycle rotten
I am noodling on a proposal related to this. The tl;dr is that if this ~gsuite~ Google workspace is funded out of the same bucket of cloud credits that funds k8s-infra, I am pretty sure we can find a workable solution that costs an additional <=2% of our current spend. I'll send to steering for review when ready, unless you would rather contribex take a look first

**Comment by spiffxp** [comment]
Some prior art for managing Google calendar https://github.com/sethvargo/terraform-provider-googlecalendar

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/steering/issues/213 as a placeholder for a proposal to address these issues

**Comment by parispittman** [comment]
with the migration efforts which will help with documentation the best we can, we can close this. also setting new fresh YouTube related issues. 

/close
