### ISSUE TITLE
Joining a Kubernetes SIG

### ISSUE THREAD

**Issue by codeekage** [kubernetes/community#3543]
Hello there 👋,

I'm Abraham Jr.  Agiri a member of Node.js TLC (top-level committee). I have some personal interest in GCP-SIG and DOCs-SIG, but also love to make contributions to the greater Kubernetes community. 

I'm having a little difficulty knowing where to get started and make contributions, would really appreciate having someone guide me through and explain how things work here. 

I'm also hoping to build some local Kuberentes communities as I understand how the GitHub and greater community work. 

Cheers 🎉,
Abraham Jr. Agiri

**Comment by daminisatya** [comment]
Hi, @codeekage Welcome! 

This talk will definitely help you get an outline of how Kubernetes as community functions.

https://www.youtube.com/watch?v=yVOCRrK6Fh0

**Comment by spzala** [comment]
@codeekage thank you for your interest in contributing! Please work with both the sigs you are interested. You can get more info about how to get in touch with them here,
https://github.com/kubernetes/community/tree/master/sig-gcp
https://github.com/kubernetes/community/tree/master/sig-docs
About learning community contribution, Github workflow and other things, you can find many resources here,
https://github.com/kubernetes/community/tree/master/contributors (e.g. https://github.com/kubernetes/community/blob/master/contributors/guide/github-workflow.md) 
If you still have a specific question please ask on sig-contributor-experience slack channel for quick answer (https://github.com/kubernetes/community/tree/master/sig-contributor-experience) 
Hope this is helpful and it's OK to close this issue. Thanks!

**Comment by nikhita** [comment]
@codeekage Welcome to Kubernetes :tada: :smile: 

I'll close this issue. Feel free to reopen if needed.

/close
