### ISSUE TITLE
API conventions should offer guidance on embedding types

### ISSUE THREAD

**Issue by pmorie** [kubernetes/community#3545]
There are a number of places within the kubernetes APIs where an API type is embedded within another type that may alter some semantics of that type. As an example, `ReplicaSet` embeds the `PodTemplateSpec` type in its spec, but [alters the semantics of certain fields](https://github.com/kubernetes/kubernetes/blob/602c3eb0e610520521c0eb750d9b36dd60c64393/pkg/apis/apps/validation/validation.go#L646), for example:

- You may not set the `activeDeadlineSeconds` field on a `PodTemplateSpec` within a `ReplicaSet`
- You must always use `RestartPolicyAlways` in a `PodTemplateSpec` within a `ReplicaSet`

It would be very useful to have some guidance within the API conventions on the best way to approach decision making around additional or altered semantics when designing APIs that embed types, especially types like `PodTemplateSpec` that are pervasively used.

**Comment by mattmoor** [comment]
One of the interesting elements of our discussion of this in Knative (thanks @pmorie) was that folks would likely have a bias towards embedding (e.g. `corev1.Container`) and validating fields out vs. redefining them.  The net effect of this is that the OpenAPI schema for these types will be shared and express a superset of the fields that the API really allows.

A case where this gets gnarly is: suppose I want to build an IDE integration that keys off of the schema data to provide auto-completion.  It'll show me fields I cannot specify :(
