### ISSUE TITLE
REQUEST: New moderator for embano1 of Slack (SIG VMware)

### ISSUE THREAD

**Issue by embano1** [kubernetes/community#3547]
### GitHub Username
@embano1 

### Property you'd like to Moderate
Slack (SIG VMware)

### Username on Property Requested
@embano1 

### Requirements

- [x] I am a Kubernetes Org member already
- [x] I have enabled 2FA on my account for the property I would like to moderate (if applicable).
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @cantbewong 
- @frapposelli 
- @castrojo 

### List of qualifications for this position

- Active participation in discussions on SIG VMware, SIG Scheduling and SIG Node, as well as external events (Kubecon, meetups)
- Active member on 3rd party forums, e.g. Reddit
- Been a Kubernetes contributor for some time and I am familiar with the code of conduct. I will do my best to help maintain a positive culture.

**Comment by frapposelli** [comment]
/lgtm

:+1:

**Comment by castrojo** [comment]
We don't really do per-channel moderation, we put you in a pool of other moderators. However having people concentrate on specific channels is a good idea as long as we're also ensuring the common areas have coverage. 

Also not explicit, but similar to org membership, I would be more comfortable with a +1 from a non-vmware sponsor

**Comment by nikhita** [comment]
> Also not explicit, but similar to org membership, I would be more comfortable with a +1 from a non-vmware sponsor

big +1 for @embano1 :)

**Comment by jeefy** [comment]
With Tempelis looming, do we want to move @embano1 forward as a Slack Moderator (we have 2 +1's) or do we want to wait and guinea-pig them as a #sig-vmware moderator? 

To be clear:
![no-strong-feelings](https://user-images.githubusercontent.com/1394552/55978619-0bae9380-5c45-11e9-8269-0518f5fe3ee6.jpg)

**Comment by mrbobbytables** [comment]
I would lean towards Tempelis. It would be a great first-use example for channel specific moderation.

**Comment by nikhita** [comment]
Is this possible through Tempelis right now?

**Comment by mrbobbytables** [comment]
Not quite yet.
