### ISSUE TITLE
speed mentoring kick off for kubecon barcelona

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3556]
speed mentoring kick off tracking issue for the speed mentoring sessions

- [x] - change the name of the event: Networking & Mentoring Session 
- [x] - update the registration form to collect all pertinent info needed up front 
- [x] - update copy to describe mentoring pods 
- [x] - figure out signage needs
- [ ] - ask mentors if they would like to do it again so we have a pool to start with and kick things off
- [ ] - use past FAQ and update for example questions for mentors to help set expectations
- [ ] - update the doc in the /mentoring folder with the information

/assign

**Comment by nwoods3** [comment]
Not sure we need "update copy to describe mentoring pods" in the initial copy, maybe when the mentor/mentees confirm we can send them a thank you for registering email with logistical information like format, what they need to come prepared with, what they can hope to take away, etc. Just trying to cut down on the initial event copy and any language confusion. Also, we can use the image of the pod throughout all communication/promotion to visually try to get the point across. Thoughts?

**Comment by mrbobbytables** [comment]
I derped on this one. Its for **KubeCon EU** NOT the EU contributor summit. My bad.

/remove-area contributor-summit
/remove-area eu-summit
/area mentorship-planning

**Comment by parispittman** [comment]
event is over. opening a new issue to cover the last item.

/close
