### ISSUE TITLE
REQUEST: Rename Slack channel: #ksonnet -> #jsonnet

### ISSUE THREAD

**Issue by anguslees** [kubernetes/community#3558]
The "ksonnet" project is [shutting down](https://blogs.vmware.com/cloudnative/2019/02/05/welcoming-heptio-open-source-projects-to-vmware/).  Some parts of the project (notably [kubecfg](https://github.com/ksonnet/kubecfg)) live on, as does the emergent jsonnet<->kubernetes community that use this channel.

To better reflect its focus, can we rename #ksonnet to #jsonnet ?

(Thanks in advance)

**Comment by castrojo** [comment]
Done, you'll want to update your pinned items and topic though!
