### ISSUE TITLE
REQUEST: New Slack channel #cluster-api-baremetal

### ISSUE THREAD

**Issue by russellb** [kubernetes/community#3568]
**GitHub Username:**

@russellb 

**Slack Username:**

russellb

**What Type of Request is it (Channel, Bot, Token, or Webhook)?**
Channel

**Name of Requested Resource:**
#cluster-api-baremetal

**Description of Request:**
The cluster-api sub-project of the cluster lifecycle SIG has #cluster-api, but also some channels for discussing the specifics of integration with different platforms (#cluster-api-aws, #cluster-api-azure, #cluster-api-openstack).

The purpose of this new channel would be to discuss the specific challenges of using cluster-api in a baremetal environment.  There are multiple efforts that would be discussed here, for example:

* automated bare metal host provisioning via cluster-api (github.com/metalkube/)
* different attempts at an ssh provider that supports pre-existing infrastructure

**Comment by castrojo** [comment]
/close

On this, I'll reach out in slack.
