### ISSUE TITLE
REQUEST: New Slack bot: Riot Bridge for #crio

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/community#3569]
**GitHub Username:**

@saschagrunert

**Slack Username:**

sgrunert

**What Type of Request is it (Channel, Bot, Token, or Webhook)?**

Bot

**Name of Requested Resource:**

Riot Bridge

**Description of Request:**

Hey 👋, we would like to setup a Riot Bridge between the freenode cri-o IRC channel and the Slack crio channel, to synchronize our IRC with Slack to not miss any relevant information. 

To do so, we need the permissions to authorize the riot.im bridge to Kubernetes slack and the authorize the riot account for the IRC channel. All should work fine with slacks event bridging.

**Comment by jeefy** [comment]
Heya @saschagrunert -- Several slack-admins have discussed this, and we feel we can't fulfill this request. 

The Kubernetes Slack adheres to the CNCF Code of Conduct and is managed by the community. While I totally see the value in adding this bridge, we would not be able to enforce the COC. Thanks for sparking the discussion, and we'll document our decision in the [Slack Communication Guidelines](https://github.com/kubernetes/community/blob/master/communication/slack-guidelines.md) soon.

/assign
/close

**Comment by saschagrunert** [comment]
Alright I understand. Nevertheless, hank you for having a look into my request. 🙏
