### ISSUE TITLE
Document conventions for raw API fields

### ISSUE THREAD

**Issue by pmorie** [kubernetes/community#357]
The [API conventions document](https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md) does not contain any information about raw API fields.  My understanding of the (undocumented) convention is that these should be `runtime.RawExtension` in versioned APIs and `runtime.Object` in unversioned APIs.  This issue is to document both the convention and the rationale in the API conventions document.

cc @kubernetes/api-reviewers

**Comment by smarterclayton** [comment]
I'll do it

**Comment by vaikas-google** [comment]
Any updates or ideas as to when this might land?

**Comment by pmorie** [comment]
This came up again here: https://github.com/kubernetes-incubator/service-catalog/issues/911

I think this needs to be documented since people are getting different answers when they ask people because **nothing is written down**.

**Comment by erictune** [comment]
@kow3ns had to deal with this for ControllerHistory.

**Comment by mrbobbytables** [comment]
Is this still relevant? It's been open and frozen for some time now.
I'm going to mark it as rotten for now, if it should be left open please update or re-freeze it 👍  

/remove-lifecycle frozen
/lifecycle rotten

**Comment by lavalamp** [comment]
This is miscategorized, it belongs to the api review subproject of sig arch, IMO

**Comment by mrbobbytables** [comment]
/assign @dims @johnbelamaric 
Can you take a look at this and see if its still relevant? or should we move to close it?
