### ISSUE TITLE
REQUEST: New Slack channel #chart-testing

### ISSUE THREAD

**Issue by scottrigby** [kubernetes/community#3573]
**GitHub Username:**

scottrigby

**Slack Username:**

scottrigby

**What Type of Request is it (Channel, Bot, Token, or Webhook)?**
New channel please :)

**Name of Requested Resource:**
#chart-testing 

**Description of Request:**
Channel for transparent discussions about helm/chart-testing. Anyone is welcome to contribute. See https://github.com/helm/chart-testing

**Comment by jeefy** [comment]
Heya! Quick question. :) Would this fall under the #helm-dev channel? Or is this a unique-enough topic and #helm-dev busy enough that this would warrant a separate channel? Thanks! 

Other slack-admins feel free to +1 in the meantime.

**Comment by rimusz** [comment]
helm-dev is for helm development, the chart-testing one is related to charts testing

**Comment by mrbobbytables** [comment]
I'm okay with +1'ing this. If it's okay, I think channel name should be `#helm-chart-testing` to fall in line with the other helm channels (makes it easy to discover when someone types in `helm` into channel search).

**Comment by rimusz** [comment]
#helm-chart-testing +1 for the channel name

**Comment by scottrigby** [comment]
🎉

**Comment by rimusz** [comment]
👍
