### ISSUE TITLE
REQUEST: New Slack channel #k8s-code-organization

### ISSUE THREAD

**Issue by dims** [kubernetes/community#3575]
**GitHub Username:**

dims

**Slack Username:**

dims

**What Type of Request is it (Channel, Bot, Token, or Webhook)?**
Channel

**Name of Requested Resource:**
#k8s-code-organization

**Description of Request:**
Need a place to discuss issues around the `code organization` subproject of sig-architecture. Please see https://github.com/kubernetes/community/tree/master/sig-architecture

**Comment by dims** [comment]
cc @liggitt

**Comment by mrbobbytables** [comment]
+1

**Comment by dims** [comment]
sorry about the confusion between the title and body, let us use `#k8s-code-organization`

**Comment by jeefy** [comment]
+1

**Comment by mrbobbytables** [comment]
created :)
/assign
/close
