### ISSUE TITLE
REQUEST: New Slack channel: #youtube-zoom-admins

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3577]
**Slack Username:**
paris

**What Type of Request is it (Channel, Bot, Token, or Webhook)?**
channel

**Name of Requested Resource:**
youtube-zoom-admins

**Description of Request:**
a place for youtube and zoom admins to discuss day to day responsibilities

**Comment by jeefy** [comment]
Big +1

**Comment by castrojo** [comment]
I'm ok with just doing this in the contribex channel.

**Comment by parispittman** [comment]
can i request a user group then so i can call all of the youtube admins and zoom admins at once instead of tagging everyone individually? @castrojo

**Comment by jeefy** [comment]
We should be able to add a usergroup via a PR through [Tempelis](https://github.com/kubernetes/community/tree/master/communication/slack-config) now.

**Comment by parispittman** [comment]
@jeefy do you mind doing that for me?

**Comment by jeefy** [comment]
Absolutely! :) 

/assign

**Comment by mrbobbytables** [comment]
Follow-up once done (no big rush), should update zoom/youtube docs that the groups are available to ping if you need immediate assistance.
