### ISSUE TITLE
REQUEST: Rename slack channels deis-users|deis-dev

### ISSUE THREAD

**Issue by kingdonb** [kubernetes/community#3582]
Hello! I am @teamhephy-admin and we're the new maintainers of Deis Workflow, I was wondering if we can rename #deis-users and #deis-dev to reflect that "ownership" or maintainership has changed?

The Deis channels are pretty quiet, we are recruiting volunteers on our own slack, but it would be good to have a continued presence on the Kubernetes slack.  There is no commercial endeavor behind this team, we are just keeping the lights on and making sure it's possible for newcomers to install Workflow.

It's open for discussion whether this should be called "workflow-users" or "hephy-users" but we don't own the Deis trademark (property of Microsoft) so, I would suggest something else.  Thoughts?

Thanks! --Kingdon

**Comment by mrbobbytables** [comment]
I think this is fine -- I would opt for `hephy-*` as workflow is quite generic and used in quite a few things.

/sig contributor-experience
/area community-management

**Comment by kingdonb** [comment]
I agree! Workflow is quite generic as a mark.

**Comment by Katharine** [comment]
+1 for #hephy-* from me - https://github.com/deis/workflow/blob/master/README.md appears to confirm this as the successor.
