### ISSUE TITLE
Develop content for social media posts about CN Summit

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#3585]
We need to give some suggested content for LFAsia and others to share on social media about the summit.

**Comment by idealhack** [comment]
We had some preparation for this, but eventually, CNCF folks beat us on translating the blog post: https://mp.weixin.qq.com/s/yqb6yHiorkuSDQCQCBtUVw

xref:

- https://github.com/kubernetes/community/issues/3587
- https://github.com/kubernetes/website/pull/14837

**Comment by idealhack** [comment]
let's try better next time!

/close
