### ISSUE TITLE
Contact speakers for Shanghai and solicit their participation in the Contributor Summit

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#3586]
Now that the list of talks is out, we can make sure that folks go to the Summit as well.

This needs to be a group effort, can we divide it up?

/sig contributor-experience
/area cn-summit
/priority important-soon

**Comment by jberkus** [comment]
This got done, led by @xiangpengzhao

**Comment by idealhack** [comment]
/assgin @xiangpengzhao
/assgin 

just for the record :)
