### ISSUE TITLE
Write Kubernetes Blog post advertising the Summit.

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#3587]
/sig contributor-experience
/area cn-summit
/assign jberkus

**Comment by parispittman** [comment]
/close

[will update with a link for records]

**Comment by idealhack** [comment]
links here:

- https://kubernetes.io/blog/2019/06/12/join-us-at-the-contributor-summit-in-shanghai/
- https://kubernetes.io/zh/blog/2019/06/11/%E6%AC%A2%E8%BF%8E%E5%8F%82%E5%8A%A0%E5%9C%A8%E4%B8%8A%E6%B5%B7%E4%B8%BE%E8%A1%8C%E7%9A%84%E8%B4%A1%E7%8C%AE%E8%80%85%E5%B3%B0%E4%BC%9A/
