### ISSUE TITLE
Apply style guide to non-code contributing guide

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/community#3599]
Make sure that the [non-code contributors guide](https://github.com/kubernetes/community/blob/master/contributors/guide/non-code-contributions.md) conforms to the [style guide](https://github.com/kubernetes/community/blob/master/contributors/guide/style-guide.md).

/good-first-issue
/help

**Comment by Sai-Adarsh** [comment]
Still open for contributions?

**Comment by nikhita** [comment]
Closing as https://github.com/kubernetes/community/pull/3596 merged. Please reopen if needed.

/close
