### ISSUE TITLE
Setup biweekly meeting for licensing subproject

### ISSUE THREAD

**Issue by nikhita** [kubernetes/community#3623]
Licensing is a subproject under SIG Release: https://github.com/kubernetes/sig-release/tree/master/licensing

To keep the ball rolling on this, it would be helpful to setup a public biweekly meeting for it. This issue is for tracking setting up the meeting - creating a doodle, finalizing on a time, adding it to sigs.yaml and notifying the sig-release mailing list. 

/sig release
/area licensing
/cc @swinslow @dims @justaugustus @tpepper @calebamiles 

/assign @justaugustus 
since you mentioned you'll create the doodle. let me know if you shouldn't be assigned here, I'll assign myself then :)

/cc @kubernetes/dep-approvers 
since you might be interested in it

**Comment by justaugustus** [comment]
@nikhita @dims @swinslow -- Doodle is up here: https://doodle.com/poll/ch62xafdbgqmyrtp

**Comment by justaugustus** [comment]
@nikhita @dims @swinslow -- My apologies, KubeCon prep has gotten the best of me. 
Can we plan to meet the week of 5/27? If that works, I'll send another Doodle.

**Comment by nikhita** [comment]
> KubeCon prep has gotten the best of me.

Np, can relate to that :)

> Can we plan to meet the week of 5/27? 

Sounds good!

**Comment by swinslow** [comment]
Yes, works for me! Thanks @justaugustus :)

**Comment by justaugustus** [comment]
@nikhita @dims @swinslow -- New Doodle for the Licensing subproject meeting: https://doodle.com/poll/bg9g5pcfw3v66g7r

**Comment by justaugustus** [comment]
@dims -- just a heads up to vote on this Doodle when you have a chance.

**Comment by justaugustus** [comment]
@nikhita @dims @swinslow -- Invite sent for Thursday, May 30th, 2pm ET!
We may move this meeting as it is in the same timeslot as SIG Arch, but let's try it out for now and adjust if we need to later. :)

/close

**Comment by justaugustus** [comment]
Notified SIG Release on the mailing list: https://groups.google.com/d/topic/kubernetes-sig-release/boaGhSZwd54/discussion

**Comment by nikhita** [comment]
> We may move this meeting as it is in the same timeslot as SIG Arch, but let's try it out for now and adjust if we need to later. :)

I'm cool with this timeslot for this week, but would prefer if we can move it later so that it won't conflict with the SIG Arch (code organization) meeting. :)

I think I filled out the doodle before the code organization meeting was setup (sorry!) :see_no_evil:

**Comment by justaugustus** [comment]
@nikhita -- For sure, that can be one of our discussion topics!

**Comment by justaugustus** [comment]
@nikhita is going to be taking point on Licensing moving forward so that I can direct my attention to the Release Engineering work. I'll let her handle the scheduling and provide support where needed.

/unassign
/assign @nikhita

**Comment by swinslow** [comment]
Hi @nikhita, I've made a note to reach out to you shortly so that we can reconnect and move this forward. Thanks!

**Comment by dims** [comment]
@swinslow ping!
