### ISSUE TITLE
[k8s blog] profile on past ncw attendees 

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3638]
Interview and profile two past new contributor workshop attendees for kubernetes blog 

@vllry and @soggiest 

things to include outside of the interviews:
- how to sign up for the barcelona and shanghai new contributor workshops
- a quote from @guineveresaenger about the new 201 workshop
- if they have any personal pics to share from the event

@vonguard will be assigned this issue once org membership rolls though.

**Comment by guineveresaenger** [comment]
@vonguard I'm `gsaenger`on Slack

**Comment by guineveresaenger** [comment]
Google doc: https://docs.google.com/document/d/1aA3Nc3hzNgu-tYLTms5cjRPa_HGY_teoliWRd3zy7_4/edit?usp=sharing

**Comment by guineveresaenger** [comment]
This is done! Thank you @parispittman for co-authoring with me and thank you @vllry for the video clips!

Blog post here: https://kubernetes.io/blog/2019/05/14/expanding-our-contributor-workshops/

/close
