### ISSUE TITLE
Add info about keywords in commit messages in contributor guide

### ISSUE THREAD

**Issue by nikhita** [kubernetes/community#3642]
The [invalidcommitmsg](https://groups.google.com/d/topic/kubernetes-dev/MOnwc8_76wo/discussion) prow plugin will disallow at mentions (like @nikhita) and [keywords which close issues](https://help.github.com/en/articles/closing-issues-using-keywords) (like fixes #xxxx) in commit messages. 

We should add this info to the contributor guide so that contributors know not to add these keywords in the first place.

cc @guineveresaenger @mrbobbytables 

/sig contributor-experience
/area contributor-guide
/kind documentation
/good-first-issue

**Comment by nzoueidi** [comment]
I can take care of this!

**Comment by nikhita** [comment]
Fixed in https://github.com/kubernetes/community/pull/3731. Thanks @nzoueidi!

/close
