### ISSUE TITLE
Cheatsheet should have links to security policies and procedures

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#3646]
/assign

**Comment by castrojo** [comment]
Filed in the middle of a meeting so just adding some detail, we should make sure the cheatsheet is pointing to the proper security procedures for the project, what to do, who to escalate to, that sort of thing.

**Comment by cblecker** [comment]
You mean the the security vulnerability/product security team procedure?

**Comment by castrojo** [comment]
Yep, all the information is here: https://kubernetes.io/docs/reference/issues-security/security/

**Comment by cblecker** [comment]
yup.. adding a link to it sounds great 👍

**Comment by castrojo** [comment]
https://github.com/kubernetes/community/pull/3651
