### ISSUE TITLE
leadership trainings

### ISSUE THREAD

**Issue by tpepper** [kubernetes/community#3662]
In other large projects with technical oversight or steering committees, I've observed that the associated foundation has funded various types of baseline and ongoing training when major boards are established or as membership turns over. Education around topics such as unconscious bias, decision making, conflict resolution, code of conduct violation/response trainings exist in industry to insure boards have standard leadership tool knowledge to be the most effective they can be. I would find it inspirational and confidence boosting to know our project leadership (especially the steering committee, but perhaps also SIG/WG chairs too?) had access to these tools and that it was valued by these governance bodies/chairs and CNCF to the point of having some required skills training baseline, dedicating the time to do them annually, and having funding for these consultations and trainings.

was: https://github.com/kubernetes/steering/issues/98

**Comment by parispittman** [comment]
thanks for filing, @tpepper! agreed and let's work on this. 

updates:
the code of conduct committee received incident management interactive training from otter tech consulting funded by CNCF. we had a good experience and I inquired to get a quote for training moderators and communication platform operators. sending a note to steering and kicking off cncf servicedesk ticket process for funding request today. 

looking into - facilitation, decision making, general leadership training for chairs. dims provided a rec and will update.

**Comment by mrbobbytables** [comment]
Just checking in, any update on this? Last was a recommendation from dims on an idea.

/remove-lifecycle stale

**Comment by parispittman** [comment]
@mrbobbytables we have the chairs/tl meeting now that we can do trainings and things through. i honestly don't remember if i connected with dims so will need to ping him again. @dims

**Comment by nikhita** [comment]
We now require unconscious bias training for all SIG/WG/UG leads - https://github.com/kubernetes/community/pull/4940.

/close
