### ISSUE TITLE
REQUEST: New Slack channel #big-data-user-group (<-- rename #sig-big-data)

### ISSUE THREAD

**Issue by erikerlandson** [kubernetes/community#3665]
**GitHub Username:**
@erikerlandson 
@goltermann 

**Slack Username:**
@goltermann 

**What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?**
Channel

**Name of Requested Resource:**
#big-data-user-group
(rename existing #sig-big-data)

**Description of Request:**
Requesting channel re-name from #sig-big-data  to #big-data-user-group

**Comment by erikerlandson** [comment]
see also: #3666

**Comment by mrbobbytables** [comment]
I'm still unsure of this change, and the renaming of the group altogether. Our convention has been `[sig|wg|x]-<group>` and putting user-group  on the end breaks from that convention completely.

Was there some consensus on changing the name?

**Comment by erikerlandson** [comment]
There was no particular consensus. Since this is the first user group, I chose names that I thought made sense. If the steering committee prefers some other name, that's fine with me. By far my highest priority is to get the changes finalized with the minimum friction for the community members.

**Comment by nikhita** [comment]
Wdyt about `ug-big-data`? That's how the directory, label etc are named today :)

**Comment by erikerlandson** [comment]
that would be OK with me

**Comment by erikerlandson** [comment]
if there is no objection, I'll re-submit the sigs.yaml google-group PR for "kubernetes-ug-big-data"

**Comment by mrbobbytables** [comment]
That sounds good to me 👍
