### ISSUE TITLE
SIG diagram needs update

### ISSUE THREAD

**Issue by nikhita** [kubernetes/community#3673]
The SIG diagram https://github.com/kubernetes/community/blob/master/SIG-diagram.png is out of date since some working groups like Container Identity don't exist anymore. 

Additionally, it would also be helpful to include a way to edit this diagram...if it was created in google slides, maybe a link to the slides, etc.

/cc @bgrant0607 @luxas @cblecker

**Comment by idvoretskyi** [comment]
/close

Closed by https://github.com/kubernetes/community/pull/4129
