### ISSUE TITLE
SIG-GCP Zoom Meeting and Meeting Docs 

### ISSUE THREAD

**Issue by codeekage** [kubernetes/community#3678]
Hello All - 

The meeting docs here https://docs.google.com/document/d/1mtmwZ4oVSSWhbEw8Lfzvc7ig84qxUpdK6uHyJp8rSGU/edit#heading=h.m19juqx3y3zc have not been updated since 2018 and the zoom link seems broken. 

Is there a new link for the zoom meetings and meeting notes?

**Comment by codeekage** [comment]
Thank you @nikhita  for the adding labels 🙏

**Comment by ameukam** [comment]
SIG-GCP is now a sub-project of SIG Cloud Provider. You can find meeting docs and updates here: 
https://docs.google.com/document/d/1OZE-ub-v6B8y-GuaWejL-vU_f9jsjBbrim4LtTfxssw/edit#heading=h.w7i4ksrweimp. 

/close
