### ISSUE TITLE
Wanted: APAC Coordinator for ContribEx

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3693]
Looking for someone who can help prop up our efforts in the APAC region for Contributor Experience. This will include:

- [ ] speaking at meetups and local events about the work that happens in contributor experience
- [ ] writing blog posts about the same in multiple languages (coordinating translation when necessary)
- [ ] helping us with regional boards on discuss.kubernetes.io
- [ ] helping us to run the APAC Contributor Experience update meeting
- [ ] writing the role book for this role that will live under /community/sig-contributor-experience

**Comment by idealhack** [comment]
Thank you for opening this specifically, Paris. I'm willing to help with some of the efforts.

**Comment by nikhita** [comment]
We should also add this to the Role board on discuss.kubernetes.io (I can help with it next week)

**Comment by Rajakavitha1** [comment]
@parispittman I am willing to help with some of the efforts!!!!

**Comment by aravindputrevu** [comment]
@parispittman Heya! I'm interested in doing some of these.. esp #1, #2 & #5.

**Comment by Pensu** [comment]
@parispittman Hey! Would love to help with some of the issues, whichever applicable!

**Comment by parispittman** [comment]
@idealhack do you want to lead this and then build a team with the rest of the folks?

**Comment by idealhack** [comment]
@parispittman sure! I'll try my best :)

**Comment by parispittman** [comment]
also note: We (contributor experience SIG) have a kubecon Shanghai Intro session (~30 minutes). Maybe this is something folks on here could help out with along with @jberkus. The other SIG Chairs and TLs won't be attending that one unfortunately.

**Comment by aravindputrevu** [comment]
@parispittman Great! I will be at KubeCon Shanghai. (Provided, I get my VISA in time)

**Comment by xihaLong** [comment]
@parispittman I frequently go between HangZhou/ShangHai, ChengDu/XiAn/ChongQing, ShenZhen/DongGuan/HongKong and will love to help in any way. I am professionally most interested in Continuous Delivery Foundation topics presently

@idealhack and @aravindputrevu See you soon in at KubeCon ShangHai! :+1:

**Comment by puja108** [comment]
Yes, we'll be there. Also at the contrib summit shanghai. I'm not based in APAC most of my time, but happy to help where I can.

**Comment by alisondy** [comment]
new Zealand checking in, would be keen to help out

**Comment by saiyam1814** [comment]
@nikhita @parispittman I am willing to contribute, specially for #1 #2 and other as well. 
I can speak on the managed kubernetes service including GCP, AWS and Oracle cloud, kubernetes monitoring , kube-eagle, cluster autoscaler(I am already part of that SIG attending meetings), Rancher docker and kubernetes etc.
I write blogs on managed kubernetes and basics as well on medium (would be happy to contribute) you can see some of my work : 
https://medium.com/faun/rancher-one-place-for-all-kubernetes-clusters-51586d72858a
https://medium.com/faun/kubernetes-essentials-282ac9951542
https://medium.com/oracledevs/kube-eagle-on-oracle-kubernetes-engine-f2c8a3730565
and other as well medium.com/@saiyampathak
Note- giving the links only for you to see my work on kubernetes and not for publicity :)

**Comment by idealhack** [comment]
Thanks to all the volunteers! We can start to work on this by resume the APAC version of [SIG meetings](https://github.com/kubernetes/community/tree/master/sig-contributor-experience#meetings). I'm thinking of a bi-weekly one after the current one (Wednesdays 9:30 PT), it could be around the old time (Wednesdays 20:00 PT) but does not have to. Let's do a doodle next week.

/assign

**Comment by idealhack** [comment]
To be clear, we will figure out things like the checklist above in this meeting at first, once that's done, we can run the APAC meetings full version eventually.

The doodle is here: https://doodle.com/poll/e2wx98nrc4g8ipek, please vote in a week if you want to join us :)

**Comment by nikhita** [comment]
Closing since we now have APAC coordinators for contribex, and we are meeting biweekly and planning exciting things. :)

Thanks @idealhack @aravindputrevu @alisondy @saiyam1814!! :tada: 

/close
