### ISSUE TITLE
Guide needs to mention setting github status

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#3696]
prow's going to be taking people's github status into account when auto-assigning reviews, we need to document this in the guide so people understand that we use their status to weigh results. 

/area contributor-guide
/assign castrojo
/sig contributor-experience

**Comment by nikhita** [comment]
Ref: https://groups.google.com/d/topic/kubernetes-dev/bXHK8l3D6l0/discussion

**Comment by mhamdisemah** [comment]
@nikhita can I take care of this ? As this my first issue I would like to get some help.

**Comment by nikhita** [comment]
> @nikhita can I take care of this ? 

Sure! :smile: 

> As this my first issue I would like to get some help.

https://groups.google.com/d/topic/kubernetes-dev/bXHK8l3D6l0/discussion has more details on the feature that we'd like to document. Basically it means that you can set your github status to "busy" to avoid getting review requests - if you are on vacation, taking time off, etc.

A note about this needs to be added in https://github.com/kubernetes/community/tree/master/contributors/guide#code-review and https://github.com/kubernetes/community/blob/master/contributors/guide/community-expectations.md#expectations-of-reviewers-review-latency.

If you have any questions, feel free to ask them here or on the #sig-contribex channel on slack. :)
