### ISSUE TITLE
Unable to run a specific integration test

### ISSUE THREAD

**Issue by marun** [kubernetes/community#370]
The [instructions](https://github.com/kubernetes/community/blob/master/contributors/devel/testing.md#run-a-specific-integration-test) for how to run a specific integration test don't work.  All tests are always run regardless of the regex supplied.

**Comment by marun** [comment]
Looks like https://github.com/kubernetes/kubernetes/pull/33952 provides a way to specify a test case:

```bash
make test-integration WHAT="auth -test.run=TestKindAuthorization"
```

This seems hacky, but it does work.  Should the documentation be updated to match the script, or the other way around?

cc: @thockin @eparis @deads2k

**Comment by thockin** [comment]
Why doesn't the documented way work?  It seems straight-forward, but I didn't dig in.  This hack is a hack.

**Comment by marun** [comment]
I was misinterpreting ``go test`` output.  I assumed that output like the following indicated that tests were running but that's not the case (it will appear even for packages for which no tests are run):

```bash
PASS
ok      k8s.io/kubernetes/test/integration/serviceaccount       0.101s
```

So the documented way does work, my bad.

I'm assuming that [#31533](https://github.com/kubernetes/kubernetes/pull/31533) was aiming to bypass this behavior by scoping to a single integration test package.  I think it would be preferable for ``make test-integration`` to follow the convention of ``make test`` in passing ``WHAT`` through to the test runner, and I plan on fixing that.

**Comment by marun** [comment]
Fix for ``make test-integration`` posted to https://github.com/kubernetes/kubernetes/pull/41581
