### ISSUE TITLE
Rewards and Recognition Umbrella Issue

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3708]
Using this issue to collect anything and everything that we have and are building that relates to rewarding and recognizing contributors. Issue will close when we have PR'ed a doc in the /contributors folder. 

- CNCF Awards (maintainer, chop wood carry water)
  - add links
- Contributor Summit Awards (need to codify)
- #shoutouts channel in slack feeds into Thursday Community Meeting Announcements section
- Swag incentives: office hours, meet our contributors, what else?

issues/ideas:
- https://github.com/kubernetes/test-infra/issues/11994
- kubecon tickets for completing x/doing a special thing/award
- k8s certification codes/opportunities?

This issue should close, when we have a doc stored somewhere (TBD) that lists all of the above in detail, what it is, who, how, when, etc. 

#6354

**Comment by parispittman** [comment]
/remove-lifecycle stale

def not stale :)

**Comment by parispittman** [comment]
/remove-lifecycle stale

still a thing

**Comment by mrbobbytables** [comment]
We sorta did this at KCS Boston with the awards and drafted the [awards ceremony role book](https://github.com/kubernetes/community/blob/master/events/events-team/content/awards-ceremony.md#awards-ceremony-handbook), although it still has some outstanding TODOs.

Maybe create an awards dir similar to the [cncf awards repo](https://github.com/cncf/awards) and formalize things a bit more?

**Comment by mrbobbytables** [comment]
/unassign @nikhita @mrbobbytables @parispittman 

@castrojo will finish this up with the awards from KCC this year.

**Comment by Debanitrkl** [comment]
I guess this is already documented here https://github.com/kubernetes/community/blob/master/events/awards/playbook.md regarding the community awards and regarding the CNCF awards, it's here https://github.com/cncf/awards
