### ISSUE TITLE
Community Maintenance for 2019

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#3717]
This is a list of things we should audit, see https://github.com/kubernetes/community/blob/master/sig-contributor-experience/community-maintenance.md for more details.

Feel free to assign yourself to a section, if you've done any of this in 2019 check it off.

### Slack

- [x] Channels - Anything out of place or not following the guidelines? 
  - [x] Close unused channels. 
  - [x] Check to see if there is a purpose, pinned documents like agendas, and other best practices being used in the channel. These are not required but are useful.
- [x] Audit the Integrations and apps
- [x] Audit the user tokens
- [x] Audit the Emojis
- ~[ ] Generate a Slack data report to share with the community (optional)~

### GitHub
Assignee: @mrbobbytables 

- [x] Audit Org admin permissions
- [x] Audit Integrations
- [x] Check Label usage (education, deprecation, etc) - likely to be revised this year (2020)
- [x] Is the PR and/or issue message still good/the best? - likely to be revised this year (2020)
- [x] Check kubernetes/community/.github/PULL_REQUEST_TEMPLATE
- [x] Where’s the issue template located? 

### Calendars

- [x] Check that the calendar works
  - Go to http://k8s.io/community and follow the flow
- [x] Make sure all SIG, WG, and other community meetings are showing - especially check new groups that were created in the last quarter
- [ ] Make sure that invites have more than one owner, shared with the mailing list distro, and have an agenda attached plus zoom URL and telephone dial information.

### SIGS

- [x] Ensure everyone in `sigs.yaml` is subscribed to sigs-leads mailing list
- [x] Ensure that chairs and leads are accurate in the `sigs.yaml`

### YouTube
Assignee: @castrojo

- [x] Check sharing on all the playlists
  - Should only be shared with leads or people appointed by leads
  - Either remove other people or regenerate a new collaboration URL
- [x] Check admin permissions on the Kubernetes account
- [x] Fix any videos accidentally tagged as unlisted 
- [ ] Generate a YouTube traffic report to share with the community (optional)

### Zoom

- [x] Ensure leads have access to their upgraded Zoom account
- [x] If appropriate change the password if a SIG has changed leadership 
  - Contact CNCF to adjust upgraded licenses if necessary

### Community Meeting

- [x] Generate an archive of the [communtiy meeting notes](https://docs.google.com/document/d/1VQDIAB0OqiSjIHI8AWMvSdceWhnz56jNpZrLs6o7NJY/edit#heading=h.2gp5yf2snwg5) for the quarter if necessary
  - [x] Ensure the retrospective section has links to the retrospective for the releases
  - [x] Ensure the demo section is filled out and demos are assigned dates
  - [x] Ensure the [agenda template and hosting guide](https://docs.google.com/document/d/1g7fR5cvCGFq15SJ4iQMclbj0QIeREKu_QP8ftnSaJ4o/edit) are up to date 
- [x] Ensure the [SIG Schedule](https://docs.google.com/spreadsheets/d/1adztrJ05mQ_cjatYSnvyiy85KjuI6-GuXsRsP-T2R3k/edit#gid=1543199895) have SIGs assigned for the next few months
  - [x] Ensure the assigned SIGs in this sheet match the actual SIGs in sigs.yaml. Double check that a SIG hasn't missed an update this past cycle and if they have schedule them for an upcoming meeting

### Mailing Lists

- [ ] Check via a web browser that each of these mailing lists, as indicated in sigs.yaml and the UG/WG README.md file actually exist
- [ ] If they exist, then we need to send a note to the organizers pointing them at the right doc in the communication folder that has the settings directions for mailing lists
- [ ] If they do not exist, we need to reach out to the organizers to set them up or correct sigs.yaml

/sig contributor-experience
/area community-management
/milestone next

**Comment by nzoueidi** [comment]
I can help in many points in this list. I will link indeed some PRs here soon. :)

**Comment by ameukam** [comment]
Interested to volunteer on this issue. :-)

**Comment by castrojo** [comment]
No need to wait on anyone, if you see something you can bust out feel free to just do it and check the boxes. The sigs.yaml stuff doesn't need special perms so that can be done, also the community meeting stuff is available in public documents so that's an easy one too, ping me on slack if you run into any problems!

**Comment by castrojo** [comment]
@parispittman I believe my template for the gsuite is now out of date, we'd just file a ticket with steering now I'd assume? Also I think you've been in there recently so we can probably check off the box for this milestone?

**Comment by scottilee** [comment]
@castrojo I took a look at the "Check that the calendar works" task and the only place I see the calendar on http://k8s.io/community is at the bottom of the page. I think it could be called out more prominently.

<img width="648" alt="Screen Shot 2019-06-17 at 4 56 31 PM" src="https://user-images.githubusercontent.com/7443383/59644327-55be6480-9121-11e9-89db-46784f335c7e.png">

Additionally, in reference to the "Make sure all SIG, WG, and other community meetings are showing - especially check new groups that were created in the last quarter" task, it's only for Kubecon events and the contributor meeting calendar https://calendar.google.com/calendar/embed?src=cgnt364vd8s86hr2phapfjc6uk%40group.calendar.google.com&ctz=America%2FLos_Angeles isn't shown anywhere.

Lastly for the "Close unused channels" task what is the criteria for "unused"? Is it if a message hasn't been posted in x days or months? If the number of members if below a threshold? Once the criteria has been established maybe Katherine Berry can use https://github.com/kubernetes-sigs/slack-infra to archive channels (https://api.slack.com/methods/channels.archive) then delete them, although there doesn't seem to be support for programmatically deleting channels.

**Comment by markyjackson-taulia** [comment]
@castrojo 
- [x] Check that the calendar works. Go to http://k8s.io/community and follow the flow
- [x]  Ensure that chairs and leads are accurate in the sigs.yaml (Since I was just working in here I thought I would make sure)

I will go through and do some more of the items on the list over the next few days

**Comment by mrbobbytables** [comment]
/remove-lifecycle stale
/assign @castrojo 
just to keep everyone else on top of things

**Comment by mrbobbytables** [comment]
Going to move forward with closing this. We can re-open for 2020/2021 👍 

/close
