### ISSUE TITLE
[docs] googlegroups changed settings 

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3718]
update mailinglist-guidelines.md that googlegroups moderation and other perm settings have recently changed globally. this has caused some breaks in certain groups visibility settings. 

instructions on how to fix from googlegroups for owners of the list:
Near the top right, click Manage group.
Click Settings 
 ->Information 
     ->Directory.
          ->Edit the setting to set the desired visibility for your group.
          ->Click Save.

need to document in the guidelines and also link to all of the changes that happened in case others have issues with the date shown (may 6 2019) -> https://support.google.com/a/answer/9191148?hl=en

**Comment by nzoueidi** [comment]
I will help with this. :)

**Comment by codeekage** [comment]
Is this for Google SIG? Haven’t much activities there. Please, correct me if I’m wrong.

**Comment by nikhita** [comment]
> Is this for Google SIG?

@codeekage No, this isn't about SIG GCP. [Google Groups](https://groups.google.com/) are used for mailing lists, and this is about documenting some settings for it. :)

**Comment by codeekage** [comment]
Thank you @nikhita. 😅 I’d love to help with some docs. Can you help walk me through? 🙏🏼

**Comment by nikhita** [comment]
@codeekage Sure, feel free to ping me on Slack and we can discuss more. I am @nikhita there as well.

**Comment by codeekage** [comment]
Please, can I get the link to Slack? 🙏🏼

**Comment by nzoueidi** [comment]
@codeekage here is the link to slack: slack.k8s.io
You might want also to join #sig-contribex.
Feel free also to ping me there, I have some good first issues in mind. My username is nzoueidi.
