### ISSUE TITLE
unconscious bias training for SIG chairs

### ISSUE THREAD

**Issue by michelleN** [kubernetes/community#3724]
The steering committee has committed to taking [unconscious bias training](https://github.com/kubernetes/steering/issues/98). Our community is large and diverse and we think this is important for us to do. We also talked about whether we should require SIG chairs and any other leadership positions to take this kind of training as well. I've opened this issue so we can come to a consensus on this as a community. Please share your thoughts and feedback here.

**Comment by cblecker** [comment]
/committee steering

If the steering committee found the training valuable, then I’m +1 to requiring sig leaders to do it too.

**Comment by nikhita** [comment]
We now require unconscious bias training for all SIG/WG/UG leads - https://github.com/kubernetes/community/pull/4940.

/close
