### ISSUE TITLE
REQUEST: New Slack user token

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/community#3726]
**GitHub Username:**
@mariantalla 

**Slack Username:**
`maria`

**What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?**
Token

**Description of Request:**
I plan to use this token to query public data from the kubernetes slack, relating to aggregated activity over a period of time. Some examples: which channels were most active, how long conversation threads were on average, how many there were to external websites (github/Google docs), which emoji reactions were most popular.

**OAuth scopes requested**: `read` across all objects is sufficient; more specifically I expect to use the following subset (ref: https://api.slack.com/docs/oauth-scopes):
`channels:read`
`emoji:read`
`files:read`
`groups:read`
`pins:read`
`reactions:read`
`reminders:read`
`search:read`
`stars:read`
`team:read`
`usergroups:read`
`users.profile:read`
`users:read`

**Comment by coderanger** [comment]
I think it would be better from a privacy PoV if you could list the specific aggregate data you are interested in and then someone from the Slack admin team could get it. Even better if you could show the script you want to run :)

**Comment by coderanger** [comment]
Also you mentioned in Slack to me that this is specifically re: the 1.14 release as part of the post-release analysis. Would be good to confirm that on here.

**Comment by mariantalla** [comment]
Thanks for the comments!

> Also you mentioned in Slack to me that this is specifically re: the 1.14 release as part of the post-release analysis
Indeed; this is in the context of collecting aggregate data on contributor collaboration during the 1.14 timeline.

> Even better if you could show the script you want to run
Good point, I'll write it against another workspace and send it back if it helps offer more detail 🤔

**Comment by mariantalla** [comment]
A bit more detail on the data points I was hoping to add:

* all public channels
* all public channels with activity during 1.14
* total number of messages during 1.14
* total number of words
* total number of threads during 1.14
* average length of thread
* number of messages per channel and per day, for the top 10 (in total messages) channels during 1.14
* slack usernames of users that posted messages during 1.14 (I only plan to use this to gauge overlap with github users; not posting usernames on screen)
* timezone spread of users who posted in slack in 1.14
* number of messages posted per user, for the 20 slack users with the most messages.
* ~_number of messages that contain github.com/kubernetes in the message body_~ (web search should be sufficient for that)
* total number of emoji reactions
* top 10 most popular reactions

I've put together a script that I'd use [here](https://gist.github.com/mariantalla/eb5eaeb3d8f7ad3be6aefa2cfef91942).

And of course, I'm happy for any access to be revoked at the end of the week.

Thoughts? Feedback?

**Comment by mrbobbytables** [comment]
Sorry for the delay in response, still playing catch up from KubeCon. -- Overall, I think this sounds fine.  :)
 The scopes are read only, and the time range is limited. It'd be interesting to see the data and run the report from release to release to see various trends.

**Comment by mariantalla** [comment]
Hello! If it's still ok to go ahead with this, I'd still be interested to get a read-only token.

/remove-lifecycle stale

**Comment by mrbobbytables** [comment]
I'm still okay with it ¯\_(ツ)_/¯
It's very tightly scoped.

**Comment by jeefy** [comment]
I'm also okay with it. It's scoped well and I see no reason not to move forward with this.

@mariantalla More a curiosity, what's this for? Pet project?

**Comment by mariantalla** [comment]
> @mariantalla More a curiosity, what's this for? Pet project?

Yep! Started with the intention to include some of these in a talk I had last Kubecon, but now it's just for side project. That said, if there's anything in specific that would be useful/interesting for the slack admins team, let me know!

**Comment by mrbobbytables** [comment]
Token has been granted \o/ 
/close
