### ISSUE TITLE
youtube: create a playlist for code base walk throughs

### ISSUE THREAD

**Issue by cblecker** [kubernetes/community#3727]

**Comment by nikhita** [comment]
/area community-management
/cc @parispittman  @castrojo @jeefy @alejandrox1 @mrbobbytables 

Maybe we should have a GitHub team for youtube admins :P

**Comment by mrbobbytables** [comment]
> Maybe we should have a GitHub team for youtube admins :P

Probably a good idea XD

**Comment by jeefy** [comment]
@kubernetes/youtube-admins Created a playlist and started populating it: https://www.youtube.com/playlist?list=PL69nYSiGNLP0gugLYzpNR1ueyUj9GjzpK

**Comment by parispittman** [comment]
/closed

thanks @jeefy

**Comment by cblecker** [comment]
Thank you!
