### ISSUE TITLE
Git Hub Repo needs code fix

### ISSUE THREAD

**Issue by ShubhasisMathur** [kubernetes/community#3735]
I am doing set up of Kubernetes on my Aws Ec2 instance. I executed the below commands as per the instructions
git clone https://github.com/kubernetes/kubernetes
cd kubernetes
make quick-release
But getting error after running the make command:
Makefile.generated_files:152: recipe for target 'gen_deepcopy' failed
make[2]: *** [gen_deepcopy] Error 1
Makefile:557: recipe for target 'generated_files' failed
make[1]: *** [generated_files] Error 2
Makefile:518: recipe for target 'cross' failed
make: *** [cross] Error 1
!!! [0523 18:22:13] Call tree:
!!! [0523 18:22:13]  1: build/../build/common.sh:519 kube::build::run_build_command_ex(...)
!!! [0523 18:22:13]  2: build/release.sh:36 kube::build::run_build_command(...)
make: *** [Makefile:461: quick-release] Error 1

I think this needs a code check in to correct the above error. PLease suggest .

**Comment by nikhita** [comment]
Closing in favour of https://github.com/kubernetes/kubernetes/issues/78342#issuecomment-495994653

/close
