### ISSUE TITLE
Clarify terminology “Kubernetes CLA” vs. “CNCF CLA”

### ISSUE THREAD

**Issue by sftim** [kubernetes/community#3737]
Some parts of this repo and the [Kubernetes documentation](https://kubernetes.io/docs/) mention a Kubernetes CLA; others, the CNCF CLA.

I _think_ the most accurate term is “CNCF Contributor License Agreement” because it's applicable to more than just Kubernetes. If so, then there's some cleanup tasks to adopt that wording everywhere.

/priority background

**Comment by cblecker** [comment]
Can you provide some examples of where you are seeing inconsistency?

**Comment by sftim** [comment]
https://github.com/kubernetes/community/blob/95bb2fbd88b951ac20b34d35a89ce71c389afe21/CLA.md mentions “the Kubernetes CLA”; later on the page, there's a sample email which says:
> You have signed CNCF Individual Contributor License Agreement

and there's a heading [Setting up the CNCF CLA check](https://github.com/kubernetes/community/blob/95bb2fbd88b951ac20b34d35a89ce71c389afe21/CLA.md#setting-up-the-cncf-cla-check)

[Setting up the CNCF CLA check](https://github.com/kubernetes/community/blob/95bb2fbd88b951ac20b34d35a89ce71c389afe21/github-management/setting-up-cla-check.md#branch-protection) then mentions a “Linux Foundation CLA”.

This is a sample; I haven't made an exhaustive search.

Revising various pages under [https://kubernetes.io/docs/contribute/](https://kubernetes.io/docs/contribute/), I wanted to change some of them to read “CNCF CLA” rather than just “CLA”; however, I couldn't work out if the correct term was in fact “Kubernetes CLA” or maybe “Linux Foundation CLA”.
(The overall aim of my changes was to make it easier for readers to learn what CNCF is short for).

**Comment by cblecker** [comment]
So "CNCF CLA", "CLA", and "CNCF Contributor License Agreement" are interchangeable in my opinion depending on the context. "Kubernetes CLA" isn't accurate, and can be corrected. "Linux Foundation CLA" is a grey area, and may be correct in some cases (in particular when talking about the `cla/linuxfoundation` GitHub status context).
