### ISSUE TITLE
Enable global Slack welcome message

### ISSUE THREAD

**Issue by nikhita** [kubernetes/community#3741]
**GitHub Username:** The issue template says that this needs to be the GitHub username of the bot owner or primary contact, not sure who this should be...I guess @Katharine or @jeefy? :grimacing:  

**Slack Username:** Again, not sure who this should be.

**What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?**: Bot, which sends a configurable welcome message to each new member who joins the kubernetes slack.

**Name of Requested Resource:** `slack-welcomer`: https://github.com/kubernetes-sigs/slack-infra/tree/master/slack-welcomer

**Description of Request:**

Whenever someone joins the Kubernetes slack, the bot will DM the person with a welcome message. The message can contain guidelines on how to interact on slack and also point them to some good-first-channels that they can join.

/cc @Katharine @jeefy  @vllry @mrbobbytables @parispittman

**Comment by Katharine** [comment]
Saving it from the history of a private Slack channel, this is the proposed message:

```
Welcome to the Kubernetes Community Slack!

The Kubernetes Slack can be a large and intimidating place, please don't be afraid to ask questions. The community is quite welcoming :) 
To ensure Slack remains a welcoming place for all, the Kubernetes Community adheres to a <https://git.k8s.io/community/code-of-conduct.md|Code of Conduct>.

*Looking to contribute?*
- Ask questions in  #kubernetes-dev.
- Join a <https://git.k8s.io/community/sig-list.md|SIG channel>.
- Have your question answered live  on stream in #meet-our-contributors during the monthly <https://git.k8s.io/community/meet-our-contributors.md|MoC>.
- Have a PR you need reviewed? Hop into #pr-reviews to get some feedback.

*Have a general Kubernetes question?*
- Join #kubernetes-novice.
- Have your question answered live on stream in #office-hours during the monthly <https://git.k8s.io/community/events/office-hours.md|Office Hours>.
- Find a  <https://git.k8s.io/community/sig-list.md|SIG channel> to join and ask your question.

*See some spam? or being harrassed?*
- Use the _"<https://git.k8s.io/community/communication/slack-guidelines.md#escalating-andor-reporting-a-problem|Report Message>"_ message action.
- Escalate by joining #slack-admins and ask for an Admin's assistance.

*Looking to join a local community?*
- There are many channels for regions and meetups, look for channels like `#meetup-[region]` or `[region]-users`.

*Other channels of note:*
- #kubecon - Get your question answered about any upcoming <https://www.cncf.io/community/kubecon-cloudnativecon-events/|KubeCon/CloudNativeCon>.
- #kubernetes-careers - A place to post Kubernetes related jobs.

Have any other questions? Please see the <http://git.k8s.io/community/communication/slack-guidelines.md|Slack communications guidelines> to start.
```

**Comment by dims** [comment]
@Katharine the message looks great!

**Comment by nikhita** [comment]
@Katharine @jeefy @mrbobbytables what are the next steps required for turning on the slack bot? Does a slack admin just need to add it to our instance?

To move this forward, I was thinking that we could do a lazy consensus on the contribex mailing list.

**Comment by nikhita** [comment]
Btw to @vllry's point on slack about how most questions in sig channels are ending up user focused:

Maybe we could replace `- Find a  <https://git.k8s.io/community/sig-list.md|SIG channel> to join and ask your question.` in `Have a general Kubernetes  question` with a link to our support channels?

**Comment by vllry** [comment]
Small suggestion: it might be good to move the "have a question" section to the top. That's probably the most relevant by volume, and many people will drop-off part way through reading.

**Comment by mrbobbytables** [comment]
Agree -- we should move it to the top. It can also be updated to route to discuss - 
```
*Have a general Kubernetes question?*
- Ask your question in the official Kubernetes Forum.
<https://discuss.kubernetes.io> 
- Join #kubernetes-novice.
- Have your question answered live on stream in #office-hours during the monthly <https://git.k8s.io/community/events/office-hours.md|Office Hours>.
```

**Comment by Katharine** [comment]
> @Katharine @jeefy @mrbobbytables what are the next steps required for turning on the slack bot? Does a slack admin just need to add it to our instance?

It needs to actually run somewhere, too (which, as ever, is a problem that will be solved via liberal application of yaml).

Of greater concern is that another of our slack bots started double reporting joins lately, which suggests a Slack API bug (or perhaps intentional entirely undocumented change) that makes me nervous about turning this on until we can dedupe the spurious events Slack is sending - otherwise we'll be welcoming people twice.

**Comment by nikhita** [comment]
> Of greater concern is that another of our slack bots started double reporting joins lately, which suggests a Slack API bug 

@Katharine from your message on slack, looks like this is no longer the case? :)

>  It needs to actually run somewhere, too (which, as ever, is a problem that will be solved via liberal application of yaml).

Do you think we could do this or would you like to wait to confirm that slack won't go berserk again? :stuck_out_tongue:

**Comment by Katharine** [comment]
I'm working on it literally as we speak

**Comment by jeefy** [comment]
/assign @Katharine 

This is done already, correct? 🎉

**Comment by Katharine** [comment]
Correct!

/close
