### ISSUE TITLE
Clarify the sig-openstack mission statement

### ISSUE THREAD

**Issue by hogepodge** [kubernetes/community#376]
After some discussion in the kubernetes-sig-openstack group, submit a patch to clarify the scope of sig-openstack to cover both OpenStack as a target platform and OpenStack as an application on top of K8S.

https://groups.google.com/forum/#!topic/kubernetes-sig-openstack/yTjt2_kJb4o

**Comment by xsgordon** [comment]
Following discussion on the SIG mailing list and in the weekly meetings @hogepodge's PR has now merged, any future additions/changes can be tracked via a new issue or PR.
