### ISSUE TITLE
Create blog@kubernetes.io alias

### ISSUE THREAD

**Issue by kbarnard10** [kubernetes/community#3763]
Requesting an alias for editors of the Kubernetes blog:

Alex Handy
Zach Corleissen
Paris Pittman
Cody Clark
Bob Killen
Kaitlyn Barnard
Jorge Castro 

cc // @parispittman

**Comment by mrbobbytables** [comment]
Teams managed under the [kubernetes/org](https://github.com/kubernetes/org) repo. The sig-docs teams are located in [org/config/kubernetes/sig-docs/teams.yaml](https://github.com/kubernetes/org/blob/master/config/kubernetes/sig-docs/teams.yaml) 👍

**Comment by nikhita** [comment]
@mrbobbytables looks like this is for an email/gsuite alias. I'm not sure who owns that...maybe steering? https://github.com/kubernetes/steering#top-level-accounts

**Comment by nikhita** [comment]
cc @philips @jbeda @spiffxp

**Comment by mrbobbytables** [comment]
> @mrbobbytables looks like this is for an email/gsuite alias. I'm not sure who owns that...maybe steering? https://github.com/kubernetes/steering#top-level-accounts

100% right, I overlooked title and went right to github team/alias 🤦‍♂

**Comment by dims** [comment]
@nikhita @mrbobbytables i have automation for k8s-infra-.* alias(es) in [1], but this needs "blog", so just drop an email to steering and one of Brandon, Joe or Aaron will create the list for you.
 
[1] https://github.com/kubernetes/k8s.io/blob/master/groups/groups.yaml

**Comment by philips** [comment]
I created blog@kubernetes.io google group and made @nikhita admin. She can add the others from here.

**Comment by nikhita** [comment]
@philips would the link be https://groups.google.com/a/kubernetes.io/forum/#!forum/blog? I can't seem to access it.

**Comment by nikhita** [comment]
Or uh wait, that should be added to groups.yaml. Will do.

**Comment by nikhita** [comment]
@dims @kbarnard10 looks like this is done?

**Comment by dims** [comment]
yep @nikhita
