### ISSUE TITLE
There should be an API-conventions document for users of CRDs

### ISSUE THREAD

**Issue by pmorie** [kubernetes/community#3776]
The API conventions document is useful but targets an audience that is adding to the kubernetes API surface directly or implementing their own aggregated API server (and thus has the same conversion / validation / default mechanisms available to them as someone making API changes in k/k). Much of this document does not directly translate to people developing APIs using CRDs. I am aware of a number of projects that could benefit from having an API-conventions-like document specifically aimed at users of CRDs; this issue is a request to make such a document.

**Comment by deads2k** [comment]
This is true.  Behaviors around nullable and optional are particularly hard and the distinctions between defaults and mutating webhooks aren't always obvious.

/assign @sttts @p0lyn0mial

**Comment by markyjackson-taulia** [comment]
Is this still relevant? It's been open and frozen for some time now.
I'm going to mark it as rotten for now if it should be left open please update or re-freeze it 👍

/remove-lifecycle frozen
/lifecycle rotten
