### ISSUE TITLE
Youtube automation request for release team

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#3793]
Opening for discussion; the release team seems like it's ready to investigate youtube automation. I was doing it by hand this cycle, which wasn't a a problem but there likely won't always be a youtube admin on RT, and on top of that release leads changes 4 times a year and sometimes it feels like we can never get the collab feature working on youtube quite right. 

Towards the end of the cycle there are daily standups and it gets a bit hectic, this feels like a place where automation could take the stress off the release team and remove some toil. 

/sig release
/sig contributor-experience

**Comment by parispittman** [comment]
Do you want to hook them up to splain.io like docs, contribex, etc?

**Comment by castrojo** [comment]
Yes I think it'd be a good step, once the 1.15 crunch is done.

**Comment by parispittman** [comment]
we can turn it on today to test - its a few clicks

**Comment by justaugustus** [comment]
Can we turn this on for the SIG Release meetings as well?

/priority important-longterm
/kind feature
/area release-team

**Comment by mrbobbytables** [comment]
Everything connected and tested. 👍 

Going to go ahead and close this out.

If there are any other problems don't hesitate to give me a ping :)

/close
