### ISSUE TITLE
Proposal to create UX sig or sub-project

### ISSUE THREAD

**Issue by tashimi** [kubernetes/community#3794]
I have been talking to some UX designers and researchers who are interested in contributing to improve the user experience of upstream Kubernetes to be more uniform and user-friendly. I was wondering if there might be community interest in creating a UX working group or sub-project?

Some ideas:
- user research initiative to better understand users of Kubernetes, distinct from builders of Kubernetes, through surveys and interviews
- collaborate to create uniform open sourced design elements (e.g. icons) for different cloud native concepts, adding on to the clarity project https://clarity.design/

I shared this idea on the SIG-PM, SIG-Arch, SIG-Contribex mailing lists, and the following people expressed interest: 

- Ron Norman: I think this is a fantastic idea, and I'd love to contribute.  I'm the UX Manager for GKE, Anthos and Cloud Run @ Google.  A few of the UX Researchers and Designers on my team have contributed to Kubernetes OSS, but we've never formed anything as official as a working group.  There is sig-ui, but I believe the focus is mainly the K8s Dashboard UI (Dan Romlein from our team is active there). We have some foundational Research that we published to the Knative project on Service Naming that might be a good starter topic on the UX Research front.  Information architecture/design is always a fun UX topics in the K8s world, and maybe a good place for some community driven Design exploration as well.
- Roger Klorese, Senior PM @ SUSE: Makes a lot of sense to me. As it forms, I’d like to add our UX lead. 
- Aaron Crickenberger: UX can mean different things to different people.  For example SIG Apps is focused on the experience of developing and running applications in Kubernetes [1].  SIG CLI is focused on the user experience of command line tools that interact with the Kubernetes API [2].  SIG Cluster Lifecycle aims to improve the user experience for cluster administration. [3] Given that it crosses so many boundaries a WG makes sense to me.  I'm curious what the aforementioned SIGs think.
- Pamel Shinh: is the originator of the clarity.design idea in my email above, and a senior UX designer at VMware

**Comment by tashimi** [comment]
@kubernetes/sig-pm-proposals, @kubernetes/sig-architecture-proposals, @kubernetes/sig-contributor-experience-proposals

**Comment by spencersugarman** [comment]
Maybe to start, this is a sig-contribex working group, and then later its own SIG or an ongoing project under an existing SIG (like PM). Short term, it would be great to define processes for how to (1) share existing work that is relevant to open source, and (2) match UX contributors to SIGs that want help.

**Comment by justaugustus** [comment]
Thanks for writing this up, @tashimi!
Echoing my sentiment from the [thread](https://groups.google.com/d/topic/kubernetes-sig-pm/OoUHBK6iKMs/discussion), I think this fits nicely as a subproject of a horizontal SIG as opposed to a Working Group (because it's something we want to continue to exist).

We'd happily support this as a subproject of SIG PM! :)
/assign

**Comment by mattfarina** [comment]
I'm excited to see some people interested in UX. We need this.

@tashimi thanks for getting this out there.

I don't think UX fits within ContribEx. [The ContribEx charter notes](https://github.com/kubernetes/community/blob/master/sig-contributor-experience/charter.md):

> The Contributor Experience Special Interest Group (SIG) is responsible for improving the experience of those who upstream contribute to the Kubernetes project.

Many of the users we need to be concerned with the experience of are not contributing to k8s development and never will. They are the people operating the clusters, operating workloads in the clusters, and extending k8s by building tools that interact with the API.

Should this be a WG or a SIG PM subproject? I think it depends on what the group wants to do. Are they looking to have active participation from some SIGs? Will active participants from the SIGs help with user research? Would it be better for the SIGs to get the output of the research?

I would suggest that if the SIGs would be better to get the output of research than a subproject of SIG PM makes sense. If active SIG participation would be useful than a WG.

**Comment by oicheryl** [comment]
There's several in the CNCF End User Community who would be keen to participate in user research studies and interviews. I'm happy to support and facilitate connecting with Kubernetes end users.

**Comment by spiffxp** [comment]
(pulling out of the e-mail thread)

UX can mean different things to different people.  For example SIG Apps is focused on the experience of developing and running applications in Kubernetes [1].  SIG CLI is focused on the user experience of command line tools that interact with the Kubernetes API [2].  SIG Cluster Lifecycle aims to improve the user experience for cluster administration. [3] 

Given that it crosses so many boundaries a WG makes sense to me.  I'm curious what the aforementioned SIGs think.

[1] https://github.com/kubernetes/community/blob/master/sig-apps/charter.md#scope
[2] https://github.com/kubernetes/community/tree/master/sig-cli#cli-special-interest-group
[3] https://github.com/kubernetes/community/blob/master/sig-cluster-lifecycle/charter.md#in-scope

**Comment by Rajakavitha1** [comment]
Hi,
SIG-Docs has been working on making https://kubernetes.io/ accessible since December 2018. In
Q2 we completed adding the guidelines for accessibility and accessibility checker:
https://github.com/kubernetes/website/pull/14292 and https://github.com/kubernetes/website/pull/14218

Guidelines for UX is planned for Q3.

**Comment by justaugustus** [comment]
The ML discussion is leading us down the path of forming SIG Accessibility, which I'm a strong +1 for. h/t @brendandburns! :)
Who's going to run with this? https://github.com/kubernetes/community/blob/master/sig-wg-lifecycle.md#Creation

/unassign
/committee steering

**Comment by serenamarie125** [comment]
I would definitely be interested in helping to support & facilitate connecting with Kubernetes end users as well

**Comment by cblecker** [comment]
/remove-sig contributor-experience

I agree that this doesn't fit with contribex, but there are other clear homes for it :)

**Comment by tashimi** [comment]
@justaugustus I'm happy to run with the SIG creation process, unless there's someone better suited?

**Comment by justaugustus** [comment]
@tashimi -- you're the OP. Go ahead and run with it! :)
Thanks again for the wonderful suggestion!

**Comment by tashimi** [comment]
@justaugustus from the mailing list it looks like @brendanburns is going to run with creating the PR to create the sig instead

**Comment by gaby-moreno** [comment]
Hello! I'm a researcher and designer on the IBM Kubernetes service, would be happy to help with any research as well or support with getting this off the ground. 

Might I suggest adding **sig-end-user-experience** to the many names  being considered?

**Comment by brendandburns** [comment]
PR is here for SIG-usability (working name for now)

https://github.com/kubernetes/community/pull/3801

**Comment by spiffxp** [comment]
/close
Charter has merged, SIG has had their first meeting https://www.youtube.com/watch?v=nV4-TF_5loM
