### ISSUE TITLE
Should KEPs be used for process changes?

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#3795]
It was stated during today's contributor experience meeting that KEPs should be used for process changes which was a surprise to me, given that:

- Current KEP documentation seems to avoid mentioning the word process: https://github.com/kubernetes/enhancements#is-my-thing-an-enhancement
- Current KEP documentation seems to frame in terms of user and operator facing changes - https://github.com/kubernetes/enhancements/blob/master/keps/0001-kubernetes-enhancement-proposal-process.md#what-type-of-work-should-be-tracked-by-a-kep
- The Contributor Experience charter doesn't mention the use of KEPs for process changes: https://github.com/kubernetes/community/blob/master/sig-contributor-experience/charter.md#cross-cutting-and-externally-facing-processes
- I've seen major process changes roll out without KEPs including:
  - mandating that everything landing in a release must use a KEP (https://github.com/kubernetes/sig-release/tree/master/releases/release-1.14#what-will-we-do-differently-this-release)
  - the API review process (https://github.com/kubernetes/community/pull/243, https://github.com/kubernetes/community/pull/3261)

/sig pm
/sig contributor experience

FYI @justaugustus @parispittman

**Comment by celanthe** [comment]
Hi @spiffxp and @justaugustus --I am working on contribex issue triage, and wanted to circle back as to the status of this PR. 

If you have any updates as to where it's at in the process, or if it can be closed or frozen, that would be great. 

If this issue needs to be escalated or there is someone else from the PM team I should loop in, please let me know so that I can get this moving again! Thank you so much!

**Comment by celanthe** [comment]
kind/documentation

**Comment by celanthe** [comment]
priority/backlog

**Comment by celanthe** [comment]
priority/awaiting-more-evidence

**Comment by cblecker** [comment]
And update on this @justaugustus ?

**Comment by LappleApple** [comment]
Also following up here—has this been resolved/partly resolved? Or maybe it's referenced elsewhere, in another issue or in docs?

**Comment by LappleApple** [comment]
Update: @mrbobbytables says this is now being discussed in the #Enhancements Slack channel.

**Comment by mrbobbytables** [comment]
In general I do see KEPs being used more for process changes and we probably should update the docs to reflect it. The discussion for adding tooling support for process/policy changes has been started in https://github.com/kubernetes/enhancements/issues/1783.

A recent example of a process change KEP is the [Issue Triage KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-contributor-experience/1553-issue-triage). It was first discussed on a few mailing lists with the KEP being the artifact of those discussions.

**Comment by mrbobbytables** [comment]
I've been thinking about this more, and I think it depends on scope.
The triage workflow one required ALOT of input from many different sources. It was good to go through that to make sure everyone's thoughts were gathered.

Other smaller changes like requiring the passcode for zoom, I wouldn't bother with a full blown KEP for it.

**Comment by justaugustus** [comment]
I think where we landed here was "it depends".
The idea of a `scope` field is being proposed in https://github.com/kubernetes/enhancements/issues/2311.

Let's bring the discussion there, with updated KEP documentation being part of the success criteria for that issue.
/close
