### ISSUE TITLE
SIG Scalability out of date

### ISSUE THREAD

**Issue by tpepper** [kubernetes/community#3798]
The https://github.com/kubernetes/community/blob/master/sig-scalability/README.md mentions weekly meetings but based on the agenda and youtube playlist it seems this is no longer the case, with notes of one meeting perhaps held in 2019 and no videos uploaded since 2017.

**Comment by wojtek-t** [comment]
I was on vacation for last 3 weeks - sorry for delay.

I don't understand the comment about the charter - it has a link:
```
The [charter](charter.md) defines the scope and governance of the Scalability Special Interest Group.
```

**Comment by tpepper** [comment]
> I was on vacation for last 3 weeks - sorry for delay.
> 
> I don't understand the comment about the charter - it has a link:
> 
> ```
> The [charter](charter.md) defines the scope and governance of the Scalability Special Interest Group.
> ```

My turn to have been on vacation, apologies for delay on my side now.  I don't know what I was seeing anymore either.  I could swear I'd hit a non-link "charter" text, but clearly it is a link
and the git history shows it has been for quite some time.

I'll amend my issue description to remove that.

**Comment by cblecker** [comment]
/remove-help

This should be handled by the sig-scheduling leads.

**Comment by wojtek-t** [comment]
This should be fixed now - readme is up-to-date, notes are being regularly updated.

/close
