### ISSUE TITLE
Document how to run kubemark against a pre-existing cluster

### ISSUE THREAD

**Issue by jpeach** [kubernetes/community#3809]
Kubemark has support for running against a pre-existing cluster, see kubernetes/kubernetes#44394. The pre-existing cluster configuration is not mentioned at all in the [kubemark guide](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-scalability/kubemark-guide.md#starting-a-kubemark-cluster)

There is some [minimal documentation](https://raw.githubusercontent.com/kubernetes/kubernetes/master/test/kubemark/pre-existing/README.md), but this doesn't contain the steps you need to follow to get kubemark to work, or references to other documentation that would help.

I haven't been able to get this working yet, but I already ran into the following problems:
* `cluster/kubemark/pre-existing/config-default.sh` doesn't define the `+ENABLE_KUBEMARK_CLUSTER_AUTOSCALER` variable
* `cluster/pre-existing/util.sh` doesn't define the `detect-master` function
* `hack/ginkgo-e2e.sh` searches for ginkgo in Bazel output directories, not in `$PATH`
* `test/kubemark/run-e2e-tests.sh` should check the `ARGS` count with `${#ARGS[@]}` (might be a regression in kubernetes/kubernetes#73746)

I can get the scripts to the point of wanting to run ginkgo with the following invocation:
```
$ MASTER_NAME=jpeach MASTER_IP=192.168.99.121 PROJECT=jpeach CLOUD_PROVIDER=pre-existing  ./test/kubemark/run-e2e-tests.sh
```

None of the necessary environment variables are mentioned in the kubemark guide, so I filled them in by poking at the scripts.

**Comment by snowplayfire** [comment]
I have recorded how to setup a kubemark cluster against pre-existing cluster as follows: 

https://github.com/snowplayfire/kubemark-outside-gce

Hope it is helpful for you.

**Comment by markyjackson-taulia** [comment]
/remove-lifecycle rotten

@jpeach Does the recording that @snowplayfire created suffice? If so, is it ok to close this issue?
Thanks kindly.

**Comment by markyjackson-taulia** [comment]
Closing this. Video recording is listed above.
/close
