### ISSUE TITLE
REQUEST: New Slack Invite

### ISSUE THREAD

**Issue by seenickcode** [kubernetes/community#3815]
Hello, I noticed a link to the Slack workspace in this repo and would like an invite to the kubernetes.slack.com. I didn't see a way to request an invite. 

My email is nicholas.manning@gmail.com 

Thanks in advance.

**Comment by mrbobbytables** [comment]
Hey there @seenickcode - No invite is needed :) You can join slack through this link: http://slack.k8s.io

I'm going to go ahead and close this issue, but if you have any other questions feel free to follow-up.

Thanks!

/close
