### ISSUE TITLE
REQUEST: New private Slack channel (release-managers-private)

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/community#3824]
**GitHub Username:**
SIG Release Chairs: @calebamiles @justaugustus @tpepper 

**Slack Username:**
SIG Release Chairs: @calebamiles @justaugustus @tpepper 

**What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?**

**Name of Requested Resource:**
Private channel: #release-managers-private (or some equivalent appropriate naming for a private channel)

**Description of Request:**
Release Managers will on occasion need to coordinate Kubernetes releases in private e.g., when addressing a CVE. This will provide a communications channel that is not a flurry of direct messages.

ref: https://kubernetes.slack.com/archives/C4M06S5HS/p1561061184030500

/sig release
/area release-eng
/committee product-security
/cc @tpepper @calebamiles @kubernetes/patch-release-team @kubernetes/release-managers @Katharine @jeefy

**Comment by mrbobbytables** [comment]
+1'ing as another slack admin
