### ISSUE TITLE
New Contributor Workshop San Diego Content Proposal

### ISSUE THREAD

**Issue by guineveresaenger** [kubernetes/community#3835]
The [content proposal for NCW San Diego](https://docs.google.com/document/d/1ha3KtgLcRIY7IaRi9pm_h28xVsx9VoVLu8Fl1YO-eCI/edit#) is now live!

Please comment and discuss. Links have been sent out to the New Contributor Content Team by email.

Part of #3792.

**Comment by guineveresaenger** [comment]
Argh.
/sig contributor-experience
/area na-summit
/cc @raelga 
/cc @alisondy
/cc @geekygirldawn

**Comment by markyjackson-taulia** [comment]
@guineveresaenger Is it possible to volunteer to help here?

**Comment by guineveresaenger** [comment]
@markyjackson-taulia yes! Some things we're currently working on:

- updating the slide deck; specifically we're hoping to add some tie-ins for the codebase walkthrough. I'f you're good at making diagrams, this would be a place that has lots of work!

- I'm tossing around the idea of having a complete PR walkthrough demo as the workshop opener to hook people's interest and create better context for any questions they may have.

**Comment by guineveresaenger** [comment]
issue for slides: #3919

**Comment by mrbobbytables** [comment]
The SD event is over~ going to go ahead and close out this issue :)
/close
