### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by rickducott** [kubernetes/community#3857]
There were some broken links on this page: https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/#specify-multiple-versions

The links reference this repo: 
https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md
https://github.com/kubernetes/community/blob/master/contributors/devel/api_changes.md

**Comment by geekygirldawn** [comment]
It looks like these 2 files have been moved to: 

https://github.com/kubernetes/community/tree/master/contributors/devel/sig-architecture

I'm working on a pull request now for this change.

/assign @geekygirldawn

**Comment by nikhita** [comment]
https://github.com/kubernetes/website/pull/15220 has merged. Thanks for fixing this, Dawn! :)
