### ISSUE TITLE
Contributor Summit - SD Website Requirements 

### ISSUE THREAD

**Issue by JamieRachel** [kubernetes/community#3865]
This will track content and registration. 

**Shell site:** https://events.linuxfoundation.org/events/contributor-summit-north-america-2019/

Task: 

- [ ] Update venue information (contract needs to be signed)

- [ ] Detail/identify the process of ownership of pre-registration information (deb at cncf has this; will download and send emails once we are live)

- [ ] Put up skeleton copy of track descriptions  - What are the tracks? (next mtg: 7/22; use sched template per bob)

- [ ] Sort out registration process to implement on site #3837 

- [ ] Create clear registration instructions (jonas to own)

- [ ] put get in touch with us info on the site

**Comment by parispittman** [comment]
pre-reg data = cncf has it (ask deb)

venue needs to have contract in place before putting on the main site 

mid-august track descriptions look amazing by then

**Comment by JamieRachel** [comment]
[Contributor Summit Co-located Event Link](https://events.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2019/co-located-events/#kubernetes-contributor-summit)

**Comment by debgiles** [comment]
@jonasrosland To help ensure we have all of the correct information when launching websites and our team can easily build them, I've created a website framework for you and team to complete with information.  The goal is to make this something that we can use as a framework for all future websites too, so please make comments/edits/suggestions throughout the doc as your completing it, to make it successful as a template moving forward.  Let me know if you'd like to chat through it together at all.

https://docs.google.com/document/d/1mulfto6GpXogbQYmAoY9EGh5NOsfXUopRylivMdIcFg/edit?usp=sharing

**Comment by jonasrosland** [comment]
Thank you @debgiles! I'll work on this during the week.

**Comment by jeefy** [comment]
Venue is already locked in, check that! :)

Now that the site is live, what's the turn around for the emails from Deb? :) 

Also: Should working out on-prem reg details be part of the Website Requirements issue? 🤔

**Comment by debgiles** [comment]
Email to those that showed an interest prior to the site going live is going out today!

I think the reg info referred to the website, so that can be checked off too.  I think everything here has been completed and is live on the website!

**Comment by jeefy** [comment]
Website is up!

/close
