### ISSUE TITLE
Contributor Summit SD - Registration Mechanism 

### ISSUE THREAD

**Issue by JamieRachel** [kubernetes/community#3866]
This issue will track discussion and process of the tiered pre-registration system. as referenced in umbrella issue #3837

Task: 
 
- [ ] Create a registration code of local, underrepresented groups for NCW 

- [ ] Create a roll out plan for code launch - include dates and membership role 

To do:
Add more task for details

**Comment by parispittman** [comment]
75 chairs/tls block (codes needed)

100-125 sep reg for ncw

total capacity for reg = 275

**Comment by parispittman** [comment]
~mid-aug 31 - soft website launch with codes
sept 5 - general website is up

**Comment by parispittman** [comment]
will need codes for contributors who are not attending kubecon either so we have a way to handle those transactions

**Comment by tashimi** [comment]
Women in tech in San Diego groups: https://www.meetup.com/topics/witi/us/ca/san_diego/ 
Out Entrepreneurs group: https://www.meetup.com/San-Diego-LGBT-Entrepreneurs-Investors-And-Allies/ 
Blacks in Technology meetup: https://www.meetup.com/BITSanDiego/

**Comment by mrbobbytables** [comment]
> * Create a registration code of local, underrepresented groups for NCW

Unfortunately cvent does not support registration codes to come out of a central "pool" for attendees to specific events. They require a different reg flow. It will be a "clone" of the NCW flow that will be used as an alternative. 

> * Create a roll out plan for code launch - include dates and membership role

The current rollout plan is as follows, but may see further update:
* August 28th
  * **Active Contributor** - Registration will be "soft launched" for SIG/WG Chairs and Tech Leads by giving them the link for Active Contributor Registration early. Registrations will still be verified by the the normal approval process.

* September 4th
  * **Active Contributor** - Registration will be opened to Kubernetes Org members and sponsored attendees.
  * **New Contributor** - Registration will be opened for both Diversity & Outreach + General attendance.

* October 28th
  * **New Contributor** - Remaining Diversity & Outreach attendee slots will go back to the General attendee pool.
  * **Active Contributor** - Registration will be opened for general admittance. Attendees must still be involved in the upstream project and will be verified by the normal approval process.

**Comment by mrbobbytables** [comment]
Here is the current registration number breakdown:

Total: 515
Total - estimated no shows: 450
- New Contributor (165)
  - Beginner (70)
    - No-show (20)
    - Diversity & Outreach (30)
    - General Admittance (20)
  - Intermediate (95)
    - No-show (20)
    - Diversity & Outreach (20)
    - General Admittance (55)
- Active Contributor (325)
  - No-show (25)
  - General Admittance (300)
- Staff (25)

**Comment by tashimi** [comment]
Created a form to gather attendees to send code to: https://forms.gle/m8rjYQLHqdu48smz9 
Outreach: 
- tweeted and requested signal boost
- reached out to meetup groups above
- will email to kubedev

**Comment by jeefy** [comment]
Are we doing any sort of registration codes? AFAIK we aren't (@mrbobbytables didn't think so either) so, is this considered completed?

**Comment by tashimi** [comment]
I've got the dedicated link I need for the accessibility drive, so I am good.

**Comment by mrbobbytables** [comment]
Unless we want to leave this open till the last reg phase change (October 28th) I think this issue can be closed. 👍 

We have the separate reg links for the different paths and the phased rollout is in effect. \o/

**Comment by jeefy** [comment]
Reg is opened!

/close
