### ISSUE TITLE
Contributor Summit SD - Awards  

### ISSUE THREAD

**Issue by JamieRachel** [kubernetes/community#3867]
This issue is to track the discussion and progress

Reference **[best practices](https://github.com/kubernetes/community/blob/master/events/events-team/best-practices.md#contributor-awards)**: 

- [x]  codify this,

- [x]  determine what awards

- [x]  process for nominations

**Comment by jberkus** [comment]
I will be raising the possibility of Release Team/RE awards in SIG-Release.

**Comment by parispittman** [comment]
simple nom form? small committee that sees noms. per: dawn

**Comment by parispittman** [comment]
surprise or not surprise, that is the question. :)

discussion around: knowing its happening but not knowing the winners

**Comment by geekygirldawn** [comment]
Some ideas from the UK open source awards:

* [Gathering nominations](https://opensourceawards.org/2019/04/25/the-uk-open-source-awards-is-back/)
* [Announcing the shortlist](https://opensourceawards.org/2019/05/22/uk-open-source-awards-shortlist-announced%ef%bb%bf/)

**Comment by parispittman** [comment]
nominations by contributors for most approachable/"mentoring"/helpful

go through labels (code cleanup, triage, etc) (our chop wood and carry water)

**Comment by detiber** [comment]
I can see potentially having both community-wide awards as well as per-sig awards. The per-sig awards might allow for recognizing people's contributions that are invaluable to a SIG, but may not be visible to the wider community.

What are the limitations? Is there a particular budget and/or limitations of time for presenting the awards? Or does that still need to be scoped?

**Comment by jberkus** [comment]
The main limitation is that we don't want an hour-long awards ceremony.  So we really want to limit it to 6-7 awards.

Hey, thought: what if we did the awards during the social?  @alisondy ?

**Comment by alisondy** [comment]
Would be great to have awards at the social. Only other thing I could think of would be needing some rough schedule for social so that folks know when things are happening throughout the evening.

**Comment by detiber** [comment]
The only downside to doing the awards at the social could potentially be that not all recipients may be in attendance. Of course not all awardees might not be at the Contrib Summit, but due to travel plans and/or the contributor's desire to participate in the social there would probably be a greater chance of attendance at the Contrib Summit proper.

**Comment by mrbobbytables** [comment]
I would definitely lean towards having it during the actual Contributor Summit. For both Seattle and Barcelona lots of folk weren't able to make the social due to travel interruptions etc.

**Comment by parispittman** [comment]
i think contributor summit proper is the best place for awards if we are looking to spotlight folks. 

we didn't ask for budget for this but based on savings in other areas that we will probably see - I'd say under 3k total.

last year we did the kubernetes logo framed in code from kubernetes/kubernetes

**Comment by jberkus** [comment]
Note, both @coderanger and I are available for award trophy sourcing.

**Comment by jeefy** [comment]
Have we started reaching out to SIGs regarding awards? This is something we should try and have wrapped up by the end of the month so there's time for trophy orders.

**Comment by parispittman** [comment]
tim and claire have completed this journey ✨
