### ISSUE TITLE
Contributor Summit SD - Create a content proposal

### ISSUE THREAD

**Issue by JamieRachel** [kubernetes/community#3869]
[WIP Content Proposal](https://docs.google.com/document/d/1pXCjKcBMZByBIOLTDT9A5br3kyJ1Ray3eSf0aLXzU_Y/edit)

- [ ] Contributor Summit NA San Diego 2019 Content Proposal to be drafted (new contributor workshop can be found separately in #3835)

- [x] Content Proposal to be reviewed, discussed with SIG chairs, tech leads and the Contributor Summit team

- [x] Send to steering committee for review & target date July 15th

**Comment by parispittman** [comment]
update - sent to steering july 22nd for comments

**Comment by parispittman** [comment]
Goals
Have content that is interesting for all contributor personas (see Expectations for details)
Create a space where people can work and have extended hallway track
Assist new and current contributors with their onboarding paths
Focus on sustainability and education topics 
Include a track or multiple sessions that will be driven by the contributors (unconference)

Facts and content planning methodology
Survey results for Seattle, Barcelona, and all other previous events
Content comes directly from past surveys, asking directly on registration forms, brainstorming with contributor summit team, known community issues/gaps/improvement areas, steering committee meetings, and mailing lists. 
SIGs/WGs have updates/deep dives during tracks at KubeCon. We will encourage attendance here and include on the main contributor summit schedule. No rooms reserved for SIG meetings at this event (unless they would like to self-organize).
Contributors having their voices heard and working on problems they want to solve is still important to us
Continue to ask the value prop question on the reg form
NCW content has been iterated over by experts within the community roughly 4 times now

**Comment by parispittman** [comment]
Timeline For Content

July 20th: determine tracks/rooms
August 6th: send out solicitation for preplanned content
September 10th: close proposals for preplanned content
September 24th: finish selecting sessions
October 1st: publish draft schedule
October 15th: finalize schedule
Expectations
450 people 
~50 new; 75 intermediate NCW will be a separate registration process
Graduate 100+ into the community 
~350 current contributors (largest event to date)
Contributor registration goes live in the first week of September
Block of 75 saved for Chairs, TLs, and subproject owners 
Code blocks go live in mid-August as a soft launch of the registration process/website
Something there for everyone: 
Current contributors
Sig chairs/leads
Approvers, reviewers
Vets (4+ years)
Docs 
New Contributors
https://github.com/kubernetes/community/issues/3835
How to get started fka “101”
Building, testing, and gh workflows fka “201”

**Comment by parispittman** [comment]
Monday, Nov 18th

A mix of workshops, unconference, pre-planned topics and discussion sessions, and other multimedia adventures.

Room proposal

2 rooms for new contributor workshop activities, sig meet and greet, etc. https://github.com/kubernetes/community/issues/3835
Previous 101 and 201 workshops are being re-worked to How to Get Started (101) and Building, testing, and GH Workflows (201)
Some “201” content will be ad hoc this time; any contributor onsite can join and not solely those who signed up for it
SIG Meet and Greet is going to focus on linking people up with actual work vs letting them play on their own and open to current contributors, too for a ‘bring your PR’ for review. We’ve noted that if folks walk out confused as to where they will add value, they will not participate in the future. We are opening this to current contributors, too, so they can get involved with new SIGs or open the floor for communication.https://github.com/kubernetes/community/issues/3896
Round tables setup; recorded 

1 main room (listening and q&a)
host morning welcome, afternoon wind down, and other sessions that we believe will have more than 100 people attending
Ideas: year of changes in API review, what’s ahead, API live PR review, live coding
Sourcing content from: reg form question, steering, contribex, feedback from chairs
Theater setup; 
Recording: yes

1 unconference room (listening, participating, q&a) https://github.com/kubernetes/community/issues/3894
This has been reduced from previous events based on feedback; people still want their voice heard (and we do, too) though.
Topics and voting will happen on Sunday night only. TBU on logistics.
Discussion/fishbowl setup; 
Recording: not recorded

1 current contributor workshop room (listening, participating, q&a)
3 hour block for a doc sprint - tbd 
Other ideas: interactive chair training, writing better tests, writing KEPs, etc
Round Tables Setup
Recording: possibly recorded depending on the interactiveness of the workshops

1 technical discussions (listening and participating) 
Sourcing content from: reg form question, xx
Ideas: release engineering, test infra, etc. 
Fishbowl; 
Recording: not recorded unless we get project decision discussion

1 sustainability topics room 
Ideas: building roles, mentoring how tos, retaining contributors, stories/BPs/what works from sigs, how to work with other timezones, etc
Sourcing content from: experts/chairs/contributors, steering, contribex
Discussion/fishbowl setup; 
Recording: yes

**Comment by jeefy** [comment]
At this point we do have proposals set up for [Sunday](https://github.com/kubernetes/community/issues/3893) and [Monday](https://github.com/kubernetes/community/issues/3893)

Please re-open if I'm incorrect in that assertion. :)
