### ISSUE TITLE
Contributor Summit SD - Project Management

### ISSUE THREAD

**Issue by hpandeycodeit** [kubernetes/community#3879]
This Issue is to track/list down all the project management activities that can be referred to in future summits as well. 

[Best Practices](https://github.com/kubernetes/community/blob/master/events/events-team/best-practices.md#project-management): 

Each event will have a project board created. The incoming team will need to create a label area/regionfor-summit and any issue or PR related to all summits will have the label area/contributor-summit.

The event team can decide if they want a dedicated project manager role at the time of planning.

To Do:

- [ ] Add More Project Management related Tasks 
- [ ] Update Best Practices section as we proceed
- [ ] Assign Labels and track the ongoing issues
- [ ] Mark Already completed issues as resolved
- [ ] Create a meeting format
- [ ] Avoid duplicate issues and if there is an umbrella issue, the related issues should have a reference to it. 
- [ ] Weekly Project Board Triage

**Comment by JamieRachel** [comment]
[ ] Create a meeting format

**Comment by mrbobbytables** [comment]
NA Summit has completed -- going to go ahead and close this issue.
/close
