### ISSUE TITLE
REQUEST: New moderator for nzoueidi of Zoom and Youtube

### ISSUE THREAD

**Issue by nzoueidi** [kubernetes/community#3889]
### GitHub Username
@nzoueidi 

### Property you'd like to Moderate
Zoom, Youtube

### Username on Property Requested
nzoueidi

### Requirements

- [x] I am a Kubernetes Org member already
- [x] I have enabled 2FA on my account for the property I would like to moderate (if applicable).
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @parispittman 
- @castrojo 

### List of qualifications for this position

- Part of the Ubuntu Board Membership which is a team that do meetings in order to approve new Ubuntu members. (https://launchpad.net/~ubuntu-membership-board/+members#active).
- Moderator of the mailing list of ubuntu-board-membership https://lists.ubuntu.com/mailman/private/ubuntu-membership-boards/
- Founder and organizer of Kubernetes and Cloud Native Tunisia meetup group< (https://www.meetup.com/Kubernetes-Cloud-Native-Tunisia/).
- Kubernetes coordinator.

**Comment by parispittman** [comment]
+1! Excited to have you.

assigning some other admins for a lgtm and approve.

**Comment by alejandrox1** [comment]
+1 
🎉

**Comment by idvoretskyi** [comment]
+1

**Comment by alejandrox1** [comment]
coming back this (please forgive the delay :sweat_smile: )... @nzoueidi could you PR yourself to the appropiate places in https://github.com/kubernetes/community/blob/master/communication/moderators.md ?
