### ISSUE TITLE
Contributor Summit SD: Sunday Night Celebration

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3893]
umbrella issue collecting the following:

- [x] select venue (cncf to sign on contracts) Lead: Deb/me: quartyard
- [x] update website with venue info (times and other pertinent info) Lead: Deb/Bob
- [x] decide on activities (team to decide together): contributor bingo, karaoke
- [x] create welcome bingo / new contributor welcome activities. Lead: Alison #3914 
- [x] slide show or other medium for monday need to know info. Lead: Jonas with Rael helping (will potentially break into another issue; ref here)
- [x] possible talent show and/or contributor entertainment from gophercon inspiration 

Goals: 
Extended “hallway track” (aka folks want to hang out and small talk kubernetes; the #1 reason why people attend) 
Welcome committee for new contributors; guided socialization for new contributors
Another checkpoint for need to know info for Monday
Celebrate contributors 

Why/Impact
Contributors want more time together. With a full week ahead of us, there isn’t enough time to do other dedicated contributor events so this Sunday night event helps with that. Meeting folks before the event is also helpful to make new people and go with them during the week.  

This night doesn’t compete with Monday night which has empowerUS and other events that would conflict.

**Comment by parispittman** [comment]
suggestions from alison for bingo card from content proposal doc:
Have a bingo card, for meeting people, You have to get their signature, and fill out the card, squares like 'A member of the 1.15 release team', 'A person who has a kep'

**Comment by parispittman** [comment]
update - walk thru for two venues complete

**Comment by parispittman** [comment]
sunday activities: unconference suggesting and voting, possible talent show of sorts

**Comment by parispittman** [comment]
include sig intro and deep dive schedule on the presentation and info about the event including a description of what folks can expect. we will also cover these in the monday morning intro. 

preserved comment from the original proposal doc from clayton:
One thing that is interesting is that we lack the "summarize all sigs priorities" event - since sigs go during the week but this happens on Monday it's obviously hard. should sigs summarize why you should attend their tracks with 1-2 bullet points and the contributor summit have a time for those to be read out / discussed? Or maybe something meta like "why you should attend sig track during kubecon" pitches in written / slide form that is available but not discussed?

**Comment by jeefy** [comment]
Updates ping

@parispittman Can check off venue and website updates (first two)

@alisondy Can you status update us on the Bingo-ey Goodness? 

@jonasrosland We should start thinking about the info presentation when you get back. ;)

**Comment by raelga** [comment]
@jeefy the info deck is [here](https://drive.google.com/file/d/1OFGJ2kTV_2KsBMmA4aM3j_JU2OQLxb0C/view)

**Comment by raelga** [comment]
@parispittman The issue for the info slides is https://github.com/kubernetes/community/issues/4069

**Comment by parispittman** [comment]
need to get final confirmation on gopher band, get slides going, and some other finishing touches.

**Comment by mrbobbytables** [comment]
Sunday info slides are here: 
[Kubernetes Contributor Summit - San Diego 2019 - Sunday Info Slides](https://docs.google.com/presentation/d/1OFGJ2kTV_2KsBMmA4aM3j_JU2OQLxb0C/edit#slide=id.p1)

We had a karaoke, dogs, games, bingo and more there 👍 

With the event over, I'm going to go ahead and close this out.

Thanks!

/close
