### ISSUE TITLE
Contributor Summit SD - SIG Meet and Greet

### ISSUE THREAD

**Issue by geekygirldawn** [kubernetes/community#3896]
This issue is to track the discussion and progress toward organizing the SIG Meet and Greet.

**What is the SIG Meet and Greet?**

The SIG Meet and Greet is a great place for SIGs and WGs to recruit contributors, and every SIG / WG is being asked to send one or more experienced members to the Meet and Greet to represent your group. Representatives should complete this [Google Form](https://forms.gle/hxx1qz8XtwtXEBMm8) to help us track who will be attending for each SIG / WG. These representatives are expected to arrive 15 minutes before the SIG Meet & Greet and stay for the duration. We don't have the exact timing for the SIG Meet and Greet, but it will be during the Contributor Summit at 5pm on Monday, November 18.

As part of the Contributor Summit SIG Meet and Greet, SIGs and WGs will have easy access to:
* experienced Kubernetes contributors who are interested in expanding their involvement into new SIGs / WGs.
* new contributors, many of whom have extensive experience from other projects, and are excited to get started in Kubernetes after attending a New Contributor Workshop.

**Organizing Details**

More details in the [SIG Contributor Events organizing doc](https://github.com/kubernetes/community/blob/master/events/events-team/content/sig-contrib-events.md) for best practices:

- [x] Create [Google Form](https://forms.gle/hxx1qz8XtwtXEBMm8) to collect representative details.
- [x] Send Google form in chairs email.
- [x] SIG Representatives Identified: Follow up with each SIG until we have the names of 1 or more experienced members who will represent the SIG at the Meet and Greet. 
- [x] Calendar: Add these representatives to a calendar notice for the SIG Meet and Greet.
- [x] Stands and Buttons: Make sure that we have table stands and buttons for each SIG. Come up with a process that makes it easy to hand them out at the beginning of the event.
- [x] Volunteers: Recruit a few volunteers to distribute table stands and buttons and to help SIGs / contributors find the right tables.

**Tracking SIG Reps**

SIGs:
 *  API Machinery - @lavalamp 
 *  Apps - @prydonius 
 *  Architecture - @liggitt 
 *  Auth - @enj 
 *  Autoscaling - @vivekbagade 
 *  CLI - @seans3 
 *  Cloud Provider - @spzala (IBM), @adisky (OpenStack), @craiglpeters (Azure), @cheftako 
 *  Cluster Lifecycle - @vincepri (Cluster API), @ant31 (Kubespray), @detiber (Cluster API, Kubeadm), @timothysc 
 *  Contributor Experience - @Phillels 
 *  Docs - @thecrudge, @zacharysarah, @jimangel, @mhamdisemah 
 *  Instrumentation - @ehashman 
 *  Multicluster - @pmorie 
 *  Network - @bowei 
 *  Node - @yujuhong @dashpole 
 *  PM - @calebamiles 
 *  Release - @tpepper & @kacole2 
 *  Scalability - @mm4tt 
 *  Scheduling - @Huang-Wei 
 *  Service Catalog - @jberkhahn & @mszostok 
 *  Storage - @saad-ali 
 *  Testing - Need rep
 *  UI - @jeefy 
 *  Usability - @hpandeycodeit, @vllry
 *  Windows - @PatrickLang, @michmike, & @ddebroy 

WGs:
 *  Apply - @fedebongio
 *  Component Standard - @stealthybox & @mtaufen 
 *  IoT Edge - @cantbewong 
 *  K8s Infra - @dims 
 *  LTS - @youngnick 
 *  Machine Learning - Being disbanded
 *  Multitenancy - @tashimi 
 *  Policy - @ericavonb
 *  Resource Management - @ConnorDoyle 
 *  Security Audit - @aasmall

**Comment by geekygirldawn** [comment]
@guineveresaenger @parispittman I realized we never created an issue to track the SIG Meet & Greet, so here it is :)

Also, I can't seem to figure out how add it to the Contrib Summit project board, so if someone could do that (or tell me how), I'd appreciate it.

**Comment by parispittman** [comment]
chairs email in mid august will include a 'how to get involved' with sig meet and greet

**Comment by debgiles** [comment]
@geekygirldawn Stands and buttons are on our ordering list.  I'll be creating "SIG Kits" that can be picked up outside of each room.  In the kit will include that SIG's stand with tablecard and buttons, so the lead can pick up the kit on the way in the room and then leave the kit on the table on the way out or return it to the table outside the room.  This will hopefully make the process much quicker/smoother than Barcelona was.  If there are additional things that need to be added to the kits, let me know!

**Comment by geekygirldawn** [comment]
/assign @detiber 

I've recruited @detiber to work with me on organizing the SIG Meet & Greet. It's worth noting that I will be on holiday and not checking email the 2 weeks before KubeCon, so I wanted to have someone else involved from the start.

We're working on a form to capture the details for the representative from each SIG, which should be ready to go out in the next few days. The SIG chairs email is probably a good place to send this out as a start. @parispittman - when do you need this if I want it to go out in the August chairs email?

Here's a [draft of the form](https://forms.gle/vNmg9SaXSvCmJwrz8) if people have any feedback for us.

**Comment by jonasrosland** [comment]
This looks great @geekygirldawn!
The description is spot on I'd say, and will be great to use on the event site.

I can't access the form unfortunately, "This form can only be viewed by users in the owner's organization."

**Comment by geekygirldawn** [comment]
> I can't access the form unfortunately, "This form can only be viewed by users in the owner's organization."

This should be fixed now.

**Comment by jonasrosland** [comment]
Thanks! The form looks great 👍

**Comment by parispittman** [comment]
thanks dawn!

**Comment by jeefy** [comment]
@parispittman We should link directly to the form in the next Chair/TL Need-To-Know. Less clicks might help with engagement. I also think if we lack any SIG reps by October, we should reach out. Thoughts?

**Comment by geekygirldawn** [comment]
@jeefy we're way ahead of you :) @detiber and I got together this week to divvy up the SIGs/WGs to follow up with them. We're going to start the following up process now, since we want to get the SIG M&G on people's calendars before they commit to anything else!

@parispittman Agree that linking directly to the form is probably best.

**Comment by parispittman** [comment]
i think we are good to close this one 🚀 what do you think?

**Comment by geekygirldawn** [comment]
We're still using this issue to track last minute changes - people who said they would represent their SIG, but who can't make it now for a variety of reasons. 🙄 We also still need to finish up some of the remaining tasks, like sending out the meeting request 😄

**Comment by detiber** [comment]
As of today (28 October), all current volunteer representatives are registered for the Contributor summit and an event reminder has been sent to all volunteers.

**Comment by detiber** [comment]
@chris-short thanks, I think the biggest thing we'd need right now is help with day of awareness

**Comment by detiber** [comment]
Discussed how to distribute the SIG cards and buttons, since we don't necessarily know offhand how much space each SIG will need, discussed having them available for pickup by the entrance to the room to allow for SIG/WG reps to pick up when entering and move to an area based on how much room they feel they'll need.

**Comment by geekygirldawn** [comment]
We had a great SIG M&G, but now we're done 😃
