### ISSUE TITLE
REQUEST: Kubernetes slack `incoming webhook` URL

### ISSUE THREAD

**Issue by hongkailiu** [kubernetes/community#3902]
**GitHub Username:**
@hongkailiu @stevekuznetsov 

**Slack Username:**
@hongkailiu @stevekuznetsov 

**What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?**

We need slack [incoming-webhooks URL](https://api.slack.com/incoming-webhooks) to set up `alertmanager` of [prow-monitoring stack](https://github.com/kubernetes/test-infra/blob/master/prow/cluster/monitoring/alertmanager-prow_secret.yaml#L24).

**Name of Requested Resource:**

**Description of Request:**

When we get the URL, we will do `kubectl apply -f` using [the secret file](https://github.com/kubernetes/test-infra/blob/a3c842850be5c9c8681d38ce52c03163e2d918ca/prow/cluster/monitoring/alertmanager-prow_secret.yaml).

**Comment by Katharine** [comment]
Putting on my sig-testing hat:

We want to create a slack app that has an incoming webhook, for the purpose of being able to send alerts about the health of prow. Contrary to the documentation and purpose of incoming webhooks, the slack app will be theoretically capable of sending to _any_ channel. In practice, however, it will not.

The only scope used is the webhook, which is strictly write-only, so the token cannot be used to retrieve information about anything in Slack. It will live in the prow cluster, which also contains other far greater secrets.

Putting on my slack admin hat:

This seems reasonable to me — the code is open source (though not actually written by us), is running in a sig-testing cluster, and serves an obviously useful purpose, so +1 from me.

**Comment by jeefy** [comment]
+1

**Comment by Katharine** [comment]
I've created the integration and added the webhook URL secret into the prow cluster.

/close

**Comment by mrbobbytables** [comment]
Thanks @Katharine :)

/pony yay
