### ISSUE TITLE
Contributor Summit SD - Marketing Timelines

### ISSUE THREAD

**Issue by hpandeycodeit** [kubernetes/community#3911]
Documenting the timelines as per the discussion: 

- [x] Send [Steering Committee Proposal Email](https://github.com/kubernetes/community/issues/3835)
- [x] Send [SIG Chair/TL Proposal Email ](https://github.com/kubernetes/community/issues/3835)
- [x] Sent out a tweet to get people signed up - **By Mid July**
- [x] Add ContribSummit to main KubeCon site - **July**
- [x] wordings finalization for 101 and 201 workshops - **Aug 1st week**
- [x] Sent out a second tweet to get people signed up - **By Mid August**
- [x] Website complition draft - **By Eng of August**
- [x] Completion of kickoff blog draft -  **September first week**
- [x] Kickoff  k-dev , Twitter and [discuss.k8s.io](discuss.k8s.io) - **By Mid September**

**Comment by jeefy** [comment]
The Chair/TL proposal email was sent out by @parispittman on Aug 26th so you can safely check that.

I imagine @parispittman will send a reminder email with the same content in the next Chair/TL Need to know. :)

**Comment by jeefy** [comment]
Pressed enter too early. Oops!

Did these get done? 
> wordings finalization for 101 and 201 workshops - Aug 1st week
> Sent out a second tweet to get people signed up - By Mid August

Because at this point 
> Website complition draft - By Eng of August

Should be done, as the website/reg is live. Am I missing something there? :)

**Comment by jeefy** [comment]
Per @jonasrosland all of these are done! :tada: 

/close

**Comment by jonasrosland** [comment]
@hpandeycodeit Can you please add these to the list, as unchecked?
- Publish blog post with the schedule and descriptions
- Send out schedule and registration numbers to k-dev
- Tweet about the scheduled
- Once the NCW registration reopens, tweet about that

**Comment by mrbobbytables** [comment]
With the event over, I think it's safe to close this issue out. The remaining items that need to be completed can be found in the event wrap up issue (https://github.com/kubernetes/community/issues/4280).

Thanks all!

/close
