### ISSUE TITLE
Contributor Summit SD - Bingo Cards for Sunday Night Celebration

### ISSUE THREAD

**Issue by alisondy** [kubernetes/community#3914]
As discussed in the content proposal document, We would like to have a game to get folks to  know one another.

See parent issue #3893 

todo:
- [x] Get Questions for cards
- [x] Submit by October 18th
- [x] Organize Prizes

Could alternatively make a webapp.

**Comment by debgiles** [comment]
@alisondy - We can print these for you.  Would you also like us to design them?  If so, you would just have to provide us with the list of questions and we can create 10 different card options that mix the bingo's around.

If you'd like our creative team to design them, deadline for the list of questions/squares would be October 18.
If we're just printing, deadline for files is November 1.

**Comment by alisondy** [comment]
Some questions
A Sig Chair
Someone who has an Open KEP
Someone who is attending Kubecon for the first time
A member of ______ sig
Someone on the current release team
Someone who has previously been on the release team
Someone who is on the contributor summit team
Someone who is a member of the Kubernetes org

**Comment by jberkus** [comment]
Any thoughts on what *kind* of prizes we might want?

**Comment by markyjackson-taulia** [comment]
Stickers pack?

**Comment by alisondy** [comment]
I expanded on the list, some things are a bit repetitive, thank you @jberkus for the suggestions, I've added them and a couple more to the list below

1. ... is a Sig Chair of _fill in the blank___ sig
2. ... has an Open KEP
3. ... is attending Kubecon for the first time
4. ... is a member of ___fill in the blank___ sig
5. ... is on the current release team
6. ... has previously been on the release team
7. ... is on the contributor summit team
8. ... is a member of the Kubernetes org
9. … has an open (Kubernetes) PR
10. ... has been to 3+ contributor summits
11. ... is at their first contributor summit
12. ... is running a session at the summit tomorrow
13. ... has used Kubernetes before 1.0
14. ... came from more than 1000km away
15. ... came from more than 5000km away
16. ... came from more than 10,000km away
17. ... is a musician
18. ... is into cooking
19. ... makes visual art
20. ... has pictures of food on their phone
21. ... has pictures of their cat on their phone
22. ... has pictures of their dog on their phone
23. ... has pictures of their kid(s) on their phone
24. ... does a sport  (Write sport here)
25. free space

Any feedback would be great thankyou 🙏

**Comment by jeefy** [comment]
Everyone on the 09/30 call to review and propose/+1 by EOW. :)

**Comment by markyjackson-taulia** [comment]
+1 for the newly expended items.
I really love this idea @alisondy and I think people are going to really have fun with this

**Comment by mrbobbytables** [comment]
Bingo went well, and it was a good ice breaker for new folk. ❤️ 

With the event now over, I'm going to go ahead and close out this issue.

Thanks @alisondy :D

/close
