### ISSUE TITLE
Contributor Summit SD -  Create New Contributor Workshops slides

### ISSUE THREAD

**Issue by raelga** [kubernetes/community#3919]
Following content discussed in:

- [Contributor Summit SD - Create a content proposal #3869](https://github.com/kubernetes/community/issues/3869)
- [New Contributor Workshop San Diego Content Proposal #3835
](https://github.com/kubernetes/community/issues/3835)

Proposal for the decks content:

### NCW 101 deck

- [x] Brief k/k overview
- [x] Setting Up Your Development Environment: Prerequisites, Check-In, Assistance
- [x] SIGs, Labels, Issues: Overview
- [x] Open Source Interactions
- [x] PRs and Bots
- [x] Playground Exercise
- [x] Build System(s)
- [x] Make Targets
- [x] Build kubectl
- [x] Testing
- [x] SIGs, Areas, Issues: Engaging
- [x] Help Wanted: First PR Ideas

### NCW 201 deck

- [x] k/k repo tour
- [ ] Build And Test Your First Binary 
- [ ] Testing in Kubernetes
- [ ] Lables and bot commands
- [ ] Labels and Bot Commands, OWNERS files, GitHub workflow, tools like gubernator.
- [ ] Membership
- [ ] Demo: Code Cleanup - PR against k/k 
- [ ] Find A Reviewer
- [ ] Release Cycle
- [ ] Questions

/sig contributor-experience
/area contributor-summit

**Comment by guineveresaenger** [comment]
/area na-summit

Links to past slide decks:

[Barcelona Slides for reference](https://docs.google.com/presentation/d/1usEbwHMSC8vR7HvbxHJBOj2ISdTkw9rmufQUq7fkIl4/edit#slide=id.g577153f745_1_410)
[Seattle NCW Slides](https://docs.google.com/presentation/d/1cgEw0t8oeokaN44piqmEemul2gQBqZX5wvj6NncqPFI/edit#slide=id.g46fa5fb152_0_0)

**Comment by debgiles** [comment]
Event powerpoint template available in #3903

**Comment by raelga** [comment]
Thanks @debgiles, the slides look awesome!

**Comment by raelga** [comment]
WIP of the new deck at https://docs.google.com/presentation/d/18LcwvqyNn74HgqIk7O-ChgfSsJAqDIYm7obguEXto4Q/edit?usp=sharing

**Comment by parispittman** [comment]
@raelga can you pass me comment perms? thanks!

**Comment by raelga** [comment]
@paris Done!

Sharing link updated with comment permissions for all and added you as editor just in case.

**Comment by jeefy** [comment]
How are things going with the 201 preso? Please ping if help is needed. :)

**Comment by raelga** [comment]
Added:
- [Community values slide](https://docs.google.com/presentation/d/18LcwvqyNn74HgqIk7O-ChgfSsJAqDIYm7obguEXto4Q/edit#slide=id.g608b283008_0_52)
- [Community Groups slide](https://docs.google.com/presentation/d/18LcwvqyNn74HgqIk7O-ChgfSsJAqDIYm7obguEXto4Q/edit#slide=id.g608b283008_0_11) 
- [Community Groups overview diagram](https://docs.google.com/presentation/d/18LcwvqyNn74HgqIk7O-ChgfSsJAqDIYm7obguEXto4Q/edit#slide=id.g5e6254b17b_4_1270)
- [Community Group Governance model](https://docs.google.com/presentation/d/18LcwvqyNn74HgqIk7O-ChgfSsJAqDIYm7obguEXto4Q/edit#slide=id.g608b283008_0_25)

Merged:
- [Community / Committees](https://docs.google.com/presentation/d/18LcwvqyNn74HgqIk7O-ChgfSsJAqDIYm7obguEXto4Q/edit#slide=id.g5e6254b17b_4_1345)
- [Community / User Groups](https://docs.google.com/presentation/d/18LcwvqyNn74HgqIk7O-ChgfSsJAqDIYm7obguEXto4Q/edit#slide=id.g608b283008_0_80)

**Comment by raelga** [comment]
The community groups sections have been updated with up-to-date information.

Updated:

 * [SIGs diagram slide](https://docs.google.com/presentation/d/18LcwvqyNn74HgqIk7O-ChgfSsJAqDIYm7obguEXto4Q/edit#slide=id.g5e6254b17b_4_1270)
 * [SIGs / WG / Sub-projects slides](https://docs.google.com/presentation/d/18LcwvqyNn74HgqIk7O-ChgfSsJAqDIYm7obguEXto4Q/edit#slide=id.g5e6254b17b_4_1282)

**Comment by mrbobbytables** [comment]
With the summit done with, I think it's safe to close out this issue.
Thanks all for your effort ❤️ 

/close
