### ISSUE TITLE
Add url for event planning doc

### ISSUE THREAD

**Issue by markyjackson-taulia** [kubernetes/community#3921]
Need to update sig.yaml with url doc link

/sig contributor-experience
/area contributor-summit
/area na-summit
/assign @markyjackson-taulia

**Comment by markyjackson-taulia** [comment]
#3920

**Comment by hpandeycodeit** [comment]
@markyjackson-taulia Since the PR related to this is already merged, I think we are good to close this issue. :) 
/close
