### ISSUE TITLE
Can't join sig node mailing list, access denied

### ISSUE THREAD

**Issue by alisondy** [kubernetes/community#3927]
[On this page](https://github.com/kubernetes/community/tree/master/sig-node), under mailing list, when I try access the page for the google group, the following message is displayed :

<img width="574" alt="Screen Shot 2019-07-26 at 19 48 08" src="https://user-images.githubusercontent.com/19580905/61935368-77432380-afde-11e9-92e2-50d31987c322.png">

Please help 🙏

**Comment by nikhita** [comment]
I think this could be related to the recent permissions change that google groups introduced.

Pasting from @parispittman's email to chairs and TLs:

```
GoogleGroups changed their settings and a lot of your mailing list discovery settings are borked.[Article: Google Groups changed many moderation and role based features]. The setting allows people to see your group when they aren’t a member (to join, read).

"People can’t access my group, even with a link" is the problem statement we are hearing.

1. Sign in to Google Groups.
2. Click My Groups.
3. Click the name of the group.
4. Near the top right, click Manage group.
5. Click Settings
  1. Information
  2. Directory.
    1. Edit the setting to set the desired visibility as all on the web.
    2. Click Save.
``` 

I can see the mailing list in incognito, but there have been previous reports of this being inconsistently visible to non-members. Would be good to fix the settings in any case.

/assign @derekwaynecarr @dchen1107

**Comment by derekwaynecarr** [comment]
@nikhita thanks for the pointer.  I think I lack permissions for this item, will make sure its brought to @dchen1107 attention in sig-node meeting tomorrow.

**Comment by dchen1107** [comment]
Fixed. Thanks for the reporting and the tips.

**Comment by nikhita** [comment]
@alisondy Can you close this issue if you are able to access the mailing list? Thanks! :)

**Comment by alisondy** [comment]
Solved thankyou 🙏

/close
