### ISSUE TITLE
Ensure all SIG/WG/UG leads are Kubernetes org members

### ISSUE THREAD

**Issue by nikhita** [kubernetes/community#3945]
From https://github.com/kubernetes/community/blob/master/committee-steering/governance/sig-governance.md#notes-on-roles:

> Members MUST be community members to be eligible to hold a leadership role within a SIG.

From https://github.com/kubernetes/community/blob/master/committee-steering/governance/wg-governance.md#creation-process-description:

> Please note that all working group organizers and holders of other leadership roles must be community members.

This note for working groups was added in https://github.com/kubernetes/community/pull/3564.

---

The following SIG/WG/UG leads are currently not Kubernetes org members. If your name is listed below, please [apply for membership](https://github.com/kubernetes/community/blob/master/community-membership.md#member).

wg-iot-edge-leads:
  - ~@cindyxing~
  - ~@dejanb~
  - @ptone (needs to accept invite)

wg-security-audit-leads:
  - ~@aasmall~
  - ~@cji~
  - ~@jaybeale~

wg-policy-leads:
  - @easeway
  - @ericavonb
  - @hannibalhuang
  - @mdelder
  - @tsandall

---

Some practical reasons why we want to enforce this:

- The `verify-owners` prow plugin adds the `do-not-merge/invalid-owners-file` whenever a PR _patch_ mentions people in OWNERS files who are not org members. This has caused friction while updating sig leads: https://github.com/kubernetes/community/pull/3923#issuecomment-514675122,  https://github.com/kubernetes/org/pull/1052#issuecomment-516291829.

- Having non-org members in OWNERS files is a no-op because they won't be able to lgtm/approve. Leads should be able to have powers to do this for community admin tasks.

/sig contributor-experience
/area github-management
/kind bug

cc @kubernetes/owners

**Comment by parispittman** [comment]
other practical reasons: voting in elections (contributor names can be pulled without validating multiple sources like a chair list), contributor summit invites, etc.

**Comment by spiffxp** [comment]
/priority critical-urgent
The lack of membership should have been a blocker to the creation of these groups in the first place
/committee steering
Putting this on steering's radar

**Comment by cji** [comment]
Hello! To clarify, if our involvement is focused on the WG we're a part of, should we be requesting access to @kubernetes or @kubernetes-sigs? Or both? https://github.com/kubernetes/org/issues/966

**Comment by spiffxp** [comment]
@cji definitely kubernetes; if, as part of your WG's mission, you need to interact with code or issues in repos in kubernetes-sigs, there too

**Comment by tallclair** [comment]
@easeway is no longer involved with Kubernetes, and should be removed from the wg-policy-leads

I will also vouch for / sponsor @cji @JayBeale and @ericavonb

**Comment by mattmoyer** [comment]
I'm also happy to vouch for @cji and @ericavonb.

**Comment by hannibalhuang** [comment]
agree with @tallclair and @mattmoyer 's endorsement on Erica, for policy-wg @easyway @mdelder and @tsandall are not active leads, just me and Erica at the moment :)

**Comment by nikhita** [comment]
Thanks for the update, everyone!

@hannibalhuang can you create a PR to update leads for wg-policy?

**Comment by ptone** [comment]
What is the guidance on soliciting the sponsors required for membership (per the application link, you need 2 +1s ) if the WG activity is mostly about running recurring meetings and docs?

**Comment by nikhita** [comment]
> What is the guidance on soliciting the sponsors required for membership (per the application link, you need 2 +1s ) if the WG activity is mostly about running recurring meetings and docs?

@ptone I'd look at asking the leads of the WG's stakeholder SIGs: https://github.com/kubernetes/community/blob/master/wg-iot-edge/README.md#stakeholder-sigs and/or people you interacted with while seeding the WG.

**Comment by nikhita** [comment]
Ping on this...

@ericavonb: Can you create a membership request to be added to the Kubernetes org?

@ericavonb and @hannibalhuang: Can you create a PR/mailing list thread to update the wg policy leads? 

@ptone and @aasmall: Reminder to accept the invite to the org. You can find the invite by visiting https://github.com/kubernetes :)

**Comment by mrbobbytables** [comment]
/remove-lifecycle stale
Still blocked by wg-policy, but there has been some updates in https://github.com/kubernetes/community/issues/4185
