### ISSUE TITLE
kube-scheduler  bind is async,   scheduler-extender how to maintain node/pod cache 

### ISSUE THREAD

**Issue by hongli-my** [kubernetes/community#3951]
according to  [scheduler-extender](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/scheduler_extender.md)

we can configure scheduler.conf  extenders section:  filterVerb, prioritizeVerb, bindVerb.
but, kube-scheduler  filter and prioritize is sync, bind is async,  before bind will call  assume.
maybe some request should be send to scheduler-extender when assumePod in kube-scheduler.

**Comment by hongli-my** [comment]
sig/scheduling

**Comment by k82cn** [comment]
@hongli-my , would you help to open an issue at https://github.com/kubernetes/kubernetes ?

**Comment by hongli-my** [comment]
@k82cn   here: https://github.com/kubernetes/kubernetes/issues/82359
