### ISSUE TITLE
Contributor Summit SD: Monday Content Framework 

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3956]
This issue will collect main content, room, and Monday event information and link to other detailed issues (possibly by room/track). Monday is a mix of workshops, unconference, pre-planned topics and discussion sessions, and other multimedia adventures.

By Room:
Main Room/Main Track (1 room)

- host morning welcome, afternoon wind down, and other sessions that we believe will have more than 75 people attending. q&a
- Ideas: year of changes in API review, what’s ahead, API live PR review, live coding
- 6-10 sessions depending on timing 
- Sourcing content from: reg form question, steering, contribex, feedback from chairs
- Setup: Theater
- Recording: yes

New contributor workshop activities / sig meet and greet (2 rooms)
https://github.com/kubernetes/community/issues/3835

- Previous 101 and 201 workshops are being re-worked to How to Get Started (101) and Building, testing, and GH Workflows (201)
- Some “201” content will be ad hoc this time; any contributor onsite can join and not solely those who signed up for it
- SIG Meet and Greet is going to focus on linking people up with actual work vs letting them play on their own and open to current contributors, too for a ‘bring your PR’ for review. We’ve noted that if folks walk out confused as to where they will add value, they will not participate in the future. We are opening this to current contributors, too, so they can get involved with new SIGs or open the floor for communication. https://github.com/kubernetes/community/issues/3896
- Set up: Round tables 
- Recording: yes 

Unconference Track (1 room)
https://github.com/kubernetes/community/issues/3894

- This has been reduced from previous events based on feedback; people still want their voice heard (and we do, too) though
- 5-8 sessions depending on timing 
- Suggesting topics and voting will happen mainly at the Sunday night event but will be open for an hour during breakfast on Monday. TBU on logistics.
- Setup: discussion/fishbowl 
- Recording: not recorded

[Current Contributor] Workshop and Learning Track (1 Room)

- 3 hour block for a doc sprint - tbd 
- 3-5 sessions depending on timing 
- Other ideas: interactive chair training, writing better tests, writing KEPs, etc
- Sourcing content from: reg form question, call for sessions
- Set up: roundtables or pods, whichever has a larger capacity
- Recording: possibly recorded depending on the interactiveness of the workshops

Technical discussions (1 Room)

- Sourcing content from: reg form question, call for sessions
- Ideas: release engineering, test infra, build and test using KIND, etc. 
- Set up: Fishbowl 
- Recording: not recorded unless we get a project decision discussion, past videos of other meetings do not come out well

Sustainability topics (1 Room)

- Ideas: building roles, mentoring how tos, retaining contributors, stories/BPs/what works from sigs, how to work with other timezones, etc
- Sourcing content from: experts/chairs/contributors, steering, contribex, call for sessions
- Set up: Discussion/fishbowl
- Recording: yes

**Comment by jberkus** [comment]
Looks good.  Should this go onto the content proposal doc?

**Comment by parispittman** [comment]
@jberkus i took it out of there to make it more open.

**Comment by cblecker** [comment]
I'm curious as to what the schedule looks like.

I'm concerned about concurrency and forcing folks to choose between multiple important sessions. For example, "technical discussions" and "sustainability topics" are equally important and apply to most of the project.. I wouldn't want to see the situation where folks (particularly senior project leaders) have to choose between participating in a technical discussion, and talking about project sustainability.

**Comment by mrbobbytables** [comment]
> I'm concerned about concurrency and forcing folks to choose between multiple important sessions. For example, "technical discussions" and "sustainability topics" are equally important and apply to most of the project.. I wouldn't want to see the situation where folks (particularly senior project leaders) have to choose between participating in a technical discussion, and talking about project sustainability.

It's honestly a difficult balance to maintain. =/ There has been, and certainly will be a significant amount of content to fit in and schedule for one day.

**Comment by jberkus** [comment]
@cblecker that will never not be a problem.   However, making the CS longer has been impractical for a number of reasons.  Also, as the CS grows (450 for San Diego), we *must* have concurrent sessions in order to keep some sessions small enough that real discussion sessions can happen.

**Comment by cblecker** [comment]
@jberkus This means that the schedule is even more important. Trading off large sessions for too many sessions that stakeholders can't attend sessions they need to is not *necessarily* a good trade off.

My point is though, I'm interested in seeing the draft schedule when it's available and perhaps provide some feedback. I know all of us have the goal of the most useful schedule possible.

**Comment by jberkus** [comment]
@cblecker great, I've put your name down as someone to help us work out a schedule.  ;-)

**Comment by cblecker** [comment]
@jberkus happy to help :)

**Comment by jeefy** [comment]
Walking the board and pinging for updates. The next major deadline we have involves room layout and A/V reqs (Sept 16th). The following week (Sept 25th) is when we finalize our signs. 

We should try to have the schedule in a firm state before the 16th. Ping with an update, and let us know if less opinions (or more help) are/is required. :)

**Comment by idealhack** [comment]
We've been catching up for the past week.

Now schedule's been sending out to speakers to confirm their availability etc.

**Comment by jeefy** [comment]
Schedule is pending and we'll be releasing it this week.

Thanks all!

/close
