### ISSUE TITLE
doc: combo zoom and youtube admins

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3959]
per an email sent to moderators for discussion, it makes sense to have zoom and youtube moderators/admins be the same. as we set up more automation, both of those functions need to share credentials in order to set it up. we can explore using the youtube communications manager feature to add youtube specific moderators down the line but for now, they should all have the same perms. 

to close this issue:
make sure the moderator is good with both (this doesn't impact a lot of people)
combo the sections for zoom and youtube moderators in /communication/moderators.md
onboard moderator onto the other platform (zoom or youtube)

**Comment by markyjackson-taulia** [comment]
@castrojo Can I pair with you to complete this? I think the only portion left to do is sync the zoom and youtube users and combo the doc.. Currently, it looks like we have more youtube admins then zoom admins..
