### ISSUE TITLE
I manage the corporate CLA for my company, how do I add more contributors?

### ISSUE THREAD

**Issue by DanRoscigno** [kubernetes/community#3974]
Hi Folks,
I have not added anyone other than myself to the CLA for my company, and I can't remember how to add someone.  One of my colleagues would like to contribute.  

Thanks!!

**Comment by thecrudge** [comment]
/sig contribex

Hi Dan, 

I think the best place to start would be here:

https://github.com/kubernetes/community/blob/master/governance.md

and

https://github.com/kubernetes/community/blob/master/community-membership.md

**Comment by parispittman** [comment]
@DanRoscigno - https://github.com/kubernetes/community/blob/master/CLA.md instructions are there for corp as well as individual. you may want to consult a lawyer as it related to adding things on your side.

**Comment by nikhita** [comment]
@DanRoscigno Also, in case you run into any issues, the LF Support Site (https://github.com/kubernetes/community/blob/master/CLA.md#troubleshooting) would have the necessary expertise to help you. :)

fyi @idvoretskyi  

Closing since this isn't actionable from the Kubernetes side.
/close
