### ISSUE TITLE
SD Contributor Summit - Sunday Social event - Child Care 

### ISSUE THREAD

**Issue by JamieRachel** [kubernetes/community#3993]
Diversity/inclusion - re: childcare services provided for attendees for Sunday evening social events 

[] @debgiles will check on logistics as this is with a 3rd party company (cost)
[] if need link to registration 

/milestone September

**Comment by JamieRachel** [comment]
sig/contributor-experience
area/contributor-summit
area/na- summit

**Comment by debgiles** [comment]
We've confirmed we will not offer childcare on Sunday night, and the venue will be open to all ages.  That should close this issue out.  Let me know if there are any questions.  Thanks!

**Comment by jeefy** [comment]
That will do it, Thanks! 

/close
