### ISSUE TITLE
SD Contributor Summit - Laptop Program 

### ISSUE THREAD

**Issue by tashimi** [kubernetes/community#3994]
I'd like to propose creating a loaner laptop program. Currently in the New Contributor sign up form, we ask if a participant has a laptop they can install software on, and if they don't, the form tells them they must have a laptop to participate. This will exclude potential new contributors who either don't have a laptop they can bring, or have a laptop at their work that they are not allowed to install software on. 

I propose we create a loaner laptop program, and have laptops available for those who do not have one, and that we ask attendees to tell us if they need a loaner laptop at registration, using gentler and more encouraging language so they know they are still welcome to attend and will still get something out of attending without a laptop. 

I understand we need to engage with CNCF and their legal team to see how to correctly go about doing this.

**Comment by tashimi** [comment]
@kubernetes/sig-contributor-experience-proposals

**Comment by mrbobbytables** [comment]
Thanks again for surfacing this idea! :) 

/assign @debgiles 
For working with CNCF legal.

/area contributor-summit
/area na-summit

**Comment by cblecker** [comment]
This is a cool idea :)

**Comment by debgiles** [comment]
I believe we're going to do discovery first to see if people need the laptops and then revisit this?  Let me know if I misunderstood on today's call though.  Thanks!

**Comment by tashimi** [comment]
Yes, step 1 is for us to ask the question on the sign up form (cc @mrbobbytables). Meanwhile, if someone does ask for assistance, we'd like to have the convo with CNCF legal so we can offer a loaner laptop (@debgiles )

**Comment by mrbobbytables** [comment]
👍 The question was added to the list to update:
```
Do you have a laptop that you can bring to this event for use with the workshop
(install software, capable of running containers or a virtual machine)?
Yes
No - do not have a laptop
No - have a laptop but cannot install software on it without IT approval
```

**Comment by jeefy** [comment]
Should we leave this open until after we have collected data? My feeling is this should be closed and addressed during retro once we look at both feedback and future planning, but I could go both ways.

Thoughts?

**Comment by tashimi** [comment]
Once we see if people need laptops, we plan to implement a program for this Kubecon, so I think this should remain open. We're not going to wait for a future Kubecon to fill this need.

**Comment by ameukam** [comment]
@jeefy Should we leave this open for Amsterdam ?

**Comment by tashimi** [comment]
@ameukam I would suggest we close it, but continue tracking if participants need laptops to participate. If they do, we can kick off a laptop program to satisfy the need.

**Comment by mrbobbytables** [comment]
We'll definitely keep the question on the reg form 👍and will follow-up as needed.
Thanks for kicking off the idea @tashimi :)
