### ISSUE TITLE
Cross-cluster communication between pods (AWS)

### ISSUE THREAD

**Issue by nydalal** [kubernetes/community#400]
I've question with cross-cluster communication between pods on AWS.

I am using kubernetes to deploy clusters on AWS. Both clusters are in same region and AZ. Both clusters are deployed in their own VPC with non-overlapping subnets. I've successfully created VPC Peering to establish communication between two VPCs. and Minions (instances) from VPC can ping each other through private IP.

Question is, Kubernetes pods from one Cluster (VPC) can not ping Pod in another cluster through it's internal IP. I see traffic leaving pod and minion but dont see it on other VPC.

Here is IP info:

Cluster 1 (VPC 1) - subnet 172.21.0.0/16
Minion(Instance)in VPC 1 - internal IP - 172.21.0.232
Pod on Minion 1 - IP - 10.240.1.54

Cluster 2 (VPC 2) - subnet 172.20.0.0/16
Minion(instance)  in VPC 2 - internal IP - 172.20.0.19
Pod on Minion 1 - IP - 10.241.2.36

I've configured VPC Peering between two VPC and I can ping Minion in VPC 1 (172.21.0.232) to Minion
in VPC 2 through IP 172.20.0.19

But when I try to ping pod on VPC 1, Minion 1 - IP 10.240.1.54 from VPC 2, Minion Pod 10.241.2.36, it can not ping.

Is this supported use case in AWS? How can I achieve it. I have configured security group on both instance to allow all traffic from source 10.0.0.0/8 as well but it did not help.

Really appreciate your help!

**Comment by kruunch** [comment]
I'm running into the same issue as well.

**Comment by liggitt** [comment]
For issues like this, please use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/
