### ISSUE TITLE
not able to pull images from ECR: no basic auth credentials

### ISSUE THREAD

**Issue by dhineshbabuelango** [kubernetes/community#4003]
We are using aws eks, we used to deploy our application which will always pull images from ECR. it was working fine for a month and all of a sudden we started getting this error, not able to pull any images from ECR.

Failed to pull image "": rpc error: code = Unknown desc = Error response from daemon: Get https://XXXXXX.dkr.ecr.ap-southeast-1.amazonaws.com/v2/webbook/webbook/manifests/latest: no basic auth credentials

We were able to fix this issue after we restart the kubelet service. But to get the root cause i tried opening a case with AWS and they told it is out of thier scope need some help here

**Comment by cblecker** [comment]
I'm sorry, but you'll need to speak to AWS support. The open source Kubernetes project doesn't run ECR or EKS.. these are specific AWS products.

/triage support
/close
