### ISSUE TITLE
Create event-team-cs1119 mailing list

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#4007]
We could really use a mailing list for the 2019/11 contributor summit event team.   Please create one.

In the future, I think it should be policy to create mailing lists for each event team.  I thought about having a general event-team list instead (the way the release team does it), but the difficulty with that is that event team planning periods overlap, and having different teams sharing the same list would result in some serious confusion as to which event was being posted about.

/assign @parispittman 
/assign @jamiehannaford 
/area contributor-summit

**Comment by ameukam** [comment]
@jberkus Now San Diego is done, do you want to keep this open for the future summits ?
/remove-lifecycle stale

**Comment by cblecker** [comment]
Closing for now. This can be revisited by future summit leads.
/close
