### ISSUE TITLE
[doc needed] boxing up the contributor workshop

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4010]
several of us have boxed up the workshop and delivered it at places that were not kubecon/cloudnativecon. others have expressed helping to launch in other markets/conferences/unis, etc. it would be cool if we had a checklist for future hosts/teachers.

I can help with this (many others, too) but can't lead. 

scope creep: it should also be targeting an online experience vs in person too

**Comment by jberkus** [comment]
Is this duplicative of the new NCW effort, or not?

**Comment by mrbobbytables** [comment]
Closing in favor of the new NCW efforts 👍 

/close
