### ISSUE TITLE
add more moderators to the moderators@ alias

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4011]
looked at the members list on moderators@ and only see slack, kdev, and youtube admins on the list. we need to add discuss and make sure everyone else is included as well. moderators@ should be the main point of contact for everyone. we should add this into the moderator documentation somewhere that folks will need to take an action and get added. 

https://github.com/kubernetes/community/blob/master/communication/moderators.md

**Comment by cblecker** [comment]
I think GitHub is in there too. If not, we should be.

**Comment by parispittman** [comment]
people that are on there now:
coderanger
jeefy
ihor
spiffxp
dylan
castrojo
jorge (other one)
gus
idealhack
mrbobbytables
christoph
jaice
munnerz
joel 
katharine
loic
nikhita
puja
manjunath
roy
Pandiyaraja

heres the list to compare it to:
https://github.com/kubernetes/community/blob/master/communication/moderators.md

**Comment by cblecker** [comment]
To make changes to this list, please PR in e-mail addresses here: https://github.com/kubernetes/k8s.io/blob/f7715c03741b081abacc78e651d1d1702bdd8c42/groups/groups.yaml#L741-L774

/remove-lifecycle stale

**Comment by idealhack** [comment]
> To make changes to this list, please PR in e-mail addresses here: https://github.com/kubernetes/k8s.io/blob/f7715c03741b081abacc78e651d1d1702bdd8c42/groups/groups.yaml#L741-L774
> 

+1, this should be documented in [moderators.md](https://github.com/kubernetes/community/blob/master/communication/moderators.md) too

**Comment by parispittman** [comment]
@cblecker @mrbobbytables can we automate this in some way?

**Comment by mrbobbytables** [comment]
I don't think there's a good way to automate it beyond what we've done with PR'ing new emails into the groups.yaml in k8s.io. We just need need to make it part of our process when on-boarding new moderators.

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/community/pull/4652 for documenting the process
