### ISSUE TITLE
Decide what to do about declining Community Meeting attendance

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#4019]
For a while, we've been noting that attendance on Zoom at the community meetings has declined, from 100+ dial-ins back in 2017 to an average of less than 40 now (don't have solid data on this because Zoom doesn't record it).  Our assumption had been that more people were watching it on Youtube, but Jorge pulled some data for me, and that doesn't appear to be the case:

![Monthly median community meeting views](https://user-images.githubusercontent.com/115146/63556851-3108b380-c4fb-11e9-8ce9-38f6b95c7459.jpg)

I'm pretty sure the drop in January 2018 was due to Youtube accounting changes, but the fact remains that streaming video viewing has certainly not being going *up*.  And this is during a period where our number of contributors was growing rapidly.

So, what do we want to do about it, if anything?

**Comment by jberkus** [comment]
/sig contributor-experience
attn:
@castrojo

**Comment by castrojo** [comment]
The format of the meeting hasn't changed too much since I started working on it (~2.5 years), however, the community meeting predates many things that we have today that did not exist back then:

- A KEP process
- A dedicated release team
- Regular contributor summits and a contributor focused meet-our-contributors mentorship
- and I am sure I'm missing some

In the past it felt like you really _had_ to attend the meeting to understand what exactly was happening, these days it feels like you can watch the enhancements repo and get close enough without having to have someone explain an upcoming thing to you. 

I'd like to bring in the -dev list and get feedback from core contributors on why they attend or not attend.

I'm not personally attached to any element of the community meeting, it's our format to decide on, so if we need to cut or add something in order to be more useful to core developers then I can easily adjust the format.

**Comment by markyjackson-taulia** [comment]
(Marky wondering aloud) I wonder if we could drive attendance if we had some intros or walked through an issue or even showed people how to get involved, maybe even a sig sponsored drive to get more people.
Just some random idea. Sorry if that doesn't help this issue.

**Comment by castrojo** [comment]
Adding a link on what we say the purpose of the meeting is:

> The Kubernetes community meeting is intended to provide a holistic overview of community activities, critical release information, and governance updates. It also provides a forum for discussion of project-level concerns that might need a wider audience than a single special interest group (SIG).

- https://github.com/kubernetes/community/blob/master/events/community-meeting.md

Marky, those are all great ideas, and we should definitely look at doing those things on the YouTube Channel as a whole (like how we add contributor summit videos, etc); not sure how they might apply for this specific meeting though, we do cover lots of that in Meet Our Contributors, participants can ask a developer to do a code walkthrough or a PR review, etc.

**Comment by markyjackson-taulia** [comment]
If I can help in any way @castrojo please do not hesitate to call on me

**Comment by parispittman** [comment]
i think we need to have an advertising and communication plan for all of our programs and that was my intention of setting up a marketing team for contribex but hasn't gotten off the ground. we should send out the agenda before the meeting to k-dev, get folks to write blog posts about content they see there, pull in josh's lwkd as a subproject, set up a contributor twitter, etc.

**Comment by jberkus** [comment]
> In the past it felt like you really had to attend the meeting to understand what exactly was happening, these days it feels like you can watch the enhancements repo and get close enough without having to have someone explain an upcoming thing to you.

Yeah, I was thinking "if we dropped the contributor meeting, what would I miss?" and the answer is pretty much "the SIG updates".  The CM is still a good way to keep tabs on SIG dev priorities across the project ... but maybe not the best way we could do that.

> I'd like to bring in the -dev list and get feedback from core contributors on why they attend or not attend.

I believe that @parispittman has some data from last year's survey

**Comment by parispittman** [comment]
<img width="913" alt="Screen Shot 2019-05-17 at 2 21 10 PM" src="https://user-images.githubusercontent.com/5912992/63666134-32e4a800-c783-11e9-9bea-03ae130245eb.png">
for the most part, our contributors are split with what they like the most. there is no trends either on certain personas except the two bubbles at the top right

**Comment by parispittman** [comment]
devstats did the poorest and thus, removed it since we removed it from the meeting

**Comment by chris-short** [comment]
YouTube is there too. Watching the meeting is easy, actively participating
is harder. There are a number of things we could try but, I think
reiterating that it's a community meeting and having a community of people
asking questions during the meeting is important. At the moment, it's a
sort of demo and status meeting. If you're not interested in the demo and
are good on updates, what's the incentive to attend? I feel we should work
on making it a more engaging meeting or maybe even conversational to a
point.

I also agree with Paris on the need for a marketing push of some sort. No
one goes to things they don't know about. The calendar invite has probably
changed for everyone and folks haven't picked it back up yet I bet too. How
do you market a meeting? That is a tough question.

Chris Short
He/Him/They
Web <https://chrisshort.net/> | Newsletter <https://devopsish.com/> |
Twitter <https://twitter.com/ChrisShort> | LinkedIn
<https://linkedin.com/in/thechrisshort>

**Comment by guineveresaenger** [comment]
Knowing the agenda beforehand is great; we haven't historically done that.

full disclosure: I am one of the meeting-avoiders, plus my company often has all-hands during the community meeting slot.

**Comment by castrojo** [comment]
On thing for sure I am going to start doing is inviting people outside the usual suspects to host the meeting. The cloud-native/container community has tons of interesting characters and personalities. This seems like a nobrainer way to get interesting hosts that would spice up the meeting: 

![image](https://user-images.githubusercontent.com/1264109/64058447-3e681280-cb79-11e9-9915-5ca25f8e8022.png)

**Comment by parispittman** [comment]
i think it might be safe to close this issue for now and re-open after evaluation of current changes?

**Comment by nikhita** [comment]
> i think it might be safe to close this issue for now and re-open after evaluation of current changes?

:+1: 

/close
