### ISSUE TITLE
Build Amsterdam Contributor Summit Team

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4022]
We'll need to fill the following core roles + shadows to get the ball rolling on strategy and venue selections. Core team will decide on subteam roles (ie - marketing lead will determine if a writer is needed) based on the direction of the event.

[Event Team Folder](https://github.com/kubernetes/community/tree/master/events/events-team)

Self nominations from current and past contributor summit staff for the first week for lead roles. Shadows do not need to have Kubernetes event experience but should be ok with taking a lead role within the next 12 months of events. @jeefy has first choice of what event to lead in 2020 since Jeff was a shadow event lead for San Diego. 

| Role | Volunteer Name | Shadow Name | Notes |
| --- | --- | --- | --- |
| Event Lead|   |   |  |
| Registration Lead |   |   | |
| Marketing Lead |   |  |  |
| CNCF Events Manager | Deb Giles @debgiles  | n/a | CNCF/LF employee |
| Overall Content Lead |   |   |  |

**Comment by geekygirldawn** [comment]
I'm definitely interested in helping out with something, but things are a bit crazy at work right now, so I don't want to commit to anything that might consume more time than I have available :)

**Comment by jonasrosland** [comment]
I would gladly take on the marketing lead role again. If Jeff chooses not to take lead on the Amsterdam Summit, I would also be available to do that.

**Comment by geekygirldawn** [comment]
I could probably do content lead, since the EU events don't have an insane amount of content outside of NCW?

**Comment by ameukam** [comment]
I'm interested in helping out the Registration Team. :-)

**Comment by tashimi** [comment]
I'm happy to do D&I again

**Comment by raelga** [comment]
Happy to be part of the Content / NCW team again, not ready to lead (yet), but willing to keep learning to be there in the future!

:)

**Comment by celanthe** [comment]
Happy to help with content/D&I however possible! :)

**Comment by idealhack** [comment]
I'm happy to help with Content / NCW again :)

**Comment by jeefy** [comment]
@parispittman Toss me on as lead for Amsterdam please. :) 

Let's get this party started.

**Comment by raelga** [comment]
{{party_parrot_placeholder}}

**Comment by Pensu** [comment]
Would love to help out with Registration/Content.

**Comment by tariq1890** [comment]
I am happy to be involved with content again. But also open to other teams if that slot already fills up.

**Comment by palnabarun** [comment]
I would love to take up the Registration Lead role for the Amsterdam Summit. :)

**Comment by mrbobbytables** [comment]
> I would love to take up the Registration Lead role for the Amsterdam Summit. :)

+1 from current reg lead :)

and with that, I'd like to shadow for lead :D

**Comment by celanthe** [comment]
+1 for being interested in shadowing as lead, though likely not for this particular event, as I [currently] don't think I'll be able to attend.

**Comment by VineethReddy02** [comment]
+1 am interested and would love to help preferably content and registration also am flexible to take up any role looking forward to collaborate.  :)

**Comment by anirudhmurali** [comment]
Can lend a hand for any of the roles. Count me in! 😄

**Comment by jeefy** [comment]
Hey y'all! I'll be reaching out to people after San Diego to firm up the Amsterdam team. Stay tuned!

**Comment by thecrudge** [comment]
I would like to lead the unconference if it’s not been filled yet

**Comment by dianaabv** [comment]
I'm interested in helping out the RT but actually any Team would work. 💯 👍

**Comment by onlydole** [comment]
I’d love to help out in any of the Content / Registration / Event capacities!

**Comment by alisondy** [comment]
✋  Am keen to help out with the NCW and am willing to lead

**Comment by rajula96reddy** [comment]
Hey! I loved participating in the NA Contributor Summit. I would love to help out here.

**Comment by hpandeycodeit** [comment]
I don't see Project Management role here but happy to be a part of the Project Management Team again or Registration Team.

**Comment by BenTheElder** [comment]
Hi, I would love to help run the new contributor workshop 🙂

**Comment by jeremyrickard** [comment]
Hey, I'm not 100% sure if I'll attend AMS, but I'd love to shadow NCW and help out. I enjoyed filling in during San Diego and would like to help make NCW even more successful!

**Comment by savitharaghunathan** [comment]
Hi, I would like to be a shadow for Registration/Events team :)

**Comment by detiber** [comment]
I'm happy to help out with the Content team as well (assisted @geekygirldawn with the SIG M&G planning for San Diego). Also happy to help out w/ Registration if needed as well.

**Comment by markyjackson-taulia** [comment]
I would like to help with the unconference. Still working out with my employer going but I would like to be involved

**Comment by chris-short** [comment]
I was confirmed going to Amsterdam yesterday. I’m in wherever needed. Can do content work And/or on the ground workshops.

**Comment by munnerz** [comment]
I would also like to help out with the new contributor workshop 🙂

**Comment by amandakatona** [comment]
Hey! I would love to help out with by way of shadow for the unconference in Amsterdam. I'll have more time to give in Boston, and would like to be a part of AMS if there's room.

**Comment by jeefy** [comment]
Hey y'all! I'm going to keep this thread open to track the effort but at this point volunteer sign-ups are closed. :) 

I've started reaching out to some prospective leads (and suggested some shadows along the way) and hopefully we'll have a team staffed next week. 

Thanks to everyone that posted! Y'all make this community and make me feel warm and fuzzy inside. 😊 😊 😊

**Comment by jeefy** [comment]
We're all set I think. :) 

/close
