### ISSUE TITLE
Community Meeting Notifications

### ISSUE THREAD

**Issue by chris-short** [kubernetes/community#4031]
I'd like to get an MVP notification system up and running for community meetings (see #4019). Tweets, emails, etc. What are the best places to send to? k-dev? k8s twitter? kubeweekly? where else?

**Comment by guineveresaenger** [comment]
/sig contributor-experience
/area community-management

I support the use of twitter to blast about the community meeting!

Do we have a community-meeting Slack channel? internally, we have an all-hands channel, and it's a great way to comments and stay connected with any presenters and ask questions if you're not comfortable putting up your hand in a meeting, or if you can't video chat.

**Comment by chris-short** [comment]
I'll reach out to CNCF team today to work on the k8s twitter messaging.

**Comment by chris-short** [comment]
First crack at these, need a few more so we can tweet more often throughout the week.

Want to find out what's going on in #Kubernetes? Come find out at the Kubernetes Community Meeting! https://github.com/kubernetes/community/tree/master/communication#weekly-meeting

Subscribe to the Kubernetes Community livestream to learn more about the latest happenings with Kubernetes: youtu.be/c1GzVlofSm4

Want to participate in the Kubernetes Community meeting? Join the Zoom meeting every Thursday at 1000 UTC. https://zoom.us/my/kubernetescommunity

**Comment by castrojo** [comment]
Spam is a problem when we post zoom URLs to twitter, would prefer to send people to youtube or the page and then put the zoom info on there.

**Comment by chris-short** [comment]
Noted, @castrojo 

Also, I talked to Kristen Evans who said occasional tweets from CNCF/Kubernetes accounts are possible but, a scheduled cadence of them isn't recommended due to the frequency.

**Comment by geekygirldawn** [comment]
I think it would be great if we could customize the messages with details from the agenda, which might entice people to attend their first meeting if they see something they are are interested in learning more about. 

Something like:

Join the Sept 5th #Kubernetes Community Meeting to see a demo of ?? and get updates from our Autoscaling, Windows, and Network SIGs: https://github.com/kubernetes/community/tree/master/communication#weekly-meeting

As for the CNCF/Kubernetes accounts, maybe we could get them to post something about once a quarter or maybe they could promote the first community meeting after each KubeCon to encourage people to stay engaged?

**Comment by chris-short** [comment]
I will begin scheduling some of these through my personal account(s) and will ask CNCF to broadcast/rebroadcast as appropriate.

The question is, what platforms should we care about (we need to think about outside the US)?

Updated per feedback:

Want to find out what's going on in #Kubernetes? Come find out at the Kubernetes Community Meeting! https://github.com/kubernetes/community/tree/master/communication#weekly-meeting

Subscribe to the Kubernetes Community livestream to learn more about the latest happenings with Kubernetes: https://youtu.be/c1GzVlofSm4 #Kubernetes

Want to participate in the Kubernetes Community meeting? Join us every Thursday at 1000 UTC. https://github.com/kubernetes/community/tree/master/communication#weekly-meeting #Kubernetes

**Comment by cblecker** [comment]
Want to find out what's going on in #Kubernetes? Come find out at the Kubernetes Community Meeting! https://git.k8s.io/community/communication#weekly-meeting

Want to participate in the Kubernetes Community meeting? Join us every Thursday at 1000 UTC. https://git.k8s.io/community/communication#weekly-meeting #Kubernetes

^^ updated with shortened links

**Comment by chris-short** [comment]
https://twitter.com/ChrisShort/status/1169267080798932993

Join the Sept 5th #Kubernetes Community Meeting to see a demo from our @GSOC student, Elijah Oyekunle. Plus we'll be getting updates from our Autoscaling, Windows, and Network SIGs: https://git.k8s.io/community/communication#weekly-meeting #K8s

**Comment by chris-short** [comment]
Also shared on linkedin: https://www.linkedin.com/posts/thechrisshort_kubernetescommunity-activity-6575105747120644098-Rmme

**Comment by chris-short** [comment]
Join the live stream of today's Kubernetes Community meeting to learn more about the latest happenings with Autoscaling, Windows, and Network SIGs. Plus, a bonus demo from our @gsoc student, Elijah Oyekunle! https://youtu.be/41Le9wRzbf8 #Kubernetes #K8s

https://twitter.com/ChrisShort/status/1169623031695794176

**Comment by markyjackson-taulia** [comment]
@chris-short Did you find a doc for tweeting?

**Comment by chris-short** [comment]
@markyjackson-taulia No. I would say that this is going to fall under the Social Media subproject of the Marketing team. That's all in-flight.

**Comment by mrbobbytables** [comment]
/area contributor-comms
Moved this over to the marketing sub-project 👍

**Comment by mrbobbytables** [comment]
I think this is now sorted out with the plans for the twitter account etc? @chris-short @mbbroberg @parispittman

**Comment by chris-short** [comment]
I think @mrbobbytables is right that this is safe to close now. Thank you!  
  
@kaslin, @parispittman: We should consider a sheet of tweets that we can modify and re-use existing content (like the tweets crafted here) so that we can more quickly put solid tweets together.
