### ISSUE TITLE
REQUEST: New Slack private channel #reddit-admins-private

### ISSUE THREAD

**Issue by gtaylor** [kubernetes/community#4040]
**GitHub Username:** gtaylor

**Slack Username:** greg.taylor

**What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?** Private Channel

**Name of Requested Resource:** #reddit-admins-private

**Description of Request:**

Per [discussion](https://kubernetes.slack.com/archives/C4M06S5HS/p1563920994003800) with @thockin, we are looking to get more organized with the moderation of the unofficial [r/kubernetes](https://www.reddit.com/r/kubernetes/) subreddit. We'd like to get the mod team for the subreddit in a private channel, where we can talk over the modlog and other things that probably shouldn't be visible to all.

While the subreddit is not official, it is large (~30k subscribers), growing rapidly, and is a major source for news and discussion for the Kubernetes community. We could create a separate Slack org for this, but wanted to see if we could hitch to this one since we're all already here!

Thanks in advance!

**Comment by castrojo** [comment]
/lgtm

This would be great!

**Comment by castrojo** [comment]
Please open a PR against this: https://github.com/kubernetes/community/blob/master/communication/slack-config/channels.yaml

**Comment by mrbobbytables** [comment]
Unfortunately, tempelis can't manage private channels...they're kind of funky in slack. After creation they can't really be "managed" by anyone (including owners and admins) unless they're in the channel itself already . :|

Before creating a private channel for it, would you be open to the idea of making it an official kubernetes community platform? 

The big change would be that the [Kubernetes (CNCF) Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) would need to be enforced. There's a few other small things such as listing it as an official communication platforms and updating the [moderators list](https://github.com/kubernetes/community/blob/master/communication/moderators.md) with info on who to contact, but all-in-all pretty minor tasks.

**Comment by gtaylor** [comment]
> The big change would be that the Kubernetes (CNCF) Code of Conduct would need to be enforced.

We have this in the sidebar where our rules are outlined:
![image](https://user-images.githubusercontent.com/75556/64299864-98792700-cf2f-11e9-80cf-c48d7212ff74.png)
The thing that we're running into is that we're not coordinated enough as a mod team to enforce the CoC in a timely and consistent manner (which is where this channel would come in). This sub has gradually and organically grown by the sheer inertia of the wider Kubernetes community, rather than from anything the mod team is doing.

I think we'd be very open to the idea of making the community official. Would there be comfort with starting with the channel + getting organized? We don't quite have our act together to be able to bear the official label without blushing.

Would we be comfortable starting the channel? I'd like to work with @thockin to cull the mod list down to just those who have the time to be actively involved, do another pass on our rules, get on the same page about enforcing the rules in a consistent manner, and incorporating some regular/scheduled events. This'd get us to the point of being a "real" sub that'd be ready for official consideration.

**Comment by mrbobbytables** [comment]
Awesome. The CoC thing was the biggest concern.

Because of the nature of private channels, they're something we really don't want to do for an unofficial communication platform (our current policies are pretty strict on their usage). Once created they're essentially 100% unmanageable from a slack admin/owner perspective =/ 

If you'd like to become official (even if not quite ready for it), a case can be made for it.

Going beyond that, if you do need help finding mods -- that is something we may be able to help with. 👍

**Comment by gtaylor** [comment]
I don't think I can sign us up for that unilaterally, and we're not quite organized enough for me to have a great way to make that case.

I'm going to close this and we'll find another way to get stuff sorted out!
