### ISSUE TITLE
cloudera manager in kubernetes

### ISSUE THREAD

**Issue by Fiseast** [kubernetes/community#406]
I tried to deploy cloudera manager in kubernetes.
Kubernetes's network is flannel.
cloudera manger server 172.100.73.5
host1 172.100.39.3
host2 172.100.73.3
host3 172.100.76.3

Now, I found it will connect to broadcast's(172.100.73.0) port 7182 if the hosts and the cloudera manager server is different ip network when add hosts to cluster.
So the result is "connection is refused" except host2.

How can I expose the broadcast's port to hosts?

Thanks for your help.

**Comment by bgrant0607** [comment]
Please try stackoverflow.
