### ISSUE TITLE
 Contributor Summit SD - Create Monday need to know info slides

### ISSUE THREAD

**Issue by raelga** [kubernetes/community#4069]
Slide deck to display during the Sunday Night Celebration with _need to know information_ for the Contributor Summit San Diego event on Monday.

Following requirement requested in:

- [Contributor Summit SD: Sunday Night Celebration #3893](https://github.com/kubernetes/community/issues/3893)

Proposal for deck content:
- [x] New contributors name list
- [x] Current contributors name list
- [x] SIG List
- [x] CS Sessions
- [x] NCW Info
- [x] NCW Combined session Morning Agenda 
- [x] NCW Combined session Afternoon Agenda (TBD)
- [x] NCW 101 Agenda
- [x] NCW 201 Agenda
- [x] SIG Meet & Greet Info 
- [x] SIG Meet & Greet session list (TBD)

[WIP] Deck:

- [Kubernetes Contributor Summit - San Diego 2019 - Sunday Info Slides](https://docs.google.com/presentation/d/1OFGJ2kTV_2KsBMmA4aM3j_JU2OQLxb0C/edit#slide=id.p1)

**Comment by idealhack** [comment]
we are currently reviewing proposals of CS Sessions, and the program will be available about two weeks later.

**Comment by jonasrosland** [comment]
Alright, I've added the schedule, all approved attendees, information about all SIGs, the NCWs, and the SIG Meet & Greet. Please take a look.

**Comment by mrbobbytables** [comment]
The linked slide deck is complete and was used at the summit \o/
Here is the deck for future reference:
[Kubernetes Contributor Summit - San Diego 2019 - Sunday Info Slides](https://docs.google.com/presentation/d/1OFGJ2kTV_2KsBMmA4aM3j_JU2OQLxb0C/edit#slide=id.p1)

Going to go ahead and close this out :)

/close
