### ISSUE TITLE
Document Process for setting up recurring Zoom meetings.

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#4077]
The [Zoom Guidelines](https://git.k8s.io/community/communication/zoom-guidelines.md) are missing the best practices for setting up a recurring meeting (ensuring a start/end time etc). This is referenced by the [YouTube guidelines](https://git.k8s.io/community/communication/youtube/youtube-guidelines.md#automation) as a prerequisite for setting up a splain pipeline.

/sig contributor-experience
/area community-management
/kind documentation

**Comment by mrbobbytables** [comment]
/remove-lifecycle stale

This is a little more relevant now after some of the changes zoom has introduced.

**Comment by vishakhanihore** [comment]
@mrbobbytables Here we need to explain `Automation of Zoom` like recurring meetings, Automatic start & stop of meeting ?

**Comment by mrbobbytables** [comment]
This has been done 👍 
/close
