### ISSUE TITLE
APAC friendly K8s Webinars

### ISSUE THREAD

**Issue by saiyam1814** [kubernetes/community#4086]
We are planning to conduct webinars during the APAC friendly timezone. In order to get this started this, we need some kind of google form for CFP wherein people can submit their topics, abstract etc and then we can prioritize things when and how we are going to start.
We also need to check with CNCF for it.

**Comment by idealhack** [comment]
If we want to duplicate some of the CNCF webinars, here they are: https://www.cncf.io/webinars/?_project=kubernetes

**Comment by saiyam1814** [comment]
Yeah, so for the process of nomination they have an email given. I feel that can be changed and we can have google form wherein we can ask for all the information we need and then we select one by one the topics.

**Comment by nikhita** [comment]
cc @kubernetes/sig-contributor-experience-apac-coordinators

**Comment by aravindputrevu** [comment]
Now that we're all on boarded. What are the next steps?

**Comment by saiyam1814** [comment]
We need below for the APAC webinars: 
- cncf official approval for the webinars with the zoom links (when they get decided)
- Google forms : to fill out the (Name, Topic, Abstract, Speaker Bio)-> I can create that
Also I feel Google forms are more interactive rather than sending out emails for the same.
- Kubernetes maintainers/Sig chairs to choose the topics 
- Date and Time (Biweekly, APAC friendly time)

**Comment by vishakhanihore** [comment]
@saiyam1814 Can I create the google form ?

**Comment by vishakhanihore** [comment]
Also I would love to help in the following issue.

**Comment by saiyam1814** [comment]
@vishakhanihore we are not sure if we want to use that but please create a sample one and lets keep it , will bring this up in the next meeting.

**Comment by nikhita** [comment]
From the Nov 7 APAC meeting: @alisondy and I will setup a doodle for the contributor-focused meet-our-contributors-like session and share across the regional channels.

**Comment by nikhita** [comment]
We've decided to move to a blog post format instead: https://github.com/kubernetes/community/issues/4469

/close
