### ISSUE TITLE
Mention point release schedule on the contributor cheatsheet

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#4091]
This is a simple task that is adding a URL to an existing page, if you're a new contributor looking for something simple to learn the process, consider adopting this issue! 

SIG Release has an awesome point release page now: https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md

We should add this to the cheatsheet: https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet

Also consider just having a section on release resources so a contributor has signposts on where the release resources are. 

/sig contributor-experience
/area contributor-guide
/help

**Comment by 2pai** [comment]
can i take this issue ?
so  i just add patch release link to the contributor cheatsheet right?

**Comment by idealhack** [comment]
this was fixed by https://github.com/kubernetes/community/pull/4103

/close
