### ISSUE TITLE
Proposal: provide a font (like fontawesome)

### ISSUE THREAD

**Issue by alexec** [kubernetes/community#4106]
It'd be great to have this as a font similar to how fontawesome works.

/sig contributor-experience
/area contributor-guide
/help

**Comment by nikhita** [comment]
@alexec can you add some more details on what the font is supposed to be meant for, how you are intending to use it, etc?

**Comment by alexec** [comment]
It would make it easy to use the icons in web apps as they could be used via simple CSS styling. I’d note that fontawesome is not actually a font.
