### ISSUE TITLE
Update youtube guidelines to include subprojects

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#4109]
The [current guidelines for  youtube meeting playlists](https://github.com/kubernetes/community/blob/master/communication/youtube/youtube-guidelines.md#meeting-playlists) exclude subprojects. As some of the subprojects are very large in size and host their own meetings, they should be able to have their own playlist to better target their own contributors and increase general discoverability.

/sig contributor-experience
/area community-management
/good-first-issue

**Comment by pravarag** [comment]
If this has not been addressed, I would like to work on it as my first issue. @mrbobbytables let me know if I can take it.

**Comment by mrbobbytables** [comment]
It does not look like it has -- go for it! :)

**Comment by pravarag** [comment]
@mrbobbytables @nikhita any suggestions, where I can get the whole list of subprojects?

**Comment by mrbobbytables** [comment]
@pravarag The list can be found in [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml) in the root of the community repo, and each sig readme (e.g. [contributor experience](https://github.com/kubernetes/community/tree/master/sig-contributor-experience)) will contain the subprojects that they own.

For the documentation, the specifics sig subprojects don't need to be explicitly defined, just a note that subprojects in addition to SIGs, WGs, UGs may request youtube playlists.

**Comment by pravarag** [comment]
Thanks @mrbobbytables . I'm working on it.

**Comment by mrbobbytables** [comment]
I think this is back to being open again if anyone wants to take it on 👍

**Comment by mrbobbytables** [comment]
@zestrells are you still interested in working on this?

**Comment by Evalle** [comment]
@mrbobbytables @zestrells hey folks. I think I can take care of this issue if @zestrells doesn't have time for it atm. 
Thanks!

**Comment by mrbobbytables** [comment]
@Evalle As its been some time and it's open, I think you can go for it :) Please feel free to assign

**Comment by Evalle** [comment]
@mrbobbytables thanks! 
/assign
