### ISSUE TITLE
contribex meetings updated in sigs.yaml

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4111]
need to have the mentoring and contributor documentation meetings updated with times/dates/other info in sigs.yaml (in the root of kubernetes/community)

also need to remove the meeting information for the noncode guide since that is flowing into the contributor documentation meeting

contribex meeting agenda has all of the above information in detail on the first page
[meeting notes](https://docs.google.com/document/d/1qf-02B7EOrItQgwXFxgqZ5qjW0mtfu5qkYIF1Hl4ZLI/edit?usp=sharing)

update meetings that need to be updated and their times:
triage meeting (under the biweekly meeting): bi weekly 1030a-1130a Weds https://zoom.us/j/712527529
apac meeting (community management subproject) 9-930pm PT bi weekly wednesdays
https://zoom.us/j/712527529
upstream marketing (community management subproject) fridays @ 8am-9am PT 
https://zoom.us/j/596959769

**Comment by vishakhanihore** [comment]
@parispittman I would like to contribute to it.

**Comment by parispittman** [comment]
@vishakhanihore please do :)

**Comment by vishakhanihore** [comment]
@parispittman A little help, I can see there are places for `Day,Date,Time,Description` for meetings in `sigs.yaml`, But where do I find `mentoring and contributor documentation` to add in `sigs.yaml` ?

**Comment by parispittman** [comment]
you can find those on the meeting agenda @vishakhanihore. there is a link to that in sigs.yaml as well. you may need to join kubernetes-dev@googlegroups.com if you are having access problems and can't view. thanks for helping, too!! :)

**Comment by vishakhanihore** [comment]
> you can find those on the meeting agenda @vishakhanihore. there is a link to that in sigs.yaml as well. you may need to join [kubernetes-dev@googlegroups.com](mailto:kubernetes-dev@googlegroups.com) if you are having access problems and can't view. thanks for helping, too!! :)

Thanks for the perfect explaination. 
@parispittman Can you please help me in drafting my final application for outreachy? Since I want to apply for `Technical Writer`, I am unable to figure out what to mention in my timeline?

**Comment by vishakhanihore** [comment]
> you can find those on the meeting agenda @vishakhanihore. there is a link to that in sigs.yaml as well. you may need to join [kubernetes-dev@googlegroups.com](mailto:kubernetes-dev@googlegroups.com) if you are having access problems and can't view. thanks for helping, too!! :)

Great, I joined the group! PR will be ready in day

**Comment by vishakhanihore** [comment]
@parispittman I see the `sign.yaml` already has a section for `sig-contributor-experience` and in the following there are sub-projects, Do I need to add another `subproject` with information mentioned in meeting notes ?

**Comment by mrbobbytables** [comment]
FYI - there are a few meeting decisions in flight, should have consensus on this early next week 👍
The 5 that will be updated/added are: 
- biweekly meeting
- triage meeting
- biweekly apac meeting
- marketing meeting
- mentoring meeting

**Comment by SomtochiAma** [comment]
Hey, New contributor here, Can I pick this up?

**Comment by mrbobbytables** [comment]
Here are the current updates that need to be applied, the Mentoring meeting time is still TBD.
- Meetings:
  - Regular SIG Meeting
    - url: https://zoom.us/j/397264241
  - Biweekly Issue Triage 
    - day: Wednesday
    - time: 10:30
    - tz: PT
    - frequency: biweekly
    - url: https://zoom.us/j/308291410 
    - recordings_url: https://www.youtube.com/watch?v=EMGUdOKwSns&list=PL69nYSiGNLP2x_48wbOPO0vXQgNTm_xxr
- Subprojects:
  -  community-management
      - meetings:
        - APAC Coordinator Meeting
           - url: https://zoom.us/j/144440337
        - Marketing Team Meeting
           - day: Friday
           - time: 8:00
           - tz: PT
           - frequency: Weekly
           - url: https://zoom.us/j/596959769
           - recordings_url: https://www.youtube.com/watch?v=EMGUdOKwSns&list=PL69nYSiGNLP2x_48wbOPO0vXQgNTm_xxr
