### ISSUE TITLE
looking for one more zoom and youtube admin

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4112]
looking for another zoom and youtube admin to take my place as a admin and moderator. i will mentor. there is a level of trust that comes with this role and would like to see folks who have been contributing to the project for a bit take it. its been two years of me in this role and it's time to let someone else take the wheel. 

[zoom guidelines](https://github.com/kubernetes/community/blob/master/communication/zoom-guidelines.md)
[youtube guidelines](https://github.com/kubernetes/community/blob/master/communication/youtube/youtube-guidelines.md)
[moderators](https://github.com/kubernetes/community/blob/master/communication/moderators.md)

**Comment by markyjackson-taulia** [comment]
@parispittman i can help here if needed

**Comment by onlydole** [comment]
@parispittman - I'd be happy to help out with this too!

**Comment by parispittman** [comment]
yay @onlydole !! file an issue template for moderator in k/community for zoom/youtube. they are different credentials but the automation and things you'll find need both to make a smooth process. use me as a sponosor if you need. thank you again!!

**Comment by parispittman** [comment]
@markyjackson-taulia just saw that you volunteered, too! same thing as I said to Taylor above!! :) yay

**Comment by parispittman** [comment]
closing this issue as between the two of you, even if we get one more thats awesome! :) thanks again everyone!!
