### ISSUE TITLE
2019 Steering Committee Election Tracking Issue

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#4118]
This is a bit late -- but getting out there. Supersedes the kick off issue https://github.com/kubernetes/community/issues/3915.

| When       | Week | What                                                                     | Done    |
|------------|------|--------------------------------------------------------------------------|---------|
| 2019-09-12 | 0    | Stub election content in Community repo                                  | &#9745; |
| 2019-08-20 | 1    | Create voter exemption form                                              | &#9745; |
| 2019-08-20 | 1    | Generate voters.md                                                       | &#9745; |
| 2019-08-21 | 1    | **Election announcement sent to k-dev and begin soliciting nominations** | &#9745; |
| 2019-08-28 | 2    | Election status update sent ot k-dev                                     | &#9745; |
| 2019-09-04 | 3    | Election status update sent to k-dev                                     | &#9745; |
| 2019-09-10 | 4    | Send notification that election nominations close in 24hrs               | &#9745; |
| 2019-09-11 | 4    | **Nominations close at 5 PT**                                            | &#9745; |
| 2019-09-12 | 4    | Election prep begins (collating emails etc)                              | &#9745; |
| 2019-09-18 | 5    | **Voting begins - send out CIVS ballots**                                | &#9745; |
| 2019-09-25 | 6    | Election status update sent to k-dev                                     | &#9745; |
| 2019-10-02 | 7    | **Voting ends at 5pm PT**                                                | &#9745; |
| 2019-10-03 | 7    | **Announce election results at community meeting**                       | &#9745; |
| 2019-10-03 | 7    | **Publish blog post election recap**                                     | &#9745; |
| TBD        | TBD  | Election retro                                                           | &#9744; |

/area community-management
/committee steering
/sig contributor-experience

**Comment by castrojo** [comment]
We've checked in the fixes, the document is pretty detailed, I don't think we need a face-to-face retro unless steering really wants one, IMO this can be closed.

**Comment by dims** [comment]
@castrojo sounds good!

**Comment by nikhita** [comment]
> We've checked in the fixes, the document is pretty detailed, I don't think we need a face-to-face retro unless steering really wants one, IMO this can be closed.

There seem to be some more points in the [retro doc](https://docs.google.com/document/d/1La9ZJPdvgLRzVH_RvE3Tmmx7uw_de8x8Ca4HoCkH8R0/edit) that aren't crossed out yet. Could we keep this open until they are resolved (especially points related to the voter qualification bar and exemption)? Or maybe we should create a new issue for those? Wdyt?

I don't think this warrants a face-to-face retro immediately but it'd be nice to have a place to track this, so it doesn't get lost. :)

**Comment by mrbobbytables** [comment]
> I don't think this warrants a face-to-face retro immediately but it'd be nice to have a place to track this, so it doesn't get lost. :)

sgtm -- Maybe an issue in steering with the retro items that weren't covered?

**Comment by nikhita** [comment]
> Maybe an issue in steering with the retro items that weren't covered?

Good idea! Created https://github.com/kubernetes/steering/issues/140. :+1: 

Closing this issue since the retro items are moved to the steering one, and the election is over.
/close
