### ISSUE TITLE
Invalid owners files in sigs.yaml

### ISSUE THREAD

**Issue by geekygirldawn** [kubernetes/community#4125]
The following owners files in sigs.yaml are generating 404 errors:

sig-apps
https://raw.githubusercontent.com/kubernetes/kubernetes/master/staging/src/k8s.io/api/core/v1/OWNERS

sig-auth
https://raw.githubusercontent.com/kubernetes/kubernetes/master/pkg/controller/certificates/approver/OWNERS
https://raw.githubusercontent.com/kubernetes/kubernetes/master/plugin/pkg/admission/imagepolicy/OWNERS

sig-autoscaling
https://raw.githubusercontent.com/kubernetes/client-go/master/scale/OWNERS

sig-storage
https://raw.githubusercontent.com/kubernetes/kubernetes/master/staging/src/k8s.io/csi-api/OWNERS

sig-api-machinery (pull request fix pending #4124)
https://raw.githubusercontent.com/kubernetes/kubernetes/master/pkg/quota/OWNERS

I wasn't positive which owners files should replace most of these, so if someone could track them down and update sigs.yaml, that would be great. For the sig-api-machinery quota file, I think I found the correct owners file and created pull request #4124 to update just that one owners file in sigs.yaml

**Comment by nikhita** [comment]
Thanks for auditing these, @geekygirldawn :)

>  if someone could track them down and update sigs.yaml, that would be great. 

/help

For anyone who takes it up:

Most of the work involves tracking the OWNERS files and following up with SIGs. One suggestion for tracking these OWNERS files is to do a `git log -- <file-name>` to get the list of commits that touched the file. The latest commit would have removed the file and would contain more context about the change.

If you have any questions, please feel free to ask questions in #sig-contribex on the k8s slack. :rainbow:

**Comment by mrbobbytables** [comment]
Thanks @geekygirldawn -- Longer term I think this is something we should look into automate a bit. Walking sigs.yaml and checking for valid OWNERS shouldn't be too bad. Maybe schedule a report to run once every release? If there are any out of date, create a follow-up issue after the release.

**Comment by geekygirldawn** [comment]
Agreed! I was doing a little bit of analysis of owners files, and one of my scripts returned errors on these files, so it should be easy enough to automate :)

**Comment by geekygirldawn** [comment]
After a bit more digging:

**Comment by mrbobbytables** [comment]
It doesn't solve the problem, but I do plan to at least audit the ones in place this cycle.
Looping in steering for evaluation with the sig/wg checkins.
/committee steering
/assign mrbobbytables
/milestone v1.20

**Comment by spiffxp** [comment]
https://github.com/kubernetes/community/issues/5425 would be a good opportunity to catch these

**Comment by liggitt** [comment]
fixed sig-auth issues

/remove-sig auth

**Comment by ehashman** [comment]
Is this a dupe of https://github.com/kubernetes/community/issues/1913 ? Can we close one?

**Comment by dims** [comment]
found a few more urls we need to fix

```
[dims@dims-m1 11:28] ~/go/src/k8s.io/community ⟩ ~/go/src/github.com/dims/maintainers/maintainers check-urls
Running script : 12-23-2021 11:28:41
found invalid url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/pkg/master/OWNERS (http code: 404) at (114,7)
found invalid url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/pkg/registry/extensions/OWNERS (http code: 404) at (239,7)
found invalid url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/staging/src/k8s.io/api/core/v1/OWNERS (http code: 404) at (242,7)
found invalid url: https://raw.githubusercontent.com/kubernetes/client-go/master/scale/OWNERS (http code: 404) at (614,7)
found invalid url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/pkg/controller/cloud/OWNERS (http code: 404) at (824,7)
found invalid url: https://raw.githubusercontent.com/kubernetes/noderesourcetopology-api/master/OWNERS (http code: 404) at (1915,7)
found invalid url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/test/e2e/scalability/OWNERS (http code: 404) at (2101,7)
found invalid url: https://raw.githubusercontent.com/kubernetes-sigs/kube-scheduler-simulator/main/OWNERS (http code: 404) at (2196,7)
found invalid url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/staging/src/k8s.io/csi-api/OWNERS (http code: 404) at (2448,7)
done
```

**Comment by dims** [comment]
[updated version of tool](https://gist.github.com/dims/dcdfd3a783f297452ac3a22d4892f67d) from @spiffxp shows the same issues 

```
WARNING: sig-api-machinery/server-binaries is missing kubernetes/kubernetes/master/pkg/OWNERS
WARNING: sig-apps/workloads-api is missing kubernetes/kubernetes/pkg/registry/extensions/OWNERS
WARNING: sig-apps/workloads-api is missing kubernetes/kubernetes/staging/src/k8s.io/api/core/v1/OWNERS
WARNING: sig-autoscaling/scale-client is missing kubernetes/client-go/scale/OWNERS
WARNING: sig-cloud-provider/kubernetes-cloud-provider is missing kubernetes/kubernetes/pkg/controller/cloud/OWNERS
WARNING: sig-node/noderesourcetopology-api is missing kubernetes/noderesourcetopology-api/OWNERS
WARNING: sig-scalability/kubernetes-scalability-and-performance-tests-and-validation is missing kubernetes/kubernetes/test/e2e/scalability/OWNERS
WARNING: sig-scheduling/kube-scheduler-simulator is missing https://raw.githubusercontent.com/kubernetes-sigs/kube-scheduler-simulator/main/OWNERS
WARNING: sig-storage/kubernetes-csi is missing kubernetes/kubernetes/staging/src/k8s.io/csi-api/OWNERS
```
