### ISSUE TITLE
map for contrib summit

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4150]
logging issue so it doesn't go untracked

need a map of the floor for summit:
-sched
-signs

**Comment by mrbobbytables** [comment]
Noah offered to take a stab at it last week 👍 
/assign @qedrakmar

**Comment by qedrakmar** [comment]
Adding in @coderanger

**Comment by mrbobbytables** [comment]
map has been added to sched under information tab: https://kcsna2019.sched.com/info

**Comment by mrbobbytables** [comment]
Map was created and added 👍 
Going to go ahead and close this out.
/close
