### ISSUE TITLE
`Ready` condition for programatic decisions

### ISSUE THREAD

**Issue by soorena776** [kubernetes/community#4154]
Hi everyone!

In Crossplane project, we are tackling the problem of inter resource referencing (https://github.com/crossplaneio/crossplane/pull/874).  In summary, a resource `c` in some scenarios might need to retrieve the desired attributes of a referred resource `r`, which becomes available once `r`'s corresponding external resource is created.

Let's assume resource `c` is consuming `r`'s attribute `r.id`. `c` has to wait until `r`'s external resource is created and its status is populated. One way of doing this would be to instruct `c` to periodically poll `r` to check if `r.Status.Ready == True`,  and then read `r.id`. An alternative could be directly polling `r.id  != Empty`.

I am wondering if such programatic decision making based on a resource's `Ready` condition is aligned with the [API conventions], or `Ready` is only intended to be read by humans. 

Thanks!

[API conventions]: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md

**Comment by soorena776** [comment]
@kubernetes/sig-contributor-experience-proposals

**Comment by idealhack** [comment]
/remove-sig contributor-experience

since you're linking a doc from sig-architecture, you could try to talk to them.
