### ISSUE TITLE
Retire WG Resource Management

### ISSUE THREAD

**Issue by nikhita** [kubernetes/community#4157]
It was mentioned in the Community Meeting on [October 3](https://docs.google.com/document/d/1VQDIAB0OqiSjIHI8AWMvSdceWhnz56jNpZrLs6o7NJY/edit#heading=h.mt6ckbh4j4u0) that WG Resource Mangement will be sunset soon. This is a tracking issue for the same.

It also looks like the WG hasn't had meetings after [Jan 30 2019](https://docs.google.com/document/d/1j3vrG6BgE0hUDs2e-1ZUegKN4W4Adb1B6oJ6j-4kyPU/edit), so this seems apt.

/assign @derekwaynecarr @vishh 
/wg resource-management
working group organizers

/sig contributor-experience
to carry out some of the tasks required to sunset the wg

/committee steering
cc @kubernetes/steering-committee

**Comment by timothysc** [comment]
+1 from me.  
wg's are meant to be ephemeral and this started years ago.

**Comment by vishh** [comment]
+1 from me as well. Most of the projects shepherded by the working group are now fully managed by participating SIGs. I'd say the original mission of the WG is fully met!

**Comment by nikhita** [comment]
@vishh @derekwaynecarr Next step would be send an email to kubernetes-dev@googlegroups.com and community@kubernetes.io with a doc like [this](https://docs.google.com/document/d/1qZcAvuWBznR_oEaPWtwm7U4JNT91m8r9YOUvInU-src/edit#heading=h.jsw0l2t0ra8) to let the community know that the WG plans to disband.

After that's done, contribex can take point on the retirement procedures.

Ref: https://github.com/kubernetes/community/blob/master/sig-wg-lifecycle.md#steps

**Comment by hannibalhuang** [comment]
@derekwaynecarr @vishh hi guys we have interested in still hosting the resource management wg forward, would it be possible for us to do that ?

**Comment by jeremyeder** [comment]
Loved working with you all in this WG context.  See you on the other side.

https://twitter.com/jeremyeder/status/980816275013238785

**Comment by spiffxp** [comment]
@derekwaynecarr to open PR to disband
