### ISSUE TITLE
Link Broken - Edge Security Challenges

### ISSUE THREAD

**Issue by devdattakulkarni** [kubernetes/community#4164]
Following link seems to be broken.

https://github.com/kubernetes/community/blob/master/wg-iot-edge/whitepapers/edge-securuity-challenges

It it referenced from the wg-iot-edge README. It is also referenced in the community update slide deck:
https://docs.google.com/presentation/d/1Ozby628UmK91fGOoo_10YDSRJ0BVlUIx-YAF4iwlyOA/edit#slide=id.g62d1d3d748_0_2

**Comment by geekygirldawn** [comment]
It looks like that link is a typo with an extra u in security. The correct link should be:
https://github.com/kubernetes/community/tree/master/wg-iot-edge/whitepapers/edge-security-challenges

**Comment by rochfordk** [comment]
Have created PR#4165 to correct link https://github.com/kubernetes/community/pull/4165

**Comment by mrbobbytables** [comment]
PR has merged, link should be fixed.
Thanks @rochfordk for the quick fix :)
/close
