### ISSUE TITLE
question bank for survey

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4166]
this is one of the issues/tasks broken down from the #3969 (umbrella contributor survey) issue. this issue will close when the questions have been cleaned up and ready to ship. we have room for 1 more questions tops. need to figure out which questions are required to answer. 

1- How long have you been contributing to Kubernetes?
less than one year
one to two years
two to three years
three+ years

2- What level of the Contributor Ladder do you consider yourself to be on? (pick the highest if you are multiple OWNERs files)
-there's a contributor ladder?
-not yet a member but working on it
-member
-reviewer
-approver
-subproject owner

3- Are you interested in advancing to the next level of the Contributor Ladder?
-no
-yes
-if I had help/mentoring/support
-if i had more free time

4- What region of the world are you in?
(REMOVING: What timezone are you most often in? (Check your UTC offset here))
-list the same regions we did last year

5- How many other open source projects not in the Kubernetes ecosystem do you contribute to? (example nodejs, debian)
this is my first open source project!
1 other
2 or more

6- Please rate the below parts of the contribution process by how challenging they are, from 1 (not a problem) to 5 (a frequent blocker):
Code/Documentation review
Communication
GitHub tools and processes (not our customized tooling)
Finding the right SIG for your contributions
Our CI, labels, and crafted customized automation
Debugging test failures
Finding appropriate issues to work on
Setting up development environment
Having PRs rejected
Writing documentation and notes
Other/insert yours here

7- How often do you interact with Kubernetes GitHub via the following methods (1 - not at all, 5 - frequently):
GitHub website
Desktop application
Mobile
E-mail notifications

8- Do you agree with the following statements (1 - strongly disagree, 5 - strongly agree):
"I understand enough about how Kubernetes CI works to be able to diagnose my own PR failures"
"When something is broken in my PR, I can read the comments from CI and understand why"
"The number of test failures unrelated to my PR severely impacts my ability or desire to contribute"
"There are too many notifications to be helpful when I open a PR"

9- Does your employer support your contributions to Kubernetes?
yes i can contribute on company time
no i need to use my own time

10- How often do you contribute upstream (code, docs, issue triage, etc.)?
every day
several times a week
several times a month
a few times a year

11- What areas of Kubernetes do you contribute to? Please check all that apply.
Core code inside of kubernetes/kubernetes
Code inside of another repo in the kubernetes/* GitHub organization
Documentation
Testing & Infrastructure
Advocacy and events
Community & Project management; SIG Chair etc.
Plugins & Drivers (CSI, CNI, cloud providers)
Related projects (Helm, container runtimes, other CNCF projects, etc.)
Don’t contribute yet, hoping to start soon
I can contribute during the day but it's not officially supported //may need rewording

12 - Are there specific ways the project could make contributing easier for you?
open ended question

13 - How often do you attend the weekly Thursday community meeting live?
- never
- once a month 
- try to make it to all of them (3-4 a month)
- rarely, but I frequently watch the video and/or read the notes
- few times a year

14 - Which of the below would make you likely to attend more of the Community Meetings? Check all that apply.
Nothing, I attend and think they are great
Having a full agenda with descriptions posted several days ahead
Eliminating the demo at the beginning
Additional developer tips/news content
Using the meeting to discuss project-wide development topics & roadblocks
Fewer meetings in my personal schedule
Different timeslot for the meeting
Other:

15 - Some of the major projects contributor experience is working on are listed below, check one that is most important to you that we carry through to completion:
Mentoring programs for all contributor membership levels [link to community membership doc]
GitHub Management
Delivering valuable contributor summits at relevant events
Governance operations (youtube, zoom, etc.)
Keeping our community safe on our various communication platforms through moderation guidelines and new approaches
Cleaning up OWNERs files
Contributor Documentation (guide, noncode guide, developer guide, contributor site)

16- What is missing from that list entirely that's important to you/your SIG? Why?

17 - Of our various communications channels, please rate which ones you use and/or check most frequently on a 1-5 scale, where 1 is “never”, 3 is “several times a month” and 5 is “every day”.
Google Groups/Mailing Lists
Slack
discuss.kubernetes.io
Zoom video conferencing/meetings
Discussions on Github Issues and PRs
Unofficial channels (IRC, WeChat, etc.)
YouTube recordings (community meetings, SIG/WG meetings, etc.)
Google Docs/Forms/Sheets, etc (meeting agendas, etc)

18 - Which of these channels is most likely to reach you first for news about decisions, changes, additions, and/or announcements to the contributor process or community matters?
kubernetes-dev mailing list
Dedicated discuss.k8s.io forum for contributors
Contributor Experience mailing list
Slack
Twitter
A dedicated contributor site
Kubernetes blog
k/community repo in GH (Issues and/or PRs)

19 - Have you ever used the Help Wanted and/or Good First Issue labels on issues you file to find contributors?

20 - Have you watched or participated in an episode of our YouTube mentoring series Meet Our Contributors? If you have specific suggestions, leave them at the end of the survey.
no - didn't know this was a thing
yes - it was helpful
yes - it wasn't helpful
no - i don't need mentoring, guidance, or other resources

21 - Are you available to mentor other Kubernetes contributors through one or more of our many mentorship programs?
I'm inexperienced and don't know enough to mentor
Yes, please contact me (you'll include your email in the last question)
I am already mentoring (you'll include your email in the last question because you want swag!)
I would like to but I don't have the time / employer doesn't support it

22- How many Kubernetes Contributor Summits have you attended?
0
1
2
3+

23 -
Do you have any comments, questions, or clarifications for your answers on this survey? Leave the general feedback here. If you leave your email, we will circle back with you:

**Comment by mariantalla** [comment]
* Not sure if SurverMonkey supports it, but it may be worth adding an `Other (tell us more)` sort of option for Question 6, just to open up space for additional blokers/bottlenecks to come up.
* I noticed "demographics" in https://github.com/kubernetes/community/issues/3969  (and the question on timezones covers part of it, in my head). Would we want to add a `Do you identify as an underrepresented minority` question too?

**Comment by jberkus** [comment]
edits:

22 seems redundant with 21.

For 13 - How often do you attend the weekly Thursday community meeting live?

Please change:

    you can't make it but read the notes or watch the video

To:

   - Rarely, but I frequently watch the video

I'd like to separate the folks who watch the video once a year from the ones who do it weekly.

Also, I see we've elminated questions about contributor summits.  Not arguing with that decision, just making sure that it's intentional.

**Comment by parispittman** [comment]
@mariantalla great suggestions - added!

@jberkus - made all changes and added the 'how many contributor summits have you attended question' with a 0-3+ range. wdyt?

**Comment by mrbobbytables** [comment]
Possibly something to expand on `22- How many Kubernetes Contributor Summits have you attended?`

If you haven't been able to attend a previous summit or cannot attend the summit in San Diego, was there a particular reason why?
- Not attending KubeCon.
- Funding (no work support, or cannot afford to individually go).
- Not interested in attending.
- Helping at other co-located event.
- Attending other conference.
- Other.


Main reason for asking, we've had a lot of folk not sign up because of other commitments, it'd be nice to try and get a pulse on this sort of thing going forward.

**Comment by parispittman** [comment]
TESTING ONLY: https://www.surveymonkey.com/r/F6SG3GB
DO NOT expect your answers to stay; this is a sandbox link only for testing purposes. 

Please report any bugs, feedback, and last minute question suggestions in this issue.

**Comment by idealhack** [comment]
```
I can contribute during the day but it's not officially supported //may need rewording
```

this one seems more of an answer to _Does your employer support your contributions to Kubernetes?_ than _What areas of Kubernetes do you contribute to? Please check all that apply._

For the _areas_ question, also I don't see options for SIG Release or _Other (please specify)_.

**Comment by idealhack** [comment]
_Which of the below would make you likely to attend more of the Community Meetings? Check all that apply._ should have multiple choices instead of one.

**Comment by idealhack** [comment]
_Have you watched or participated in an episode of our YouTube mentoring series Meet Our Contributors? If you have specific suggestions, leave them at the end of the survey._ The link in question is broken because of extra space.

**Comment by parispittman** [comment]
> _Have you watched or participated in an episode of our YouTube mentoring series Meet Our Contributors? If you have specific suggestions, leave them at the end of the survey._ The link in question is broken because of extra space.

thanks @idealhack, addressed

**Comment by parispittman** [comment]
> _Which of the below would make you likely to attend more of the Community Meetings? Check all that apply._ should have multiple choices instead of one.

thanks @idealhack, addressed

**Comment by onlydole** [comment]
@parispittman - this looks FANTASTIC. Thank you for this, I’ll be happy to retweet it out once it goes live!

**Comment by markyjackson-taulia** [comment]
This is awesome @parispittman thank you for all this hard work!
Question: `20. Are you available to mentor other Kubernetes contributors through one or more of our many mentorship programs?`
Should a link be included to https://github.com/kubernetes/community/tree/master/mentoring

**Comment by mariantalla** [comment]
Hello! Just a couple of nits below. Happy holidays! 🎅

* Question 2: `What level of the Contributor Ladder do you consider yourself to be on? (pick the highest if you are multiple OWNERs files)` > missing an `in`, I think (_in_ multiple OWNERs files)
* The nit of nits on Question 5: `5. How many other open source projects not in the Kubernetes ecosystem do you contribute to? (example nodejs, debian)` > perhaps a comma to separate the sentence, and `for example: ` rather than `example` =>  `How many other open source projects, not in the Kubernetes ecosystem, do you contribute to? (for example: nodejs, debian)`. Very minor though, still makes perfect sense.
* Question 14: there's still a placeholder for a link: `[link to community membership doc]`
* (minor) Question 17 has `GH` in `kubernetes/community repo in GH (Issues and/or PRs)` (somewhat inconsistent with `GitHub` elsewhere but not a huge deal)
* (sorry if this is covered elsewhere) In Question 22, `Not attending KubeCon`, `Not interested in attending` and `Attending other conference` could overlap for folks 🤔In which case it might be worth clarifying 🤔

**Comment by cblecker** [comment]
Question 3: If you're already a subproject owner (Q2), then you can't "advance" technically. There should be an option added "no, as I'm already a subproject owner"

**Comment by spzala** [comment]
@parispittman awesome overall. Few comments below. Thanks! 
7. Do you agree with the following statements (1 - strongly disagree, 5 - strongly agree):
Comment: The first and second statements related to CI seems redundant. 
10. What areas of Kubernetes do you contribute to? Please check all that apply.
Comment:  Suggest to move "Don’t contribute yet, hoping to start soon" before "Other"
14. Some of the major projects contributor experience is working on are listed below, rank the ones that are most important to you (and/or your SIG)
Comment:  Suggest to use SIG Contributor Experience (i.e.g Some of the major projects SIG Contributor Experience is working....) 
17. Which of these channels is most likely to reach you first for news about decisions, changes, additions, and/or announcements to the contributor process or community matters?
Comment: Suggest to add "Other (please specify)"

**Comment by cblecker** [comment]
@spzala the similar statements in question 7 are intentional. They are different enough that we can determine subtleties if you agree with one but not the other

**Comment by spzala** [comment]
> subtleties

@cblecker :) OK, sounds great. I just wanted to make sure that it doesn't confuse the reader, thanks for clarifying it!

**Comment by parispittman** [comment]
thanks all - will revise in a few hours and then post back here with updates! 🚀

**Comment by parispittman** [comment]
all changes are live. only a few of the nits couldn't happen like reordering of multiple choice answers re: sahdev. will check to see if we can do this before we go live. thanks all!

**Comment by mrbobbytables** [comment]
I do have a few small nits:
---
_11- What areas of Kubernetes do you contribute to? Please check all that apply._
For the option: 
`Code inside of another repo in the kubernetes/* GitHub organization`
If this is meant for all the k-orgs, it might be better as something like:
`Code inside another repo within one of the Kubernetes GitHub Organizations (e.g. kubernetes or kubernetes-sigs).`

---
_13 - How often do you attend the weekly Thursday community meeting live?_

Since we've moving to monthly, this might be better phrased as:
`How often did you attend the weekly Thursday community meeting live?`

**Comment by spzala** [comment]
> all changes are live. only a few of the nits couldn't happen like reordering of multiple choice answers re: sahdev. will check to see if we can do this before we go live. thanks all!

@parispittman awesome!! No worries about reordering. Thanks!!

**Comment by parispittman** [comment]
all changes have been made. target send out monday (6th) to k-dev@ mailing list. 

collecting final approval from @nikhita @cblecker and @Phillels (elsie approved via slack)

**Comment by parispittman** [comment]
nikhita also approved via slack.

**Comment by dims** [comment]
Q3 : please move `no` as the last option. please prefix the others with `yes. ...`
Q19 : group all the `yes` before the `no`s please

Looks great thanks @parispittman

**Comment by cblecker** [comment]
Approved

**Comment by parispittman** [comment]
@dims corrections made; thank you

updates:
https://www.surveymonkey.com/r/VYRJZ5G - this is the real survey. drafting language for k-dev@ email now and will have folks review from slack to be sent from contributors@. wait for this to send to your contributor groups.

**Comment by parispittman** [comment]
survey went out; closing issue

/close
