### ISSUE TITLE
Question about Flex volumes

### ISSUE THREAD

**Issue by furkanmustafa** [kubernetes/community#4171]
On [Volume Plugin FAQ](https://github.com/kubernetes/community/blob/704d38f63cedb5ff52946428c52e578bd93dc00a/sig-storage/volume-plugin-faq.md) page, it lists the limitations of Flex Volume.

1. FlexVolume requires root access on host
2. FlexVolume requires tools(mount, etc.) to exist on host, thus again requiring root access (and package managers, etc.) to install them.

I am confused about how CSI would be any different. Can someone explain?
( The document is commited by @saad-ali )

Thanks

/label community/question
/label sig-storage (cannot be added by just leaving it like that for now)

**Comment by furkanmustafa** [comment]
@k8s-ci-robot you're funny

**Comment by jingxu97** [comment]
cc @saad-ali

**Comment by saad-ali** [comment]
> FlexVolume requires root access on host

This should've been worded better. The intention was to point out that a standard Flex driver requires users to copy a Flex driver file to a specific directory on each node. This requires direct machine access beyond the Kubernetes control plane. With CSI you simply deploy a Kubernetes workload to install the CSI driver on all nodes (and automatically on any new nodes that may be added to the cluster later). 

Arguably you could deploy a Flex driver using a DaemonSet and a hostpath volume, which would negate this difference.

> FlexVolume requires tools(mount, etc.) to exist on host, thus again requiring root access (and package managers, etc.) to install them.

CSI drivers are containerized. Which means the user space utilities the driver depends on can simply be included in the driver container image. With a Flex driver, the utilities must be installed on the host.

**Comment by furkanmustafa** [comment]
Thanks for the explanation!

Maybe the wording can be focused around the two points;

* CSI is invoked through network (unix socket only?) (Flexvolume requires direct invocation)
* CSI allows running everything inside a container (Flexvolume does not, requires modifying host)
* Requiring root access is not much different, but can be quite confined in CSI's case, because of two points above.

Is my understanding above correct?

Also, when the kubelet is containerized, flexvolume MUST be in the same container this time, instead of host, right? (or use shared volumes with kubelet)

**Comment by saad-ali** [comment]
> * CSI is invoked through network (unix socket only?) (Flexvolume requires direct invocation)
> * CSI allows running everything inside a container (Flexvolume does not, requires modifying host)
> * Requiring root access is not much different, but can be quite confined in CSI's case, because of two points above.
> Is my understanding above correct?

Yep, that seems correct to me.

> Also, when the kubelet is containerized, flexvolume MUST be in the same container this time, instead of host, right? (or use shared volumes with kubelet)

Yep, that's right.

One more thing I would add is that for master control plane operations (like volume attach), CSI allows the master component to be deployed on a node machine, whereas Flex requires a driver file to be installed on the master along with the kube-controller-manager. This makes some Flex drivers infeasible in Kubernetes environments where the master is not exposed.

**Comment by parispittman** [comment]
looks like this is safe to close. should these move to the keps repo?

/close
