### ISSUE TITLE
Update WG Policy leads

### ISSUE THREAD

**Issue by nikhita** [kubernetes/community#4185]
It was mentioned in https://github.com/kubernetes/community/issues/3945#issuecomment-517421709 and https://github.com/kubernetes/community/issues/3945#issuecomment-517499806 that some of the leads listed in sigs.yaml for wg-policy aren't active anymore. So it should be updated to reflect the current state.

/wg policy
/committee steering
/kind cleanup
/assign @hannibalhuang @ericavonb

**Comment by vishakhanihore** [comment]
@nikhita Can I update the following for the changes ?

**Comment by hannibalhuang** [comment]
> @nikhita Can I update the following for the changes ?

if you could help with the update, please also add @rficcaglia as the third co-lead

**Comment by mrbobbytables** [comment]
@hannibalhuang before they're added, they should apply for org membership. The original issue that this is referencing was to ensure that all leads are org members.

**Comment by rficcaglia** [comment]
Bob - is there a link for org membership for an individual?

**Comment by mrbobbytables** [comment]
@rficcaglia membership guidelines can be found here:
https://github.com/kubernetes/community/blob/master/community-membership.md#member

**Comment by rficcaglia** [comment]
ok I signed the document and linked my github account. for the issue with
sponsorship are you my sponsors that I put in the GHI? Or do I need someone
else?

**Comment by mrbobbytables** [comment]
@rficcaglia I would recommend the other wg-policy leads as a starting point 👍 sponsors are generally folk that you've interacted with.

**Comment by mrbobbytables** [comment]
@hannibalhuang @rficcaglia poking again about this. It's been a month and the other issue (#3945) has been open for almost 6 months. =/

**Comment by rficcaglia** [comment]
I think I just need Erica to add herself as the second sponsor?

**Comment by mrbobbytables** [comment]
That would be ideal -- once you have your sponsors lined up, just need to open up an issue in k/org - https://github.com/kubernetes/community/blob/master/community-membership.md#member

**Comment by ericavonb** [comment]
@mrbobbytables I would be honored to sponsor @rficcaglia. Do I need to add a comment somewhere else?

**Comment by mrbobbytables** [comment]
Once he opens the k/org issue, you'll want to chime in with a +1 on there 👍

**Comment by mrbobbytables** [comment]
@rficcaglia Can you please go ahead and open the membership request? We'd really like to close this out. 😬

**Comment by rficcaglia** [comment]
sure - one problem I always hit is that neither Zhipeng or Erica show up in
github so I can't @them.  I don't know if it's something weird in my
browser or what but FWIW I added the ghi:
https://github.com/kubernetes/org/issues/1618
