### ISSUE TITLE
De-dupe developer/contributor information

### ISSUE THREAD

**Issue by monopole** [kubernetes/community#420]
@bgrant0607 recently noted that [Our Developer/Contributor Docs Need Love](https://groups.google.com/forum/#!topic/kubernetes-wg-contribex/ucUPGVKhkQI).

One aspect of that is removal of duplicated or outdated info.

To close this issue, in the [code repo](https://github.com/kubernetes/kubernetes), replace all long discussions of code contribution with shorter text pointing to the right spots in the [community repo](https://github.com/kubernetes/community).  As necessary, move or merge text to community.

**Comment by bgrant0607** [comment]
cc @grodrigues3
