### ISSUE TITLE
Secrets Storage

### ISSUE THREAD

**Issue by MeenaAlfons** [kubernetes/community#4207]
Currently, Secrets are stored in `etcd`. I've been looking for a way to change the backend storage for Secrets but didn't found any. I also found that my expectations are aligned with the [Secrets design document](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/auth/secrets.md). Here are some quotes from it:

> **Constraints and Assumptions**
> This design does not prescribe a method for storing secrets; storage of secrets should be pluggable to accommodate different use-cases

> **Data store backing the REST API**
> The data store backing the REST API should be pluggable because different cluster operators will have different preferences for the central store of secret data. Some possibilities for storage:
> 
> 1. An etcd collection alongside the storage for other API resources
> 2. A collocated HSM
> 3. A secrets server like Vault or Keywhiz
> 4. An external datastore such as an external etcd, RDBMS, etc.

1. Could someone confirm or deny that this aspect of the Secrets design is not currently implemented or supported by the current implementation?
2. How can I implement a plugin to allow different storage for Secrets?
3. If no way currently exists, How can I help to implement this feature in Kubernetes?

Thank you.

**Comment by MeenaAlfons** [comment]
I thought about achieving the same purpose by making a Custom Resource Definition and found a nice implementation at [godaddy/kubernetes-external-secrets](https://github.com/godaddy/kubernetes-external-secrets).

This for the record for those searching for a solution. But the questions in the original post still stands. What is the direction of Kubernetes regarding the storage of Secrets?

**Comment by mrbobbytables** [comment]
@MeenaAlfons The community repo is used as the general management point of Kubernetes contributor community. Questions like that are not likely to be answered here. =/

I'd ask it over in the #sig-storage slack channel or on their mailing list.

With that I'm going to go ahead and close this out, if you have any questions feel free to respond or reach out to me directly.

/close
