### ISSUE TITLE
Create official shortcut link for our CoC

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#4219]
The official location of our CoC is at https://github.com/kubernetes/community/tree/master/committee-code-of-conduct, which is a difficult URL to fit into a text-only email, or to copy by hand from a slide projected on a screen.  Given how often we direct people to this, it needs to be shorter (and a shortcut link would also let us move the canonical location).

Can we create an official shortcut link for the CoC on k8s.io or another link shortener?  I've created a temporary one on bit.ly/K8sCoC, but that's my personal account and as such not long-term.

**Comment by cblecker** [comment]
Does https://git.k8s.io/community/code-of-conduct.md work?
/sig contributor-experience

**Comment by jberkus** [comment]
giving up on this.

/close
