### ISSUE TITLE
Call for Community Bridge interns

### ISSUE THREAD

**Issue by idvoretskyi** [kubernetes/community#4220]
[Community Bridge](https://communitybridge.org) is a platform developed by the Linux Foundation, which offers mentorship opportunities (besides many others).

This year, CNCF has started participating in the Community Bridge, sponsoring three students to work on Kubernetes and CoreDNS projects during the programs’ pilot stage - see https://www.cncf.io/blog/2019/08/22/cncf-hosts-three-student-internships-for-kubernetes-and-coredns-projects-through-linux-foundations-communitybridge/.

We are going to run another round of Community Bridge mentorship program in December, and happy to offer for Kubernetes at least one slot in the program, preferably offering mentorship opportunities for the underrepresented groups in tech.

Let's use this issue to identify the areas where inters may participate.

/assign @parispittman @nikhita

**Comment by parispittman** [comment]
would like to remain with outreachy and gsoc for interns and community bridge for contractors that are experienced. We should be choosing diverse pipelines only and I don’t see that from community bridge at the moment. What’s the roadmap/strategy on making connections with those communities?

**Comment by idvoretskyi** [comment]
> What’s the roadmap/strategy on making connections with those communities?

This shouldn't be an issue as the program is backed by the Linux Foundation.

Also, one of the biggest benefits of the Community Bridge is that it's way more flexible than the comparable programs, eg. the Community Bridge doesn't set a specific timeline for a project and a student (it's up to project and mentor to decide on the timeline).

I'm happy to chat in San Diego at KubeCon about this more though.

**Comment by sladyn98** [comment]
@idvoretskyi Hey I read about the project on the community bridge website, and I would like to be a student for the December round, I began looking around the k8 testing infrastructure as a starting point for my contributions, is there a specific list of projects that I can take a look at?
Thanks and cheers.

**Comment by sladyn98** [comment]
CC : cc @nikhita @parispittman

**Comment by idvoretskyi** [comment]
@sladyn98 please see https://github.com/cncf/soc/blob/master/communitybridge/README.md

**Comment by nikhita** [comment]
@idvoretskyi can this issue be closed? the interns have already been selected, right?

**Comment by sladyn98** [comment]
Have the interns already been selected or are there any slots still left ?

**Comment by idvoretskyi** [comment]
@nikhita for Kubernetes - yes.

/close

@sladyn98 the program was publicly announced around a month ago, together with the call for applications - https://www.cncf.io/blog/2019/12/05/cncf-to-participate-in-the-community-bridge-mentorship-program/.

We already have Kubernetes mentees selected, but there are still a few other projects in progress. Also, feel free to apply for the next round of the Community Bridge program (to stay informed please track the CNCF blog announcements and the https://github.com/cncf/soc repo).
