### ISSUE TITLE
contrib summit feedback for shanghai and san diego

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4230]
need to PR in the feedback (https://github.com/kubernetes/community/blob/master/events/events-team/feedback.md) and retros for the following

shanghai links for 2018 feedback and 2019 retro are below from yang. 
still need 2018 retro and 2019 feedback

san diego retro: https://docs.google.com/document/d/1mDHxPAbwyy7CSrk7G__Qts6FkhuwuCUQ23RnHpJpVUQ/edit
still need san diego feedback

**Comment by idealhack** [comment]
This is what I can find:

- Shanghai 2019 retro: https://docs.google.com/document/d/13aeCb6Rfy0XM2uOhEhIZJZM2ykg-j2IgxsTdNbt2_TI/edit
- Barcelona retro: https://docs.google.com/document/d/1pwVJLPLJtv_vyLFF3BTuuZ24yEn0TJbxihd1I_e4p48/edit
- Shanghai 2018 feedbacks: https://docs.google.com/spreadsheets/d/1HLhpUwMSZlU_bkCsLgeMdB6jUBLOV9m81p7qicVXC6M/edit

**Comment by debgiles** [comment]
Here are the links I have.  I'm not 100% comfortable editing that feedback page, as it's opened very different than I'm used to, but let me know if there's something else I can do to get them added.

Shanghai
Retro - https://docs.google.com/document/d/13aeCb6Rfy0XM2uOhEhIZJZM2ykg-j2IgxsTdNbt2_TI/edit#heading=h.7zrpue9bmixk
NCW Feedback - https://drive.google.com/open?id=1PhBMtacE567SH7sMyxdDGhAC8UYx3wav
Active Feedback - https://drive.google.com/open?id=1VATvp0tUggzEF8nff8xSHUzSu8ECGxNo

San Diego
Retro - https://docs.google.com/document/d/1mDHxPAbwyy7CSrk7G__Qts6FkhuwuCUQ23RnHpJpVUQ/edit#heading=h.v03voxdwxi2r
NCW Feedback - https://docs.google.com/spreadsheets/d/1qfWcCsuXdrpl49bMiFS9ID3yXpC7lRJDvOd8eoxRvSg/edit#gid=1846336934
Active Feedback - https://docs.google.com/spreadsheets/d/1bnuB3aLRwSB2FaDZCWfARQ5TBiApyKU8Elv6bprxfzI/edit#gid=4535733
