### ISSUE TITLE
REQUEST: New moderator for idealhack of YouTube & Zoom

### ISSUE THREAD

**Issue by idealhack** [kubernetes/community#4231]
### GitHub Username

@idealhack

### Property you'd like to Moderate

YouTube & Zoom

### Username on Property Requested

idealhack(at)gmail.com

### Requirements

- [x] I am a Kubernetes Org member already
- [x] I have enabled 2FA on my account for the property I would like to moderate (if applicable)
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mrbobbytables 
- @castrojo 

### List of qualifications for this position

- would like to provide more time zones coverage in UTC+9
- regular contributor of sig-contribex, organizing the APAC coordinator team
- current moderator of Discuss and Slack

**Comment by mrbobbytables** [comment]
+1 from current mod on both

**Comment by castrojo** [comment]
+1 from me on both!
