### ISSUE TITLE
Need to disable spellcheck test or find some other location for meeting notes

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#4249]
Per #4247, we currently have a CI presubmit that checks English spelling.

This makes a lot of sense for, say, SIG profiles.  It does not make sense for meeting notes from things like contributor summits.

Should we find a different location for notes, or should we disable this presubmit on specific directories?

**Comment by tpepper** [comment]
It feels like already in the linked PR and in this issue more work has gone into discussing spelling than it would've taken to fix the five tiny typos in the first place and re-push an amended commit.

Misspellings can genuinely be a barrier to entry for readers and is something quite easy to address.

**Comment by jberkus** [comment]
It's not so much that PR as that asking people to create a PR, that has to pass presumbit tests, in order to save notes from a meeting, is probably the least likely way to result in anyone sharing any notes that I can think of.

We need to upload notes to a place with minimum barriers to speedy upload, or even one that would permit live note-taking during the session.  This GH repo isn't it.

**Comment by cblecker** [comment]
/sig contributor-experience

I agree with Tim here. Another benefit of the spell check is it prevents sucking up future reviewer time by needing to review small spell check PRs in the future. Get all the revisions in at once.

**Comment by jberkus** [comment]
Y'all have your priorities skewed.

The #1 problem for community meetings is that people don't take notes at all, or that the notes they do take are inadequate, or that they do take notes but never upload them.  Readability of the notes is not a priority if there are no notes.

Right now, our priorities as expressed by how we have this set up is "We would rather not have notes at all than have messy notes."  That's not a prioritization I agree with, nor do I think most of the community would.

I think the solution to this is to have a different place to share notes than by PR into this repo; the PR process is much more of a barrier than the CI spellcheck, and doesn't allow for collaborative note-taking.  Then, after the notes are uploaded, someone can clean them up and merge them into the repo.  Not sure where this should be; GDocs tends to bog down on conference wifi.

**Comment by parispittman** [comment]
why can't we upload the doc to the hack.sh file so it skips the check?

**Comment by jberkus** [comment]
Works for me.  Up to the folks running CD-AMS, of course.
