### ISSUE TITLE
Feature Submission template has to be enhanced - umbrella issue

### ISSUE THREAD

**Issue by idvoretskyi** [kubernetes/community#425]
This is an umbrella issue to collect the feedback from the community.

Existing feature submission template [1] has to be enhanced and simplified before 1.7 features acceptance will be open.

1. https://github.com/kubernetes/features/blob/master/ISSUE_TEMPLATE.md

**Comment by idvoretskyi** [comment]
cc @kubernetes/features-maintainers @kubernetes/kubernetes-pm

**Comment by idvoretskyi** [comment]
Template v2 is described in the [document](https://docs.google.com/document/d/1-D_QP2IC5Z_QJUmTOV24IsFknc9pGPU5xeq6gjP4f38/edit) and proposed at https://github.com/kubernetes/features/pull/204.

**Comment by grodrigues3** [comment]
Closing since new template is merged.  Reopen if needed
