### ISSUE TITLE
ssh to kube nodes? [AWS]

### ISSUE THREAD

**Issue by alouane** [kubernetes/community#427]
Hi there,
How is it possible to ssh to a particular kube node [AWS environment], where I can find the pem file? I looked in **kubernetes/cluster/aws/util.sh** but nothing could link me out to the pem file location, I got only the fingerprint used to create the aws key

Thanks

**Comment by kris-nova** [comment]
How did you deploy the cluster? If you used a tool like kops you specified the key at runtime and you should have it on your local file system

**Comment by alouane** [comment]
well I actually used kube-up.sh script => **[https://kubernetes.io/docs/getting-started-guides/aws/](https://kubernetes.io/docs/getting-started-guides/aws/)**

**Comment by talk2vino** [comment]
@alouane 

The perm file should be in $HOME/.ssh/kube_rsa

``` ssh -i <path of the private key file>  admin@<ip of the aws kube instances> ```

hope this help

**Comment by alouane** [comment]
Yep I got it

Thanks @talk2vino
