### ISSUE TITLE
Wrap up SD Contributor Summit

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4280]
- [x]  survey 
- [x] retro
- [ ]  blog post (+ follow up kdev with blog post link)
- [x]  wrap up email to all attendees
- [x]  picture album
- [x]  youtube videos
- [ ]  upload feedback and retro to events folder: https://docs.google.com/document/d/1mDHxPAbwyy7CSrk7G__Qts6FkhuwuCUQ23RnHpJpVUQ/edit#heading=h.v03voxdwxi2r - retro

**Comment by mrbobbytables** [comment]
I think enough time has passed where we can probably skip the blog post. :x
