### ISSUE TITLE
Form Application Performance and Benchmarking subproject for SIG-Scalability

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#4286]
Per discussion with SIG-scalability leads and other interested parties, I'd like to start the process of forming a new subproject of SIG-Scalability, "Application Performance and Benchmarking".  The goal of this subproject would be to pool the efforts of the current various benchmarking efforts around applications on Kubernetes, provide a place to share and publish results for the education of users, and eventually to develop and add some automated application performance tests to Testgrid.

In order to launch the subproject, we'll need to determine the initial owners and a formal statement of scope, as well as where we want to store benchmarking configuration, examples, and data.

cc SIG chairs:
@wojtek-t @shyamjvs 

some interested contributors:
@aakarshg @sagyvolkov @tduzan

/sig scalability
/kind subproject

**Comment by wojtek-t** [comment]
FYI - I'm no longer a chair - I moved to the TL role. @mm4tt replaced me in chair role

That said, I support creating that subproject - it's one of the things that wasn't getting enough attention from us.

I propose discussing this in a bit more details on the next SIG meeting on Dec 5th.

**Comment by mm4tt** [comment]
Sorry for not looking at this earlier, I was OOO for the last 2 weeks.

I second what Wojtek has said, +1 for creating the subproject.

**Comment by rsevilla87** [comment]
@mm4tt I'm also interested on creating this subproject.

**Comment by wojtek-t** [comment]
@jberkus already said that he will work on creating a charter for this subproject; there are more people interested in it.

**Comment by wojtek-t** [comment]
Josh already created a charter and directory: https://github.com/kubernetes/perf-tests/pull/1030
We will continue there.

/close
