### ISSUE TITLE
Proposal: IPvS implementation for KubeProxy

### ISSUE THREAD

**Issue by boynux** [kubernetes/community#429]
# Overview:

The current proxy with IPTables implementation has some limitations.

* The most problematic one is inability to pass-through the original request IP address. 
* The other issue is load distribution algorithms over the origins.

Many applications rely on request source address information to work normally. Most layer 7 proxies like NginX or HAProxy can add "X-Forwarded-For" header to the original request. The issue is it mostly works with HTTP requests but not all TCP and UDP requests.
On the other hand at the moment there is no way to define how the traffic should be distributed across the origins (it relies on iptables round-robin)

# Motivation

[IPvS or LVS](http://www.linuxvirtualserver.org) is a kernel module that can provide various forms of layer 3 loadbalancing without relying on iptables. Two main reasons to use LVS are:

* [Direct Routing](http://www.linuxvirtualserver.org/VS-DRouting.html), can preserve the request IP header information (via Virtual IPs) 
* We can use different [routing algorithms](http://www.linuxvirtualserver.org/docs/scheduling.html) Like least connection or weighted routing

# Limitations

Although other routing models like LVS/NAT support port mappings but LVS/DR does not. Which means services will not be able to map their ports to different Pod ports if DR mode is enabled.

# Related works:

Currently Docker Swarm using the method

# Design

## Kube Proxy

* Operates in this new modes LVS/NAT or LVS/DR.
* Adds new origins and remove obsolete ones from IPvS kernel module (LinuxDirector).
* Injects virtaul IPs into Pods if it operates in DR mode.
* Enable IPvS NAT in iptables if operates in NAT mode (using xt_ipvs)

## Pods

* If KubeProxy operates in DR mode pods need to use the assigned Virtual IP to communicate to the client.

**Comment by quinton-hoole** [comment]
We have a tested implementation of IPVS kubeproxy in https://github.com/kubernetes/kubernetes/issues/44063
Busy tying the various related issues and PR's together now.

**Comment by cmluciano** [comment]
xref: https://github.com/kubernetes/community/pull/692

**Comment by cmluciano** [comment]
IPVS is now supported in beta form
