### ISSUE TITLE
zoom main account needs to change

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4291]
currently logging in as: k8szoom@gmail which is an account @castrojo and I share.
Should be: contributors@kubernetes.io

two things:
1-cncf needs to get zoom to change this for us because you can't update an email in zoom for the license you have to delete the license and then establish a new one. OR we may be able to add contributors@ as a license holder and then delete the other one, etc. [insert administrivia here]
2- all of the recurring meetings under k8szoom@ will need a new home which will generate new links and therefore need to be updated in their appropriate calendar invites.

only zoom/youtube admins can make these changes.

**Comment by castrojo** [comment]
/assign

I'll work on this next week.

**Comment by castrojo** [comment]
Changing the email via Zoom totally worked, licenses appear to work fine, etc. I'll leave this open while I inform the zoom admins of the password change.

**Comment by castrojo** [comment]
/close

This seems to have worked perfectly and everything has been updated, so closing this for now.
