### ISSUE TITLE
Domain registration

### ISSUE THREAD

**Issue by lukehinds** [kubernetes/community#4295]
Who can I contact that can acquire and manage domains for use in  k8's infrastructure (for functional tests)?

/sig security

**Comment by stp-ip** [comment]
@idvoretskyi knows the best process I assume

**Comment by caniszczyk** [comment]
under what domain? kubernetes.io? k8s.io? also what would the DNS records be?

**Comment by dims** [comment]
@lukehinds let's use https://github.com/kubernetes/k8s.io/ we maintain a bunch of infra stuff

**Comment by lukehinds** [comment]
We have an issue being handled in the product security committee and one part of a possible resolution under consideration requires a domain with a preference to not use anything with k8s, kubernetes, or CNCF in it. Do it being a private discussion I can't divulge in public why the specific need. This issue is to work out what any process would be or point of contact for requesting such a domain.

**Comment by cblecker** [comment]
@lukehinds Please reach out to dims and myself privately by email with some details around requirements and we can see what we can do.

/close
