### ISSUE TITLE
Need more active response from owners and members

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes/community#4296]
There are lots of issues lost response and inactive from community, for example, [issues from kubespray](https://github.com/kubernetes-sigs/kubespray/issues?q=is%3Aissue+is%3Aopen+sort%3Acomments-asc), more than 30% percent issues don't have any response.

And some PRs, for example ( I just take the example from our repo pool, it's NOT the ONLY one ), like [this PR](https://github.com/kubernetes/website/pull/16135#issuecomment-539112024), some members gave LGTM, and it's blocked by blog reviewer.

I know we're all spending our time to do such open source job, and it's reasonable to away from community jobs due to busy business job. But it hurts our users, since these issues don't have any response from community, we could close it if it's NOT reasonable, OR we could hold it if we could NOT fix it currently, but we should **do more active response**. As well as the PRs, we give LGTM, and story ends... 

I hope our community could give some active response about such things, and maybe we could setup some rules for this, like `let someone be emeritus approver if he/she is away from our community too long time` or `rotate the oncall member, let issue and PR could have response, even it is CLOSE/REJECT`.

Thanks.

**Comment by castrojo** [comment]
This is related to thi: https://github.com/kubernetes/community/issues/4149
