### ISSUE TITLE
REQUEST: New moderator for @jberkus of kubernetes Slack

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#4300]
### GitHub Username
@jberkus 

### Property you'd like to Moderate
slack.kubernetes.org

### Username on Property Requested
@jberkus 

### Requirements

- [X] I am a Kubernetes Org member already
- [X] I have enabled 2FA on my account for the property I would like to moderate (if applicable).
- [X] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [X] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @castrojo 
- @mrbobbytables 

### List of qualifications for this position

- Jorge asked me to rotate in to allow some of the existing Slack moderators to take a season off.
- Currently moderator of discuss.kubernetes.io
- 18 years experience moderating OSS mailing lists for the PostgresSQL, Fedora, OpenOffice, and other projects
- For that matter, moderator of several neighborhood groups on Facebook and formerly NextDoor, and a more wretched hive of harassment and petty insults you will never see.

**Comment by mrbobbytables** [comment]
+1

**Comment by idealhack** [comment]
+1 from current moderator

**Comment by jeefy** [comment]
+1

**Comment by onlydole** [comment]
+1

**Comment by castrojo** [comment]
/assign

+1 - ping me on slack at some point this week and we'll do the minutea.
