### ISSUE TITLE
Dead link for volume plugins inside CSI driver design proposal

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes/community#4330]
Hi team,

While reading the design proposal of CSI, I found the [volume plugins link](https://git.k8s.io/kubernetes/pkg/util/strings/escape.go#L27) from [kubelet-to-csi-driver-communication section](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/container-storage-interface.md#kubelet-to-csi-driver-communication) was out-dated.

In order to let our users don't be confused about that, we may need to update it.

Thanks.

**Comment by markyjackson-taulia** [comment]
Per https://github.com/kubernetes/kubernetes/pull/73455 the code in https://github.com/kubernetes/kubernetes/tree/master/pkg/util/strings/ was moved to https://github.com/kubernetes/utils/tree/master/strings. So the documentation should reference https://github.com/kubernetes/utils/blob/master/strings/escape.go#L27

PR is https://github.com/kubernetes/community/pull/4340

**Comment by Colstuwjx** [comment]
Hi @markyjackson-taulia ,

I have been already submitted PR #4331 , no need to repeat it.
Thanks.

**Comment by markyjackson-taulia** [comment]
Oh my, I totally did not see that and I apologize.

**Comment by markyjackson-taulia** [comment]
@Colstuwjx I closed my pr, totally sorry about that
/honk for find and getting the PR in
