### ISSUE TITLE
Include Contribution Best Practices Section in  Contributor Guide

### ISSUE THREAD

**Issue by vishakhanihore** [kubernetes/community#4333]
I propose to add a section for `Contribution Best Practices` which may include some basic courtesy like:
- Naming the commit, PR Description.
- Using GitHub Special Keywords and etc.

/area contributor-guide
/kind documentation
/sig contributor-experience

**Comment by mrbobbytables** [comment]
That sounds good to me :) 
We have a little bit here:
https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#6-squashing-and-commit-titles
but I know we're missing the guidelines like 'don't include `@<person>` in the commit msg etc.
Some other details here: https://github.com/kubernetes/test-infra/pull/9387

**Comment by vishakhanihore** [comment]
> That sounds good to me :)
> We have a little bit here:
> https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#6-squashing-and-commit-titles
> but I know we're missing the guidelines like 'don't include `@<person>` in the commit msg etc.
> Some other details here: [kubernetes/test-infra#9387](https://github.com/kubernetes/test-infra/pull/9387)

Hey @mrbobbytables Just made a PR, Lets discuss over there 😄
