### ISSUE TITLE
kick off sig chair/tl monthly shindig

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4364]
We've been kicking around the idea for a while. This is an optional (until folks say its valuable and we PR into governance) meeting for SIG Chairs/TLs. This meeting will cover topics around the operations and leadership of SIGs/WGs. (ideas: announcements, administrivia operations/how-tos/demos (examples: youtube automation, zoom, etc) setting up programs to grow more reviewers and approvers, open discussion, learning from each other, and more.)

Poll for chairs/tls:
https://www.doodle.com/poll/agzc4kncxnp5hasm 
If we have a fork in the poll with two times, I’ll happily do two meetings a month. As with all Kubernetes meetings, it will be recorded, notes will be taken, and issues filed in appropriate repos (community, steering, etc).

Looking for 1-2 others from contribex to help with this effort and run/curate meetings. 

this will complete a Chair/TL communication loop of the following:
-mailing list
-slack channel
-"need to know" email
-monthly meeting (result in agenda docs, issues/PRs, and youtube playlist)

**Comment by parispittman** [comment]
notes from mailing list thread:
@markyjackson-taulia @justaugustus @jimangel volunteered to help

**Comment by chris-short** [comment]
Happy to help where skills match (email, meeting running, etc.)

**Comment by parispittman** [comment]
two initial meetings set for this tues and thurs; kubernetes-sig-leads@ mailing list sent invite. #chairs-and-techleads for more info. 

will reach out to folks who said they can help post contribex update on weds/first meeting. 

/close
