### ISSUE TITLE
[Contributor Summit Amsterdam] Registration Phases

### ISSUE THREAD

**Issue by palnabarun** [kubernetes/community#4366]
The registration will open for Kubernetes Contributor Summit Amsterdam in phases.

#### Tentative Phases as of now:

- [x] January 27 - Registration for Active Contributor Track opens to Organisation members
- [x] January 27 - Registration for New Contributor Track opens to General Audience
- [ ] February 21 - Registration for Active Contributor Track opens to General Audience

#### Capacity for each track

Total: 350

NCW 101 65
NCW 201: 65
Active: 190
D&I: 50 (Included and spread over NCW 101, NCW 201 and Active)
Staff: 30

Reference: https://docs.google.com/spreadsheets/d/1L5v2NbGFvhUyKWMnfB8FFi7mshRPRVk433ZsnWty8Ys/edit#gid=453336487

/sig contributor-experience
/area contributor-summit
/area eu-summit

/assign

**Comment by mrbobbytables** [comment]
With the cancellation of the EU summit, I'm going to go ahead and close out the remaining open issues. If you think something should still be addressed. Please go ahead and reopen 👍 

/close

**Comment by palnabarun** [comment]
This too needs no further work.

Thanks again for closing this. :+1:
