### ISSUE TITLE
REQUEST: New moderator for onlydole of Zoom and YouTube

### ISSUE THREAD

**Issue by onlydole** [kubernetes/community#4369]
### GitHub Username
@onlydole 

### Property you'd like to Moderate
Zoom, YouTube

### Username on Property Requested
@onlydole

### Requirements

- [X] I am a Kubernetes Org member already
- [X] I have enabled 2FA on my account for the property I would like to moderate (if applicable).
- [X] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [X] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@parispittman 
@kbarnard10 

#### Prior Kubernetes moderation experience
* Working on the communications team for Kubernetes releases 1.14, 1.15, and 1.16

* 1.16 Kubernetes Release Webinar

**Comment by parispittman** [comment]
+1

thank you for stepping up!

**Comment by jeefy** [comment]
Big +1

**Comment by castrojo** [comment]
+1 from me as well, let's coordinate through slack to train you up.

**Comment by mrbobbytables** [comment]
+1 from me as well :)

**Comment by markyjackson-taulia** [comment]
Also huge +1
/pony
