### ISSUE TITLE
REQUEST: New moderator for New moderator for markyjackson-taulia of Zoom and YouTube

### ISSUE THREAD

**Issue by markyjackson-taulia** [kubernetes/community#4370]
### GitHub Username
@markyjackson-taulia 

### Property you'd like to Moderate
Zoom, YouTube

### Username on Property Requested
@markyjackson-taulia 

### Requirements

- [x] I am a Kubernetes Org member already
- [x] I have enabled 2FA on my account for the property I would like to moderate (if applicable).
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @castrojo 
- @parispittman 

### List of qualifications for this position

- Prior moderation experience
- A host of community meeting several times
- Summit staff lead

**Comment by jeefy** [comment]
Another big +1

**Comment by mrbobbytables** [comment]
+1 here as well

**Comment by onlydole** [comment]
+1 to the one, the only, @markyjackson-taulia! 🥇

**Comment by kris-nova** [comment]
Huge +1 for @markyjackson-taulia

**Comment by markyjackson-taulia** [comment]
I am ugly crying happy tears over here y’all
