### ISSUE TITLE
access and community infra for summit roles

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4374]
summit roles need access to contributor@ gsuite account to send notices from the main account. the lead+shadow, and marketing/comms+shadow roles will need this. all other roles should go through them to post things. 

community@ is good for a support email line; contributors@ is messy right now. so folks may need access to this one too. reminder - this is a glorified google group and not an email box. 

this will need to be granted to the 2020 EU team and also added to the rolebooks.

**Comment by mrbobbytables** [comment]
This has been done for the EU team.
The follow-up that is needed is to update the role-book.

**Comment by mrbobbytables** [comment]
Guidelines have been added for both the marketing and event lead roles in #4620 / #4622.
Once those have been merged this should be good to close.

**Comment by mrbobbytables** [comment]
Both PRs have merged -- guidelines have been added 👍 
Going to go ahead and close this out :)

/close
