### ISSUE TITLE
2019/20 ContribEx Survey Results

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4392]
- [x]  pass to m&k firm for analysis
- [ ] pass results to CNCF for pretty report
- [x]  create README for results
- [ ]  post results
- [x]  follow up with everyone who wanted swag with codes
- [x]  respond to everyone who left an email that had follow up questions, needs more 411 on a topic, etc. (41 people)
- [ ]  write a blog post https://docs.google.com/document/d/1jlJeioTblSet7S4hm5jMzEcski5ZnGj-TflTAem-cy0/edit?usp=sharing
- [ ]  turn survey angst and cheers into actionable items; discuss in contribex; sit down with triage team to determine priorities
- [x] schedule one hour meeting with contribex folks and other curious minds to go deep into the data

**Comment by cblecker** [comment]
I would specifically want to see breakdowns of questions 6 and 7 by experience in the project

**Comment by mrbobbytables** [comment]
In addition to 6 and 7 break down by experience in the project, 14 would be good as well.

**Comment by parispittman** [comment]
https://github.com/kubernetes/community/pull/4427 -> readme

**Comment by parispittman** [comment]
swag codes sent to 58 people

**Comment by mrbobbytables** [comment]
Going to go ahead and close this for now, we will roll the results into the next survey results/blog post 👍 

/close
