### ISSUE TITLE
Check permissions on UG/WG mailing lists

### ISSUE THREAD

**Issue by cblecker** [kubernetes/community#4395]
I attempted to post to the following mailing lists today, and received a rejection. This indicates either the list in sigs.yaml is incorrect, or the settings are incorrect.

Need help with the following:
- Check via a web browser that each of these mailing lists, as indicated in sigs.yaml and the UG/WG README.md file actually exist
- If they exist, then we need to send a note to the organizers pointing them at the right doc in the communication folder that has the settings directions for mailing lists
- If they do not exist, we need to reach out to the organizers to set them up or correct sigs.yaml

Failing lists:
```
kubernetes-data-protection
kubernetes-ug-vmware
kubernetes-wg-apply
kubernetes-wg-component-standard
kubernetes-wg-security-audit
```

/help

**Comment by cblecker** [comment]
FYI: @parispittman @castrojo

**Comment by castrojo** [comment]
I've added these to the audit list: https://github.com/kubernetes/community/issues/3717

We need to do this for 2020, I'll put it on the next agenda for us to divy this up.

**Comment by castrojo** [comment]
Just as a note for myself, we should try with one mail to all the lists and see what bounces, with something they'd all need to read anyway like an announcement or something, that way we're not mailing "test" to each SIG.

**Comment by mrbobbytables** [comment]
/assign @castrojo @mrbobbytables
We've been working on this 👍 It's not just ug/wg ..but also a lot of sigs 😬

**Comment by mrbobbytables** [comment]
Just to update, the only 2 that have issues at this point in time are:
- kubernetes-wg-policy - must apply to join
- kubernetes-wg-security-audit - not public

**Comment by mrbobbytables** [comment]
/assign @ericavonb @hannibalhuang 
For kubernetes-wg-policy

/assign @aasmall @cji @JayBeale @joelsmith 
For kubernetes-wg-security-audit

**Comment by cji** [comment]
I believe I have corrected the settings for kubernetes-wg-security-audit based on the [documentation](https://github.com/kubernetes/community/blob/master/communication/mailing-list-guidelines.md) I found.

**Comment by mrbobbytables** [comment]
At this point in time only wg-policy remains with outstanding permissions issues.

**Comment by mrbobbytables** [comment]
ContribEx has followed up with every group they can. At this point remaining groups have been unresponsive. Steering should be the group to follow up with them.
