### ISSUE TITLE
Add slack channel for Service Binding work-group

### ISSUE THREAD

**Issue by Avni-Sharma** [kubernetes/community#4397]
Over the last several years, several vendors have proposed solutions toward the concept of "binding" applications with backend services managed by operators. There are several projects going on with similar goals.

The purpose of this channel(service-binding) would be to encourage a dialog and to work towards consensus in this area. A workgroup has been formed focused around this topic. Currently, it resides here - https://groups.google.com/forum/#!msg/operator-framework/ofTVEIUUtow/uiJyWcHfBAAJ . 
The workgroup comprises of any individuals or vendors interested in either promoting user requirements, those contributing operators in general, or anyone interested in contributing to either specifications or common runtime implementations.

**Comment by idealhack** [comment]
+1, could you please make a PR to add it in our [slack configs](https://github.com/kubernetes/community/blob/master/communication/slack-config/channels.yaml)?

**Comment by mrbobbytables** [comment]
Out of curiosity, have you engaged with the folks in the [service catalog sig](https://github.com/kubernetes/community/tree/master/sig-service-catalog)? This seems very much inline with what they're trying to accomplish.

**Comment by markyjackson-taulia** [comment]
@Avni-Sharma Is this still in progress?

**Comment by Avni-Sharma** [comment]
Hi @markyjackson-taulia . No, We can close this now. Thanks!
