### ISSUE TITLE
Index sig / contributor office hours 

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#4409]
Many sigs have adopted contributor office hours or onboarding sessions to help new contributors. These are scattered across several resources, with most of them listed in sigs.yaml / sig-list.md. 

These should be indexed and linked to from our general mentoring docs.

/sig contributor-experience
/area mentorship-planning
/milestone Next

**Comment by danielthrasher** [comment]
@mrbobbytables id love to take a stab at this!

**Comment by markyjackson-taulia** [comment]
@danielthrasher if I can help in any way please do not hesitate to ping me

**Comment by mrbobbytables** [comment]
Thanks @danielthrasher and @markyjackson-taulia :)

**Comment by mrbobbytables** [comment]
@danielthrasher Just wanted to check in :) 
Are you still looking to work on this?

**Comment by mrbobbytables** [comment]
I think this is open again if anyone wants to take it on. 👍

**Comment by mrbobbytables** [comment]
@samudralavamshi54 just checking in, are you still planning to work on this?

**Comment by samudralavamshi54** [comment]
@mrbobbytables yup will work on it.. unfortunately due to other things on plate delayed will try to work and close it next week if its ok

**Comment by mrbobbytables** [comment]
No worries, just wanted to check in 👍

**Comment by joshuabezaleel** [comment]
Hi @samudralavamshi54 , are you still working on this? 
I may be able to give this a shot if this is open :slightly_smiling_face: Thank you!

**Comment by samudralavamshi54** [comment]
@joshuabezaleel Please go ahead and assign it sorry didn't work on this

**Comment by mrbobbytables** [comment]
@joshuabezaleel are you still interested in working on this?

**Comment by championshuttler** [comment]
@mrbobbytables I would like to contribute to this as my first bug , can you help me getting started

**Comment by mrbobbytables** [comment]
@championshuttler Sure, the general idea is to gather up all the office hours / mentoring and any other tracks to help get going contributing from [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml) in the root of this repo and then add them to the our [mentoring documentation](https://github.com/kubernetes/community/tree/master/mentoring) as an easy one stop shop to see which community groups offer them. 😄
