### ISSUE TITLE
sig-instrumentation desc.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/community#441]
We Need a better description for sig-instrumnetation

**Comment by jayunit100** [comment]
Also sig node needs beeter info https://github.com/kubernetes/community/blob/master/sig-node/README.md

**Comment by jayunit100** [comment]
sig storage also could use more specific buzz words in its description

**Comment by jayunit100** [comment]
And of course, sig testing should mention that we focus alot on CI, e2es, flakes, defining semantics of tests in our sig description.

**Comment by kargakis** [comment]
@piosz @fabxc can you guys take care of this issue? Also, I cannot find any github groups to mention this SIG...

**Comment by piosz** [comment]
@fabxc created kubernetes/sig-instrumentation-* groups and added mission statement #789. Any missing action item on our side?

**Comment by kargakis** [comment]
@piosz @fabxc thanks guys! Good enough for me. I am closing this issue and will open separate issues for sig-node and sig-storage.

**Comment by kargakis** [comment]
Opened https://github.com/kubernetes/community/issues/806 and https://github.com/kubernetes/community/issues/807
