### ISSUE TITLE
Paris' Chair Offboarding

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4415]
Checklist for off-boarding things:

- [x] sent email to mailing list & announce during update meeting
- [x] emeritus in sigs.yaml
- [x] removed from contribex-leads@ mailing list
- [x] contribex zoom password needs to be changed
- [x] that might be it? what am I missing?

**Comment by castrojo** [comment]
Are you going to keep running your programs/subprojects in the SIG or do we need to divy those up? What about youtube/zoom admin/moderation overall?

**Comment by markyjackson-taulia** [comment]
If I can help in any way here please do not hesitate to call on me

**Comment by parispittman** [comment]
@castrojo keeping everything :)

**Comment by mrbobbytables** [comment]
contribex zoom password has been changed 👍

**Comment by parispittman** [comment]
and we're closed :)

/close
