### ISSUE TITLE
Request: Auto upload for sig-network Zoom meetings

### ISSUE THREAD

**Issue by robscott** [kubernetes/community#4441]
To avoid manually uploading meeting recordings after every call, it would be nice to have auto upload enabled for our meetings. This includes all meetings currently listed in this repo (sig-network, Service APIs, Ingress V1). As long as a sig-network chair approves this, @mrbobbytables can help get this set up for us.

/cc @bowei @mrbobbytables 
/assign @caseydavenport

**Comment by mrbobbytables** [comment]
This was completed last Wednesday \o/

if you have any questions, please feel free the reopen or ping the youtube admins in slack 👍 

Thanks!

/close
