### ISSUE TITLE
[Feature Request] Add "point of contact" for subprojects in sigs.yaml

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#4445]
TL;DR: An additional optional field in sigs.yaml for subprojects that will list preferred contacts for that project.

This is a follow-up to several discussions in slack and the contribex bi-weekly meeting.
Subprojects can span multiple OWNERS files and different groups -- In most cases, there is 1-3 people who shepherd that project and should be the preferred point of contact regarding it. It would be a "nice to have" to be able to list those folk in sigs.yaml / sig README's.

/kind feature
/area community-management
/sig contributor-experience

**Comment by samudralavamshi54** [comment]
will start working on this

**Comment by spiffxp** [comment]
Discussed during steering.  We want to better understand what specific problems occurred that this is trying to solve.  Subprojects and Groups (SIGs, WGs, etc) both suffer from "leads" and OWNERS files falling out of sync, just in different directions (viz all the OWNERS_ALIAS files that are copied around).

If this is a question of a point person for responsive to the release-team, we had some thoughts:
- which subprojects need this?
- it seems like SIG chairs may also not always be the best person, and it would be useful for them to designate a delegate person
- it may just be easier for the release team to maintain a list of contacts independently of this (it makes my DRY-nerd-brain cringe, but maybe it's the most pragmatic for now)

**Comment by nikhita** [comment]
Discussed this with @mrbobbytables on slack and agreed to close this primarily because of:

> Subprojects and Groups (SIGs, WGs, etc) both suffer from "leads" and OWNERS files falling out of sync, just in different directions (viz all the OWNERS_ALIAS files that are copied around).

If a need arises, we can reopen and have discussions specific to the concern at that time.

/close
