### ISSUE TITLE
Pod Startup Latency SLO with Sidecars

### ISSUE THREAD

**Issue by Joseph-Irving** [kubernetes/community#4454]
The Sidecars KEP (https://github.com/kubernetes/enhancements/issues/753) has the potential to increase the time taken for all Containers in a Pod to start which is one of the SLOs defined here
https://github.com/kubernetes/community/blob/master/sig-scalability/slos/pod_startup_latency.md

By design, the non-sidecar containers will wait until the sidecars have started up and passed readiness checks before they are started. So this could introduce quite a lot of variability in this SLI as you are dependent on how fast sidecars start up and become ready.

Therefore we could consider explicitly excluding Pods with Sidecars from this SLI for now, and see if we should rethink this in the future.

**Comment by Joseph-Irving** [comment]
/sig scalability
cc @wojtek-t

**Comment by wojtek-t** [comment]
@kubernetes/sig-scalability-api-reviews

**Comment by Joseph-Irving** [comment]
This KEP is no longer happening
/close
