### ISSUE TITLE
Action Items for 2020 Survey / process

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4464]
starting this issue to collect comments for the 2020 survey and how to do it better (and what to continue)

- don't advertise on k8s main twitter; maybe the contributor focused twitter? (timestamp survey data matches up with this)
- write a blog post
- have christoph or someone else blast all 40+ community group mailing lists; attend major sig meetings (this worked out well)
- include the accidentally left off question about how people are consuming gh (mobile, desktop, etc)
- start the survey in july - it will take at least one month to get consensus on the questions and possibly another few weeks to get them loaded and tested into surveymonkey
- think about having two surveys a year instead of one. someone left a comment to this extent and this could be a great idea. 
- change wording for 'clean up owners files' in the most important project section: folks didn't understand this and needs to be clear what the purpose is

**Comment by mrbobbytables** [comment]
We could bring this up on the next bi-weekly meeting. Then aim to PR the notes in.

**Comment by mrbobbytables** [comment]
We rolled some of the follow-ups into the new questions (change owners file clean up etc) - I'm going to move the remaining AIs into the 2020 survey issue (mostly around documenting the process changes)

/close
