### ISSUE TITLE
Re-activating a deactivated Slack account

### ISSUE THREAD

**Issue by timucingelici** [kubernetes/community#4467]
It seems I joined to Kubernetes’ Slack community on 11th of April 2017 but then my account has been deactivated in time.

I believe the reason was that I have not been active for quite a long time. I was wondering if anyone can check the status of my account and help me to re-activate it - if possible?

The local part of the email I used was “timucin.gelici”, which should help to find the deactivated account.

Thanks.

**Comment by castrojo** [comment]
/assign

I can't find any account with "timucin.gelici" in the slack admin interface?

**Comment by timucingelici** [comment]
@castrojo I don't know if I ever get in and set a username for that workspace. `timucin.gelici` is the part comes before `@` of my email registered address. Is it possible to search the deactivated users by their emails?

**Comment by castrojo** [comment]
Found it! I activated the account, please confirm it works before I close this, thanks!

**Comment by timucingelici** [comment]
@castrojo Yes, I am in. Thank you. :)

**Comment by fa-bwilliams** [comment]
I need my account reactivated on Slack. Invite oage says my account is disabled. Not sure where else I can go to request.
