### ISSUE TITLE
API conventions give incorrect Conditions advice

### ISSUE THREAD

**Issue by jpeach** [kubernetes/community#4471]
As per [this comment](https://github.com/kubernetes-sigs/service-apis/pull/47#issuecomment-580474003) the advice the API conventions document gives about `.status.conventions` is wrong. This should be corrected so that projects trying to be good API participants can define interoperable Conditions behavior.

**Comment by jpeach** [comment]
xref kubernetes-sigs/service-apis#47

**Comment by evankanderson** [comment]
@smarterclayton if you think this is sufficiently established case law, I'm happy to send a PR to distill some of the wisdom.

**Comment by smarterclayton** [comment]
Yeah I think so, @liggitt if he wants to disagree

**Comment by evankanderson** [comment]
Still discussing #4521
