### ISSUE TITLE
moderators.md needs to be updated

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4473]
several open slots that aren't open, sarah is no longer the owner of youtube and hasn't been for a while, and since i'm counting at least 3 areas that need to be updated, an overall audit of this page should probably happen.

https://github.com/kubernetes/community/blob/master/communication/moderators.md

it might be time to have a moderator lead for all moderators with a shadow so that they can organize all, do updates at the meetings, audit docs and roles, etc. but i think i just scope creeped this issue...

**Comment by samudralavamshi54** [comment]
will audit the page and update

**Comment by castrojo** [comment]
Ok I've audited the page. A few people were missing on the moderator mailing list so I've added them, and a few people changed emails so they've been updated and readded.
