### ISSUE TITLE
REQUEST: New Slack channel #aks-engine

### ISSUE THREAD

**Issue by karenhchu** [kubernetes/community#4482]
**GitHub Username:**
craiglpeters
karenhchu

**Slack Username:**
craiglpeters
karenhchu

**What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?**
Channel

**Name of Requested Resource:**
#aks-engine

**Description of Request:**
Need a place to discuss AKS Engine matters with the community.

**Comment by craiglpeters** [comment]
There are really two audiences to address: users and developers. Ideally I'd like to see two channels:

- aks-engine-users
- aks-engine-devs

**Comment by castrojo** [comment]
/lgtm

Sorry it took so long to get to this, here are the instructions for PRing in the channels you want: https://github.com/kubernetes/community/blob/master/communication/slack-guidelines.md#requesting-a-channel

Feel free to assign me to the PR.
