### ISSUE TITLE
REQUEST: New Slack app: wee-slack

### ISSUE THREAD

**Issue by dustymabe** [kubernetes/community#4496]
**GitHub Username:**

> The github username of the Channel/Bot/Token/Webhook owner or primary contact.

I don't know who to put down here. My GH name is @dustymabe but I don't think that is what is being asked for. 

**Slack Username:**

> The Slack username of the Channel/Bot/Token/Webhook owner or primary contact.

Again, my username is @dustymabe, but not sure that is the correct answer to the question

**What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?**

Slack App request.

**Name of Requested Resource:**

A request for the [wee-slack app](https://slack.com/apps/A1HSZ9V8E-wee-slack) to be added to the kubernetes workspace.

**Description of Request:**

There is a subset of users that hate communicating via either a browser window or a separate desktop application. There is a further subset of users that prefer a purely plain text and terminal based experience for text based chat communication. Currently I use [weechat](https://weechat.org/) to communicate via IRC and slack (for other workspaces that I'm already a part of). In order to do this I use the [wee-slack](https://github.com/wee-slack/wee-slack) plugin. This plugin uses either legacy slack tokens or, IIUC, it can use oauth if the [wee-slack app](https://slack.com/apps/A1HSZ9V8E-wee-slack) if it is installed in the workspace.

Since slack legacy tokens are blanket denied my understanding is that the only way I'll ever be able to communicate on the kubernetes slack is if the wee-slack app gets installed in the workspace.

Please consider connecting via weechat as a valid alternative for this subset of people who prefer to communicate in the ways I've mentioned above. Thanks so much!

**Comment by dustymabe** [comment]
Anyone care to comment on this request?

**Comment by danielmellado** [comment]
I would love to see this there as well

**Comment by coderanger** [comment]
The same policy applies, we do not currently allow new Slack apps or alternative client bridges outside of direct support of the project. With so many people in the Slack and so few volunteer moderators/admins, it helps to keep things more unified which unfortunately restricts this kind of app. We encourage you to let Slack know about your desire for a smoother command-line experience.
