### ISSUE TITLE
Build Shanghai 2020 Contributor Summit Team

### ISSUE THREAD

**Issue by idealhack** [kubernetes/community#4513]
Contributor Summit will be back to Shanghai again at the end of July, and here we form the team and get the ball rolling :)

Please see [Events Team roles](https://github.com/kubernetes/community/tree/master/events/events-team) for details and nominate yourself or others.

- Lead roles: from current and past contributor summit staff
- Shadows: do not need to have Kubernetes event experience, but should be ok with taking a lead role within the next 12 months of events

Tentative roles are:

| Role | Lead | Shadow | Notes |
|---|---|---|---|
| Event Lead | | | |
| Registration | | |
| Communications | | |
| Current Content | | | |
| New Contributor Workshop | | | |

/sig contributor-experience
/area contributor-summit
/area cn-summit

**Comment by idealhack** [comment]
cc @puja108 @kubernetes/sig-contributor-experience-apac-coordinators @kubernetes/sig-contributor-experience-leads

**Comment by idealhack** [comment]
note: I've confirmed with Deb that we are going to work on this event as planned, for concerns about the coronavirus, see https://www.lfasiallc.cn/kubecon-cloudnativecon-open-source-summit-china/attend/coronavirus-update/ as KCS is a co-located event of KubeCon.

**Comment by tao12345666333** [comment]
I was about to say this.  :+1:
This thing will affect the schedule.

**Comment by idealhack** [comment]
btw, we don't have the staff information for the [2018](https://github.com/kubernetes/community/tree/master/events/2018) or the [2019](https://github.com/kubernetes/community/tree/master/events/2019/06-contributor-summit) one. I'll add them when I contact previous leads.

**Comment by puja108** [comment]
@jberkus mentioned in San Diego that he would like to step down from being the lead and IIRC nominated @idealhack as the new lead. I would support Yang's nomination for this and I can offer to be the shadow, as I've been involved with the last two years, too, and as it currently looks will also make it to China again this year. Alternatively, I can be involved in Current Content again.

**Comment by alisondy** [comment]
👋 I'll be willing to help out with NCW

**Comment by aravindputrevu** [comment]
I'd like to join you folks too,  but it depends on the travel restrictions.

**Comment by palnabarun** [comment]
@idealhack @puja108 I would like to help out again with the Registration role. I am a bit doubtful about my attendance on-site for the event.

**Comment by Pensu** [comment]
Would love to help out with KCS Shanghai, hope the travel situation is sorted out by then. :)

**Comment by idealhack** [comment]
As KubeCon China 2020 was [canceled](https://www.lfasiallc.cn/kubecon-cloudnativecon-open-source-summit-china/), the (physical) KCS will be canceled as well. However, the SIG will be planning on if we are going to have a virtual event, so I'll keep this one open.

**Comment by puja108** [comment]
Yeah, some Chinese contributors and community companies are planning on creating a virtual KubeCon China/APAC (cc @kevin-wangzefeng as you sent me your survey) anyway, so we might be able to attach our events there to have a nicer crowd and benefit from each other's marketing and organization efforts.

**Comment by jberkus** [comment]
You'll be able to re-use the NCW content from the virtual NCW in March.

**Comment by mrbobbytables** [comment]
Going to go ahead and close this :(
Will revisit again next year...

/close
