### ISSUE TITLE
create new slack team/user group for upstream marketing

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4515]
need to create @contributor-comms as a team in slack so folks can reach out to us as one (out of many) methods, this one hitting our real time needs. this is a reminder PR for myself but if someone wants this as a good first issue or a friendly PR and it's still open - take it. :)

jonasrosland
chrisshort
tunde
simplytunde
onlydole
Rin Oliver
and me - paris

need to get ok to add from karthik, nzoueidi

https://slack.com/help/articles/212906697-Create-a-user-group

**Comment by tao12345666333** [comment]
I submitted a PR to complete it

/assign
