### ISSUE TITLE
When the legacy-cloud-provider for vsphere will be removed from the k8s controller?

### ISSUE THREAD

**Issue by darbiste** [kubernetes/community#4519]
it's announted that the CSI for vSphere is supported only for on v6.7U3 (https://github.com/kubernetes/cloud-provider-vsphere/blob/master/docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md). In the other hand, legacy-cloud-provider embeded with k8s controller is marked as depricated and continue to work on lasted k8s version, our vSvphere infra is not moving so fast interms of upgrades, and we need to know witch k8s version will stop supporting the CPI

/sig cloud-provider
/sig vmware-users

**Comment by mrbobbytables** [comment]
@darbiste This repo is used as the general management point of Kubernetes contributor community. Questions like that are not likely to be answered here. I'd ask it over in the [#provider-vsphere slack channel](https://kubernetes.slack.com/messages/provider-vsphere) or reach out to the [vmware users group channel / or send an email to their mailing list](https://github.com/kubernetes/community/tree/master/ug-vmware-users).

With that I'm going to go ahead and close this out, if you have any questions feel free to respond or reach out to me directly.

/close
