### ISSUE TITLE
Threshold limits on headless service

### ISSUE THREAD

**Issue by deekshith-elear** [kubernetes/community#4525]
Hi,
I was using headless service to provide DNS name for the pod, In thresholds.md I'm seeing services can hold max endpoints of 250, Does this applies the same to headless service.

Thanks
Deekshith

**Comment by mrbobbytables** [comment]
@deekshith-elear The community repo is used as the general management point of Kubernetes contributor community. Questions like that are not likely to be answered here. =/ 

I'd ask it over in the [#sig-network](https://kubernetes.slack.com/messages/sig-network) slack channel or on their [mailing list](https://groups.google.com/forum/#!forum/kubernetes-sig-networkt).

With that I'm going to go ahead and close this out, if you have any questions feel free to respond or reach out to me directly.

/close
