### ISSUE TITLE
Add a mentor available label to denote that an issue has a mentor available for getting it addressed

### ISSUE THREAD

**Issue by bradtopol** [kubernetes/community#4530]
In an effort to reduce the friction of new contributors being able to identify and implement an existing issue,  I propose the creation of a new prow label called the "mentor available" label. Similar to how the good first issue label denotes that an issue is appropriate for a new contributor, the mentor available label denotes that a mentor is available for any contributor that wishes to attempt to implement the issue that has this label.  If an issue has this label, it is expected that inside of the description of the issue, a mentor contact will be provided and anyone that decides to own this issue can contact the mentor for guidance and advice on how to implement a solution to the issue.

The thought process behind this feature is that it would help enable senior contributors to delegate work items to new contributors and it would also enable new contributors to work on issues which they are guaranteed to get some guidance and advice on how to proceed with addressing the issue. It also reduces the effort required by new contributors to connect with a more senior contributor that is capable of providing guidance on how to address the issue.  This is is critical because in many cases new contributors are not sure who to contact when trying to start becoming a new contributor to an open source project.

/cc @zacharysarah @sftim

**Comment by zacharysarah** [comment]
The PR to add a label belongs in test-infra, but I asked @bradtopol to open an issue here to maximize visibility.

Like Brad mentions, SIG Docs wants to deepen our pool of good first issues. We notice that many issues aren't quite in the range of a new contributor, but could be with a mentor to provide feedback. Folks with feature knowledge but no bandwidth to write docs may find it easier to provide reviews, or more valuable to mentor a newer contributor, or both. 

We'd love feedback on this idea, even if it's as simple as a 👍 👎 .

**Comment by sftim** [comment]
SIG Docs also intend to update https://kubernetes.io/docs/contribute/intermediate/ and https://kubernetes.io/docs/contribute/advanced/ to specifically mention mentoring.
