### ISSUE TITLE
REQUEST: New Slack channel (k8s-infra-alerts) and integration (Google Cloud Monitoring) 

### ISSUE THREAD

**Issue by thockin** [kubernetes/community#4534]
**GitHub Username:** thockin

**Slack Username:** thockin

**What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?**. Channel & integration

**Name of Requested Resource:**  k8s-infra-alerts and enable GCP Monitoring integration

**Description of Request:** We want to be able to send alerts (e.g. k8s.io is down) to a slack channel.  To do that, we need to allow Google Cloud Monitoring integration and give it a channel to shout into.  Hopefully we can live with just 1 channel, but we will see as we learn more.

**Comment by jeefy** [comment]
/assign @mrbobbytables @jeefy 

Context https://kubernetes.slack.com/archives/C4M06S5HS/p1582220495051900

**Comment by thockin** [comment]
YAY!  I have a channel.

How do I get the app authorized?

```
You are not authorized to install Google Cloud Monitoring on Kubernetes
Google Cloud Monitoring is restricted for this workspace. Please reach out to one of your App Managers if you would like additional information or to ask them to install this app.
```

**Comment by munnerz** [comment]
Copying from Slack...

I am +1 to this, but we should double check whether this will allow anyone on Slack to configure Stackdriver Monitoring alerts from there own workspace into channels (and if this _is_ the case, decide whether that's okay...)

**Comment by munnerz** [comment]
(I wouldn't be against 'learning on the job' either!)

**Comment by thockin** [comment]
All approved - will test now!  Thanks slack admins.
