### ISSUE TITLE
Policy Violation Custom Resource Definition

### ISSUE THREAD

**Issue by JimBugwadia** [kubernetes/community#4538]
The [Policy Violation CRD](https://docs.google.com/document/d/1QJWcaJdo8w88tIixiZp9zBMHKghTMrHTyHyk6xcoVhk/edit#heading=h.wn242twwl364) proposal aims to standardize how different Kubernetes policy management tools (OPA, Falco, Kyverno, kube-bench, etc.) can report non-conformance. The goal is to allow consistent reporting and management of policy violations.

There are three work areas for this proposal:

**Comment by nikhita** [comment]
xref https://github.com/cncf/soc/pull/145 - this is for a GSoC project.

**Comment by nikhita** [comment]
@JimBugwadia Now that we have https://github.com/kubernetes-sigs/wg-policy-prototypes, would it be ok to close this issue and create a new one at that repo? We generally use this repo for issues affecting the community as a whole. :)

**Comment by JimBugwadia** [comment]
Yes, thanks! Since GSoC deadline has passed, no need for a new issue at this time. Closing.
