### ISSUE TITLE
Soliciting Kubernetes CI requirements for Inclusive Integration with CNCF Projects

### ISSUE THREAD

**Issue by hh** [kubernetes/community#455]
> "CNCF is helping develop a cloud native software stack that enables cross-cloud deployments. Cross-project CI that ensures ongoing interoperability is especially valuable." - Dan Kohn Executive Director CNCF

[[cncf-ci-public] CNCF CI Goals](https://lists.cncf.io/pipermail/cncf-ci-public/2017-February/000001.html)
[[cncf-ci-public] Soliciting CI requirements via Project GitHub Issues](https://lists.cncf.io/pipermail/cncf-ci-public/2017-March/000024.html)

This github issue is to provide a highly visible invite to be part of creating a cross-cloud cross-project CI within the diverse software communities of the Cloud Native Compute Foundation.

To fully understand our needs and expectations, some help documenting the current state of the Kubernetes CI and ongoing requirements of the Kubernetes community would be useful.

https://github.com/cncf/wg-ci/blob/master/projects/kubernetes.mkd

As we collect Kubernetes and other project CI requirements, we'll use the @cncf/cncf-ci-working-group issue at https://github.com/cncf/wg-ci/issues/12 and encourage you to join the discussion on the [cncf-ci Mailing List](https://lists.cncf.io/mailman/listinfo/cncf-ci-public)

**Comment by dankohn** [comment]
Note that there is a desire to move the K8s testing off of Google-controlled (and Google-funded) infrastructure. https://github.com/kubernetes/release/issues/281#issuecomment-287234235
