### ISSUE TITLE
Kubernetes Contributor Twitter Handle

### ISSUE THREAD

**Issue by chris-short** [kubernetes/community#4554]
The [Kubernetes Upstream Marketing](https://github.com/kubernetes/community/tree/master/communication/marketing-team) team has been stood up to elevate the hard work being done throughout the Kubernetes community by its contributors. Part of that work is to create a community social media presence.

The first platform we're looking to tackle is Twitter and we need to choose a handle from a group @mrbobbytables has been sitting on. The team has narrowed down the dozens of choices to the following five. Please vote by using the emoji in front of the purposed handle:

**Voting concludes 13 March 2020**

👍 Contribernetes

🎉 K8s-contributors

❤️ K8scontributors

🚀 Kubernetes-dev

👀 Kubernetesdev

Thank you so much for your participation here and in this great community!

**Comment by justaugustus** [comment]
It feels a little confusing/diluted to have multiple presences?
Is there a reason we couldn't share control of https://twitter.com/kubernetesio?

**Comment by parispittman** [comment]
@justaugustus they only push out so much content a day and we have more content than what they want to share

**Comment by justaugustus** [comment]
Gotcha. Thanks for the clarification, @parispittman! :)

**Comment by eyevariety** [comment]
It's criminal that the hyphenated version is winning.  The non hyphenated is far easier to communicate and will be the default mistake that people trying to do the hyphenated one make.

**Comment by nimbinatus** [comment]
✋ Can we ensure that if any of the non-hyphenated handles do get picked gets CamelCased so people with screen readers have an easier time of it? My understanding based on what I know of accessibility is that CamelCase is read properly by a reader (e.g., "Cam-el Case" vs "cam-el-cas-e") Or are these already claimed and we just need to pick one?

**Comment by eyevariety** [comment]
Twitter handles aren't case sensitive, so it would just be an aesthetic change

**Comment by chris-short** [comment]
Hey Kubernetes Family,

The polling is over. **K8s-contributors** is the clear winner. But, we have a few issues we're working through at the moment with regards to the Twitter handle.

Earlier this week, we realized that K8s-contributors is an invalid Twitter handle as it exceeds the fifteen (15) character limit. When piecing together what didn't go as planned, we realized something rather unique to our community.

@mrbobbytables gave the team a list of Twitter handles he'd been squatting. While discussing which handles to vote on, someone asked to include hyphens between words to help folks with screen readers. As we were going through the shortlist, we made sure to hyphenate handles in the meeting minutes where appropriate. I then transferred that list into a draft message that became this issue. But, I did not go about the task of registering ALL the handles (only documenting them).

The team met today to discuss the matter. We agreed that bringing everything to another vote was not conducive to our team's goals. Even though Kubernetes-dev came in second, we feel the term dev is exclusionary. Our community is thousands of people from all walks of life. Much like how we want to be inclusive of folks with screen readers, we do not want to exclude folks that don't have 'developer' in their job description.

**K8sContributors** is a handle that Bob has control over. The team thinks that's the best handle to use. After getting out of the meeting today, I went to check the handle; it turns out it has been suspended. Bob has already started the appeals process with Twitter. We're hopeful the appeal moves quickly. 

That's the current state of the community Twitter handle. I'm going to stick my head under a rock now (figuratively).

If you have any questions or concerns, please feel free to comment here or in the sig-contribex Slack channel.

**Comment by chris-short** [comment]
The handle has been secured.

We’re working on narrowing down a social media platform in #4626. If you have any feedback there, it’d be appreciated.

I think we can call this one done.
