### ISSUE TITLE
Virtualize 2020 EU Kubernetes Contributor Summit

### ISSUE THREAD

**Issue by jeefy** [kubernetes/community#4558]
With the concerns I've heard from many contributors (summit staff and otherwise) as well as companies starting to ban international travel, I want to propose that the Kubecon EU 2020 Contributor Summit be ~cancelled and~ turned into a virtual-only event.

I (along with @geekygirldawn and @mrbobbytables) had [written up a proposal](https://docs.google.com/document/d/1FH24lkoLS0mQcXNhYbk08L9qXzjrCaVgnCGwGSirGmc/edit) that was meant to be a Plan-B in case Kubecon itself was cancelled; however, I now move that this be the new path forward.

This is a super awkward topic and there are many opinions on it. From the last Zoom call (eventual link to recording once live), there was a majority that said ~cancel/~virtualize; however, of note it was not an overwhelming majority. Also, because this is quite an awkward proposal, it isn't strictly clear who gets to make the decision on whether it is ~cancelled~ virtualized or not. 

That being the case, I'm assigning the Events subproject owners to either decide, or delegate decision back to me (which we will then need to document.)

Shout out to literally everyone who so far has voiced an opinion, a concern, or a supporting gesture. This road goes both ways and though awkward this truly shows the power of our community.

/assign @parispittman @guineveresaenger @jberkus @mrbobbytables @Phillels @cblecker @nikhita 
/area contributor-summit
/sig contributor-experience
/priority critical-urgent

**Comment by jeefy** [comment]
GH Group broke it looks like 

/assign @parispittman @guineveresaenger @jberkus @mrbobbytables @Phillels @cblecker @nikhita

**Comment by BenTheElder** [comment]
What's the upshot to this over like, generally preparing materials for contributors?

To me the contributor summit is about getting face to face time. For the new contributor workshop in particular that means having people go around and personally help people work through it 1:1.

If it's "virtual" AKA video calls and slack, that sounds like every other day in the project and lacking the 1:1 interaction we gain in a non-virtual summit. In that case I'd suggest maybe instead doing:

- record talks?
- better yet: write up content! produce new developer guides etc.
- invite people to come join us in disqus / slack :upside_down_face: 

I don't see any real reason to have people attend something live over async media if we're not gaining that higher bandwidth, personal interaction.

**Comment by markyjackson-taulia** [comment]
Zoom has the breakout room for 1:1 help and I have done that before for training

**Comment by chris-short** [comment]
@BenTheElder I think the idea is that a lot of folks have already booked this time for the event so we do not want to leave them empty-handed. For example, OpenShift Commons has shifted to a completely virtual event. Additionally, this content does have the added benefit of then becoming available asynchronously.

**Comment by jberkus** [comment]
I firmly believe that IF Kubecon still happens, there should be a live, physical Contributor Summit.  If people are going to Kubecon anyway we're not adding to anyone's risk by holding the CS, and currently a lot of our registrants forwent other Day 0 events so that they could be at the Contributor Summit.  Cancelling on them would be irresponsible.

**Comment by alisondy** [comment]
@jberkus playing devils advocate
with all these travel bans, and people dropping out
are we confident we can still deliver them a quality event?

**Comment by jberkus** [comment]
Now, that's a good question.  I'm inclined to believe that, if enough companies pull their people to make the CS untenable, they'll also cancel Kubecon.  But maybe you aren't.

**Comment by markyjackson-taulia** [comment]
I will also add to what @alisondy said, if we do not have enough staff or speakers, I am of the opinion that delivering a subpar event should not happen

**Comment by chris-short** [comment]
There would still be an event. It would be virtual. If there are folks on the ground there that could facilitate participation, I think that could be blended. I could be wrong too. But, I believe that the quality is going to be subpar right now given those that have pulled out.

**Comment by jeefy** [comment]
FYI I formatted things to remove the word Cancel. The core idea here is to transition things from an in-person event to an entirely remote/virtual one.

PS I'm staying out of things for a while. I brought the proposal up and want everyone to have a voice here. <3

**Comment by mrbobbytables** [comment]
Sorry for the large delay in response -- just got back near a comp

> To me the contributor summit is about getting face to face time. For the new contributor workshop in particular that means having people go around and personally help people work through it 1:1.

A digital event cannot replace Face-to-Face time =/ We can however try and do what we can.

We have focused session content that should be useful (e.g. [overview of structure logging](https://kcseu2020.sched.com/event/aO3i/introducing-structured-logging-into-kubernetes-codebase)). For others its a block of time where we can discuss/work on a specific things For example the [KEP BoF](https://kcseu2020.sched.com/event/aO46/keps-bof-driving-enhancements-for-enhancements) or the [LTS discussion](https://kcseu2020.sched.com/event/aO3u/kubernetes-support-terms). 

Could these things be done in a regular SIG Zoom session? Some, yes; but others -- especially the new contributor workshop would be difficult in a "normal" zoom meeting. We can however use the webinar mode which helps with facilitating large groups and allows for sub-groups to break out and work on things.  This has been effective with other activities such as the CoC training.

> better yet: write up content! produce new developer guides etc.

This can still be done (digital unconference?). The big thing we have is a dedicated block of uninterrupted time to work on something.

**Comment by BenTheElder** [comment]
> We have focused session content that should be useful (e.g. overview of structure logging). For others its a block of time where we can discuss/work on a specific things For example the KEP BoF or the LTS discussion.

I still think the former is a video or written post and the latter should be a KEP or slack or mailinglist discussion. Or workgroup meeting. Needing to attend and present this live digitally seems pointlessly exclusionary.

> ... The big thing we have is a dedicated block of uninterrupted time to work on something.

I contest the idea that everyone will still have an uninterrupted time slot for this when they are no longer attending, and presume attendees would prefer a physical event.

I think greater impact can be made improving permanent contributor content / tooling / ... and this does not require time zone alignment.

> I'm inclined to believe that, if enough companies pull their people to make the CS untenable, they'll also cancel Kubecon. But maybe you aren't.

\+ :100:

**Comment by parispittman** [comment]
It looks like ~4 folks on the event crew are left out of 25. I'm +1 to start on virtual plans.

**Comment by jberkus** [comment]
Yeah, when I made the comment above I wasn't aware that two companies had already pulled their people.  

However ... we should discuss timing.  Like, if this is not happening at Kubecon, then is there a particular reason to have it on March 30?

**Comment by parispittman** [comment]
@jeefy can you and ams crew discuss the pros/cons of moving vs having the same day and let us know what you think?

**Comment by jberkus** [comment]
My thought was to break it up over several days.

**Comment by cblecker** [comment]
@jeefy Thank you for bringing this forward.

As a subproject owner and ContribEx TL: +1 to cancelling the in person summit, and moving forward with some sort of virtual plan.

I agree with a number of the arguments and concerns, both for the health and safety of our volunteer contributors running this event, and the quality of program we could put on with the large number of staff and speakers who are unable/unwilling to travel.

It is unfortunate that we are in the spot that we have to do this, but I believe at this time it is for the best.

**Comment by jeefy** [comment]
@parispittman - Having it the same day has a couple benefits that were discussed on the planning call:
* As of now, everyone already has the time blocked off
* If Kubecon is held, those summit attendees who travel to it could attend it still virtually (depending on the timezone question, which is still up in the air)

When the group was polled on Zoom, the majority felt same-day made the most sense. 

From a quality-of-event-perspective, I have the utmost confidence we can turn this around to a pretty kick-ass virtual summit. Will it have the F2F/Dedicated interactions that the @BenTheElder's of the world want, no: We can't replace IRL jollies with virtual ones. But I think with a month, we can amplify the benefits of being remote, and do some cool things. 

Changing the dates, or spreading it across multiple days, was discussed and deemed "confusing". One point of discussion was shifting the NCW to the day before so all NCW participants (staff/attendees) could then attend the regular sessions: I'm personally for that, but we need to look into that more.

---

It looks like we have a majority of the subproject owners on +1 (unless I misinterpret). For tonight and tomorrow morning my plan is to hammer out some verbage/messaging and refine the proposal more. My aim is to engage comms to spread the word tomorrow afternoon barring the brakes being hit.

That being said: I want to keep this thread open and encourage discourse about all of this. We're stronger when we talk things out even as wheels start turning.

**Comment by nikhita** [comment]
Explicit +1 for a virtual event :+1: :100:

**Comment by chris-short** [comment]
I am a hard +1 for virtualizing the event.

I would also propose we make as few changes to the schedule as possible to minimize confusion, drastically ease logistics (no one's workload changes), and not burn the three streamers we have out. I understand there is flexibility in virtualizing but, I'd rather see that flexibility used to open the event up to more people as opposed to changing formats to meet the medium.

I think the only thing that might be flexible is timezone. I am for keeping it in the Amsterdam TZ but, I understand there may be better times given the speakers and audience.

**Comment by raelga** [comment]
+1 for the virtual event too.

**Comment by saschagrunert** [comment]
+1 let’s do it virtual

**Comment by jberkus** [comment]
The Virtual Contributor Summit (VCS) should not be all on March 30th.

Here's why: nobody is going to be OK with schedule conflicts in a purely online event when we could actually serialize it.

One of the primary compliants about the CS in every survey we do is the conflicts between sessions that the same people want to be in.  And for this CS, we were juggling presenters for the NCW because of the people who had to be in a session at the same time as their NCW segment. 

We should serialize the CS over a few days, instead.

**Comment by parispittman** [comment]
thank you everyone for your comments and jeff for being considerate and asking for folks suggestions <3 closing this issue now as the decision has been made. thank you jeff, dawn, and bob for the thoughtful proposal.

/close
