### ISSUE TITLE
Update SIG Contributor Experience Sub-project Owners

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#4585]
This is a general maintenance task. Before the 1.19 cycle / project planning starts we should ensure that the sub-project owners are up to date.
- [x] [Community](https://github.com/kubernetes/community/tree/master/sig-contributor-experience#community)
- [x] [Community-management](https://github.com/kubernetes/community/tree/master/sig-contributor-experience#community-management)
- [x] [Contributor Documentation](https://github.com/kubernetes/community/tree/master/sig-contributor-experience#contributors-documentation)
- [x] [Devstats](https://github.com/kubernetes/community/tree/master/sig-contributor-experience#devstats)
- [x] [Events](https://github.com/kubernetes/community/tree/master/sig-contributor-experience#events)
- [x] [GitHub Management](https://github.com/kubernetes/community/tree/master/sig-contributor-experience#github-management)
- [x] [k8s.io](https://github.com/kubernetes/community/tree/master/sig-contributor-experience#k8sio)
- [x] [Mentoring](https://github.com/kubernetes/community/tree/master/sig-contributor-experience#mentoring)
- [x] [Slack Infra](https://github.com/kubernetes/community/tree/master/sig-contributor-experience#slack-infra)

/assign @mrbobbytables @cblecker @nikhita @Phillels 
/priority important-soon
/kind cleanup
/sig contributor-experience

**Comment by parispittman** [comment]
Checking in that I have intentions of remaining active in all of mine. I would like to be emeritus in the communication subproject by EOY if I can get someone to mentor.

**Comment by mrbobbytables** [comment]
Just to update -- I have reached out to most subproject owners and should complete it this week with PRs to follow.

**Comment by mrbobbytables** [comment]
This is complete 👍 
/close
