### ISSUE TITLE
zoom feature additions to add to docs

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4587]
break out rooms, polling, and nonverbal queues to host are features we were not using before that we should start using in certain situations/SIGs/meetings. when flipping these on zooms global control panel, this will let meeting hosts on individual licenses toggle those on if they would like. this is a net positive but will need some things in place:

1-documentation will need to be updated/testing
2-chairs and other meeting hosts will need comms

setting issue to collect other thoughts/comments/questions and see if anyone would like to work on this

**Comment by castrojo** [comment]
Ok playing with the streaming stuff now, here's what I found: https://support.zoom.us/hc/en-us/articles/360028478292-Streaming-a-Meeting-or-Webinar-on-YouTube-Live

Good:
- Anyone with the right youtube creds can now stream their meeting right from zoom directly to youtube by clicking a button, they don't need OBS or dedicated hardware!

Bad:
- If we wanted to do this for all the SIGs they'd need to have youtube access permissions, this would lead to account overhead at the YouTube level (rotating out new SIG chairs, etc.). But, it would also remove a lot of their complexity they are dealing with now. We'd need to investigate this and get feedback at where we'd want the complexity to be. 
- 20 second delay, but this would be more for archival purposes and not live-stream engagement purposes. 

No change:
- For Meet Our Contributors and Office Hours where we like having the chat and an overlay with the URL this doesn't change much, we'd still use OBS for that.
