### ISSUE TITLE
Replace SIG/WG meeting placeholder references with Zoom links

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#4588]
Some time ago Zoom did not have sufficient moderation capabilities and the Zoom meeting links were removed from [sigs.yaml] and pointed towards this placeholder:
https://docs.google.com/document/d/1FQx0BPlkkl1Bn0c9ocVBxYIKojpmrS1CFP5h0DI68AE/edit

As a workaround to help mitigate trolls from causing problems in meetings. This has since been resolved and the entries in [sigs.yaml] should be updated with their correct link.

There are 53 references to the above placeholder as of 2020-03-09. Updated zoom links can be taken from either the SIG/WG's agenda or their calendar event from the [community calendar](https://calendar.google.com/calendar/embed?src=cgnt364vd8s86hr2phapfjc6uk%40group.calendar.google.com&ctz=America/Los_Angeles).

/area community-management
/sig contributor-experience
/help
/good-first-issue

[sigs.yaml]: https://github.com/kubernetes/community/blob/master/sigs.yaml

**Comment by AGMETEOR** [comment]
Would love to try this

**Comment by mrbobbytables** [comment]
Go for it @AGMETEOR :)

**Comment by markyjackson-taulia** [comment]
> Would love to try this

This is awesome and I am so proud of you for giving this a go.
You will need to make side you sign the CLA: https://github.com/kubernetes/community/blob/master/CLA.md

/assign @AGMETEOR

**Comment by rajendar38** [comment]
I am also interested in this  jack and bob

**Comment by markyjackson-taulia** [comment]
> I am also interested in this jack and bob

@rajendar38 this has been taken up by @AGMETEOR

**Comment by rajendar38** [comment]
Ok no issues, any good first issue please let me know jack, 
I already signed in CLA agreement 
and let me know the next steps to proceed further for future purposes.

**Comment by markyjackson-taulia** [comment]
> Ok no issues, any good first issue please let me know jack,
> I already signed in CLA agreement
> and let me know the next steps to proceed further for future purposes.

Take a look at https://github.com/search?q=org%3Akubernetes+org%3Akubernetes-sigs+org%3Akubernetes-incubator+org%3Akubernetes-csi+org%3Akubernetes-client+is%3Aopen+is%3Aissue+label%3A%22help+wanted%22&type=Issues

**Comment by AGMETEOR** [comment]
@mrbobbytables / @markyjackson-taulia for each meeting with the same `description`, should I use the same zoom link or I should just map the meeting day and time in `sig.yaml` with the time on the calendar and then get the appropriate zoom link?

**Comment by markyjackson-taulia** [comment]
@AGMETEOR I would map the meeting day and time in sig.yaml with the time on the calendar and then get the appropriate zoom link but I would also like @mrbobbytables to advise

**Comment by mrbobbytables** [comment]
Multiple people should be able to do this one. You can do 1 sig/wg per PR and break it up that way :) 
1 SIG per PR will also likely get reviewed/merged much much faster.

**Comment by AGMETEOR** [comment]
@mrbobbytables going to break them up.

**Comment by AGMETEOR** [comment]
@mrbobbytables broke them up into 9 branches. I also noted that some meeting links were not available on the calendar. I noted them down and will be putting a comment of those under each PR.

**Comment by castrojo** [comment]
You need to run `make` on your PRs, the instructions are here: https://github.com/kubernetes/community/tree/master/generator

Thanks for working on this!

**Comment by AGMETEOR** [comment]
@castrojo thanks for the heads up! I just did :)
