### ISSUE TITLE
fixing shadow-roles.md

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4591]
I was in the middle of a review and someone lgtm'ed it. I had some comments that need to be addressed in a new PR. 

https://github.com/kubernetes/community/pull/4574

[this doc](https://github.com/kubernetes/community/blob/master/mentoring/programs/shadow-roles.md)

<img width="638" alt="Screen Shot 2020-03-10 at 9 57 58 AM" src="https://user-images.githubusercontent.com/5912992/76340105-420eeb80-62b8-11ea-8ed3-88fa7791e37e.png">

**Comment by zestrells** [comment]
Opened a PR to address this issue https://github.com/kubernetes/community/pull/4609
