### ISSUE TITLE
Splain configuration for SIG Apps 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/community#4595]
I want the splain (zoom to youtube automation service) configuration for SIG Apps. Thanks!

@kow3ns @mattfarina @prydonius

**Comment by janetkuo** [comment]
> @janetkuo: The label(s) `sig/` cannot be applied, because the repository doesn't have them
> 
> In response to [this](https://github.com/kubernetes/community/issues/4595#issuecomment-597936331):
> 
> > /sig apps

This message is confusing. k8s-ci-robot added `sig/apps` label successfully.

**Comment by mrbobbytables** [comment]
It has now been configured \o/ Going to go ahead and close this out :)
/close
