### ISSUE TITLE
 Define the happy path to multichannel communication

### ISSUE THREAD

**Issue by mbbroberg** [kubernetes/community#4616]
As part of ContribEx Upstream Marketing initiative, we want to provide a clearer way to consume Kubernetes information. This issue is a kickoff to that primary goal of defining our motive, documenting the strategy, and assigning subtasks. 

Here's my first take on our motive: 

- Provide all Kubernetes contributors with a dependable experience of communication.  
- Find ways of adding our human touch to potentially overwhelming quantities of info
- Provide clear expectations on what’s important, urgent, or otherwise
- Build process like we build Kubernetes, so members get it and so it works well at scale

And some strategic considerations: 

- **Define our “one place”** -- where is the one place people can request sharing information? What's the one place we publish to that results in publishing elsewhere?
  - Think of both inbound requests and our outbound communication
- **Define “runbooks”** so others understand what to expect based on our terminology.
  - If you tag a message with X, you will get Y
- **Version control our patterns**: good communication is like an API, and it helps us iterate and beta test new approaches while providing a consistent, trustworthy experience

I started to map this out further in [these slides](https://docs.google.com/presentation/d/1ks-T822afBoeJZFrwWtdh6MqGmvniMF4qE4VS7pzvs8/edit#slide=id.g6f4355f17a_0_58) and I look forward to us jumping into the next steps. 

![Screen Shot 2020-03-13 at 1 14 08 PM](https://user-images.githubusercontent.com/1744971/76648352-873b5380-652c-11ea-8b79-8aa5c3747acf.png)

**Comment by parispittman** [comment]
notes:

outbound: kubernetes-dev@googlegroups.com 
justification: growing in popularity to check for contributor news per 2018 and 2019 survey results, highlighted on the contributor guide, sig readmes, gov docs, etc.

inbound: issue or PR with area/contributor-comms

**Comment by mbbroberg** [comment]
Hey @parispittman, given we're clarifying which part of the marketing team has the next steps, I'm going to tag @jonasrosland / @simplytunde as the owners of this. I'm all for following along and championing the colorful and simple categorization 🔴🟡🔵🟢. 

🎉

**Comment by jonasrosland** [comment]
Thanks @mbbroberg! I think the color scheme could work well, just wondering if mail filters would work on those icons? Such as "if PRIORITY > store in PRIORITY folder". That's fairly easy to accomplish if it's written text, and one more thing would be regarding color usage and accessibility. Need to think on this a bit.

**Comment by mbbroberg** [comment]
Great point. I could see a combo -- color + keyword -- once we get to the
experimental phase of this, then see if it looks good and helps anyone in
practice. Also feel free to email me as part of the experimental outreach.
I'm happy to see it in action.

**Comment by mbbroberg** [comment]
Fixed by #4679 🎉
