### ISSUE TITLE
add meeting notes for marketing team to sigs.yaml

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4623]
meeting notes: https://docs.google.com/document/d/1IlHAJ131akGhI5ffF4OoVW0PrsVY4C0BB8l-UyQaQVo/edit

file to be updated:
https://github.com/kubernetes/community/blob/master/sigs.yaml
- the contributor marketing team entry can be found under sig-contributor experience subproject listings.

**Comment by mbbroberg** [comment]
@Pensu happy to have you give this one a go :tada:
