### ISSUE TITLE
Kubernetes Upstream Marketing Social Media Platform Request

### ISSUE THREAD

**Issue by chris-short** [kubernetes/community#4626]
We have discussed a need for a social media platform that adds more functionality than the current experience on Twitter.com (and other platforms as we expand). The team has some requirements around the ability to schedule posts, an approval process (might be external to the platform), multiple logins (no shared single login, if possible), and availability of APIs for automation. There are several platforms that we evaluated. They are listed below:

1. Salesforce Social Studio
2. Hootsuite
3. Capzool
4. Buffer
5. Sprout Social

Right off the top, we're removing Salesforce and Capzool. Salesforce is overkill in terms of features and pricing ($1000/mo for Salesforce, yikes). Capzool seems like a solid tool, but it doesn't have the APIs we'd want from a social media platform. Sprout Social also doesn't have an API that they expose for automation. This leaves Buffer and HootSuite.

HootSuite provides an extensive feature set, but there is one feature that helps with automated scheduling that I am most interested in. The feature is billed as being able to determine optimal times for social media posts to go out. This is a highly sought after feature for social media publishers. Buffer provides a more focused experience around posting but, from what I can tell doesn't have an auto-scheduling function. Both provide APIs for automation and an approval process for posts in teams. Single user accounts for HootSuite and Buffer are $29/mo and $15/mo, respectively. A single shared login isn't optimal, though. Buffer offers two accounts for $65/month and HootSuite offers three accounts for $129/month.

With the added functionality of auto-scheduling and the extra account for use by a shadow/alternate, HootSuite seems like the best fit for the Kubernetes Upstream Marketing team. But, Buffer could be made to work (with more effort) if the price of HootSuite is too high.

**Comment by parispittman** [comment]
If we have to define our top 3 needs, what are they? we've drawn out approval process and some kind of automation/api that could link us up with slack et al - what else? Trying to look at it as a quick rubric to see where buffer and hoot fall.

**Comment by mbbroberg** [comment]
Great work on this Chris. As  I mentioned in Slack: 

My thought is on what each tool centers on. Hootsuite allows for account management -- tweet, delete, follow/unfollow, etc. Buffer is highly specialized for scheduling and curating -- tweets, retweets, rss feed input, image embedding by default, etc.

Based on what I understand, Buffer is a great choice with a smooth experience. If we need more account management than scheduling, then Hoot is the right answer.

FWIW, I use Buffer daily and love it.

**Comment by chris-short** [comment]
1. Automation capabilities
2. Scheduling capabilities
3. Security (I'm lumping multiple accounts, approval process, etc. into this label)

The automation capabilities are a deal-breaker as is high cost.

Scheduling capabilities exist in all the platforms here but, HootSuite probably has an edge as they're using some intelligence in scheduling.

Security: Approval processes exist in HootSuite and Buffer. But, with only two accounts on Buffer that means approvers will have one account and creators will have another. We'll need to think about that. With HootSuite there's a third account that would allow for more granular controls I feel. I don't like sharing logins for a variety of reasons and that might be skewing my analysis here.

To be clear, I don't think either Buffer or HootSuite will fail us. Both will meet our needs with appropriate processes on our side.

**Comment by mbbroberg** [comment]
> Scheduling capabilities exist in all the platforms here but, HootSuite probably has an edge as they're using some intelligence in scheduling.

I think they're comparable. Buffer auto-schedules based on the number of desired posts per day. I never worry about when it's going out: I hit the icon in Firefox/Chrome and it sends it to be scheduled. It's pretty perfect that way. 

Regarding scheduling, I'd say it hinges on multiple people being able to suggest a post and someone being able to review it. I haven't used that feature on either platform.

**Comment by chris-short** [comment]
Since I personally have a use for such a service, I went ahead and signed up for HootSuite.

@Mbbroberg it’d be cool to sit down and do a side-by-side with @parispittman, Marketing team, and others interested.

**Comment by parispittman** [comment]
whatever trials and things we are signing up for, can we use the projects official stuff instead of having it tied to individuals? i can give access to this team for community@kubernetes.io (googlegroup on the gsuite; less perm overhead) or contributors@kubernetes.io (actual gmail instance which comes with more responsibility)

**Comment by mbbroberg** [comment]
Noting during the upstream marketing meeting today -- still waiting to hear back from Twitter for an API key to use github actions.

**Comment by mbbroberg** [comment]
Note from team meeting today -- this issue will close when we have a documented process for how we review tweets. 

So far we're leaning toward a program-based tweets through the issue template, one-off requests can come in through Slack, recurring/regular tweets can be loaded up and :+1: Friday mornings at the team meeting. 

cc @chris-short @kaslin who are on point.

**Comment by mbbroberg** [comment]
This is technically completed by https://github.com/kubernetes-sigs/contributor-tweets, though needs documentation on how someone manages the twitter account. It's ready to close since we're no longer looking for an external platform. 

/close
