### ISSUE TITLE
REQUEST: New Slack token cluster-api-provider-aws-alerts

### ISSUE THREAD

**Issue by detiber** [kubernetes/community#4641]
**GitHub Username:**
@detiber

**Slack Username:**
jdetiber

**What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?**
Token

**Name of Requested Resource:**
cluster-api-provider-aws-alerts

**Description of Request:**
Request api token to allow for special routing of cluster-api-provider-aws specific alerts from the Prow Monitoring App rather than alerting in #testing-ops where it creates noise that is not actionable.

I'm not exactly sure what type of oauth scopes are necessary, but @Katharine or @cjwagner might be able to provide more specifics.

/cc @cjwagner 
/cc @Katharine 
/assign @mrbobbytables

**Comment by mrbobbytables** [comment]
Just to be 100% clear, this would also be a new channel? (`cluster-api-provider-aws-alerts`) right?

**Comment by detiber** [comment]
@mrbobbytables I had originally naively thought that we could just forward the alerts to #cluster-api-provider-aws, but I like your idea of a new channel better.

**Comment by coderanger** [comment]
+1 from me. Is there a PR for making the new channel?

**Comment by mrbobbytables** [comment]
+1 from me as well, theres no current PR to add the channel specifically, but sounds like theres a few things that need to be sorted out with prow first.

**Comment by detiber** [comment]
Created a PR to add the slack channel here: https://github.com/kubernetes/community/pull/5069
/cc @cjwagner

**Comment by ncdc** [comment]
I see the Slack channel was created. What are the next steps for this? Thanks!!!

**Comment by detiber** [comment]
@ncdc next steps are to coordinate with test-infra-oncall and configure the alerts. I'm not sure if it is possible to do that through git hosted config currently or if it would need to be done externally.

@BenTheElder @cjwagner do either of you have insight into how to proceed?

**Comment by BenTheElder** [comment]
I'm not involved with slack config and I've moved to go.k8s.io/oncall build-admin-oncall. If you think you need something from test-infra-oncall, please reach out via the slack alias.
The prow alerting system I'm not familiar with, I think @cjwagner is though.

**Comment by detiber** [comment]
For configuring the alerts, I believe this will require modifying the prometheus alert manager to route the Boskos aws alerts separately from all of the other alerts here: https://github.com/kubernetes/test-infra/blob/983896656456bc61f0e444e603f362a4de3d7139/config/prow/cluster/monitoring/alertmanager-prow_secret.yaml

**Comment by nikhita** [comment]
Is this still desired?

**Comment by detiber** [comment]
unsure, @randomvariable might have more context if it is still desired.

**Comment by randomvariable** [comment]
This dropped off the bottom of my Github notifications page until today. Eek.

Maybe. I think it'll be helpful in addition to the emails.

CC
@sedefsavas and @richardcase

**Comment by detiber** [comment]
@randomvariable this was less around the email notifications for failed jobs and more around notifications when the pool of available boskos resources is critically low. Currently those alerts go to #testing-ops, but they don't have any action they can take other than trying to track down someone from the CAPI/CAPA community to try and followup.

**Comment by randomvariable** [comment]
Ah, ok. That explains the Prometheus Alert Manager bit.

It might be better to rename the channel a bit more generically like aws-account-alerts (but that's a total super nit), as we're likely to start also using these accounts for the AWS Cloud Provider & CAPI at some point.

Looking at the docs, I don't think we need a new token if  we're using Incoming Webhooks
> Incoming webhooks have a default channel, but it can be overridden in your JSON payload. A public channel can be specified with "channel": "#other-channel", and a Direct Message with "channel": "@username".

I think we only need to set up a route for the boskos alerts, and add an inhibit_rule to the general ones to filter out the boskos alerts (I think, I haven't used alertmanager all that much).

**Comment by randomvariable** [comment]
Had a quick look. I don't feel confident in making the PR without risking breaking Alertmanager without the Prometheus instance to test against

**Comment by randomvariable** [comment]
Trying to see if we can reuse the same token in https://github.com/kubernetes/test-infra/pull/22828/files

**Comment by randomvariable** [comment]
Re-opening this issue in the new Github issue format

/close
