### ISSUE TITLE
Some place to store voice recordings from our bi-weekly sessions

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes/community#4647]
Hi everyone!

At our slack channel one of our users (Niels van Brecht / @meauses) suggested to create some space and store there voice recordings from our sessions for people who can't watch videos but would like to listen them like podcasts.

I'm not aware what are requirements to place that kind of recording on Spotify or other places, but I think it would be a great to start with some bucket where we would place that kind of recordings.

What do you think about that?

Bart

P.S.
I'll try to find more information about how to place that recording on Spotify and similar.

**Comment by spiffxp** [comment]
/kind feature
/lifecycle stale
/sig contributor-experience
I transferred this over from k8s.io because this seems a more appropriate venue for a contribex-related issue

**Comment by parispittman** [comment]
someone with access to contributors@ in contribex can create a public drive for you there. could you figure out how to get them to there?
