### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by CriaHu** [kubernetes/community#4663]
There are some broken links in this project. Most of them are caused by branch based links. If you delete a branch, the link is broken. So I suggest that links in this project should be based on specific submissions.

**Comment by castrojo** [comment]
Can you be more specific? Do you have an example? We could run the 404-checking script again if you mean the community repo. Thanks!

**Comment by CriaHu** [comment]
The directory structure of the community has changed so much that many other projects have lost links to community content, such as enhancements. How to view the references in those projects?
