### ISSUE TITLE
How to view SSL network traffic from the master to the worker

### ISSUE THREAD

**Issue by mydockergit** [kubernetes/community#4670]
I want to debug Kubernetes' network between the master to the worker.  
For example, when the API server needs to create a new pod, I want to see what happens in the background.  
The network is encrypted and I have the weave network plug-in, how can I decrypt it and see what is going on?  

Maybe there is an easy solution to disable the SSL in Kubernetes? just for debugging.

**Comment by mrbobbytables** [comment]
@mydockergit The community repo is used as the general management point of Kubernetes contributor community. Questions like that are not likely to be answered here. =/ 

I'd ask it over in the [#sig-network](https://kubernetes.slack.com/messages/sig-network) slack channel or on their [mailing list](https://groups.google.com/forum/#!forum/kubernetes-sig-networkt).

With that I'm going to go ahead and close this out, if you have any questions feel free to respond or reach out to me directly.

/close

**Comment by mydockergit** [comment]
OK but the mailing list is not working for me, it says that the group does not exist or I don't have access to it. How can I view the mailing list?
