### ISSUE TITLE
sig-leads mailing list to go under gsuite

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4673]
had this conversation in slack and moving here for record. this is not urgent and can be determined by the folks working on infra and contribex as to the priority. 

kubernetes-sig-leads@googlegroups.com gets stale a lot and manually updating and pruning is getting painful for over 75 folks. i'd like to rename and move this group to gsuite owned googlegroup - chairs-and-techleads@kubernetes.io.

**Comment by nikhita** [comment]
Can we use https://github.com/kubernetes/k8s.io/blob/master/groups/groups.yaml instead? 

@spiffxp I think you had raised some concerns about using the current automation in slack (might be misremembering...), but can't find it right now.

**Comment by spiffxp** [comment]
My concern is that a human is involved in reconciliation.  Maybe it's just me, but wait-for-merge, dry-run-for-paranoia, actual-run, and post-that-I-ran-it are all long enough events that I can wander away while they're happening, and then forget to move on to the next one.  Adding the leads group will increase the number of people we reconcile by 20%.

I'm willing to compromise and say we'll do this group. But I don't want any other large groups added after this until we either remove humans from the reconciliation loop, or we speed up reconciliation

**Comment by spiffxp** [comment]
Discussed during steering and we're fine with the compromise I suggested.  We can use the leads mailing list.  We have tech/process debt to pay down before we go any further.

**Comment by spiffxp** [comment]
I don't have the ability to pull members from kubernetes-sig-leads@ but if someone assigns me the PR to k8s.io I can work to reconcile

**Comment by nikhita** [comment]
> I don't have the ability to pull members from kubernetes-sig-leads@ but if someone assigns me the PR to k8s.io I can work to reconcile

@castrojo @mrbobbytables @parispittman do y'all know who has access to https://groups.google.com/forum/#!forum/kubernetes-sig-leads?

**Comment by parispittman** [comment]
i have access, so does @castrojo @jdumars @idvoretskyi @mrbobbytables (through contributors@) lmk where i can send the info

**Comment by parispittman** [comment]
sent to Nikita and spiffxp in slack DMs

**Comment by nikhita** [comment]
created https://github.com/kubernetes/k8s.io/pull/970
