### ISSUE TITLE
MOC ( meet our contributors and office hours ) hours missing on contributor calendar update)

### ISSUE THREAD

**Issue by samudralavamshi54** [kubernetes/community#4676]
Can anyone please update the MOC meet our contributor hours on contributor calendar.
I don't see them if they are updated and i miss it. Sorry in advance.

https://calendar.google.com/calendar/embed?src=cgnt364vd8s86hr2phapfjc6uk%40group.calendar.google.com&ctz=America/Chicago

**Comment by samudralavamshi54** [comment]
@parispittman @mrbobbytables

**Comment by parispittman** [comment]
link fixed - thank you for reporting!!

/close
