### ISSUE TITLE
chair and tech lead folder updates

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4677]
the [chair and tech lead folder's readme](https://github.com/kubernetes/community/tree/master/contributors/chairs-and-techleads) needs some more work that I wanted to do but might be a good first issue for someone else and will go faster :) 

I was envisioning this README in a style like the [developer guide's README](https://github.com/kubernetes/community/tree/master/contributors/devel) as a collection of resources that are scattered in the community repo and steering repo that would be helpful to chairs and tech leads. Add in a descriptive phrase or sentence for each resource. the current README lists some abbreviated file names in the TODOs (not the full file names) and if you need help with finding those, I can be reached in slack DMs (paris) or #sig-contribex. 

please also add the following to the README:
- the chair and tech lead monthly meeting time without the zoom information:
2nd Tuesday and Thursday of the month at 730pm UTC and 430pm UTC respectively

**Comment by Heena-PyCloud** [comment]
@parispittman 
Hi Paris,
I have updated the chair and tech lead monthly meeting time without the zoom information at line 25 in README.md.  and created a pull request. Is there any other process I need to follow for review.

**Comment by Nivedita-coder** [comment]
Is this issue still open ? I would  like to work on this.

**Comment by Riaankl** [comment]
@Nivedita-coder I planned to work on it over the holiday, but did not get round to it yet.
It would be great if you have time to work on it.

**Comment by Nivedita-coder** [comment]
> @Nivedita-coder I planned to work on it over the holiday, but did not get round to it yet.
> It would be great if you have time to work on it.

Yes, I want to work on this issue. Thanks!

**Comment by Nivedita-coder** [comment]
#5399

**Comment by Nivedita-coder** [comment]
#5399

**Comment by mrbobbytables** [comment]
#5399 has been merged \o/
This is good to be closed.

/close
