### ISSUE TITLE
Add sig-aws to org

### ISSUE THREAD

**Issue by k8s-mirror-aws-misc** [kubernetes/community#468]
@idvoretskyi @sarahnovotny 

I will be adding the new sig users here, can you please add them to the org?

**Comment by k8s-mirror-aws-misc** [comment]
😄

**Comment by k8s-mirror-aws-test-failures** [comment]
:1st_place_medal:

**Comment by k8s-mirror-aws-bugs** [comment]
😻

**Comment by k8s-mirror-aws-feature-requests** [comment]
🚀

**Comment by k8s-mirror-aws-proposals** [comment]
🤕

**Comment by k8s-mirror-aws-pr-reviews** [comment]
😷

**Comment by k8s-mirror-aws-api-reviews** [comment]
💃

**Comment by kris-nova** [comment]
I need this done before I can add the teams :( 

https://github.com/kubernetes/community/blob/master/sig-creation-procedure.md#create-the-github-teams

**Comment by luxas** [comment]
Oh, wow, bot take over!!

Does a human control these accounts or was this auto-generated from somewhere :smile:?

**Comment by kris-nova** [comment]
@luxas I created these accounts

I think they are used for bots and for mailing list notifications. I just do what I am told 😄 

@idvoretskyi and @sarahnovotny probably can tell you more.

**Comment by idvoretskyi** [comment]
@luxas @kris-nova these accounts are used for the "service" purposes, a human doesn't need to use them. More details are [here](https://github.com/kubernetes/community/blob/master/sig-creation-procedure.md#github-users-creation).

**Comment by philips** [comment]
Can someone explain what is happening here?

**Comment by idvoretskyi** [comment]
@philips no worries, testing the procedure with @kris-nova

**Comment by jdumars** [comment]
Can this issue be closed?

**Comment by idvoretskyi** [comment]
@jdumars not sure :(
https://github.com/orgs/kubernetes/teams?utf8=%E2%9C%93&query=aws

**Comment by chrislovecnm** [comment]
I am guessing it is some testing that needs to be cleaned up.
