### ISSUE TITLE
What is the difference between "/exec" to "/run" Kubelet's API

### ISSUE THREAD

**Issue by g3rzi** [kubernetes/community#4683]
There are [two APIs](https://github.com/kubernetes/kubernetes/blob/c1f1b1bceb8e6dfbc0083617a25f17dd8d57340b/pkg/kubelet/server/server.go#L398) for Kubelet agent that I didn't understand their differences:

1. `/run`
2. `/exec`  

Both of them allow to run command inside a container, what is the difference between them ?

According to https://github.com/kubernetes/kubernetes/blob/c1f1b1bceb8e6dfbc0083617a25f17dd8d57340b/pkg/kubelet/server/server.go#L767-L811
It looks like `/run` just run a command inside the container and `/exec` does the same thing but allows also streaming (interactive ?)

**Comment by mrbobbytables** [comment]
@g3rzi The community repo is used as the general management point of Kubernetes contributor community. Questions like that are not likely to be answered here. =/

I'd ask it over in the [#sig-node](https://kubernetes.slack.com/messages/sig-node) slack channel or on their [mailing list](https://groups.google.com/forum/#!forum/kubernetes-sig-node) as they're the owners of the kubelet codebase.

**Comment by g3rzi** [comment]
OK I can do it
