### ISSUE TITLE
REQUEST: auto-upload of sig-arch meeting recordings

### ISSUE THREAD

**Issue by johnbelamaric** [kubernetes/community#4696]
We would like to get the auto-upload set up, please.

/cc @dims @derekwaynecarr

**Comment by dims** [comment]
+1 thanks!

**Comment by johnbelamaric** [comment]
I created a separate zoom ID for code org, see #4698. One question: Do we need to auto-record the meetings too, or can we still start the recordings manually?

**Comment by mrbobbytables** [comment]
Nope, recording manually is preferred as long as things are saved to the cloud. If you setup auto-recording the youtube team has to do more trimming and there will be random small vids when people hop in and then hop back out.

**Comment by mrbobbytables** [comment]
I reached out in PM, but for transparency sake -- We're going to hold off setting this up at this time until Zoom is [able to reliably deliver webhooks again](https://devforum.zoom.us/t/developer-impacting-changes-during-covid-19/8930). This has caused for intermittent failures to upload across all enabled accounts and is not something that should currently be relied upon.

I will update when I have more promising news =/

**Comment by mrbobbytables** [comment]
/remove-lifecycle stale
Splain is still having problems sadly :(
