### ISSUE TITLE
REQUEST: auto-upload of kops office hours meetings

### ISSUE THREAD

**Issue by justinsb** [kubernetes/community#4699]
We would like to get the auto-upload set up, please.

/assign @mrbobbytables

**Comment by mrbobbytables** [comment]
I reached out in PM, but for transparency sake -- We're going to hold off setting this up at this time until Zoom is [able to reliably deliver webhooks again](https://devforum.zoom.us/t/developer-impacting-changes-during-covid-19/8930). This has caused for intermittent failures to upload across all enabled accounts and is not something that should currently be relied upon.

I will update when I have more promising news =/

**Comment by mrbobbytables** [comment]
/remove-lifecycle stale
Splain is still having problems sadly :(
