### ISSUE TITLE
Kubernetes Alpha Feature Posts

### ISSUE THREAD

**Issue by onlydole** [kubernetes/community#4710]
During any given Kubernetes release, alpha features that are added don’t typically get a large focus unless they are called out directly. The upstream marketing team can create posts about the alpha features and work with SIGs to get their alpha features highlighted and to get end-user feedback. These feature posts should use a tool like [discuss.kubernetes.io](https://discuss.kubernetes.io) or some other medium to capture as much feedback as possible.

/cc @mrbobbytables @parispittman @mbbroberg 
/milestone v1.19
/kind feature
/priority important-longterm

**Comment by mbbroberg** [comment]
@onlydole love the idea. It'd be great to advertise / feature alpha features regularly. Let's talk through what a programmatic approach to this looks like.

**Comment by mbbroberg** [comment]
@mrbobbytables talking through this in practice: 

- Alpha feature gets published
- Discuss (in Discourse) thread starts for that feature
- We're notified to write an article about the feature and embed the Discuss thread as the call to action at the end of the article

**Comment by parispittman** [comment]
this falls under the same premise as #4729 and both processes should match for getting approvals, etc

**Comment by LappleApple** [comment]
This is a great idea—thanks @onlydole! And thanks @mrbobbytables for looping me in. Two things:

- Maybe Discuss is the right tool for generating the feedback—I'll defer to others as I haven't used it. We might also encourage posting a structured (and brief) Google Form created by the SIG to gather user feedback on specific points or details. A highly polished, inspiring and thorough example of a user survey is this recent one by [Cluster Lifecycle](https://docs.google.com/forms/d/1AA75xUUdsboenrGPFN-Dtnx8N8vfR_b3kmmQNrdXX4g/viewanalytics). That one is comprehensive—I'd go much shorter—but worth using as a guide.
- Posts could include a section highlighting and describing the "what we're thinking about for beta/GA" to give readers an idea of the KEP's future direction (but no promises/commitments on still-uncertain things, to manage expectations from the readers). 
- can use a pullout box with bullet points highlighting the key attributes of the Alpha version, or key questions for which user feedback is sought.

How does that sound, to start?

**Comment by mbbroberg** [comment]
If anyone would like to write this up, we can keep this issue around. Otherwise, let's let it close and mark Alpha features as an ideal piece of content for the Comms release liaison.

**Comment by onlydole** [comment]
@mbbroberg - Agreed! I'm going to close this for now as it's a good comms action item.
