### ISSUE TITLE
Can kubemark master be a normal node of external cluster?

### ISSUE THREAD

**Issue by chauncey-77** [kubernetes/community#4712]
I see the doc community/contributors/devel/sig-scalability/kubemark-setup-guide.md says that before starting a kubemark cluster, we need kubemark master and external cluster. I have a question, can the kubemark master be a normal node of the external cluster? Because I just have a k8s cluster and no more other machine.
/sig scalability

**Comment by mrbobbytables** [comment]
@chauncey-77 The community repo is used as the general management point of Kubernetes contributor community. It's unlikely that your question would get answered here =/

I'd ask it over in the [#sig-scalability](https://kubernetes.slack.com/messages/sig-scalability) slack channel or on their [mailing list](https://groups.google.com/forum/#!forum/kubernetes-sig-scale) as they're the [owners of kubemark](https://github.com/kubernetes/community/tree/master/sig-scalability#kubernetes-scalability-test-frameworks).

**Comment by chauncey-77** [comment]
@mrbobbytables thank you very much, but I don't have account in kubernetes.slack.com so that I can't log in to check the slack channel. So, when next time I have another question I should send mail to them directly?

**Comment by mrbobbytables** [comment]
You can join slack here: https://slack.k8s.io/
But yes -- you can email directly.

**Comment by chauncey-77** [comment]
@mrbobbytables it's very kind of you, thanks. Beside send email, maybe I can open issue in the Kubernetes repo instand of the community repo?

**Comment by mrbobbytables** [comment]
You can give that a go, but I think you will wind up with the quickest response reaching out in either slack or their mailing list.

**Comment by mrbobbytables** [comment]
@chauncey-77 I'm going to go ahead and close this out. If you have any other questions, please feel free to reach out to me directly.

/close
