### ISSUE TITLE
Correct wg-api-expression meeting info

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#4715]
Followup issue for https://github.com/kubernetes/community/pull/4655/files#r404382727

The `url:` should link to a zoom meeting, not a calendar entry. You should use a scheduled zoom meeting instead of an account's personal meeting id. See https://github.com/kubernetes/community/blob/master/communication/zoom-guidelines.md#setting-up-your-meeting-and-moderation for more info

There should be an `archive_url:` property and it should link to a meeting agenda

/assign @kwiesmueller @apelisse 
/sig api-machinery

**Comment by kwiesmueller** [comment]
Thanks, will do.
