### ISSUE TITLE
Follow up on issues labeled 'milestone/needs-attention' 

### ISSUE THREAD

**Issue by LappleApple** [kubernetes/community#4723]
As per my Slack message, [these 30 open issues](https://github.com/search?q=org%3Akubernetes+is%3Aopen+label%3Amilestone%2Fneeds-attention&unscoped_q=is%3Aopen+label%3Amilestone%2Fneeds-attention) dated March 26, 2018 and filed by @mtaufen include the `milestone/needs-attention` label, which seems to have been either abandoned or never adopted into general use. All but one of the issues refer to migrating Kubelets. Should the label be dropped from these items?

**Comment by nikhita** [comment]
/sig contributor-experience
/sig release

cc @justaugustus @mrbobbytables

**Comment by mrbobbytables** [comment]
I think the removal will need to be manually reconconciled -- It looks like they're a vestigial piece from mungegithub. -- I didn't see it in the history of label_sync.

**Comment by mtaufen** [comment]
I'm not sure about why the needs-attention label was applied, probably fine to remove?

**Comment by mrbobbytables** [comment]
> I'm not sure about why the needs-attention label was applied, probably fine to remove?

I think so 👍  

/remove-lifecycle stale

**Comment by nikhita** [comment]
/assign

I think it can be removed too, but I'll follow up with folks in sig release/testing around the historical reasons for why this was added.

**Comment by mrbobbytables** [comment]
The label has been removed from all open items, going to go ahead and close this out 👍 
/close
