### ISSUE TITLE
adding area/contributor-comms label to other repos

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4728]
need to add the area/contributor-comms label to:
kubernetes/website (we are blogging there) and 
kubernetes/enhancements (if the author and reviewer/approvers would like a wider net of comments, feedback, +anything else)

labels.yaml needs to be updated. might not be a good first issue because of my lack of time to mentor but a good help wanted if you've done this before:)

**Comment by nikhita** [comment]
> might not be a good first issue because of my lack of time to mentor 

I have bandwidth and I'm happy to help out with this! :)

/good-first-issue

Steps on how to proceed here:

- The [labels.yaml](https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.yaml) file defines all the labels that are used in the Kubernetes project across multiple repos. The file configures what a label's color and description is, what repos a label should be present in, etc.

- The file can be considered to be split into multiple parts - a "default" set of labels that are present across all repos in the kubernetes org, and a set of additional labels defined for each repo.

- The `area/contributor-comms` label is currently only defined for `kubernetes/community` here. We want to duplicate it to other repos as well - https://github.com/kubernetes/test-infra/blob/bf417d86043427e5c84ab8939ce196a92b4d90c2/label_sync/labels.yaml#L789-L793

- To add it to `kubernetes/website`, you'll need to copy the above part to this section - https://github.com/kubernetes/test-infra/blob/bf417d86043427e5c84ab8939ce196a92b4d90c2/label_sync/labels.yaml#L1233

- Similarly, to add it to `kubernetes/enhancements`, you'll need to copy the above part to this section - 
https://github.com/kubernetes/test-infra/blob/bf417d86043427e5c84ab8939ce196a92b4d90c2/label_sync/labels.yaml#L794

- Once that's done, the [labels.md](https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.md) file needs to be auto-generated. You can auto-generate it by running the last bazel command in [this section](https://github.com/kubernetes/test-infra/tree/master/label_sync#usage). If you don't already have bazel installed, [official instructions](https://docs.bazel.build/versions/master/install.html) and [bazelisk](https://github.com/bazelbuild/bazelisk) are good places to start out.

If anyone wants to take this up and has further questions, feel free to ping me on slack too (I'm `nikhita` there).

**Comment by lfrancke** [comment]
If no one else gets to this before then I'd take a look (first issue for me) at it this afternoon. Thank you @nikhita for the offer to help.

**Comment by lfrancke** [comment]
@nikhita Thank you for the detailed instructions. It'd have taken me ages otherwise.

**Comment by nikhita** [comment]
@lfrancke Glad it helped! :smile:

**Comment by nikhita** [comment]
Will remove the good first issue label since @lfrancke has got it covered :)

/remove-good-first-issue

**Comment by nikhita** [comment]
Fixed in https://github.com/kubernetes/test-infra/pull/17297

Thanks again, @lfrancke!

/close

**Comment by lfrancke** [comment]
Thanks for your help @nikhita!
