### ISSUE TITLE
REQUEST: Windows VMs for minikube integration test

### ISSUE THREAD

**Issue by medyagh** [kubernetes/community#4736]
### GitHub Username
medyagh

### Property you'd like to Moderate
need windows VMS capable of running hyperV to run minikube's integration tests

### Info
Hi I am one of minikube's maintainers and I need to add windows integration tests for minikube, I would like to get Windows VMs in the the cloud capable of running HyperV, provided by CNCF budget for our integration tests
https://github.com/kubernetes/minikube

**Comment by nikhita** [comment]
@medyagh Can you open an issue with more details in the kubernetes/funding repo - https://github.com/kubernetes/funding/issues/new/choose? Specifically, we would need more information about expected budget (the issue templates should help with filling all the necessary info).

A good example of this is https://github.com/kubernetes/steering/issues/156. 

I'll keep this issue open until a new issue opened in k/funding. :+1: 

/remove-sig contributor-experience
/remove-area community-management
/committee steering

**Comment by idvoretskyi** [comment]
@medyagh you may want to request the compute resources on the CNCF Cluster (backed by Packet.com) - https://github.com/cncf/cluster.

**Comment by nikhita** [comment]
@medyagh Closing this issue, please create a new issue in https://github.com/kubernetes/funding with the necessary details.

/close
