### ISSUE TITLE
Revising Issue Triage page to include workflow/automation KEP details, other adds

### ISSUE THREAD

**Issue by LappleApple** [kubernetes/community#4743]
I've created a [draft revision](https://github.com/kubernetes/community/pull/4744/files) of the [issue triage guide](https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md), and shared it in the #contribex channel to get some feedback (received). 

Some highlights:
- Tools section that mentions Gubernator, Project Boards, DevStats, etc.
- Process Pointers from SIGs on how to run triage sessions
- step-by-step flow
- ToC

Would be great if some of you could give this a look and provide feedback. It currently does not include points made in the recently merged [Issue Triage Workflow and Automation KEP](https://github.com/kubernetes/enhancements/pull/1554#issuecomment-619277659), so the next step would be to integrate key portions into the guide pending your suggestions. 

ref #4744

**Comment by LappleApple** [comment]
Hi, I've made changes based on posted comments so perhaps this is ready for another look?

**Comment by mrbobbytables** [comment]
/assign @mrbobbytables @spzala 
To document the needs-triage workflow

**Comment by spzala** [comment]
> /assign @mrbobbytables @spzala
> To document the needs-triage workflow

@mrbobbytables I will create a PR for this in a day or two. Thanks!

**Comment by spzala** [comment]
@mrbobbytables as I started working on it, I see that the current triage workflow is probably missing few things and we should wait before updating the flow in the guidelines. I will put some more thoughts and share the findings for discussion with the SIG and folks involved in the related triage KEP.

**Comment by spzala** [comment]
Created this one for further discussion - https://github.com/kubernetes/community/issues/5358

**Comment by mrbobbytables** [comment]
As #5430 has merged, this should be safe to close \o/
It was the last item on the list with the large changes being done in #4744

/close
