### ISSUE TITLE
Documentation: "Naming Conventions" errata

### ISSUE THREAD

**Issue by wabernatScality** [kubernetes/community#4772]
The Naming Conventions section (https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#naming-conventions) has the following issues: 

* First bullet: "Go field names must be CamelCase. JSON field names must be camelCase. Other than capitalization of the initial letter, the two should almost always match. No underscores nor dashes in either."
  * The Go field name example is Pascal case, not camel case.
  * In the last sentence, change "nor" to "or."

* In the second bullet: "Field and resource names should be declarative, not imperative (DoSomething, SomethingDoer, DoneBy, DoneAt)", remove or rephrase "DoSomething."  "DoSomething" is imperative, hence an inapt example.

**Comment by sftim** [comment]
Also relevant to
/sig docs

**Comment by sftim** [comment]
I'd definitely like for the Kubernetes documentation to clarify what Kubernetes means by the term “camel case”, because that use is different from the most common use outside of Kubernetes (with the first letter lower case).

**Comment by sftim** [comment]
“Pascal case” is fine if that's what's meant.
