### ISSUE TITLE
Document storytelling process

### ISSUE THREAD

**Issue by mbbroberg** [kubernetes/community#4780]
Document a default article flow for interviewing people from the technology standpoint and the editorial one. 

First take: 

Tools: 

- Google doc with questions for SIG/interviewee (give a due date for responses)
- Create another document for the article draft in either Google Docs or hackmd
- Invite feedback for the draft and iterate 
- Open a PR for the final draft 

Editorial tips: 

- Start with your background on the topic or some other framing of the conversation
- Find these two points: 
  - A focus area from the discussion
  - The call to action (what we want people to _do_ after reading)
- Build a story starting from the background framing, to the most interesting part of the focus all the way to the call to action. 

Ex. If I interviewed SIG Security and they recently solved a complex security bug (focus) and were looking for more contributors (call to action), I would build a story that covers: 

- Either my interest in security or some background info on SIG security
- Unpack the story of the bug report. What, where, and when it happened. Build up to the resolution, then resolve it.
- Finish with the call to action: "If you want to solve bugs like these and learn from some of the best in the industry, SIG Security is looking for new contributors." Where `[looking for new contributors]` links to the `how-to-join` header in their documentation. 

/sig contributor-experience
/area contributor-comms

**Comment by mbbroberg** [comment]
We still want to work on this. 

/remove-lifecycle rotten

**Comment by mbbroberg** [comment]
Thanks for signing up to work on this Jason! 

/reopen 
/unassign @mbbroberg 
/assign @JasonMorgan

**Comment by JasonMorgan** [comment]
Heyo! I'd love to take this!

**Comment by mbbroberg** [comment]
Closing this in favor of https://github.com/kubernetes/community/issues/5574 which documents the desired outcome of filling in the existing TODO. 

/close
