### ISSUE TITLE
sig-gov de-dupping evolution continues..

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4781]
we merged and want to iterate again now on [sig-governance.md](https://github.com/kubernetes/community/blob/master/committee-steering/governance/sig-governance.md) based on some comments that were left from folks and what we see as gaps now that we've collated 

tasks:
- [ ] take the first section about general sig operations and simplify this so it isn't a repeat of the chair duties below. a way to solve this could be listing out the general activity with a link to it's canonical source without the detail 
example:
    - [community meeting](link to the procedure around community meetings)
- [ ] create sections for the duties in the chair section to break up the text, ie: "community updates:", "operations:", "cncf/kubecon stuff" as loose examples
- [x] whitespacing issues
- [x] line 69-72 needs editorial changes
- [x] general formatting and other style guide changes

**Comment by nikhita** [comment]
@parispittman do you think this can be closed?
