### ISSUE TITLE
REQUEST: New tool integration with Kubernetes community

### ISSUE THREAD

**Issue by gkarthiks** [kubernetes/community#4782]
**GitHub Username:** @gkarthiks 

**Slack Username:** Karthik

**What Type of Request is it ?**
There is a commercial app named **[Zapier](https://zapier.com/)** which connects multiple web applications. 
For when a netlify application deployment is succeeded, we can trigger a slack-channel message, email announcement, tweet etc as shown in the fig below.

But there is one thing to note, to integrate all the applications that needs to be used in the event flow, Zapier needs to onboard those with the credentials or tokens. And the admin can create event flow that triggers multiple actions that are attached in a flow.

So this issue request is to check capability for adding this commercial tool. Brought this in the contribex and I was suggested to check with Slack Admins.  Not sure if that is something we should invest in. So looking for some thoughts and comments here from everyone.

/cc @parispittman 
/cc @mrbobbytables 

![image](https://user-images.githubusercontent.com/30545166/82114054-f07f5300-9777-11ea-88ad-d5a4f9b133bb.png)

**Comment by coderanger** [comment]
Is this re: https://github.com/rajula96reddy/k8s-slack-contribex-marketing-bot ?

**Comment by gkarthiks** [comment]
Not directly, but something like that can be used as a source of truth for rest of the communications. This commercial app (zapier) is capable of much more automated works. Not sure if that is something we should invest in. So looking for some thoughts and comments here from everyone.

**Comment by coderanger** [comment]
I think you should update the top comment with a much more detailed description of what you are proposing then.

**Comment by gkarthiks** [comment]
Thanks @coderanger, I have updated to my best. lemme know if this needs more detailed information.

**Comment by coderanger** [comment]
What specific flows are you suggesting we create? We would probably want those worked out ahead of time to avoid creating a spam problem.

**Comment by coderanger** [comment]
Also is this request coming from SIG-ContribEx? We don't generally allow this kind of thing, I might have been misunderstanding last night if this was an official SIG request or just you personally working on something?

**Comment by mrbobbytables** [comment]
@coderanger It is coming from the marketing team under sig-contribex. Zapier was something we did experiment with some time ago, but not in its slack capacity (cc @castrojo)

**Comment by coderanger** [comment]
@mrbobbytables Yeah, my understanding was we decided to move forward with the bot rather than Zapier though? I might just be missing a loop :)

**Comment by jdumars** [comment]
My two cents: I am strongly against integration of commercial tools unless it is a critical use case, and supported across other CNCF projects. Given the above comments and staleness, I am inclined to close this issue in ~1 week barring objections.

**Comment by gkarthiks** [comment]
I agree to not bring in the commercial tool as well. This issue is to check the sentiment across the board for this. 

I will close this issue.
