### ISSUE TITLE
"Meet our contributors" weird sentence

### ISSUE THREAD

**Issue by lfrancke** [kubernetes/community#4790]
I initially opened this in the wrong repo: https://github.com/kubernetes-sigs/contributor-site/issues/130

The Meet our Contributors page has this sentence:

> Grab a copy of the calendar to yours from kubernetes.io/community

Something seems to be missing in that sentence.
I'm not sure what the intention was.
In addition, there's no calendar to be found at that site.

Happy to create a PR to just remove that sentence..

**Comment by markyjackson-taulia** [comment]
@lfrancke Pr would be awesome!

**Comment by lfrancke** [comment]
Sure, I'm just not sure what it should say. Are you fine with just removing that bit?
