### ISSUE TITLE
openstack-volume driver unable to find virtio-scsi devices.

### ISSUE THREAD

**Issue by shannonmitchell** [kubernetes/community#4797]
The issue is with this device matching code in the openstack_volumes.go file:  https://gitlab.dev.cncf.ci/kubernetes/kubernetes/blob/6c7afd1222ebf2cb91567364471d74ac056437b7/pkg/cloudprovider/providers/openstack/openstack_volumes.go#L483

It is limiting the volumeid to 20 characters when looking for /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_<volumeID> devices.  We are seeing the full volume id within the OS causing the match to fail against the check with the 20 char limit.   The result is the following error:

`W0520 16:21:31.842907   17689 openstack_volumes.go:561] Failed to find device for the volumeID: "e4bdcdb3-c858-48d3-86b1-52a92d05ae3b"
E0520 16:21:31.842937   17689 attacher.go:246] Error: could not find attached Cinder disk "e4bdcdb3-c858-48d3-86b1-52a92d05ae3b" (path: ""): <nil>
`

We created a new symlink with the 20 char limit under /dev/disk/by-id/ to verify.  As soon as the link was in place the pod saw the device and came online.  

Updating the check to remove the ':20' char limit or adding a new one without the limit should fix the issue.

**Comment by shannonmitchell** [comment]
Looks like there is a related open PR(https://github.com/kubernetes/kubernetes/pull/89726) and a fix in cloud-provider-openstack.  (https://github.com/kubernetes/cloud-provider-openstack/pull/853)

**Comment by mrbobbytables** [comment]
The community repo is used as the general management point of Kubernetes contributor community. Questions like that are not likely to be answered here. I'd follow up in one of those open issues.

/close
