### ISSUE TITLE
sig/docs about kube-cross image problem

### ISSUE THREAD

**Issue by houfangdong** [kubernetes/community#4815]
hello，
I am currently compiling version 1.18.3 and found that the cross mirror repository has been removed.
https://github.com/kubernetes/community/blob/master/contributors/devel/development.md
question：
The image for cross compiling in build / build-image / cross.
It has been moved to k / release / images / build / cross.
But now the link given to the **Upgrading Go chapter** is wrong. 
/sig docs
/sig @justaugustus

**Comment by justaugustus** [comment]
/assign
/sig release
/area release-eng

@houfangdong -- I've got updated documentation coming within the next week or two for Go.
cc: @kubernetes/release-engineering

**Comment by nikhita** [comment]
@justaugustus @LappleApple do you know if we are tracking this in a sig-release issue and/or if this issue is good to be closed?
