### ISSUE TITLE
NCW2: New Contributor Workshop Virtual

### ISSUE THREAD

**Issue by alisondy** [kubernetes/community#4830]
## Motivation

In the past, we delivered the New Contributor workshop as a live in person workshop. There was alot of issues with this approach, bad conference wifi, inaccessible to folks who couldn't attend a kubecon, folks presenting couldn't attend other contributor summit sessions.

### Goals
- Each section of the contributor workshop surfaced as a doc on the contributor site
### Non-Goals
- Producing a video recording for each segment 

## Proposal

Create a self paced workshop hosted on the contributor site. Each section of the contributor workshop as a doc.

## Implementation

Each segment exists as it's own page in the workshops folder on ``kubernetes/contributor-site`` repo.

Information surrounding how to contribute to the Contributor Workshop initiative, such as how to add a segment, recording guides is surfaced in the``mentoring/programs/contributor-workshop`` folder on the ``kubernetes/community`` repo.

### How does the workshop differ from the developer guide

The workshop provides a guided path for folks wanting to learn more about contributing whereas the developer guide is more of a reference * im not 100% sure on this

The workshop will refer to the developer guide in some parts

## Issues

What | Link to issue |
--- | --- |
Call for volunteers | #4830 (this issue)
Contributing Guide | 
Marketing Material |
Video Recording Guide | [Document Here](https://github.com/kubernetes/community/blob/master/mentoring/programs/new-contributor-workshop/videoguide.md)
Page for each segment of workshop | #4549
Webpage | #4894

Related issues
[Boxing Up NCW](https://github.com/kubernetes/community/issues/4010)
[Improve YT Leave Behind](https://github.com/kubernetes/community/issues/4539)

**Comment by savitharaghunathan** [comment]
Hi @alisondy , I am interested in volunteering if you are still looking for one, or help anywhere needed.

**Comment by raelga** [comment]
🥳
