### ISSUE TITLE
New release notes process and guidance

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/community#484]
Forked from https://github.com/kubernetes/features/pull/204 and other discussions.

We put our release notes here:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md

The original release-note mechanism design and release changelog template were described here:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release-notes.md

A decision about whether a PR should generate a release note was made merge-blocking in the PR workflow, as described here:
https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md#release-notes

We subsequently made it possible to both set the labels automatically from the PR template, if properly filled out, and created /release-note commands to enable non-maintainers to set the labels, as described here:

https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md#set-release-notes

We also subsequently developed the features repo and process, from which some of the release notes are created by hand, based on which features target the release.

It's clear that the release-note mechanism in the kubernetes repo is causing too much contributor friction, that most people don't know what deserves a release note (e.g., examples, tests, and build scripts shouldn't have release notes) or what would make a good release note, and that the features repo provides another potential mechanism for surfacing release notes.

** What is the purpose of release notes **

Release notes give our users a heads-up about what is coming when they install or upgrade to a particular release of Kubernetes.

They are not primarily for contributors to Kubernetes, who could look at the PRs associated with a particular git tag.

** What deserves a release note **

Any significant user- or admin-visible change. It could be an API change, a CLI change, a UI change, a configuration schema change, a behavioral change, a change in non-functional attributes such as efficiency or availability, availability of a new platform, advance warning about deprecation of a feature, etc.

Fixes of issues previously cited as Known Issues due to the breadth and/or severity of their impact also qualify, as do CVE fixes.

** What doesn't deserve a release note **

Not exhaustive:
* tests (e.g., `Fix TestServiceAlloc flakes`)
* examples
* build infrastructure
* fixes of unreleased bugs
* fixes of minor bugs
* ideally, incomplete/inaccessible features

** What should be in a release note **

* Clear, concise description of the change
  * Explicitly name affected API or configuration fields, CLI commands or flags, relevant feature, measured non-functional changes, etc., in user-visible terms (e.g., using json field names rather than Go field names)
  * State whether it was added, removed, changed, deprecated, advanced in maturity (alpha, beta, stable), etc.
  * Link to relevant user documentation about the feature or, if non-trivial actions are required, about the change itself (yes, docs shouldn't be an afterthought)
  * Make the information relevant to and actionable by admins or users, if necessary.  (For example, `Fix GCI mounter issue` is not.)
* Appropriately categorized
  * Feature
  * Action required
  * Deprecation announcement
  * Other notable change, categorized by component or feature area (not by contributor concepts such as SIG or code repo)

We also need some way of reporting known issues left unaddressed in the release, and recommended versions of dependencies (e.g., etcd, container runtimes), along with their known issues.

cc @idvoretskyi @calebamiles @fejta @pwittrock

**Comment by bgrant0607** [comment]
It's also worth looking at:

https://github.com/linuxfoundation/cii-best-practices-badge/blob/master/doc/criteria.md#release_notes

The project MUST provide, in each release, release notes that are a human-readable summary of major changes in that release to help users determine if they should upgrade and what the upgrade impact will be. The release notes MUST NOT be the raw output of a version control log (e.g., the "git log" command results are not release notes).

**Comment by idvoretskyi** [comment]
@bgrant0607 should it work for _every_ release (including minor x.y.z) or major only (x.y.0)?

**Comment by xiangpengzhao** [comment]
@bgrant0607 @idvoretskyi does this issue make sense?

"Consider splitting CHANGELOG in separate files"
https://github.com/kubernetes/kubernetes/issues/48985

**Comment by zhangxiaoyu-zidif** [comment]
I think one release should have its own changelog in a independent files.
We can create a dir for these changelog files. :)

**Comment by dchen1107** [comment]
I made the proposal on how to automate the  release note in 1.7 release cycle at: 
https://docs.google.com/presentation/d/1f-Td0Fs1kR3rSWlYzR0EJ2PFgd8_R2srlE_O_vxwdlk/edit#slide=id.p 

The initial discussion among the kubernetes community is here: https://groups.google.com/forum/#!topic/kubernetes-dev/NNnbHAhzuVI

**Comment by bgrant0607** [comment]
@calebamiles @jdumars Could we please find someone to document this?

**Comment by justaugustus** [comment]
Adding RT Release Notes peeps from 1.10, 1.11, 1.12 to provide additional color and maybe get a volunteer to document the process.

/cc @nickchase @qedrakmar @marpaia @dstrebel @onyiny-ang

**Comment by bgrant0607** [comment]
Changes to the set of conformance tests should have release notes that briefly explains what the change is to someone who cares about what conformance tests are run, passing/failing, etc., such as a Kubernetes provider or someone building their own cluster "the hard way".

**Comment by marpaia** [comment]
CC @dstrebel @onyiny-ang and @jeefy to follow-up with @bgrant0607 and the Conformance Working Group to determine what content we should add to the release notes regarding the changes that are happening.

**Comment by saschagrunert** [comment]
A note from my brain: Beside writing a guideline/contributor checklist, we could also introduce some sort of _assisted review_ process around in conjunction with the release notes team.

@mariantalla what do you think?

**Comment by saschagrunert** [comment]
I think a good first step is to bring these information into the contributors guide: #4274

**Comment by mrbobbytables** [comment]
Assigning other relnotes owners to for additional ack
/assign @jeefy @onyiny-ang @marpaia

@saschagrunert @jeefy @onyiny-ang @marpaia - Do you think this is good enough to be closed at this point?

**Comment by saschagrunert** [comment]
> Assigning other relnotes owners to for additional ack
> /assign @jeefy @onyiny-ang @marpaia
> 
> @saschagrunert @jeefy @onyiny-ang @marpaia - Do you think this is good enough to be closed at this point?

I think we're probably fine with https://github.com/kubernetes/community/pull/4274 and https://github.com/kubernetes/community/pull/4282 and I suggest in closing this issue. :+1:

**Comment by jeefy** [comment]
+1 to closing

**Comment by mrbobbytables** [comment]
with 2 acks, I'm going to go ahead and close this out. Thanks!

/close
