### ISSUE TITLE
Feature Request for Community Communication: bulletin notifications

### ISSUE THREAD

**Issue by mbbroberg** [kubernetes/community#4854]
Capturing an interesting request that relates to #4446, which is in progress.

From Slack: 

```
Is there any longterm publicly visible reminder system, for example “swap out the XYZ images, because they have a deprecation date of bleh, so remind me two weeks ahead of bleh”. A list of chore tasks that need to be done every so often, but publicly recorded and so we get bugged every now and then to do them.
I can do a private slack reminder, but nobody else can see that, and it’s attached to slack.
Any idears?

paris:verified:  21 hours ago
what about a reminder in a channel like kubernetes-dev?

justaugustus:kubecat:  18 hours ago
@mhb @paris -- Even cooler if it's a bulletin system of sorts that people can PR to, maybe takes multiple inputs

mhb  16 hours ago
Oh, does everyone have perms to do channel reminders? I can try that.

mhb  16 hours ago
not that I want to encourage people to spam reminders.

mhb  16 hours ago
good idea. As well as PR/git controlled system.

paris:verified:  14 hours ago
the slack-admins can. @contributor-comms might be able to hash out some ideas too and help with figuring out next steps.
```
/sig contributor-experience
/area contributor-comms

**Comment by justaugustus** [comment]
This could be useful to us, @kubernetes/sig-release + @kubernetes/product-security-committee

**Comment by mrbobbytables** [comment]
Just pinging in here - any update on this?

**Comment by nikhita** [comment]
:wave: would this be a part of slack-infra?

**Comment by mbbroberg** [comment]
This concept never quite materialized into a plan. In discussion with Contrib Comms, we're concluding that pointing users to release the most important location to date. We haven't figured out a place or message that should go on a bulletin board, but there was some discussion on the homepage of k8s.dev having a status of key activities. 

That leads to more questions than actions. With that in mind, closing this issue as unactionable.
