### ISSUE TITLE
Archive kubernetes-sig-leads google group

### ISSUE THREAD

**Issue by nikhita** [kubernetes/community#4892]
The https://groups.google.com/g/kubernetes-sig-leads google group has now moved to leads@kubernetes.io (https://groups.google.com/a/kubernetes.io/g/leads). See https://github.com/kubernetes/k8s.io/pull/970 and https://github.com/kubernetes/community/issues/4673 for more details.

With this move, we need to archive the old google group (ref: https://github.com/kubernetes/k8s.io/pull/970#issuecomment-649002807)

contributors@kubernetes.io are owners of the old google group and they have access to archive it.

/assign @castrojo @jdumars @idvoretskyi @mrbobbytables @parispittman 
(members behind contributors@)

**Comment by castrojo** [comment]
/assign

I've moved/fixed the TL/Chairs leads doc into the contributors@ gdrive and shared the permissions to the proper groups. I'm going to make a final scrub through the repo next week to check for dangling references to the old doc and fix them.

**Comment by castrojo** [comment]
/close

I've set the old group to "owners" only allowed to post per the google groups documentation. The last post was 24 days ago and the the traffic on the new leads group is recent, so closing this for now.
