### ISSUE TITLE
NCW2: Create page for NCW

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#4894]
We need to create a web page that will hold the NCW.  This should be on some page controlled by the Kubernetes community, and not on a CNCF/Kubecon page for ease of updating.  The page should include:

- Text introduction
- TOC of all the NCW segments, with descriptions, and links to both materials and video
- Links to other contributor guide materials
- Link to next steps (become an org member, usually)
- Qualification information on how to get their Kubernetes patch (currently TBD)

/sig contributor-experience
/kind documentation
/area new-contributor-track
/help

cc:
@alisondy @markyjackson-taulia

**Comment by mrbobbytables** [comment]
I think it'd make sense to add this to the contributor site -- we'll have the contributor guide and other docs there. What do you think?

**Comment by jberkus** [comment]
Yes, clearly ... where woudl we drop the files right now to make sure they get included in the contributor site?

**Comment by jberkus** [comment]
New location is going to be contributor-site/docs/newcontributor/

**Comment by alisondy** [comment]
https://github.com/kubernetes/contributor-site/tree/workshop once this is merged in / when we release the workshop to public this issue will be complete
