### ISSUE TITLE
NCW2: create Kubeconless version of slide deck

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#4897]
The New Contributor slide deck designed for Kubecon Amsterdam is themed and branded for Kubecon.  We need to create a version of the slide deck that doesn't have Kubecon branding, but instead has general Kubernetes branding.

TBD: should we chop the deck up into segments, or leave it as one big deck?  Rael, who is doing the work, will decide.

/sig contributor-experience
/kind documentation
/area new-contributor-track
/assign @raelga

**Comment by raelga** [comment]
Thanks @jberkus !

**Comment by raelga** [comment]
Amsterdam slide deck themed with vanilla kubernets style:

https://bit.ly/kubeconlesss_NCW2_slides

**Comment by raelga** [comment]
I will gather with @alisondy to start working on the final decks for the next NCW.

**Comment by jberkus** [comment]
Thanks!

Anyway, this is done

/close
