### ISSUE TITLE
reviewer group mentoring kick off

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4901]
this issue is for the kick off to a reviewership group mentoring session targeting sig-node topics lead by @dims as the mentor and me as the coordinator. 

Things we know 
- July 10th and the following Fridays will be slack stand up day; calendar invite sent from contributors@ to everyones calendars 
- Group is full with 5 current members

Things we need
- private slack channel for the 7 of us: #reviewer-cohort2
- a few "speakers" on topics that will be curated by dims and the group 
- more on this planning issue - this is the placeholder :)

**Comment by mrbobbytables** [comment]
I think this was completed. @parispittman can you confirm?

**Comment by nikhita** [comment]
/assign @parispittman @dims 

Is there info from this mentoring group we can add in our contributor docs?

**Comment by mrbobbytables** [comment]
At this stage I think we can close it and move anything else to follow up items, the cohort has been going for some time now :x and is definitely out of kick-off phase.

/close
