### ISSUE TITLE
Add "Kubernetes SIG Storage Shared Calendar" to "K8s Contributor Calendar"

### ISSUE THREAD

**Issue by Rajpratik71** [kubernetes/community#4903]
Request is to merge standalone 

 "Kubernetes SIG Storage Shared Calendar" [available at](https://calendar.google.com/calendar/embed?src=vvvo48r6cprccii1lsava6p2uc%40group.calendar.google.com) 

to "K8s Contributor Calendar" [available at ](https://calendar.google.com/calendar/embed?src=cgnt364vd8s86hr2phapfjc6uk%40group.calendar.google.com)

**Comment by mrbobbytables** [comment]
@saad-ali @xing-yang Can you add the contributor calendar address (`cgnt364vd8s86hr2phapfjc6uk@group.calendar.google.com`) to the meeting invites?

They should then appear on the contributor calendar 👍 

ref: https://github.com/kubernetes/community/blob/master/communication/calendar-guidelines.md#establishing-a-new-meeting
/sig storage

**Comment by xing-yang** [comment]
I have added the contributor calendar address (cgnt364vd8s86hr2phapfjc6uk@group.calendar.google.com) to the Data Protection WG meeting invites.
Looks like only the person who originally sent out the meeting invite can add new invites.
@saad-ali can you do this for the sig-storage bi-weekly meeting and the COSI meeting?
@msau42 can you do this for the CSI implementation meeting?

**Comment by xing-yang** [comment]
Hi @saad-ali,

Can you share the sig-storage calendar with the contributor calendar address (cgnt364vd8s86hr2phapfjc6uk@group.calendar.google.com)?  I think then we don't need to send individual meeting invites to them.  Thanks!

**Comment by mrbobbytables** [comment]
It doesn't work that way unfortunately :( It still needs to be added to individual meetings -- we're hoping to have an alternative solution soonish though.

**Comment by xing-yang** [comment]
Got it.  Thanks @mrbobbytables!

**Comment by xing-yang** [comment]
Hi  @mrbobbytables, so we are all set for this, right?  We don't need to manually add it any more?

**Comment by mrbobbytables** [comment]
@xing-yang You're good! We've automated the process away :)

**Comment by xing-yang** [comment]
Awesome!  Thanks @mrbobbytables!
