### ISSUE TITLE
Mailing list creation in the SIG/wg lifecycle document is missing important information

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#4904]
Placeholder bug until I can get to it, or feel free to submit a fix! 

https://github.com/kubernetes/community/blob/master/sig-wg-lifecycle.md

Doesn't mention that we need new lists to have contributors@kubernetes.io, etc, this is important! We should add a link to people to check out the mailing list guidelines just like we do for zoom, slack, etc. to point to this page:

https://github.com/kubernetes/community/blob/master/communication/mailing-list-guidelines.md

/help-wanted

**Comment by championshuttler** [comment]
@castrojo I would like to contribute to this as my first issue , can you help me getting started
