### ISSUE TITLE
REQUEST: New communication about community group annual reports

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4906]
**What do you want send out?** 
announcement about new community group annual reports; 2020 will be just working groups and 2021 will include all groups (committees, sigs, etc.)

**What’s the intended outcome?**
inform the community this is happening so they can prepare in their groups, ask questions now, and kick off for the working group annual reports
**What is the sponsoring SIG or community group?**
steering

**Is this time-sensitive?** 
yes, need the kdev email out by July 1 but other communications can have later timelines

- [ ] Yes, it is **due by** <$DATE> <$TIME>
- [x] Yes, it **must be sent** July 1, anytime
- [ ] No, but I'd prefer <$DATE> <$TIME>

**Where do you want it to be visible?**

- [ ] Everywhere 🌍
- [x] Email (kubernetes-dev@googlegroups.com)
- [x] Blog post (with help from a [Storyteller] (@divya-mohan0209 is taking this )(https://github.com/kubernetes/community/tree/master/communication/marketing-team#purpose))
- [x] Twitter (via [@k8scontributors](https://twitter.com/k8scontributors))
- [ ] YouTube ([Kubernetes](https://www.youtube.com/channel/UCZ2bu0qutTOM0tHYa_jkIwg))
- [x] Slack (assumes `#kubernetes-dev` unless otherwise mentioned)
- [x] Contributor Calendar event entry (available [here](https://calendar.google.com/calendar/embed?src=cgnt364vd8s86hr2phapfjc6uk%40group.calendar.google.com&ctz=America%2FLos_Angeles))
- [ ] Other (fill this out)

**Where is your first draft available?**
https://hackmd.io/jpZOM7RJRJOTPsxDsHmS_Q

**Lastly, who's the best point of contact?** 
parispittman

**Comment by mbbroberg** [comment]
Seems we missed the deadline on this. Is there room to extend that @parispittman? 

Thinking from comms POV on this one, it's unclear how we go from an unassigned request to a copy edited post to a published one. 

To start testing it out: I'll sign up for copy editing and wrap up by meeting time tomorrow. Coordination after that is still in the works. Let's talk at tomorrow's meeting.

**Comment by mbbroberg** [comment]
Paris mentioned getting this done off GitHub. It's feeding into the lessons learned that will be applied to #4931

**Comment by mbbroberg** [comment]
Confirming this was sent already: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-dev/Uyo0BXB69Qk/PG4WrGuaBQAJ
