### ISSUE TITLE
Replace “master” icon with control plane

### ISSUE THREAD

**Issue by sftim** [kubernetes/community#4913]
https://github.com/kubernetes/community/tree/master/icons#kubernetes-icons-set has an icon representing the kubernetes control plane, labelled “master”

I recommend replacing this with a group symbol (possibly _not_ a heptagon) to represent the set of control plane elements.

The term “master” is problematic because the control plane doesn't have to run on a single primary host with replicas, and also because in some cultures it implies references to slavery.

Relevant to https://github.com/kubernetes/website/pull/20767

/wg naming

**Comment by justaugustus** [comment]
Recommendation in-flight here: https://github.com/kubernetes/community/pull/5243
