### ISSUE TITLE
Remove resync period for disruption controller

### ISSUE THREAD

**Issue by yuanhuaiwang** [kubernetes/community#4916]
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
The disruption controller is resyncing all ssets every 30 seconds, this is not necessary, and make the depth of disruption workqueue longer and can cause delays processing actual updates when large amounts of disruptions [exist.]

Which issue(s) this PR fixes:
Fixes #4916 

Special notes for your reviewer:

Does this PR introduce a user-facing change?
Disruption controllers no longer force a resync every 30 seconds when nothing has changed.

**Comment by nikhita** [comment]
@yuanhuaiwang was this meant to be a PR or an issue report?

If it was an issue report, can you please reopen this against https://github.com/kubernetes/kubernetes? Thanks!

Closing since an issue against k/k would make more sense.
