### ISSUE TITLE
Unable to move past Current Contributor Info (page 3) of Kuberentes Contributor Form if you have not made any contribution.

### ISSUE THREAD

**Issue by valaparthvi** [kubernetes/community#4938]
I was filling out [this form](https://goo.gl/forms/9WllkPFTRB999vcc2) to sign up for The 1:1 Hour but could not move past `Current Contributor Info` (page 3) of the form which asks questions assuming the person signing up has made at least one contribution and wanted information regarding the same, but I just started today and have not made any contributions yet, so I was stuck.

Example question - 
![Screenshot from 2020-07-14 00-37-57](https://user-images.githubusercontent.com/11015077/87343822-186a1780-c56b-11ea-8795-3be7c8c7eaab.png)

I read the mentor-ship program docs and I don't think I came across anything that said you need to make at least one contribution to participate in the program.
Is there any chance to make questions on this page optional or am I missing something here?

**Comment by nikhita** [comment]
/area mentorship-planning

@parispittman do you have context around the form?
