### ISSUE TITLE
NCW2 Session: Community Groups

### ISSUE THREAD

**Issue by alisondy** [kubernetes/community#4945]
We need someone to update, prepare materials for, and record the segment of the New Contributor Workshop that informs students on how the groups within the Kubernetes project work

See the [Section Description] for what this section is to cover, or used to cover.  This will have to be updated.

Slides are in the [Overall NCW Slide Deck](http://bit.ly/kubeconlesss_NCW2_slides), slides 29 to 51. You will be making a copy of these slides, then updating and modifying it to work with your recording.

Here's what the team creating this segment needs to do:

- [ ] Update the slides and materials for timeliness and changes to the community
- [ ] Modify the slides to take into account online presentation
- [ ] Devise new exercises for this segment that work with an online, asynchronous audience
- [ ] Publish slides and exercises to the NCW repository
- [ ] Record a presentation of this section and upload that to the NCW Gdrive folder

## Approximate Length
45m

/sig contributor-experience
/kind documentation
/area new-contributor-track
/help

**Comment by mrbobbytables** [comment]
/assign
I can update and record this section

**Comment by kaslin** [comment]
Paris and I were planning to. We had a meeting last week to discuss how we wanted to update it. You're welcome to join in if you like.

**Comment by mrbobbytables** [comment]
Nah, go for it! :)

/unassign

**Comment by alisondy** [comment]
@kaslin @parispittman are you still interested on working on this? This can be in the form of either a video or a written guide.
