### ISSUE TITLE
NCW2 Session: Pull Request Exercise

### ISSUE THREAD

**Issue by alisondy** [kubernetes/community#4952]
We need someone to update, prepare materials for, and record the segment of the New Contributor Workshop that demonstrates and guides students through submitting a pull request to Kubernetes

it involves walking them through a fake PR on a test repo, aswell as a real pull request

See the [Section Description] for what this section is to cover, or used to cover.  This will have to be updated.

Slides are in the [Overall NCW Slide Deck](http://bit.ly/kubeconlesss_NCW2_slides), slides ___ to ___. You will be making a copy of these slides, then updating and modifying it to work with your recording.

Here's what the team creating this segment needs to do:

- [ ] Update the slides and materials for timeliness and changes to the community
- [ ] Modify the slides to take into account online presentation
- [ ] Devise new exercises for this segment that work with an online, asynchronous audience
- [ ] Publish slides and exercises to the NCW repository
- [ ] Record a presentation of this section and upload that to the NCW Gdrive folder

## Approximate Length

45m

**Comment by savitharaghunathan** [comment]
Happy to help with this exercise
