### ISSUE TITLE
NCW2 Session: Contribute to Docs

### ISSUE THREAD

**Issue by alisondy** [kubernetes/community#4953]
We need someone to update, prepare materials for, and record the segment of the New Contributor Workshop that guides students on submitting a documentation fix to Kubernetes doc repo

See the [Section Description] for what this section is to cover, or used to cover.  This will have to be updated.

Slides are in the [Overall NCW Slide Deck](http://bit.ly/kubeconlesss_NCW2_slides), slides ___ to ___. You will be making a copy of these slides, then updating and modifying it to work with your recording.

Here's what the team creating this segment needs to do:

- [ ] Update the slides and materials for timeliness and changes to the community
- [ ] Modify the slides to take into account online presentation
- [ ] Devise new exercises for this segment that work with an online, asynchronous audience
- [ ] Publish slides and exercises to the NCW repository
- [ ] Record a presentation of this section and upload that to the NCW Gdrive folder

**Comment by savitharaghunathan** [comment]
Interested in helping. Should I assign this to myself @alisondy ?

**Comment by alisondy** [comment]
@savitharaghunathan Yes, you can assign this to yourself! thank you ✨

**Comment by sftim** [comment]
I might be able to help with this. I'd certainly like to!

**Comment by savitharaghunathan** [comment]
Hi @sftim 👋  do you want to team up? It would be awesome :) We can do the presentation together?

**Comment by sftim** [comment]
I'm happy to try @savitharaghunathan - I can't be sure that I can make time, that's my only reason for reluctance.

**Comment by savitharaghunathan** [comment]
@sftim Cool. I will follow up with you in slack.

**Comment by sftim** [comment]
Relevant to https://github.com/kubernetes/website/issues/25043

**Comment by geoffcline** [comment]
I'm working on adding a section to the docs contributor guide with videos/links for new people.

**Comment by sftim** [comment]
> adding a section to the docs contributor guide with videos/links

Consider adding that to https://k8s.dev/ and then having the contribution pages on https://k8s.io/ link to the new content you add into https://k8s.dev/
(this is because it's helpful to have consistent “how do I contribute to component _x_?” documentation, rather than each SIG having its own style).

**Comment by sftim** [comment]
Sorry I haven't made any progress on this so far.
