### ISSUE TITLE
NCW2 Session: Find your first issue

### ISSUE THREAD

**Issue by alisondy** [kubernetes/community#4954]
We need someone to update, prepare materials for, and record the segment of the New Contributor Workshop that informs students on how to find a suitable issue for contributing to Kubernetes for the first time to ( todo: fix this sentence )

See the [Section Description] for what this section is to cover, or used to cover.  This will have to be updated.

Slides are in the [Overall NCW Slide Deck](http://bit.ly/kubeconlesss_NCW2_slides), slides ___ to ___. You will be making a copy of these slides, then updating and modifying it to work with your recording.

Here's what the team creating this segment needs to do:

- [ ] Update the slides and materials for timeliness and changes to the community
- [ ] Modify the slides to take into account online presentation
- [ ] Devise new exercises for this segment that work with an online, asynchronous audience
- [ ] Publish slides and exercises to the NCW repository
- [ ] Record a presentation of this section and upload that to the NCW Gdrive folder

**Comment by Pensu** [comment]
Would love to work on this.
/assign

**Comment by alisondy** [comment]
@Pensu are you still interested on working on this? This can be in the form of either a video or a written guide.

**Comment by Pensu** [comment]
@alisondy Yes, haven't had time to look into it. But would love to give this a shot. Do we have any timelines for this?
