### ISSUE TITLE
NCW2 Session: K/K Walthrough

### ISSUE THREAD

**Issue by alisondy** [kubernetes/community#4955]
We need someone to update, prepare materials for, and record the segment of the New Contributor Workshop that guides students through the k/k repo

part of this will involve creating a quiz centered around finding certain parts of code in the repo.

See the [Section Description] for what this section is to cover, or used to cover.  This will have to be updated.

Slides are in the [Overall NCW Slide Deck](http://bit.ly/kubeconlesss_NCW2_slides), slides ___ to ___. You will be making a copy of these slides, then updating and modifying it to work with your recording.

Here's what the team creating this segment needs to do:

- [ ] Update the slides and materials for timeliness and changes to the community
- [ ] Modify the slides to take into account online presentation
- [ ] Devise new exercises for this segment that work with an online, asynchronous audience
- [ ] Publish slides and exercises to the NCW repository
- [ ] Record a presentation of this section and upload that to the NCW Gdrive folder

**Comment by alisondy** [comment]
note: refer to teh repo tour guide and remind folks that there is many different repos they can contribute too aswell

**Comment by jpmcb** [comment]
II can take this on!

/asign
