### ISSUE TITLE
Kubernetes and Vault Integration

### ISSUE THREAD

**Issue by Wonder007** [kubernetes/community#496]
Any experts out there who can briefly provide pros and cons of Vault vs Kubernetes?

Vault -> Generic storage for anything
Kubernetes -> Specific to Containerization Technology

Thanks in advance

**Comment by kow3ns** [comment]
Vault is a secrets storage system.
Kubernetes is a container orchestration framework. 
You could use Vault to secure your secrets for your Kubernetes workloads [eg](https://github.com/kelseyhightower/vault-controller).
