### ISSUE TITLE
REQUEST: New Slack channel #openservicemesh

### ISSUE THREAD

**Issue by karenhchu** [kubernetes/community#5009]
**GitHub Username:**
karenhchu
michelleN

**Slack Username:**
karenhchu
mnoorali

**What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?**
channel

**Name of Requested Resource:**
#openservicemesh

**Description of Request:**
Need a place to discuss Open Service Mesh (OSM) matters with the community.

**Comment by coderanger** [comment]
Hmm, are you sure this shouldn't go in the CNCF Slack? We are always happy to host ecosystem projects but if you're expecting to grow as a community we would recommend using the CNCF Slack instead.

**Comment by karenhchu** [comment]
Thanks for the feedback. We've taken this request to the CNCF. I will go ahead and close the issue.
