### ISSUE TITLE
Grant sig-scalability leads write/admin access to github.com/kubernetes/perf-tests repo

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/community#5010]
Dear @kubernetes/owners,

We'd like to request write/admin access to github.com/kubernetes/perf-tests repository for sig-scalability leads (https://github.com/orgs/kubernetes/teams/sig-scalability-leads)
The access is needed to cut release branches. We started cutting release branches, mimicking the k/k release model, in order to address issues with accidentally breakages of k/k presubmits (see https://github.com/kubernetes/perf-tests/issues/797) 
Currently, only @wojtek-t has write access, but this is not a sustainable solution going forward.

Thanks,

Matt

**Comment by dims** [comment]
cc @cblecker @nikhita

**Comment by nikhita** [comment]
@mm4tt -- @kubernetes/sig-scalability-leads should have admin access to the perf-tests repo now. :+1: 

Btw just for the future, if you create an issue in https://github.com/kubernetes/org, it'll get seen by the org admins quicker. :)

/close

**Comment by mm4tt** [comment]
Thanks!
