### ISSUE TITLE
Review anti-racist language guidelines from other organizations for adoption by WG Naming

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/community#5021]
Review how other organizations and projects are changing outdated and harmful language. Note any emerging consensus.

Possible sources include:
- [ ] Microsoft (specifically GitHub)
- [ ] Apple
- [ ] IBM
- [ ] Google
- [ ] Amazon

ref: https://www.cnet.com/news/microsofts-github-is-removing-coding-terms-like-master-and-slave/

/wg naming

## Moving forward

After review from WG Naming, we note emerging consensus as documented at the Inclusive Language Initiative, and guidelines from companies whose standards frequently serve as reference points for software development at large:

- https://inclusivenaming.org/
- https://developers.google.com/style/inclusive-documentation
- https://docs.microsoft.com/en-us/style-guide/bias-free-communication

**Comment by dims** [comment]
Chris Wright from Red Hat's blog post - https://twitter.com/kernelcdub/status/1277954122172465152?s=20

**Comment by SueKocher** [comment]
My company (SAS) is dealing with these issues too, as best we can. Could you tell me if this SIG has any meetings planned, an agenda, or a plan to propose something specific to GitHub? (because i think I've seen similar discussions for GitHub terminology that have been going on for a while...)

Thanks for any info!

**Comment by lguinn** [comment]
There was a similar discussion a few years ago that ended with some negative responses, claiming that this is not important. Let's push through this time to a better place. An issue does not need to affect everyone to be important and worth the long-term effort to resolve it.

**Comment by justaugustus** [comment]
/assign @zacharysarah 
ref: https://inclusivenaming.org/

**Comment by zacharysarah** [comment]
I edited the description with WG Naming's review results. The review function of this issue being complete, I'm closing this issue.

/close
