### ISSUE TITLE
Create a network policy user group directory

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/community#5024]
I would like to create folder under community/ called "network-policy-ug", where we could have. a permanent user group home, which would initially start as a home for some artifacts produced by the Kubernetes sig-network WG for network-policies.  

*Motivation*

We have a current network policy working group associated with sig-network, which I believe will be able to complete most of its core purpose within a few weeks.    At that point if we continue being a working group, I think our purpose will be quite narrow and some of the use cases, we had, such as

- create indirection layers between policies
- possibly making a policyctl or similar tool for managing network policies on the client side
- creating a gateway service which funneled all cross namespace traffic
- network policy templates and scripts to reproduce common scenarios in the 20+ user stories which were originally suggested.

might be lost.

There are a lot of ideas that came out of that group, and we've had meetings with 20+ people from 10 or more companies over the past 4 months.

I think once our initial first phase of effort is done, putting some artifacts into this repo and becoming a user-group for asynchronous collection of ideas, prototypes, and so on might be idea.

**Comment by nikhita** [comment]
@jayunit100 would need to follow the process here - https://github.com/kubernetes/community/blob/master/sig-wg-lifecycle.md#prerequisites-for-a-ug :)

/sig network
/committee steering

**Comment by jayunit100** [comment]
I think per conv w Bobby .... it's a no go as wgs and ugs and sps don't own code.  Will use a personal github repo for now .

**Comment by mrbobbytables** [comment]
subprojects can own code (as they're owned by a sig) - Would just need a place or repo that sig-network signs off on to put it all 👍

**Comment by jayunit100** [comment]
ah, ok, ill leave this open for now then.  Ive put a feeler out on the mailing list as to *what* our deliverable will be for the policy stuff...  once I get some feedback there, then will know what to do.

**Comment by jayunit100** [comment]
im going to close this, we'll use our own personal repos for now

**Comment by jayunit100** [comment]
@rikatz :)

**Comment by rikatz** [comment]
@mrbobbytables @nikhita we're looking to have some kubernetes-sigs/netpol-evolution repo, working with issues, user stories as markdown files and future implementations / specs there as well :)

Is that possible? Do we need to open an specific issue?

Thank you very much :)

**Comment by mrbobbytables** [comment]
Just need to open an [issue in kubernetes/org](https://github.com/kubernetes/org/issues/new/choose) for the repo request :) It will need sign off from the sig leads. and we can move forward with creating it 👍

**Comment by nikhita** [comment]
@jayunit100 do you think this issue is good to be closed?

/remove-committee steering

**Comment by rikatz** [comment]
@jayunit100 Let's discuss about this also in the next netpol subproject meeting, (or even in this week sig-network meeting) so we can gather the sponsorship to move forward with the project, and ask for the whole package of repo, slack channel, etc :)

cc @andrewsykim

**Comment by jayunit100** [comment]
I think folks still wanted to add it , yeah we'll bring it up tomorrow I guess Ricardo?

**Comment by rikatz** [comment]
@nikhita I'll close this issue in favor of https://github.com/kubernetes/org/issues/2239 :)

Thank you!!

/close
