### ISSUE TITLE
Pod IP in hostNetwork mode does not update when node IP changes

### ISSUE THREAD

**Issue by pupapaik** [kubernetes/community#5025]
When PODs are running in hostNetworking mode they use Kubernetes node IP address. I hit issue when actual node IP changes, but some of the pods have never reflected the change. See screenshot bellow:

![image](https://user-images.githubusercontent.com/7746321/89935425-73e30000-dc12-11ea-9baf-05337c3c05e8.png)

The workaround is to restart kubelet. It seems like there is condition which does not update pod IP in hostNetworking mode during regular generateAPIPodStatus, if Pod IP is already present https://github.com/volterraedge/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go#L1531

I tried to remove `&& s.PodIP == ""` and it helped. I'm going to submit PR with fix.

**Comment by dims** [comment]
please open in https://github.com/kubernetes/kubernetes

/close
