### ISSUE TITLE
REQUEST: New Slack channel: sig-docs-localization

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/community#5026]
**GitHub Username:**
@bradtopol 
@jimangel 

**Slack Username:**
@bradtopol 
@jimangel 

**What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?**

Channel

**Name of Requested Resource:**

sig-docs-localizations

**Description of Request:**

Language localizations for Kubernetes docs need an easy way to confer with each other, provide mutual support, and provide a better contributor experience. Some localizations have a great experience with great tooling and project management; others struggle with membership, tooling, and progress.

A Slack channel may help localizations confer with each other in an easily signposted place.

/sig docs
cc @kubernetes/website-maintainers

**Comment by raelga** [comment]
Thanks for the initiative!

**Comment by sftim** [comment]
LGTM!

**Comment by coderanger** [comment]
The `sig-docs-` prefix in Slack is delegated to the SIG-Docs team, so y'all can do this directly. Add your channel to https://github.com/kubernetes/community/blob/master/communication/slack-config/sig-docs/docs-channels.yaml and you can approve it yourself :)
