### ISSUE TITLE
Retire WG Machine Learning

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#5034]
/wg machine-learning
/comittee steering
/assign @castrojo @mrbobbytables 
Since we discussed on slack

/assign @k82cn @vishh @kow3ns 
Listed as WG organizers

ref: https://groups.google.com/forum/#!topic/kubernetes-dev/WBYJmIIaY4c

per: https://github.com/kubernetes/community/blob/master/sig-wg-lifecycle.md#steps

I'm happy to help however I can

**Comment by castrojo** [comment]
### Steps:
- [ ] Send an email to kubernetes-dev@googlegroups.com and community@kubernetes.io alerting the community of your intentions to disband or merge. [example]
- This kicks off the process for Contributor Experience’s community managers who will reach out and set an issue against `kubernetes/community` with exact next steps covered below. We can help walk through this when you get there. Most of this is covered in the same creation communication docs as above.
- [ ] Archive the member and lead/chair mailing lists/[GoogleGroups]
- [ ] Check the [slack-guidelines.md] for latest process on archiving the slack channel
- [ ] Deactivate the zoom license
- [ ] Delete your shared SIG/WG/UG calendar
- [ ] Ensure that the [youtube-guidelines.md] links are removed and you've uploaded all SIG/WG/UG meetings to date
- [ ] Move the existing SIG directory into the archive in `kubernetes/community`
- [ ] GitHub archiving/removing/other transactions:
   - [ ] Move all appropriate github repositories to an appropriate archive or a repo outside of the Kubernetes org
   - [ ] Each subproject a SIG owns must transfer ownership to a new SIG, outside the project, or be retired
   - [ ] File an issue with kubernetes/org if there are multiple repos
   - [ ] Retire or transfer any test-infra jobs or testgrid dashboards, if applicable, owned by the SIG. Work with SIG-Testing on this.
   - [ ] Migrate/Remove/Deprecate any SIG/WG labels in labels.yaml
   - [ ] Remove or rename any GitHub teams that refer to the SIG
   - [ ] Update sigs.yaml to remove or rename

**Comment by castrojo** [comment]
I don't have access to the Google Group to archive it, one of the leads will have to do that.

**Comment by mrbobbytables** [comment]
@k82cn do you happen to have access to the calendar or group?

**Comment by k82cn** [comment]
> @k82cn do you happen to have access to the calendar or group?

I will cancel the calendar, but I can not access the gorup :(

**Comment by mrbobbytables** [comment]
ah >_<
@vishh can you archive the group?

**Comment by mrbobbytables** [comment]
I think at this point our best bet is to send a mail to the list and then call it done.

**Comment by vishh** [comment]
Not sure what exactly archiving a mailing list entails, but I went ahead and froze the mailing list with all the knobs available via google groups. All old email threads are still accessible, only group owners can post new messages and no new members can join unless invited by group owners. Is that it?

**Comment by mrbobbytables** [comment]
@vishh That's it :) As long as no one else can post. If you can, do one final post stating that the group is retired and that should call it done.

**Comment by mrbobbytables** [comment]
All items that can be completed are done. Going to go ahead and close this out.

/close
