### ISSUE TITLE
REQUEST: New communication about the Slack reporter tool

### ISSUE THREAD

**Issue by munnerz** [kubernetes/community#5040]
**What do you want send out?** 

A message to inform/remind users of Slack that the Slack reporter tool exists to report CoC violations to the Slack administration team and CoCC, to ensure everyone is aware of it. (in a non-boring way! 😄)

**What’s the intended outcome?**

People reporting messages and code of conduct violations on Slack, and ensuring it's a well known resource.

**What is the sponsoring SIG or community group?**

#sig-contribex maybe? Slack administrators community group.

**Is this time-sensitive?** 

- [x] No

**Where do you want it to be visible?**

- [ ] Everywhere 🌍
- [x] Email (kubernetes-dev@googlegroups.com)
- [ ] Blog post (with help from a [Storyteller](https://github.com/kubernetes/community/tree/master/communication/marketing-team#purpose))
- [x] Twitter (via [@k8scontributors](https://twitter.com/k8scontributors))
- [ ] YouTube ([Kubernetes](https://www.youtube.com/channel/UCZ2bu0qutTOM0tHYa_jkIwg))
- [x] Slack (assumes `#kubernetes-dev` unless otherwise mentioned)
- [ ] Contributor Calendar event entry (available [here](https://calendar.google.com/calendar/embed?src=calendar%40kubernetes.io))
- [ ] Other (fill this out)

(not too sure on the above, and if kubernetes-dev mailing list is worthwhile posting to - would be good to get others opinions!)

**Where is your first draft available?**

Did you know the Kubernetes Slack community has a "Report message" feature to allow anyone to report code of conduct violations (optionally anonymously too)?

![Screenshot 2020-08-17 at 15 21 30](https://user-images.githubusercontent.com/203583/90413436-54caef00-e0a6-11ea-80d9-6c0f8ebd6446.png)

**Lastly, who's the best point of contact?** 

Myself, or the Slack admin team (#slack-admins on k8s slack)

/cc @parispittman

**Comment by mbbroberg** [comment]
Thanks for filling this out @munnerz! We'll get working on it. cc @kaslin

**Comment by mbbroberg** [comment]
Hey @munnerz -- we've sent a few tweets related to this (sorry for not updating along the way. We're working on a process to shoot this out into k-dev Slack (cc @rajula96reddy to send that). Lastly, would you be interested in sharing a first draft of the blog post? We're happy to help edit and shepherd from there. 

Thanks!

**Comment by mbbroberg** [comment]
Given that we've tweeted a few times and don't have any copy for a blog post, we'll close this one for now. @munnerz, happy to help with a blog if you get to a first draft! 

/close
