### ISSUE TITLE
Adjust German style guide for inclusive speech & check translated docs

### ISSUE THREAD

**Issue by mkorbi** [kubernetes/community#5043]
Not sure if it is best placed here or at kubernetes/website.
## Issue 1
The German language is in most cases ether using a masculine or feminine ending of a word. 

Small example:
- EN: "As contributor you have to follow the code of conduct."
- DE: "Als Beitragend**er**/**e** musst du dem Verhaltenscodex folgen."
As shown above, in DE we can't express a role, person, job etc. in a neutral way.

ToDos:
- [ ] Collect potential terminology (by newspaper, magazines, blogs)
- [ ] Discuss and pick with the German i18n team a terminology
- [ ] Extend Germany Style Guide
- [ ] Scan German i18n and adjust the wording

I don't expect that we use person-oriented sentences in too many places and is most likely in the community/contribution area focused. Even more, it is important to be inclusive.

## Issue 2
Check for master/slave terminology and align with the list of harmful words. 
Potentially we have to do this for Germany too and write a list of harmful words.

ToDos:
- [ ] Align with wg-nameing on harmful words
- [ ] Scan German i18n for harmful wording
- [ ] Prepare a writeup for i18n harmful words and add the reference to the style guide

cc'ed Jim as we should keep this topic in mind for https://github.com/kubernetes/website/issues/22960
/cc @jimangel @rlenferink @bene2k1 
/wg naming

**Comment by celestehorgan** [comment]
Hi all,

per [the recommendation](https://github.com/kubernetes/community/blob/master/wg-naming/recommendations/master-control-plane.md), please feel free to update to use "control plane" when you are ready.
