### ISSUE TITLE
#SIG-Architecture  Support for RISCV

### ISSUE THREAD

**Issue by pramchan** [kubernetes/community#5044]
Since was looking at CNI and found there is no support for RISCV , wanted the architecture SIG to look at possibility of adding support for RISCV. Who will be interetsed in it? Possibly currently Academic like UC Berkely & IITM.
Some reference links are here for review:
https://en.wikipedia.org/wiki/RISC-V
https://en.wikipedia.org/wiki/Berkeley_RISC
https://gitlab.com/shaktiproject/software/shakti-sdk
May be lets check with Davanum Srinivas (@dims) if he would be able to comment on this as member of sig-architecture.
/sig-architecture

**Comment by pramchan** [comment]
I created one for CNI - https://github.com/containernetworking/cni/issues/784

**Comment by dims** [comment]
@pramchan https://github.com/kubernetes/community/pull/5014
