### ISSUE TITLE
Most guides are not detailed enough

### ISSUE THREAD

**Issue by erikbgithub** [kubernetes/community#505]
For instance this one: https://github.com/kubernetes/community/blob/master/contributors/devel/local-cluster/docker.md

It basically says "run hyperkube with these params" and even after an update it's mostly "don't do this any more, use minikube instead" while the minikube again just says "run minikube with these params".

This kind of article doesn't do any good, because people run into problems. And when they do that and are paid to continue anyways, they want to understand how the stuff works underneath. We need such guides to explain what happens underneath as well to replicate the behaviour manually or see at a failing step in the helper tool how to debug it.

**Comment by calvn** [comment]
Another case is on the [Getting started locally](https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md) guide, where it mentions running the setup with minikube if not on Linux, but does not actually provide any steps or configuration on how things should be set up for that scenario.

**Comment by nikhita** [comment]
I guess this is still relevant.

/remove-lifecycle rotten

@castrojo Not sure if this is being tracked elsewhere (for the contributor guide). If it is, please feel free to close it. :)

**Comment by erikbgithub** [comment]
I also think it's still relevant, but I've moved on to Openshift, so I'm not really in the know anymore and will unsubscribe. Thanks for continue to working on it, though. Documentation is always one of the hardest parts.

**Comment by mrbobbytables** [comment]
I think at this point with our contributor guide we should be good. We have a planned rework for at least development.md that is being tracked here:
https://github.com/kubernetes/community/issues/1644

With that I'm going to go ahead and close this out for now 👍 
If you think it should be left open, please feel free to reply here or poke me in slack.

Thanks!
/close
