### ISSUE TITLE
Contributor site - couple of broken references

### ISSUE THREAD

**Issue by spzala** [kubernetes/community#5051]
The following references are broken:

Under `Making your First Contribution` page:
See **Open A Pull Request** below. 
Please see **Contributing** below for the workflow

Under `Contributing to Kubernetes` page:
Beginner focused information can be found below in **Open a Pull Request**

**Comment by spzala** [comment]
/cc @mrbobbytables @castrojo 
I am not sure if we are compiling all issues around Contributor site and fixing, but can help with the fix if needed. Thanks!

**Comment by mrbobbytables** [comment]
I did a 404 scan and already have PRs in flight for fixing 👍

**Comment by spzala** [comment]
Awesome! Thanks @mrbobbytables

**Comment by mrbobbytables** [comment]
All PRs with link fixes have been merged 👍 
going to go ahead and close.
/close
