### ISSUE TITLE
Contributor site - inconsistency in the doc at few places

### ISSUE THREAD

**Issue by spzala** [kubernetes/community#5052]
The site has inconsistency in completing sentences with or w/o period in few pages. We should do clean sweep across all pages and try to make it consistent for a better user experience, few examples below: 
Under `Getting Started` page:
See the sentences under **Sign the CLA** and **Setting up your development environment** vs **Code of Conduct** 
See the sentences under **Events** and **Mentorship** vs **Meetups** 
Under `Owners file` page:
See the two paragraph in **Overview**
Under `Contributor Cheatsheet` page:
See the **Gubernator Dashboard** and **Prow** vs **Tide** and **Bot commands**
Under `Coding Convention`page: 
See how various bullets in **Testing conventions**
etc. 

/sig contributor-experience

**Comment by mrbobbytables** [comment]
This should be resolved with the contributor guide clean up that @celanthe is doing :D

/assign @celanthe
