### ISSUE TITLE
Contributor site - Update site link in twitter profile

### ISSUE THREAD

**Issue by gkarthiks** [kubernetes/community#5054]
The contributor site is up and running at https://k8s.dev

The Twitter profile k8scontributors link is still forwarding to GH.

![image](https://user-images.githubusercontent.com/30545166/90712881-9daabf80-e2c1-11ea-95d6-845e378ede70.png)

/sig contributor-experience

/cc @mrbobbytables

**Comment by parispittman** [comment]
updated

thanks for the catch!

/close
