### ISSUE TITLE
Periodic tweets and emails about SIGs

### ISSUE THREAD

**Issue by sureshpalemoni** [kubernetes/community#5061]
**What do you want send out?** 
Twitter handle should tweet or periodical email to distribution list about the existing SIG one at a time.

**What’s the intended outcome?**
For example we tweet/email periodically about  /sig-apps/CONTRIBUTING.md
 - If email - short one line what this sig about(tweet we can have this if we post some template image)
 - References to active repo of this SIG
 - contacts of active sig leads who can mentor new contibutors
 - Next upcoming meeting. (Contributors gets lost in either emails or tweets). So we remind/inform them using these channels.

**What is the sponsoring SIG or community group?**
#sig-contribex

**Is this time-sensitive?** 
- On a periodic basis

**Where do you want it to be visible?**

- [ ] Everywhere 🌍
- [x] Email (kubernetes-dev@googlegroups.com)
- [ ] Blog post (with help from a [Storyteller](https://github.com/kubernetes/community/tree/master/communication/marketing-team#purpose))
- [x] Twitter (via [@k8scontributors](https://twitter.com/k8scontributors))
- [ ] YouTube ([Kubernetes](https://www.youtube.com/channel/UCZ2bu0qutTOM0tHYa_jkIwg))
- [x] Slack (assumes `#kubernetes-dev` unless otherwise mentioned)
- [ ] Contributor Calendar event entry (available [here](https://calendar.google.com/calendar/embed?src=calendar%40kubernetes.io))
- [ ] Other (fill this out)

**Where is your first draft available?**
This is basic idea: 

Are you interested in contributing to Kuberenetes Networking?
 - SIG: #sig-network
 - Next Contrinutor meeting on SIG-Network
       - Aug 25th (Example) - Link to zoom meeting
 - Mentor contacts(who can be contacted via twitter,slack or email)
______________________________________________________________________
Or, SIG of the week or SIG of the day also works.

**Lastly, who's the best point of contact?** 
Myself or @mbbroberg

**Comment by sureshpalemoni** [comment]
https://guides.github.com/features/mastering-markdown/
<img width="581" alt="Screen Shot 2020-08-30 at 2 05 24 PM" src="https://user-images.githubusercontent.com/16357895/91656498-2d264e80-eaca-11ea-8631-6942a062a713.png">

@mbbroberg  - Example Format

**Comment by mbbroberg** [comment]
LOVE this! The one thought that comes to mind is that we could talk to reader a little more. 

```
Meet our SIG of the week: SIG-DOCS! 

You can start contributing by joining: 
- Slack link
- Group link
- The next meeting on X 

On-going agenda: 
- A
- B

#sigoftheweek
```

**Comment by mbbroberg** [comment]
This is coming along! Notes from working with the team: 

- Do NOT link to Zoom 
- Do link to the k8s.dev/calendar
