### ISSUE TITLE
Proposal: prompt contributors to join the org

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#5074]
In the Elections committee, we were surprised to find that there were 302 folks who made 50 contributions (of some kind) to Kubernetes in 2019-2020 but were not org members.  The reason for this is likely that they don't know about org membership, or don't think it applies to them.

After a discussion, we thought it would be a good idea to prompt every contributor to become an org member on their third PR.  That is, if they open a new PR after having 2 accepted, and they are not already in members.md, they should get a message (by whatever means) suggesting that it's time for them to join the Org.

Questions: 

- does this seem like a good idea?
- is it technically feasible?
- do we want to check anything other than PRs?

/sig contributor-experience
/area contributor-management

cc @jdumars @mrbobbytables @cblecker

**Comment by spiffxp** [comment]
See https://github.com/kubernetes/test-infra/issues/13371 for prior discussion about this

**Comment by jberkus** [comment]
closing in favor of the older issue on test-infra.  Please move any further discussion there.
