### ISSUE TITLE
Allow blocking unchunked requests to list pods

### ISSUE THREAD

**Issue by grosser** [kubernetes/community#5085]
We have lots of pods and requests to get all pods use lots of memory on the api-server ~150m atm.
It would be nice if we could block any client from doing a request without chunking (limit to 1k items per response) to improve api server availability.

/sig api-machinery

**Comment by mrbobbytables** [comment]
@grosser This repo is the general management point of the contributor community, things like that are not likely to get a response here =/ 

Can you open your issue in https://github.com/kubernetes/kubernetes ?

**Comment by grosser** [comment]
thx ... I got redirected here from opening an issue somehow ... worked now :D
