### ISSUE TITLE
Change how we intro new people in meetings

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#5090]
In SIG-Contribex meetings, and others, we do do this thing where we ask new people to introduce themselves, and only the new people.

This really puts new people on the spot, and is super-intimidating to introverts.  More importantly, it puts the new people in the position where everyone now knows them, but they don't know anybody.

Instead, we should either intro *everyone* (if a small meeting), or have 2-3 "old people" intro themselves before the new people do.  This would put the new people on a more even footing, and be less hostile to introverts.

/sig contributor-experience

**Comment by castrojo** [comment]
/assign

Agree 100%, I can easily fix this in the template.

**Comment by castrojo** [comment]
/close
This is now implemented.
