### ISSUE TITLE
Create app for holding Steering elections using only github auth

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#5096]
There are two extremely labor intensive and data-error-prone portions of the current [Steering Elections process](https://github.com/kubernetes/steering/blob/master/elections.md):

1. pulling the list of eligible voters
2. getting everyone's ballots to them by email

The latter is by far the worst, because it takes 2 days of solid time for the elections committee, and requires technical skills on their part.  It is also frustrating for members who do not receive their ballots due to spam filters and other problems.

That said, we like the elections logic of CIVS, our current tool.  We just want it to work differently.  We would also prefer a tool written in a programming language that expertise exists for within test-infra group.

As such, we would like to mentor an intern (either via Community Bridge, or Outreachy) to develop a web application that would allow voting, with authentication to be handled via Github Oauth.  This would remove email as the failure link in the chain to voting.  The application would have the following requirements:

- support configurable external Oauth sources (with Github being the requirement/default)
- support multiple elections, even concurrently, with each election to have a start and end date, and its own list of valid voters and candidates
- follow all CIVS voting logic that we use (randomization of candidates, Concordet/Schultze preference voting) 
- validate voters against an administrator-supplied list
- create list of candidates from an administrator-supplied list
- allow voters to check their own vote via login
- affiliate votes with obfuscated/encrypted logins to prevent casual administrator examination of individual votes
- supply on-demand statistics for the administrator (number of voters/votes cast)
- output a final preference ranking of candidates when the election is "closed"
- be written in Go, Python, or Javascript (due to community's ability to support) (somewhat negotiable)

We anticipate this application would be desired by many OSS projects once completed.  As such, we would plan to suggest it to the CNCF/LF as a service once the app is written, and distribute it as an independant OSS project.

Mentors for this project would be Jaice, Josh, and Marky

/sig contributor-experience
/committee steering
cc @jdumars @idvoretskyi @markyjackson-taulia @nikhita @parispittman

**Comment by jdumars** [comment]
I strongly support this effort.

**Comment by markyjackson-taulia** [comment]
+1 to @jdumars this will help a lot and I would love to help mentor this along with @jberkus and @jdumars

**Comment by Oghenebrume50** [comment]
Hi @jberkus @jdumars @markyjackson-taulia  I would love to take this up, I am comfortable with JavaScript and Ruby, plus I am currently learning Go, please what is the proper communication medium to follow up with this?

**Comment by kunal-kushwaha** [comment]
Looking forward to contributing to it for the upcoming community bridge program! 🚀

**Comment by jberkus** [comment]
@Oghenebrume50 @kunal-kushwaha Projects will be accepted for Community Bridge on Sept 21st.  After that we will announce the project and tell you were to apply.

**Comment by Oghenebrume50** [comment]
Alright noted, looking forward to it :slightly_smiling_face:

**Comment by ehashman** [comment]
+1000

This is what I saw after casting my ballot:

![Screenshot at 2020-09-17 15-19-42](https://user-images.githubusercontent.com/4706131/93534656-58969f00-f8fa-11ea-83b6-968558949a30.png)



Seeing that last poll does not surprise me, as the platform lacks mechanisms to address abuse: a particular individual has been using CIVS to harass the Debian project for months.

**Comment by jberkus** [comment]
@Oghenebrume50 @kunal-kushwaha  please apply for the Community Bridge program here.  We've been selected!

https://www.cncf.io/blog/2020/09/21/calling-all-mentees-cncf-communitybridge-projects-for-the-fall-2020-program/

**Comment by jberkus** [comment]
@SergeyKanzhelev we're going to be refining the spec for this application; I'll ping you for your input.

**Comment by jberkus** [comment]
@Oghenebrume50 @kunal-kushwaha let me apologize, we are delayed in accepting applications because of problems with the CommunityBridge platform.

**Comment by UdokaVrede** [comment]
That's understandable, I'll patiently wait

**Comment by jberkus** [comment]
This effort has been re-consituted as a "new" project under CommunityBridge.  Applications will be open for the next 10 days, and the timeline is extended.  [Please apply here](https://people.communitybridge.org/project/953e5f12-460b-4bf1-80b3-5171c2044462).

Yes, this will mean re-submitting materials, but you can copy & paste from your previous application.

@Oghenebrume50 @kunal-kushwaha

**Comment by Oghenebrume50** [comment]
Hi @jberkus the google-docs file under the "Full-specification" does not open, I think there is a mistake in the URL

**Comment by markyjackson-taulia** [comment]
@Oghenebrume50 I just tried it using copy and paste and it works. Try [this](https://docs.google.com/document/d/e/2PACX-1vQ4Z3jOpIsGZHaBy9Xa6me6IyL_rj-JZgAl-xRO-M2KacWhcRexcV3mILjwclsc9QI4ghRfic2ESFtB/pub)

**Comment by Oghenebrume50** [comment]
> @Oghenebrume50 I just tried it using copy and paste and it works. Try [this](https://docs.google.com/document/d/e/2PACX-1vQ4Z3jOpIsGZHaBy9Xa6me6IyL_rj-JZgAl-xRO-M2KacWhcRexcV3mILjwclsc9QI4ghRfic2ESFtB/pub)

@markyjackson-taulia  thank you, the link here works, I don't know why that did not work.

**Comment by shivam-51** [comment]
@jberkus @markyjackson-taulia  Hi, I would like to work on this project through Community Bridge. I hope its not too late.

**Comment by markyjackson-taulia** [comment]
> @jberkus @markyjackson-taulia Hi, I would like to work on this project through Community Bridge. I hope its not too late.

@shivam-51 
Hello. No, it is not too late. You can review the specs and apply here: https://people.communitybridge.org/project/953e5f12-460b-4bf1-80b3-5171c2044462

**Comment by shivam-51** [comment]
@markyjackson-taulia Thank You

**Comment by DiptoChakrabarty** [comment]
Hey I am interested in this , can I know the exact duration of this program . Thanks.

**Comment by SergeyKanzhelev** [comment]
> Hey I am interested in this , can I know the exact duration of this program . Thanks.

https://github.com/cncf/mentoring/tree/master/communitybridge/2020/q3-q4#timeline

**Comment by jberkus** [comment]
It's shifted my more than a week; we're pretty sure this project will take extra time.  See spec, linked above.

**Comment by rahul799** [comment]
Hello mentors,
I have applied for Community-bridge. Just curious to know that when the results will be declared?

**Comment by jberkus** [comment]
At the end of this week.

**Comment by jberkus** [comment]
@Oghenebrume50 hey, reminder: you only have 24 hours left to complete your CommunityBridge application for this project, if you are going to.

**Comment by Abhishek-Dev09** [comment]
@jberkus Is am late or CommunityBridge still accepting the application for this project ?

**Comment by jberkus** [comment]
@Abhishek-Dev09 yes, you were too late.  Sorry.

**Comment by its-crypted** [comment]
@jberkus when the results are going to be released?

**Comment by jberkus** [comment]
We have selected @kalkayan as the mentee for this project.  Thanks everyone for your interest!  There may be a follow-up project in the spring; we'll see.

**Comment by nikhita** [comment]
Related - https://github.com/kubernetes/community/issues/4586. We will also be using this app for SIG elections whenever needed.

**Comment by SergeyKanzhelev** [comment]
should this be closed as there is https://elekto.io/ now?

**Comment by mrbobbytables** [comment]
I believe so, @jberkus are there any other follow up items at this time?

**Comment by nikhita** [comment]
@jberkus :wave: do you think this can be closed?

**Comment by jberkus** [comment]
yeah, the app is created, I still need to integrate it into Kubernetes infra, but that should be a seperate issue.

/close
