### ISSUE TITLE
WG Security Audit active?

### ISSUE THREAD

**Issue by tpepper** [kubernetes/community#5120]
[sig-list.md](https://github.com/kubernetes/community/blob/master/sig-list.md) points to a WG Security Audit meeting log google doc which only includes minutes from 2018/2019.  Is the WG still active?

**Comment by parispittman** [comment]
@tpepper they are in a wind down process now and folding work into the new sig-security

**Comment by Jerry061-eng** [comment]
[Gta 5 apk](https://thegta5android.com/)

**Comment by mrbobbytables** [comment]
ref: https://github.com/kubernetes/community/pull/4976

**Comment by nikhita** [comment]
wg-security-audit has now been folded into sig-security - https://github.com/kubernetes/community/pull/4976. Closing.

/close
