### ISSUE TITLE
tweet every time we go live?

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#5156]
can we set up an automated method that we can tweet from the k8scontributors account every time we are live on the community YouTube?

**Comment by mbbroberg** [comment]
@chris-short is looking into this since he has permission for each.

**Comment by mbbroberg** [comment]
Chris found there is no native mechanism that will tweet when you go live. There are 3rd party tools (streamlabs) if the team wants to add another tool. Alternatively, we stick with the scheduled tweets, though this isn't automated.

**Comment by chris-short** [comment]
I could not find a native way to do this in YouTube.

I started a discussion in #sig-contribex Slack tagging both groups. Will continue updating as I get info here.

**Comment by mbbroberg** [comment]
Note from our team meeting today: we may find some options in the team Zapier mentioned in  #5201.
