### ISSUE TITLE
Contributor Survey Images are sporadically loading, should be tracked in repo

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#5162]
When viewing the [contributor survey reports](https://github.com/kubernetes/community/tree/master/sig-contributor-experience/surveys/2019), the images don't consistently load. They are being externally stored in a gdrive directory. They should be tracked in repo alongside the markdown docs themselves.

/area community-management
/sig contributor-experience
/milestone v1.20
/help
/good-first-issue

**Comment by sourabhsingh282** [comment]
I would like to work on this

**Comment by mrbobbytables** [comment]
@sourabhsingh282 - I think @evalsocket is working on it - if they're not interested you're welcome to though :)
