### ISSUE TITLE
get a slack invitation for #sig-api-machinery

### ISSUE THREAD

**Issue by robstoll** [kubernetes/community#5167]
I have basically a feature request: https://github.com/kubernetes/enhancements/issues/1917
As it seems, I need first a sponsoring SIG and as far as I understood API changes (even if I eventually want it to happen for kubectl) have to be addressed by this SIG. Therefore, I would like to talk about the idea somehow to get the sponsoring.

Can someone help out?

**Comment by mrbobbytables** [comment]
The slack is open, you can get an invite by going to https://slack.k8s.io
I'd also suggest joining their mailing list if you haven't already: https://groups.google.com/forum/#!forum/kubernetes-sig-api-machinery

**Comment by coderanger** [comment]
As mentioned, all are welcome :) You can join using the link above and then in the Channels list click the `+` icon and search for `#sig-api-machinery`.

/close
