### ISSUE TITLE
Update mailing list guidelines to include subprojects

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#5169]
The current mailing list guidelines only cover top level community groups. There are instances of subprojects that are either large enough (kubebuilder) or are scoped in a way that would benefit from an independent list (kubernetes-keps).

/sig contributor-experience
/area community-management
/milestone v1.20

**Comment by thejoycekung** [comment]
Hey, I'd like to try helping out with this! The current guidelines are under `communication/mailing-list-guidelines.md`, right? 

Some things I can spot right now:
- We should mention subprojects either in the first sentence or right after
- Should instances of `SIG/WG` be replaced with `SIG/WG/subproject` instead? 
- Do the mailing list guidelines for creation (e.g. needs a leads list and a members list, needs email of form `kubernetes-<sig>-foo`, privacy settings, etc.) apply the same to subprojects?

Also, I think it would be really useful to add a table of contents to this file (but that's just me!).

/assign thejoycekung

**Comment by mrbobbytables** [comment]
> * We should mention subprojects either in the first sentence or right after

SGTM!

> * Should instances of `SIG/WG` be replaced with `SIG/WG/subproject` instead?

Yup!

> * Do the mailing list guidelines for creation (e.g. needs a leads list and a members list, needs email of form `kubernetes-<sig>-foo`, privacy settings, etc.) apply the same to subprojects?

Yes, they should follow the same guidelines. The two big differences for subprojects is they should be titled as `kubernetes-<subproject>`, but the rest of the privacy settings would be the same.

They should also be added to the subproject's contact information in [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml), similar to how its done for the server-sdk subproject: https://github.com/kubernetes/community/blob/master/sigs.yaml#L120-L121 

That will ensure they're discoverable 👍
