### ISSUE TITLE
[Tracking Issue] GitHub Recognition Beta Test

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#5175]
GitHub is working on a beta feature that allows members to recognize, thank or give kudos to other members. :tada:

This issue will be used for discussing rollout and feedback.

### How

It is a configurable `/command` that will then appear on a user's hover card, in addition to being able to see all kudos given for a specific repo. In the future, these are planned to be aggregated up to the org level in addition to potentially displaying them on a user's profile. An example kudos:
```
/shoutout to @herpderp for providing an awesome review!
```

### Preventing Abuse

For the start of this beta, who can (members) and how many kudos can be given is tightly controlled. Anyone with write access to a repo may edit or remove a kudos. GitHub does plan to put in place many more controls before potentially going live.

---
/sig contributor-experience
/area github-management
/milestone v1.20

**Comment by nikhita** [comment]
:shipit: 

+1 to use `/shoutout` as the command.

**Comment by mrbobbytables** [comment]
shoutout it is 🎉 

Right now GitHub can only enable on specific repos. To start I'm thinking:
- kubernetes/kubernetes
- kubernetes/test-infra
- kubernetes/community


We can also reach out to other leads and subproject owners to see if its something they'd like to enable on their own repos.

**Comment by jimangel** [comment]
SIG Docs (k/website) would be interested in helping pilot this!

/cc @kbarnard10 @irvifa @zacharysarah

**Comment by mrbobbytables** [comment]
Okay, we'll move forward with those 4 to start 👍

**Comment by mrbobbytables** [comment]
GitHub has put a pause on the beta for now and plan to revisit it in 2021. As the timeframe for it is unknown, going to go ahead and set this to lifecycle frozen for now.
/lifecycle frozen

**Comment by mrbobbytables** [comment]
Closing this as there has been no update on when the beta may restart
/close
