### ISSUE TITLE
Clean up YouTube moderators

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#5180]
We haven't had a clean up in a while, and I know only a handful of us are moderating so we need to clean this up. 

If you're actively moderating/streaming please ack this issue, if not, no worries we'll just put you in emeritus, either way the list needs to reflect reality so that we new contributors opportunities to participate. 

- [x] @castrojo
- [x] @mrbobbytables 
- [ ] @parispittman 
- [x] @chris-short 
- [ ] @idvoretskyi 
- [x] @jeefy 
- [ ] @jbeda 
- [x] @markyjackson-taulia 
- [ ] @nzoueidi 
- [x] @onlydole 
- [ ] @idealhack 
- [ ] @alejandrox1

**Comment by markyjackson-taulia** [comment]
ack

**Comment by jeefy** [comment]
ack, though primarily as a backup streamer and ad-hoc request processor.

**Comment by onlydole** [comment]
Ack - I help with uploads, metadata edits, and Zoom faux pas. I'd like to chat with y'all about streaming as I'm coming along with OBS 😄

**Comment by jeefy** [comment]
I'm happy to run a mini workshop for the YT admins on streaming if people are interested. :)

**Comment by castrojo** [comment]
Also wondering how useful having the release lead be able to self-serve, something to consider? (Or someone else on the release team)

**Comment by chris-short** [comment]
Yeah, I'm here when streaming needs to happen and no one else can.

**Comment by mrbobbytables** [comment]
Just as a general note - we'd really like the YT mods to help with wrangling of posting of videos. Lately It's just been myself, @markyjackson-taulia and @castrojo and tbh - @markyjackson-taulia <3 has been the one really carrying the torch lately. We really need more folk to help with the general responsibilities of being YT admins =/

**Comment by markyjackson-taulia** [comment]
If I can help anyone who sees this issue and wants to learn, just let me know :-)

**Comment by chris-short** [comment]
Teach me, Obi-Wan @markyjackson-taulia.

This is a muscle I need to learn.

**Comment by markyjackson-taulia** [comment]
@chris-short I will ping you tomorrow. Should take no more then 39 mins..

**Comment by onlydole** [comment]
@mrbobbytables / @markyjackson-taulia - After this week I free up quite a bit and am able to help accordingly! If you have any requests, I'm happy to be a point of delegation (and will respond to any `youtube-admins` mentions I see in Slack).

**Comment by chris-short** [comment]
I'm around tomorrow, @markyjackson-taulia.

**Comment by markyjackson-taulia** [comment]
I'm happy to just hang out! But if you can't get enough of me: https://youtu.be/IbZ2wnvu_Zs

**Comment by castrojo** [comment]
My old work account and jbeda's account are now removed, afaict youtube now reflects what we want. We should probably review one more time as a group and then close?

**Comment by mrbobbytables** [comment]
This has now been synced
/close
