### ISSUE TITLE
Embedding DevStats charts into the Contributor Website

### ISSUE THREAD

**Issue by LappleApple** [kubernetes/community#5181]
In recent months we've been discussing ways to make [DevStats](https://k8s.devstats.cncf.io/d/12/dashboards?orgId=1&refresh=15m) optimally appealing and attractive for different types of users, including:
- SIG Chairs and Tech Leads
- the range of contributors to the project 
- Open source program managers at companies
- Members of the Steering Committee

To gain a greater understanding of the types of data these different users would like to have convenient access to, we've been interviewing members of the community, collecting feedback, and shaping the results into personae. You can review our progress to date [here](https://docs.google.com/spreadsheets/d/1pkYr9PqKtRQtkFIxpG6s1Ad3DGPoyIOH7JxEzn9Aspk/edit#gid=190083292).

As part of our effort, we have been discussing the user advantages of embedding relevant DevStats dashboards into the Contributor Website. Our first steps (more TBD):
- [x] determining if/how this is possible from a technical perspective. Embedding iframes? And can Grafana accommodate this well? 
- [ ] estimating the required effort

In recent Contribex meetings Bob Killen volunteered knowledge on this, and @celestehorgan was named as a knowledgeable source, so I'll assign to Bob and give Celeste the freedom to self-assign (yay autonomy :)). 

/assign @mrbobbytables 
/assign @LappleApple

Adding Jenny, Nikitha and Sergey here so they can follow along, and pending the evolution of this issue get involved.

**Comment by mrbobbytables** [comment]
WIP PR is here: https://github.com/kubernetes-sigs/contributor-site/pull/194
Preview of dashboard embeds: https://deploy-preview-194--kubernetes-contributor.netlify.app/resources/dashboards/

**Comment by nikhita** [comment]
@mrbobbytables based on https://github.com/kubernetes/contributor-site/pull/194#issuecomment-825667362, can this be closed?
