### ISSUE TITLE
wg-k8s-infra: multiple meeting recordings missing from youtube playlist

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#5199]
Playlist link: https://www.youtube.com/playlist?list=PL69nYSiGNLP2Ghq7VW8rFbMFoHwvORuDL

I suspect all of these are due to the splain/youtube automation flaking out.  I'm happy to manually upload and update the playlist if it'll ease burden on youtube/zoom admin.

I moved all recordings in our zoom account to trash if they had been previously uploaded, leaving the following which need to be uploaded
- 2020-09-16
- 2020-06-10
- 2020-05-13
- 2020-04-29
- 2020-04-01
- 2020-03-18
- 2020-01-22

/wg k8s-infra
FYI @dims @bartsmykla 
/sig contributor-experience
/area community-management
total guess, was looking for a youtube or zoom label

**Comment by spiffxp** [comment]
Link to slack thread: https://kubernetes.slack.com/archives/C1TU9EB9S/p1602097305225400

My take-away is that the current automation is a bit flaky, and it'll be easier to download the recordings from Zoom and then manually upload them, at least to backfill what's currently missing.

**Comment by spiffxp** [comment]
/assign @castrojo 
who offered to help upload if I could get recordings into a bucket
```
$ gsutil mb gs://spiffxp-k8s-recordings
$ gsutil iam ch allUsers:objectViewer gs://spiffxp-k8s-recordings
$ gsutil cp * gs://spiffxp-k8s-recordings
$ gsutil ls gs://spiffxp-k8s-recordings
gs://spiffxp-k8s-recordings/Kubernetes WG K8s Infra - 2020-01-22.mp4
gs://spiffxp-k8s-recordings/Kubernetes WG K8s Infra - 2020-03-18.mp4
gs://spiffxp-k8s-recordings/Kubernetes WG K8s Infra - 2020-04-01.mp4
gs://spiffxp-k8s-recordings/Kubernetes WG K8s Infra - 2020-04-29.mp4
gs://spiffxp-k8s-recordings/Kubernetes WG K8s Infra - 2020-05-13.mp4
gs://spiffxp-k8s-recordings/Kubernetes WG K8s Infra - 2020-06-10.mp4
gs://spiffxp-k8s-recordings/Kubernetes WG K8s Infra - 2020-09-16.mp4
```

**Comment by spiffxp** [comment]
/close
These were all uploaded last week.  Thanks @castrojo

**Comment by spiffxp** [comment]
/reopen
The two most recent meetings have also not automatically uploaded, I'll download and upload into GCS shortly

**Comment by spiffxp** [comment]
Turns out it was just one meeting, 2020-10-28 has been posted

```gs://spiffxp-k8s-recordings/Kubernetes WG K8s Infra BI-Weekly Meeting for 20201014.mp4```

**Comment by markyjackson-taulia** [comment]
This video is now processing and will be available in 5 to 10 mins.. Sorry for the delay.

**Comment by spiffxp** [comment]
/reopen
Last week's meeting recording never uploaded, I've placed into GCS if someone can help upload
```
$ gsutil ls gs://spiffxp-k8s-recordings
gs://spiffxp-k8s-recordings/Kubernetes WG K8s Infra - 2021-01-20.mp4
```

Linking back to issue to review zoom automation: https://github.com/kubernetes/community/issues/5201

**Comment by spiffxp** [comment]
The meeting for 2020-01-20 remains missing.

The meeting for 2020-02-03 never uploaded either, so I've added that to the GCS bucket.

```
$ gsutil ls gs://spiffxp-k8s-recordings
gs://spiffxp-k8s-recordings/Kubernetes WG K8s Infra - 2021-01-20.mp4
gs://spiffxp-k8s-recordings/Kubernetes WG K8s Infra - 2021-02-03.mp4
```

/unassign @castrojo
/assign @alisondy @mrbobbytables
Please assign to someone more relevant if you don't have the bandwidth.  Also, I think maybe I'm ready to suggest we cut off Splain automation, and I'll just go back to uploading manually?  Let me know what you think.

**Comment by mrbobbytables** [comment]
The only consistent way I've found to get splain to work after a meeting
stops being posted is to recreate the meeting with a new zoom id.

**Comment by spiffxp** [comment]
Meetings are up. I’ll get a new zoom meeting set up to close

**Comment by mrbobbytables** [comment]
Just checking back in, are things good now?

**Comment by spiffxp** [comment]
They are not. I never got around to creating a new meeting. Will do so tomorrow. We are also behind in recordings again, I may just upload those myself to a channel I have publish rights to, and add to the shared playlist save you the trouble

**Comment by spiffxp** [comment]
Today's meeting was a new recurring meeting, if It gets automatically uploaded I'll call this done.

**Comment by spiffxp** [comment]
And... it did not.  I'll just manually upload to my channel again and add to playlist

**Comment by spiffxp** [comment]
@ameukam and myself have been manually uploading to our own channels and adding to https://www.youtube.com/playlist?list=PL69nYSiGNLP2Ghq7VW8rFbMFoHwvORuDL

I created a new meeting ID when we re-scheduled, and thus far have yet to see anything get automatically uploaded.  Is there any additional configuration that needs to happen to get auto-uploading working again, or should we consider it abandoned?

**Comment by spiffxp** [comment]
/close
/triage unresolved
Closing as wont-fix, at this point I think we'll just get by manually uploading videos to our own channels and adding to playlist until there is a better solution available
