### ISSUE TITLE
REQUEST: New communication about Steering Committee results!

### ISSUE THREAD

**Issue by mbbroberg** [kubernetes/community#5213]
**What do you want send out?** (Please include a link to a draft)

The Steering committee, via @jberkus, requested an article on the Steering Committee results. 

https://docs.google.com/document/d/1Qz-DsXt7uohIWjPsFxpuFHWtx2CSwW7i2mQ4h77thFI/edit

- [x] I agree that if this is urgent, I will @contributor-comms in #sig-contribex Slack.

**Comment by castrojo** [comment]
Here is the information from last year: https://kubernetes.io/blog/2019/10/03/2019-steering-committee-election-results/

**Comment by jberkus** [comment]
@kaslin pinged us and we're coordinating

**Comment by mbbroberg** [comment]
Merged!
