### ISSUE TITLE
Write up method for community contributed chapters for recordings

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#5222]
We can make chapters on our youtube videos to make it easier for users to consume our content. The format is basically: 

0:00 Begin
00:15 Foo
00:30 Bar

And so on. We could do this for large meetings like the community meeting where we can chapter up the SIG updates, the release, etc. All we would need is for a youtube admin to copy and paste the table of contents from a volunteer who just watches the video and notes down the timestamps.

Chapter example: https://www.youtube.com/watch?v=ID-bnZCIOFw

Then what we can do is append text on every new video that doesn't have a decent description with something like "Want to help contribute? If you're going to watch this video anyway please consider writing down timestamps for this video (click link for instructions), and then submit them via github via these instructions", then we have a template for them to follow.

**Comment by castrojo** [comment]
Riaan's done the community video: https://www.youtube.com/watch?v=h7jth3Js-Vg&feature=youtu.be

Looks great! We're thinking along the lines of appending text to videos we'd want to chapterize with something like: "Watching this video? Help the community by creating a ToC for this by following these instructions", and then a github template, then anyone can click through and submit a ToC and then we just slap it onto the video. Bob thinks we can do the video description through a github action right to youtube, but not putting the cart before the horse yet.

**Comment by Riaankl** [comment]
/remove-lifecycle stale
@castrojo Did this get any traction?
Can I help/
