### ISSUE TITLE
[Developer Guide Audit] Architecture

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#5231]
Documentation is the go-to reference for contributors. Parts of the developer guide have been cited as vastly out of date (e.g. referencing VERY outdated versions of docker). We are asking each SIG that owns a portion of the developer guide to audit their [devel guide documentation](https://github.com/kubernetes/community/tree/master/contributors/devel/). 

**This does not have to include updating it.**
(although if you want to, please go ahead 😄 )

If you could, update this issue with items that are out of date or you think should be added to the [Architecture](https://github.com/kubernetes/community/tree/master/contributors/devel/sig-architecture) portion of the devel guide. 

Assigning to leads, but please feel free to re-assign and delegate.
/assign @derekwaynecarr @dims @johnbelamaric 

**Potential Related Items**
- [api-conventions.md should explain patchStrategy](https://github.com/kubernetes/community/issues/3752)
- [Separating proposals and architecture related items from community](https://github.com/kubernetes/community/issues/2565)
- [Clarify the correct ways to differentiate different behavioral modes of API resources](https://github.com/kubernetes/community/issues/859)
- [Document conventions for raw API fields](https://github.com/kubernetes/community/issues/357)
- [Proposal: document structure of annotation/label namespaces more completely](https://github.com/kubernetes/community/issues/300)

---
Parent Tracking Issue: #5229 
/sig architecture
/sig contributor-experience
/area developer-guide
/milestone v1.20

**Comment by mrbobbytables** [comment]
Reminder ping @derekwaynecarr @dims @johnbelamaric
It doesn't have to be done this cycle, but would like to get it on the radar to be evaluated if possible^^;;; Identified items become something we can farm out to update.

**Comment by sftim** [comment]
I raised https://github.com/kubernetes-sigs/contributor-site/issues/207 not knowing this was already open.

**Comment by mrbobbytables** [comment]
@dims @johnbelamaric @derekwaynecarr Any chance this could get looked at this cycle?

**Comment by dims** [comment]
@mrbobbytables will look into possibilities! ( cc @navidshaikh )

**Comment by dims** [comment]
@kikisdeliveryservice Could you please organize some folks to revisit this on behalf of sig-arch?

**Comment by kikisdeliveryservice** [comment]
Just to track the docs already in the dir:

- [ ] api-conventions.md - updated this week, will confirm it's up-to-date
- [ ] api_changes.md - - updated this month, will confirm it's up-to-date
- [ ] component-config-conventions.md - hasn't been updated in years, will get this looked at
- [ ] conformance-tests.md - updated in may have asked conformance team to re-review in case needs update
- [ ] feature-gates.md - update was in june, I'll double check that we don't need anything else in the near term
- [ ] godep.md - deprecated, we use go modules now (doc is vendor.md below)
- [ ] staging.md -  hasn't been updated since 2019, list of published branches stale, will get it updated.
- [ ] vendor.md - this was updated in the last month by @dims

**Comment by mrbobbytables** [comment]
One other thing that would be worth looking at, what files are worth copying from the sig-arch design proposals directory to the dev docs. Once that's done we can archive those off some place for good 🎉

**Comment by kikisdeliveryservice** [comment]
> One other thing that would be worth looking at, what files are worth copying from the sig-arch design proposals directory to the dev docs. Once that's done we can archive those off some place for good

@mrbobbytables that would be this right? https://github.com/kubernetes/community/issues/2565#issuecomment-758615477

**Comment by mrbobbytables** [comment]
Yup!
We could probably move and copy later too, but it'd be sorta nice to get it on the list.

**Comment by kikisdeliveryservice** [comment]
> Yup!
> We could probably move and copy later too, but it'd be sorta nice to get it on the list.

Great! I'm going thru the linked things in your Description as well. Just trying to organize myself and wrap my brain around the state of everything now :smile:

**Comment by dims** [comment]
@MadhavJivrajani @palnabarun any interest in this?
