### ISSUE TITLE
[Developer Guide Audit] CLI

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#5232]
Documentation is the go-to reference for contributors. Parts of the developer guide have been cited as vastly out of date (e.g. referencing VERY outdated versions of docker). We are asking each SIG that owns a portion of the developer guide to audit their [devel guide documentation](https://github.com/kubernetes/community/tree/master/contributors/devel/). 

**This does not have to include updating it.**
(although if you want to, please go ahead 😄 )

If you could, update this issue with items that are out of date or you think should be added to the [CLI](https://github.com/kubernetes/community/tree/master/contributors/devel/sig-cli) portion of the devel guide. 

Assigning to leads, but please feel free to re-assign and delegate.
/assign @seans3 @soltysh @pwittrock

---
Parent Tracking Issue: #5229 
/sig cli
/sig contributor-experience
/area developer-guide
/milestone v1.20

**Comment by mrbobbytables** [comment]
Reminder ping @seans3 @soltysh @pwittrock
It doesn't have to be done this cycle, but would like to get it on the radar to be evaluated if possible^^;;; Identified items become something we can farm out to update.

**Comment by soltysh** [comment]
@mrbobbytables it's on our radar, but not sooner than after the code freeze :wink:

**Comment by mrbobbytables** [comment]
@soltysh don't blame ya there in the least XD Just wanted to make sure it was visible :) Thank you for the ack!

**Comment by soltysh** [comment]
Some work was done by Phil in https://github.com/kubernetes-sigs/cli-experimental/pull/48 but I'll keep it open for full review in the upcoming weeks.

**Comment by eddiezane** [comment]
@SyamSundarKirubakaran is this something you'd be interested in hopping on?

**Comment by SyamSundarKirubakaran** [comment]
Sure @eddiezane, I'll sync up with Phil to get more context on this.

**Comment by mrbobbytables** [comment]
I know this is closed (from lifecycle) but was it completed?
@eddiezane @soltysh
