### ISSUE TITLE
[Developer Guide Audit] Node

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#5234]
Documentation is the go-to reference for contributors. Parts of the developer guide have been cited as vastly out of date (e.g. referencing VERY outdated versions of docker). We are asking each SIG that owns a portion of the developer guide to audit their [devel guide documentation](https://github.com/kubernetes/community/tree/master/contributors/devel/). 

**This does not have to include updating it.**
(although if you want to, please go ahead 😄 )

If you could, update this issue with items that are out of date or you think should be added to the [node](https://github.com/kubernetes/community/tree/master/contributors/devel/sig-node) portion of the devel guide. 

Assigning to leads, but please feel free to re-assign and delegate.
/assign @dchen1107 @derekwaynecarr 

---
Parent Tracking Issue: #5229 
/sig node
/sig contributor-experience
/area developer-guide
/milestone v1.20

**Comment by mrbobbytables** [comment]
Reminder ping @dchen1107 @derekwaynecarr
It doesn't have to be done this cycle, but would like to get it on the radar to be evaluated if possible^^;;; Identified items become something we can farm out to update.

**Comment by mrbobbytables** [comment]
cc @SergeyKanzhelev @ehashman

**Comment by ehashman** [comment]
Added to next week's agenda.

**Comment by ehashman** [comment]
I don't think so...

/reopen
/remove-lifecycle rotten

**Comment by endocrimes** [comment]
/remove-lifecycle stale

working on this - blocked on approvals for some draft docs before doing a full audit in one go
