### ISSUE TITLE
[Developer Guide Audit] Release

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#5235]
Documentation is the go-to reference for contributors. Parts of the developer guide have been cited as vastly out of date (e.g. referencing VERY outdated versions of docker). We are asking each SIG that owns a portion of the developer guide to audit their [devel guide documentation](https://github.com/kubernetes/community/tree/master/contributors/devel/). 

**This does not have to include updating it.**
(although if you want to, please go ahead 😄 )

If you could, update this issue with items that are out of date or you think should be added to the [release](https://github.com/kubernetes/community/tree/master/contributors/devel/sig-release) portion of the devel guide. 

Assigning to leads, but please feel free to re-assign and delegate.
/assign @justaugustus @tpepper @alejandrox1 @saschagrunert 

---
Parent Tracking Issue: #5229 
/sig release
/sig contributor-experience
/area developer-guide
/milestone v1.20

**Comment by justaugustus** [comment]
I started some work by moving the version markers doc here: https://github.com/kubernetes/community/pull/5268

@kubernetes/sig-release-leads -- who's interested in driving the audit of our docs?

**Comment by justaugustus** [comment]
Also assigning Lauri!
/assign @LappleApple

**Comment by justaugustus** [comment]
Assigning Savitha as discussed in today's SIG Release meeting.

/assign @savitharaghunathan 
/unassign @justaugustus @tpepper @saschagrunert @hasheddan @LappleApple @alejandrox1

**Comment by justaugustus** [comment]
@savitharaghunathan -- any updates on this one?

**Comment by savitharaghunathan** [comment]
> @savitharaghunathan -- any updates on this one?

Apologies for not progressing on this issue. It fell off my plate. I will get to it this weekend.

**Comment by savitharaghunathan** [comment]
Update: I am working on putting a document together with items that can be moved. I Will share it with the wider group, once I have it ready for feedback and comments. Thank you :)

**Comment by LappleApple** [comment]
Hi @savitharaghunathan, any updates on this?

**Comment by savitharaghunathan** [comment]
Hi @LappleApple, I have made very minimal progress on this since my last update. I am hoping to tackle this in the 1.22 cycle if it is okay to move it to the 1.22 milestone. Thanks :)

**Comment by jeremyrickard** [comment]
@savitharaghunathan can you pick up or re-assign to someone on release team or new contributor?

**Comment by savitharaghunathan** [comment]
/unassign 
I would be happy to provide context and guidance if any contributor wants to pick this up.

**Comment by jeremyrickard** [comment]
We will try and address this during 1.23

**Comment by saschagrunert** [comment]
/remove-lifecycle stale


> We will try and address this during 1.23

Did we finish that in 1.23?

**Comment by justaugustus** [comment]
> Did we finish that in 1.23?

We currently have no assignee here. Assigning Jeremy, since he was the last to comment on this. :)
/assign @jeremyrickard 
/milestone v1.24
/priority important-soon

**Comment by jeremyrickard** [comment]
@savitharaghunathan I will pick this up and get it moving forward. I'll reach out on slack to do a handoff/context transfer if that is ok.
