### ISSUE TITLE
[Developer Guide Audit] Scalability

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#5236]
Documentation is the go-to reference for contributors. Parts of the developer guide have been cited as vastly out of date (e.g. referencing VERY outdated versions of docker). We are asking each SIG that owns a portion of the developer guide to audit their [devel guide documentation](https://github.com/kubernetes/community/tree/master/contributors/devel/). 

**This does not have to include updating it.**
(although if you want to, please go ahead 😄 )

If you could, update this issue with items that are out of date or you think should be added to the [scalability](https://github.com/kubernetes/community/tree/master/contributors/devel/sig-scalability) portion of the devel guide. 

Assigning to leads, but please feel free to re-assign and delegate.
/assign @mm4tt @shyamjvs @wojtek-t 

---
Parent Tracking Issue: #5229 
/sig scalability
/sig contributor-experience
/area developer-guide
/milestone v1.20

**Comment by mrbobbytables** [comment]
Reminder ping @mm4tt @shyamjvs @wojtek-t

It doesn't have to be done this cycle, but would like to get it on the radar to be evaluated if possible^^;;; Identified items become something we can farm out to update.

**Comment by mm4tt** [comment]
Hey Bob, this devel documentation is old and indeed might be outdated in many places. I skimmed through it and while some of the instructions there may still work it definitely doesn't reflect the spirit of current scalability efforts. For example, the documentation doesn't mention clusterloader2 at all.

I'm adding this to my TODO list. Unfortunately, I won't be able to do it this quarter. Will aim to review and update it in Q1 2021.

**Comment by mrbobbytables** [comment]
No worries @mm4tt :) Thank you for the update. I just wanted to make sure its on folks radar.

**Comment by wojtek-t** [comment]
Docs to be update:
- [ ] the two kubemark-related docs should be updated and merged into a single kubemark-related one
- [ ] documentation on how to use cluster-loader should be added
- [ ] documentation on how to extend cluster-loader should be added

Having those should give us a good start.

**Comment by wojtek-t** [comment]
/remove-lifecycle stale

@marseel did a bit of progress on improving our documentation, but there are still things left to audit here

**Comment by marseel** [comment]
I've added tutorials about:
- documentation on how to use cluster-loader should be added
- documentation on how to extend cluster-loader should be added
I think we can close this issue for now.  This should be a good starting point for new contributors.
/close
