### ISSUE TITLE
[Developer Guide Audit] Storage

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#5238]
Documentation is the go-to reference for contributors. Parts of the developer guide have been cited as vastly out of date (e.g. referencing VERY outdated versions of docker). We are asking each SIG that owns a portion of the developer guide to audit their [devel guide documentation](https://github.com/kubernetes/community/tree/master/contributors/devel/). 

**This does not have to include updating it.**
(although if you want to, please go ahead 😄 )

If you could, update this issue with items that are out of date or you think should be added to the [storage](https://github.com/kubernetes/community/tree/master/contributors/devel/sig-storage) portion of the devel guide. 

Assigning to leads, but please feel free to re-assign and delegate.
/assign @saad-ali @xing-yang @jsafrane @msau42 

---
Parent Tracking Issue: #5229 
/sig storage
/sig contributor-experience
/area developer-guide
/milestone v1.20

**Comment by xing-yang** [comment]
Hi @mrbobbytables, do the docs shown under sig-storage have to be files in this repo?  Can we add links to docs from other places, i.e., https://kubernetes-csi.github.io/docs/?

https://github.com/kubernetes/community/tree/master/contributors/devel#sig-storage

**Comment by mrbobbytables** [comment]
They don't have to be in this repo, but I would definitely add a sign-post from there to the other docs. - The devel directory is where we direct folks getting started so any pointers on where to go would be very useful.
