### ISSUE TITLE
[CSI and localpv]

### ISSUE THREAD

**Issue by ruanchen** [kubernetes/community#5271]
it's there any talk about CSI and Local PV in the future version?

**Comment by coderanger** [comment]
Can you be more specific? This repo is for tracking community projects. If you would like to ask about the progress of features, that would be a question for a SIG meeting or mailing list.

**Comment by mrbobbytables** [comment]
@coderanger is right; a question like that isn't going to get answered here =/ This place is the meta repo for contributor community management. His suggestion of reaching out to the sig-storage mailing list/meeting/slack channel would be the right course of action.

With that I'm going to go ahead and close this out. If you have any further questions please feel free to respond or ask in slack 👍 

/close
