### ISSUE TITLE
GitHub Recognition Beta: Shoutout test issue

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#5277]
Test issue for the GitHub recognition beta

ref: https://github.com/kubernetes/community/issues/5175

---
/sig contributor-experience

**Comment by mrbobbytables** [comment]
Test typing below shoutout line.

**Comment by nikhita** [comment]
I've sent some feedback to GitHub. Will delete the stray shoutouts after I've received a response from them. Sorry for the noise!

**Comment by dims** [comment]
![image](https://user-images.githubusercontent.com/23304/97428305-31b18c80-18ec-11eb-96ef-af2aeb0bf155.png)

I can see the shoutout on my hover card.

**Comment by bdresser** [comment]
Multiple shoutouts in the same comment aren't supported yet, but they will be eventually :)

**Comment by coderanger** [comment]
/shoutout @kubernetes/bots for does it work with teams?

**Comment by mrbobbytables** [comment]
GitHub has put a pause on the beta for now and plan to revisit it in 2021. As the timeframe for it is unknown, going to go ahead and set this to lifecycle frozen for now.
/lifecycle frozen
