### ISSUE TITLE
owners team link broken

### ISSUE THREAD

**Issue by hi-rustin** [kubernetes/community#5285]
The owners team link broken in https://github.com/kubernetes/community/blob/master/github-management/README.md#github-administration-team.

**Comment by nikhita** [comment]
@hi-rustin did you mean https://github.com/orgs/kubernetes/teams/owners? That link will only be visible to Kubernetes org members due to how GitHub teams work.

**Comment by hi-rustin** [comment]
> That link will only be visible to Kubernetes org members due to how GitHub teams work.

Got it. Thanks!
