### ISSUE TITLE
GitHub Recognition Beta: Community Feedback

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#5292]
## Community Feedback
Please use this issue for feedback on the [GitHub Recognition Beta](https://github.com/kubernetes/community/issues/5175).

### TL;DR
Kubernetes is participating in a GitHub beta where members can recognize, thank or give kudos to other members. 🎉
For Kubernetes, this is in the form of a shoutout:
```
/shoutout @foobar for an awesome PR review
```
These will appear in the timeline and user hovor card.

---
Tracking Issue: https://github.com/kubernetes/community/issues/5175
Test Issue: https://github.com/kubernetes/community/issues/5277
/sig contributor-experience
/area github-management
/milestone v1.20

**Comment by coderanger** [comment]
The timestamp on a shoutout doesn't have an anchor link like other events, would be nice for showing off a shoutout on Twitter or whatnot. Also it would be nice if you could use reaction emoji on them for others to +1 a shoutout without a ton of noise.

**Comment by mrbobbytables** [comment]
GitHub has put a pause on the beta for now and plan to revisit it in 2021. As the timeframe for it is unknown, going to go ahead and set this to lifecycle frozen for now.
/lifecycle frozen

**Comment by mrbobbytables** [comment]
Closing this as there has been no update on when the beta may restart
/close
