### ISSUE TITLE
Triage Process Feedback

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#5299]
### Feedback Thread
It has now been a few weeks since the roll-out of the `needs-triage` labels. Several bumps and issues have been raised in slack and elsewhere.

Please post comments, friction points, and any other feedback in this issue.

---
/sig contributor-experience
/area community-management
/area github-management

**Comment by mrbobbytables** [comment]
### Problem
A PR that touches a file that has a sig label applied by the label key in an OWNERS file will automatically reapply the label if it is removed. This is a feature ensuring that a PR that is updated and touches a new file has the new sig label applied and signals a new group of potential owners needing to approve the PR.

The problem arises during triage when a PR touches multiple areas and a SIG wants to "remove it from their queue" after determining that it should not be evaluated by them.

---

**Thought:** Add a command that signals CI to ignore attempts to apply a specific label. It could potentially cause problems if a PR is updated and touches a new area that would require a sig to look at it again, but could potentially be implemented in a similar fashion to the new approve plugin where files could be selectively approved:

```
/ignore-sig foo /some/path/blah
```

This would not solve the problem if an owner from there is still needed, and could potentially be a further problem if that area is updated at a later date.

**Comment by lavalamp** [comment]
Yeah, this is hitting sig api-machinery repeatedly as there's lots of stuff we co-own with other sigs.

**Comment by sftim** [comment]
When I triage an issue in [k/website](https://github.com/kubernetes/website) eg `/triage needs-information`, sometimes the issue can be both triaged and needing triage.
Eg at the time of writing https://github.com/kubernetes/website/issues/24657 is labelled _needs-triage_ and _triage/needs-information_.

**Comment by mrbobbytables** [comment]
@sftim That is indeed the intended behavior. There was some back and forth on it, but it was decided that method would be best.

**Comment by sftim** [comment]
When adding this to a repo, existing issues don't get _needs-triage_ added; is that right? I think I'd prefer it to have the old issues get that label too if they need it.

**Comment by thockin** [comment]
I am not sure that needs-triage is useful for PRs.  At least *I* don't pay attention to that.

**Comment by ehashman** [comment]
Feedback from SIG Instrumentation:

- We use and find needs-triage useful for both issues and PRs. It helps us track what issues and PRs we haven't looked at already.
- We are running into some contention issues when things span multiple SIGs. We might want to triage/accept things for SIG Instrumentation, but e.g. maybe SIG API-Machinery disagrees with us. We're not really sure how to manage this.


If anyone wants to see how SIG Instrumentation does our [triage sessions], feel free to drop in. We run them biweekly Wednesdays at 9am PT (next one is 2020-12-02 given the KubeCon/US Thanksgiving break).

[triage sessions]: https://github.com/kubernetes/community/blob/master/sig-instrumentation/README.md#meetings

**Comment by nikhita** [comment]
> When adding this to a repo, existing issues don't get needs-triage added; is that right? I think I'd prefer it to have the old issues get that label too if they need it.

Old issues and PRs will get the `needs-triage` label if there are any changes on the issue/PR i.e. it is reopened or labels are updated. Unconditionally updating old issues becomes trickier because it could mean that we'd hit the rate limit if there are a lot of issues (which is usually the case for kubernetes repos).

**Comment by sftim** [comment]
Is there any mechanism for trickling old, open issues into Prow's labelling mechanisms? Even 1 per minute would be useful I think.

**Comment by ehashman** [comment]
Is #5436 useful for other SIGs here?

**Comment by ehashman** [comment]
Two notes that came out of SIG Instrumentation's triage session today:

- Applying the `triage/unresolved` label doesn’t remove the needs-triage label -- is this a bug?
- What do we do when we don’t want to accept a PR but we also want to mark that we’ve looked at it? `triage/unresolved`? New contributors tend to view `triage/accepted` as "we're going to review and merge your PR," and for some PRs that's not the right signal.

**Comment by thockin** [comment]
My opinion:

For issues, triage/accepted means:
 - we have confirmed or reproduced the issue
 - we have categorized it as a bug/feature/etc
 - we have applied some notion of priority
 - we do not need further debate over whether this is real or not

For PRs it is far less clear.  It certainly doesn't mean "we're going to
review and merge your PR".  I think it means:
 - we have looked at it, and it is not outright rejected
 - we think the assignee is reasonable to evaluate further

**Comment by lavalamp** [comment]
For SIG API Machinery, 

* on issues, triage/accepted means we agree we're the right SIG, and we've selected someone to decide what to do about the issue
* on PRs, it means we've assigned a reviewer (but not made a judgement about whether or not the PR should be merged)

**Comment by sftim** [comment]
For k/website, `/triage accepted` is a good way of marking issues as not-incoming, making it much easier to spot issues that are new vs. those that “need triage” because they are incomplete, or look like a support request, etc.
