### ISSUE TITLE
Confused with CheckNodeMemoryPressure

### ISSUE THREAD

**Issue by maxim28** [kubernetes/community#530]
The Algorithm document says:

> CheckNodeMemoryPressure: Check if a pod can be scheduled on a node reporting memory pressure condition. Currently, no BestEffort should be placed on a node under memory pressure as it gets automatically evicted by kubelet.

i think it means all pods except BestEffort will be checked for NodeMemoryPressurePredicate, is that right? but when i investigated the code, which means No BestEffort Pods will not be checked?

```
func CheckNodeMemoryPressurePredicate(pod *v1.Pod, meta interface{}, nodeInfo *schedulercache.NodeInfo) (bool, []algorithm.PredicateFailureReason, error) {
    var podBestEffort bool
    if predicateMeta, ok := meta.(*predicateMetadata); ok {
        podBestEffort = predicateMeta.podBestEffort
    } else {
        // We couldn't parse metadata - fallback to computing it.
        podBestEffort = isPodBestEffort(pod)
    }
    // pod is not BestEffort pod
    if !podBestEffort {
        return true, nil, nil
    }

    // is node under presure?
    if nodeInfo.MemoryPressureCondition() == v1.ConditionTrue {
        return false, []algorithm.PredicateFailureReason{ErrNodeUnderMemoryPressure}, nil
    }
    return true, nil, nil
}
```

Similar in CheckNodeDiskPressurePredicate, the document says

> CheckNodeDiskPressure: Check if a pod can be scheduled on a node reporting disk pressure condition. Currently, no pods should be placed on a node under disk pressure as it gets automatically evicted by kubelet.

i think it means all pods will be checked for NodeDiskPressurePredicate, and the code describe the same thing:

```
func CheckNodeDiskPressurePredicate(pod *v1.Pod, meta interface{}, nodeInfo *schedulercache.NodeInfo) (bool, []algorithm.PredicateFailureReason, error) {
    // is node under presure?
    if nodeInfo.DiskPressureCondition() == v1.ConditionTrue {
        return false, []algorithm.PredicateFailureReason{ErrNodeUnderDiskPressure}, nil
    }
    return true, nil, nil
}
```

So anything wrong with the CheckNodeMemoryPressurePredicate? Or i misunderstood the meaning of CheckNodeMemoryPressurePredicate? Please help me figure it out, thank you very much.

**Comment by davidopp** [comment]
The implementations are consistent with the comments. First one (memory) says "no BestEffort should be placed on a node under memory pressure" and thus only applies the predicate for best-effort pods. Second one (disk) applies to all pods.

In the future, please post questions like this on StackOverflow over the kubernetes-users mailing list
https://groups.google.com/forum/#!forum/kubernetes-users

**Comment by maxim28** [comment]
OK，thanks for your response.
