### ISSUE TITLE
Surface email filtering page on k8s.dev

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#5303]
https://twitter.com/IanColdwater/status/1324842182658777089
https://github.com/kubernetes/community/blob/master/communication/best-practices.md

TLDR, add the metadata for this page to be surfaced on k8s.dev

/assign @castrojo

**Comment by championshuttler** [comment]
Hi @castrojo , I would like to help on this bug, can you help me with what i need to add and where? Thanks

**Comment by mrbobbytables** [comment]
it's been posted with the surfacing of our communication docs  - https://k8s.dev/comms
/assign
/close
