### ISSUE TITLE
SIG: Kubernetes-helm-chart sponsorship

### ISSUE THREAD

**Issue by kvaps** [kubernetes/community#5305]
Hey, first sorry if I choose wrong place for this issue.

I'm having a cool project to install Kubernetes in Kubernetes using a Helm chart:
https://github.com/kvaps/kubernetes-in-kubernetes

Currently it has no many contributors, but I'm going to make a speech about it soon.
I would like to share it with the community and if possible to continue development as **kubernetes-sigs/kubernetes-helm-chart**.
It would be nice to have independent development and possibly more people interested in this project.

In continue to [this conversation](https://groups.google.com/a/kubernetes.io/g/steering/c/bXtjjase-iU/m/p5IYf5FEAQAJ) on steering mailing list @dims let me know that I need to find a SIG that wants to sponsor this effort.
I would like to suggest **@kubernetes/sig-cluster-lifecycle** on this role since you are already having [**kubespray**](https://github.com/kubernetes-sigs/kubespray) and [**bootkube**](https://github.com/kubernetes-sigs/bootkube) projects under your wing.

Cheers!

**Comment by mrbobbytables** [comment]
This likely won't get much visibility here in this repo. For new initiatives you'll want to reach out on the [sig-cluster-lifecycle mailing list](https://github.com/kubernetes/community/tree/master/sig-cluster-lifecycle#contact).

**Comment by kvaps** [comment]
Hi @mrbobbytables,
Thanks for pointing out, I'll write on mailing list then!

**Comment by kvaps** [comment]
OK, let's move the conversation to
https://groups.google.com/g/kubernetes-sig-cluster-lifecycle/c/Tmr7LZ0g5iU
