### ISSUE TITLE
Feature repo and SIG PM should track "efforts", not "features"

### ISSUE THREAD

**Issue by idvoretskyi** [kubernetes/community#531]
_From @countspongebob on April 11, 2017 21:39_

Creating this issue per the SIG PM discussion today. Linking this issue to Ihor's proposed feature lifecycle doc and the governance PM discussion as requested during the call.

Linking to governance umbrella seems sensible, as the Seven need to ensure they either define or define who will own the overall change control process.

Draft feature lifecycle doc is [here](https://docs.google.com/document/d/1-D_QP2IC5Z_QJUmTOV24IsFknc9pGPU5xeq6gjP4f38/edit
). (Note that this proposal would also rename this to a "effort submission process".

Use of the word "feature" implies that that some new API call or new functional behavior of kubernetes is scope of the repo or the PM SIG. This also starts to beg the question "what is a feature". 

Proposing that the scope is instead a chunk of work of sufficiently large or significant scope that it should tracked and visible across the entire community with the following guidelines:

Your proposed work might belong in the "effort repo" if:
- It's a feature that would show up in blog
- It's something that would end up in the release notes
- If it crosses SIG boundaries
- If it affects a lot of developers 
- If it affects a lot of users

Checklists, review, and timing of all significant chunks of work (whether features or not) demand the same level of rigor and process.

Proposing feature repo should be renamed and SIG PM scope clarified.

-Bob

_Copied from original issue: kubernetes/features#247_

**Comment by bgrant0607** [comment]
The existing guidelines are any change that:
* a blog post would be written about after its release (ex. minikube, StatefulSets, rkt container runtime)
* requires multiple parties/SIGs/owners participating to complete (ex. GPU scheduling [API, Core, & Node], StatefulSets [Storage & API])
* needs significant effort or changes Kubernetes in a significant way (ex. something that would take 10 person-weeks to implement, introduce or redesign a system component, or introduces API changes)
* impacts the UX or operation of Kubernetes substatially such that engineers using Kubernetes will need retraining
* users will notice and come to rely on

Any API or CLI change should be tracked.

I'm inclined to say that anything that requires a proposal should be tracked.

**Comment by countspongebob** [comment]
Closing, especially in light of various process improvements.  Looking forward to see how we manage the KEP process in this regard.

/close
