### ISSUE TITLE
 Update broken links

### ISSUE THREAD

**Issue by hzliangbin** [kubernetes/community#5315]
[ Ephemeral Containers KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20190212-ephemeral-containers.md) turns to be `404 nout found`. it would be a help to update the [doc](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/troubleshoot-running-pods.md).

thx!

**Comment by hzliangbin** [comment]
/ sig node

**Comment by mrbobbytables** [comment]
design proposals are deprecated and there for historical purposes only. The enhancement repo is the correct location for any new info.

/close

**Comment by hzliangbin** [comment]
@mrbobbytables  thx
