### ISSUE TITLE
Prefixes and Suffixes

### ISSUE THREAD

**Issue by zinus92** [kubernetes/community#5316]
Hello,
I would like to make a small clarification (I apologize for the fussiness). In SI, the symbols "m, k, M, G, T, etc." they are **prefixes**, not suffixes.

**Comment by mrbobbytables** [comment]
Which docs are you asking to update?

**Comment by zinus92** [comment]
Sorry, I'm referring to community/contributors/design-proposals/scheduling/resources.md

**Comment by mrbobbytables** [comment]
That doc is for [historical purposes only](https://github.com/kubernetes/community/tree/master/contributors/design-proposals#kubernetes-design-documents-and-proposals). Updates are blocked to the entire design-proposal directory as the process was replaced by [Kubernetes Enhancement Proposals](https://github.com/kubernetes/enhancements)

/close
