### ISSUE TITLE
PR template creates invalid commit messages

### ISSUE THREAD

**Issue by paulczar** [kubernetes/community#5348]
It appears that the PR template creates an invalid commit message due to the `fixes:  #` section.

The offending line in the template: https://github.com/kubernetes/community/blame/master/.github/PULL_REQUEST_TEMPLATE.md#L15

What causes an invalid commit message tag: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#do-not-use-github-keywords-or-mentions-within-your-commit-message

**Comment by mbbroberg** [comment]
/sig contributor-experience 

Thanks Paul! 

Hey @castrojo, the latest policy is to not have `Fixes` annotation, right? If so, I'm down to remove it from the template.

**Comment by mrbobbytables** [comment]
The PR template is not intended to be a part of the commit msg which is whats flagging the bot. It's the text that gets loaded into the first response.

**Comment by paulczar** [comment]
Ahhh yeah good call, I don't know what I did wrong to end up with it in there. I'll close this out, pretty sure I'm wrong.
