### ISSUE TITLE
Kubernetes Issue Triage Workflow and Automation missing few items

### ISSUE THREAD

**Issue by spzala** [kubernetes/community#5358]
While working on updating the triage guideline according to the new Issue Triage Workflow and Automation KEP [1] and the new workflow[2], I noticed that the new workflow/automation seems not complete. 

Please see this issue https://github.com/kubernetes/kubernetes/issues/96066  - as you can see, `triage/needs-information` and `triage/not-reproducible` were correctly added in the beginning. Later, `triage/accepted` was added. Now, the issues has all three `triage/` labels, which seems not right. 

Here is how we describe the labels: 
`triage/accepted` - Indicates an issue or PR is ready to be actively worked on. (i.e. It should applied upon determining that an issue is ready to be actively worked on.) 
`triage/needs-information` -  Indicates an issue needs more information in order to work on it.
`triage/not-reproducible` - Indicates an issue can not be reproduced as described.

The `triage/accepted` indicates that issue is being triaged and doesn’t need more information to work on it. That means, the other two labels triage/needs-information and triage/not-reproducible  shouldn’t be there in the open issue mentioned above. 

I think this is a problem and the possible solution would be one or more of below: 

- either automatically (or at least manually) remove the other triage labels when `triage/accepted` applied 

- anyone applying `triage/accepted` should first make sure that triage need is satisfied and remove the other triage labels before applying the `triage/accepted`. 

- if issue owner finds out that it needed a further triage (e.g. more info) and add new triage/ label than the `triage/accepted` should be removed.

Does this make sense? If so, until we discuss further automation at least we should document that we should take care of this situation manually. 

[1] https://github.com/kubernetes/enhancements/pull/1554
[2] https://github.com/kubernetes/enhancements/tree/master/keps/sig-contributor-experience/1553-issue-triage#new-workflow

**Comment by mrbobbytables** [comment]
> Please see this issue kubernetes/kubernetes#96066 - as you can see, triage/needs-information and triage/not-reproducible were correctly added in the beginning. Later, triage/accepted was added. Now, the issues has all three triage/ labels, which seems not right.

`triage/accepted` is independent of the other labels. It essentially means its been evaluated by a community group.
There was a lot of back and forth, but that was what was decided on as the best path forward with it.

I'm pretty sure the other labels just weren't removed when it was accepted. I'd consider that more an edge than regular case looking at other isuses in k/k. - Looking at others, that one issue is the only one with both triage/accepted and triage/needs-information.

**Comment by spzala** [comment]
OK, thanks @mrbobbytables We can keep eye on it, and see if we find more such issues as 96066. If not, we are good. I will create a PR for documenting the other things.

**Comment by mrbobbytables** [comment]
@spzala I think we're good to close this one, right?

**Comment by spzala** [comment]
@mrbobbytables +1 I kept it open to keep eye on the triage flow in regards to this issue, but good idea to close too as didn't see anything new so far. Will reopen if needed. Thanks!
