### ISSUE TITLE
k8s.io/blue should point to our branding guidelines

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#5360]
As a joke @marcoceppi made https://326ce5.com/ which is the hex color code for Kubernetes blue so that if you need it for slides or whatever you're working on. It then points to https://branding.cncf.io/projects/kubernetes/

We should just do k8s.io/blue and have it point right to the CNCF logo page. In order to prevent (or encourage!) this bikeshed issue, we could do k8s.io/logos or something.

**Comment by alisondy** [comment]
+1

**Comment by cblecker** [comment]
So to spec this out:
- Base domain.. k8s.io vs go.k8s.io? The latter is normally used for short links.
- Are you suggesting both blue *and* logos? Or just one or the other?

As long as the destination page is either k8s project or CNCF controlled, I don't see a problem with this.

**Comment by castrojo** [comment]
go.k8s.io/logo makes more sense and follows other conventions.

**Comment by nikhita** [comment]
/remove-lifecycle stale

Adding the good-first-issue label.
/good-first-issue

If you are picking this issue up, here's how to proceed:

**What we want to do**:
Create a new shortlink go.k8s.io/logo to point to https://branding.cncf.io/projects/kubernetes

**Background**:
- The list of go.k8s.io redirections are here - https://github.com/kubernetes/k8s.io/tree/main/k8s.io#redirections
- The rewrite rules are defined in https://github.com/kubernetes/k8s.io/blob/main/k8s.io/configmap-nginx.yaml#L232

**How to do it**:
- Add a new line for go.k8s.io/logo in https://github.com/kubernetes/k8s.io/blob/main/k8s.io/configmap-nginx.yaml#L232


If you have questions on how to proceed here, please ping me in the #sig-contribex channel on the k8s slack.
