### ISSUE TITLE
chairs/orgs comms checklist/guidance 

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#5385]
loose idea:
- checklist and templates for suggested weekly, monthly, n cadence communications to community group members (ie - sig members) 
- examples:weekly meeting update template, new contributor alerts, maintainer opportunities, contributor process information, monthly important keps to review, etc. 
- could we automate any of this/does any of this need to be automated? - ie, keps with labels to go certain mailing lists? filing out an issue template on a weekly report goes to a mailing list? 

put in contributor/chair-and-techlead docs

**Comment by Nivedita-coder** [comment]
Hi @parispittman , I would like to work on this issue, can you help me with what I need to add and where? Thanks
