### ISSUE TITLE
Rewrite the community values statement

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/community#5408]
## Description

The [community values statement]( https://git.k8s.io/community/values.md) needs a rewrite.

## Example

Consider the first sentence:

> Kubernetes Community culture is frequently cited as a substantial contributor to the meteoric rise of this Open Source project.

- Uses evocative rather than descriptive language
- Uses passive voice
- Makes an uncited claim

This could be rewritten:
> The culture of Kubernetes contributes substantially to the project's success.

This suggested edit:
- Uses active voice
- Uses descriptive rather than evocative language
- Makes a verifiable claim

## Other improvements

Other grammatical elements also need revision. (For example, commas require review.)

## Out of scope

Changing community values is out of scope for this issue.

## Required skills

This issue requires advanced written English skills, but would otherwise make a good first issue.

For more information, see the [Kubernetes documentation style guide](https://kubernetes.io/docs/contribute/style/style-guide/).

/sig docs
/area community-management
/good-first-issue

**Comment by Nivedita-coder** [comment]
I would like to work on this issue.

**Comment by sladyn98** [comment]
I would like to work on this issue too :) if two can work on it together

**Comment by coderfornow** [comment]
I could also work on this issue.

**Comment by mrbobbytables** [comment]
@coderfornow theres an open PR from @sladyn98 already.^^;;;

---
I'm going to go ahead and remove the good first issue as theres already a PR in flight 👍 
/remove good-first-issue
