### ISSUE TITLE
mutatingwebhook apply patch failed

### ISSUE THREAD

**Issue by Davidrjx** [kubernetes/community#5410]
when applying patch below, an internalError occur where patch and related looks like
```
Patch:
patchOps = append(patchOps, patchOperation{
			Op:   "add",
			Path: "/spec/nodeSelector",
			Value: map[string]string{
				"local.cloud.io/key": "eden",
			}})

Error:
Error from server (InternalError): Internal error occurred: Internal error occurred: Unexpected kind: unknown
```
while patchObj is nil, no patch no error above, anybody faced with same issue and any solution or idea?

**Comment by mrbobbytables** [comment]
@Davidrjx this is a meta-repo for management of the kubernetes contributor community, issues like that won't get looked at here =/
I suggest asking on the [api-machinery](https://github.com/kubernetes/community/tree/master/sig-api-machinery#contact) or [kubernetes-dev](https://groups.google.com/g/kubernetes-dev) mailing list or asking in slack.

/close

**Comment by Davidrjx** [comment]
@mrbobbytables yes, thank you for answer. But my problem had been resolved as incorrect json patch syntax.
