### ISSUE TITLE
REQUEST: New Slack channel sig-security-external-audit

### ISSUE THREAD

**Issue by reylejano** [kubernetes/community#5424]
**GitHub Username:**
@aasmall 
@tabbysable 

**Slack Username:**
@Aaron Small
@Tabitha Sable

**What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?**
Private Channel

**Name of Requested Resource:**
sig-security-external-audit

**Description of Request:**

SIG Security's subgroup for a third-party security audit for Kubernetes is publishing an RFP for an external security audit. Subgroup members would like a private Slack channel to discuss proposals that meet vendors' confidentiality requirements. 

/sig security

**Comment by mrbobbytables** [comment]
I am +1
For some context there was a previous channel created for this purpose.

**Comment by tabbysable** [comment]
+1 from me, too. It will be hard to deal with this sensitive info properly using only public comms.

**Comment by coderanger** [comment]
+1, risks early disclosure of issues before they can be fixed to leave this public

**Comment by mrbobbytables** [comment]
This has been created 👍  @tabbysable has been invited to start - there are two aaron smalls in slack, so I'll leave it to @tabbysable  to add the right one^^;;;
/assign
/close
/milestone v1.21
