### ISSUE TITLE
Validate sigs.yaml resources created by other tools

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#5425]
The dream: updating sigs.yaml would result in automatic create/deletion of resources managed by other tooling, e.g.
- GitHub labels
  - tool: label_sync
  - repo: kubernetes/test-infra
- GitHub teams (peribolos)
  - tool: peribolos
  - repo: kubernetes/org
- Slack channels (tempelis)
  - tool: tempelis
  - repo: kubernetes/community

The reality: just because something is in sigs.yaml doesn't make it so.  Humans need to remember to make PR's to other repos.

As a start, it would be helpful to have a periodic prowjob that can report on which of these resources exist in sigs.yaml but are missing in reality.  It could:
- read latest sigs.yaml
- compare labels against https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.yaml
- compare teams against contents of https://github.com/kubernetes/org/tree/master/config
- compare slack channels against contents of https://github.com/kubernetes/community/tree/master/communication/slack-config
- fail with output of which resources are missing
- send e-mail alert to contribex via testgrid

/kind feature
/sig contributor-experience

**Comment by spiffxp** [comment]
I filed this because I noticed the `wg/reliability` label was missing (original PR to create: https://github.com/kubernetes/community/pull/5127)

**Comment by mrbobbytables** [comment]
One other item I would like to see is automatic updating of the leads mailing list and subsequent sig-foo-leads lists.

**Comment by spiffxp** [comment]
/help
I'm willing to help provide reviews and guidance on how to write a prowjob that does this

My suggestion would be to extend the generator app to optionally take paths to local copies of the files/directories mentioned above, and add a flag/verb for validation against those paths if provided

FYI @nikhita if you have other suggestions

**Comment by spiffxp** [comment]
>One other item I would like to see is automatic updating of the leads mailing list and subsequent sig-foo-leads lists.

This is going to require that email addresses find their way into sigs.yaml.  

And movement of the sig-foo-leads lists to kubernetes.io groups.  I would like to see group approval sharded (same model as kubernetes/test-infra job configs and kubernetes/org team configs) before we lean too heavily on groups.  One difference: creation/deletion of groups should require root approval (but membership additions can be fully delegated)

**Comment by spiffxp** [comment]
another good fit for this: validate that owners files listed for subprojects actually exist (ref: https://github.com/kubernetes/community/issues/4125)

**Comment by bunniseng** [comment]
Hey @spiffxp 

Is this something I could pick up? I'm new to the community, happy to get my hands dirty with a bit of direction.

**Comment by spiffxp** [comment]
@bunniseng sure! if you comment `/assign` the issue will get assigned to you

Comparing the labels might be the easiest place to start, since it's a single file.  If you can write something that does that comparison, outputs diffs, and exits non-zero if there are diffs... it's pretty straightforward to turn that into a prowjob.

The slack channels and teams are going to require walking either remote APIs (source of actual configuration), or directory trees (source of intended configuration).  I would recommend vetting against source of intended configuration.

Personally I would implement the directory tree walking by pre-cloning those repos someplace, and passing the locations of those paths to the tool, rather than having the tool try to be smart and auto-clone the repos or walk the hierarchy remotely on its own.

**Comment by AvineshTripathi** [comment]
@spiffxp can we have a program running that compares both the .yaml file at a periodic interval and and see for missing labels in the label.md file and if the condition satisfy we can can do the needful change

**Comment by AvineshTripathi** [comment]
forgot about this ;) 
/assign

**Comment by daemon1024** [comment]
1. Where will this job/code reside in?
2. How do we import constructs from generator and label_sync tools?
	We were testing things out by building a local tool and we needed structures to read out the YAML files like

**Comment by AvineshTripathi** [comment]
@nikhita Isn't this issue resolved with the addition of the `maintainers` tool, or there is still some features left to be added in the tool to resolve this issue

**Comment by nikhita** [comment]
@AvineshTripathi the maintainers tool needs to be integrated into a prow job to inform when sigs.yaml gets out of date. @RaghavRoy145 is working on this.
