### ISSUE TITLE
Update YouTube guidelines

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#5451]
The [Youtube Guidelines](https://github.com/kubernetes/community/blob/master/communication/youtube/youtube-guidelines.md) currently require three updates to bring them up-to-date
1) The list of groups with splain enabled needs to be updated removing SIG PM and WG LTS
2) The [Uploading Guidelines](https://github.com/kubernetes/community/blob/master/communication/youtube/youtube-guidelines.md#uploading-guidelines-for-collaborators), needs to have a note added that both public and private steering meeting recordings should be made public.
3) There is at least one broken link that needs to be fixed

/sig contributor-experience
/area community-management
/milestone v1.21
/good-first-issue
/help wanted

**Comment by viviandsilva** [comment]
Hi! I'd like to give a try on this issue

**Comment by MehulKChaudhari** [comment]
Hey @viviandsilva, If you aren't doing this can I please take this issue forward?

**Comment by viviandsilva** [comment]
Hey @MehulKChaudhari, I am doing this

**Comment by MehulKChaudhari** [comment]
Okay, All the best

**Comment by sharmapulkit04** [comment]
I would also like to work on this issue :)

**Comment by sharmapulkit04** [comment]
@mrbobbytables I am not sure what to update when you said
>3. There is at least one broken link that needs to be fixed. 
>

I checked all the links, and all seems to be working, except SIG PM and WG LTS. And after removing them
>1. The list of groups with splain enabled needs to be updated removing SIG PM and WG LTS.
>
there are no more broken links in the file.

**Comment by mrbobbytables** [comment]
https://github.com/kubernetes/community/blob/master/communication/youtube/youtube-guidelines.md#moderator-expectations-and-guidelines

The line:
```
Moderators should adhere to the general Kubernetes project
[moderation guidelines]
```

This is a markdown reference link, but there is no link at the bottom of the doc pointing to the correct file. It needs this at the bottom of the file with the other reference links:
```
[moderation guidelines]: /communication/moderation.md
```

**Comment by sharmapulkit04** [comment]
Didn't saw that one. Thanks !!
