### ISSUE TITLE
[Idea] Pronouns field for Slack

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/community#5454]
Hey y'all, is it possible to enable a pronouns field for Slack?
I currently just do this in my display name, but it would be cool to have a field to promote inclusivity!

(Apologies if there's already an issue for this; I couldn't find anything on a quick search.)

cc: @kubernetes/sig-contributor-experience-leads

**Comment by jberkus** [comment]
I've confirmed that this is technically possible, and it sounds like a good idea to me.  I'd like +1s from other Slack admins before I go ahead.

**Comment by jberkus** [comment]
tag: @mrbobbytables @coderanger @munnerz

**Comment by parispittman** [comment]
+1

**Comment by mrbobbytables** [comment]
+1

**Comment by jberkus** [comment]
Leaving this open for 24 hours just so that folks can point out issues, if there are any.

**Comment by nikhita** [comment]
+1

**Comment by jberkus** [comment]
done!  Thanks for thinking of this.
