### ISSUE TITLE
Document how to create in-tree plugins

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/community#5466]
We have recently changed how plugin args are parsed, defaulted and (#90859) validated.

The process is more complicated than most standard API uses.
We need to document this, probably in a new `pkg/scheduler/framework/plugins/README.md`.

Details for out-of-tree plugins can go to https://kubernetes.io/docs/concepts/scheduling-eviction/scheduling-framework/

/kind documentation
/sig scheduling
/help

**Comment by aliakbar-hemmati** [comment]
Hi, 
I see a merged commit here. Is there still sth to be done for this issue?

**Comment by alculquicondor** [comment]
This section still needs to be written https://github.com/kubernetes/community/blob/master/contributors/devel/sig-scheduling/scheduler_framework_plugins.md#creating-a-new-in-tree-plugin

However, this requires some previous experience writing plugins
