### ISSUE TITLE
REQUEST: New communication about upcoming Data on Kubernetes presentation

### ISSUE THREAD

**Issue by celanthe** [kubernetes/community#5467]
**What do you want send out?** 

If possible I would love a tweet/signal boost amplifying the presentation that myself and Savitha (on twitter at @coffeeartgirl) are giving on 2/9/21 at 9:00 AM PST _The Kubernetes Contributor Experience and Fighting Impostor Syndrome_.

Here is the suggested copy: Let's contribute! @kiran_oliver from @Camunda and @coffeeartgirl are presenting at the @DoKCommunity meetup 2/9/21at 9:00 AM PST about getting involved in open source projects! Sign up here https://meetup.com/Data-on-Kubernetes-community/events/275961632/ #dok #k8s #opensource

If it's also possible to add it to the K8s Community Calendar that would be great. The registration link is [here](https://www.meetup.com/Data-on-Kubernetes-community/events/275961632/)

Thank you so much!! 

If this is not allowed, please let me know and I'll close this issue ASAP.

**Comment by mbbroberg** [comment]
Thanks @celanthe! We're discussing in today's meeting whether it fits into our charter to cover a vendor-specific events. While it's not directl covered in the [social guidelines](https://github.com/kubernetes/community/blob/master/communication/marketing-team/social-guidelines.md), SIG ContribEx and our subgroup agree that it's best to avoid vendor amplification on the channel.

@mrbobbytables @kaslin @rajula96reddy we also mentioned: 

- Likes are a signal we only want to use when k8scontirbutors or kubernetes account are directly mentioned or tweets show appreciation for them. 

And thank you, Rin, for helping us think through this work! You sparked an important conversation :smile:
