### ISSUE TITLE
Fix "Ephemeral Containers KEP" link

### ISSUE THREAD

**Issue by nicolas-g** [kubernetes/community#5491]
The URL link for `Ephemeral Containers KEP.` is invalid in https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/troubleshoot-running-pods.md

**Comment by mrbobbytables** [comment]
@nicolas-g design-proposals are in an archived state and are there for historical purposes only. Please see the readme for more info:
https://github.com/kubernetes/community/tree/master/contributors/design-proposals#kubernetes-design-documents-and-proposals

/close
