### ISSUE TITLE
Consider a more discoverable URL for the gubernator

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#550]
From scanning the contributor docs it seems https://k8s-gubernator.appspot.com/pr isn't mentioned, someone kind of has to tell you it exists. I debated just adding links to it in the existing docs but I was thinking as a prerequisite to make it a URL that anyone can remember, something like kubernetes.io/pr or pr.kubernetes.io. 

Something that would make it easy to put on a slide/business card for contributors to remind each other to do reviews, it would make it easier to socialize if it was something rememberable. We could then ensure that we link to it from our contributor docs, workflow documents, etc.

**Comment by jdumars** [comment]
Until a better solution comes along, I setup http://k8s.reviews

**Comment by cblecker** [comment]
The go.k8s.io redirects are in code here, if we wanted to decide on something and make a PR:
https://github.com/kubernetes/k8s.io/blob/master/k8s.io/configmap-nginx.yaml#L193-L208

**Comment by ixdy** [comment]
thanks to @dims, we now have https://go.k8s.io/pr-dashboard.
