### ISSUE TITLE
REQUEST: New *private* Slack channel - product-security-committee

### ISSUE THREAD

**Issue by tallclair** [kubernetes/community#5528]
**GitHub Username:** @tallclair 
**Slack Username:** tallclair

**What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?**
Private channel for @kubernetes/product-security-committee use

**Name of Requested Resource:**
#product-security-committee

**Description of Request:**
Private channel for @kubernetes/product-security-committee to coordinate vulnerability response (separate from #security-release-team). Members should be the same as the product-security-committee usergroup (https://github.com/kubernetes/community/blob/master/communication/slack-config/usergroups.yaml#L41).

I volunteer to act as moderator and ensure that the [code of conduct](https://github.com/kubernetes/community/blob/master/code-of-conduct.md) is followed.

All members of the channel must enable 2-factor authentication. I will follow up this request with an update to the [PSC documentation](https://github.com/kubernetes/security) outlining our use and requirements for slack. 

/cc @jeefy @parispittman @kubernetes/product-security-committee

**Comment by jeefy** [comment]
+1 from slack admin

**Comment by parispittman** [comment]
+1 channel has been created; members of psc have been added and I've removed myself 

/close
