### ISSUE TITLE
Document remaining kubernetes/kubernetes hack/verify* tests

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#5532]
Part of developer guide audit for sig-testing: https://github.com/kubernetes/community/issues/5239

Follow-on to https://github.com/kubernetes/community/pull/5349 (ref: https://github.com/kubernetes/community/pull/5349#discussion_r575029064)

We lack documentation for the sundry verify tests that are used to block merge or release of kubernetes/kubernbetes.  We should ensure these tests are documented in [contributors/devel/sig-testing/verify-tests.md](https://git.k8s.io/community/contributors/devel/sig-testing/verify-tests.md).

The following merge-blocking verify tests are run as part of `pull-kubernetes-verify`
- [x] verify-api-groups (https://github.com/kubernetes/community/pull/5829, thanks @pravarag)
- [x] verify-bazel (https://github.com/kubernetes/community/pull/5864, @pravarg)
- [x] verify-boilerplate (https://github.com/kubernetes/community/pull/5864, @pravarag)
- [x] verify-cli-conventions (https://github.com/kubernetes/community/pull/5864, @pravarag)
- [x] verify-codegen (https://github.com/kubernetes/community/pull/5864, @pravarag)
- [ ] verify-conformance-requirements
- [ ] verify-description
- [ ] verify-flags-underscore
- [ ] verify-generated-device-plugin
- [ ] verify-generated-docs
- [ ] verify-generated-files
- [ ] verify-generated-kms
- [ ] verify-generated-kubelet-plugin-registration
- [ ] verify-generated-pod-resources
- [ ] verify-generated-protobuf
- [ ] verify-generated-runtime
- [ ] verify-generated-stable-metrics
- [ ] verify-generated-swagger-docs
- [ ] verify-gofmt
- [ ] verify-govet
- [ ] verify-import-aliases
- [ ] verify-import-boss
- [ ] verify-imports
- [ ] verify-internal-modules
- [ ] verify-no-vendor-cycles
- [ ] verify-openapi-spec
- [ ] verify-pkg-names
- [ ] verify-prerelease-lifecycle-tags
- [ ] verify-publishing-bot
- [ ] verify-readonly-packages
- [ ] verify-shellcheck
- [ ] verify-spelling
- [ ] verify-staging-meta-files
- [ ] verify-staticcheck
- [ ] verify-test-code
- [ ] verify-test-featuregates
- [ ] verify-test-images

There are also additional tests that are run as part of release-blocking verify jobs:
- [ ] verify-external-dependencies-version
- [ ] verify-generated-files-remake
- [ ] verify-readonly-packages
- [ ] verify-typecheck
- [ ] verify-typecheck-dockerless
- [ ] verify-typecheck-providerless
- [ ] verify-vendor
- [ ] verify-vendor-licenses

/priority important-longterm
/kind documentation
/sig testing
/help

**Comment by pravarag** [comment]
@spiffxp I would like to work on this issue. Though I'm getting started with `sig/test-infra` but I beleive this will help me build my knowledge around it.

**Comment by championshuttler** [comment]
@spiffxp I also like to contribute

**Comment by pravarag** [comment]
@championshuttler you can work on this issue since I haven't started working on it yet.

**Comment by spiffxp** [comment]
/assign @pravarag 
go for it! I'll leave the /help tag on since you said you haven't started

**Comment by spiffxp** [comment]
/assign @championshuttler 
same thing

**Comment by pravarag** [comment]
@spiffxp apologies for not able to put anything on my assigned part under this issue from past two months. But I've started looking on it again and will surely update soon.

**Comment by pravarag** [comment]
@spiffxp, I've created a PR with documentation for `verify-api-groups` test for your review. I'll progress with changes for other verification tests documentation as well meanwhile.

**Comment by pravarag** [comment]
@spiffxp one query here: if I'm working on creating documentation for more than one `verify-*` tests, so shall I include those in same PR or we are expecting a PR for each test separately here?

**Comment by spiffxp** [comment]
Whatever is easier for you. If the same same pr, one commit per would be appreciated.

**Comment by spiffxp** [comment]
/reopen 
Should not be closed until all verify tests are documented

**Comment by pravarag** [comment]
I've created a draft PR while I'm adding documentation for various `verify*` tests. Will open it for review once done.

**Comment by pravarag** [comment]
Hi @spiffxp , this issue is closed by mistake I guess as still many scripts' documentation needs to be added 😃

**Comment by pravarag** [comment]
@spiffxp I've added another PR which covers two more scripts. I recently used those two (structured-logging, verify-gofmt) scripts while working on another issue so had some idea around it 🙂 Kindly review.

**Comment by pravarag** [comment]
Hi @spiffxp @BenTheElder I've opened one more PR [here](https://github.com/kubernetes/community/pull/6127) for your review. Kindly let me know if any changes are required for the same.
