### ISSUE TITLE
Update community platform docs with moderation guidelines

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#5541]
### Problem Statement

Our communication property guidelines explain how to moderate content and when it should be reported, but broadly do not offer any other guidance of how moderations should respond. For example, under what conditions would you outright ban a person vs when would you reach out.

### Proposed Solution

Update our moderation guides to include some general guidelines or rules regarding what type of response is appropriate for certain actions or behaviors.

---

/sig contributor-experience
/area community-management
/milestone v1.21

**Comment by Haimantika** [comment]
Hi @mrbobbytables, I would love to work on this. I just got introduced to the community, so this might take a while, we can expect some output from me within mid of August.
