### ISSUE TITLE
Document feature flag lifecycle

### ISSUE THREAD

**Issue by ehashman** [kubernetes/community#5542]
The API lifecycle is well documented, but the feature flag lifecycle, which is related but not strictly coupled to it is not. It would be great to document the conventions for alpha, beta, and GA feature flags, how to add and graduate them, what the conventions for locking to true mean, etc.

This issue sparked by the conversation in https://github.com/kubernetes/kubernetes/pull/99158#issuecomment-783597035

/sig architecture
/area developer-guide
/assign @dims

**Comment by ehashman** [comment]
/remove-lifecycle stale

ping @kikisdeliveryservice :)

**Comment by kikisdeliveryservice** [comment]
PR is still waiting final review - I'm going to bring it up in meeting.
