### ISSUE TITLE
incident management process for comms platforms

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#5546]
we should have a comms process for when things go not great and what not great means. Ideally, we should email moderators@ or contribex mailing list with a basic:
- when
- what 
- current status
- help needed

normal guidelines to be used when incidents are happening but this would be addressing the post/during if its long.

**Comment by mrbobbytables** [comment]
related to #5541

**Comment by markyjackson-taulia** [comment]
I will have a draft up in a few days for this

**Comment by AvineshTripathi** [comment]
Hey @markyjackson-taulia what is the current status of the draft. Is there any way I can help
