### ISSUE TITLE
Requesting suggestions from GH Management for prow extension

### ISSUE THREAD

**Issue by gkarthiks** [kubernetes/community#5564]
### Hi GitHub Management Team,

Based on the discussion in the **WG Naming** [here](https://groups.google.com/u/3/g/kubernetes-wg-naming/c/D2fqUWt-H00), this issue is to request suggestion/comment on the following proposal.

### Problem Statement:
There are few terms that are considered offensive/biased that appear or enter into Kubernetes world only via issues(or most commonly via issues). These are created by all the stakeholders of Kubernetes.

### Proposed Solution:

Based on the above-linked GG discussion, we are requesting suggestions/comments on extending the [Prow Plugin](https://github.com/kubernetes/test-infra/tree/master/prow/plugins) that will start soon after the issue is created and scans the content of the issue. If there are any offensive/biased terms mentioned in the content of the issue, a comment will be created addressing the author stating that they need to address those terms with alternatives.

PS: We already do this in K8s and CNCF Slack.

### Addressing to:

- [GH Management](https://github.com/kubernetes/community/blob/master/github-management/OWNERS)
  - @cblecker
  - @spiffxp
  - @fejta
  - @idvoretskyi
  - @justaugustus
  - @mrbobbytables
  - @nikhita

**Comment by nikhita** [comment]
@kubernetes/wg-naming-leads -- can you please confirm if you'd like to go ahead with this feature?

From the contribex side, I will add it to next meeting's agenda.

**Comment by mrbobbytables** [comment]
While I approve of the intent behind this. I don't think it'll have the intended impact. People don't look at the messages from our bots as it is :(

**Comment by gkarthiks** [comment]
@nikhita  @celestehorgan @mrbobbytables  so what should we do? just drop this idea and see better options in future? Looking for some direction guide here pls.

**Comment by nikhita** [comment]
> @nikhita @celestehorgan @mrbobbytables so what should we do? just drop this idea and see better options in future? Looking for some direction guide here pls.

I agree with @mrbobbytables -- we have too many bot comments today (related #3621) and I don't think this would have the intended impact either.

**Comment by mrbobbytables** [comment]
>  so what should we do? just drop this idea and see better options in future? Looking for some direction guide here pls.

I would drop for now, or potentially freeze the idea. I think there are other areas where we should focus our efforts for greater impact. There are a lot of repos that still need to be migrated from master -> main, and effort within various projects to switch away from non-inclusive language.

**Comment by gkarthiks** [comment]
As per the suggestions from @justaugustus in the WG Monthly meeting(May 17th, 2021), I will take this idea to the [INI](https://inclusivenaming.org) group and check how are they approaching this in a broader spectrum. 

I will circle back with the findings/approach from there, document it here, and will close this issue. No further actions are needed here. So assigning it to myself.

/assign gkarthiks
