### ISSUE TITLE
Katacoda Scenario(?) for a brand new developer - basic tutorial

### ISSUE THREAD

**Issue by dims** [kubernetes/community#5576]
Other CNCF communities maintain katacoda courses, example:
https://github.com/thanos-io/thanos/issues?q=is%3Aissue++katacoda+

There are a lot of katacoda scenarios for kubernetes in general as a end user:
https://katacoda.com/kubernetes

ASK:
We need one where someone who has just starting out in kubernetes and wants to try their hand at making a patch and testing it.

Basic Steps:
- Create a fork on github
- Install basic tools like `go`, `make` (`build-essential` on ubuntu)
- Checkout their personal fork 
- Add kubernete/kubernetes as a remote
- Make some simple change
- Run basic developer workflows like 
  * Run a test using go
  * Run some verification and update scripts (hack/verify-gofmt.sh, hack/verify-typecheck.sh) 
- Create a branch and submit a PR 

Optional : 
- Show how to start a `kind` cluster with the updated code
- Update an existing PR to incorporate any changes during review

Why do we need to doing:
- We have a *LOT* of documentation, it's hard to figure out what one has to do
- Videos / Recordings help a bit, but there is no substitute for trying things yourself
- There is a lot of beginners who have a basic laptop (say windows) and do not have access to a beefy linux box/vm. So give them a chance to participate/learn

Possible issues:
- Not sure if Katacoda environments can support the CPU/Mem, we can hit up folks if we run into issues.

**Comment by dims** [comment]
Idea thanks to conversations with  @soniasingla @LappleApple @darshnadas

**Comment by soniasingla** [comment]
hey @mrbobbytables! Want to collaborate on this with me? It would be a great addition to our developer community! 

I have some experience in creating Katacoda tutorials. https://katacoda.com/thanos/courses/thanos/2-lts I created this last summer, it came out to be really helpful :)

**Comment by saiyam1814** [comment]
I think this is great @dims and would be useful for the community!
There is a Kind scenario already -> https://www.katacoda.com/petermbenjamin/scenarios/kind
Kubernetes playground is also there, so we can over time actually create fully maintained Kubernetes Katakoda scenarios that we can use to teach other things as well

**Comment by mrbobbytables** [comment]
I did a quick test of trying to build kubernetes, but unfortunately the instance just dies when doing so. I don't think katacoda can cope with our build requirements:
- 8GB of RAM
- 50GB of free disk space

If you want to try, I just went with vanilla instance and went through the dev procedure here to install our reqs and 
https://github.com/kubernetes/community/blob/master/contributors/devel/development.md#building-kubernetes-on-a-local-osshell-environment

Then ran `make all`

**Comment by dims** [comment]
@mrbobbytables `make all` may be a very heavy hammer. if we can do

- `make kubelet` (like individual pieces)
- `make generated_files`
- hack/verify-* scripts (especially typecheck)

that should give us a decent start. `make quick-release` etc will be too heavy as well. hoping we can experiment with some low resource stuff at least for now

**Comment by dims** [comment]
cc @benhall

**Comment by BenHall** [comment]
@mrbobbytables thanks for the info. We do limit our free tier but the platform supports much larger instances. I will try in one of our large environments and see what happens.

**Comment by mrbobbytables** [comment]
@BenHall Thanks! Are the instance types/resource allocations documented anywhere? I was trying to find it earlier, but didn't have any luck^^;;

**Comment by BenTheElder** [comment]
re: kind, LMK if there's any issues 🙃 
re: `make quick-release` is heavy: https://github.com/kubernetes/kubernetes/issues/99517

**Comment by BenHall** [comment]
@mrbobbytables @dims I took a look today. With slightly CPU and Memory (8 cores, 8Gb) everything looked to build successfully within an environment, even `make all`. 

I ran `make test` and most appear to work but some failed. Here is the output https://gist.github.com/BenHall/2896bf3012282deaae7f58508bfa7b8e

Anything failing due to Katacoda?

**Comment by dims** [comment]
@BenHall thanks! i see 2 failures, please log an issue about them so we don't forget. i think this is fine, you don't have to dig into it yet. we are reworking a bunch of stuff (rip bazel, bump to golang 1.16) so i'd expect some hiccups right now.

@BenHall can you please check if this works?
```
kind build node-image
kind create cluster --image kindest/node:latest
```
documented here : https://github.com/kubernetes-sigs/kind/blob/master/README.md#L87

a really stretch goal would be this:
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#running-conformance-tests-with-kind

**Comment by BenHall** [comment]
@dims Looks like the node-image can build. It took 5mins, not sure what the normal time is.

Create Cluster however failed

```
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
Command Output: I0305 15:13:17.371346     210 initconfiguration.go:246] loading configuration from "/kind/kubeadm.conf"
[config] WARNING: Ignored YAML document with GroupVersionKind kubeadm.k8s.io/v1beta2, Kind=JoinConfiguration
I0305 15:13:17.378564     210 kubelet.go:259] setting the KubeletConfiguration cgroupDriver to "systemd"
```

The healthcheck appears to timeout after a while. 

```
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.
```

**Comment by BenTheElder** [comment]
If we're building Kubernetes sources at HEAD we need kind installed from HEAD. Kubeadm made a breaking change in 1.21 (unreleased) which kind at HEAD handles.

**Comment by BenHall** [comment]
@BenTheElder that would be it! Thanks, will give it a go.

**Comment by BenTheElder** [comment]
Also I'm pretty sure for the contributor summit at least what we've done is used stable releases of both (checkout to kubernetes release-1.X branch, use latest kind stable release) to avoid surprises on the day of the session, that may be a good idea here (though might be nearly as tricky to do on a rolling basis?)

We also have pre-compiled binaries used by CI here: https://kind.sigs.k8s.io/dl/latest/linux-amd64 (not really advertised, since if you're _not_ developing Kubernetes we'd prefer that people stick to a stable release).
Kubernetes PRs download and run a compressed copy along with an e2e script https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz (~2MB vs ~7MB).

**Comment by alisondy** [comment]
@hh @heyste fyi re: ncw build and test

**Comment by eddiezane** [comment]
@napcs @katjuell @hazel-nut this might be a good place to contribute if DO folks are interested.

**Comment by dims** [comment]
@BenHall Any updates? please let us know.

**Comment by dims** [comment]
Some additional notes for someone who may work on this one day.

```
put yourself in the shoes of someone (say a student), who does not have a good enough machine to learn how to build and run k8s. with this now you have an option to try things out in a limited fashion. So for this person, they don’t know anything about kubernetes and just showed up for a event (new contributor workshop), we have to walk them through in detail what it takes to build and run kubernetes. the script is something Ben documented as possible steps to get to a working environment. we need to use that and turn that into a detailed set of steps that anyone with very limited knowledge of open source (say even a first year student) can follow along to get to the point where they can try something.

Note that this is the first step, next step would be to show them how they can tweak kubernetes code to be able to fix a bug, run tests, ensure that they can recreate a scenario (before and after their own fix), so they can then contribute to kubernetes.

i think the first thing for you to do here is to try this yourself (don’t run the script as-is) in an incremental fashion and see if you understand exactly what is happening and then being able to tweak it if necessary for newer kubernetes versions(?) or make it easier than what’s in the script. then finally writing detailed notes for newbies.
```

https://gist.github.com/BenHall/b9a546797797fec6492a1a7d90b31ef3

**Comment by dims** [comment]
some chat with @yashikabadaya 

```


Yashika Badaya  9:29 AM
Hi dims,
Wanted to confirm a few things -
Are we planning to checkin this script- https://gist.github.com/BenHall/b9a546797797fec6492a1a7d90b31ef3 in k8s repo or will we directly provide same link to users.
Do we expect users to create cluster on their own machines? I didn’t understand use of https://beta.katacoda.com/ben_hall/scenarios/build …
beta.katacoda.combeta.katacoda.com
Build | ben_hall | Katacoda (26 kB)

dims:palm_tree:  9:34 AM
we will turn it into a doc/markdown with code snippets. We will not be checking in the script as-is. Folks an copy/paste from the doc.
the katacoda is a website where they can try the stuff out from step 1. Most students do not have a big enough box to try things and the website provides that. (it’s just a terminal where you can paste and run things … running in a browser)
9:36
you can use hackmd.io to draft the doc/markdown (it creates a url that you can share so i can peek and help you edit it as we go along)

Yashika Badaya  10:33 AM
ok thanks
10:33
btw that script is running from past 1/2 hr
10:33
currently its running tests

dims:palm_tree:  10:34 AM
got it. we need to break it into smaller chunks so we can tell a story around each step.
10:35
also we may want to to run a single test at the end, so folks are not stuck :slightly_smiling_face:

Yashika Badaya  10:43 AM
can we run some basic test?
10:43
something as simple as pod bring up and bring down test? That would help folks understand how it looks like I think (edited) 

dims:palm_tree:  10:44 AM
exactly

Yashika Badaya  10:44 AM
do have such test already present?

dims:palm_tree:  10:54 AM
should contain last line of the log https://github.com/kubernetes/kubernetes/blob/95ff56c201ae7ccdcd1f01bc36646d1d6496483a/test/e2e/kubectl/kubectl.go#L615-L627
you can run it using
./_output/bin/e2e.test -context kind-kind -ginkgo.focus="should contain last line of the log" -num-nodes 2
You can see the test grid for just this single test in one of the CI jobs
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&include-filter-by-regex[…]should%20contain%20last%20line%20of%20the%20log

test/e2e/kubectl/kubectl.go:615-627
        ginkgo.It("should contain last line of the log", func() {
            podName := "run-log-test"

            ginkgo.By("executing a command with run")
            framework.RunKubectlOrDie(ns, "run", podName, "--image="+busyboxImage, "--restart=OnFailure", podRunningTimeoutArg, "--", "sh", "-c", "sleep 10; seq 100 | while read i; do echo $i; sleep 0.01; done; echo EOF")
Show more
<https://github.com/kubernetes/kubernetes|kubernetes/kubernetes>kubernetes/kubernetes | Added by GitHub (Legacy)

Yashika Badaya  11:00 AM
ok
Yashika Badaya has notifications turned off
```

**Comment by Debanitrkl** [comment]
I have created the katacoda scenario [here](https://www.katacoda.com/debanitrkl ), could anyone please review it. 
cc @MadhavJivrajani @dims

**Comment by dims** [comment]
@Debanitrkl please send an email to sig-contribex and sig-docs about creating a github repository like the one mentioned in the url above and let us see who can help. Also add it to their meeting agenda please.

**Comment by dims** [comment]
see "Repository creation/migration" in https://github.com/kubernetes/org/issues/new/choose (no need to involve steering, you need a SIG to own this)

**Comment by Debanitrkl** [comment]
The [repository](https://github.com/kubernetes-sigs/contributor-katacoda) for the katacoda-scenario has been created and the first basic tutorial is prepared, so closing the issue.
/close

**Comment by Debanitrkl** [comment]
/reopen
For LFX Mentorship applicants to go through the discussion on this issue and get a brief idea of the motive behind the [contributor-katacoda](https://github.com/kubernetes-sigs/contributor-katacoda).
