### ISSUE TITLE
Rename of PSC

### ISSUE THREAD

**Issue by lukehinds** [kubernetes/community#5596]
We recently discussed the name of the PSC / Product Security Committee  and if best describes what we do / could lead to confusion. The particular part is "Product" as there is no Product as such (that would be an element for downstream). 

A more suitable name could be 'Security Response Committee' or 'Vulnerability Response Committee', the outcome of this discussion on our recent PSC meeting was that we should take this to the steering committee:

Tagging sc members:

@cblecker
@derekwaynecarr 
@dims
@liggitt
@mrbobbytables
@nikhita
@parispittman

**Comment by dims** [comment]
cc @kubernetes/sig-security-leads

**Comment by dims** [comment]
@lukehinds please go ahead and open a PR against sigs.yaml:
https://github.com/kubernetes/community/blob/master/sigs.yaml#L3033-L3077

and drop an email to steering@k8s.io to approve. will force us to do stuff :) once that's approved, we can start making changes in other places. please give a heads up to related sigs as well.

**Comment by lukehinds** [comment]
cc @kubernetes/product-security-committee

**Comment by tabbysable** [comment]
+1 (with my SIG Security hat on)

I like the "Security Response Committee" suggestion, as PSC isn't necessarily limited to k8s vulns.

**Comment by ehashman** [comment]
Can this be closed now that the PRs above have merged?
