### ISSUE TITLE
contributors/devel/sig-testing/e2e-tests.md references deprecated script

### ISSUE THREAD

**Issue by RobertKielty** [kubernetes/community#5626]
The below quoted section from  contributors/devel/sig-testing/e2e-tests.md looks out of date:

- references cluster/log-dump.sh which has moved and contains a deprecation notice
- references Jenkins builds
- the script does not work on local clusters

```
Debugging clusters
If a cluster fails to initialize, or you'd like to better understand cluster state to debug a failed e2e test, you can use the cluster/log-dump.sh script to gather logs.

This script requires that the cluster provider supports ssh. Assuming it does, running:

$ cluster/log-dump.sh <directory>
will ssh to the master and all nodes and download a variety of useful logs to the provided directory (which should already exist).

The Google-run Jenkins builds automatically collected these logs for every build, saving them in the artifacts directory uploaded to GCS.
```

**Comment by nikhita** [comment]
/sig testing

cc @BenTheElder

**Comment by BenTheElder** [comment]
yeah, log-dump.sh is not a great detail of testing, it's useful to know about but not really portable.

sorry this slipped through the cracks for me.
/remove-lifecycle stale
/help

**Comment by yuswift** [comment]
> yeah, log-dump.sh is not a great detail of testing, it's useful to know about but not really portable.
> 
> sorry this slipped through the cracks for me.
> /remove-lifecycle stale
> /help

What about using `kubectl cluster-info dump` to debug the cluster. If you agree with that, I'm willing to open a pr for the doc.
