### ISSUE TITLE
Default branch migration docs feedback

### ISSUE THREAD

**Issue by nikhita** [kubernetes/community#5636]
This issue is to track feedback about docs for migrating default branch from `master` to `main`. Docs are at:
- https://k8s.dev/rename
- https://github.com/kubernetes/community/blob/master/github-management/default-branch-migration.md

We've had feedback and ideas being shared in slack. This issue would help in collecting the feedback at a single place on GitHub.

Note - The docs are meant for repos who would like to try out default branch migration and provide feedback. There are a few outstanding items we'd like to complete (tracked in https://github.com/kubernetes/org/issues/2222) before announcing the docs more broadly.

cc @spiffxp @mrbobbytables @cblecker 

/sig contributor-experience
/area github-management

**Comment by nikhita** [comment]
Feedback from @BenTheElder (ref: [slack thread](https://kubernetes.slack.com/archives/C1TU9EB9S/p1615487742145000)):

```
bentheelder:dns:  5 days ago
first thing that comes up is under prerequesites it says:
Create an issue in your repo to track the branch rename. You can paste this checklist in the issue body.
Except you can't really copy and paste a checklist this from the page, and I haven't spotted the page source from the page (I'm sure I can find it, but it doesn't seem obvious) (edited) 

bentheelder:dns:  5 days ago
I think maybe instead we should consider linking to an issue template and encourage the template / checklist more strongly?

bentheelder:dns:  5 days ago
  Once the issue has been approved, send a notice to your SIG’s mailing list about the potential branch rename.

bentheelder:dns:  5 days ago
I understand the sentiment warning people, but are we sure we want an email per repo?
I think this is potentially trollbait and going to get a bit noisy as we ramp this up, versus active contributors can see the repo issue etc?

bentheelder:dns:  5 days ago
(especially for repos meeting the < 20 open PRs requirement, it seems OK to just do the thing and not worry too much about the disruption / blasting the SIG ML) (edited) 

bentheelder:dns:  5 days ago
It's also not possible to assign a team across orgs, I think.

bentheelder:dns:  5 days ago
  Once all non-disruptive tasks have been completed and disruptive tasks have been identified, assign the GitHub Management team (@kubernetes/owners) for approval.
```

**Comment by nikhita** [comment]
From @cblecker (ref: [slack message](https://kubernetes.slack.com/archives/C01672LSZL0/p1615842694011700)):

> I don't know if we have helper docs anywhere, but I finally flipped a table and figured out consistent git aliases for default branches without hardcoding: https://gist.github.com/cblecker/41ad288fcaaf6fbca8d2674b8b2534c8

**Comment by BenTheElder** [comment]
Thank you @nikhita!

**Comment by nikhita** [comment]
xref https://github.com/kubernetes/community/issues/5619 - Update branch rename guide with snippets to get default remote branch vs hardcode

**Comment by BenTheElder** [comment]
also `branch_protection` is not the real config field, it's `branch-protection` apparently (which is super config as other fields in prow typically are snake case)

https://github.com/kubernetes/test-infra/blob/7c62dd64c875ae223eee355ce1ba9a20a66ab42d/config/prow/config.yaml#L135

**Comment by BenTheElder** [comment]
KIND is done now, remaining feedback:

- A lot of the checklist mentions prow config, but github actions are in use in some subprojects and may also need updating and don't seem to have any callouts.

- I also noticed netlify will try to retain the `master` branch in the configured branches for build, but that doesn't seem like a big deal / wasn't difficult to cleanup.

**Comment by spiffxp** [comment]
re: https://github.com/kubernetes/k8s.io/pull/1792#discussion_r595494784, that would be good ol' https://github.com/kubernetes/test-infra/issues/7971 which kept aging out

**Comment by BenTheElder** [comment]
I _think_ recent projects have had a smoother time. A number are still tripping over prow config but otherwise doing OK I think.

**Comment by spiffxp** [comment]
/milestone v1.23
I've noticed more people going through the docs but haven't seen much feedback about whether there are points of confusion.

**Comment by spiffxp** [comment]
/priority awaiting-more-evidence
I've moved this to Blocked because I feel like we need to decide whether they're good enough, or we're just holding this open in perpetuity.

I feel like we need to consider how to more widely / easily federate people migrating their repos, and if we think the docs are good enough for that, then we're good to go.  This could look like opening up a placeholder issue in all repos that have yet to migrate, with the checklist as the issue body.

**Comment by mrbobbytables** [comment]
I think the current docs are good enough.

For what its worth  re:organizing people to migrate we were tossing an idea around to make it a community wide activity as part of the EoY contributor celebration. It'd be after the last release is cut and during the lull between releases. I do kinda like the idea of opening up issues in the repos ahead of time and assign to repo admins - give folks a little time to think about prepping for it with explicit links to instructions.

**Comment by mrbobbytables** [comment]
Following up on last comment, going to go ahead and close this out.

/close
