### ISSUE TITLE
Unclear definition of the --horizontal-pod-autoscaler-initial-readiness-delay flag

### ISSUE THREAD

**Issue by betaincao** [kubernetes/community#5637]
issues: https://github.com/kubernetes/website/issues/12657

If my Java pod takes 3 minutes to start up and uses a lot of CPU and I want to make sure this CPU burst is not taken into account by HPA for scale up, which value should I set to 3 minutes? --horizontal-pod-autoscaler-initial-readiness-delay? --horizontal-pod-autoscaler-cpu-initialization-period? Both? Does it also matter when the readinessProbe returns successfully?

https://github.com/kubernetes/website/issues/12657#issuecomment-546409137

**Comment by mrbobbytables** [comment]
Your question isn't likely to be answered here =/ This place is the meta repo for contributor community management. You will have better luck reading out to sig-autoscaling's [mailing list/meeting/slack channel](https://github.com/kubernetes/community/tree/master/sig-autoscaling#contact).

With that I'm going to go ahead and close this out. If you have any further questions please feel free to respond or ask in slack 👍 

/close
