### ISSUE TITLE
Remove `kind/design` label

### ISSUE THREAD

**Issue by LappleApple** [kubernetes/community#5641]
This label isn't needed anymore.

/kind cleanup
/area enhancements
/sig architecture

**Comment by mrbobbytables** [comment]
/assign @nikhita @cblecker @alisondy @mrbobbytables 
For further thoughts

As an FYI - at least within k/k this label isn't used that much anymore with the shift to KEPs.
I'm +1 for removal, @dims +1'ed the original thread in k/enhancements as well.

https://github.com/kubernetes/kubernetes/search?q=label%3Akind%2Fdesign&state=open&type=issues

**Comment by nikhita** [comment]
> As an FYI - at least within k/k this label isn't used that much anymore with the shift to KEPs.

Agree.

There are [68 open issues](https://github.com/search?p=1&q=org%3Akubernetes+label%3Akind%2Fdesign+is%3Aopen&type=Issues) in the kubernetes org with the label `kind/design`. Most of them are from k/k and k/kubeadm.

There are [52 open issues](https://github.com/search?q=org%3Akubernetes-sigs+label%3Akind%2Fdesign+is%3Aopen&state=open&type=Issues) in the kubernetes-sigs org with the label `kind/design`. Looking at the issues/PRs, it looks like they can be labelled with `kind/feature`. Most of them are from kind, kubadm, cluster-api and controller-runtime.

Before we remove the label entirely:
- someone should update all open issues/PRs with the `kind/design` label in kubernetes and kubernetes-sigs to ensure that they have the `kind/feature` label too.
- @dims -- can you confirm here that you are good with removing the label for k/k with the sig-arch hat on?

cc @BenTheElder @neolit123 @vincepri  - in case you have any concerns with removing the kind/design label, since it's being used in kind, kubadm, cluster-api and controller-runtime.

**Comment by neolit123** [comment]
i use this label on issues that require thinking,  discussion and proposal docs.
it can apply to bugs *and* features.

if you remove the `kind/design` label from k/k that's fine, but let's not remove it from non-k/k repo issues.
repo maintainers are free to add whatever `kind/*`, `area/*` labels they want.

**Comment by vincepri** [comment]
We have kind/design, but also kind/proposal. We truthfully only need a single one, although I know that Controller Runtime also uses this label. cc @DirectXMan12 @alvaroaleman 

The reason to have an additional label is for us to remind that we need a design document / proposal when a feature is too large to discuss in an issue.

**Comment by dims** [comment]
@nikhita +1 to remove `kind/design` from k/k

**Comment by MadhavJivrajani** [comment]
I can take this up /assign

From the conversation, I understand that this label should only be removed from k/k and `kind/feature` should be added to the currently open issues and PRs that have `kind/design` assigned to them. Please correct me if I'm missing something, thank you 😄

**Comment by BenTheElder** [comment]
I've been tagging `kind/design` on issues that do not have an agreed design yet, but I don't think it's been particularly effective.

**Comment by BenTheElder** [comment]
The KEP process is *far* too heavyweight for projects outside of Kubernetes but we don't yet have an easy pattern to standup a lighter process, a few projects do now anyhow, like cluster-api and minikube.

**Comment by spiffxp** [comment]
I would want to see a survey of which repos other than kubernetes/kubernetes use kind/design before blanket removing it from all repos

**Comment by spiffxp** [comment]
Given that the label sync tool doesn't allow denylisting of org-wide defaults this would be a pretty manual change today. We can do it, but I'm sure I see urgency to land this prior to v1.23

**Comment by mrbobbytables** [comment]
I think the general consensus was to remove it from k/k, but leave it as an option for others subprojects.

**Comment by MadhavJivrajani** [comment]
Hey folks 👋🏻 

As per the standing consensus, `kind/design` in favor of `kind/feature` was decided to be removed from only `k/k` and not the other repos. The method I hope to follow is as follows:

- Do a sweep of existing issues/PRs and remove and replace `kind/design` with `kind/feature`
  - A manual sweep would be required mainly because `label_sync` does not support a label to be present under a repo (with a `previously` label mentioned) as well as under default.
  - An initial sweep was done, I will do another one after opening a PR in `k/test-infra`
- Remove `kind/design` and `kind/feature` from the `default` section in [`labels.yaml`](https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.yaml)
  - Add `kind/feature` to each individual repo and add a `previously` of `kind/design` for `kind/feature` under `k/k`
  - Add `kind/design` to all repos except `k/k`
  - This removal from `default` and addition to individual repos is mainly because if a `previously` is added under `kind/feature` then it will affect all repos. 

Relevant slack discussion can be found [here](https://kubernetes.slack.com/archives/C09QZ4DQB/p1624988310246600?thread_ts=1624988310.246600&cid=C09QZ4DQB).

If folks are alright with removal of `kind/design` from `default` then I can go ahead with this approach. Please let me know if I've missed anything or if this can be done in a better way.

cc @nikhita

**Comment by nikhita** [comment]
> Remove kind/design and kind/feature from the default section in labels.yaml


For anyone reading this - to elaborate, this means that new repos will **not** automatically include the `kind/design` label. If a repo wants to use the label, the repo maintainers would need to explicitly opt-in by adding the repo to `labels.yaml`.

> Add kind/design to all repos except k/k


There are a lot of repos in the @kubernetes and @kubernetes-sigs organization right now. Adding all of the existing repos to labels.yaml will blow up the (already large) file. :)

To avoid this, I think it should be sufficient to add the `kind/design` label (in `labels.yaml`) to only those repos that actively use the repo.

**Comment by mrbobbytables** [comment]
> To avoid this, I think it should be sufficient to add the kind/design label (in labels.yaml) to only those repos that actively use the repo.

+1

**Comment by MadhavJivrajani** [comment]
I think we might also need to update the pull request template in `k/k`

**Comment by spiffxp** [comment]
Just so I understand the intended outcome here, is this what everyone is expecting?
- no new repos will have the `kind/design` label
- the following repos will continue to have the `kind/design` label in github (source of truth) but not in labels.yaml (source of intent)
```
    "kubernetes-client/.github",
    "kubernetes-client/c",
    "kubernetes-client/csharp",
    "kubernetes-client/gen",
    "kubernetes-client/go",
    "kubernetes-client/go-base",
    "kubernetes-client/haskell",
    "kubernetes-client/java",
    "kubernetes-client/javascript",
    "kubernetes-client/perl",
    "kubernetes-client/python",
    "kubernetes-client/python-base",
    "kubernetes-client/ruby",
    "kubernetes-csi/.github",
    "kubernetes-csi/cluster-driver-registrar",
    "kubernetes-csi/csi-driver-host-path",
    "kubernetes-csi/csi-driver-image-populator",
    "kubernetes-csi/csi-driver-iscsi",
    "kubernetes-csi/csi-driver-nfs",
    "kubernetes-csi/csi-driver-smb",
    "kubernetes-csi/csi-lib-fc",
    "kubernetes-csi/csi-lib-iscsi",
    "kubernetes-csi/csi-lib-utils",
    "kubernetes-csi/csi-proxy",
    "kubernetes-csi/csi-release-tools",
    "kubernetes-csi/csi-test",
    "kubernetes-csi/docs",
    "kubernetes-csi/driver-registrar",
    "kubernetes-csi/external-attacher",
    "kubernetes-csi/external-health-monitor",
    "kubernetes-csi/external-provisioner",
    "kubernetes-csi/external-resizer",
    "kubernetes-csi/external-snapshotter",
    "kubernetes-csi/kubernetes-csi.github.io",
    "kubernetes-csi/lib-volume-populator",
    "kubernetes-csi/livenessprobe",
    "kubernetes-csi/node-driver-registrar",
    "kubernetes-csi/volume-data-source-validator",
    "kubernetes-sigs/.github",
    "kubernetes-sigs/about-api",
    "kubernetes-sigs/alibaba-cloud-csi-driver",
    "kubernetes-sigs/apiserver-builder-alpha",
    "kubernetes-sigs/apiserver-network-proxy",
    "kubernetes-sigs/apiserver-runtime",
    "kubernetes-sigs/application",
    "kubernetes-sigs/aws-ebs-csi-driver",
    "kubernetes-sigs/aws-efs-csi-driver",
    "kubernetes-sigs/aws-encryption-provider",
    "kubernetes-sigs/aws-fsx-csi-driver",
    "kubernetes-sigs/aws-iam-authenticator",
    "kubernetes-sigs/aws-load-balancer-controller",
    "kubernetes-sigs/azuredisk-csi-driver",
    "kubernetes-sigs/azurefile-csi-driver",
    "kubernetes-sigs/blob-csi-driver",
    "kubernetes-sigs/boskos",
    "kubernetes-sigs/cli-experimental",
    "kubernetes-sigs/cli-utils",
    "kubernetes-sigs/clientgofix",
    "kubernetes-sigs/cloud-provider-azure",
    "kubernetes-sigs/cloud-provider-baiducloud",
    "kubernetes-sigs/cloud-provider-huaweicloud",
    "kubernetes-sigs/cluster-addons",
    "kubernetes-sigs/cluster-api",
    "kubernetes-sigs/cluster-api-provider-aws",
    "kubernetes-sigs/cluster-api-provider-azure",
    "kubernetes-sigs/cluster-api-provider-digitalocean",
    "kubernetes-sigs/cluster-api-provider-docker",
    "kubernetes-sigs/cluster-api-provider-gcp",
    "kubernetes-sigs/cluster-api-provider-ibmcloud",
    "kubernetes-sigs/cluster-api-provider-kubemark",
    "kubernetes-sigs/cluster-api-provider-nested",
    "kubernetes-sigs/cluster-api-provider-openstack",
    "kubernetes-sigs/cluster-api-provider-packet",
    "kubernetes-sigs/cluster-api-provider-vsphere",
    "kubernetes-sigs/cluster-capacity",
    "kubernetes-sigs/cluster-proportional-autoscaler",
    "kubernetes-sigs/cluster-proportional-vertical-autoscaler",
    "kubernetes-sigs/container-object-storage-interface-api",
    "kubernetes-sigs/container-object-storage-interface-controller",
    "kubernetes-sigs/container-object-storage-interface-csi-adapter",
    "kubernetes-sigs/container-object-storage-interface-provisioner-sidecar",
    "kubernetes-sigs/container-object-storage-interface-spec",
    "kubernetes-sigs/contributor-playground",
    "kubernetes-sigs/contributor-tweets",
    "kubernetes-sigs/controller-runtime",
    "kubernetes-sigs/controller-tools",
    "kubernetes-sigs/cosi-driver-sample",
    "kubernetes-sigs/cri-tools",
    "kubernetes-sigs/custom-metrics-apiserver",
    "kubernetes-sigs/dashboard-metrics-scraper",
    "kubernetes-sigs/depstat",
    "kubernetes-sigs/descheduler",
    "kubernetes-sigs/discuss-theme",
    "kubernetes-sigs/downloadkubernetes",
    "kubernetes-sigs/e2e-framework",
    "kubernetes-sigs/etcdadm",
    "kubernetes-sigs/execution-hook",
    "kubernetes-sigs/external-dns",
    "kubernetes-sigs/externalip-webhook",
    "kubernetes-sigs/gateway-api",
    "kubernetes-sigs/gcp-compute-persistent-disk-csi-driver",
    "kubernetes-sigs/gcp-filestore-csi-driver",
    "kubernetes-sigs/gluster-block-external-provisioner",
    "kubernetes-sigs/gluster-file-external-provisioner",
    "kubernetes-sigs/go-open-service-broker-client",
    "kubernetes-sigs/hierarchical-namespaces",
    "kubernetes-sigs/ibm-vpc-block-csi-driver",
    "kubernetes-sigs/image-builder",
    "kubernetes-sigs/ingress-controller-conformance",
    "kubernetes-sigs/instrumentation",
    "kubernetes-sigs/instrumentation-addons",
    "kubernetes-sigs/instrumentation-tools",
    "kubernetes-sigs/ip-masq-agent",
    "kubernetes-sigs/iptables-wrappers",
    "kubernetes-sigs/k8s-container-image-promoter",
    "kubernetes-sigs/k8s-gsm-tools",
    "kubernetes-sigs/kind",
    "kubernetes-sigs/kpng",
    "kubernetes-sigs/krew",
    "kubernetes-sigs/krew-index",
    "kubernetes-sigs/kube-batch",
    "kubernetes-sigs/kube-storage-version-migrator",
    "kubernetes-sigs/kubebuilder",
    "kubernetes-sigs/kubebuilder-declarative-pattern",
    "kubernetes-sigs/kubebuilder-release-tools",
    "kubernetes-sigs/kubectl-check-ownerreferences",
    "kubernetes-sigs/kubefed",
    "kubernetes-sigs/kubespray",
    "kubernetes-sigs/kubetest2",
    "kubernetes-sigs/kui",
    "kubernetes-sigs/kustomize",
    "kubernetes-sigs/legacyflag",
    "kubernetes-sigs/lwkd",
    "kubernetes-sigs/mcs-api",
    "kubernetes-sigs/mdtoc",
    "kubernetes-sigs/metrics-server",
    "kubernetes-sigs/minibroker",
    "kubernetes-sigs/multi-tenancy",
    "kubernetes-sigs/network-policy-api",
    "kubernetes-sigs/nfs-ganesha-server-and-external-provisioner",
    "kubernetes-sigs/nfs-subdir-external-provisioner",
    "kubernetes-sigs/node-feature-discovery",
    "kubernetes-sigs/node-feature-discovery-operator",
    "kubernetes-sigs/poseidon",
    "kubernetes-sigs/prometheus-adapter",
    "kubernetes-sigs/provider-aws-test-infra",
    "kubernetes-sigs/reference-docs",
    "kubernetes-sigs/release-notes",
    "kubernetes-sigs/release-sdk",
    "kubernetes-sigs/release-utils",
    "kubernetes-sigs/scheduler-plugins",
    "kubernetes-sigs/secrets-store-csi-driver",
    "kubernetes-sigs/security-profiles-operator",
    "kubernetes-sigs/service-catalog",
    "kubernetes-sigs/sig-storage-lib-external-provisioner",
    "kubernetes-sigs/sig-storage-local-static-provisioner",
    "kubernetes-sigs/sig-usability",
    "kubernetes-sigs/sig-windows-dev-tools",
    "kubernetes-sigs/sig-windows-samples",
    "kubernetes-sigs/sig-windows-tools",
    "kubernetes-sigs/slack-infra",
    "kubernetes-sigs/structured-merge-diff",
    "kubernetes-sigs/vsphere-csi-driver",
    "kubernetes-sigs/wg-policy-prototypes",
    "kubernetes-sigs/windows-gmsa",
    "kubernetes-sigs/windows-testing",
    "kubernetes-sigs/work-api",
    "kubernetes-sigs/yaml",
    "kubernetes-sigs/zeitgeist",
    "kubernetes/.github",
    "kubernetes/api",
    "kubernetes/apiextensions-apiserver",
    "kubernetes/apimachinery",
    "kubernetes/apiserver",
    "kubernetes/autoscaler",
    "kubernetes/cli-runtime",
    "kubernetes/client-go",
    "kubernetes/cloud-provider",
    "kubernetes/cloud-provider-alibaba-cloud",
    "kubernetes/cloud-provider-aws",
    "kubernetes/cloud-provider-gcp",
    "kubernetes/cloud-provider-openstack",
    "kubernetes/cloud-provider-sample",
    "kubernetes/cloud-provider-vsphere",
    "kubernetes/cluster-bootstrap",
    "kubernetes/code-generator",
    "kubernetes/community",
    "kubernetes/component-base",
    "kubernetes/component-helpers",
    "kubernetes/contributor-site",
    "kubernetes/controller-manager",
    "kubernetes/cri-api",
    "kubernetes/csi-api",
    "kubernetes/csi-translation-lib",
    "kubernetes/dashboard",
    "kubernetes/dns",
    "kubernetes/enhancements",
    "kubernetes/examples",
    "kubernetes/frakti",
    "kubernetes/funding",
    "kubernetes/gengo",
    "kubernetes/git-sync",
    "kubernetes/ingress-gce",
    "kubernetes/ingress-nginx",
    "kubernetes/k8s.io",
    "kubernetes/klog",
    "kubernetes/kompose",
    "kubernetes/kops",
    "kubernetes/kube-aggregator",
    "kubernetes/kube-controller-manager",
    "kubernetes/kube-openapi",
    "kubernetes/kube-proxy",
    "kubernetes/kube-scheduler",
    "kubernetes/kube-state-metrics",
    "kubernetes/kubeadm",
    "kubernetes/kubectl",
    "kubernetes/kubelet",
    "kubernetes/kubernetes",
    "kubernetes/kubernetes-template-project",
    "kubernetes/legacy-cloud-providers",
    "kubernetes/metrics",
    "kubernetes/minikube",
    "kubernetes/mount-utils",
    "kubernetes/node-api",
    "kubernetes/node-problem-detector",
    "kubernetes/noderesourcetopology-api",
    "kubernetes/org",
    "kubernetes/perf-tests",
    "kubernetes/pod-security-admission",
    "kubernetes/publishing-bot",
    "kubernetes/release",
    "kubernetes/repo-infra",
    "kubernetes/sample-apiserver",
    "kubernetes/sample-cli-plugin",
    "kubernetes/sample-controller",
    "kubernetes/security",
    "kubernetes/sig-release",
    "kubernetes/sig-testing",
    "kubernetes/steering",
    "kubernetes/system-validators",
    "kubernetes/test-infra",
    "kubernetes/utils",
    "kubernetes/website"
```
- some repos will have `kind/design` both in github and in labels.yaml
- all existing issues with `kind/design` will keep the label

This is what https://github.com/kubernetes/test-infra/pull/23011 in its current form will accomplish.

I'm not sure I see the benefit of allowing the persistent delta between source of intent and source of truth?

**Comment by MadhavJivrajani** [comment]
Cross posting here:

https://github.com/kubernetes/test-infra/pull/23011#pullrequestreview-724409023
