### ISSUE TITLE
How to create ingress by golang api

### ISSUE THREAD

**Issue by wei5523** [kubernetes/community#5654]
**Hi Everyone,**

**I want to create ingress by golang.  But I got error when I send the body like this  :**

 `{
    "apiVersion": "extensions/v1beta1",
    "kind": "Ingress",
    "metadata": {
        "name": "drone-ingress",
        "namespace": "drone"
    },
    "spec": {
        "rules": [
            {
                "host": "drone-local.nip.io",
                "http": {
                    "paths": {
                        "backend": {
                            "serviceName": "drone-service",
                            "servicePort": "8080"
                        },
                        "path": "/"
                    }
                }
            }
        ]
    }
}`

**The error is :**

`{
    "code": 10003,
    "message": "json: Unmarshal(non-pointer string)",
    "request": "POST /api/v1/ingress/drone-test"
}`

---------------------------------------------------------

I guess the "servicePort" caused this error, because its type is  "intstr.IntOrString".
How to write the json ?
Hope anyone can tell me ! Thanks !

<img width="588" alt="1" src="https://user-images.githubusercontent.com/28132838/112140680-467e1c00-8c0f-11eb-8f8d-34ab12816177.png">

<img width="411" alt="2" src="https://user-images.githubusercontent.com/28132838/112140711-54cc3800-8c0f-11eb-8df4-18989fa51345.png">

**Comment by mrbobbytables** [comment]
@wei5523 your question won't really get answered here, this is the meta-repo used for general contributor community management. I suggest [reaching out to sig network](https://github.com/kubernetes/community/tree/master/sig-network#contact) either in slack or on their mailing list to get your question answered 👍

**Comment by wei5523** [comment]
@mrbobbytables thank for your reply. I will try and close this issue.  👍
