### ISSUE TITLE
Add slack bot for non-inclusive language

### ISSUE THREAD

**Issue by nikhita** [kubernetes/community#5660]
This issue is to track adding a slack bot to moderator non-inclusive language. See original issue with more details - https://github.com/kubernetes-sigs/slack-infra/issues/27

Ref: [slack thread](https://kubernetes.slack.com/archives/C4M06S5HS/p1614182913005000)

- [x] PR to add the bot - https://github.com/kubernetes-sigs/slack-infra/pull/41
- [x] Updates to slack-moderator-words to push the image - kubernetes-sigs/slack-infra#43
- [x] Config for deploying the bot - https://github.com/kubernetes/k8s.io/pull/1696
- [x] Deploying the config - @ameukam @spiffxp have created the secret, @cpanato has deployed the bot
- [x] Approval from slack-admins
- [x] Send an email to k-dev (@cpanato to send)
- [x] Update the slack token config with the new URL for the bot (todo by @jeefy)

/assign @cpanato 
/sig contributor-experience
/area slack-management

**Comment by cpanato** [comment]
bot is deployed and running

**Comment by cpanato** [comment]
email sent: https://groups.google.com/g/kubernetes-dev/c/7ZdDLJ8UiQ8

**Comment by cpanato** [comment]
all this is done, we can close this issue
@nikhita can you check the last item and close it when you have a chance?

**Comment by nikhita** [comment]
> @nikhita can you check the last item and close it when you have a chance?

Done. Closing 🎉
