### ISSUE TITLE
REQUEST: Upgrade the Slack App "GitHub"

### ISSUE THREAD

**Issue by maelvls** [kubernetes/community#5668]
**GitHub Username:** @parispittman (AFAIK owner of the `#cert-manager-dev` channel, see below)
**Slack Username:** [Paris Pittman](https://kubernetes.slack.com/team/U5SB22BBQ) (owner of the `#cert-manager-dev` channel)

<details>
<summary>🪧 Screenshot: owner of #cert-manager-dev</summary>

<img width="400" alt="Screenshot 2021-03-30 at 15 59 51" src="https://user-images.githubusercontent.com/2195781/113001808-74181780-9171-11eb-95ac-680494f978c6.png">
</details>

**Type of Request:** not sure
**Description of Request:**

The cert-manager team has been discussing [on 13th January 2021](https://docs.google.com/document/d/1Tc5t6ylY9dhXAan1OjOoldeaoys1Yh4Ir710ATfBa5U/edit#bookmark=id.ousd7wrdk049) and [on 10th February 2021](https://docs.google.com/document/d/1Tc5t6ylY9dhXAan1OjOoldeaoys1Yh4Ir710ATfBa5U/edit#bookmark=id.4p8og7nlq92) the idea of using the GitHub "real-time alerts" for helping with keeping up with PR reviews. These real-time alerts are opt-in only (the user has to click on "Configure GitHub" in order to enable it for their account), and are DM-only, meaning that there is no bot pollution to public channels.

Note that the GitHub app has already been installed to `#cert-manager-dev` using the "old" GitHub Slack app.
<details>
<summary>🪧  Screenshot: the legacy GitHub App is currently installed
</summary>

<img width="400" alt="Screenshot 2021-03-30 at 15 59 51" src="https://user-images.githubusercontent.com/2195781/113006351-9318a880-9175-11eb-8778-f2b9cb12020a.png">
</details>

 On the https://slack.github.com/ website, we can read:

> Using an older version of GitHub + Slack? Installing the new app will allow you to migrate subscriptions from legacy versions. By installing or using the app, you agree to the [Terms and Conditions](https://github.com/integrations/slack/tree/master/docs/terms-and-conditions.md).

Would it be possible to upgrade (i.e., just re-install the app) the [Slack + GitHub App](https://slack.github.com/) to be able to use the "real-time alerts" feature?

Thank you,

Maël

**Comment by mrbobbytables** [comment]
We unfortunately cannot upgrade the GitHub Slack app. When the new version was first released it was reviewed by the GitHub admin team and the the capabilities it enables + it being enabled for ALL channels automatically with no way of restricting its access is too much of a risk to enable. There are some capabilities of it that could potentially bypass the workflow processes that we have built with Prow. =/

**Comment by maelvls** [comment]
Got it! I will add a note about this on the [cert-manager biweekly meeting notes](https://docs.google.com/document/u/6/d/1Tc5t6ylY9dhXAan1OjOoldeaoys1Yh4Ir710ATfBa5U/edit#heading=h.7h8rkitcxn99). Thanks for the information!

/close
