### ISSUE TITLE
provider-aws OWNERS_ALIAS is mostly stale

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#5671]
This alias is copy-pasted in a bunch of different repos (kubernetes/org, kubernetes/test-infra).  Two of its members have moved on from the project and have at most 5 contributions for the year (kris-nova, d-nishi) vs ~1K for justinsb (according to devstats).  PRs that touch paths it owns go unaddressed if justinsb happens to be unavailable.

This is the alias definition in this repo, but as I said, it's copy-pasted around:
https://github.com/kubernetes/community/blob/099566260faa4674fc98b3789e2d36b42bcd1978/OWNERS_ALIASES#L166-L169

https://cs.k8s.io/?q=provider-aws&i=nope&files=OWNERS%24&excludeFiles=&repos= are the paths in question, basically:
- KEPs related to aws
- GitHub team changes related to aws

/kind bug
/priority important-soon
/sig cloud-provider
/provider aws
/assign @justinsb @cheftako @andrewsykim 
FYI @AndyXiangLi @wongma7

**Comment by nikhita** [comment]
related in k/org - https://github.com/kubernetes/org/pull/2759

**Comment by CIPHERTron** [comment]
I would love to take up this issue @spiffxp provided no one else is working on it. 😄

**Comment by spiffxp** [comment]
Looks like @nckturner is taking this on
/assign @nckturner
