### ISSUE TITLE
kubernetes-dev moderator staff has openings

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#5685]
I kicked a bunch of kubernetes-dev@ messages from first-time posters out of moderation today.  Made me wonder if our moderation staff is stretched too thin.

So after asking in #sig-contribex I added @dims as an Owner, and reconciled the state of kubernetes-dev roles and the moderation docs: https://github.com/kubernetes/community/pull/5684

This leaves us with:
- 2 open primary moderator seats
- 5 open pro-tempore moderator seats

/sig contributor-experience
/assign @mrbobbytables @alisondy 
Putting this on your plate if you want to call for more staff etc.
FYI @parispittman @dims

**Comment by nikhita** [comment]
> 2 open primary moderator seats

First one has been filled by @cpanato (https://github.com/kubernetes/community/pull/5689), created https://github.com/kubernetes/community/pull/5888 to add @palnabarun for the second one

We are now left with 5 open pro-tempore moderator seats

**Comment by cpanato** [comment]
@nikhita I have a quick question, I never received any messages from this to moderate neither I see options when I access https://groups.google.com/g/kubernetes-dev

**Comment by nikhita** [comment]
Update -- @cpanato did not actually have moderator access, granted access now

**Comment by parispittman** [comment]
FYI two folks from the current contribex mentoring group that is going to sign up and comment here that they are ready, available, understand the duties.

**Comment by Debanitrkl** [comment]
Hi, I'm Debabrata, from contribex-mentoring group. I have gone through the moderation docs and also @parispittman gave a demo on how moderation works. I would like to help with this.
Thank you

**Comment by Atharva-Shinde** [comment]
Hey I am Atharva, I am part of the current Contribex mentoring group and I have thoroughly gone through the moderation guidelines, I am available as required and understand the duties. I am interested and would like to be a part of this and help the community

**Comment by mrbobbytables** [comment]
I'm going to go ahead and close this out, more moderators have been added bringing the total to 11.

/close
