### ISSUE TITLE
Kubernetes Benchmark Testing 

### ISSUE THREAD

**Issue by Kevin1515-ENG** [kubernetes/community#5702]
Hello, 

I am new to the Kubernetes World so any guidance is greatly appreciated. 

My role is a test engineer. The system I am testing is a Konvoy Kubernetes Cluster on a Bare Metal System. 

My goal is to find a Benchmark or set of standards that is accepted across the Kubernetes community for testing the limits of  a Kubernetes Cluster. 

My end goal is to take these Bare Metal results and compare them to a Cloud Base system results. The Cloud Based system would be tested with the same set of standards. I could then take these results and show the developer the limits of their Bare Metal and Cloud system.  

/sig Testing

**Comment by mrbobbytables** [comment]
This repo is the meta-repo for managing the project, your question is not likely to get answered here. =/

I'd suggest emailing the [kubernetes-dev](https://groups.google.com/u/1/g/kubernetes-dev) mailing list.

**Comment by mrbobbytables** [comment]
With the suggestion, and it not likely going to get any answer here I'm going to go ahead and close this issue. If you have any questions, please feel free to still use it or reach out in slack.
Thanks!

/close
