### ISSUE TITLE
REQUEST: New private Slack channel #sig-auth-leads

### ISSUE THREAD

**Issue by tallclair** [kubernetes/community#5716]
**GitHub Username:** @tallclair 
**Slack Username:** @tallclair

**What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?**
Private channel for SIG-Auth leads to coordinate administrative duties.

**Name of Requested Resource:**
`#sig-auth-leads`

**Description of Request:**
Private channel for sig-auth leads to coordinate administrative duties (e.g. who is running the biweekly meeting). We currently use DMs for this, but it would be convenient to maintain some history across leadership changes.

/sig auth

/cc @enj @mikedanese @ritazh @liggitt @deads2k

**Comment by markyjackson-taulia** [comment]
@tallclair is it not possible to have these discussions in the sig-auth channel? My concern is that the private channels are not managed by the slack infra..

**Comment by mrbobbytables** [comment]
Marky is right, we only do private channels for very specific and limited use-cases (security issues, CoCC etc)

**Comment by tallclair** [comment]
There's nothing in there that needs to be strictly private. My concern with having these conversations in #sig-auth is that at best it will create noise for non-leads, and at worst could be misleading (e.g. the question of "who is running the meeting today" is not a call for volunteers from the general community, as it requires access to the sig-auth zoom account).

This request is really a nice-to-have. If it's a problem, we can continue with the approach we've been using, and be a bit more disciplined about pushing more conversations to the public channel.

FWIW, as community leads, we're all responsible for upholding the code of conduct, and I think have all taken the unconscious bias training.

**Comment by tallclair** [comment]
OK, sounds like we can close this out then. Thanks for the feedback!
