### ISSUE TITLE
Kubernetes cluster why exactly is public hosted domain needed on AWS

### ISSUE THREAD

**Issue by vivekaundkar** [kubernetes/community#573]
I am new to kubernetes. Using Kops I am able to create cluster using both public and private topologies on AWS . However trying to under why is it essential to have an public hosted domain for kubernetes cluster? Is there a way we can just use route 53(with no need of public hosted domain on external site like GoDaddy etc) and create a fully functional high availability kubernetes cluster? If do please point to some documentation or working example

**Comment by kris-nova** [comment]
@vivekaundkar I am closing this as a duplicate of https://github.com/kubernetes/kops/issues/2416

Please see notes there for follow up
