### ISSUE TITLE
Broken link in sig-node/README

### ISSUE THREAD

**Issue by MadhavJivrajani** [kubernetes/community#5738]
The link to OWNERS file for [noderesourcetopology-api](https://github.com/kubernetes/community/blob/master/sig-node/README.md#noderesourcetopology-api) in the [sig-node/README](https://github.com/kubernetes/community/blob/master/sig-node/README.md#noderesourcetopology-api) seems to be broken due to absence of an OWNERS file in that repo.

/sig node

**Comment by nikhita** [comment]
cc @ehashman

**Comment by ehashman** [comment]
The repo is completely empty: https://github.com/kubernetes/noderesourcetopology-api/

Repo was created as part of https://github.com/kubernetes/org/issues/2302

/assign @swatisehgal 

do you know what's happening here?
