### ISSUE TITLE
Create a new `kubernetes-sigs/network-policy-api` repo

### ISSUE THREAD

**Issue by astoycos** [kubernetes/community#5747]
After much discussion in the [Network Policy API Meeting](https://docs.google.com/document/d/1AtWQy2fNa4qXRag9cCp5_HsefD7bxKe3ea2RPn8jnSs), on the [KEP for Cluster Scoped Network Policy](https://github.com/kubernetes/enhancements/pull/2522/files#r600361541)  and in slack([dis 1](https://kubernetes.slack.com/archives/C01CWSHQWQJ/p1619120255062800) [dis 2](https://kubernetes.slack.com/archives/C09QYUH5W/p1618570463278100)) we (the sig-network-policy subgroup within [Sig-Network](https://github.com/kubernetes/community/tree/master/sig-network)) have decided that the best way to iterate on Network Policy, such as with the cluster-scoped network policy and a possible Network Policy V2, is to create a repo which will serve to house CRDs supported by the group.  This follows the same pattern completed  by the [Kubernetes Gateway API](https://github.com/kubernetes-sigs/gateway-api).  It has also been agreed upon that this repo should be called `network-policy-api` as it relates to all future work involving k8's network security.   

This issue serves to open up further discussion from the greater Sig-Network group around how the internals (CRD groups, api approval process etc should work) and to hopefully get permission to create the new repository.

**Comment by astoycos** [comment]
cc @abhiraut @Dyanngg

**Comment by aojea** [comment]
@astoycos I think that you have to open the issue in kubernetes/org, there is also a template for that
see this example https://github.com/kubernetes/org/issues/1292

Once you submit the request, it should be good to announce it in the sig-net mailing list too , see
https://groups.google.com/g/kubernetes-sig-network/c/Ev2FX74bACA/m/jtw65R5ADAAJ

**Comment by mrbobbytables** [comment]
@aojea is right 👍  please open an issue on k-org

**Comment by mrbobbytables** [comment]
I'm going to close this for now, when you're ready - please open an issue over in k-org.

Thanks!

/close

**Comment by astoycos** [comment]
ACK, will do Thanks!
