### ISSUE TITLE
SIG Auth needs a CONTRIBUTING.md

### ISSUE THREAD

**Issue by ritazh** [kubernetes/community#5760]
Follow up item from sig auth annual report.

**Comment by pravarag** [comment]
Hi @ritazh , can I work on this issue if it's available to take?

**Comment by ritazh** [comment]
Go for it! Thanks @pravarag!

**Comment by pravarag** [comment]
Thanks @ritazh! Just to confirm, I'm guessing this is the location where we can place the CONTRIBUTING.md guide: https://github.com/kubernetes/community/tree/master/sig-auth ?

**Comment by ritazh** [comment]
Yes that’s the right place!

**Comment by pravarag** [comment]
@ritazh I've created a PR and would like to have your review comments on it.
