### ISSUE TITLE
REQUEST: New moderator for rawkode of YouTube

### ISSUE THREAD

**Issue by rawkode** [kubernetes/community#5784]
### GitHub Username
@rawkode

### Property you'd like to Moderate
YouTube Channel

### Username on Property Requested
david.andrew.mckay@gmail.com

### Requirements

- [x] I am a Kubernetes Org member already
- [x] I have enabled 2FA on my account for the property I would like to moderate (if applicable).
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mrbobbytables 
- @markyjackson-taulia 

### List of qualifications for this position

- Prior moderation experience

As a Developer Advocate, I've been moderating Slack's and YouTube's for the organizations I've worked with for the last few years, as well as my own YouTube channel and Discord.

**Comment by markyjackson-taulia** [comment]
+1 and thank you for stepping up

**Comment by mrbobbytables** [comment]
+1 from me :) 

If you want, please go ahead add yourself to the moderator list here:
https://github.com/kubernetes/community/blob/master/communication/moderators.md#youtube-channel

and we can follow up getting you added 👍
