### ISSUE TITLE
REQUEST: New moderator for danpopsd of YouTube Channel

### ISSUE THREAD

**Issue by danpopSD** [kubernetes/community#5786]
### GitHub Username
@danpopsd

### Property you'd like to Moderate
YouTube Channel

### Username on Property Requested
@danpopSD 
dpapandrea@gmail.com (for the yt id) 

### Requirements

- [X ] I am a Kubernetes Org member already
- [ X] I have enabled 2FA on my account for the property I would like to moderate (if applicable).
- [ X] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [ X] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [ X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@castrojo 
@mrbobbytables 

### List of qualifications for this position
- hosted office hours
- hosted Kubernetes Community Call
- member of k8s contributors
- i have a nice smile and enjoy long walks on the beach.

**Comment by mrbobbytables** [comment]
+1 from me :)

**Comment by jeefy** [comment]
+1

**Comment by castrojo** [comment]
+1 from me as well!

**Comment by mrbobbytables** [comment]
You have been added 👍 
If you could, follow up with adding yourself to the list of moderators here:
https://github.com/kubernetes/community/blob/master/communication/moderators.md#primary-moderators-1

**Comment by mrbobbytables** [comment]
PR has been merged (https://github.com/kubernetes/community/pull/5795), this is good to close 👍 
/close
