### ISSUE TITLE
Brainstorming on Issue management 

### ISSUE THREAD

**Issue by jagosan** [kubernetes/community#580]
Background:  I am new to the project and trying to get a sense of status and direction is difficult.  This is at least partially due to a high number of open issues inconsistently labeled and organized.  I had some side conversations with a couple of people, who suggested opening a brainstorming issue here.  

Intention is to start with brainstorming and evolve to a proposal for: 

1. management of incoming issues; and 
2. organizing existing issues into reasonable groups

**Comment by bgrant0607** [comment]
Brief proposal here:
https://github.com/orgs/kubernetes/projects/1#card-2296048

cc @grodrigues3

**Comment by zhangxiaoyu-zidif** [comment]
@bgrant0607 https://github.com/orgs/kubernetes/projects/1#card-2296048 is broken? it response 404.

**Comment by timothysc** [comment]
auto-close with label have bot ignore, similar to PRs - 
https://github.com/kubernetes/test-infra/issues/2132

**Comment by bgrant0607** [comment]
Contents of the project card:

Design and implement sustainable issue routing (to appropriate SIG and kind (bug, feature request, etc.)). Require org members to provide this information (close if not). Round-robin assign to triage team if not provided by non-member.

**Comment by bgrant0607** [comment]
Clearly issues are being auto-closed now.

I still think we need more effective triage rotation, but closing in favor of more specific proposals
