### ISSUE TITLE
Migrate sig-testing leads mailing list

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#5800]
Followup issue to https://github.com/kubernetes/k8s.io/pull/2109 which adds a sig-testing-leads@kubernetes.io mailing list

- Switch our zoom account to use this e-mail address (super easy self-service, I did this for wg-k8s-infra)
- Update docs

/sig testing
/kind cleanup
/kind documentation
/priority backlog
/assign @spiffxp @BenTheElder @stevekuznetsov

**Comment by BenTheElder** [comment]
So we still need to switch the zoom / docs?
I can work on this.

**Comment by spiffxp** [comment]
/close
There are not
