### ISSUE TITLE
Proposal - Build a K8S hub to share and consume Deployment yaml files

### ISSUE THREAD

**Issue by vmtocloud** [kubernetes/community#581]
Finding decent K8S yaml files for common applications is difficult. I know we have Github for this but a central site like Docker Hub would be so much better.

**Comment by viglesiasce** [comment]
Hey @vmtocloud!

Have you seen [KubeApps](https://kubeapps.com) and the [Charts repository](https://github.com/kubernetes/charts) for Helm?

**Comment by vmtocloud** [comment]
Yup, I think KubeApps is what I was looking for! Man, I searched Google for a while too, thank you @viglesiasce for the share!
