### ISSUE TITLE
What does "MVP" mean in this context?

### ISSUE THREAD

**Issue by HeGaoYuan** [kubernetes/community#5818]
What does MVP mean in this context? 
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/autoscaling/vertical-pod-autoscaler.md#in-place-updates

**Comment by coderanger** [comment]
Hi there, this isn't a good place to ask support questions. If you're looking to get involved in Kubernetes, join us in Slack (slack.k8s.io) and try the `#kubernetes-contributors` channel.

But to answer your question, MVP is Minimum Viable Product (or something Project).

/close
