### ISSUE TITLE
Please, Add Official Discord Link of Kubernetes to Community Repo

### ISSUE THREAD

**Issue by atulkamble** [kubernetes/community#5831]
[Discord](https://discord.com/) for Kubernetes Community can add more value.

**Comment by mrbobbytables** [comment]
We used a discord temporarily last year for an event, and tbh, I'm personally a big fan of it, but at this time we have no plans to create and moderate a more permanent one. We have roughly 130,000 people in slack and that takes a significant effort to staff and run, we really don't want to split our community and manage another platform.  =/

/close

**Comment by atulkamble** [comment]
okay, Thanks for replying and clearing my doubt @mrbobbytables.
