### ISSUE TITLE
Please advertise Thursday's Community Meeting

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#5835]
Comms:

```
Join us for the monthly Kubernetes community meeting this Thursday!  
10am PDT / 1700 UTC / 7pm CET
On Zoom[1]!

We have a bunch to discuss already on the Agenda[2]:
- 1.22 updates
- What happened with the patch releases?
- Upcoming mass API removal
- Preventing CLI Footguns
- Release schedule calendar

... but there's still room for your item if there's something you need to discuss/coordinate with our whole contributor community.  Contact Josh[3][4] to add your stuff to the agenda.  See you on Thursday!

[1]: https://zoom.us/j/91768411674?pwd=MVpqL0ZHbGFYMnpXVXpybTBvalFRQT09
[2]: http://bit.ly/k8scommunity
[3]: jberkus@redhat.com
[4]: @jberkus on slack.k8s.io
```

/sig contributor-strategy
/area contributor-comms

**Comment by jberkus** [comment]
feh

/sig contributor-experience

**Comment by rajula96reddy** [comment]
Update: As of today, we have [tweeted](https://twitter.com/K8sContributors/status/1404589369667715072?s=20) about this and posted the same on [k-dev](https://groups.google.com/g/kubernetes-dev/c/nM8EGUC6zDA). 
We can send out a reminder tweet on Wednesday/ early Thursday for the same.

**Comment by mrbobbytables** [comment]
@rajula96reddy can kick off a slack msg reminder tomorrow too?

**Comment by rajula96reddy** [comment]
> @rajula96reddy can kick off a slack msg reminder tomorrow too?

Do we want the message reminder in all of the SIG & WG slack channels?

**Comment by mrbobbytables** [comment]
> Do we want the message reminder in all of the SIG & WG slack channels?

Yes along with the `#kubernetes-contributors` channel 👍

**Comment by rajula96reddy** [comment]
We have [retweeted](https://twitter.com/K8sContributors/status/1405211796772855810?s=19) to bring attention to the first tweet.
And pushed reminder messages to all the SIG/ WG/ UG & `#kubernetes-contributors` slack channels ([Example](https://kubernetes.slack.com/archives/C1TU9EB9S/p1623864028197600))

**Comment by jberkus** [comment]
Thanks for all the reminders to folks

**Comment by spiffxp** [comment]
/close
I think this has been completed.  Please /reopen if I've closed this in error
