### ISSUE TITLE
Request to change the year in SIG-network's annual report

### ISSUE THREAD

**Issue by MadhavJivrajani** [kubernetes/community#5838]
Hi!

The year mentioned In SIG-network's annual report is `2021`, iiuc, this should be `2020`. 
xref: https://github.com/kubernetes/steering/pull/211#discussion_r651820153

/sig network
cc @mrbobbytables 
cc @caseydavenport

**Comment by mrbobbytables** [comment]
Here is the PR for it: https://github.com/kubernetes/community/pull/5837

**Comment by MadhavJivrajani** [comment]
/close
Fixed in #5837
