### ISSUE TITLE
Compatibility version kubernetes and docker

### ISSUE THREAD

**Issue by ffelicissimo** [kubernetes/community#584]
I'm looking for compatibility map of kubernetes / docker and I can not find anything very concrete ...... I would like to know which version of docker this homologated for kubernetes 1.6?

**Comment by FrederikNS** [comment]
In the [changelog for Kubernetes 1.6.0](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md), in the "Node Components" section it says:

    Drop the support for docker 1.9.x. Docker versions 1.10.3, 1.11.2, 1.12.6 have been validated.

**Comment by ffelicissimo** [comment]
Hi Frederik,

What's the version of ETCD that is recommeded to install with k8s 1.6.1?

**Comment by calebamiles** [comment]
@ffelicissimo, tested etcd version is 3.0.17. Information is in the [CHANGELOG](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#external-dependency-version-information) as mentioned by @FrederikNS. Closing this issue.
