### ISSUE TITLE
Link to k/k/cmd/controller-manager in sig-apimachinery

### ISSUE THREAD

**Issue by MadhavJivrajani** [kubernetes/community#5843]
`k/k/cmd/controller-manager`, which is linked [here](https://github.com/kubernetes/community/tree/master/sig-api-machinery#server-binaries) is no longer existent IIUC. If my understanding is correct, this should be removed. If not removed, then what could we edit the link to? Thank you! 

EDIT
TODO: remove `kubernetes/kubernetes/cmd/controller-manager` from [here](https://github.com/kubernetes/community/blob/1cc043a0b883960ef1cf0374f86b100fce0e4f66/sigs.yaml#L108) and run `make` 

/sig apimachinery
/help
/good-first-issue

**Comment by verma-kunal** [comment]
hey @MadhavJivrajani , can i work on this ?

**Comment by MadhavJivrajani** [comment]
Sure! Go ahead and assign yourself (`/assign`)  😄

**Comment by KamalSinghKhanna** [comment]
Hey is this issue still open ?
I would like to work on this

**Comment by MadhavJivrajani** [comment]
Hey, there's a PR already open to fix this :)
But feel free to pick up another one!

**Comment by KamalSinghKhanna** [comment]
Sure I'll pick another one, 
Thanks!

**Comment by verma-kunal** [comment]
there are various good first isssues for you to start contributing @KamalSinghKhanna !! do ask in the community channel if you'll need any help 🙂
