### ISSUE TITLE
Re-activating a deactivated Slack account

### ISSUE THREAD

**Issue by ruizink** [kubernetes/community#5847]
I just registered in the slack workspace and in the attempt of unifying my slack accounts I ended up deactivating my kubernetes account.

 I was wondering if anyone can help me to re-activate it?

The email I used to register is `mario.rf.santos@********`.

Thanks a lot.

**Comment by mrbobbytables** [comment]
I've gone ahead and reactivated it 👍 
If you have further problems, please feel free to reuse this issue till its all resolved.

Thanks!

/close

**Comment by ruizink** [comment]
I'm in.

Thank you so much! @mrbobbytables
