### ISSUE TITLE
Document the purpose and criteria for NodeConformance tests

### ISSUE THREAD

**Issue by ehashman** [kubernetes/community#5859]
/sig node testing
/kind documentation

Consider renaming to CRIConformance?

See Slack discussion: https://kubernetes.slack.com/archives/C78F00H99/p1623803503028500

Discussed in SIG Node CI Subgroup on 06/23 and 06/16 meetings.

**Comment by unnati914** [comment]
could you guide me for this issue.. i have some idea of it

**Comment by ehashman** [comment]
@unnati914: @SergeyKanzhelev should currently be working on this, please reach out to him.

/assign @SergeyKanzhelev

**Comment by SergeyKanzhelev** [comment]
this is tracked in the enhancement https://github.com/kubernetes/enhancements/pull/3042
