### ISSUE TITLE
Term `master` in contributors/design-proposals/cluster-lifecycle/ha_master.md

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/community#5861]
Hello all!

It will be nice to replace the term `master` with `control plane` or `control plane node(s)` in
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cluster-lifecycle/ha_master.md .

Also, https://kubernetes.io/docs/tasks/administer-cluster/highly-available-control-plane/ needs to be updated accordingly.
![image](https://user-images.githubusercontent.com/46767780/123227597-b2726800-d50f-11eb-8d96-c8aa98c8bd70.png)

**Comment by mrbobbytables** [comment]
Design proposals are in an archived state, they are there for [historical purposes only](https://github.com/kubernetes/community/tree/master/contributors/design-proposals#kubernetes-design-documents-and-proposals) (Theres rules blocking PRs from merging updating them)

The tasks on the website can be updated though, an issue should be filed in [kubernetes/website](https://github.com/kubernetes/website) to get that changed 👍

**Comment by mrbobbytables** [comment]
With that, I'm going to go ahead and close this out. If you have questions, please feel free to reopen 👍 

/close
