### ISSUE TITLE
 JSON format of the SIG metadata

### ISSUE THREAD

**Issue by shekhar-rajak** [kubernetes/community#5862]
Hi team,

Can we have JSON formate of the SIG metadata : https://github.com/kubernetes/community/blob/master/sigs.yaml ? 

I am working on PR https://github.com/kubernetes/contributor-site/pull/222 "All Enhancement proposals in single webpage | KEPs " and basically I want to pull a file simialr to https://raw.githubusercontent.com/kubernetes/community/master/sigs.yaml means a GET request in JSON formate (currently we only have sig.yaml).

Please help me understand how this file is generated or let me know if we can have something that we generate its JSON formate automatically, so that we can use it in Hugo website (since Hugo doesn't suppot YAML version currently, the JSON requirement came into picture)

**Comment by palnabarun** [comment]
AFAIU, this file is the source of truth for the pages in this repository. Hence, it is managed manually.

**Comment by shekhar-rajak** [comment]
I find alternate way. Please refer: https://github.com/kubernetes/contributor-site/pull/222#issuecomment-869222740

closing this.
