### ISSUE TITLE
Kubernetes never cancels PreStop http hook

### ISSUE THREAD

**Issue by Zsolt-LazarZsolt** [kubernetes/community#5863]
Consider the following setup.

Have a main container with a liveness probe and a http prestop hook.
Have a side container running a webserver that is listening on said prestop hook, stalling connections indefinitely.

If the following happens:
- main container start failing the liveness probe (in the example port 8002 is not actually open)
- kubernetes decides to kill the main container, triggers the prestop hook. (sidecontainer listens on the called port 8080)
- side container receives the http request towards the prestop hook, accepting the connection, and stalling it.
- after the terminationGracePeriodSeconds ends kubernetes forcefully kills the main containters
The problem is:
- the connection to the prestop hook never disconnects, the connection is kept alive indefinitely.

Attached the following yaml with a not living livenessprobe and a slow server as side container.
[slowserver.txt](https://github.com/kubernetes/community/files/6732223/slowserver.txt)

A dockerfile and code for the slow server
[slowserver.code.txt](https://github.com/kubernetes/community/files/6732240/slowserver.code.txt)
[Dockerfile.txt](https://github.com/kubernetes/community/files/6732233/Dockerfile.txt)

**Comment by mrbobbytables** [comment]
I'd recommend reposting this as a bug in the [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes) repo. It is unlikely to be answered here. This repo is sort of the "meta" repo for the upstream contributor community.

**Comment by Zsolt-LazarZsolt** [comment]
Thank you for the heads up. Opened in the right place
