### ISSUE TITLE
Link in sig-autoscaling README.md are broken

### ISSUE THREAD

**Issue by sanjimoh** [kubernetes/community#5872]
The below link refers to a non-existing OWNERS file in kubernetes/client-go/scale project. 

https://github.com/kubernetes/community/blob/master/sig-autoscaling/README.md#scale-client

![image](https://user-images.githubusercontent.com/33784301/124415339-48a95800-dd72-11eb-81a3-b8a0803c3af6.png)

I tried creating a PR (https://github.com/kubernetes/client-go/pull/994) to introduce OWNERS file but the PR was closed without merge indicating that the OWNERS file is not required in kubernetes/client-go/scale project (https://github.com/kubernetes/client-go/pull/994#issuecomment-873626894)

As part of this issue, I am looking forward to understand why it is not apt to introduce OWNERS file if the README.md is linked and expecting this file? 

If it is the case, alternatively, can I proceed with updating the README.md to remove this broken hyperlink?

**Comment by mrbobbytables** [comment]
It's entry can be updated by removing it from [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml) then running `make` to update all the locations that reference it.

I'd defer to the leads, @gjtempleton and @mwielgus about removing it or updating it to its new location (if it exists)

**Comment by gjtempleton** [comment]
/remove-lifecycle rotten
Sorry, this got lost in the Github noise and is still valid.

Our annual SIG report has also highlighted this link being broken. Marcin's looking into whether we still need to own that code and if so how we go about denoting ownership.
