### ISSUE TITLE
Create kubernetes cluster without public hosted domain with working k8 dashboard on AWS

### ISSUE THREAD

**Issue by vivekaundkar** [kubernetes/community#588]
I am trying to create a k8 cluster without public hosted domain. I just created a private route 53 zone entry and using this entry and an S3 bucket as inputs, with help of kops able to bring up a kubernetes cluster.
I am able to see load balancer entries, route tables, 3 master and 2 nodes, a bastion server created. It seems everything is in place. Since I used private topology option while creating cluster all instances got private i/p's only bastion instance has public ip. I am able to SSH onto bastion server and to K8 master instance from there. Somehow I am able to make kubectl get nodes command running on k8 master.
Question is where and how to make k8 dashboard up an running?
I am assuming inside my VPC I can start a new instance and run k8 dashboard from there or use bastion server to run k8 dashboard. But how exactly to do that in case I am on right track.

Please suggest if there is an alternate way to create a k8 cluster without public hosted domain with working dashboard and yaml deployment possible from any instance inside same VPC.

I am going to be using VPN as next step so if solution is considering VPN that will be great.

**Comment by jessfraz** [comment]
Hi @vivekaundkar I believe you opened this issue in the wrong repo, would you mind moving it to kubernetes/kubernetes or perhaps joining #sig-aws on slack :)

**Comment by jessfraz** [comment]
also please see @kris-nova's response on https://github.com/kubernetes/community/issues/573#issuecomment-297066002
