### ISSUE TITLE
should TechLeads be mandatory (vs not combo with Chair)

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#5890]
Broken down from issue #5855 

Current state/knowns:
- 1 Chair is required for a SIG per sig-governance.md 
- only two roles that are identified in sig-governance.md is TL and Chair 
- 11 SIGs have explicit entries for TLs in sigs.yaml (combo=chair and TL):
  - Scale
  - Storage
  - Windows
  - Cluster life
  - ContribEx
  - Docs
  - Instrumentation
  - Release 
  - ApiM - 1 chair, 1 TL, 1 combo 
  - Auth - 2 chairs, 2 TLs, 1 combo
  - Cli - 2 chairs, 1 TL, 1 combo 

Why:
- There is a lot of work just for a chair to do "Chairship is not about being an expert on the technical details. It's about organizing the SIG." (current chair)
- operational and community work gets neglected (example: #4289) which helps build sustainabilty and meet governance 
- Helps separate technical decisions from running a meeting (moderation vs ownership/technical decision maker)
- helps with contributor ladder 
- people conflate chair and tech lead 
- [will add more]

Notes
- will collect feedback and discussion here

**Comment by lavalamp** [comment]
Problems I have heard -> my recommended solution

* Lack of documentation -> document better / in better places
* Lack of succession planning -> have deputy chairs / TLs / subproject owners
* Lack of recognition for accomplishments -> OWNERs files, subproject owners, deputy roles
* Lack of formal roles within a SIG to reward/encourage contributors -> OWNERs files, subproject owners, deputy roles

I have not heard of any problem for which "require *every* SIG to have TLs" sounds like it could be a solution.

**Comment by mrbobbytables** [comment]
TLs were split in this PR: https://github.com/kubernetes/community/pull/7160

Going to go ahead and close :)

/close
