### ISSUE TITLE
Broken link in /kubernetes/test-infra/tree/master/prow/cmd

### ISSUE THREAD

**Issue by vaibhav2107** [kubernetes/community#5891]
In https://github.com/kubernetes/test-infra/tree/master/prow/cmd , the line in section Base Images
The container [images](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/images) in images are used as base images for Prow components.
has a broken link.

/assign

**Comment by mrbobbytables** [comment]
@vaibhav2107 if that is a broken link over in test infra, it should be opened in that repo and not the community repo.

**Comment by mrbobbytables** [comment]
Please open a new issue in test infra

/close

**Comment by BenTheElder** [comment]
Please prefer to open an issue instead of CC me 🙃 
I am mostly out right now and the test-infra issue tracker can help route this to the relevant owners.

https://github.com/kubernetes/test-infra/issues/new?assignees=&labels=kind%2Fbug&template=bug-report.md

**Comment by vaibhav2107** [comment]
Opened as a new issue https://github.com/kubernetes/test-infra/issues/22987
