### ISSUE TITLE
fejta-bot is a bit annoying

### ISSUE THREAD

**Issue by graywolf-at-work** [kubernetes/community#5900]
As instructed by fejta-bot

> Send feedback to sig-contributor-experience at kubernetes/community.

I would like to leave a feedback. Having the bot wanting to close the issue
every few months, without any action taken by an actual human feels really cold
and uninviting. I understand that resources might be spread thin, and I'm not
demanding my issues to be fixed, but having the bot try to close them over and
over is just cold.

**Comment by MadhavJivrajani** [comment]
/sig contributor-experience 

Hi, thanks for the feedback!

There's some discussion around this here: https://github.com/kubernetes/kubernetes/issues/103151
if you'd like to follow along and maybe even provide your inputs on there :)

**Comment by spiffxp** [comment]
/close
Agree with @MadhavJivrajani that https://github.com/kubernetes/kubernetes/issues/103151 is the place to discuss this

Consider: what would be a warmer way to express that there isn't sufficient contributor capacity to even look at the issue?  How would you propose increasing contributor capacity to ensure that all issues can be looked at?
