### ISSUE TITLE
REQUEST: New Slack webhook #cluster-api-aws-alerts

### ISSUE THREAD

**Issue by randomvariable** [kubernetes/community#5916]
**GitHub Username:**

@randomvariable 

**Slack Username:**

[Naadir Jeewa](https://kubernetes.slack.com/team/U6RDFQAF5)

**What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?**

New webhook URL for the [#cluster-api-aws-alerts Slack channel](https://kubernetes.slack.com/archives/C019TN4QZ7D)

**Name of Requested Resource:**

Test-Infra Prometheus AlertManager

**Description of Request:**
Follow up from #4641 . I asked @cjwagner to reuse one of the existing webhook URLs as local testing seemed to suggest that AlertManager in another Slack Instance could send to multiple channels using one webhook URL. This didn't work, so we need to use a unique webhook URL for the cluster-api-aws-alerts channel. Thanks.

**Comment by jberkus** [comment]
Is this issue still relevant?

**Comment by jberkus** [comment]
Apparently not.

/close
