### ISSUE TITLE
minikube Netlify fails to deploy for PRs

### ISSUE THREAD

**Issue by andriyDev** [kubernetes/community#5932]
https://app.netlify.com/sites/kubernetes-sigs-minikube/deploys/610c1201f5160400081d4f84

Netlify fails to fetch branches, with no info.

According to https://answers.netlify.com/t/error-fetching-branch-from-github-but-it-used-to-work/10941/6, the solution may be to just clear the cache and redeploy.

**Comment by mrbobbytables** [comment]
Judging from the linked thread, this was done.

FTR - please post these issues in k/org for faster triage. Non k/website related Netlify sites are handled by the GitHub admins.

/close
