### ISSUE TITLE
Improve links to create community membership 

### ISSUE THREAD

**Issue by iamNoah1** [kubernetes/community#5936]
On the [community membership doc](https://github.com/kubernetes/community/blob/master/community-membership.md) the link to [open an issue on the kubernetes/org](https://github.com/kubernetes/org/issues/new?template=membership.md&title=REQUEST%3A%20New%20membership%20for%20%3Cyour-GH-handle%3E) opens an issue without template. Also the link to the template leads to 404. 

Suggestion: 

* Point the `open an issue` link to: `https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.yml&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E`
* Point the link of the issue template to: https://github.com/kubernetes/org/blob/main/.github/ISSUE_TEMPLATE/membership.yml

**Comment by mrbobbytables** [comment]
Thanks for catching that -

The link should be updated to this:
https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.yml&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E

Which is a direct link to the membership form.

/sig contributor-experience
/good-first-issue
/help wanted

**Comment by iamNoah1** [comment]
@mrbobbytables https://github.com/kubernetes/community/pull/5937
