### ISSUE TITLE
REQUEST: New communication about August 2021's community meeting

### ISSUE THREAD

**Issue by nimbinatus** [kubernetes/community#5948]
**What do you want send out?** (Please include a link to a draft)
Announcement for this month's community meeting: https://docs.google.com/document/d/1WLFaTdJ8_fFInSX1bgnnjoWbuqBAXKBeUaLEhBLu2zU/edit?usp=sharing 

Needs to go out on Monday, 16 August 2021.

- [x] I agree that if this is urgent, I will @contributor-comms in #sig-contribex Slack.

/area contributor-comms

**Comment by nimbinatus** [comment]
Tweets and other posts also very welcome...

**Comment by mbbroberg** [comment]
Welp, looks like we missed the target timeline on this one from the issue POV. @nimbinatus, anything we can do to help in the next week to amplify? If not, we can close this and review our issue response to not miss this in the future. Thanks!

**Comment by nimbinatus** [comment]
No worries! @mbbroberg Not yet; we're still getting the lineup together for September, so I don't have the email ready. I'll make a new issue for it when we do. Thank you!
