### ISSUE TITLE
development.md#workflow should emphasize that local repo location is not optional

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/community#597]
I used to be able to work on Kubernetes when its location on my laptop was `$GOPATH/src/github.com/${my github profile name}/kubernetes` (an obvious choice, IMO).  Now that _does not_ work.  The location stated in https://github.com/kubernetes/community/blob/master/contributors/devel/development.md#workflow --- namely `$GOPATH/src/k8s.io/kubernetes` --- is _required_ .  If that location is not used then the `hack/update-bazel.sh` script fails (e.g., see https://github.com/kubernetes/kubernetes/pull/45263#issuecomment-299088432).  It would be good to update development.md#workflow to make it clear that the location it states *MUST* be used.

**Comment by MikeSpreitzer** [comment]
It would also be good to have findable documentation for the `hack/update-bazel.sh` script; that could explain the requirement.

**Comment by xiangpengzhao** [comment]
Mike, the documentation for bazel is here: https://github.com/kubernetes/community/blob/master/contributors/devel/bazel.md

And it explains the requirement:
>## Updating `BUILD` files
To update `BUILD` files, run:
```console
$ ./hack/update-bazel.sh
```
**NOTE**: `update-bazel.sh` only works if check out directory of Kubernetes is `$GOPATH/src/k8s.io/kubernetes`.

**Comment by xiangpengzhao** [comment]
I agree to make the documentation more findable. It would be great to put a new chapter introducing bazel briefly in development workflow.

/cc @bgrant0607
