### ISSUE TITLE
Broken links in sig-scalability documents

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes/community#5970]
Three linked pages don't exist in sig-scalability documents.

1. In [provider-configs.md](https://github.com/kubernetes/community/blob/master/sig-scalability/configs-and-limits/provider-configs.md) 

    Broken link: [Hardware guidelines for administering etcd clusters](https://github.com/etcd-io/website/blob/master/content/docs/v3.4/op-guide/hardware.md)

1. In [formal-scalability-processes.md](https://github.com/kubernetes/community/blob/master/sig-scalability/processes/formal-scalability-processes.md)

   Broken link: [started scaling to 5000](https://kubernetes.io/blog/2017/03/scalability-updates-in-kubernetes-1.6)

1. In [scalability-validation.md](https://github.com/kubernetes/community/blob/master/sig-scalability/processes/scalability-validation.md)

    Broken link: [supporting](http://blog.kubernetes.io/2017/03/scalability-updates-in-kubernetes-1.6.html)

**Comment by niteshseram** [comment]
Hello, I would like to take this up
/assign
