### ISSUE TITLE
Use issue forms for code repositories

### ISSUE THREAD

**Issue by sftim** [kubernetes/community#5972]
For code repositories, we could use [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) rather than issue templates. This might be handy for issue types where people often omit important details.

**Comment by CIPHERTron** [comment]
Heyy @sftim you need any help with this issue? I'm willing to help.

**Comment by sftim** [comment]
I haven't figured out the right way to use these things (and also I haven't asked for help from GitHub, forums etc).

@CIPHERTron if you're happy to try this out, perhaps in your own fork of a repo, and get it working, that'd be really handy!

**Comment by sftim** [comment]
I'm going to pause my work on this because it doesn't seem to be the low-hanging fruit I originally thought it might be.

**Comment by sandipanpanda** [comment]
May be fixed by #6253
