### ISSUE TITLE
[SIG-CLI]: Meeting notes and agenda requires auth

### ISSUE THREAD

**Issue by jaehnri** [kubernetes/community#5982]
The three **Meeting notes and Agenda** links referenced below require authentication:

https://github.com/kubernetes/community/blob/1acc88be28506b3b6a2c8a306f45c4c434631159/sig-cli/README.md#L17

https://github.com/kubernetes/community/blob/1acc88be28506b3b6a2c8a306f45c4c434631159/sig-cli/README.md#L20

https://github.com/kubernetes/community/blob/1acc88be28506b3b6a2c8a306f45c4c434631159/sig-cli/README.md#L23

| ![space-1.jpg](https://user-images.githubusercontent.com/30930799/131399036-d7cddc2d-e3dd-4747-9630-5fc1e2ce7e1c.png) |
|:--:|
| <b>You must have access - Request access or switch to an account that has access.</b>|

I think read-only permission should be granted to everyone, right?

Thanks!

**Comment by lakshya8066** [comment]
Hey @jaehnri thanks for pointing out the issue!
The links seem to work fine for me. Can you check if you are subscribed to the sig-contribex [mailing list](https://groups.google.com/forum/#!forum/kubernetes-sig-contribex)?

**Comment by mrbobbytables** [comment]
Docs are generally shared with the SIGs mailing list (SIG CLI) for edit, kdev for comment and public for view. It is however something only the sig cli leads can adjust.

/remove-sig contributor-experience
/remove-sig docs
