### ISSUE TITLE
Typo in SIG Cloud Provider's CHARTER.md

### ISSUE THREAD

**Issue by budhirajamadhav** [kubernetes/community#5991]
There is a typo in [SIG Cloud Provider CHARTER.md](https://github.com/kubernetes/community/blame/master/sig-cloud-provider/CHARTER.md) at [Line 17](https://github.com/kubernetes/community/blame/master/sig-cloud-provider/CHARTER.md#L17).
It says:

> Testing and testing frameworks to ensure vendor neutrality across all cloud providers

I think it should be like

> Testing frameworks to ensure vendor neutrality across all cloud providers

**Comment by MadhavJivrajani** [comment]
Hi @budhirajamadhav, thanks for sending creating this issue and sending a PR in!

The line in question is not a typo. "Testing and testing frameworks" implies that the SIG's areas of focus include both testing relevant code and maintaining test frameworks (if any) for the purposes of "ensuring vendor neutrality across all cloud providers".

Closing
/close
