### ISSUE TITLE
404 links in `sig-api-machinery/README.md`

### ISSUE THREAD

**Issue by astraw99** [kubernetes/community#5994]
In doc https://github.com/kubernetes/community/blob/master/sig-api-machinery/README.md
In the `Contact` part, the links are invalid and got 404, pls check and fix.

```
Contact
GitHub Teams:
@kubernetes/sig-api-machinery-api-reviews - API Changes and Reviews (API Machinery APIs, NOT all APIs)
@kubernetes/sig-api-machinery-bugs - Bug Triage and Troubleshooting
@kubernetes/sig-api-machinery-feature-requests - Feature Requests
@kubernetes/sig-api-machinery-misc - General Discussion
@kubernetes/sig-api-machinery-pr-reviews - PR Reviews
@kubernetes/sig-api-machinery-proposals - Design Proposals
@kubernetes/sig-api-machinery-test-failures - Test Failures and Triage
```

**Comment by MadhavJivrajani** [comment]
@astraw99 I don't seem to he getting a 404 on those links. Could you please recheck?

**Comment by astraw99** [comment]
> @astraw99 I don't seem to he getting a 404 on those links. Could you please recheck?

In the `Contact/GitHub Teams` part, all the 7 links are invalid.
For example: the 1st link dst is: https://github.com/orgs/kubernetes/teams/sig-api-machinery-api-reviews, got 404.
PTAL thanks.

**Comment by MadhavJivrajani** [comment]
Ah I see what the issue is. Teams can only be accessed by members of the organization. Maybe they shouldn't be hyperlinks then if only org members can access it?
cc @mrbobbytables

**Comment by mrbobbytables** [comment]
Hyperlinks would do the same =/ If you're not a member of the org you won't be able to see the teams.

**Comment by MadhavJivrajani** [comment]
> Hyperlinks would do the same =/ If you're not a member of the org you won't be able to see the teams.

@mrbobbytables  Ah, I meant maybe formatting them as `@team-name` (formatted as markdown) rather than `[@team-name](link-to-team)` (this is how it currently is)

**Comment by mrbobbytables** [comment]
I'd lean towards leaving as is for our org members to be able to see who's a part of the team, but to be honest I wish we could link to entries in k/org instead (our source of truth).  There's really not a good way of doing that though >_<

**Comment by astraw99** [comment]
@MadhavJivrajani @mrbobbytables As these docs are not secret, could you help to move the docs to the community project or give us(contributors) the team access? As contributors we want to see the docs, thanks.

**Comment by mrbobbytables** [comment]
They aren't secret, they're listed here (for api-machinery): https://github.com/kubernetes/org/blob/main/config/kubernetes/sig-api-machinery/teams.yaml

The reason the GH team lists are private is to prevent spamming of them and people requesting to join the teams through GitHub UI instead of via our management mechanism by updating entries in k/org

**Comment by astraw99** [comment]
> They aren't secret, they're listed here (for api-machinery): https://github.com/kubernetes/org/blob/main/config/kubernetes/sig-api-machinery/teams.yaml
> 
> The reason the GH team lists are private is to prevent spamming of them and people requesting to join the teams through GitHub UI instead of via our management mechanism by updating entries in k/org

Got it.
Can I make a PR to add this new link(https://github.com/kubernetes/org/blob/main/config/kubernetes/sig-api-machinery/teams.yaml), and add some tips around the `GitHub Teams` part?

**Comment by mrbobbytables** [comment]
It'd probably be worth calling out in our contributor cheatsheet's community section
https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet#community and/or updating our readme templates  (e.g. https://github.com/kubernetes/community/blob/master/generator/sig_readme.tmpl) to link to k/org as the source of truth.

 We can't link directly to the teams.yaml files as there are some sigs that don't have teams broken out into their own section and instead managed one level up in org.yaml (e.g. https://github.com/kubernetes/org/blob/main/config/kubernetes/org.yaml#L1247) and there are multiple orgs, but not every sig has projects in all orgs.
