### ISSUE TITLE
Meeting notes and agenda link of community management links to an archived file 

### ISSUE THREAD

**Issue by sandipanpanda** [kubernetes/community#5999]
In README of SIG contributor experience under Subprojects: [community management](https://github.com/kubernetes/community/blob/master/sig-contributor-experience/README.md#community-management)
Meeting notes and Agenda link of community-management links to an archived file:

https://docs.google.com/document/d/1qf-02B7EOrItQgwXFxgqZ5qjW0mtfu5qkYIF1Hl4ZLI/edit

The line in file needed to be updated: https://github.com/kubernetes/community/blob/master/sig-contributor-experience/README.md?plain=1#L67.

It should link to the current meeting notes and agenda file of SIG contributor experience:

https://docs.google.com/document/d/1CBz8qV_mD6rbDmTsMuosTOQGRXGhN3d8UrcULUI6Vkw/edit

/sig contributor-experience

**Comment by sandipanpanda** [comment]
@GauravKakoti @lakshya8066 you can clearly see that this issue is already assigned to someone and a linked PR meaning someone is already working on this issue. Don't make multiple duplicate PRs for the same issue. Before assigning yourself an issue, check that it has not been assigned to anyone else. 

You can find a good number of unassigned issues up for grabs here: https://go.k8s.io/help-wanted, Hope that helps. Thank you for understanding and good luck for the new issues!

**Comment by lakshya8066** [comment]
No problem @sandipanpanda I did not mean to interfere. I was adding updates and did not realise you were still working on it.

**Comment by sandipanpanda** [comment]
The APAC meeting is discontinued and should be removed. No need to update the docs. 
https://kubernetes.slack.com/archives/C1TU9EB9S/p1631301227145600?thread_ts=1631301044.145300&cid=C1TU9EB9S
