### ISSUE TITLE
Community sig-contribx README has a broken link

### ISSUE THREAD

**Issue by spzala** [kubernetes/community#600]
https://github.com/kubernetes/community/blob/master/sig-contribx/README.md has a broken link under "Issues", the "Detailed backlog" (https://github.com/orgs/kubernetes/projects/1) hyper link is not working.

**Comment by spzala** [comment]
#dibs

**Comment by idvoretskyi** [comment]
cc @kubernetes/sig-contributor-experience-misc

**Comment by grodrigues3** [comment]
I think this is a github permissions issue.  I think org members can see the org level github projects, but the link is presumably broken (what does it show?) for non org members?

**Comment by grodrigues3** [comment]
@spzala our command is /assign by the way

https://github.com/kubernetes/test-infra/blob/master/commands.md

**Comment by spzala** [comment]
@grodrigues3 - Hello, thanks for looking at it. I presumed it's a public link but regardless as you said it seems broken. I get a '404' Page not found, I suppose we should have 401 or 403. Please let me know if it's OK as it is, I am fine closing the PR or make any changes to my PR. Thanks!

**Comment by spzala** [comment]
@grodrigues3 about the /assign comment - did it mean instead of "dibs" I should use "/assign"? Thanks!

**Comment by spzala** [comment]
@grodrigues3 - :-) well, I found the answer of my question on assign playing with it. Thanks!

**Comment by xiangpengzhao** [comment]
Since it's not an actual problem, could we close this issue?

/cc @bgrant0607 @spzala

**Comment by spzala** [comment]
@xiangpengzhao  Yes, sure. Thanks!
