### ISSUE TITLE
Copy editing of upcoming Katacoda course

### ISSUE THREAD

**Issue by mbbroberg** [kubernetes/community#6003]
**What do you want send out?** (Please include a link to a draft)

https://hackmd.io/LdhuuYCbQCC-0fhDON9RMg?both

- [x] I agree that if this is urgent, I will @contributor-comms in #sig-contribex Slack.

**Comment by mbbroberg** [comment]
Relates to https://github.com/kubernetes/community/issues/5576

**Comment by Debanitrkl** [comment]
https://www.katacoda.com/debanitrkl released the course here, could anyone please review it

**Comment by mbbroberg** [comment]
Looking for someone to do a full review of this -- going through the scenario and reviewing the text along the way. Anyone interested?

**Comment by Debanitrkl** [comment]
Thank you for all the reviews and help, the [host repository](https://github.com/kubernetes-sigs/contributor-katacoda) for the katacoda-scenario has been created. So closing the issue
/close
