### ISSUE TITLE
KubeCon NA 2021: SIG Meet & Greet

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#6011]
The [SIG Meet and Greet](https://sched.co/luKT) will be a part of KubeCon proper this time around. It is scheduled for Wednesday, October 13 from 1:30pm - 2:30pm, right at the beginning of KubeCon in an effort to try and boost interest for attendees to visit the SIG specific sessions during the rest of KubeCon.

If your SIG is interested in having a table, please comment on this thread and I will update the list below

Current participating community groups:
- SIG Auth - @enj 
- SIG CLI - @KnVerey @seans3
- SIG Cloud Provider - @cheftako 
- SIG Cluster Lifecycle - @stealthybox
- SIG Contributor Experience - @parispittman @kaslin 
- SIG Docs - @jimangel
- SIG MultiCluster - @lauralorenz
- SIG Storage - @xing-yang 
- SIG Release - @puerco @jlbutler @reylejano
- SIG Security - @reylejano @tabbysable
- SIG Windows - @brasmith-ms @immuzz

/assign @mrbobbytables @eddiezane

**Comment by eddiezane** [comment]
SIG CLI - @KnVerey @seans3 
SIG Cluster Lifecycle - @stealthybox

**Comment by eddiezane** [comment]
SIG Security - @tabbysable

**Comment by eddiezane** [comment]
SIG Scalability - @marseel

**Comment by johnbelamaric** [comment]
Alas, change of plans. I will NOT be attending in person this time, so I will not be able to represent SIG Architecture for Meet & Greet.

**Comment by immuzz** [comment]
SIG Windows - @immuzz

**Comment by brasmith-ms** [comment]
SIG Windows - @brasmith-ms

**Comment by marseel** [comment]
Unfortunately I won't be attending in person as well (travel ban) so I won't be able to represent SIG Scalability for Meet & Greet.

**Comment by lauralorenz** [comment]
SIG-Multicluster - @lauralorenz

**Comment by mrbobbytables** [comment]
The meet and greet is complete \o/ thanks everyone!
Looks like it went off really well :) 

/close
