### ISSUE TITLE
It should be mentioned for Windows Users to build tools inside WSL environment to run make test

### ISSUE THREAD

**Issue by NikhilSharmaWe** [kubernetes/community#6026]
When I forked the kubernetes/kubernetes repo and run make test it showed me error. But after researching and Mark Rosetti told me that in Windows you need to build tools inside WSL environment. Windows users need to install ubuntu and clone the repo again.

**Comment by NikhilSharmaWe** [comment]
It is mentioned but it should be more clear for the beginner to understand what steps to be taken to set up.

**Comment by mrbobbytables** [comment]
/remove-sig docs
/sig contributor-experience
FYI - the docs sig is for end user docs (https://kubernetes.io), Contributor Experience is responsible for contributor focused docs 👍
