### ISSUE TITLE
Retiring WG Component Standard

### ISSUE THREAD

**Issue by Debanitrkl** [kubernetes/community#6039]
In a recent [mail](https://groups.google.com/g/kubernetes-dev/c/_IN6H0m_QHk/m/566t3cVpCQAJ) to the k-dev mailing list it was mentioned that WG component standard should be dissolved as they were unable to find replacement chairs also the WG hasn't had meetings after [July 07, 2020](https://docs.google.com/document/d/18TsodX0fqQgViQ7HHUTAhiAwkf6bNhPXH4vNVTI7GwI/edit#heading=h.ka0dnu2ck8gf).
This is a tracking issue for the same.
/assign @parispittman 

/sig contributor-experience
/area community-management
/wg component-standard

**Steps:**
- [x] Send an email to kubernetes-dev@googlegroups.com and community@kubernetes.io alerting the community of your intentions to disband or merge. [example]
- [x] Archive the member and lead/chair mailing lists/[GoogleGroups]
- [x] Check the [slack-guidelines.md] for latest process on archiving the slack channel
- [x] Deactivate the zoom license
- [x] Delete your shared SIG/WG/UG calendar
- [x] Ensure that the [youtube-guidelines.md] links are removed and you've uploaded all SIG/WG/UG meetings to date
- [x] Move the existing SIG directory into the archive in kubernetes/community
- [x] GitHub archiving/removing/other transactions: 
- - [ ] <del>Move all appropriate github repositories to an appropriate archive or a repo outside of the Kubernetes orgs</del>
- - [ ] <del>Each subproject a SIG owns must transfer ownership to a new SIG, outside the project, or be retired</del>
- - [ ] <del>File an issue with kubernetes/org if there are multiple repos</del>
- - [ ] <del>Retire or transfer any test-infra jobs or testgrid dashboards, if applicable, owned by the SIG. Work with SIG-Testing on this</del>
- - [x]  Migrate/Remove/Deprecate any SIG/WG labels in labels.yaml
- - [x]  Remove or rename any GitHub teams that refer to the SIG
- - [x] Update sigs.yaml to remove or rename

**Comment by Debanitrkl** [comment]
/wg component-standard
cc @stealthybox @mtaufen

**Comment by mtaufen** [comment]
Should we try to get the youtube videos all transferred to the [official Kubernetes account](https://www.youtube.com/c/KubernetesCommunity)? They're currently mostly in a [separate account](https://www.youtube.com/channel/UCx2prWFkMAY4fkRdf62vG_Q/videos) (we were still doing manual uploads), with some very old ones still hosted by @luxas's personal youtube account.

Playlist: https://www.youtube.com/playlist?list=PL69nYSiGNLP33s-PULNo9F_23b9X2_8GF&jct=Vp_sS1fajiBGHrsJcif75y8cIUoQNA

**Comment by Debanitrkl** [comment]
Yes they should be posted in kubernetes channel.

**Comment by mtaufen** [comment]
Great, how can we get them transferred?

**Comment by Debanitrkl** [comment]
Let me get help from YouTube mods.

**Comment by castrojo** [comment]
There's no way to transfer videos unfortunately, however we can youtube-dl the playlist and reupload it to the main account, which isn't as bad as it sounds, is the playlist complete or do you have anything else to add to it?

**Comment by mtaufen** [comment]
The playlist should be complete.

**Comment by Debanitrkl** [comment]
@mtaufen could you please delete the wg calendar if that stll exists because as an owner you could do that

**Comment by castrojo** [comment]
Ok all set: https://www.youtube.com/playlist?list=PL69nYSiGNLP2-UwxeTIxb_QRXTk7nJg0h

However the descriptions are empty, can one of you provide a generic description? I can then bulk edit the videos with it, ideally if there's a place you want people to end up or links to a resource that might be useful for them is probably best.

**Comment by Debanitrkl** [comment]
@castrojo it's loading like this when I click on the link
![Screenshot_20210928-214552](https://user-images.githubusercontent.com/50622005/135125809-98c50df4-5ac8-47d0-8f91-5d6c331e8982.png)

**Comment by Debanitrkl** [comment]
@mtaufen could you please help with the video description that @castrojo is asking above

**Comment by mtaufen** [comment]
Sure, let's just use the WG description:

```
WG Component Standard focuses on developing a standard foundation (philosophy and libraries) for core Kubernetes components to build on top of. Areas to standardize include configuration (flags, ComponentConfig APIs, ...), status endpoints (healthz, configz, ...), integration points (delegated authn/z, ...), and logging.
```

**Comment by mtaufen** [comment]
The calendar invites should already be deleted, let me know if you see otherwise and I can try to debug.

**Comment by Debanitrkl** [comment]
No it's not showing to me either so it's already deleted 👍

**Comment by parispittman** [comment]
mailing list has now been archived; only group managers can post and edit things with the group. documenting here that contributors@ has access to make any other changes needed.

**Comment by Debanitrkl** [comment]
The YouTube videos are in here https://youtube.com/playlist?list=PL69nYSiGNLP33s-PULNo9F_23b9X2_8GF and with this all the tasks regarding retiring of wg component standard is completed. Thank you @mtaufen and all the contributors who have contributed to this wg. I guess we can now close this issue

**Comment by parispittman** [comment]
confirming zoom has been deactivated

**Comment by mtaufen** [comment]
> The YouTube videos are in here https://youtube.com/playlist?list=PL69nYSiGNLP33s-PULNo9F_23b9X2_8GF 

This link looks like the old playlist (videos still on the old account)?

**Comment by Debanitrkl** [comment]
> > The YouTube videos are in here https://youtube.com/playlist?list=PL69nYSiGNLP33s-PULNo9F_23b9X2_8GF
> 
> This link looks like the old playlist (videos still on the old account)?

@castrojo could you please look into this

**Comment by Debanitrkl** [comment]
The Youtube Playlist is added and we are done with all the tasks
/close
