### ISSUE TITLE
API conventions: HTTP PUT can really create?

### ISSUE THREAD

**Issue by bronger** [kubernetes/community#6041]
On https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#verbs-on-resources, it says:

> PUT /\<resourceNamePlural\>/\<name\> - Update or create the resource with the given name with the JSON object provided by the client.

Is the “or create” really true? FWIW, I get 404 errors PUT’ting a resource that does not exist yet.

/sig architecture

**Comment by ossparvinder** [comment]
Can you please provide an example? According to [RFC2616](https://datatracker.ietf.org/doc/html/rfc2616#section-9.6), you should be able to create a resource using PUT only if you have required privileges.

I assume that also means, user is allowed to assign a unique identifier which is required to create a resource when making a PUT request.

**Comment by bronger** [comment]
I observe this with secrets in Kubernetes 1.21. Being a cluster admin, I cannot place a PUT request on /api/v1/namespaces/default/secrets/certificate-12345 if a secret called “certificate-12345” does not exist. Instead, I have to POST to /api/v1/namespaces/default/secrets. However, if a secret with that name does exist, PUT works.

**Comment by bronger** [comment]
The error data is:

    kind: Status
    apiVersion: v1
    metadata: {}
    status: Failure
    message: secrets "certificate-12345" not found
    reason: NotFound
    details:
      name: certificate-12345
      kind: secrets
    code: 404

**Comment by ossparvinder** [comment]
Thank you, it seems the [API ](https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/#update-replace-the-specified-secret) first tries to find the secret which it expects to exists and is returning 404.

I'm also new to kubernetes codebase hence, cannot find exact code to confirm but it seems the implementation and documentation (API conventions) are not in sync @bronger

**Comment by coderanger** [comment]
SIG-Architecture would be group to ask for an official ruling but I suspect the short-term answer might be something like "no core types use PUT for creation however this can be allowed for aggregated APIs as they see fit".

**Comment by dims** [comment]
cc @liggitt

**Comment by liggitt** [comment]
whether a resource can be created with a PUT request to `.../$group/$version/$resource/$name` depends on the particular resource's storage strategy configuration, specifically the `AllowCreateOnUpdate()` return value.

Most built-in types do not allow this. The ones that do are:
* leases
* endpoints
* events
* limitranges
* services
* runtimeclasses
* roles, rolebindings, clusterroles, clusterrolebindings
