### ISSUE TITLE
REQUEST: New moderator for CIPHERTron of YouTube and Zoom

### ISSUE THREAD

**Issue by CIPHERTron** [kubernetes/community#6042]
### GitHub Username
@CIPHERTron

### Property you'd like to Moderate
YouTube Channel, Zoom

### Username on Property Requested
pritish.samal918@gmail.com

### Requirements

- [x] I am a Kubernetes Org member already
- [X] I have enabled 2FA on my account for the property I would like to moderate (if applicable).
- [X] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @parispittman 

### List of qualifications for this position

- Prior moderation experience
- Links to public discussions showing your moderation experience (if available)
- Any other qualifications

**Comment by parispittman** [comment]
in

/close
