### ISSUE TITLE
REQUEST: New moderator for sandipanpanda of YouTube and Zoom

### ISSUE THREAD

**Issue by sandipanpanda** [kubernetes/community#6047]
### GitHub Username
@sandipanpanda

### Property you'd like to Moderate
YouTube channel and Zoom

### Username on Property Requested
samparksandipan@gmail.com

### Requirements

- [ ] I am a Kubernetes Org member already
- [x] I have enabled 2FA on my account for the property I would like to moderate (if applicable).
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [ ] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@parispittman

### List of qualifications for this position

- Mentee in community manager group mentoring cohort under mentorship of @parispittman

**Comment by parispittman** [comment]
/close

in
