### ISSUE TITLE
 Code Organization - to help new contributors

### ISSUE THREAD

**Issue by ossparvinder** [kubernetes/community#6066]
Hello,

First of all, I want to say we have good documentation on many subjects (and are being updated as gaps are identified).

One thing that I did not find yet, is how such a large code base is organized? So when you look at issues like #6041 or something else you don't know where to start?

It might be helpful to document (if it doesn't exists) to say:

Kubernetes code is organized in following areas:
- shared utilities
- common core
- etc..

Not sure if it is doable but some directions will be helpful!

Thank you.

**Comment by ossparvinder** [comment]
sig/contributor-experience
sig/docs
sig/architecture

**Comment by Debanitrkl** [comment]
There are New contributors workshop organized time and again like here for code walk-through https://www.youtube.com/watch?v=XeHlZuF3BhU. 
Also there is an umbrella issue regarding this https://github.com/kubernetes/community/issues/4549

**Comment by Debanitrkl** [comment]
Also if you need to search for any term in kubernetes repository for that we have https://cs.k8s.io/ so these all things are already taken care of for any other queries regarding k8s please join our slack channel 
/close
