### ISSUE TITLE
Make sure Slack meetings are documented in SIG Readmes

### ISSUE THREAD

**Issue by alisondy** [kubernetes/community#6068]
Some of the slack meetings aren't documented in SIG Readmes

For example:
https://github.com/kubernetes/community/tree/master/sig-contributor-experience#meetings

We need to check that all meetings are documented so folks are going to the right places

TODO

- [ ] Send out message to mailing list to remind people
- [ ] Update contribex readme

**Comment by CIPHERTron** [comment]
Heyy @alisondy I would love to work on this. Could you give a bit more context on this issue? Thanks!
