### ISSUE TITLE
REQUEST: New moderator for onlydole of YouTube

### ISSUE THREAD

**Issue by onlydole** [kubernetes/community#6072]
### GitHub Username
@onlydole

### Property you'd like to Moderate
Kubernetes YouTube Channel

### Username on Property Requested
onlydole@gmail.com

### Requirements

- [X] I am a Kubernetes Org member already
- [X] I have enabled 2FA on my account for the property I would like to moderate (if applicable).
- [X] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [X] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@jeremyrickard 
@cpanato
@jeefy 

### List of qualifications for this position

- Prior moderation experience
As a Developer Advocate, I've been moderating Slack workspaces and YouTube channels for the organizations I worked in over the last few years, including the Kubernetes channel. For SIG Release, I have been helping with uploading videos and updating the Splain integration as aliases have been updated.

I am currently working on some automation for SIG Release around our meeting videos and my account lost access on 9/24.

**Comment by cpanato** [comment]
+1
thanks for working on this!

**Comment by jeremyrickard** [comment]
+1 from me!

/lgtm

/honk

**Comment by onlydole** [comment]
Thank you, @parispittman! I'm in!
