### ISSUE TITLE
Steering Committee Nomination: Stephen Augustus (@justaugustus)

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/community#6074]
Hi Kubernetes Community,

I am self-nominating for the upcoming Steering Committee election.
I've had the opportunity to learn from this wonderful community as a part of my day-to-day work (and play) across the last few years and I'd be honored to serve you all in this capacity!

Best,
Stephen

**Comment by markyjackson-taulia** [comment]
I whole heartedly +1 this

**Comment by jeremyrickard** [comment]
+1 from me!

**Comment by reylejano** [comment]
+1 from me, I'm one of many who have learned a lot from Stephen

**Comment by jimangel** [comment]
+1 @justaugustus has demonstrated, year after year, model community leadership and would be a great fit for the steering committee.

**Comment by tabbysable** [comment]
+1 Stephen is a brilliant, caring, and thoughtful leader. The community stewardship he has demonstrated in SIG Release will be even more valuable on the Steering Committee.

**Comment by danpopSD** [comment]
There is NO ONE more deserving of this role.  This man has demonstrated leadership in every aspect of Kubernetes and his time is now.

**Comment by IanColdwater** [comment]
Strong +1! Stephen would be an amazing addition to the Steering Committee. The project would be lucky to have him.

**Comment by youngnick** [comment]
+1 from me as well. Stephen's gracious, caring, and diligent leadership would serve the project well, I think.

**Comment by mcbenjemaa** [comment]
+1 @justaugustus is potentially a great fit and he really deserve it.

**Comment by puerco** [comment]
+1E10 ! Stephen is a true cornerstone of this community, not only holding it together but also ensuring a path for contributors to join, grow and become the best they (we) can be. Long overdue.

**Comment by cpanato** [comment]
huge +1 I think Stephen has all the skills and leadership to be part of the Steering Committee

**Comment by afirth** [comment]
+1

**Comment by ncdc** [comment]
+1 - thanks for everything you do for this community!

**Comment by xing-yang** [comment]
+1 for Stephen!

**Comment by MoShitrit** [comment]
Easiest +1 EVERRR. @justaugustus is a true inspiration!

**Comment by monadic** [comment]
+1

**Comment by mkorbi** [comment]
+1 🚀

**Comment by qedrakmar** [comment]
+1

**Comment by jailton** [comment]
+1

**Comment by thecrudge** [comment]
+1

**Comment by wilsonehusin** [comment]
+1 🎸

**Comment by mmenbawy** [comment]
+1

**Comment by divya-mohan0209** [comment]
+1 for Stephen ✨

**Comment by puja108** [comment]
+1 for the one and only

**Comment by nimbinatus** [comment]
+1

**Comment by celestehorgan** [comment]
+1 ❤️

**Comment by strongjz** [comment]
+1

**Comment by Huang-Wei** [comment]
+1

**Comment by savitharaghunathan** [comment]
+1 for Stephen ❤️ ✨

**Comment by dlorenc** [comment]
I strongly support this!

**Comment by lachie83** [comment]
+1

**Comment by StabbyCutyou** [comment]
+1

**Comment by benhemp** [comment]
+1 Stephen would be an excellent steward of Kubernetes ecosystem in my estimation.

**Comment by jdumars** [comment]
+1

**Comment by edsoncelio** [comment]
+1

**Comment by bgeesaman** [comment]
+10000000

**Comment by lukehinds** [comment]
+1

**Comment by jgavinray** [comment]
+1

**Comment by mtaufen** [comment]
+1

**Comment by naveensrinivasan** [comment]
+1

**Comment by jayunit100** [comment]
+1

**Comment by pacoxu** [comment]
+1

**Comment by saiyan86** [comment]
+1!!

**Comment by alisondy** [comment]
Per the requirements of the [candidate process](https://git.k8s.io/steering/elections.md), I have verified that Stephen Augustus has the necessary endorsements to qualify to run for steering committee.

Stephen, please prepare a bio for yourself based on the `nomination-template` file in the election directory and submit a PR before October 14th.

**Comment by kikisdeliveryservice** [comment]
last but still gonna give my +1 ❤️

**Comment by vincepri** [comment]
+1

**Comment by navidshaikh** [comment]
+1
