### ISSUE TITLE
Proposed: create Elections subproject of SIG-contribex

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#6084]
Per @parispittman proposal during SIG-Contribex meeting today:

## New Subproject: Elections, SIG-Contribex

The elections subproject would own:

* Recruiting and proposing the Election Committee for the annual Steering elections
* Supporting SIGs and committees in using elections.k8s.io to run other elections for their group (starting in 2022)
* The elections.k8s.io app, shared with SIG-Infra, including /k8s.io/apps/elekto
* A new /elections directory in this repository (historical elections would be moved there)
* Documentation on running elections, and maintenance of that documentation
* /area/elections label (#6083)

It is also possible that this could just be a named role, and not a subproject, but Elections seems to own enough things to make it a de-facto subproject.

Discuss?  If we want to do this, I'll write up a full charter.

/sig contributor-experience

**Comment by parispittman** [comment]
+1 

this would be extremely useful and a good way to organize this work

**Comment by parispittman** [comment]
related: #4586

**Comment by jberkus** [comment]
FYI: this is mainly waiting on me to do all the directory re-arranging as a PR.  That's more complicated than it sounds because moving the elections directory affects our running instance of Elekto.

**Comment by parispittman** [comment]
@jberkus we still need a TL to approve the concept

**Comment by jberkus** [comment]
Ah, point.  Well, no rush.

**Comment by cblecker** [comment]
No objections from me.

@nikhita thoughts?

**Comment by nikhita** [comment]
+1

cc @kubernetes/steering-committee - no action needed, just fyi.

**Comment by nikhita** [comment]
cc @mrbobbytables @alisondy

**Comment by mrbobbytables** [comment]
lgtm from me - it was one of the big things to come out of the retro.

**Comment by cblecker** [comment]
@jberkus you're clear to proceed :)

**Comment by jberkus** [comment]
this is still planned.

/remove-lifecycle stale

**Comment by jberkus** [comment]
This is created.

/close
