### ISSUE TITLE
curate a lead moderator role 

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#6088]
we have several platforms (mailing list, slack, etc) that are all moderated and/or administered in some way with a different set of moderators (some that overlap) for each. between sig-contribex chairs, myself, and other active leads on certain platforms, we all play a part in what could be a carved out role for a moderation lead.

this person would help with:
- training and onboarding all new members
- communicating changes to any of the flow (tech or non tech)
- helping to formulate incident management reporting 
- check-ins with moderators
- recruiting new moderators
- updating documentation
- have a shadow
- what else?

this person should:
- have experience moderating at least one of the platforms for kubernetes, current or in the past
- put 1 hour a week into the role (we are large and have enough random tidbits that this is realistic) 
- expect ~5 hours a month
- grow a shadow
- what else?

this issue will close when/if:
- we've drafted the role and its merged by one of the contribex leads https://hackmd.io/PectKpzeRfy0tkizWUUZjw
- we can't come to an agreement that the role should exist 

/sig-contributor experience

**Comment by parispittman** [comment]
lol dang that hyphen 

/sig contributor-experience

**Comment by jdumars** [comment]
Big +1 - and I would suggest a person + shadow(s) for this. It might also be good to have a calendar/schedule so there's continual coverage.

**Comment by markyjackson-taulia** [comment]
I am interested in this role. Having served as Slack, email, and YouTube moderator, I have knowledge and am also looking to get back in to contributing.

**Comment by jberkus** [comment]
I was going to say: I don't see the point in having such a role *unless* we have a candidate for it.  But: if Marky is available, I'll happily +1 him.

Couple of bits of feedback, neither of which should be considered blockers, just so that we get the role description right:

* we need to poll the existing moderation teams and get their collab on this.  Otherwise it could be seen as "imposing management".
* 5 hours a month is unrealistically low; think 10-15.  I spend 5 hours a month and I'm just a routine Slack mod.

**Comment by markyjackson-taulia** [comment]
I agree that this role would require more than 5 hours per week. 10 - 15 is more what I feel is needed, and I am up for that.
As for gather info from other moderators, this is a very good idea. I do feel this could be done in parallel with the building of the role.

**Comment by parispittman** [comment]
folks: #6278 
your reviews would be very appreciated. thank you!

**Comment by jberkus** [comment]
Also ... should this Lead be responsible for reporting to the CoCC?

**Comment by markyjackson-taulia** [comment]
@jberkus yes, I see that as being critical

**Comment by markyjackson-taulia** [comment]
This is still ongoing but very close to the end.

**Comment by markyjackson-taulia** [comment]
I think this is complete @parispittman also cc @coderanger 

/remove-lifecycle stale

**Comment by markyjackson-taulia** [comment]
This has been completed
/close
