### ISSUE TITLE
Steering Committee Nomination: Lachlan Evenson (@lachie83)

### ISSUE THREAD

**Issue by lachie83** [kubernetes/community#6089]
Hi Kubernetes community - I would like to self nominate for the 2021 Steering Committee election.

I have been a long time member of the community and have served in many different capacities including a 6 month term on the Steering committee. I would like to return to the steering committee and have the opportunity to serve the community for a full term to continue helping meet the needs of the Kubernetes project and ecosystem.

**Comment by youngnick** [comment]
+1

Strewth, you can't go past having a bottler like Lachie on the steering committee again.

**Comment by jeremyrickard** [comment]
I am happy to +1 this nomination ❤️

**Comment by puerco** [comment]
+1 happy to see Lachie on the ballot again :koala:

**Comment by thockin** [comment]
+1

**Comment by markyjackson-taulia** [comment]
+1
![image](https://user-images.githubusercontent.com/16655670/135385909-c3709618-615d-44c3-927c-4200c20693c1.png)

**Comment by droslean** [comment]
+1

**Comment by cpanato** [comment]
+1 yayy!!

**Comment by savitharaghunathan** [comment]
+1 to Lachie!

**Comment by nimbinatus** [comment]
+1

**Comment by detiber** [comment]
+1

**Comment by celestehorgan** [comment]
+1!! ❤️

**Comment by resouer** [comment]
+1

**Comment by Fei-Guo** [comment]
+1

**Comment by marcel-dempers** [comment]
+1 
I had the honor of working with @lachie83  for a week. Was the best week ever!

**Comment by bcosden** [comment]
+1

**Comment by FillZpp** [comment]
+1

**Comment by danpopSD** [comment]
+1 one of the most active, responsive, encouraging people in our community.  Strong support for Lachie.

**Comment by erikaehrli** [comment]
+1 to Lachie!

**Comment by jimangel** [comment]
+1!! 🙌🙌🙌

**Comment by SteveLasker** [comment]
+1 Lachie can navigate the most difficult of situations

**Comment by reylejano** [comment]
+1 🚀

**Comment by bgeesaman** [comment]
+1000000

**Comment by qedrakmar** [comment]
+1

**Comment by aojea** [comment]
+1

**Comment by saiyan86** [comment]
+1 @lachie83 goooo!

**Comment by alisondy** [comment]
Per the requirements of the [candidate process](https://git.k8s.io/steering/elections.md), I have verified that Lachlan Evenson has the necessary endorsements to qualify to run for steering committee.

Lachlan, please prepare a bio for yourself based on the `nomination-template` file in the election directory and submit a PR before October 14th.

**Comment by lachie83** [comment]
Thanks @alisondy - I have submitted PR https://github.com/kubernetes/community/pull/6105 with my bio.

**Comment by devigned** [comment]
+1 x 1000
