### ISSUE TITLE
Steering Committee Nomination: Saiyam Pathak (@saiyam1814)

### ISSUE THREAD

**Issue by saiyam1814** [kubernetes/community#6093]
Hello everyone!
I would like to self nominate for the 2021 Steering Committee election.
I have been part of the Kubernetes community in different ways for many years now- first as an end-user trying to understand how K8s worked. Today, I spend much of my time welcoming and educating new users to the k8s and cloud native community.
I've also been a heavy Kubernetes user for many years at different organizations (Oracle, Walmart Labs, Civo). Most recently I have been involved in shaping up the Chaos Engineering WG.
I'm interested in giving more back to the community and project as a part of the steering community.

/committee steering

**Comment by karthequian** [comment]
+1 this nomination!!

**Comment by mehabhalodiya** [comment]
+1

**Comment by kunal-kushwaha** [comment]
+1

**Comment by shuklaritvik06** [comment]
+1 :)

**Comment by abhibhaw** [comment]
+1

**Comment by PurneswarPrasad** [comment]
+1

**Comment by RealHarshThakur** [comment]
+1

**Comment by AnaisUrlichs** [comment]
+1

**Comment by gvsraju** [comment]
+1 👍

**Comment by Krishnapro** [comment]
+1`👍`

**Comment by IshwarChandra** [comment]
+1👍

**Comment by avinashupadhya99** [comment]
+1

**Comment by sangam14** [comment]
+1 👍

**Comment by chris-short** [comment]
+1

**Comment by LukasGentele** [comment]
+1

**Comment by suchakra012** [comment]
+1 for nomination

**Comment by oshi36** [comment]
+1

**Comment by dmgolembiowski** [comment]
+1

**Comment by kmova** [comment]
+1

**Comment by alisondy** [comment]
Per the requirements of the [candidate process](https://git.k8s.io/steering/elections.md), I have verified that Saiyam Pathak has the necessary endorsements to qualify to run for steering committee.

Saiyam, please prepare a bio for yourself based on the `nomination-template` file in the election directory and submit a PR before October 14th.

**Comment by amolugu** [comment]
+1

**Comment by vidhyasagar7** [comment]
+1
