### ISSUE TITLE
REQUEST: Install Github app for #cert-manager-aws-privateca-issuer channel

### ISSUE THREAD

**Issue by solonish** [kubernetes/community#6096]
**GitHub Username:** @solonish 

**Slack Username:** [Nishanth Solomon](https://kubernetes.slack.com/archives/D02D1JKT9V2)

**What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?** 
Installing GitHub for Slack.

**Name of Requested Resource:**
GitHub for Slack - https://slack.com/intl/en-gb/help/articles/232289568-GitHub-for-Slack#github-for-slack-1

**Description of Request:**
#cert-manager-aws-privateca-issuer channel is for the users of https://github.com/cert-manager/aws-privateca-issuer repository. Posting issues, pulls, statuses, commits, deployments in the slack channel would keep the users well informed of the changes in the repository. To enable notifications GitHub app needs to be added to our slack channel.

**Comment by coderanger** [comment]
Sorry, we do not allow apps for security and privacy reasons. In the case of GitHub, the issue is the near-total lack of access controls.

/close
