### ISSUE TITLE
Broken links on non-code-contributions.md

### ISSUE THREAD

**Issue by Debanitrkl** [kubernetes/community#6099]
While going through the [non-code-contributions.md](https://github.com/kubernetes/community/blob/master/contributors/guide/non-code-contributions.md), I found a broken link on `line 34` , which should indicate to [Meet Our Contributors](https://github.com/kubernetes/community/blob/master/mentoring/programs/meet-our-contributors.md).

For `good-first-issue`:
To solve this we need to update the link on `line 34` of [non-code-contributions.md](https://github.com/kubernetes/community/blob/master/contributors/guide/non-code-contributions.md), which at present looks like this `[Meet Our Contributors](https://github.com/kubernetes/community/blob/master/mentoring/meet-our-contributors.md)`

/sig contributor-experience
/good-first-issue

**Comment by YushChaudhary** [comment]
Thanks For this issue let me fix this.

**Comment by Debanitrkl** [comment]
@YushChaudhary thanks for your interest, I think @BLasan has already assigned him this and working on it, you could look for another issue to work on.

**Comment by YushChaudhary** [comment]
ok

**Comment by YushChaudhary** [comment]
Hay what are these steering commiteee nominations

**Comment by Debanitrkl** [comment]
@YushChaudhary  You can find more about it here https://github.com/kubernetes/community/tree/master/committee-steering also the [k8s.dev](https://www.kubernetes.dev/) is a good place to start with. And join our [slack channel](https://slack.k8s.io/), where all your queries could be answered

**Comment by YushChaudhary** [comment]
Hey Thanks a lot.
