### ISSUE TITLE
Require org members to have a merged PR (if including PRs in an application)?

### ISSUE THREAD

**Issue by ehashman** [kubernetes/community#6110]
I know that this is often an informal requirement among sponsors (it is for me -- open PRs are not sufficient imho), but I am wondering if it should be a formal requirement.

Requiring org members to have a merged PR ensures that they have correctly signed the CLA and are able to interact with our GitHub repos. When individuals become org members, it gives them power over PRs such as applying triage, LGTM and ok-to-test labels. They can also be added to OWNERS files.

Hence, given these privileges, if a membership application is focused on GitHub-based contributions, I don't think it's unreasonable to ask them to have a merged PR.

**Edit:** I've scoped down this first comment to address the core of my suggestion here https://github.com/kubernetes/community/issues/6110#issuecomment-933937596 If a contributor's contributions are mainly outside of GitHub, I don't know that it adds value to impose a requirement of a PR, so let's not distract ourselves with that. However, _if_ PRs are provided as part of an application, I'd like it to be formalized that _open_ PRs are not enough; at least one should be merged.

/sig contributor-experience

**Comment by jberkus** [comment]
If we include kube-sigs, and the possibility of a chicken-and-egg issue (that is, that the PR requires org membership to merge), then this seems OK.

**Comment by ehashman** [comment]
> possibility of a chicken-and-egg issue (that is, that the PR requires org membership to merge)

I've only seen this happen when people try to add themselves to OWNERS files and weren't org members, _usually_ because they were already a kubernetes org member but not kubernetes-sigs (and were bootstrapping a kubernetes-sigs repo).

I would be 100% fine with the PR happening in kubernetes-sigs.

**Comment by coderanger** [comment]
I'll put myself up as an example of someone that probably had no code contributions at the time I was put up for org membership (if I did I'm sure it was like 1 character typo fixes or something), so I think it's definitely a path that exists. It's mostly for folks joining on the community and security sides right now (SIG-ContribEx, SIG-Security, SRT, etc) but that's still a very important path IMO. There are workarounds like contribex-facing folks making some kind of token PR but this feels like it's not the right solution, puts too much emphasis on code as the important factor.

**Comment by ehashman** [comment]
>There are workarounds like contribex-facing folks making some kind of token PR but this feels like it's not the right solution, puts too much emphasis on code as the important factor.

Let me scope down a little bit here---do you have any objection to requiring that if a list of PRs are included in a membership application, at least one of those must be merged?

**Comment by coderanger** [comment]
+1 to that, unmerged PRs don't count for zero but it's very close to zero :) If that's what you are citing as your reasons for joining, I agree it's not a very compelling case.

**Comment by nikhita** [comment]
> However, if PRs are provided as part of an application, I'd like it to be formalized that open PRs are not enough; at least one should be merged.

Big +1 to this.

cc @kubernetes/owners

**Comment by mrbobbytables** [comment]
I am +1 to adjusting the language to reference merged PRs.

**Comment by jeremyrickard** [comment]
+1

**Comment by vincepri** [comment]
+1

**Comment by ehashman** [comment]
Given generally positive response here, I've submitted https://github.com/kubernetes/community/pull/6120
