### ISSUE TITLE
Steering Committee Nomination: Vince Prignano (@vincepri)

### ISSUE THREAD

**Issue by vincepri** [kubernetes/community#6112]
Hi Kube-folks,

I'd like to self nominate for the Steering Committee 2021 election ✨.

Joined the Kubernetes community 3 years ago, have been serving it in multiple forms and shapes. Today, I'm SIG Cluster Lifecycle co-Chair and maintainer of Cluster API, pushing forward the vision to make Kubernetes lifecycle management boring.

I'd love to bring SIG, end-user, and my overall experience to the Steering Committee serving this incredible community even more 😊.

/committee steering

**Comment by jdumars** [comment]
Big +1 from me!

**Comment by jeremyrickard** [comment]
+1

**Comment by cpanato** [comment]
huge +1

**Comment by sbueringer** [comment]
💯  (+1)

**Comment by charleszheng44** [comment]
+1 👍

**Comment by nimbcode** [comment]
+1

**Comment by devigned** [comment]
+1

**Comment by alvaroaleman** [comment]
+1

**Comment by fabriziopandini** [comment]
Big +1

**Comment by randomvariable** [comment]
+ :100:

**Comment by srm09** [comment]
Huge +1

**Comment by tamalsaha** [comment]
+1

**Comment by shysank** [comment]
+1

**Comment by AartiJivrajani** [comment]
💯 (+1)!!

**Comment by ykakarap** [comment]
Huge +1!!

**Comment by embano1** [comment]
No doubts +1, GOOOO Vince!!!!

**Comment by elmiko** [comment]
+1

**Comment by yastij** [comment]
Huge +1

**Comment by frapposelli** [comment]
BIG +1 for Vince

**Comment by detiber** [comment]
+1

**Comment by jberkus** [comment]
Bio is merged.

/close
