### ISSUE TITLE
Steering Committee Nomination: Tasha Drew (@tashimi) 

### ISSUE THREAD

**Issue by tashimi** [kubernetes/community#6118]
Hi all, 

I'd like to nominate myself for the Steering Committee for the 2021 election! 

I've been around the Kubernetes community for five-ish years now, starting off working with the fine folks in SIG-Apps as I tried to understand how application lifecycle management would be handled in this brave new world when I was working on Habitat.sh, and then migrating over to WG-Multitenancy (and eventually becoming the co-chair) when I started thinking about Supervisor and Kubernetes lifecycle management when I began working on Project Pacific at VMware. Since then I also became a co-chair and worked to build up SIG-Usability so we have a place where user research and user experience can be elevated to a top level upstream concern in a way that's never been done in upstream before. I was also on the Code of Conduct Committee for two years, and it gave me unique insight into the health and resiliency of our community. I'd like to continue helping our community grow and evolve as the technology continues to become an underpinning of so many modern platforms.

I think we're at our best when we're working to enable ourselves and our new community members to share their ideas, excitement, and potential. I'd love to help continue the excellent work that's already been done to make this a resilient, friendly, professional community. I'd bring a good perspective from a number of different groups within the community, and consumers of the technology, and I think I'd be a good addition to the SteerCo team! I also have a bunch of ideas about how to make it easier for people to become contributing members of the community I'd love to have the opportunity to drive.

Cheers, Tasha 

/committee steering

**Comment by jdumars** [comment]
Having served with Tasha on the code of conduct committee, as well as seeing the numerous invaluable contributions she has made to our community, I strongly support this nomination!

**Comment by lachie83** [comment]
+1

**Comment by rjbez17** [comment]
+1

**Comment by frapposelli** [comment]
BIG +1

**Comment by celestehorgan** [comment]
+1

Working with Tasha on the CoCC has been an excellent experience! Tasha has so much leadership to offer the project, so much maturity, and such a level head, and would do well in this position.

**Comment by vincepri** [comment]
+1 💯

**Comment by cpanato** [comment]
+1 !!!

**Comment by RinkiyaKeDad** [comment]
+1 I've first-hand experienced the welcoming environment Tasha creates for everyone when I was getting started!

**Comment by detiber** [comment]
+1
