### ISSUE TITLE
Question/Comment on candidate bios for Steering Election

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes/community#6129]
Hey SC election people! 

I had a question/comment, after submitting my candidate bio. 

> All biographical statements should be brief and to the point, with a guideline of around 300 words total for all text. If your statement is excessively long, you will be asked to abbreviate it before it is merged.

It looks like we added a verify script that enforces the 300 character limit but is a little blunt: 

```
for bio in ${STEERING_ELECTION_BIOS} ; do
  [[ -f $bio ]] || continue
  word_count=$(wc -w < "$bio")
  if [[ ${word_count} -gt "300" ]]; then
    echo "${bio} has ${word_count} words."
    invalid_bios=$((invalid_bios+1))
  fi
done
```

I believe this ends up including all the template + SIGs and links to YouTube videos and other stuff, which limits down what you can include in your statements of "What I've Done" and "What I'll Do".  I edited my bio down to meet the verify hook, but I previously had put those to sections into a doc and edited there, following the word count limits. That ended up failing when I finally submitted.   I think those sections are pretty important for voters to make informed decisions, and this feels like we are being a little overly restrictive. 
   
It might be nice for next time, if we can limit the word counting to those sections and exclude template and links?

Thanks!

**Comment by jeremyrickard** [comment]
oooops :) 

/committee steering
/area elections
/sig contributor-experience

**Comment by jberkus** [comment]
Wait, I thought the verify hook was disabled?  I'd asked for it to be disabled.
