### ISSUE TITLE
REQUEST: Comms assistance with SC Election

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#6130]
Contributor-comms:

The Election Committee would like your help with publicizing the timeline to our contributors during the election:

1. The beginning of voting on Oct 18th
2. Final Election Reminder, Oct 29
3. Election results announcement, Nov 7

Voting opens on October 18th, and we would like notification for that to be carried on contributor social media as well as kubernetes-dev.

The results announcement requires a blog post as well as the usual mailing list announcements, and we would appreciate help with that.

/sig contributor-experience
/area contributor-comms
/area elections

**Comment by jberkus** [comment]
Tap tap tap ... is this thing on?

**Comment by cblecker** [comment]
@jberkus You may need to ping @\contributor-comms in slack again

**Comment by chris-short** [comment]
Tweets updated to use https not http

**Comment by jberkus** [comment]
All the messaging is done.  Thanks!

/close
