### ISSUE TITLE
SIG-diagram of the K8s community in this repository needs to be updated

### ISSUE THREAD

**Issue by sandipanpanda** [kubernetes/community#6175]
[SIG-diagram.png](https://github.com/kubernetes/community/blob/master/SIG-diagram.png) and [SIG-diagram.svg](https://github.com/kubernetes/community/blob/master/SIG-diagram.svg) were created 2 years ago and are now outdated. The SIG structure of this community has changed since then. SIG PM, WGs Apply, Component Standard, LTS, machine learning, resource management and Security Audit have been archived, K8s-infra's status has changed from WG to SIG. It will nice if someone volunteers to create a fresh SIG-diagram of this community. 

/sig contributor-experience
/help

**Comment by Debanitrkl** [comment]
Related to #4001

**Comment by mrbobbytables** [comment]
fwiw, I have google slides with the template - its easy to modify and export to png
