### ISSUE TITLE
Update release cycle docs from 3 months to 4 months

### ISSUE THREAD

**Issue by CIPHERTron** [kubernetes/community#6178]
Recently, the release cycle period has been increased from **three** months to **four** months but the [release cycle docs](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/release.md) and the [timeline](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/release-cycle.png) hasn't been updated yet i.e. it still shows a timeline taking into consideration 12 months instead of 16 months. 

Also, the images displaying the timeline of the release cycle are also outdated (referenced below). Those need to be updated too!
- [Image 1](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/release-cycle.png)
- [Image 2](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/release-lifecycle.png)

Apart from the images, there are a few other documentation changes required. For this issue, we'll be mainly dealing with **[The Release Cycle](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/release.md#the-release-cycle)** section in the **[release.md](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/release.md)** file

/sig contributor-experience
/sig release

**Comment by CIPHERTron** [comment]
Just a quick follow up, 
https://kubernetes.io/blog/2021/07/20/new-kubernetes-release-cadence/

⬆️ Here's a blog stating the changes in the release cycle i.e.from 4 releases per year to three releases per year. We can use this to get some context and update the docs.

For the timeline, I think we can use [draw.io](https://draw.io) and make a flowchart kinda thing. Views? @reylejano 

cc: @vedant-kakde

**Comment by kunalchhabra37** [comment]
@CIPHERTron can you please provide 4 month cycle?
