### ISSUE TITLE
Security feature lifecycle

### ISSUE THREAD

**Issue by jedsalazar** [kubernetes/community#6180]
I'm wondering if we should promote features that improve the security of a cluster beyond alpha more rapidly and backport these features to previous K8s versions. For example, Ephemeral Containers has been in alpha since 1.21 which requires a feature gate to enable and will transition to beta in K8s 1.23, after at least 2 K8s releases in alpha. 

Using standard graduation feature timelines for features that improve security restricts improving security to anyone other than bleeding-edge K8s adopters. The official Kubernetes base images ship with distroless for enhanced security and to encourage its adoption more widely in standard workloads, there's currently a dependency on the availability of Ephemeral Containers.

Ephemeral Containers for Distroless base images is just one example. Security-enhancing features should be available in as many environments as possible and rethinking the standard graduation timelines for them could facilitate a safer Kubernetes ecosystem for all.

**Comment by justaugustus** [comment]
cc: @kubernetes/sig-architecture @kubernetes/release-engineering
