### ISSUE TITLE
REQUEST: Slack account reset

### ISSUE THREAD

**Issue by shambannaa** [kubernetes/community#6186]
Hi team,

I am unable to log in to slack as my two-factor authentication app got deleted and I have lost the access code as well.
can you please reset my account so that I can signup and login.

Thanks,
Shambanna.

**Comment by shambannaa** [comment]
@nikhita  @coderanger  can you please reset my slack account?

**Comment by mrbobbytables** [comment]
@shambannaa we need to know the email associated with the slack account that needs to be reset. Once we can verify it we can move to reset it.

**Comment by shambannaa** [comment]
@mrbobbytables sorry for delay my email id is
echidna.shambu@gmail.com

**Comment by shambannaa** [comment]
@nikhita  @coderanger  @mrbobbytables  can you please help ?.

**Comment by mrbobbytables** [comment]
@shambannaa I have disabled 2fa

**Comment by shambannaa** [comment]
Thanks
