### ISSUE TITLE
REQUEST: New moderator for <your-GH-handle> of <k8s property>

### ISSUE THREAD

**Issue by itsMeShon** [kubernetes/community#6194]
### GitHub Username
e.g. (at)itsMeShon

### Property you'd like to Moderate
e.g. kubernetes-dev

### Username on Property Requested
e.g. (at)property_user

### Requirements

- [ ] I am a Kubernetes Org member already
- [ ] I have enabled 2FA on my account for the property I would like to moderate (if applicable).
- [X] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [ ] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- (at)sponsor-1
- (at)sponsor-2

### List of qualifications for this position

- Prior moderation experience
- Links to public discussions showing your moderation experience (if available)
- Any other qualifications

**Comment by coderanger** [comment]
Hi there, welcome to Kubernetes. This form is intended to be filled out by folks requesting moderator permissions. I don't think that's what you were going for? Were you looking for help joining the mailing list maybe?

**Comment by itsMeShon** [comment]
> Hi there, welcome to Kubernetes. This form is intended to be filled out by folks requesting moderator permissions. I don't think that's what you were going for? Were you looking for help joining the mailing list maybe?

I am trying to join the community as a member of the fommunity to work with community in the front end development.

**Comment by coderanger** [comment]
You probably want to join the SIG-UI mailing list then, which you can find here https://groups.google.com/g/kubernetes-sig-ui . Click "Join Group" at the top of that page. Going to close out this ticket since this isn't how you join mailing lists :) Welcome!

/close

**Comment by itsMeShon** [comment]
K thanks

> You probably want to join the SIG-UI mailing list then, which you can find here https://groups.google.com/g/kubernetes-sig-ui . Click "Join Group" at the top of that page. Going to close out this ticket since this isn't how you join mailing lists :) Welcome!
> 
> /close

Thanks!

**Comment by itsMeShon** [comment]
I joined the group. But how can i join this community is there any way to join this community, github community

**Comment by coderanger** [comment]
You find information here https://github.com/kubernetes/community/blob/master/community-membership.md#requirements

But the short version is you have to have already done some work on a Kubernetes project and find 2 existing members to sponsor you.

**Comment by itsMeShon** [comment]
Ok!
