### ISSUE TITLE
active contributor/owner survey

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#6200]
TIMEBOX: for suggested questions or process changes - Tuesday, December 14th at 1pm PT. 

**what**
in preparing sustainability and continuity planning, it would be good if we had some real data for some it. lets create an owners survey - or maybe active contributors? - to find this out. 

**when**
March 29th

**knowns**
- we have the yearly ContribEx survey that we have retro'ed in the past would be good to trim down and/or have multiple times a year
- lots of questions on the contribex survey that are valuable and we shouldn't take away from them

**survey questions**
1- how long have you been in an OWNERs file or a named role in a SIG?
2 - how many owners files are you in and/or named roles do you have?
3 - what drives you/motivates you to continue to maintain your role?
4 - if you are employed by an organization do you feel supported to work on upstream during your work day?
5 - if so, how much time in percentage weekly?
6 - are you encouraged to mentor others OUTSIDE/external of your organization to grow the community, specifically into OWNERs files as a fellow reviewer/approver/etc?
7 - If you didn’t vote in the steering committee election, why not? 
8 - is there anything that we can improve, governance, operations, or other, that would improve your experience upstream? 

**how**
- message to kdev 
- message to OWNERs
- tweet on k8scontributors
- #chairs-and-techleads, #kubernetes-contributors, possibly the announcement bot 
- draft survey: https://www.surveymonkey.com/r/S7M7SCG 

/sig contributor-experience

**Comment by chris-short** [comment]
The survey looks good.

As far as communicating goes, I'd legit hound OWNERS. Open a time period for the survey, email OWNERS three times throughout the time period (reminding fellow OWNERS to tell their friends who are also OWNERS), and maybe email to k-dev at least once (a message of encouragement to take the survey).

**Comment by parispittman** [comment]
sending survey today

**Comment by parispittman** [comment]
sent direct to 408 owners with emails associated to GitHub
