### ISSUE TITLE
Improving the contributor experience of sig contributor experience

### ISSUE THREAD

**Issue by alisondy** [kubernetes/community#6209]
From the mentoring meeting 8th of November

- Better documentation around how folks can get involved in the sig
- More opportunities
- What guides do we need for folks to be able to contribute and get involved in the sig
- how do we surface this information on the contributor site

**Comment by narenarjun** [comment]
Good to see would be :
- getting started with contributing to contributex-sig
- list of checklist 
- what are the roles of a contributor in regards with the contributex-sig

**Comment by alisondy** [comment]
I am bad at labels 😓

**Comment by alisondy** [comment]
Closing this issue as it's too widely scoped and more a goal, that's being implemented through our mentoring subproject


/close

**Comment by alisondy** [comment]
Need to make the points in the description their own issues
