### ISSUE TITLE
Contributor Celebration 2021 Umbrella Issue

### ISSUE THREAD

**Issue by alisondy** [kubernetes/community#6210]
Issue to track the organisation of the contributor celebration

**Comment by narenarjun** [comment]
[TODO]  Need to create a git repo to document and track the progress

**Comment by sandipanpanda** [comment]
Contributor Celebration 2021 Meeting Notes: 
https://docs.google.com/document/d/10AgEBsTAvLP7eAvIOqen6Q47moLnc9ts5QcHMoRl6hI

Dropped it here just for reference.:relaxed:

**Comment by narenarjun** [comment]
[TODO] Need to tidy-up discord and discuss what how to structure the channels in discord

**Comment by sandipanpanda** [comment]
> [TODO] Need to tidy-up discord and discuss what how to structure the channels in discord

Maybe you can edit your previous issue to add this, reduces scroll time.

**Comment by chris-short** [comment]
Probably safe to close this?

**Comment by mrbobbytables** [comment]
Event complete - closing issue

/close
