### ISSUE TITLE
REQUEST: New moderator for pnbrown of YouTube Channel

### ISSUE THREAD

**Issue by pnbrown** [kubernetes/community#6219]
### GitHub Username
@pnbrown

### Property you'd like to Moderate
e.g. discuss.k8s.io, kubernetes-dev
https://www.youtube.com/c/KubernetesCommunity

### Username on Property Requested
e.g. (at)property_user
pnigelbrown@gmail.com

### Requirements

- [] I am a Kubernetes Org member already
- [x] I have enabled 2FA on my account for the property I would like to moderate (if applicable).
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @parispittman 
- @mrbobbytables 

### List of qualifications for this position

- Prior moderation experience
- Links to public discussions showing your moderation experience (if available)
- Any other qualifications

I am currently a moderator on [VMware Cloud Native Apps](https://www.youtube.com/channel/UCdkGV51Nu0unDNT58bHt9bg) and the community manager for [Tanzu Community Edition](https://kubernetes.slack.com/archives/C02GY94A8KT).

**Comment by pnbrown** [comment]
Requested membership to Kubernetes in #3105
https://github.com/kubernetes/org/issues/3105

**Comment by parispittman** [comment]
invited

/close
