### ISSUE TITLE
Update github-workflow diagram to change references from 'master' to 'main'

### ISSUE THREAD

**Issue by wiggitywhitney** [kubernetes/community#6222]
https://github.com/kubernetes/community/blob/master/contributors/guide/git_workflow.png

**Comment by CIPHERTron** [comment]
> /remove-area github-management /area contributor-guide

OOPS! My bad 😅

**Comment by sftim** [comment]
Also see #6290

**Comment by CIPHERTron** [comment]
Just a quick question:
The link to the workflow diagram in the issue description ([this](https://github.com/kubernetes/community/blob/master/contributors/guide/git_workflow.png)) belongs to the **kubernetes/kubernetes** repo whose default branch is yet to be updated to `main`. Do we still need to update this?

If yes, do we need to create a whole new diagram or do we have a way to edit the existing diagram itself?

**cc**: @mrbobbytables @sftim
