### ISSUE TITLE
Establish and Publicize Official Community Survey Process

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#6223]
Comms,

Per today's meeting, we want to make it clear across the contributor base that there's an official survey process for putting out surveys to the community.  Messaging:

1. We can help with surveys and we have experience and surveymonkey and ability to promote on multiple channels
2. Process is [documented](https://github.com/kubernetes/community/blob/master/communication/requesting-survey.md)
3. If you don't go through Comms, you may not use community channels

Additionally we want to message to the community that approved community surveys will always come from either CNCF SM or kubernetes.io Google account and maybe some other sign of approval.

**Comment by chris-short** [comment]
Found this today during the Upstream Marketing meeting: https://www.kubernetes.dev/resources/services/#surveys

**Comment by jberkus** [comment]
/remove lifecycle-stale

I still need to add a survey thing to the main Communications page for this
