### ISSUE TITLE
Add links of respective Project Boards in SIG READMEs

### ISSUE THREAD

**Issue by sandipanpanda** [kubernetes/community#6224]
Project boards are a very useful feature, built like a spreadsheet, project tables give us a live canvas to filter, sort, and group issues and pull requests. 

Kubernetes currently has 48 active project boards: https://github.com/orgs/kubernetes/projects, but they are undocumented in the SIG / WG READMEs.

This reduces visibility for new contributors on the SIGs' / WGs' are current status of work: backlog, planned, in progress, needs help, done, etc., if they are not aware of the respective SIG project boards. Hence, I propose to update the [sig_readme.tml](https://github.com/kubernetes/community/blob/master/generator/sig_readme.tmpl) and other necessary changes to document the respective Project Boards of SIGs / WGs in the READMEs.

As another possible option, these can be [added as a custom content](https://github.com/kubernetes/community/tree/master/generator#adding-custom-content) to the READMEs, to reduce complexity. I find the first option preferable though.
 
/sig contributor-experience
/area github-management

**Comment by sandipanpanda** [comment]
I am willing to help in making necessary changes if the community sees this as an issue.  I would love feedback or suggestions on this.

**Comment by justaugustus** [comment]
I think this would be a great idea!
In favor of the first option: supporting a field for project boards in the generator app

cc: @kubernetes/sig-contributor-experience @kubernetes/owners

**Comment by mrbobbytables** [comment]
The generator and template would be the right place 👍
