### ISSUE TITLE
Contributor Celebration 2021 Comms

### ISSUE THREAD

**Issue by chris-short** [kubernetes/community#6227]
This issue is for the communications regarding the 2021 Contributor Celebration

The Celebration Umbrella issue is here #6210 

The HackMD I'm working from is here: https://hackmd.io/Rw5Lw09pTH-4mUGow40eSw

**Comment by chris-short** [comment]
@jeefy Let me know when you have a landing page URL, please.

@mrbobbytables How is this for initial comms? [https://hackmd.io/Rw5Lw09pTH-4mUGow40eSw#Initial-Comms](https://hackmd.io/Rw5Lw09pTH-4mUGow40eSw#Initial-Comms)

I could not find the original messaging from last year so if anyone has that feel free to pass it along here.

**Comment by Debanitrkl** [comment]
https://groups.google.com/g/kubernetes-dev/c/eZ8BwZT9k9I/m/poDDvJwQBgAJ 
https://groups.google.com/g/kubernetes-dev/c/qsXoUnFDwXk/m/DTC31bI9BgAJ
I guess these 2 are the only communications sent regarding contributor celebration last year

**Comment by jeefy** [comment]
Once https://github.com/kubernetes/contributor-site/pull/258 merges in, it will take over the `k8s.dev/celebration` alias. That's probably the best one for comms. :) 

That said, we also have permalinks for each event, this one's being `k8s.dev/kcc2021`

**Comment by chris-short** [comment]
Save the date sent on Nov 19th: https://groups.google.com/g/kubernetes-dev/c/lwGJo57PVGw

**Comment by CIPHERTron** [comment]
> @jeefy Let me know when you have a landing page URL, please.

https://www.kubernetes.dev/events/kcc2021/

@chris-short here's the link to the landing page if you're still looking for it.

https://k8s.dev/kcc2021
This also works!

**Comment by chris-short** [comment]
Another message went out today: https://groups.google.com/g/kubernetes-dev/c/8b4rLkNEx48

Expectation is another message with more details will go out the next two weeks.

**Comment by chris-short** [comment]
All comms for the contributor summit are complete.
