### ISSUE TITLE
Reactivate the slack account

### ISSUE THREAD

**Issue by shakeerahamed** [kubernetes/community#6230]
I have an account in the slack with email ID shakeer16590@gmail.com
When I tried to get my invite link it is showing user_disabled.
Could you activate my account.
Username : Skr 
Email: shakeer16590@gmail.com

**Comment by coderanger** [comment]
I've emailed you to confirm you control the address, please respond to that email.

**Comment by coderanger** [comment]
Sorry for the delay, user has confirmed account control and it is now reactivated. @shakeerahamed you can do a password reset if needed.

/close
