### ISSUE TITLE
stale bot feedback message is not helpful

### ISSUE THREAD

**Issue by grosser** [kubernetes/community#6232]
```
Please send feedback to sig-contributor-experience at kubernetes/community.
```
... link to an issue template or say what to put in title/body

/sig contributor-experience

**Comment by AvineshTripathi** [comment]
Hey @grosser I am not sure won't this issue come under sig/testing as they are responsible for the bot and stuff. Correct me if I missed anything

**Comment by mrbobbytables** [comment]
contribex is the right one for this 👍 
We have lifecycle commands to flag issues, `/lifecycle frozen` is used for long term issues.
For PRs, we have a lot of issues with them being abandoned and they SHOULD age out.

**Comment by AvineshTripathi** [comment]
Hey @mrbobbytables thank you for clarifying it :-)

**Comment by grosser** [comment]
"we have a lot of issues with them being abandoned and they SHOULD age out."
they should only be age out if the requester abandons them and not the contributors
as in "last comment is by contributor -> age out"
so either contributor closes them say "not going to happen / this is bad" or contributor asks for changes and never gets replies, but not "we never looked at this PR, let's close it"

**Comment by mrbobbytables** [comment]
I did say for PRs, they should age out and never be frozen.

For issues, if they're a long term issue they can be frozen to avoid the stale bot.

**Comment by grosser** [comment]
Yes, "abandoned PRs" should age out, but not "unreviewed PRs".

**Comment by grosser** [comment]
staying alive
