### ISSUE TITLE
sig-network/windows meeting recordings missing.... 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/community#6234]
i think our sig-network weekly videos arent getting recorded in the last month or so ?  @caseydavenport 

i guess we need to fix something in the zoom recording ?

https://www.youtube.com/playlist?list=PL69nYSiGNLP2E8vmnqo5MwPOY25sDWIxb

sig-windows:  last update, Oct 20, 2021

sig-network: last update, Sept 13, 2021

sig-node: all recordings up to date (published yesterday)

Some screenshots i took while checking various `sig * meeting playlists` on youtube... 

![image](https://user-images.githubusercontent.com/826111/142040093-247b99ca-037a-4f0d-b9a8-5d0eec38db57.png)

![image](https://user-images.githubusercontent.com/826111/142040030-1736617b-be75-4a7a-853f-ae66cc09c442.png)

![image](https://user-images.githubusercontent.com/826111/142040366-58ee4f2b-5a65-4c74-a5a3-c48d81c4c835.png)

**Comment by bridgetkromhout** [comment]
I suggest that someone with those zoom credentials check to see if the missing meetings are in the recordings section of the zoom account.

I checked the "videos" (not just the playlists) and it seems like items may be sometimes uploaded in batches. Have we identified the normal course of how the zoom recordings make it onto youtube and into playlists?

**Comment by mrbobbytables** [comment]
The vids should be there, the hold up is that there have been no active YT admins to process the vids. For awhile now its pretty much just been me, and YT stuff frequently winds up the 5th thing on the list.

**Comment by jayunit100** [comment]
so, theres no active youtube admins other then bobby ? wow !

**Comment by endocrimes** [comment]
@mrbobbytables happy to help spread the load a bit if needed

**Comment by rajaskakodkar** [comment]
I am happy to help as well on this :)

**Comment by mrbobbytables** [comment]
@endocrimes @rajaskakodkar thank you!
If you could, please fill out [Moderator request form](https://github.com/kubernetes/community/issues/new?assignees=&labels=area%2Fcommunity-management%2C+sig%2Fcontributor-experience&template=moderator_application.md&title=REQUEST%3A+New+moderator+for+%3Cyour-GH-handle%3E+of+%3Ck8s+property%3E).

**Comment by mrbobbytables** [comment]
The new moderators have been onboarded and backlog published 👍  going to go ahead and close this out.

/close
