### ISSUE TITLE
Issues in the Kubernetes Resource Model write-up

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/community#6235]
I read [https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/resource-management.md] carefully, and noticed some things.

1. The title and/or organization is a bit odd.  The document's title is entirely focused on resources, but look at the outline:
- first there is some introductory/background material, under no section heading, providing context --- and not, so far as I noticed, presenting a resource model;
- the first section with a heading, "Declarative control", is about controllers;
- the next section is "_Additional_ resource model properties".  At this point I start to feel like [Alice](https://www.azquotes.com/quote/692730).

I think it is fair to say that the concepts of resources and controllers are intertwined.  One way I explain the kube control plane is in terms of microservices, after explaining that I take that term to be broadly about independent components and not specifically about imperative RPCs; the interfaces between the kube microservices are not remote procedure calls but rather are objects with desired and reported state.

2. Late in the "API topology and conventions" section there is a brief discussion of the two extension mechanisms (aggregating custom external apiservers, and CRDs).  It is my understanding that the term "custom resource" applies to a resource created via _either_ of the extension mechanisms.  However, the text in that section associates the term "custom resource" with only one of them ("CRDs").  That text also makes the mistake of conflating a resource with its definition object.

3. The "Resource semantics and lifecycle" section starts with a careful walk-through of how a write is handled.  Step 3, "defaulting", uses the word "persisted".  That is not where the actual persistence happens --- right?

4. That walk-through of the handling of a write continues nicely for the first six steps, but then step 7 is not a step at all.  It is named "Idempotence", but its text is just about the fact that the names are defined by the client.  And surely that is a more pervasive issue, arising as early as step 2 "authorization" and continuing on.

5. The step of writing to etcd is not mentioned in that walk-through at all.

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by mrbobbytables** [comment]
Design proposals are there for historical purposes only and not being updated, they do not reflect any current work within the project. Please see the root of the design proposals dir for more info:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/

/close

**Comment by MikeSpreitzer** [comment]
@mrbobbytables : oh, sorry, I did not notice that it is only a design proposal.  I read it because a colleague cited it, also without awareness that it is only a design proposal.  It is easy to find by searching on the Internet.  We should have some maintained document on this subject.  Is there such a thing?

**Comment by mrbobbytables** [comment]
The plan is to actually move all the design proposals out of k/community to an archived repo - we get a lot of people citing them or opening PRs to fix links etc in them =/

It's on the owning SIGs to do what they want with each set of docs. Some maintain up to date copies in their devel directory, but it really varies from sig to sig.
