### ISSUE TITLE
Convert Issue Templates in community repo to GitHub Forms

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#6251]
It would be useful to convert the k/community [issues templates](https://github.com/kubernetes/community/tree/master/.github/ISSUE_TEMPLATE) to the new [GitHub Issue Forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/). They have been used in several repos and have worked out quite well.

Supporting material:
- [GitHub Issue Form Syntax Reference](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)
- [k/org examples](https://github.com/kubernetes/org/tree/main/.github/ISSUE_TEMPLATE)
- [k/kubernetes examples](https://github.com/kubernetes/kubernetes/tree/master/.github/ISSUE_TEMPLATE)

---
/good-first-issue
/help-wanted
/sig contributor-experience

**Comment by Debanitrkl** [comment]
I guess you both @simrangupta234 and @sandipanpanda are doing the same changes, it should be better if you folks should coordinate between each other and take up a part of it and work

**Comment by simrangupta234** [comment]
Yes, you are right but I'm done from my side.
