### ISSUE TITLE
Form  a Batch Working Group

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/community#6263]
Kubernetes historically focused on service-type workloads, support for load balancing, traffic splitting, rolling-updates, spreading, autoscaling and topology-aware routing are few examples of features the community built for service workloads. Stateful workloads are also getting more support with the introduction of CSI, topology-aware volume provisioning and storage capacity tracking to mention a few.

However, support for Batch lagged in Kubernetes core, leading to a challenging migration journey of batch workloads to Kubernetes. Multiple past efforts tried to improve this status, but those efforts lacked continuity, in some cases leading to forked projects outside k8s (including a forked scheduler).

Recently, there has been momentum to improve core k8s support for batch. Examples:
1. Job API enhancements ([indexed job](https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/2214-indexed-job), [suspend jobs](https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/2232-suspend-jobs), [pod deletion cost](https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/2255-pod-cost), [accurate job tracking](https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/2307-job-tracking-without-lingering-pods), [ready pods tracking in jobs](https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/2879-ready-pods-job-status), [ttl after finish to GA](https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/592-ttl-after-finish) and [CronJob to GA](https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/19-Graduate-CronJob-to-Stable))
2. NUMA aware scheduling: https://github.com/kubernetes/enhancements/pull/2787
3. co-scheduling scheduler plugin (https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/pkg/coscheduling)
4. proposal for job-level management: [bit.ly/k8s-job-management](https://bit.ly/k8s-job-management)
5. Incubating scheduler plugins for co-scheduling and capacity-scheduling.

To keep the momentum and coordinate efforts, we would like explore forming a batch SIG or WG.

/sig scheduling
/sig apps

**Comment by ArangoGutierrez** [comment]
++

**Comment by ArangoGutierrez** [comment]
Also [NFD](https://github.com/kubernetes-sigs/node-feature-discovery) project with
https://github.com/kubernetes-sigs/node-feature-discovery/pull/525

**Comment by rochaporto** [comment]
4. seems to be giving a 404.

**Comment by ahg-g** [comment]
> 4. seems to be giving a 404.

Updated the link

**Comment by kniec** [comment]
++

**Comment by denkensk** [comment]
+1

**Comment by denkensk** [comment]
Add CapacityScheduling for batch workloads
https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/pkg/capacityscheduling

**Comment by kerthcet** [comment]
+1

**Comment by alculquicondor** [comment]
cc @kubernetes/steering-committee 

@soltysh for SIG apps

**Comment by ajyounge** [comment]
Yes please!

**Comment by hiboyang** [comment]
This will be great! We have been running Spark on Kubernetes for one year, and have to work around multiple issues. It will be very valuable to have Batch SIG/WG to enhance Kubernetes in this area. Would love to join and contribute to this effort!

**Comment by chenya-zhang** [comment]
+1 this is wonderful

**Comment by k82cn** [comment]
Honestly, prefer to have a WG in CNCF to align other implementation for batch workload, e.g. Volcano & YuniKorn.

**Comment by mrbobbytables** [comment]
There can be collaboration between the two. The big thing is for work to be done within kubernetes, especially within k/k, a kubernetes organizational unit (sig/wg/subproject) makes sense. Especially as one or more SIGs within the org will be responsible for long term maintenance and stewardship of the code, not an external project or organization.

**Comment by yangwwei** [comment]
Greetings from the [Apache YuniKorn (Incubating)](https://yunikorn.apache.org/) community, we love to join this effort in order to build a common API for batch scheduling.

**Comment by k82cn** [comment]
> There can be collaboration between the two. The big thing is for work to be done within kubernetes, especially within k/k, a kubernetes organizational unit (sig/wg/subproject) makes sense. Especially as one or more SIGs within the org will be responsible for long term maintenance and stewardship of the code, not an external project or organization.

hm... my major concern is that: this common API will dependent on k/k's progress and implementation instead of common requirements :)

Two simple examples :
-  `Queue` is one of common & major concepts of batch system, but there's not more discussed after my first proposal. So will we introduce this concept without implementation in k/k? And how about the other concepts ?
- `spec.scheduleTimeoutSeconds ` of scheduling-plugins/co-scheduling was introduced because of default scheduling's implementation (e.g. scheduling framework); but it's not a common requirements to the other implementations :)

**Comment by abin-tiger** [comment]
+1

**Comment by alculquicondor** [comment]
Specific implementation details are not decided. That's precisely why we need the SIG/WG. I agree with @mrbobbytables, even if there is a CNCF WG, we still need to close gaps in kubernetes.

We don't necessarily need a `Queue` API (although that's to be decided). For example, [suspended jobs](https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/2232-suspend-jobs) allows the implementation of job-level queuing without having a k8s implementation.

The existing co-scheduling plugins has some limitations that need to be solved. So I don't think we should consider it's API as de-facto API long term.

**Comment by raravena80** [comment]
We just had a CNCF TOC meeting today and this issue came up. Just FYI the CNCF WG issue: https://github.com/cncf/tag-runtime/issues/38

**Comment by alculquicondor** [comment]
To add a bit more towards having a SIG Batch.

We need a venue to discuss what is the best way to support batch workloads in Kubernetes. Everyone writing controllers for kubernetes should be welcome to collaborate, but we ultimately need to decide what works within the kubernetes architecture.

I think a CNCF WG could dictate orchestrator-agnostic APIs or best practices, but it shouldn't dictate how we build Kubernetes APIs.

**Comment by liggitt** [comment]
_Some_ group within Kubernetes makes sense to me, but I have a hard time seeing a distinct scope for a SIG. The description of the batch work so far seems to sit at the intersection of sig-apps and sig-scheduling (and _maybe_ sig-autoscaling and sig-node, though that's less clear).

Thinking about each of the group options (sig, subproject, or working group), how would you envision the batch discussion/design/implementation work integrating with the existing sigs?

**Comment by yuanchen8911** [comment]
Just wanted to throw out some high level thoughts on the common requirement of k8s batch support.
- Job queue and lifecycle management  
   - [kube-queue](https://github.com/kube-queue/kube-queue)
   - [volcano](https://github.com/volcano-sh/volcano)
-  Advanced scheduling: gang scheduling, capacity scheduling, GPU bin packing, topology-awareness, etc. 
   - Available scheduler plugins: https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/pkg
- High performance (throughput) scalable scheduling
- Easy integration with existing AI/ML/batch applications: Spark, TensorFlow, PyTorch, MPI, etc.
- Kubernetes native and extensible 
  - A single scheduler is preferred and extended via scheduler plugins
 /cc @denkensk

**Comment by yuanchen8911** [comment]
Put aside the different ideas, shall we work together as a single virtual team to create a common forum/group for the topic? @ahg-g, @k82cn, @Huang-Wei , @rochaporto @raravena80 

> https://github.com/cncf/tag-runtime/issues/38

**Comment by k82cn** [comment]
> We don't necessarily need a Queue API (although that's to be decided). For example, suspended jobs allows the implementation of job-level queuing without having a k8s implementation.

That's my concern about the Batch System API/Specification. Most of batch system have `Queue` concept, and it's accepted by most of user; but it seems it'll not include in k/k.

`suspended jobs` is different feature for different scenrios, it's not related to Queue :)

> I think a CNCF WG could dictate orchestrator-agnostic interfaces or best practices, but it shouldn't dictate how we build Kubernetes APIs.

We're going to have a common specification for batch system in CNCF, and have a group of CRDs accordingly.

> Some group within Kubernetes makes sense.

My major concern is that: this common API or specification will dependent on k/k's progress and implementation instead of common requirements :)

As discussed few years ago when we proposed to donate Volcano to k/k, we should not build batch system native in k/k:
- k/k is a platform for other platform, e.g. bath system
- batch system will introduce lots of concepts, e.g. Job dependency, Queue, and also CLI

> Firstly, the solution needs to be Kubernetes native and extensible with ...

Perfer to have a common specification for batch system, and generate a group of CRDs accordingly. It's up to the user or other community to decide how to implement it. For example, in [Volcano](https://github.com/volcano-sh/volcano), we build our own [framework](https://github.com/volcano-sh/volcano/tree/master/pkg/scheduler/framework) based on PodGroup for advanced algorithms:
- [SLA plugin](https://github.com/volcano-sh/volcano/blob/master/docs/design/sla-plugin.md) to resolve starvation
- [Task Topology](https://github.com/volcano-sh/volcano/blob/master/docs/design/task-topology-plugin.md) to improve training performance
- [Elastic policy](https://github.com/volcano-sh/volcano/pull/1887) enhancement for elastic training (e.g. Pytorch)
- [Preemption](https://github.com/volcano-sh/volcano/blob/master/docs/design/preempt-action.md)/[Reclaim](https://github.com/volcano-sh/volcano/blob/master/docs/design/reclaim-design.md) to rebalance resouces between Job & Queue
- [HDRF](https://github.com/volcano-sh/volcano/blob/master/docs/design/hdrf.md) for hierarchical resource sharing
- and so on

**Comment by k82cn** [comment]
> Put aside the different ideas, shall we work together as a single virtual team to create a common forum/group for the topic? @ahg-g, @k82cn, @Huang-Wei , @rochaporto @raravena80
> 
> > [cncf/tag-runtime#38](https://github.com/cncf/tag-runtime/issues/38)

+1, that's why I prefer to host a WG in CNCF to work together cross the community :)

**Comment by Huang-Wei** [comment]
> My major concern is that: this common API or specification will dependent on k/k's progress and implementation instead of common requirements :)

Not quite. I'm open to defining some API like `Queue` even if it's not implemented in k/k yet.

We can see the values of defining generic batching APIs, and I think that's the common goal. It's just we should make it generic and implementation ignostic from day 1, and ensure the APIs to be extensible and backward-compatible.

> that's why I prefer to host a WG in CNCF to work together cross the community

A key aspect is where to host the APIs: (1) native k/k API from day 1, (2) CRDs always, or (3) CRDs in the beginning and migrate back to k/k when it's mature.

For the most benefit of the ecosystem, I'd prefer (1) and hence host a WG in Kubernetes makes more sense. Note that CNI / CSI is a different story as they're more imposed on the data plane and involve local data communication via protobuf, etc. Their key functional bits don't quite go through API server.

**Comment by william-wang** [comment]
> Put aside the different ideas, shall we work together as a single virtual team to create a common forum/group for the topic? @ahg-g, @k82cn, @Huang-Wei , @rochaporto @raravena80
> 
> > [cncf/tag-runtime#38](https://github.com/cncf/tag-runtime/issues/38)

+1. It's great that there will be a group in CNCF to discuss the batch scheduling and accelerate the process.

**Comment by ahg-g** [comment]
> > My major concern is that: this common API or specification will dependent on k/k's progress and implementation instead of common requirements :)
> 
> Not quite. I'm open to defining some API like `Queue` even if it's not implemented in k/k yet.

Exactly, the WG may well collaborate on a queue api hosted in k/k. Those are object APIs, k8s-level interfaces, they need to be hosted in k/k if core kubernetes were to support them.

CNI/CRI/CSI are not object APIs, they are communication interfaces that allows portability across container orchestrators, not k8s-related projects. CNCF can't define object APIs for core k8s, it is the other way around.

> My major concern is that: this common API or specification will dependent on k/k's progress and implementation instead of common requirements :)

I don't think this is a concern, it is in fact the right dependency. Frameworks built on top of k8s are naturally dependent on k8s progress.

> As discussed few years ago when we proposed to donate Volcano to k/k, we should not build batch system native in k/k:

The decision was not "not to support batch", but not to host a new scheduler and job api. The batch working group in k8s will continue the work of enhancing the job api, adding capabilities to support queueing on top of this api, the default scheduler and default autoscaler.

**Comment by k82cn** [comment]
> Not quite. I'm open to defining some API like Queue even if it's not implemented in k/k yet.

If it's not implemented in k/k, why define this in k/k? IMO, CNCF is a good place to host such kind of specification cross communities.

> I don't think this is a concern, it is in fact the right dependency. Frameworks built on top of k8s are naturally dependent on k8s progress.

Does that mean other community have to use k8s scheduling framework and dependent on its progress ?
CRD gives more convience for all developers to build cloud native ecosystem.

> Exactly, the WG may well collaborate on a queue api hosted in k/k. Those are object APIs, k8s-level interfaces, they need to be hosted in k/k if core kubernetes were to support them.

> CNI/CRI/CSI are not object APIs, they are communication interfaces that allows portability across container orchestrators, not k8s-related projects. CNCF can't define object APIs for core k8s, it is the other way around.

How do we define "core" API? 

re CNI/CRI/CSI: it's more about specification instead of rpc or object; and it should be ok for k8s to import it. CNCF WG will try to define a common API/Specification to all related projects, it's up to user to decide which implementation to use; similar to CNI/CSI.

**Comment by ahg-g** [comment]
> > Not quite. I'm open to defining some API like Queue even if it's not implemented in k/k yet.
> 
> If it's not implemented in k/k, why define this in k/k? IMO, CNCF is a good place to host such kind of specification cross communities.

I disagree with the not implemented part. If we are to have an api defined under https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/api, it needs to have an implementation.

> Does that mean other community have to use k8s scheduling framework and dependent on its progress ? CRD gives more convience for all developers to build cloud native ecosystem.

No, I didn't refer to the scheduler framework, I was talking in general about object apis. CRDs allow extending k8s without hosting those apis in core k8s. It does not make sense to me that we define a CRD outside k8s, and then have a core k8s component depend on it. It should be the other way around.

> How do we define "core" API?

Ones that are defined in the staging repo: https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/api


> re CNI/CRI/CSI: it's more about specification instead of rpc or object; and it should be ok for k8s to import it. CNCF WG will try to define a common API/Specification to all related projects, it's up to user to decide which implementation to use; similar to CNI/CSI.

CRDs allow extending k8s without hosting those apis in core k8s, there is nothing preventing frameworks built on top of k8s from defining their own CRDs, and having a batch working group within the k8s community doesn't prevent that either.

I disagree with analogy with CNI/CRI, again those are not applications, they are low level communication protocols that aim to unify across **container orchestrators**, if they were meant to offer a k8s-only specification, it would have been defined under k/k (e.g., v1.Pod).

**Comment by k82cn** [comment]
> I disagree with the not implemented part. If we are to have an api defined under https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/api, it needs to have an implementation.

Does that mean if any new common requirement, we have to implement it in k/k before other community?

> CRDs allow extending k8s without hosting those apis in core k8s. It does not make sense to me that we define a CRD outside k8s, and then have a core k8s component depend on it.

Fistly, I don't think batch system is core to k/k. Schedulilng framework already helps users to build related features, and a common CRD cross communities is better for all related projects. Why do we want to move it into "core" API? Is there any block issue that CRD + framework can not handle? 

Hm...., that raises another question: there're several projects were built based on CRDs in CNCF, which CRDs will be the "core" API of k/k in the future? If any CRDs are considered as core API few years later, does that mean related projects have to dependent on k/k's progress, and implement new feature in k/k firstly if API changed?

> How do we define "core" API?
> Ones that are defined in the staging repo: https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/api

I mean how do we define the scope of core API, regarding the questino above.

> I disagree with analogy with CNI/CRI, again those are not applications, they are low level communication protocols that aim to unify across container orchestrators, if they were meant to offer a k8s-only specification, they would have been defined under k/k (e.g., v1.Pod).

It's more about specification/API, has nothing to do with whether it is an application nor protocol. Batch system is not k8s-only, it's a common requirement to cloud native ecosystem.

**Comment by ahg-g** [comment]
> Does that mean if any new common requirement, we have to implement it in k/k before other community?

There are no mandates in any form or shape in whichever way we go, k8s is extensible and doesn't preclude any direction. But to answer your question, if an API has enough momentum to be implemented as an extension to an existing k/k controller or in a new controller that complements existing ones, then it has to live in k/k.

> It's more about specification/API, has nothing to do with whether it is an application nor protocol. Batch system is not k8s-only, it's a common requirement to cloud native ecosystem.

but that doesn't add up with the 

>  a common CRD cross communities is better for all related projects

CRDs don't unify the whole cloud native ecosystem, CRDs are k8s, if we want to define common APIs that k/k will implement, then they have to be in k/k repo.

I also don't buy that it is practical or even desired to unify the whole batch ecosystem (k8s and non-k8s), I buy that we could try to unify batch over k8s, and in which case the canonical place for defining k8s APIs is k/k.

**Comment by yuanchen8911** [comment]
> There are no mandates in any form or shape in whichever way we go, k8s is extensible and doesn't preclude any direction. But to answer your question, if an API has enough momentum to be implemented as an extension to an existing k/k controller or in a new controller that complements existing ones, then it has to live in k/k.

+1.  

"_Batch is not k8s-only_", but we are discussing k8s support for batch.  IMHO, 
1. The solution (either as core features/APIs inside k8s or k8s extensions as CRDs, plugins and controllers) should be part of kubernetes. 
2.  Which functions/features are core k8s objects/ APIs and what are extensions as CRDs/controllers need to be carefully evaluated, tradeoff between extensibility, performance, compatibility, ease of integration, etc.
3. We'll need to consider the common requirements of existing important batch workloads when we design and define new k8s features.  
4. We'll leverage and integrate the existing features in Volcano and Yunikorn (scheduling, job management, quota, etc.) as much as possible (specs., plugins, CRDs, controllers, ...)

**Comment by reagul** [comment]
++

**Comment by sk8forether** [comment]
I just have a few questions to better understand the scope:
As a k8s user, can I expect the outcome of this project to mean Slurm integration and job scheduling will become a supported feature for k8s clusters?  (Or at least that this integration is one of the goals?)  Will this include MPI jobs on single and multi-node clusters?

And would this integration work hand-in-hand with Singularity/Apptainer?  Right now, Slurm works well with Singularity containers, so my question is on the k8 side.  I think many of us in the HPC community would be delighted to see k8s support for traditional HPC-style batch scheduling on multi-node clusters with MPI and container jobs supported.

**Comment by vsoch** [comment]
++ and I'm wondering how much closer will we be able to get to a k8s cluster acting / feeling a little more like HPC (as someone that is surrounded by it and would absolutely love to use Kubernetes instead!)

**Comment by parispittman** [comment]
based on the conversation so far, it sounds like a working group would be your best bet as it would cross multiple sigs (apps and scheduling at the very least) with a scoped defined time period as working groups are intended to be temporary. the code can live with one of the sponsoring sigs after completion or a sig can be formed (example: wg-k8s-infra to sig-k8s-infra). 

https://github.com/kubernetes/community/blob/master/committee-steering/governance/wg-governance.md

**Comment by raravena80** [comment]
My 2 cents,

The community can organically decide on how they want to work/collaborate, but for clarity CNCF TAGs were setup to encompass all cloud native open source projects.  So from that point of view whether it can be a K8s WG or a CNCF WG, it depends on the scope. If the work/collaboration is going to be only K8s then it can be a K8s WG, if the scope is wider than K8s then it can be a CNCF WG (K8s and other cloud native projects).

In the end it's all about collaborating and getting work done.

**Comment by k82cn** [comment]
> If the work/collaboration is going to be only K8s then it can be a K8s WG, if the scope is wider than K8s then it can be a CNCF WG (K8s and other cloud native projects).

+100 to that, it's better to have a CNCF WG to define the specification cross the projects in CNCF (or maybe broader); and generated CRD/gRPC for all projects to align. It's up to the project to decide to import the CRD directly, or re-implement it themself.

> CRDs don't unify the whole cloud native ecosystem, CRDs are k8s, if we want to define common APIs that k/k will implement, then they have to be in k/k repo.

Recap my question above: there're several projects were built based on CRDs in CNCF, which CRDs will be the "core" API of k/k in the future? If any CRDs are considered as core API few years later, does that mean related projects have to dependent on k/k's progress, and implement new feature in k/k firstly if API changed?

**Comment by ahg-g** [comment]
> I just have a few questions to better understand the scope:
> I just have a few questions to better understand the scope: As a k8s user, can I expect the outcome of this project to mean Slurm integration and job scheduling will become a supported feature for k8s clusters? (Or at least that this integration is one of the goals?) Will this include MPI jobs on single and multi-node clusters?
> And would this integration work hand-in-hand with Singularity/Apptainer? Right now, Slurm works well with Singularity containers, so my question is on the k8 side. I think many of us in the HPC community would be delighted to see k8s support for traditional HPC-style batch scheduling on multi-node clusters with MPI and container jobs supported.

Good questions, and I have one general answer.

This is not a single project, it is a working group that will try to advance the batch case across k8s components. Kubernetes have a process for proposing new features called the KEP process, it goes through sig-specific review (if the changes touches node for example, then sig node will have to approve it, if we plan to add a new controller to kube-controller-manager, then perhaps sig-app or sig-scheduling will need to approve it), has an API review if the enhancement proposes new APIs, and production readiness review. 

The batch working group will help coordinate efforts across sigs, it will include people with expertise and ownership from multiple with special investment in batch. For example, if someone is proposing an enhancement to improve the k8s-slurm integration, then we can bounce those ideas within the working group first and help shape the proposal to give it the highest chance of it being accepted across the sigs that touches it.

**Comment by ahg-g** [comment]
> ++ and I'm wondering how much closer will we be able to get to a k8s cluster acting / feeling a little more like HPC (as someone that is surrounded by it and would absolutely love to use Kubernetes instead!)

In my opinion, any batch enhancement is in scope and wroth discussing. My answer to this question is similar to  https://github.com/kubernetes/community/issues/6263#issuecomment-990576076. I want to stress we are not proposing a project, we are proposing a forum to discuss and advance the batch use case within k8s.

For example, if the HPC enhancement is NUMA-aware placement, then it is within the scope of the working group to help advance a proposal that works between kubelet (sig-node) and the scheduler (sig-scheduling).

**Comment by ahg-g** [comment]
> My 2 cents,
> 
> The community can organically decide on how they want to work/collaborate, but for clarity CNCF TAGs were setup to encompass all cloud native open source projects. So from that point of view whether it can be a K8s WG or a CNCF WG or both, it depends on the scope. If the work/collaboration is going to be only K8s then it can be a K8s WG, if the scope is wider than K8s then it can be a CNCF WG (K8s and other cloud native projects).
> 
> In the end it's all about collaborating and getting work done.

Thanks Ricardo, I completely agree it is all about collaborating and getting work done. 

This is a proposal to form a working group focused on k8s, hence it is in the k8s repo. The group will ideally include experts and contributors to k8s from different sigs who are able to advice and help shape new batch-focused enhancements to k/k. It can certainly collaborate with other groups like CNCF TAGs, and CNCF TAGs can propose enhancements to k8s, at the end of the day anything proposed to be hosted in k/k or wants support from k/k hosted controllers will have to go through the KEP process.

**Comment by ahg-g** [comment]
> Recap my question above: there're several projects were built based on CRDs in CNCF, which CRDs will be the "core" API of k/k in the future? If any CRDs are considered as core API few years later, does that mean related projects have to dependent on k/k's progress, and implement new feature in k/k firstly if API changed?

I think I somewhat indirectly gave my opinion on this question. There are no mandates in any form or shape in whichever way we go. k8s is extensible and frameworks built on top of k8s can choose to depend on the default behavior offered by some of k/k hosted controllers, or alter it and offer its own implementations.

In my opinion, k/k shouldn't depend on externally defined object APIs because k/k is the center of gravity for Kubernetes. Perhaps @kubernetes/api-reviewers can also give an answer to your question.

**Comment by ahg-g** [comment]
> based on the conversation so far, it sounds like a working group would be your best bet as it would cross multiple sigs (apps and scheduling at the very least) with a scoped defined time period as working groups are intended to be temporary. the code can live with one of the sponsoring sigs after completion or a sig can be formed (example: wg-k8s-infra to sig-k8s-infra).
> 
> https://github.com/kubernetes/community/blob/master/committee-steering/governance/wg-governance.md

I agree. I think a working group is the right first step. It will help cultivate expertise across sigs first to help grow strong sig-k8s-batch TLs with ownership of batch specific sub pkgs of existing components.

**Comment by ahg-g** [comment]
> All that being said, we all have a consensus on creating a working group. Can we sort it out first before diving into the technical details? Does a k8s or a CNCF working group really matter? Maybe someone can help me undersand it:-). To me, the most important thing is to have a single team and forum for further discussions!

I think there is a difference. Part of the community is focused on improving the default/core (not sure how else I can describe it) Kubernetes support for batch, and want to develop ownership of those enhancements within k/k even if it takes longer to land. The reason is that k/k has strong commitment towards  production readiness, backward compatibility and API stability. We are proposing to form a WG within k/k that serve the interests of this part of the community. 

As I mentioned in https://github.com/kubernetes/community/issues/6263#issuecomment-990581541, this group can certainly collaborate with other groups like CNCF TAGs, and CNCF TAGs can propose enhancements to k8s, but all has to go through the KEP process; moreover, there are no mandates that one group has on the other.

**Comment by denkensk** [comment]
> So from that point of view whether it can be a K8s WG or a CNCF WG or both, it depends on the scope. If the work/collaboration is going to be only K8s then it can be a K8s WG, if the scope is wider than K8s then it can be a CNCF WG (K8s and other cloud native projects).

I think even if the WG is built under Kubernetes, that doesn't mean we can't work with other projects under CNCF. We even need to collaborate with other communities not part of CNCF, like Spark and Kubeflow.

**Comment by soltysh** [comment]
I'm in the similar camp as a lot of previous comments, let's start simple figure out the outcomes and start with a WG, what follows will depend on the output of the work of that WG.

**Comment by riking** [comment]
I agree with the proposal to start a WG, keeping an eye on exactly how much code ownership ends up involved to decide on whether to turn it into a SIG.

Batch is unlikely to outright own code for a major k/k component, and instead needs to coordinate interlocking changes across several components.

**Comment by yuanchen8911** [comment]
May I try to summarize the debate and the perspectives of both sides? 

Users (@k82cn's proposal): the key goal is a full functional batch (eco)system to run in k8s. The focus will be on features (close to YARN, SLURM, Volcano, Yunikorn, etc), the compatibility with existing batch frameworks, a broad collaboration and a large scope across multiple projects and communities. 

Kubernetes teams (@ahg-g's proposal): the goal is to enhance and extend kubernetes to offer necessary features and functions to support batch on k8s. Maintaining kubernetes' reliability, stability, compatibility and extensibility is critical.  Extended features and a batch ecosystem can be built around the core k8s functions/APIs. 

They are different perspectives, but I don't think they are really conflicting with each other.  

1. The needs of k8s featues for batch should come from users, use cases and workloads.  
2. Based on the requirements, new k8s features/extensions/APIs should be identified and developed within kubernetes first.
3. Additional features, supports and batch systems can be built around it. 

If my above observation is valid and assume a kubernetes working group won't prevent a broad collaboration across  teams/projects/communities, a k8s working group might be a better choice since we first need to develop core features and components inside kubernetes. 

Again, let's try to create a working group and include users, k8s developers, contributors/developers from other related projects inside and outside of CNCF. 

Just my 2 cents.

**Comment by ahg-g** [comment]
I feel we have reasonable support to at least send a proposal, we will do so Monday and let this bake over the weekend.

**Comment by ravisantoshgudimetla** [comment]
+1 to the wg

**Comment by dims** [comment]
sounds like a plan @ahg-g

**Comment by Huang-Wei** [comment]
+1 to the batch wg.

**Comment by k82cn** [comment]
>> Recap my question above: there're several projects were built based on CRDs in CNCF, which CRDs will be the "core" API of k/k in the future? If any CRDs are considered as core API few years later, does that mean related projects have to dependent on k/k's progress, and implement new feature in k/k firstly if API changed?

> I think I somewhat indirectly gave my opinion on this question. There are no mandates in any form or shape in whichever way we go. k8s is extensible and frameworks built on top of k8s can choose to depend on the default behavior offered by some of k/k hosted controllers, or alter it and offer its own implementations.

It's more about the rule to define "core" API instead of implementation.

> As I mentioned in #6263 (comment), this group can certainly collaborate with other groups like CNCF TAGs, and CNCF TAGs can propose enhancements to k8s, but all has to go through the KEP process; moreover, there are no mandates that one group has on the other.

That's ok if this WG only focus on k/k. And CNCF WG will try to align differentiation cross CNCF projects.

**Comment by hex108** [comment]
+1, there are more and more batch workloads running on Kubernetes, and we are running big data applications on it.

**Comment by charleszheng44** [comment]
+1

**Comment by sk8forether** [comment]
@ahg-g  Please let me know if you need anything in the form of example use cases.  I can contribute a bit more about our project at Cornell involving weather modeling HPC applications (that required MPI communication), containers, and kubernetes (see our [Tech Report](https://arxiv.org/abs/2109.12186) on arXiv).  Note: we did not use batch scheduling for this, but it is a good use case for it if it were available with a low barrier to implement for projects like this.

**Comment by alculquicondor** [comment]
I just sent the formal WG formation request to kubernetes-dev@

If we get approved, a next step is establishing a time for bi-weekly meetings. Then we can plan agendas to discuss specific topics in a meeting.

**Comment by jhskone** [comment]
+1 to the batch wg.

**Comment by SergeyKanzhelev** [comment]
@ahg-g how much of SIG Node involvement do you envision in this working group? Based on description it is mostly scheduling and apps?

**Comment by ahg-g** [comment]
The concrete ones I have in mind are NUMA and retries based on exit codes (https://github.com/kubernetes/kubernetes/issues/17244); but may be there are other issues.

**Comment by chenyanjunyjy** [comment]
+1 this is wonderful

**Comment by wsxiaozhang** [comment]
+1 to the Batch WG

**Comment by dmatch01** [comment]
@alculquicondor Has the WG been approved?  Any update?

**Comment by alculquicondor** [comment]
Here is the status: https://github.com/kubernetes/community/pull/6299#issuecomment-1034033559

**Comment by alculquicondor** [comment]
wohoo! Thanks everyone for supporting the requests. We still have some work to do.

/reopen

- [ ] Create mailing list
- [ ] Create slack channel
- [ ] Setup zoom
- [ ] Create meeting notes doc

**Comment by alculquicondor** [comment]
We have created the slack channel `#wg-batch` and we have a doodle that will be used to determine a meeting schedule: https://doodle.com/poll/8abtcy5m4dzac7cc

**Comment by vsoch** [comment]
Is this in the CNCF slack? I don't see it, but I see an old #batch-wg

**Comment by alculquicondor** [comment]
kubernetes slack, as this is a kubernetes WG

**Comment by vsoch** [comment]
oops don't mind my stupidity, :laughing:

**Comment by riking** [comment]
Seems like work has moved to other issues.

/close
