### ISSUE TITLE
[ML Migration] group name for new k-dev mailing list 

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#6274]
umbrella #5877 

TIMEBOX ON VOTE: Tuesday, Dec 14th 1pm PT

this warrants a separate issue so we can poll/vote/decide on the naming convention for the upcoming mailing list migration from kubernetes-dev@googlegroups to __@kubernetes.io

purpose of the group:
news and events closest to the source; the contributors and owners 

options - please use emoji reactions per option for your vote:

1- dev@kubernetes.io (short version of kubernetes-dev@kubernetes.io; popular oss method of <project-dev@>) 🚀 
2- upstream@ (describing the where and not the who) 👀 
3- builders@ (describing the who without community or contributors; see below) 😄 
4- people@ (same as above) 🎉 
5- kubernetes-dev@kubernetes.io (keep it the same regardless of length or redundancy) ❤️
6- main@ (emoji react on the comment since we ran out of emojis) [comment](https://github.com/kubernetes/community/issues/6274#issuecomment-989709741) 

FYI
contributors@ is taken as the 'official comms' email of the project when its needed
community@ (would need to be repurposed, sitting idly now and was an events point of contact for elections etc

**Comment by nimbinatus** [comment]
what about builders@ ?

**Comment by jberkus** [comment]
Vote here for dev@

The existing lists can't easily be repurposed.

projectname-dev@ is a common convention as the "first" mailing list for many OSS projects, so I believe that folks are used to it even if they aren't aware of what "dev" is short for.

"upstream", in my experience, is not a familiar term to a lot of people, particularly those for whom English is not their first language.

**Comment by pnbrown** [comment]
supporter@ ?

I also like builder

**Comment by sandipanpanda** [comment]
How about to appreciate and honor any and every type of contribution that people have made to the Kubernetes community so far, we rename it to
people@kubernetes.io. :heart:

**Comment by justaugustus** [comment]
Maybe a bit of an internet colloquialism, but we are actively renaming a bunch of our default repo branches to it...
What about main@ ?

**Comment by mrbobbytables** [comment]
After thinking more about it, I'm still in favor of referring to it as 'dev'. Contributors or community would be my general go-to options, but those are taken by other community owned accounts. The other thought of discuss already references our end user forum. I think we're stretching it trying to find other terms.  It's also the pattern we've asked people to follow when creating slack channels:
- `<project>-users` - for end user focused discussion
- `<project>-dev` - for contributor focused discussions

**Comment by Atharva-Shinde** [comment]
These are the names I came up with as I was thinking of names describing the purpose of the mailing list-
1. discussions@kubernetes.io 
2. forums@kubernetes.io

**Comment by tao12345666333** [comment]
How about called kube-daily@ ?

Because it will contain news and events and some other information.

**Comment by parispittman** [comment]
https://github.com/kubernetes/k8s.io/pull/3217

**Comment by parispittman** [comment]
Thanks everyone for participating! 
dev@kubernetes.io it is

/close
