### ISSUE TITLE
[ML Migration] Post migration: kdev mailing list 

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#6275]
Umbrella #5877 

Things to do once the group has been created.

1. run a cs.k8s.io on k-dev@ and kubernetes-dev@ and change all respective instances to dev@kubernetes.io (https://groups.google.com/a/kubernetes.io/group/dev)
1.5 also google it to see what comes up and make the changes to the front page search results
  -pull for community repo #6311 
  -need to look at all repos
  -need to look at google search results 
  
2. have leads change all docs starting most notably with meeting invites and any open work collaboration docs
 -have leads also check that contributors@ is the owner
 -if contributor@ is already an owner, we can help add to docs 

3. Forward any active conversations to the new list 

what else?

**Comment by jberkus** [comment]
2. is going to be a HUGE effort.  Don't forget that many, many docs don't belong to current leads.  We need to treat that task as the major, months-long effort that it will be; we need a team in charge of it.

**Comment by jberkus** [comment]
Also:

What about ownership of calendar items?

**Comment by parispittman** [comment]
@jberkus calendar invites should be owned by the SIGs shared calendar for events https://github.com/kubernetes/community/blob/master/communication/calendar-guidelines.md#establishing-a-new-meeting

and then shared with contributors@ with full access to change

**Comment by chetak123** [comment]
Hey @parispittman I have changed all instances of k-dev@ and kubernetes-dev@ to dev@kubernetes.io in Kubernetes/community. If this is ok then I will start changing in other repositories
Thanks.

**Comment by mrbobbytables** [comment]
@parispittman I think this is safe to close now? Are there any follow up AIs?

**Comment by parispittman** [comment]
@mrbobbytables - need to audit #2 for meeting agendas at the very least but then I'll close

**Comment by parispittman** [comment]
we are officially good with this!! 🚀
