### ISSUE TITLE
How are limits and requests default values applied if more then one limitrange resource is created in a namespace?

### ISSUE THREAD

**Issue by ashishth09** [kubernetes/community#630]

**Comment by ashishth09** [comment]
I am sorry if this is not the right place to ask this question.

**Comment by ashishth09** [comment]
For example , is the min of all limitranges makes up the overall min for a container. What about the default request then? If more than one default requests are there because there are more than one limit range resource which one is picked?

**Comment by davidopp** [comment]
Please ask on the kubernetes-users mailing list
https://groups.google.com/forum/#!forum/kubernetes-users
or on StackOverflow
https://stackoverflow.com/questions/tagged/kubernetes
