### ISSUE TITLE
REQUEST: New Slack Assistant

### ISSUE THREAD

**Issue by Anita-ihuman** [kubernetes/community#6329]
### GitHub Username

@JimBugwadia

### Slack Username

@Jim Bugwadia

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

Bot

### Name of Requested Resource

Peritus Assistant & Connector

### Description of Request

We would love to set up Peritus on the Kyverno Slack channel to help moderate quick responses to questions asked in the channel.

Peritus is slack assistance that recommends answers and experts responses from public conversations in the slack channel.
- Peritus Assistant for Slack https://slack.com/apps/A0245BNBC0G-peritus-assistant
- Peritus Connector for Slack https://slack.com/apps/A027CU2L7P0-peritus-connector

**Comment by mrbobbytables** [comment]
This is a hard -1 from me. Peritus is far too invasive and does things that we definitely do NOT want to enable such as the "Find and Connect with Top Experits" and it tries to assemble developer profiles without allowing people to OPT IN to that sort of thing.

**Comment by markyjackson-taulia** [comment]
Also a -1 from me. This will do things that are not ok imo.

**Comment by coderanger** [comment]
Firm -1 from me as well, going to close this since I think we have strong consensus.

I would recommend investigating CNCF Slack if you would like a more liberal approach to integrations.

/close

**Comment by Anita-ihuman** [comment]
Alright,
Thank you all for your feedback regards this issue.

Will get the feedback to my team.

**Comment by JimBugwadia** [comment]
@coderanger @mrbobbytables @markyjackson-taulia - thanks for the feedback. We were under the impression this was an approved bot for CNCF projects, and hence wanted to try out. Totally understand the concerns.

**Comment by coderanger** [comment]
@JimBugwadia It might be, CNCF Slack is independent of us and we have very different policies.

**Comment by mrbobbytables** [comment]
We are very strict because slack is pretty much enable for all or none =\ There is no granular permissions, no way of opting in. We don't even have the newer GitHub slack plugin enabled because of some of these issues.
