### ISSUE TITLE
cleanup emeritus_reviewers and emeritus_maintainers from OWNERS files across kubernetes orgs

### ISSUE THREAD

**Issue by dims** [kubernetes/community#6334]
### Describe the issue

Following up from https://github.com/kubernetes/community/pull/6333#issuecomment-1011289104 and https://github.com/kubernetes/community/pull/6333#issuecomment-1011309609

We need to cleanup https://cs.k8s.io/?q=emeritus_reviewers&i=nope&files=OWNERS*&excludeFiles=&repos= and https://cs.k8s.io/?q=emeritus_maintainers&i=nope&files=OWNERS*&excludeFiles=&repos= looks like we need to clean them all up

Original discussion in https://github.com/kubernetes/community/pull/3627#issuecomment-487253671

Also see https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#owners for the list of official fields

Why are we solving this issue?
 - We need the OWNERS file to have the correct structure so it is parsable by tools

To address this issue, are there any code changes? If there are code changes, what needs to be done in the code and what places can the assignee treat as reference points?
- Yes, click on the url(s), checkout the repositories which have `emeritus_reviewers` or `emeritus_maintainers` in their OWNERS files, submit a patch that removes these sections

Does this issue have zero to low barrier of entry?
- Yes.

How can the assignee reach out to you for help?
- Yes. on sig-contribex

**Comment by dims** [comment]
@Garima-Negi found more problematic repositories / files:

https://cs.k8s.io/?q=%5E(emeritus%7Cemeritus-approvers%7Cemeritus_approver%7Cemeritus_maintainers%7Cemeritus_reviewers%7Cowners)%3A&i=nope&files=OWNERS*&excludeFiles=&repos=

**Comment by dims** [comment]
So the idea here is to open a PR in each repository to remove the section with the wrong key namely:
```
emeritus
emeritus-approvers
emeritus_approver
emeritus_maintainers
emeritus_reviewers
owners
```

When the reviewers ask we point them to this issue and say that the allowed keys are one of those mentioned here:
https://github.com/kubernetes/test-infra/blob/eb87a9362476e00852ac398a2b6417d1f01d4b48/prow/repoowners/repoowners.go#L57-L60

or `emeritus_approvers` (per conversation in https://github.com/kubernetes/community/pull/3627#issuecomment-487253671)

ping me on slack or here if there are any push backs.

Also if someone else can help you, please carve out which repositories you each will tackle as there are a bunch of them.

**Comment by dims** [comment]
Oh! sorry if you see `emeritus-approvers` or `emeritus_approver` you can change it to `emeritus_approvers` anything else you can delete and follow what the reviewers guidance if they would like the names in another section.

**Comment by dims** [comment]
@Garima-Negi i've updated search url in https://github.com/kubernetes/community/issues/6334#issuecomment-1011435747 and opened 2 PR(s) for `kubernetes/kubernetes` and `kubernetes/test-infra` to unblock some other stuff i am doing.

**Comment by peizhouyu** [comment]
> /assign

hi, @dims @Garima-Negi  i've updated `kubernetes-csi/csi-test`, other things  about `kubernetes-csi`  I'm doing. Thanks.

**Comment by Garima-Negi** [comment]
@dims what do we update `emeritus-maintainers` to ?

**Comment by dims** [comment]
@Garima-Negi yes please.

**Comment by pohly** [comment]
Please don't submit PRs for this against individual kubernetes-csi repos. The OWNERS_ALIASES file needs to be changed in csi-release-tools and then we'll copy it from there (semi-)automatically into the other repos.

**Comment by dims** [comment]
@peizhouyu @sreekaransrinath @Garima-Negi here's a full set as of right now

```
32:ERROR: unable to parse owners file at https://raw.githubusercontent.com/kubernetes/kube-openapi/master/OWNERS url - error unmarshaling JSON: while decoding JSON: json: unknown field "emritus_approvers"
48:ERROR: unable to parse owners file at https://raw.githubusercontent.com/kubernetes-client/csharp/master/OWNERS url - error unmarshaling JSON: while decoding JSON: json: unknown field "reviewer"
49:ERROR: unable to parse owners file at https://raw.githubusercontent.com/kubernetes-client/java/master/OWNERS url - error unmarshaling JSON: while decoding JSON: json: unknown field "reviewer"
468:ERROR: unable to parse owners file at https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-ibmcloud/main/OWNERS url - error unmarshaling JSON: while decoding JSON: json: unknown field "emeritus_reviewers"
500:ERROR: unable to parse owners file at https://raw.githubusercontent.com/kubernetes-sigs/cluster-api/main/OWNERS url - error unmarshaling JSON: while decoding JSON: json: unknown field "emeritus_maintainers"
507:ERROR: unable to parse owners file at https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-aws/master/OWNERS url - error unmarshaling JSON: while decoding JSON: json: unknown field "emeritus_maintainers"
533:ERROR: unable to parse owners file at https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-ibmcloud/main/OWNERS url - error unmarshaling JSON: while decoding JSON: json: unknown field "emeritus_reviewers"
560:ERROR: unable to parse owners file at https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-openstack/master/OWNERS url - error unmarshaling JSON: while decoding JSON: json: unknown field "emeritus_maintainers"
767:ERROR: unable to parse owners file at https://raw.githubusercontent.com/kubernetes/kube-state-metrics/master/OWNERS url - error unmarshaling JSON: while decoding JSON: json: unknown field "emeritus-approvers"
789:ERROR: unable to parse owners file at https://raw.githubusercontent.com/kubernetes-sigs/metrics-server/master/OWNERS url - error unmarshaling JSON: while decoding JSON: json: unknown field "owners"
797:ERROR: unable to parse owners file at https://raw.githubusercontent.com/kubernetes-sigs/prometheus-adapter/master/OWNERS url - error unmarshaling JSON: while decoding JSON: json: unknown field "owners"
1230:ERROR: unable to parse owners file at https://raw.githubusercontent.com/kubernetes-csi/csi-lib-fc/master/OWNERS url - error unmarshaling JSON: while decoding JSON: json: unknown field "reviews"
1231:ERROR: unable to parse owners file at https://raw.githubusercontent.com/kubernetes-csi/external-attacher/master/OWNERS url - error unmarshaling JSON: while decoding JSON: json: unknown field "emeritus_reviewers"
1232:ERROR: unable to parse owners file at https://raw.githubusercontent.com/kubernetes-csi/external-provisioner/master/OWNERS url - error unmarshaling JSON: while decoding JSON: json: unknown field "emeritus_reviewers"
1233:ERROR: unable to parse owners file at https://raw.githubusercontent.com/kubernetes-csi/external-resizer/master/OWNERS url - error unmarshaling JSON: while decoding JSON: json: unknown field "emeritus_reviewers"
1234:ERROR: unable to parse owners file at https://raw.githubusercontent.com/kubernetes-csi/node-driver-registrar/master/OWNERS url - error unmarshaling JSON: while decoding JSON: json: unknown field "emeritus_reviewers"
```

**Comment by Garima-Negi** [comment]
PRs opened for 
- kubernetes/kube-openapi
- kubernetes/kube-state-metrics
- kubernetes-client/csharp
- kubernetes-client/java

**Comment by Garima-Negi** [comment]
for kubernetes-csi, I have created this PR - [https://github.com/kubernetes-csi/csi-release-tools/pull/185](https://github.com/kubernetes-csi/csi-release-tools/pull/185)

@pohly @dims Please let me know if the changes are correct and if I must modify further.

**Comment by Garima-Negi** [comment]
hi @sreekaransrinath ! You've been assigned this issue as well, would you like to work on some PRs?
From what's left in the list above:
```789:ERROR: unable to parse owners file at https://raw.githubusercontent.com/kubernetes-sigs/metrics-server/master/OWNERS url - error unmarshaling JSON: while decoding JSON: json: unknown field "owners"
797:ERROR: unable to parse owners file at https://raw.githubusercontent.com/kubernetes-sigs/prometheus-adapter/master/OWNERS url - error unmarshaling JSON: while decoding JSON: json: unknown field "owners"```

**Comment by dims** [comment]
Looks like @sreekaransrinath may not be interested anymore ... @Garima-Negi can you please file the PRs? Also, i poked some approvers/reviewers in the 2 outstanding PRs. thanks for taking care of these!

**Comment by peizhouyu** [comment]
> Looks like @sreekaransrinath may not be interested anymore ... @Garima-Negi can you please file the PRs? Also, i poked some approvers/reviewers in the 2 outstanding PRs. thanks for taking care of these!

hi, If you don't mind, I think I may have revised it but didn't submit it. Could you please help to review it?
@Garima-Negi @dims 
Thanks.

**Comment by Garima-Negi** [comment]
@peizhouyu  thanks for taking up the remaining 2 kubernetes-sigs PRs . Looks like they are merged. Good job!

**Comment by Garima-Negi** [comment]
@dims looks like we are only waiting on  [kubernetes-csi/csi-release-tools#185](Fix OWNERS files with allowed keywords kubernetes-csi/csi-release-tools#185) for this issue to be solved.

I'[ll be squashing the commits and see if that moves it forward quickly.

**Comment by dims** [comment]
thanks @Garima-Negi

**Comment by pohly** [comment]
@Garima-Negi we are waiting for you to addresss https://github.com/kubernetes-csi/csi-release-tools/pull/185#issuecomment-1020749180...

**Comment by Garima-Negi** [comment]
@pohly just pushed a commit to squash. Should be merged soon! Sorry for the delay

**Comment by Garima-Negi** [comment]
[https://github.com/kubernetes-csi/csi-release-tools/pull/183](https://github.com/kubernetes-csi/csi-release-tools/pull/183)  is the remaining open PR on this issue. But [https://github.com/kubernetes-csi/csi-release-tools/pull/185](https://github.com/kubernetes-csi/csi-release-tools/pull/185) has been merged already (these 2 PRs are duplicates) 
We can close the open PR.

**Comment by dims** [comment]
thanks for all your work on this @Garima-Negi !!

**Comment by rohit777anand** [comment]
@k8s-ci-robot /assign

**Comment by AndreSPy1** [comment]
Hello, do we have to change "emeritus_reviewers" to Reviewers?

**Comment by jakspok** [comment]
@dims /assign

**Comment by Brijesh-09** [comment]
I want to work on this issue can you assign it to me?

**Comment by dims** [comment]
I think we have done a bunch of this. Closing this for now, we may do this again.
