### ISSUE TITLE
Ask Cloudnative.tv folks to take on Office Hours 

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#6349]
**what** 
talk to rawkode and other cloudnative.tv folks about moving Office Hours documentation into the CNCF repo, making sure its an official program, and has the support it needs to grow there. 

**why**
it makes more sense due to the audience and the skillset required for the host(s); Jorge and others have done a great job with documenting the process and structure for the event and would be good to continue with that level of care. 

Issue will close if:
- the event doesn't fit into cloudnative.tv
- when the docs get forked into the cncf / coudnative repo or doc site/location and a charter change PR is opened

**Comment by parispittman** [comment]
area/events

**Comment by alisondy** [comment]
I'll take this on

/assign @alisondy

**Comment by parispittman** [comment]
@alisondy 
Bob and I have a convo with David (rawkode) last week and he is going to get back to us
