### ISSUE TITLE
update hosting guide for chair/tl meeting

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#6351]
update this and make it complete: https://github.com/kubernetes/community/blob/master/contributors/chairs-and-techleads/meeting-host.md 
include:
- who should host and why
- agenda curation 
- outreach
- post production 

/sig contributor-experience

**Comment by alisondy** [comment]
I've started taking a look into this and fleshing out some ideas

https://github.com/alisondy/community/blob/hosting-guide-chair-tl/contributors/chairs-and-techleads/meeting-host.md

will get a draft pr in soon™️
