### ISSUE TITLE
Annual reports generator and templates improvements

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#6357]
Things that aren't done/working yet:
- Auto generating list of KEPs
- Auto generating new subprojects in last year
- Auto generating new working groups in last year
- Auto generating unique reviewer/approver counts based on OWNERS files

But what is working re: https://github.com/kubernetes/community/pull/5514 
- Auto generating annual report template for all SIGs and WGs in the right directory and using @liggitt’s new template
- Auto generating a GH issue template that can be used to mass open issues

help needed to flush out things like tests and add the above specific functions.

@kubernetes/steering-committee

/committee steering

**Comment by cblecker** [comment]
This is done. Thanks so much @Priyankasaggu11929 !
/unassign
/close
