### ISSUE TITLE
2021 Annual Report: SIG K8s Infra

### ISSUE THREAD

**Issue by cblecker** [kubernetes/community#6373]
Chairs: @ameukam @dims 
Liaison: @justaugustus

Actions for the chair/organizer of the community group:
- [ ] Consult your community group to complete draft of report
- [ ] If needed, consult with Steering Committee liaison on any private issues or concerns that arrise while completing report
- [ ] Submit PR to git.k8s.io/community repo with copy of report, assigning your Steering Committee liaison for review
- [ ] Steering Committee reviews report, and may make comments/ask questions
- [ ] Once all comments are addressed, Steering Committee will approve report to merge
- [ ] If needed, any follow up items may be brought to the "Chairs, Tech Leads, and Organizers" meeting in April

Once all the above items are complete, this issue may be `/close`'d

Key dates:
- Initial PR to communtiy repo should be opened by February 14, 2022
- PR should be reviewed and merged by March 1st, 2022

More detailed information on the annual reports process is available [here](https://git.k8s.io/community/committee-steering/governance/annual-reports.md).

Your group's report template is available here: https://git.k8s.io/community/sig-k8s-infra/annual-report-2021.md

If you have any questions or concerns about this process, you may reach the Steering Committee via the following methods:
- Slack/E-mail your liaison directly
- The public #steering-committee channel in Slack
- The public mailing list steering@kubernetes.io
- The private mailing list steering-private@kubernetes.io for any private or sensitive issues.

/sig k8s-infra
/committee steering

**Comment by sj7trunks** [comment]
There's a number of questions in here that talk about the successes of k8s-infra and what wasn't listed in KEPs. I can help volunteer to interview the people responsible for these areas and collate this into the document listed above.

I think one thing that we can label for ongoing improvement is this effort itself - to complete the accomplishments for this year and then get alignment with other sigs who fill this out as well. I've made a comment similar to this in the slack chat:

- Annual Reporting
- Quarterly reporting to k-dev
- Meeting format changes to mimic the sig-release track (adopting walk the board concept, documentation of async meetings as well)
- Cost reporting - I've already been given access and I can do more if I had some more context (I think the issue tracking from sig-release suggestion will help fix this)

We can break the above topics into sub-projects or working groups to help fulfill other areas that we're missing for Annual reporting in 2023.

**Comment by ameukam** [comment]
@sj7trunks -- This issue is only focus on annual reporting. I would suggest to open issues for each subject you want to discuss about on https://github.com/kubernetes/k8s.io/issues.
