### ISSUE TITLE
Add documentation regarding 1password

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#6394]
### Describe the issue

We have slowly been rolling out 1password, its in use by:
- SIG Contributor Experience
  - GitHub Admin team
- SIG K8s Infra
- SIG Release
- SIG Testing
- Steering Committee

We need to document how we grant access, enumerate those with owner rights etc etc.
Owners should be tightly controlled as they could potentially grant themselves rights to any k8s vault.

---
/sig contributor-experience
/area community-management
/milestone v1.24

**Comment by AvineshTripathi** [comment]
Hey @mrbobbytables is this issue similar to [issue](https://github.com/kubernetes/community/issues/3938) please confirm

**Comment by mrbobbytables** [comment]
@AvineshTripathi that is an old issue and should be closed in favor of this one at this point.

**Comment by RajGM** [comment]
Hi @mrbobbytables 
It looks like an excellent good first issue.

**Comment by mrbobbytables** [comment]
@RajGM this is not a good first issue, there are a number of policy and process decisions that need to be made when drafting the docs.

**Comment by RajGM** [comment]
Hi @mrbobbytables 
Can you please redirect me to the policies that should be followed while drafting the docs?

**Comment by mrbobbytables** [comment]
We don't have them yet, thats part of this issue. =/
