### ISSUE TITLE
Add Shadows for Marketing Council

### ISSUE THREAD

**Issue by Debanitrkl** [kubernetes/community#6399]
### Describe the issue

As discussed during the last week's Marketing Council meeting, there are a few shadow positions open in the Marketing Council.
Interested folks should reach out to the Leads, more details on this could be found [here](https://github.com/kubernetes/community/blob/master/communication/marketing-team/README.md).
Details on the shadow roles are mentioned [here](https://github.com/kubernetes/community/blob/master/communication/marketing-team/role-handbooks/council.md#becoming-a-shadow)
/sig contributor-experience
/area contributor-comms
cc @chris-short @kaslin @rajula96reddy

**Comment by Anosh21** [comment]
Hey @Debanitrkl , I would like to join marketing council.

**Comment by Debanitrkl** [comment]
@Anosh21 glad to know that you are interested in marketing council, I would suggest you to attend the weekly meeting we are having on Fridays.

**Comment by Debanitrkl** [comment]
Not much updates here, closing this for now
/close
