### ISSUE TITLE
Update CLA documentation for EasyCLA migration

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#6401]
### Describe the issue

With the switch-over planned for 2022-02-05 coming up, we should ensure that the [CLA docs](https://github.com/kubernetes/community/blob/master/CLA.md) are up to date with the new EasyCLA process. This should largely entail with removing most of the content from it. You now sign your CLA by following the link when opening your first PR. The bot responds with the links needed to log a ticket with the LF regarding it as well.

---
/sig contributor-experience
/area github-management
/area community-management
/milestone v1.24
/help

**Comment by Atharva-Shinde** [comment]
/ assign

**Comment by Atharva-Shinde** [comment]
oops
/assign

**Comment by mrbobbytables** [comment]
Thanks @Atharva-Shinde  :)
fixed in #6422 

/close
