### ISSUE TITLE
REQUEST: New Slack channel cluster-api-operator

### ISSUE THREAD

**Issue by alexander-demichev** [kubernetes/community#6404]
### GitHub Username

alexander-demichev

### Slack Username

ademichev

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

channel

### Name of Requested Resource

cluster-api-operator

### Description of Request

Hi, I'd like to request a slack channel cluster-api-operator subproject https://github.com/kubernetes-sigs/cluster-api-operator

**Comment by coderanger** [comment]
Hi there, https://github.com/kubernetes/community/blob/master/communication/slack-guidelines.md#requesting-a-channel shows the overall process but tl;dr open a Pull Request with the channel you want added to the appropriate config file. I would recommend something like `#sig-cluster-lifecycle-capi-operator` but I leave the specifics up to your SIG :)
