### ISSUE TITLE
Autogenerate Google calendar for SIG meetings?

### ISSUE THREAD

**Issue by jamiehannaford** [kubernetes/community#641]
Just an idea. For example, every time a PR is merged, a new group calendar for k8s community is generated or an existing one updated. That will calibrate the SIG docs with our public SIG meeting calendar.

**Comment by castrojo** [comment]
+1, right now a sig lead has to ensure they invite cgnt364vd8s86hr2phapfjc6uk@group.calendar.google.com to get on the community calendar.

**Comment by tpepper** [comment]
Should we close this now that the calendar's taken down?
