### ISSUE TITLE
[KCEU 2022] Contributor Summit Space Interest

### ISSUE THREAD

**Issue by chris-short** [kubernetes/community#6421]
### Describe the issue

This issue is to track other groups (SIG/WG/TAG) interest in utilizing some of the Contributor Summit space (2020-05-16). If your group or project is interested, please state your interest here. We can make no promises, as space is limited.

**Comment by mrbobbytables** [comment]
from @debgiles "CNCF actually launched a new offering this year, [project meetings](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/program/project-benefits/#project-benefits), for groups like CNCF TAGs, graduated, and incubating projects."

I think we're good to continue with the space as k8s only 👍 

/close
