### ISSUE TITLE
update sigs.yaml for sig-windows

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/community#6423]
### Describe the issue

placeholder , need to remove gmsa or other old subprojects

**Comment by mrbobbytables** [comment]
/reopen

I don't think this has happened yet

**Comment by marosset** [comment]
@jayunit100 do you remember what this issue was created for?
I think all of the repos listed at https://github.com/containerd/containerd/issues/6712 (except maybe kubernetes-sigs/sig-windows-samples) are active.

**Comment by jayunit100** [comment]
It was a note from a few weeks ago when we realized we wanted to refactoring the gmsa repo I think.  I'll ask in sig win tomoro

**Comment by iamarnavgupta** [comment]
Hey, I am a new contributer, if there is any task for me please assign . I would be to happy to contirbute.

**Comment by marosset** [comment]
/close
@jayunit100 feel free to re-open if you remember what we wanted to do here :)
