### ISSUE TITLE
REQUEST: New moderator for csantanapr of YouTube

### ISSUE THREAD

**Issue by csantanapr** [kubernetes/community#6438]
### GitHub Username

@csantanapr

### Property you'd like to Moderate

YouTube Channel

### Username on Property Requested

csantana23@gmail.com

### Requirements

- [X] I am a Kubernetes Org member already
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [X] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsor 1

@rawkode

### Sponsor 2

@mrbobbytables

### List of qualifications for this position

- Prior moderation experience
- Hosted previous [Kubernetes Office Hours](https://www.youtube.com/watch?v=gyku5FfLUf4)

I've been moderating KubeCon hallway track,  Kubernetes Slack's (cka, ckad, cks) 
I have moderated YouTube's for the organizations I've worked with, as well as my own YouTube channel and Twitch.

**Comment by mrbobbytables** [comment]
lgtm from me :)
