### ISSUE TITLE
Add contributing.md for SIG Instrumentation for subprojects

### ISSUE THREAD

**Issue by ehashman** [kubernetes/community#6462]
### Describe the issue

Generally the overall contributing.md works for SIG Instrumentation, but it doesn't tell folks how to get involved in our various subprojects.

@kubernetes/sig-instrumentation-members can subproject owners please take this on?

/cc @serathius 
for metrics-server
/cc @fpetkovski @dgrisonnet 
for KSM
/cc @pohly
for klog/logging

/sig instrumentation

**Comment by serathius** [comment]
How this should differ than already existing CONTRIBUTING.md within subprojects? (for example https://github.com/kubernetes-sigs/metrics-server/blob/master/CONTRIBUTING.md)

**Comment by serathius** [comment]
How this is different to just listing subprojects and saying to check their README.md/CONTRIBUTING.md file? In the end this will result in just becoming another list of SIGs project, which is redundant. I think it would make more sense to just encourage users to check out one of the subprojects (list is available in sig-instumentation/README.md).

Another approach to this problem that could be on SIG level would be agreeing on what each subprojects should specify in their CONTRIBUTING.md to ensure that maintain same level of quality. For example, they should all include:
* Up to date Kubernetes contributing guidelines
* List of tools required for development
* How to run tests

**Comment by ehashman** [comment]
@serathius right now the subprojects list just links to a bunch of OWNERS files. It's not a good starting point for newcomers to get started with contributing to subprojects. Many won't even know what an OWNERS file is.

It would be better for us to list areas seeking help and link directly to their contributor guides, which are not covered by the top-level Kubernetes one.
