### ISSUE TITLE
Suggested process for kubernetes-distributors list

### ISSUE THREAD

**Issue by dankohn** [kubernetes/community#647]
The security release [process](https://github.com/kubernetes/community/blob/master/contributors/devel/security-release-process.md) says:

> The Fix Lead will email the patches to kubernetes-distributors-announce@googlegroups.com so distributors can prepare builds to be available to users on the day of the issue's announcement. Distributors can ask to be added to this list by emailing kubernetes-security@googlegroups.com and it is up to the Product Security Team's discretion to manage the list.
TODO: Figure out process for getting folks onto this list.

The K8s software conformance [working group](https://ponymail.cncf.io/thread.html/Zse5s4ind7utvjd) is maintaining a public [spreadsheet](https://docs.google.com/spreadsheets/d/1LxSqBzjOxfGx3cmtZ4EbB_BGCxT_wlxW_xgHVVa23es/edit#gid=0) of all known Kubernetes offerings, which was initially created by @josephjacks.

I propose adding a security contact column to the spreadsheet and soliciting the security contact (or comma separated list of contacts) for each offering.  Some comments and open questions:

* Here are some details on how the Linux kernel distro list is managed: https://lwn.net/Articles/566123/
* Many folks (including CNCF staff) are monitoring the spreadsheet, and only @josephjacks and I can edit, so we should be able to avoid bad actors adding their email addresses.
* I presume we should limit security contacts to come from the appropriate domain (e.g., redhat.com for OpenShift).
* Can we just email new submissions to kubernetes-security@googlegroups.com or is there a better process for administering list membership? We would escalate any questionable entries to the security group.

Cc: @philips @jessfraz @WilliamDenniss @gregkh

**Comment by jessfraz** [comment]
> I propose adding a security contact column to the spreadsheet and soliciting the security contact (or comma separated list of contacts) for each offering. 

The less people added, the more likely embargo will not be leaked so at most we should say 1 person from each, pending certain circumstances. Security emails can also not be an internal mailing list group but should be required to be an individual, since groups would be up to the vendor to maintain who is on it and is out of our control.

 > Can we just email new submissions to kubernetes-security@googlegroups.com or is there a better process for administering list membership? We would escalate any questionable entries to the security group.

I do think the request should ultimately be handled by the group, but can be based off the spreadsheet.

**Comment by jessfraz** [comment]
This was handled by https://github.com/kubernetes/community/pull/1153 so I think it can be closed :)

**Comment by cblecker** [comment]
So it was! Thanks @jessfraz 
/close
