### ISSUE TITLE
New role? 3rd party/other programs Mentorship Coordinator 

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#6471]
### Describe the issue

LFX
Outreachy
Google Summer of Code
Google Summer of Docs

we participate in all of these but have several folks (ihor, josh, bob, me, etc) who remind us when to do things. it would be worthwhile if we can make this a role and have that individual:
- keep a calendar of dates for each program (when to submit our project name, when to submit the project scope, when selecting period is, etc) throughout the year and 
- coordinate all submissions and participation in each one
- go to sig meetings and slack channels to proactively help with scoping and planning work / job descriptions 
- help onboard interns to the k8s specific community items like coordinate a hello for them at the k8s monthly community meeting
- help off board interns to the k8s specific community items like demo at monthly community meeting

I'll close this issue after discussion that the role should be a thing and we have a merged PR (or discussion leads to no thanks). 

/sig contributor-experience
/area mentoring

**Comment by Debanitrkl** [comment]
Last week we had some discussion on the same in Upstream marketing Council meeting. We have added it to the project board to reach out to SIGs and remind them of the deadlines of proposal submission. https://github.com/orgs/kubernetes/projects/39#card-77620268

**Comment by jberkus** [comment]
Wouldn't this be chair of the mentoring subproject?  I mean, we're looking for one of those, but seems to go with the territory.

**Comment by parispittman** [comment]
we don't do chairs of subprojects but if we want to create a role that is 'mentoring lead' that is fine; my only concern is the other mentoring programs that they would need to lead as well and this is more finely scoped than that. if we really did get a mentoring lead they would need at least 5 hours a month with all of the group stuff that I do and everything else going on. just seems like too much for one person whereas this is finely scoped and already a lot of work.

**Comment by parispittman** [comment]
it would be good to get another approver for group mentoring, a 3rd party lead, and then a new contributor workshop lead

**Comment by jberkus** [comment]
BTW, do we have a candidate for this role?

**Comment by Debanitrkl** [comment]
> BTW, do we have a candidate for this role?

Presently, I'm working on this defining the timelines to reach out to SIGs for submission of proposal for specific mentoring programs.

**Comment by nikhita** [comment]
+1 on introducing this role. It's been pretty adhoc as of now and we've definitely had cases of where we've forgotten to follow up on mentorship programs with so many things going on.

**Comment by jberkus** [comment]
@Debanitrkl if you want it, I'd be thrilled to nominate you for this.
