### ISSUE TITLE
REQUEST: New communication about Community Meeting February 17, 2022

### ISSUE THREAD

**Issue by pnbrown** [kubernetes/community#6479]
### What do you want send out?(Please include a link to a draft)

Hi, can we get this email out about tomorrow's Community Meeting?

Hello k-dev,
I’m nigel, and I’ll be your host for the February community meeting, which is this Thursday at 10 AM PST (reference the time converter below). We would love to have everyone attend if they can so we can discuss important upstream topics. As the host, I’m posting the draft notes and final notes to this list.

Date and Time: 6pm UTC ([Time zone converter](http://google.com/?q=6pm+UTC))[ ](https://zoom.us/my/kubernetescommunity)on Thursday, February 17
Zoom: https://zoom.us/j/91768411674?pwd=MVpqL0ZHbGFYMnpXVXpybTBvalFRQT09
Draft Agenda:[ http://bit.ly/k8scommunity](http://bit.ly/k8scommunity)

This month, we will be talking about the following topics:

- Dockershim removal
- Raising the Reliability Bar
- k-dev move

If you have any questions about the meeting, you can reach out to the Contributor Experience SIG in Slack under[ #sig-contribex](https://kubernetes.slack.com/archives/C1TU9EB9S).

Thanks and see you soon,

nigel, on behalf of SIG Contributor Experience

P.S. - If you want to host the monthly meeting, we’re looking for volunteers and first-timers! Please reach out to us on Slack or message Laura Santamaria (nimbinatus) for more info.

**Comment by parispittman** [comment]
I didn't see a contributor comm member pick this up so I sent it from contributors@ now with 'top of the hour' language 

/close
