### ISSUE TITLE
swag ideas for OWNERs

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#6492]
### Describe the issue

one of the staple pieces of swag we have is the kubernetes contributor patch that we give away during contributor events. now that we have a [function in prow that flags new OWNERs](https://github.com/kubernetes/test-infra/pull/24937) (reviewers, approvers) with information and a swag opportunity, should we customize a patch or another piece of swag for them as an extra special thank you? OWNERs are taking on a lot of responsibility - way more than the casual contributor. Any ideas?

Ideas:
- k8s logo patch with "subproject owner" text or maybe their GitHub handle?
- k8s apparel and accessories (sizing will be an issue that will need to be solved for if its that kind of apparel) with GitHub handle  
  - hoodie
  - lapel pin

Estimated yearly $:
max 5-7k 
assumptions:
$50/pp (estimating a high cost)
no more than 100 a year 
including estimated shipping costs since that will be our large hit; folks can pick up at kubecon but will still have 

Updates:
I filed a servicedesk ticket to see what our options are here; sounds like we can definitely have a process with codes and could power the codes in an automated way/not have too many humans in the middle. Will start the set up process post KubeCon EU.  

/sig contributor-experience

**Comment by ameukam** [comment]
Kubernetes Hoodie with the Github handle of the contributor. I saw this for Github employees.

**Comment by dims** [comment]
circular lapel pin with k8s logo inside and `/approve` and `/lgtm` on the border ( i treasure one similar to this for openstack that says "+2" - i think swag from HP )

**Comment by chris-short** [comment]
Standard Kubernetes patch with OWNER embroidered in/on to it
