### ISSUE TITLE
The link to "Contributor Role Board" in the https://www.kubernetes.dev/docs/guide/first-contribution/ page is broken.

### ISSUE THREAD

**Issue by uroy-personal** [kubernetes/community#6493]
**This is a Bug Report**

**Problem:**
The link to "Contributor Role Board" in the https://www.kubernetes.dev/docs/guide/first-contribution/ page is broken.
**Proposed Solution:**
The page should redirect to correct public page
**Page to Update:**
https://kubernetes.io/...

**Comment by uroy-personal** [comment]
Hi @mrbobbytables,
I would like to work on this simple fix and get familiar with the flow of events in the process. I am not able to assign the issue to myself.  Your suggestion on next steps will be of great help.

**Comment by mrbobbytables** [comment]
@uroy-personal you can assign it via our automation, respond with  `/assign` and it'll do the rest 👍 

/sig contributor-experience
/area contributor-guide

**Comment by uroy-personal** [comment]
> I confirm that "The link to "Contributor Role Board" in the https://www.kubernetes.dev/docs/guide/first-contribution/ page is broken." /triage accepted
> 
> But the corresponding GitHub repo of https://www.kubernetes.dev/ is not this one, but https://github.com/kubernetes/contributor-site . /transfer contributor-site

Thanks @jihoon-seo

**Comment by uroy-personal** [comment]
> @uroy-personal you can assign it via our automation, respond with `/assign` and it'll do the rest 👍
> 
> /sig contributor-experience /area contributor-guide

Thanks @mrbobbytables
