### ISSUE TITLE
Where can i find the actual CRI log format description (kubelet-cri-logging.md)?

### ISSUE THREAD

**Issue by asviel** [kubernetes/community#6497]
I want to change docker to containerd/cri-o and want to know understand how i need to reconfigure my log sniffers due this change.
I only found https://github.com/kubernetes/design-proposals-archive/blob/main/node/kubelet-cri-logging.md, but it's in the archive.
Can you help me?

**Comment by Debanitrkl** [comment]
@asviel please consider asking this in https://discuss.kubernetes.io/ or in [slack](https://github.com/kubernetes/community/tree/master/communication#slack)
Also you could find more details here: https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/
/close
