### ISSUE TITLE
REQUEST: Private Slack channel for moderators

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#6505]
### GitHub Username

mrbobbytables

### Slack Username

mrbobbytables

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

Private Channel

### Name of Requested Resource

k8s-moderators (open to other ideas)

### Description of Request

We have the private moderators mailing list, but it would be useful to have it mirrored as a slack channel for better cross-platform incident coordination (e.g. BLM banner) as part of our [escalation procedure](https://www.kubernetes.dev/docs/comms/moderation/#escalation-procedures). The actual usage of it will likely be quite low, but when the moderation teams need to coordinate we could respond significantly faster with a slack channel vs the mailing list.

**Comment by parispittman** [comment]
+1

**Comment by markyjackson-taulia** [comment]
+1

**Comment by dylanANZ** [comment]
+1

**Comment by DylanGraham** [comment]
+1

**Comment by coderanger** [comment]
YouTube too, and maybe Reddit if we want to coordinate with them at all (though that's an unofficial comms channel so it's not under our formal umbrella).

**Comment by dims** [comment]
+1

**Comment by mkumatag** [comment]
+1

**Comment by cblecker** [comment]
Would it also be beneficial to invite CoCC too?

+1 to the idea

**Comment by celestehorgan** [comment]
Thanks @cblecker 

yay ❤️

**Comment by cblecker** [comment]
Also: if this is a new private slack channel we should create a doc detailing the reasons for it, what kind of topics will be discussed, and intended membership.. just so we have a public record of it for transparency sake.

**Comment by celestehorgan** [comment]
@cblecker sounds like a use case for something I think the project needs anyways - non-architectural decision records. k/enhancements gets bogged down on occasion by changes (like "no 3rd party projects in the docs") which are fundamentally policy/process decisions. But there needs to be a clear approver for that kind of change, and steering is probably it.

**Comment by jberkus** [comment]
@markyjackson-taulia what is this request waiting on?

**Comment by markyjackson-taulia** [comment]
@jberkus nothong to my knowledge other than an approval

**Comment by mrbobbytables** [comment]
Approval is done, just have to create it+document it.

IMO, if we don't document it first, it probably won't happen. I'd suggest that as next steps.

**Comment by markyjackson-taulia** [comment]
@mrbobbytables i can take on the documentation. I have an item for the escalation procedure

**Comment by mrbobbytables** [comment]
Go for it! 
It'd probably go in our main moderation doc or the moderator list

**Comment by Atharva-Shinde** [comment]
+1

**Comment by mrbobbytables** [comment]
channel has been created, it is called kubernetes-moderators
this can be closed when docs are updated
