### ISSUE TITLE
Cleaning up the design-proposals directory

### ISSUE THREAD

**Issue by jessfraz** [kubernetes/community#651]
The go proposals repo is super clean and all kind of have the same format, see https://github.com/golang/proposal/tree/master/design.

Things we might consider:
- **`-` (dash) vs `_` (underscore)**: Throughout this repo there is a mixture of `-` vs `_` in filenames (example https://github.com/kubernetes/community/tree/master/contributors/design-proposals) and it is kind of driving my OCD insane... what if we picked one :)... really not trying to start a bike shed could care less which one, as long it is consistent. It does seem like `-` is more common though...
- **ensure all have same format**: seems wrong to change the old but maybe each should at least have a table of contents and add a template.md for the future...
- **add last updated**: see a sample go proposal https://github.com/golang/proposal/blob/master/design/12914-monotonic.md

**Comment by bgrant0607** [comment]
Filenames: dash is better for my RSI

Metadata: Yes, a creation date, last updated, status in each release, and link to tracking info (e.g., features repo issue(s)).

We're also going to need to organize these by SIG to facilitate auto-assignment and approval.

**Comment by nikhita** [comment]
> We're also going to need to organize these by SIG to facilitate auto-assignment and approval.

This is done 🎉

**Comment by nikhita** [comment]
What are the TODO items here? I can help with this.

> Filenames: dash is better for my RSI

+1. I'll fix this.

> ensure all have same format: seems wrong to change the old but maybe each should at least have a table of contents and add a template.md for the future...

I don't think we should change the old ones, for the new ones we have the KEP format.

> Metadata: Yes, a creation date, last updated, status in each release, and link to tracking info (e.g., features repo issue(s)).

KEPs have this. Do we also need to go back and fix the old ones?

**Comment by nikhita** [comment]
@justaugustus Is this still relevant given the latest changes in KEPs?

**Comment by justaugustus** [comment]
@nikhita -- yep. Ideally, I'd like to see active design proposals morph into KEPs over time, but for now we're prioritizing standardizing KEPs. From there, we'll work with SIGs individually to cleanup and migrate their design proposals.

**Comment by justaugustus** [comment]
We discussed this last week at [SIG PM](https://youtu.be/jHXm10TieUI) and I think this is a good opportunity for SIG PM volunteers to get involved.

I'll be assigning people soon to work with SIGs on getting current design proposals cleaned up and migrated.

**Comment by lachie83** [comment]
@justaugustus I would be happy to iterate on this. I would like high level agreement that the following is the best course of action.

1. Rename all files replacing to lowercase only and dashes rather than underscores
1. Confirm template is correct
1. Make sure all proposals adhere to the same template
1. Update the README to reference to KEP process

Is there anything else that needs action here? Can you please assign to me?

**Comment by SeanPSnyder** [comment]
I only see one end game, so if there's another, I'd love to be privy

**Comment by lachie83** [comment]
@SeanPSnyder would you mind sharing the details on the end game you have in mind?

**Comment by SeanPSnyder** [comment]
Bullet to the brain preferrably

**Comment by LappleApple** [comment]
Heya, two things:

- was there agreement on @lachie83's points/did he get answers to his questions?
- is there a relationship between this and [#651](https://github.com/kubernetes/community/issues/651) that should be clarified or noted here and/or there?

**Comment by mrbobbytables** [comment]
This can probably be closed or should be closed once design proposals have been moved over to the enhancements repo for archival. 
ref: https://github.com/kubernetes/community/issues/2565#issuecomment-615230060

@justaugustus what do you think?
Personally I'm in favor or just closing it in favor of keeping #2565 open till the move is complete.

**Comment by mrbobbytables** [comment]
I'm going to go ahead and close this asI think the discussion for design proposals is happening under #2565 . If it should be reopened please go ahead and open it back up again 👍 

/close
