### ISSUE TITLE
Proposed: Expose k/community content via contributor-site

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#6511]
### Describe the issue

The way it is now: select portions of k/community are available via kubernetes.dev, but other portions require browsing in the repo itself.

The way it should be: any and all documentation to which contributors are expected to refer should be available via kubernetes.dev.  This would include most of k/community.

Reasons for the change:
- website content is more findable than github content
- website content is better formatted/more readable than github content
- future ability to support localizations of contributor information
- manageability of links between documents

Please set aside technical discussions of how this would be implemented.  The purpose of this issue is to determine what our goal is with the various pieces of information; once we have a goal, requirements will determine the implementation.

One particular question is what materials we do NOT want to expose via kubernetes.dev, and should remain as GitHub docs only.  For a lot of the general areas below, specific files will probably not be exposed regardless; for example, mentoring programs might expose information pages but not mentorship templates.

Here's a list of what's in this repo currently, and thus what would need to be ported/exposed, with items that are already available through the site checked off.

- [ ] CoCC charter/materials
- [ ] Security response guidelines
- [ ] Steering Committee docs
- [x] communications guidelines/moderator docs
- [ ] contributor guide
- [ ] github management documentation
- [ ] Code for the community repo itself (hack and generator)
- [ ] events information
- [ ] mentoring programs
- [ ] SIG and WG charters, annual reports, and other information
- [ ] Elections info (currently under Events, but moving)
- [ ] chairs and techleads documentation

Please offer feedback on specific items that you're involved with and why we would or would not want to expose them via kubernetes.dev.

**Comment by jberkus** [comment]
/sig contributor-experience
/area contributor-site
/assign @mrbobbytables @alisondy 

attn: @parispittman @nate-double-u

**Comment by sftim** [comment]
> events information

Depending on what this is, that information could also have a home in or linked from https://kubernetes.io/community/

**Comment by jberkus** [comment]
@sftim it's primarily information around contributor summits

**Comment by parispittman** [comment]
to @sftim point - can we expand on what docs those are in each one. for instance - the mentoring folder has programs and operations files.

**Comment by parispittman** [comment]
it would be good to know what the definitions are for each area of the contributor site too to better answer these questions. example: what goes in community and what goes in resources?

**Comment by parispittman** [comment]
re: sig directories - would they be housed in k-sigs/contributor-site or would leads be instructed they can still host materials in k/community?

**Comment by parispittman** [comment]
missing from above - chairs and tech leads documentation: https://github.com/kubernetes/community/tree/master/contributors/chairs-and-techleads

**Comment by parispittman** [comment]
breaking down steering committee docs they are:
- community group governance (how they should do it/operations)
- annual report instructions 
- charter instructions and FAQ

**Comment by jberkus** [comment]
Let me give an example of a section that's in my particular responsibility area:

## Elections

### Expose in Contributor Site

* elections meta page (i.e. here's the upcoming elections, here's where you find info, link to elections.k8s.io)
* elections subproject charter (does not exist yet)
* How To Request An Election (does not exist yet)
* elections HOWTO (for election admins)

### Remain Github-only

* YAML/MD files for configuring/running elections.k8s.io
* Templates for elections committees (e.g. email templates)

**Comment by mrbobbytables** [comment]
FWIW - while I would love to surface as much docs as possible, I think the real thing that SHOULD move to the contributor site is the contributor guide. It serves the audience that are NEW to the project and don't have any experience navigating its structure. We want to make as much as we can as easily discoverable as possible. It's also the prime target for localization, and its frustrating when people open issues in that repo for content that is here. 

If we want to look more long term and surfacing as much as possible I'd go the opposite direction and turn k/community into the contributor site and completely restructure it to serve that purpose.

**Comment by jberkus** [comment]
> If we want to look more long term and surfacing as much as possible I'd go the opposite direction and turn k/community into the contributor site and completely restructure it to serve that purpose.

If that was our decision, would it derail current efforts?

**Comment by mrbobbytables** [comment]
> If that was our decision, would it derail current efforts?

No, if we moved some content there - there isn't a reason it couldn't be moved back and still preserve git history.

**Comment by jberkus** [comment]
> re: sig directories - would they be housed in k-sigs/contributor-site or would leads be instructed they can still host materials in k/community?

@parispittman I'm really trying to separate out "what is our goal" from "how do we implement that".  Let's agree on goals first before we get bogged down in the technical details.

**Comment by parispittman** [comment]
in your example @jberkus  - where would the elections docs be housed in the current site structure?

**Comment by alisondy** [comment]
Is there any data on how people use the site now?

What links are the most clicked, what are the most common journeys folks take when using the contributor site.

What are the most commonly searched things.

**Comment by chris-short** [comment]
I would like more links from k.dev to repos, in general. But, I agree with Bob that the Contributor Guide should be on the site (so long as all the other repos are sufficiently linked). I hope that bridges the gap here.

**Comment by jberkus** [comment]
Yeah, let's go ahead and move the contributor guide.
