### ISSUE TITLE
REQUEST: New Private Slack for metal3.io project maintainers

### ISSUE THREAD

**Issue by fmuyassarov** [kubernetes/community#6515]
### GitHub Username

fmuyassarov

### Slack Username

fmuyassarov

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

Private Channel

### Name of Requested Resource

metal3-security

### Description of Request

Hi,
Within [Metal3.io](https://github.com/metal3-io) project we currently have [#cluster-api-baremetal ](https://kubernetes.slack.com/messages/CHD49TLE7) public channel on the K8s slack. However, we are trying to improve the project from the security perspective and would like to have a separate private channel under K8s slack to discuss security vulnerabilities of the project. We want the channel to be private in order to not expose potential security bugs until we fix them and report on the public channel. As such, it will be only project members (maintainers and reviewers) who will have an access to the channel and should there be someone else added, current members should do so.

**Comment by coderanger** [comment]
Sorry, we don't offer private channels to community projects due to being unable to enforce our code of conduct in them.

**Comment by namnx228** [comment]
What if we will invite someone from Kubernetes community (a maintainer/reviewer) to the channel? The person can monitor the channel activity and make sure the code of conduct is enforced.

**Comment by coderanger** [comment]
Unfortunately we as a moderation team just can't handle direct oversight in these cases, there are too many people and too many channels. Private Slack channels are reserved only for core project functions which have literally no other options such as election management and our own security response team.

I would encourage you to look at setting up your own community resources, or if you're under the CNCF banner in one way or another they offer a less encumbered Slack environment to member projects.

**Comment by markyjackson-taulia** [comment]
Also a -1 from me for the same reasons

**Comment by fmuyassarov** [comment]
Thanks for the suggestions folks.
/close
