### ISSUE TITLE
Community Icons Google Slides Deck is Private

### ISSUE THREAD

**Issue by JamesLaverack** [kubernetes/community#6527]
### Describe the issue

Under the [community icons](https://github.com/kubernetes/community/tree/master/icons) page, there is a link to a [Google Slides presentation](https://github.com/kubernetes/community/tree/master/icons#slide-deck) with all the icons present. That presentation, at the time of writing, has been set as private by whoever owns it and is now inaccessible to community members.

![image](https://user-images.githubusercontent.com/1119526/157229984-2b14b796-f62b-4e6c-9d93-51b167f8c54c.png)

I'd expect everyone to have read access on this presentation, as we used to have.

/kind bug
/sig contributor-experience

**Comment by thockin** [comment]
I also do not have access

**Comment by thockin** [comment]
`git blame` says @arnaudmz might know

**Comment by thockin** [comment]
Ehh, all the icons are checked in here, so a template slide deck isn't THAT useful...

**Comment by JamesLaverack** [comment]
I liked it because it made it faster to copy/paste them into side decks for presentations, but the barrier isn't that much higher for just copying in the raw icons you're right.

**Comment by JamesLaverack** [comment]
I've raised https://github.com/kubernetes/community/pull/6738 to remove the link, which I feel would close this issue.

/assign
/lifecycle clear
