### ISSUE TITLE
I have some issues related to Prestop improvement.

### ISSUE THREAD

**Issue by PengTaoWW** [kubernetes/community#653]
I have an improvement on Kubernetes, in our production environment, a pod is removed to use the Perstop, but no matter how quickly the result of this pod is removed, my improvement is that when Perstop fails, it will retry until the execution succeeds, or the timeout is removed. I don't know why you were so designed, or if there's a problem with my improvement, please let me know, thank you.

**Comment by resouer** [comment]
I think you are saying PreStop hook?  My personal opinion is it worth to add a retry and timeout to lifecycle hook execution. So please remove this discussion to kubernetes/issues? So more developers can push it. You can title it as "Execution retry and timeout of lifecycle hooks" or anything you like.

**Comment by PengTaoWW** [comment]
@resouer PR is here

**Comment by PengTaoWW** [comment]
@resouer https://github.com/kubernetes/kubernetes/pull/46426
