### ISSUE TITLE
Get recent build from CI

### ISSUE THREAD

**Issue by elchead** [kubernetes/community#6533]
### Describe the issue

Following https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/getting-builds.md, I tried to download the build from a PR (https://github.com/kubernetes/kubernetes/pull/104907). In the CI build log, I found a version number "v1.24.0-alpha.3.413_4c90ec346e1c8d" and used this in the hack script to download it. 
Unfortunately, I get a regexp error. When passing "ci/latest", the version format has a trailing + (v1.24.0-alpha.3.420+9e5efebb4c23a1), so I replaced the "_" with a "+" but the image can still not be found?

Is there a way to set up a cluster using the image from a PR?

**Comment by elchead** [comment]
It seems the images are moved / removed after passing CI, since I get a HTTP 301 (Moved) when using the url from the build log:

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/104907/pull-kubernetes-e2e-gce-alpha-features/1501562549865287680/artifacts/e2e-a05885a038-cc220-master/images-containerd.log

**Comment by alisondy** [comment]
Adding sig-release, the SIG associated with the owners file where this doc is located.

/area sig-release

**Comment by justaugustus** [comment]
@elchead -- Information on version markers (and how to use them) can be found here: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/kubernetes-versions.md#ci

Build jobs: https://testgrid.k8s.io/sig-release-releng-blocking

While we produce images for _periodic_ CI builds: https://console.cloud.google.com/gcr/images/k8s-staging-ci-images/GLOBAL
We provide no guarantees of existence for images that are created during _presubmit_ tests.


> When passing "ci/latest", the version format has a trailing + (v1.24.0-alpha.3.420+9e5efebb4c23a1), so I replaced the "_" with a "+" but the image can still not be found?

Important to note from https://docs.docker.com/engine/reference/commandline/tag/#extended-description:

> A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.

Image tags are not actually SemVer-compliant, specifically, they don't support encoding build versions with `+` (ref: https://semver.org/#spec-item-10), so we rewrite `+` to `_` for image tags.

What specifically are you looking to do?

/sig release
/area release-eng
cc: @kubernetes/release-engineering

**Comment by justaugustus** [comment]
I'm going to close this out in the hopes that that was helpful, but please feel free to reopen if you still need help! :)
/close
