### ISSUE TITLE
REQUEST: New communication about March 2022 Community Meeting

### ISSUE THREAD

**Issue by nimbinatus** [kubernetes/community#6537]
### What do you want send out?(Please include a link to a draft)

Looking to send out comms about the monthly Contributor Community Meeting. Draft text (tagging in @jberkus to add details/any adjustments): https://gist.github.com/nimbinatus/4d169ac482ed6c1dfab950aff8f6d18f

The sponsoring SIG is Contributor Experience, and the point of contact is @nimbinatus or @jberkus (this month's host). We'd like to get this out by 5p UTC Tuesday, if possible, to the mailing list at the very least.

**Comment by nimbinatus** [comment]
Note: @jberkus is going to email directly.

**Comment by jberkus** [comment]
Posted to k/dev.

@kaslin, could you tweet it?

**Comment by parispittman** [comment]
/close

complete
