### ISSUE TITLE
Events channel on slack doesn't align with what's in sigs.yaml

### ISSUE THREAD

**Issue by alisondy** [kubernetes/community#6540]
### Describe the issue

In the contribex readme, the events channel in slack is linked to as the contact for the events subproject

Currently the events channel in slack is used by multiple folks to share upcoming meetups and events in the cloud native / kubernetes space. 

Is there value in a creating a slack channel for all upstream focused work around events?

Thoughts?

/area sig-contributor-experience

**Comment by parispittman** [comment]
we have always used #summit-staff and since there aren’t many events outside or contrib summit, #sig-contributor-experience

**Comment by alisondy** [comment]
Updated description of issue for clarity.
