### ISSUE TITLE
Build Contributor Summit Valencia Team

### ISSUE THREAD

**Issue by alisondy** [kubernetes/community#6553]
### Describe the issue

Build Contributor Summit Team for Valencia!

[Event Team Folder](https://github.com/kubernetes/community/tree/master/events/events-team)

Role | Volunteer Name | Shadow Name | Notes
-- | -- | -- | --
Event Lead | Puja Abbassi @puja108 / Alison Dowdney @alisondy | | |
Registration Lead | Arnaud M. @ameukam  |   |  Josh Berkus @jberkus to support
Marketing Lead | | |  
Reception Lead | Josh Berkus @jberkus  | Roger Klorese @qnetter |
CNCF Events Manager | Deb Giles @debgiles | n/a | CNCF/LF employee
Overall Content Lead | | |

Marketing - Interface with contributor comms on this front
Content - Unconference

**Comment by csantanapr** [comment]
This is my first time helping, I want to shadow

**Comment by ameukam** [comment]
I volunteer as Registration lead with @jberkus.

**Comment by qnetter** [comment]
> I'll be supporting Arnaud for registration, and leading content/marketing for the Reception.
> 
> Roger Klorese will be shadowing me on the reception.

AKA @qnetter :)

**Comment by puja108** [comment]
@chris-short as Marketing Lead
