### ISSUE TITLE
Update SIG Contribex Splain and Zoom Integration

### ISSUE THREAD

**Issue by onlydole** [kubernetes/community#6556]
### Describe the issue

The current Splain integration with Zoom isn't working for SIG Contribex and needs to be fixed.

/assign @onlydole
/sig contributor-experience
/area community-management

**Comment by mrbobbytables** [comment]
It does work for the contribex zoom account, but its not configured for the root one

**Comment by onlydole** [comment]
Ah! Got it 👍🏼 Thank you, @mrbobbytables!

**Comment by onlydole** [comment]
I found the culprit! I'll work with the Splain support team to get this updated.

<img width="651" alt="Screen Shot 2022-03-21 at 6 05 15 PM" src="https://user-images.githubusercontent.com/117500/159387272-817e3bd5-a13e-4cba-b711-3d69d6b5800a.png">

**Comment by mrbobbytables** [comment]
It may just need to be disconnected / reconnected (this has happend in the past) I didn't think we had splain setup for the root account though. O_o we just need to make sure other things using the root zoom don't select record.

**Comment by onlydole** [comment]
The SIG Contribex connector was working as expected! The issue was that the root account needed to be re-authenticated (the Kubernetes community meetings get scheduled via the root Zoom account). 

Thank you to Bob and SIG Contribex folk for helping on this one! 

/close

**Comment by kofiowu** [comment]
Thanks for you contribution.
