### ISSUE TITLE
SIG Testing meeting recordings gets uploaded to YT studio twice

### ISSUE THREAD

**Issue by CIPHERTron** [kubernetes/community#6561]
### Describe the issue

 I’ve seen this weird behavior a couple of times with SIG Testing meeting recordings. Weird as in a **single recording** gets uploaded to YT studio two times. Those two recordings are essentially the same but differ only in terms of meeting views. One recording will be having the gallery view whereas the other will be having single views of the one who’ll be speaking.

I think this is some kind of bug in the zoom cloud and someone from the zoom-admins needs to check what’s wrong 🤔

**Comment by onlydole** [comment]
I can help take a look at this one! 

/assign @onlydole

**Comment by onlydole** [comment]
I found the culprit! I was able to work with the SIG Testing leads to get access to Zoom and un-check the "Record gallery view with shared screen" setting so there will be no more double video uploads. 

<img width="453" alt="Screen Shot 2022-03-24 at 3 11 29 PM" src="https://user-images.githubusercontent.com/117500/160018826-ece5b91e-5b82-4e36-8f07-d697a892d8b9.png">

Thank you for raising this, @CIPHERTron! Please let me know if there are any other issues on this front.

/close
