### ISSUE TITLE
Broken link in API conventions documentation

### ISSUE THREAD

**Issue by jkaye2012** [kubernetes/community#6566]
### Describe the issue

In the [API conventions documentation](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md) (linked in turn from the [official Kubernetes documentation](https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/)), there is a broken link to a description for `DNS_LABEL` format [on line 88](https://github.com/kubernetes/community/blame/master/contributors/devel/sig-architecture/api-conventions.md#L88).

I did some brief searches around the repository for this identifiers document to attempt to fix the link myself, but I was unable to find the referenced information.

**Comment by jkaye2012** [comment]
This would be for the Docs sig, but I don't seem to have the ability to modify the labels.

**Comment by jkaye2012** [comment]
I believe this may be the correct link for replacement?

https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names

**Comment by MadhavJivrajani** [comment]
/sig architecture
@jkaye2012 please see https://github.com/kubernetes/design-proposals-archive/blob/main/architecture/identifiers.md as the intended link (design proposals were recently migrated and archived). Feel free to send in a PR!

**Comment by jkaye2012** [comment]
/remove-lifecycle stale

Linked PR should ideally be merged before closing this

**Comment by jkaye2012** [comment]
/remove-lifecycle stale

Linked PR should ideally be merged before closing this

**Comment by divya-mohan0209** [comment]
Per [this comment](https://github.com/kubernetes/community/pull/6588#issuecomment-1336261730) on the linked PR that has been closed now, the redirect is intentional.
/close
