### ISSUE TITLE
[RFC] New Contributor Workshop for KubeCon NA 2022 scope reduction

### ISSUE THREAD

**Issue by tokt** [kubernetes/community#6572]
### Describe the issue

**Past**
Up to (and including) 2019 we used to have a full day NCW at every KubeCon event.
[Slides](http://bit.ly/kubeconlesss_NCW2_slides )
Some of the challenges with that approach: 

- Folks running NCW and Contributor Summit are mostly same people. 
- A very small percentage of people attending the NCW ended up contributing later.

**Current state**
There were no workshops in 2020/2021, and at this moment there are no plans to run it again in 2022.
However, there's a (somewhat stale) [initiative](https://github.com/orgs/kubernetes/projects/18) to update slides and create other ways to onboard new developers. (Katacoda, recorded video trainings etc).

**Proposed change:**
Reduce the on-site workshop from a full day event to a 1-2 hour session.
(The goal is to still give interested people at least some directions and a chance to ask questions)

Comments/ideas/suggestions?
/sig contributor-experience
/area new-contributor-track
/cc @jberkus @alisondy 
(Sincere apologies if I've missed anyone else).

**Comment by mrbobbytables** [comment]
If there is room, enough volunteers and bandwidth to run it, I don't see a problem with running one - my gut is leaning towards there won't be though. I know a number of the usual suspects that have run it in the past have other responsibilities that day.

**Comment by jberkus** [comment]
/remove-lifecycle stale

This is still being considered for KCSNA

**Comment by jberkus** [comment]
This is not planned for KCSNA 2022.

/close
