### ISSUE TITLE
SURVEY REQUEST: k/k branch rename impact survey

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes/community#6575]
### Group Requesting

SIG Release

### Title of Survey

Tell us how the Kubernetes repository branch rename will impact you

### Goal of Survey

We will rename the branch for https://github.com/kubernetes/kubernetes from master to main and we would like to gather some information regarding the downstream consumers of the branch.

We are aiming to do the change in the 1.25 release cycle.
For more information check out the KEP in https://github.com/kubernetes/enhancements/tree/master/keps/sig-release/2853-k-core-branch-rename

### Target Audience

Any downstream consumers of the Kubernetes GitHub repositories

### Results Recipients

@justaugustus , @jeremyrickard , @cpanato , @puerco , @saschagrunert 

### Date Survey Starts

ASAP

### Date Survey Ends

End of May 2022

### Publicity Help Wanted?

Yes

### Data Analysis Wanted?

Yes

### Link to Draft Questions

https://docs.google.com/forms/d/1hlw3bt6Qp6KLeNbcrcuaV0t3dO5mhGJGJ0K4vkw3iY4/edit

**Comment by parispittman** [comment]
Note - there are two active surveys out right now so what out for survey fatigue 

release cadence and OWNERs (800 people which is limited; however, these are the folks that might weigh in on both)

**Comment by jberkus** [comment]
Who are "downstream consumers"?  That is, who are we targeting with this?

**Comment by jberkus** [comment]
More questions:

(btw, in the future a Google Doc works better, becuase then we can comment on, and collaborate on, the individual questions.  We can't do so on a form)

1. Are you requesting that folks have only one response per organization?  That is, an "official" response?
2. Questions 2 and 3 seem unlikely to yield useful information.  Let me suggest instead:

(2) How much will renaming the primary branch affect your builds and downstream workflow?
- Just a few small automation changes
- Significant CI and build modifications
- Major refactoring of our workflow
- We will need to do an assessment to figure out what's required

(3) Please share any specific notes or information about what work the branch rename will require from your organization.

* Question 4 could stand to have some options or the responses will be hard to process

(4) How long would your organization need to prepare for the branch rename?
- 3 months or less
- 3 to 6 months
- 6 to 12 months
- Will need to do an assessment to know

**Comment by jberkus** [comment]
If this is going to have "official" answers, we need some guarantee of confidentiality for respondees, and probably an alternate route to provide you with feedback if they just can't type stuff into a form.  In the latter case, who should they contact directly? Carlos and Jeremy?

**Comment by cpanato** [comment]
Thanks, Josh, for the feedback and inputs.
The main idea of the survey is to collect feedback and have an idea of how that will affect the downstream users when we do the branch rename. 
So we can plan to do the change in the next release cycle or move to the next one.

An "official" answer might take much more time, but if we decide to move in this direction sounds good.

Agree on the extra questions, make it more clear as well

The contact can be both Jeremy and myself.

**Comment by jberkus** [comment]
Well, the question becomes: would we be satisfied with responses from the large vendors and large users (some of them), or do we need to get responses from many small vendors/users?

**Comment by jberkus** [comment]
Per @cpanato on slack, we'll be targeting the organizations we can reach directly.

**Comment by cpanato** [comment]
I think if possible we can send them directly to all we have information from CNCF and also we send that out in the k-dev mailing list and use social media to broadcast more

**Comment by jberkus** [comment]
Survey is finished and is being sent out to all of the recipients we could think of by @onlydole, including social media, Leads, K-Dev, the Conformance list, CNCF's End Users, and some individual contacts at large vendors.

https://www.surveymonkey.com/r/k8s-branch-rename

**Comment by jberkus** [comment]
This issue will remain open until May 31st, when the survey closes.

**Comment by jberkus** [comment]
Survey has been completed.

Detail data has been sent to recipients.

**Comment by justaugustus** [comment]
Thanks again, Josh!!

**Comment by cpanato** [comment]
many thanks josh <3
