### ISSUE TITLE
How to handle "do-not-merge/invalid-commit-message"

### ISSUE THREAD

**Issue by guettli** [kubernetes/community#6576]
### Describe the issue

I accidentely used `close #NNNN` in my commit message.

The PR got the `do-not-merge/invalid-commit-message` label.

I updated the commit-message via the webgui of github, but the label was not removed.

Please update the docs and explain what I can do to remove the label.

Docs: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#do-not-use-github-keywords-or-mentions-within-your-commit-message

Related PR: https://github.com/kubernetes/website/pull/32637

**Comment by guettli** [comment]
I was blind. Sorry

**Comment by guettli** [comment]
Reopen: I work with git since ages, but I have never changed a commit message. Maybe it would be good to have a hint at this place:

https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#do-not-use-github-keywords-or-mentions-within-your-commit-message

**Comment by mrbobbytables** [comment]
We have this documented in our pull-request guidelines
https://github.com/kubernetes/community/blob/master/contributors/guide/github-workflow.md#5-commit-your-changes
