### ISSUE TITLE
Make Helm able to disable auto-generate-certs

### ISSUE THREAD

**Issue by erkules** [kubernetes/community#6577]
### Describe the issue

`--auto-generate-certificates` is enabled by default.
Right now it can be disabled by setting protocolHttp. 
As an admin I would like to provide an option to disable `--auto-generate-certificate` and still run HTTPS.
I would like to provide a patch giving the opportunity disable  by .Values.disableGenerateCertificates.
This wold unset `--auto-generate-certificates` and disable the also hardcoded `volumeMounts` for `/certs` so that admins are able to mount there own certs (using `extraVolumeMounts`)

**Comment by mrbobbytables** [comment]
The helm project is independent of kubernetes. Please see https://github.com/helm instead


/close

**Comment by erkules** [comment]
I opened an issue on https://github.com/kubernetes/dashboard
and landed here. There ist the "bug" I doubt the helm-people would fix something in https://github.com/kubernetes/dashboard
