### ISSUE TITLE
Dead link to plugins yaml in Setting up the CNCF CLA check document

### ISSUE THREAD

**Issue by furkatgofurov7** [kubernetes/community#6581]
### Describe the issue

The reference link to plugins.yaml in https://github.com/kubernetes/community/blob/master/github-management/setting-up-cla-check.md#label-automation is dead and the correct link should be the https://git.k8s.io/test-infra/config/prow/plugins.yaml because `prow/plugins.yaml` was moved to `config/prow/plugins.yaml`

**Comment by furkatgofurov7** [comment]
I am happy to put a fix if it is actually a wrong link and agreed upon with maintainers!

**Comment by mrbobbytables** [comment]
Thanks!

/remove-sig docs
/sig contributor-experience
/area github-management
