### ISSUE TITLE
REQUEST: New private Slack channel sig-security-external-audit-2022

### ISSUE THREAD

**Issue by reylejano** [kubernetes/community#6625]
### GitHub Username

reylejano

### Slack Username

rlejano

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

Channel

### Name of Requested Resource

sig-security-external-audit-2022

### Description of Request

Request a private slack channel for the duration of the 2022 third party security audit with the SIG Security Third-party subproject and vendor, NCC Group, to discuss audit proceedings and any sensitive findings that are subject to embargo.

**Comment by reylejano** [comment]
cc: @tabbysable @IanColdwater 

This request is for a private Slack channel for the 2022 third-party security audit and will be deleted after the audit findings are published.

**Comment by mrbobbytables** [comment]
+1 to creation

**Comment by markyjackson-taulia** [comment]
+1 to creation

**Comment by reylejano** [comment]
Thank you @mrbobbytables @markyjackson-taulia @tabbysable , let me know what the next steps are

**Comment by mrbobbytables** [comment]
channel has been created 👍 

/close
