### ISSUE TITLE
how to use rkube?

### ISSUE THREAD

**Issue by Chenhait** [kubernetes/community#6628]
### Describe the issue

hi, i have read the wonderful paper "Mind the Gap: Broken Promises of CPU Reservations in Containerized Multi-tenant Clouds".
i want to make some experiment about this paper.
however, i am a new bird in kubernetes, 
could you tell me about how to install the rkube?
thank you very much, and wish you a happy life.

**Comment by mrbobbytables** [comment]
rkube is not an upstream kubernetes project,  I think this is the repo you're looking for:
https://github.com/a-yiorgos/rkube

With that though - I'm going to go ahead and close this out. Goodluck!

/close
