### ISSUE TITLE
Help Wanted: Drafting tweets for KubeCon EU 2022

### ISSUE THREAD

**Issue by Atharva-Shinde** [kubernetes/community#6630]
### Describe the issue

As KubeCon EU '22 is approaching, 

We at ContribEx Upstream Marketing Team are looking for **contributors** to help in drafting a bunch of tweets for the KubeCon EU Keynotes and events for the Kubernetes Contributors (@K8sContributors) twitter account.

Those interested, feel free to comment and do **reach out to @contibutor-comms group in #sig-contribex** channel on slack to get started.

Great opportunity for new contributors!

Everyone is welcome to contribute!

Edit: Ref this thread https://kubernetes.slack.com/archives/C1TU9EB9S/p1651255589637289

**Comment by Ayan-thecodeking** [comment]
hey @Atharva-Shinde I want to work on this issue .. 
let Me know if it is pending

**Comment by NitishKumar06** [comment]
Hey @Atharva-Shinde , I'm beginner to K8s. I believe this is the perfect issue for me to get started . Can you guide me on what's need to be done?

**Comment by Atharva-Shinde** [comment]
Unfortunately all the work for tweets of KubeCon EU 22 has been done with as the event's already passed.

Nevertheless you can join the Kubernetes server on slack if you haven't yet. There's always some or the other work new contributors like you can help with!
@Ayan-thecodeking @NitishKumar06
