### ISSUE TITLE
Unconference Topics - KCEU Contributor Summit 2022 Valencia

### ISSUE THREAD

**Issue by pnbrown** [kubernetes/community#6633]
### Describe the issue

Hi folks,
We're hosting an Unconference for the Contributor Summit this year in Valencia. We'd love to hear from you about topics in which you are interested. You can submit a topic, and upvote topics that seem interesting to you. We want to understand what is of general interest to the community, and not just for those who happen to be joining us in Valencia.

Topic: [Sample Topic Submission]
Description: [Sample Topic Description]
Moderator: [Will you be there in person and like to moderate? (yes or no)]

To upvote, please use the `:+1:` emote

Feel free to reach out to @pnbrown (`@nigel` in Slack) for any questions.

Thank you!
Nigel Brown, KCEU Contributor Summit 2022 Content Lead

**Comment by youngnick** [comment]
Topic: The Gateway API and its future
Description: The Gateway API has been getting more visibility in the last six months or so. Both Rob Scott and Nick Young are planning on being present, so we can give an update on where things are at and take questions or talk about what's happening.
Moderator: @youngnick and @robscott if he's up for it.

**Comment by pohly** [comment]
Topic: Structured and contextual logging
Description: [Structured logging](https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#structured-logging) enables Kubernetes components to emit log data as JSON, which is faster, easier to parse, and has a richer semantic. [Contextual logging](https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#contextual-logging) is new in 1.24. It enables callers to add additional information to all log entries created while processing, for example, a certain request. Some members of the [structured logging WG](https://github.com/kubernetes/community/tree/master/wg-structured-logging) will be present to explain these features and answer questions. We are also looking for volunteers who want to help migrate code in Kubernetes...
Moderator: @pohly and @shivanshu1333

**Comment by aojea** [comment]
Topic: Successful and Sustainable Quality
Description: Kubernetes is no longer a child, it grew so fast and so big that current quality expectations are very high.
However, it has already started to show symptoms that the quality is not as good as developers and users desire:
jobs failing permanently, flaky tests, regressions, bugs introduced by new features, technical debt never addressed, ...
Some of the problems are well known, some of those are technical, but others, like the SIG staffing and reviewers/approvers/OWNERS renewal are more complex to solve and with a bigger impact on the sustainability of the project.
Despite several initiatives has been started to address these problems, we should have a more holistic answer, considering all the aspects of the problem, and trying to address the root causes first.
Moderator: @aojea and @wojtek-t 
References:
[Open letter to Kubernetes reviewers/approvers (and contributors!)]( https://groups.google.com/a/kubernetes.io/g/dev/c/6F3h0Z1QzVg/m/43tdYs_lAAAJ)
[KEP-3138: Increase the Reliability Bar proposal](https://github.com/kubernetes/enhancements/pull/3139)

**Comment by sttts** [comment]
Topic: Serving APIs to Workspaces in KCP. A Reset of how we think about CRDs. Also: name^Wworkspaced CRDs.
Description: CRDs are everywhere. Operators are a thing. CRD evolution is still a very hard topic, and offering CRDs and semantics in a super-multi-tenant setup (= thousands of tenants) even more so. KCP tries to reset our view of what a CRD is, how it is installed, how it is updated, how RBAC policy is applied and how admission works. Building something that is made for a API service providers by reinventing CRDs while still using all the code behind CRDs.
Moderator: @sttts 
References: https://github.com/kcp-dev/kcp

**Comment by pohly** [comment]
Topic: [Dynamic Resource Allocation KEP](https://github.com/kubernetes/enhancements/pull/3064)
Description: Users are increasingly deploying Kubernetes as management solution for new workloads (batch processing) and in new environments (edge computing). Such workloads no longer need just RAM and CPU, but also access to specialized hardware. With upcoming enhancements of data center interconnects, accelerators can be installed outside of compute nodes and be connected to nodes dynamically as needed. This KEP introduces a new API for describing such resource needs with support for network-attached resources, sharing of a resource allocations between multiple containers or pods, reuse of an allocation with expensive initialization, and custom parameters. Support for new hardware will be provided by hardware vendor add-ons, without having to modify Kubernetes.
Moderator: @pohly
References: https://github.com/kubernetes/enhancements/pull/3064, https://github.com/pohly/kubernetes/pull/1

**Comment by sftim** [comment]
Topic: Improving diagrams for Kubernetes
Description: Diagrams help make for good tech docs. Which are the topics that need good diagrams? These could be end-user concepts such as VerticalPodAutoscaler or ReplicaSet. Internal topics are fair game too - we can add diagrams to content within https://k8s.dev/ and help get new contributors up to speed sooner.
References: https://www.k8s.dev/blog/2021/12/01/improve-your-documentation-with-mermaid.js-diagrams/ and [Guide to Technical Report Writing](https://www.sussex.ac.uk/ei/internal/forstudents/engineeringdesign/studyguides/techreportwriting#7)

I'll take part in this topic discussion if it happens.

**Comment by marquiz** [comment]
Topic: [Class Resources KEP](https://github.com/kubernetes/enhancements/pull/3004)

Description: Not all resources can be managed with the current Kubernetes resource model. This KEP introduces the concept of class resources which could be described as "QoS resources" or "opaque non-integer resources". Think about extended resources for non-accountable resource types. The initial motivation for class resources was [Intel RDT (Resource Director Technology)](https://www.intel.com/content/www/us/en/architecture-and-technology/resource-director-technology.html) which is a class-based mechanism for controlling the cache and memory bandwidth allocation. Currently, there is support for RDT and also a class-based configuration mechanism of the blockio/io cgroup controller in CRI-O and containerd runtimes.
moderator: @marquiz and @kad 
References:
- [KEP-3004 (issue)](https://github.com/kubernetes/enhancements/pull/3004)
- [KEP-3004 (PR)](https://github.com/kubernetes/enhancements/pull/3004)
- [RDT support in CRI-O (PR)](https://github.com/cri-o/cri-o/pull/4830)
- [RDT support in containerd (PR)](https://github.com/containerd/containerd/pull/5439)

**Comment by luxas** [comment]
Topic: Why is Kubernetes and cloud native principles the way they are?

Kubernetes is often described as designed from “decades of experience”, but it is not as often mentioned what that means in practice. Quite conversely, many newcomers to Kubernetes find it “too complex”. Why is it, or why is that the impression? What is actually the principle of cloud native? Why were certain design decisions made in k8s? What are the fundamental problems hard problem Kubernetes solves without the user even knowing they had that problem to begin with?

This session could help document answers and further discussion items for these questions.

Full disclosure, I'm very interested in these topics and have started some of this aggregation and consolidation in my BSc thesis and upcoming KubeCon talk, but I'd like to get feedback, collaborate and improve further, this is just the beginning:

- BSc thesis: Encoding human-like operational knowledge using declarative Kubernetes operator patterns, published at https://github.com/luxas/research
- KubeCon talk: Understanding Kubernetes Through Real-World Phenomena and Analogies https://kccnceu2022.sched.com/event/ytr4

**Comment by mrbobbytables** [comment]
Summit is over, thanks all!

/close
