### ISSUE TITLE
REQUEST: New Slack channel for contributor-comms

### ISSUE THREAD

**Issue by chris-short** [kubernetes/community#6637]
### GitHub Username

chris-short

### Slack Username

chris-short

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

Channel

### Name of Requested Resource

contributor-comms

### Description of Request

Contributor Comms has grown to the point where we need more than adhoc mentions in #sig-contribex and ever evolving DM groups. Having our own channel could allow for more organized conversations, history retention, and central place to ask questions.

**Comment by jberkus** [comment]
+1, agreed this is needed for communications

/lgtm

**Comment by mrbobbytables** [comment]
I'd lean towards calling it something like sig-contribex-comms or something along those lines just to follow the general pattern we have for sig channels, but overall +1 to the idea.

**Comment by chris-short** [comment]
+1 @mrbobbytables

**Comment by chris-short** [comment]
On second thought, that would break the consistent naming throughout the project spaces. Hmm…
Thoughts @kaslin?

**Comment by chris-short** [comment]
FYI @jberkus and @mrbobbytables ^^^

**Comment by mrbobbytables** [comment]
Please go ahead and open a PR to add it 👍
