### ISSUE TITLE
Renaming marketing-team to contributor-comms impact survey

### ISSUE THREAD

**Issue by chris-short** [kubernetes/community#6641]
### Describe the issue

We want to change the marketing-team subdirectory name to contributor-comms. But, we need to be ready with PRs in case it's mentioned in other files.

Here's the thankfully short list for things with marketing-team in the string: https://gist.github.com/chris-short/3288cb1273654e9323a14156ad58b6fc

I checked out all kubernetes repos and grepped recursively and case insensitively.

**Comment by chris-short** [comment]
This will need to be broken up into four (4) different PRs based on what needs changing. All mentions of marketing-team need to be replaced with contributor-comms. Here's how I'd manage the PRs:

Look in higher level directory for OWNERS files to see who has approval rights.

1. `community` repo has multiple mentions; sigs.yaml likely needs an independent PR
   1. community/committee-steering/governance/sig-governance.md
   1. community/communication/calendar-guidelines.md
   1. community/communication/marketing-team/CHARTER.md
   1. community/communication/marketing-team/role-handbooks/storytellers.md
   1. community/events/elections/2020/divya-mohan.md
   1. community/events/events-team/marketing/README.md
   1. community/mentoring/programs/shadow-roles.md
   1. community/sig-contributor-experience/README.md
   1. community/sig-contributor-experience/meeting-notes-archive/2019-meeting-notes.md
   1. community/sig-contributor-experience/meeting-notes-archive/2020-meeting-notes.md
1. `contributor-site/content/en/blog/2021/non-code-contribution.md` (it's a blog but it talks about this group and should be accurately describing and linking to it)
1. The `website` has several mentions of marketing-team and they may or may not need to be updated accordingly
   1. website/content/en/blog/_posts/2020-04-21-contributor-communication-upstream-marketing.md
   1. website/content/en/blog/_posts/2020-04-21-contributor-communication-upstream-marketing.md
   1. website/content/en/blog/_posts/2020-04-21-contributor-communication-upstream-marketing.md
   1. website/content/en/blog/_posts/2020-04-21-contributor-communication-upstream-marketing.md
   1. website/content/en/blog/_posts/2020-04-21-contributor-communication-upstream-marketing.md
   1. website/content/en/blog/_posts/2020-10-12-steering-committee-results.md
   1. website/content/en/blog/_posts/2021-11-08-steering-committee-results-2021.md
   1. website/content/en/docs/contribute/new-content/blogs-case-studies.md
   1. website/content/zh/blog/_posts/2021-11-08-steering-committee-results-2021.md
   1. website/content/zh/blog/_posts/2021-11-08-steering-committee-results-2021.md
   1. website/content/zh/docs/contribute/new-content/blogs-case-studies.md
   1. website/content/zh/docs/contribute/new-content/blogs-case-studies.md
1. Do `community/sigs.yaml` separately and preferably in a timely fashion or else we're locking ourselves out of our repo until it's merged

This work should be coordinated throughout the course of a day so things don't break in weird ways.

**Comment by chris-short** [comment]
Also, you can check here for any other potentially lingering places: https://cs.k8s.io/?q=marketing-team&i=nope&files=&excludeFiles=&repos=

**Comment by harshitasao** [comment]
Thank you, @chris-short. This is very helpful. I will make a PR soon.

**Comment by jberkus** [comment]
Hey, I added this to the ContribEx meeting for tommorrow; need to know what the timing is on this so that I can approve a bunch of PRs.

**Comment by chris-short** [comment]
@harshitasao Do you think these are ready to go?

**Comment by nate-double-u** [comment]
Can we leave breadcrumbs behind so as to not break any existing links? (i.e. leave a README.md file in any folder that's been renamed with info about where the files have gone)

That would make PRs like https://github.com/kubernetes/website/pull/34451 unneeded I think.

**Comment by kaslin** [comment]
@jberkus @harshitasao I think we're ready to go when you all are. It's been a while at this point so these might need some updates and @nate-double-u has a good suggestion here.

**Comment by kaslin** [comment]
Website PR was just rebased, per @harshitasao so I think we should send these. @jberkus?

**Comment by chris-short** [comment]
Well, if anyone can approve this that'd be awesome.

**Comment by cblecker** [comment]
What needs approval? This is an issue, not a PR, and all the linked PRs to this issue are either merged, closed, or failing tests.

**Comment by kaslin** [comment]
These are in aside from the one that is broken. However none of these actually changed the subdir name, so all of these just broke things by putting in the link we want, not the link there is. @reylejano is going to walk a new contributor through doing that change.
