### ISSUE TITLE
Ingress NGINX future survey

### ISSUE THREAD

**Issue by rikatz** [kubernetes/community#6657]
### Group Requesting

Ingress NGINX / sig-net subproject

### Title of Survey

Shaping the future of Ingress NGINX

### Goal of Survey

Research what features are more used in ingress-nginx, what should be deprecated, what are the pain points to adopt later versions and what we recently broke that may have caused problems (will help us define how to fix it)

### Target Audience

Ingress NGINX users

### Results Recipients

rikatz strongjz

### Date Survey Starts

Tbd

### Date Survey Ends

Tbd

### Publicity Help Wanted?

Yes

### Data Analysis Wanted?

Yes

### Link to Draft Questions

Tbd

**Comment by rikatz** [comment]
We will define the questions after kubecon.

**Comment by strongjz** [comment]
@jberkus We started this document here https://docs.google.com/document/d/1sH1INQPRHeIe2yAWG3w3zyUOqy9Pnkc8__aBmDOdTkA/edit?usp=sharing

**Comment by jberkus** [comment]
OK, the survey questions look good and complete.  I can turn this into a surveymonkey survey and ask Comms to help broadcast as soon as you're ready.

**Comment by strongjz** [comment]
Unless @rikatz disagrees we can send it out as soon as it's ready.

**Comment by rikatz** [comment]
I will never disagree with you James, unless you tell me that it is kubecuddle and not kube-c-t-l

@jberkus if it’s my call, I think this can be send as soon as contribex can send it :) we are ready for this!

**Comment by strongjz** [comment]
/assign @jberkus 

We have reviewed the Doc with Josh, next step is to get the survey into survey monkey and send it out to the k dev mailing list.

**Comment by jberkus** [comment]
@kubernetes/contributor-comms  this survey is in final review.  Once it's ready we'll want to promote it.

**Comment by jberkus** [comment]
The survey is now ready:  https://www.surveymonkey.com/r/ingressngx2022

Comms, let's discuss promoting it on Monday.

**Comment by AvineshTripathi** [comment]
Hey @jberkus, from comms I've taken up this task to promote this survey

**Comment by jberkus** [comment]
@rikatz the survey has been open for 3 months and you have 62 responses.  Do you want to close it?  Or do you want to do another round of promoting the survey?

![image](https://user-images.githubusercontent.com/115146/185256866-42b97fdc-08e5-4f6f-a2b3-0a75d41fd713.png)

**Comment by rikatz** [comment]
I think we can close it :) thanks Josh

@strongjz thoughts?

**Comment by jberkus** [comment]
The survey is closed and data dispatched to the survey owners.
