### ISSUE TITLE
Adding steps/detail to Contributor Guide - Getting Started

### ISSUE THREAD

**Issue by jaytiaki** [kubernetes/community#6663]
### Describe the issue

(Experience of new Contributor) The Guide assumes that those navigating the page(s) might have pre-existing knowledge about Kubernetes, some terminology e.g. 'SIGs' on the 'Welcome' page, and the concept of contribution. 

Would there be value in adding brief descriptions/breakdowns of these (providing links for further info as required), in the event this is a visitors first introduction to K8s? Aspects of the current format seems overwhelming.  _For example:_

**(Welcome section)**

**What is Kubernetes?**
Kubernetes is a system for managing containerized applications across a cluster of servers. It provides basic mechanisms for deployment, maintenance, and scaling of applications. __Want to know more?_ (link provided)_

**What does it mean to 'contribute?**
‘Open source’ projects such as Kubernetes rely on those within its community to help with continuously improving the software and its functionality. To make sure everything runs smoothly and meets the needs of its users, we need 'Contributors' within our community to provide their unique perspective and/or expertise to support in maintaining the platform... etc.

**(Contributor Guide section)**

Any thoughts/feedback welcome.

**Comment by parispittman** [comment]
I would be happy to accept PRs in areas that do not have our terms spelled out and defined like SIGs but at this stage in the game, I would hope folks are aware of Kubernetes and what it does by the time they start contributing. Most of the contribution areas right now require you to know and understand the basics of Kubernetes. Maybe link to the kubernets.io site in the first paragraph of the guide?

**Comment by mrbobbytables** [comment]
I agree with Paris - you really should have some base knowledge of what Kubernetes is before you should consider contributing to it. FWIW, we are going to be publishing a new contributor course that will cover a bit more of the general "what is a SIG" type questions in a streamlined onboarding path. These days I think the contributor guide itself is a bit more of a reference instead of start to finish type thing...It's BIG. :x

**Comment by jaytiaki** [comment]
Thank you both for your considered feedback.
@parispittman - That's all clear and helpful, I'll have a crack at those PRs as suggested :)
@mrbobbytables - The contributor course sounds awesome; can I ask if I specific Repo has been created to develop this? I'm currently starting similar work to support underrepresented groups/individuals into the space, so don't want to risk potentially doubling-up on efforts. It'd also be great learning for my team and I in general.

Thanks for clarifying the guide's purpose as well; probably explains why I've been getting lost!
