### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by FeU-aKlos** [kubernetes/community#6697]
### Describe the issue

The link  for the slides about the k8s-icons is broken.
[Kubernetes_Icons_GSlide](https://docs.google.com/presentation/d/15h_MHjR2fzXIiGZniUdHok_FP07u1L8MAX5cN1r0j4U/edit)

**Comment by heysujal** [comment]
@RajGM Hi , I want to work on this issue , can you guide me how do I go about fixing this ?
What is the correct link and where it has to be placed ?

**Comment by RajGM** [comment]
Hi @heysujal 
The links were fixed by the admins.

**Comment by RajGM** [comment]
Hi @heysujal 
I am new to open source as well.
I am looking into this as well.

**Comment by divya-mohan0209** [comment]
Hello @FeU-aKlos , please can you tell us where exactly did you find the broken link?

Also, @RajGM - would request you not add labels before seeking clarification on what the issue actually is.  Without any information, it does not seem related to sig-docs, and hence will be removing the label.

**Comment by RajGM** [comment]
Got it, @divya-mohan0209

**Comment by FeU-aKlos** [comment]
@divya-mohan0209 the link was is the README.md file. JamesLaverack fixed it by removing the broken link! Nevertheless, do you still have a link which is working? would like to see the slides again...
