### ISSUE TITLE
1Password for SIG CLI

### ISSUE THREAD

**Issue by eddiezane** [kubernetes/community#6699]
### Describe the issue

SIG-CLI is requesting a 1Password vault to share credentials.

/assign @mrbobbytables 
/cc @soltysh @KnVerey @seans3 @natasha41575

**Comment by mrbobbytables** [comment]
Sorry, this dropped off my radar. I'll provision it now

**Comment by mrbobbytables** [comment]
Invites have been sent to the emails associated with the sig cli leads list. LMK if they should go elsewhere.

**Comment by BenTheElder** [comment]
@mrbobbytables Is 1password management something we should delegate to a team like GitHub admins, or something we should kick up to steering? I know you've had a lot between steering and understaffed contribex.

**Comment by mrbobbytables** [comment]
steering owns the root account(s) as a breakglass emergecy type thing, but it should be owned by a team similar to GitHub admins, but not necessarily the same group.

**Comment by eddiezane** [comment]
No worries - thanks Bob! I accepted the invite but don't seem to be able to create a shared sig cli vault.

**Comment by mrbobbytables** [comment]
You should be able to now, after you accept an admin has to confirm your invitation and add you to groups

**Comment by BenTheElder** [comment]
> steering owns the root account(s) as a breakglass emergecy type thing, but it should be owned by a team similar to GitHub admins, but not necessarily the same group.

+1, didn't mean the same group, but it sounds like we should consider spinning up a group in a similar pattern.

**Comment by cblecker** [comment]
It appears this is complete. If you need something else, please let us know.

/remove-lifecycle stale
/close
