### ISSUE TITLE
Enforce git version when doing vendor dir update.

### ISSUE THREAD

**Issue by karataliu** [kubernetes/community#670]
In the change https://github.com/kubernetes/kubernetes/pull/45430/files

Comment line of godeps file was changed to 8 digit commit id.
For example:
```
"Comment": "v0.4-3-gc0656ed",
```
Changed to 
```
"Comment": "v0.4-3-gc0656edd",
```

This comes from describe command of git:
https://github.com/tools/godep/blob/27c0bbc57621664758b01b10cdbca24112c7a118/vcs.go#L43

'--abbrev' controls it but the default value has changed from 8 digits to 7 digits, since v1.7.0:
See:
https://git-scm.com/docs/git-describe/1.6.0
https://git-scm.com/docs/git-describe/1.7.0

Can consider add a hint in page, about git version to avoid such unnecessary change. 
https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md

For now, with new version of git >= v1.7, running './hack/godep-save.sh' on current master(b58c7ec) would change those back to 7 digits.

**Comment by nikhita** [comment]
/remove-lifecycle rotten

Still relevant.

**Comment by nikhita** [comment]
The comment problem is fixed by https://github.com/kubernetes/kubernetes/pull/70718 so we don't need to enforce the git version anymore. Closing.

/close
