### ISSUE TITLE
Community Meeting: Requesting a new label - `area/community-meeting`

### ISSUE THREAD

**Issue by MadhavJivrajani** [kubernetes/community#6704]
### Describe the issue

@nimbinatus suggested adding a new label `area/community-meeting` in order to try and ease curation of content for the monthly Kubernetes community meeting. 

Some more specifics:
- Anyone can add this label on an issue or a PR
- Before a community meeting, the issues and/or PRs with
  this label are taken and filtered down and curated for the 
  meeting.

TODO:
- [x] Lazy Consensus for change
- [ ] Merge PR in test-infra to add this label

Relevant slack discussion: https://kubernetes.slack.com/archives/C1TU9EB9S/p1646751118742639 

/cc @nimbinatus

**Comment by nimbinatus** [comment]
Thank you for doing this! Relates to #6544

**Comment by cblecker** [comment]
Two questions:
- Should this label apply to all orgs/repos, or only specific ones like k/commmunity?
- If the latter, has our chartered consensus process been followed for this change? https://github.com/kubernetes/community/blob/master/sig-contributor-experience/charter.md#cross-cutting-and-externally-facing-processes

**Comment by MadhavJivrajani** [comment]
@cblecker thanks for pointing that out. I missed that.

> Should this label apply to all orgs/repos, or only specific ones like k/commmunity?

All orgs/repos. Since a PR or issue from any org/issue can be of interest to the broader community.
This change virtually "effects" all SIGs/WGs in that all repos across orgs will have this label, but it is also a low risk change which can be rolled back if needed. I can send a laze consensus notice to k-dev with this issue if needed.

**Comment by cblecker** [comment]
That all makes sense to me! Feel free to proceed with seeking consensus :)

**Comment by mrbobbytables** [comment]
> All orgs/repos. Since a PR or issue from any org/issue can be of interest to the broader community.
My one thought on this is, how likely are the folks running the meetings actually going to SEE items outside of k/community?
if we had an issue template here with it we might be able to build the list of items more easily.

**Comment by MadhavJivrajani** [comment]
This dropped off my radar, sorry!

@mrbobbytables 
> My one thought on this is, how likely are the folks running the meetings actually going to SEE items outside of k/community?
if we had an issue template here with it we might be able to build the list of items more easily.

Please correct me if I've misunderstood something here, but what I understand from the above point is that it would be easier for folks running the meetings to curate a list of items if there was an issue template  for this in k/community because it would be a single location for access as well as the content of each item would be structured to some extent.

Provided my above understanding is correct, yes - this would definitely make it easier to build the list of items, but the intent of having a label is to have a method that's as low effort as possible. We would gain ease of use but loose out on the fact that the content is not structured anymore and someone would have to go and read the discussion to understand what's up. Maybe we can have both?

[Consideration for the label approach] If we do end up doing the label approach, we can document how someone can access all issues/PRs with that label using a GitHub query and what to do once they have this list of issues/PRs.

**Comment by nimbinatus** [comment]
Dropping an update here as I seem to have lost track of this issue: Yes, we would very much like to get the label across the repos in the org if possible. It reduces the bar to get a topic on the list of discussion, and it would help drive discussion out to SIGs' repos (which might help drive contributors to SIGs) during the community conversation, as well. I'm all for avoiding duplicating content across repos and keeping discussions in one place if we can.

**Comment by MadhavJivrajani** [comment]
FYI - comms for lazy consensus have been sent out: https://groups.google.com/u/1/a/kubernetes.io/g/dev/c/CVkurn6mUuQ

**Comment by MadhavJivrajani** [comment]
The lazy consensus deadline for this has passed! 
Lazy consensus email: https://groups.google.com/u/1/a/kubernetes.io/g/dev/c/CVkurn6mUuQ

**Comment by MadhavJivrajani** [comment]
/remove-area community-meeting
yay!
(sorry for the additional comments)
