### ISSUE TITLE
Community Meeting Calendar item should link to the RO version of the notes

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#6708]
### Describe the issue

Currently:

The Community Meeting calendar item links to the read-write version of the agenda, which during the meeting can cause the doc to freeze for the note-taker.

Fix:

The calendar item should link to the RO version (http://bit.ly/k8scommunity-ro) and then the agenda itself can have a link to the RW version for people adding items or taking notes.

/sig contributor-experience
/area community-meeting
cc @nimbinatus @bob

**Comment by RajGM** [comment]
Looks like an excellent first issue.

/good-first-issue

/assign

**Comment by RajGM** [comment]
Hi @jberkus 
I checked it out and realized that the Calendar admin needs to change that.
I am currently looking for the read-only file to include a link for the read-write version.

**Comment by RajGM** [comment]
Hi @jberkus 
I think we can close this issue.

**Comment by mrbobbytables** [comment]
/close
no more meeting
