### ISSUE TITLE
REQUEST: New Slack webhook for k8s infra

### ISSUE THREAD

**Issue by ameukam** [kubernetes/community#6717]
### GitHub Username

ameukam

### Slack Username

ameukam

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

Webhook

### Description of Request

I would to be able to send notifications from multiple GCP projects using the GCP monitoring API to the slack channel `#k8s-infra-alerts`.
Ref: https://cloud.google.com/monitoring/support/notification-options#slack

**Comment by ameukam** [comment]
cc @mrbobbytables @markyjackson-taulia

**Comment by ameukam** [comment]
Similar request have be made before: https://github.com/kubernetes/community/issues/4534

**Comment by jberkus** [comment]
So what happened with the original request?

**Comment by jberkus** [comment]
(discussion on Slack ensues)

So this is a request to track additional GCP projects, rather than a request for a new app.  I see no reason not to grant it.

Waiting through the weekend for any knowledgable objections.

**Comment by ameukam** [comment]
gently ping @jberkus @jeefy :-)

**Comment by jberkus** [comment]
This is going to require temporarily making Arnaud an admin, so turning over to @markyjackson-taulia

**Comment by markyjackson-taulia** [comment]
ack
/assign markyjackson-taulia

**Comment by markyjackson-taulia** [comment]
24 hour access has been granted. 
I will close this issue after 24 hours and verification with @ameukam has been completed.

Cc: @jberkus

**Comment by jberkus** [comment]
Is this done now?

**Comment by markyjackson-taulia** [comment]
Yes, this was completed a week or so ago

**Comment by ameukam** [comment]
This is done. 
/close
