### ISSUE TITLE
REQUEST: New Slack channel for SIG-Security assessments

### ISSUE THREAD

**Issue by aladewberry** [kubernetes/community#6722]
### GitHub Username

@aladewberry

### Slack Username

Ala Dewberry

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

Channel

### Name of Requested Resource

Slack

### Description of Request

We would like to request ([reference conversation](https://github.com/kubernetes/community/pull/6512#discussion_r903043770)), a general Slack channel - #sig-security-assessments - to make a space for general discussion about the security self assessments as part of SIG Security. This channel can act as root node of security assessments sub-project  that can branch out to new channels that are project specific: 
sig-security
- sig-security-assessments
-- sig-security-assess-capi
-- sig-security-assess-csi-driver

**Comment by aladewberry** [comment]
@mrbobbytables wooo! I'll work with @tabbysable and @IanColdwater to do it up!

**Comment by PushkarJ** [comment]
@aladewberry (just an idea) if and when you decide to add a new channel with a PR after your chat with our co-chairs, to the file Bob mentioned, it could be a good first issue for some new contributor to work on!

**Comment by tabbysable** [comment]
Officially approving the creation of this slack channel.

Is our next-steps to have Ala PR the creation of the channel into the YAML and slash-approve that PR?

**Comment by markyjackson-taulia** [comment]
Lgtm and holding for another slack admin to approve

/lgtm
/hold

**Comment by aladewberry** [comment]
Done! Figured it out finally!

https://github.com/kubernetes/community/pull/6864

**Comment by PushkarJ** [comment]
/close

(linked pr is merged)
