### ISSUE TITLE
Broken links in sig-scheduling/README.md

### ISSUE THREAD

**Issue by kidddddddddddddddddddddd** [kubernetes/community#6727]
### Describe the issue

The links in [Contect/GitHub Teams]( https://github.com/kubernetes/community/blob/master/sig-scheduling/README.md#:~:text=Community%20Issues/PRs-,GitHub%20Teams,-%3A ) are broken now.

**Comment by mrbobbytables** [comment]
👋 That's normal^^;; You have to be a GitHub org member to see the members of the team. They're private to cut down on the random requests to join. You can manually see the members in the https://github.com/kubernetes/org repo

**Comment by kidddddddddddddddddddddd** [comment]
> 👋 That's normal^^;; You have to be a GitHub org member to see the members of the team. They're private to cut down on the random requests to join. You can manually see the members in the https://github.com/kubernetes/org repo

Oops... Sorry,I'm new here and I didn't know this before😂. Understood now.
