### ISSUE TITLE
REQUEST: New Slack channel #africa-dev

### ISSUE THREAD

**Issue by somtochiama** [kubernetes/community#6729]
### GitHub Username

somtochiama

### Slack Username

somtochiama

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

channel

### Name of Requested Resource

africa-dev

### Description of Request

Hello,

This is inspired by the great work that happens at #in-dev channel⭐️. This is a request for a public slack channel for African contributorsof Kubernetes for easy communication and mentoring of new African devs to the Kubernetes community.

**Comment by ShivamTyagi12345** [comment]
I am a member of SheCodeAfrica. I would love to let the interested folks know about this initiative

**Comment by parispittman** [comment]
hi @somtochiama! awesome! you can request the channel by submitting a PR, too. here is an example and the file to change: https://github.com/kubernetes/community/pull/6728
we can also tag this with help-wanted for other contributors if you don't have the time or desire. :) let us know

**Comment by MadhavJivrajani** [comment]
/close 
As this has been addressed!
Thanks!
