### ISSUE TITLE
Assemble KCSNA 2022 Summit Team

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#6734]
### Describe the issue

The 2022 Summit will be a return to our "regular" summit planning with the usual array of roles. 

The leads for KCSNA Detroit will be myself, @castrojo and @jeefy.  For this summit we will need registration, comms, and content leads, awards + shadows that could potentially take on leading those roles in the future along with some general staff to help with on-site needs.

EDIT: Adding folks for lead/shadow roles from the responses

- Registration
  - Lead: @palnabarun 
  - Shadows:
    - @ameukam
    - @harshitasao
    - @rajaskakodkar
- Comms
  - Lead: @kaslin 
  - Shadows:
    - @AvineshTripathi
    - @Atharva-Shinde 
- Content
  - Lead: @detiber
  - Shadows:
    - @lauralorenz 
    - @markyjackson-taulia
    - @Priyankasaggu11929 
- Awards
  - Lead: @parispittman 
  - Shadows:
    - @jrsapi 
    - @reylejano 
- Social
  - Lead: @salaxander
  - Shadows:
    - @cici37 
- Operations
  - Lead: @qedrakmar 
  - Shadows: 
    - @jimangel 
    - @thecrudge 
    - @tokt 
---
ref: #6733 
/assign @mrbobbytables @jeefy @castrojo 
/sig contributor-experience
/area contributor-summit
/area na-summit
/milestone v1.25

**Comment by parispittman** [comment]
signing up to advise content and/or marketing roles. if you're reading this and had doubts about signing up but need a mentor, look no further. :)

**Comment by markyjackson-taulia** [comment]
I am signing up for whatever is needed.

**Comment by chris-short** [comment]
I'm local so I feel some obligation to provide info or site visits.

**Comment by thecrudge** [comment]
Ill be there! Just let me know what I can do :)

**Comment by palnabarun** [comment]
I can help leads with registrations.

**Comment by parispittman** [comment]
https://github.com/kubernetes/community/tree/master/events/events-team - role books if folks reading this and thinking about signing up want to take a look

**Comment by jberkus** [comment]
I'll work with community artists to design/select a tshirt for the event.

I'm available for other volunteer roles as needed, but would rather not lead anything this time.

**Comment by kaslin** [comment]
Happy to help!

**Comment by markyjackson-taulia** [comment]
I would like to shadow for content but can also take a larger role of the role is not filled by a lead.

**Comment by detiber** [comment]
After re-reading slack and the rest of the comments in this issue, I'm happy to volunteer to lead Content

**Comment by AvineshTripathi** [comment]
Hey folks, I would like to shadow for comms

**Comment by mrbobbytables** [comment]
@parispittman we only do awards at NA, they're EoY. So idea would be to shadow for next year

**Comment by tokt** [comment]
Happy to help wherever help is needed! <3

**Comment by salaxander** [comment]
Interested in shadowing wherever help is needed!

**Comment by jrsapi** [comment]
I would like to shadow Awards.

**Comment by Atharva-Shinde** [comment]
would love to shadow for socials

**Comment by harshitasao** [comment]
I'm interested in shadowing for Registration.

**Comment by reylejano** [comment]
I helped with the last awards (virtual), I can shadow or lead awards for KCSNA 22.

**Comment by Priyankasaggu11929** [comment]
I can shadow Registration, content, or comms or wherever else any help is needed.

**Comment by cici37** [comment]
I could shadow Registration, Comms, Awards or anywhere if help needed :)

**Comment by jimangel** [comment]
Late to the party, happy to help out / fill in any open spots! Catch ya'll there either way!

**Comment by detiber** [comment]
@mrbobbytables please add @Priyankasaggu11929 as a shadow for content.

@qedrakmar if you don't think it would be too much of a distraction from Operations work, I would love to have @jimangel as a shadow for content as well.

**Comment by thecrudge** [comment]
Im in!

------------------
e: ***@***.***
c: 214-603-9075
w: http://www.crudge.io

**Comment by palnabarun** [comment]
@mrbobbytables can you please add @harshitasao as a reg shadow?

**Comment by puja108** [comment]
As mentioned in the call today, bit late to the party as I was on PTO for 3 weeks+, but I will be onsite and happy to help, wherever you still need hands.

From the list above maybe I could help out @salaxander and @cici37 with the social . Otherwise (or additionally) @qedrakmar mentioned ops will definitely need half a dozen hands onsite, so I'm happy to sign up for that already.

**Comment by rajaskakodkar** [comment]
I'd like to help out. I can shadow @palnabarun for registrations. I am willing to lead registrations for EU 2023.

**Comment by mrbobbytables** [comment]
Closing this as the team was assembled 👍 

/close

**Comment by dims** [comment]
![avengers-assemble-gif-3](https://user-images.githubusercontent.com/23304/196055568-de9cb28b-254d-4bb0-974d-233e2a534133.gif)
