### ISSUE TITLE
Recommend Election Officers for the 2022 SC Election

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#6737]
### Describe the issue

The new Elections Subproject needs to prepare a group of Election Officers (three EOs and one alternate) to work the 2022 Steering election.  These should be folks who are known across the project, are not running in the election, and have been org members for at least a year.  

One other requirement is to have at least one EO continue from one year to the next, so @coderanger is already selected for this year's EOs.  This also means that new EOs are making, effectively, a 2-year commitment.

Aside from Noah, @dims and @detiber have volunteered to be EOs, and both qualify.  At a minimum, we need to ratify that selection, and select one alternate.

/sig contributor-experience
/area elections
attn: @jdumars @parispittman @jeremyrickard @fsmunoz @kikisdeliveryservice @CIPHERTron @avines

**Comment by jeremyrickard** [comment]
+1 to the Noah, Dims, and Jason.

**Comment by detiber** [comment]
+1 from me as well

**Comment by fsmunoz** [comment]
FWIW +1 to @coderanger @dims and @detiber, and +1 to @parispittman suggestion of @kaslin (should she be interested of course).

**Comment by AvineshTripathi** [comment]
+1 to paris suggestion for alternate

**Comment by CIPHERTron** [comment]
+1 from me as well for Noah, Dims and Jason.

**Comment by NitishKumar06** [comment]
I have never interacted with  Noah and @detiber but I'd definitely hit +1 for @dims @sftim and @mehabhalodiya

**Comment by markyjackson-taulia** [comment]
+1 from me as well for Noah, Dims and Jason.

**Comment by sftim** [comment]
Thanks for the suggestion but I don't feel I have capacity to be an election officer this time round.

**Comment by Babapool** [comment]
+1 from as well for Noah, Dims and Jason, and +1 to Paris's suggestions for alt (should any of them be interested)

**Comment by detiber** [comment]
+1 from me for both @bridgetkromhout and @kaslin should they be interested

**Comment by kaslin** [comment]
Thanks for the recommendations! I haven't been directly involved in elections before but I'd be happy to help and learn if that's alright.

**Comment by RajGM** [comment]
+1 for @nimbinatus 
+1 for @Nivedita-coder @parul5sahoo

**Comment by jberkus** [comment]
@RajGM I've dropped Nivedita off the list of potential nominees simply because she's on the Release Team right now.

**Comment by jberkus** [comment]
Current list of EO nominees:

* @dims 
* @detiber 
* @nimbinatus (unconfirmed)
* @kaslin 
* @MadhavJivrajani (unconfirmed)
* @mehabhalodiya (unconfirmed)

I have reached out to all of the above candidates, and am waiting to confirm interest from a few of them.

**Comment by dims** [comment]
Happy to do this. If there are enough folks, i am happy to step aside for sure!

**Comment by nimbinatus** [comment]
Thanks for the nomination! I unfortunately can't commit to the time involved right now, but I'm flattered my name came up.

**Comment by MadhavJivrajani** [comment]
> Current list of EO nominees:
> 
> * @dims
> * @detiber
> * @kaslin
> * @MadhavJivrajani (unconfirmed)
> * @mehabhalodiya (unconfirmed)
> * @bridgetkromhout
> 
> I have reached out to all of the above candidates, and am waiting to confirm interest from a few of them. Some suggested candidates have been removed from the list due to either qualifications or being uninterested.
> 
> We need two EOs and one alternate.

I’m happy to help in any way I can! Thanks ❤️

**Comment by mehabhalodiya** [comment]
> Current list of EO nominees:
> 
> * @dims
> * @detiber
> * @kaslin
> * @MadhavJivrajani (unconfirmed)
> * @mehabhalodiya (unconfirmed)
> * @bridgetkromhout
> 
> I have reached out to all of the above candidates, and am waiting to confirm interest from a few of them. Some suggested candidates have been removed from the list due to either qualifications or being uninterested.
> 
> We need two EOs and one alternate.

I'd be happy to help and learn if it's alright! Thanks for the nomination ❤️

**Comment by parul5sahoo** [comment]
>  isn't this Parul's first year contributing to Kubernetes?
 Yes, I am yet to complete one year of contributing to Kubernetes. However, thanks for the nomination @RajGM.
And +1 for @dims, @MadhavJivrajani and @mehabhalodiya .

**Comment by RajGM** [comment]
> Current list of EO nominees:
> 
> * @dims
> * @detiber
> * @kaslin
> * @MadhavJivrajani
> * @mehabhalodiya
> * @bridgetkromhout
> 
> I have reached out to all of the above candidates, and am waiting to confirm interest from a few of them. Some suggested candidates have been removed from the list due to either qualifications or being uninterested.
> 
> We need two EOs and one alternate.

+1 for @mehabhalodiya and @dims

**Comment by kikisdeliveryservice** [comment]
+1 @dims @detiber @kaslin @bridgetkromhout

**Comment by jberkus** [comment]
After a quick secret poll of additional ContribEx folks, the following officers have been selected for recommendation to the Steering Committee:

Election Officers:

* @coderanger 
* @dims 
* @kaslin 

Alternate:

* @bridgetkromhout 

From here it goes to the Steering Committee for approval.  Thanks, everyone!
