### ISSUE TITLE
REQUEST: New Slack channel kubernetes-docs-tr

### ISSUE THREAD

**Issue by mkaramuk** [kubernetes/community#6744]
### GitHub Username

mkaramuk

### Slack Username

@Muhammed Karamuk

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

channel

### Name of Requested Resource

channel

### Description of Request

Turkish localization channel.

**Comment by mrbobbytables** [comment]
sig-docs has been delegated the ability to manage channels with the kubernetes-docs-* prefix, please open a PR to add the channel here:
https://github.com/kubernetes/community/blob/master/communication/slack-config/sig-docs/docs-channels.yaml
