### ISSUE TITLE
REQUEST: New Slack channel multi-network

### ISSUE THREAD

**Issue by mskrocki** [kubernetes/community#6751]
### GitHub Username

mskrocki

### Slack Username

mskrocki

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

Channel

### Name of Requested Resource

multi-network

### Description of Request

We have formed a workgroup to work on introducing multi network concept and a Network construct into Kubernetes. We would like to have a slack channel where we can easily discuss our ideas.

**Comment by aojea** [comment]
/sig network
/Cc @dcbw @thockin 
As sig-network chairs

**Comment by markyjackson-taulia** [comment]
For channel creation, please refer to this [guide](https://github.com/kubernetes/community/blob/master/communication/slack-guidelines.md#requesting-a-channel) for submitting a new channel PR
