### ISSUE TITLE
Document team list more clearly

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/community#677]
In comments of issues or PRs, contributors can find that org members sometimes mention some teams, e.g. `kubernetes/sig-apps-bugs@`, `kubernetes/sig-apps-pr-reviews@`, to request debugging or PR reviewing. But I can't find a documentation to explain these teams. When I click the team name within the comments, I get a 404 error.

There are some questions, which I think other contributors might have also.

- how many such teams are there? Yes we have a documentation [sig-list](https://github.com/kubernetes/community/blob/master/sig-list.md), but there is nothing about such @ teams in the doc. 

- does each sig foo all have these teams? i.e. `kubernetes/sig-foo-bugs`, `kubernetes/sig-foo-pr-reviews`, `kubernetes/sig-foo-feature-requests`, `kubernetes/sig-foo-misc`.

- what's the responsibility of these teams? By the name, what I can think is debugging, PR reviewing. What's of the team `kubernetes/sig-foo-misc`?

- what's the naming rules of these teams? We have `kubernetes/sig-apps-pr-reviews`, `kubernetes/sig-apps-bugs` which seems to have a good naming rule. I also see team name like `kubernetes/test-infra-maintainers`, `k8s-sig-openstack-bugs`, `kubernetes/kubectl`. How can contributors know the teams if they never ever see them before?

- who are in the team? I can't find a member list of a team anywhere. I just get a 404. The reason what I can think is that the team is a mail list, we don't want to public our member's mail, right?

- how to join such a team? If some contributors want to help more for community by joining some such teams, how to join?

- why can't non-members mention these teams? In the past, non-members can't mention these teams at all. Currently, non-members can mention the teams, and the bot will help to trigger a notification to the team. Then why don't we allow contributors trigger a notification directly?

- ...

It would be great if there is a documentation describing these questions clearly. Thanks!

@bgrant0607 @grodrigues3 @sarahnovotny @thockin 

@kubernetes/sig-contributor-experience-misc Hope this team exists...

**Comment by xiangpengzhao** [comment]
One more thing, it would be good to make sig name consistent with sig label. We have sig directories in community root, and sig labels in this page: https://github.com/kubernetes/kubernetes/labels

But some sig names are not consistent, for example, `sig-on-premise` vs `sig/onprem`. And we have `sig-ui` in community but there isn't a label `sig/ui` in kubernetes repo.

**Comment by xiangpengzhao** [comment]
Also post this issue at https://groups.google.com/forum/#!topic/kubernetes-wg-contribex/Bo0TnJEljoA

**Comment by idvoretskyi** [comment]
@xiangpengzhao I've been a person, responsible for the SIG+Teams new procedure and have documented the steps to create a SIG at https://github.com/kubernetes/community/blob/master/sig-governance.md#sig-creation-procedure.

Please, let me know if something is unclear still/has to be enhanced.

**Comment by xiangpengzhao** [comment]
@idvoretskyi Thanks for the information, Ihor! The doc is very helpful! 

It would be great to add some guidance for contributors, as below.

- explain briefly how contributors can join such a google group in case some new beginners are not clear.

- explain how contributors can notify a team in their comments. The chapter [Create the GitHub teams](https://github.com/kubernetes/community/blob/master/sig-governance.md#create-the-github-teams) only introduces the name convention of github teams. But I still don't see how to mention a team. What I know the mentioning way is @kubernetes/sig-foo-bar.

- the example `sig-onprem` doesn't use the name convention, unfortunately. It's group name is `sig-onprem`, but the directory name in this repo is `sig-on-premise`, as is mentioned in my above comment. Should it be renamed?

- provide a way that contributors can find this doc. What I can think is let K8S-bot give a link in some of its auto-reply. @fejta

**Comment by idvoretskyi** [comment]
@castrojo aren't you working on the similar task now?
