### ISSUE TITLE
Update slack channel names in "SIGs and Working Groups"

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/community#679]
The two channels `#wg-contribex` and `#kubernetes-release` have renamed. We should update the doc [SIGs and Working Groups](https://github.com/kubernetes/community/blob/master/sig-list.md)

 `#wg-contribex` --> `#sig-contribex`

`#kubernetes-release` --> `#sig-release`

@sarahnovotny

**Comment by cblecker** [comment]
@xiangpengzhao Feel free to send a PR :)

**Comment by xiangpengzhao** [comment]
Thanks Christoph! Will do.
