### ISSUE TITLE
Steering Committee Nomination: David Eads (@deads2k)

### ISSUE THREAD

**Issue by deads2k** [kubernetes/community#6824]
Hi everyone,

I am self-nominating for the upcoming Steering Committee election.

I've worked on Kubernetes in a technical capacity since before 1.0, focusing primarily on sig-auth and sig-apimachinery. I'd be glad to serve on the steering committee.

**Comment by astoycos** [comment]
+1!

**Comment by thockin** [comment]
+1

**Comment by xing-yang** [comment]
+1

**Comment by vonguard** [comment]
+1

**Comment by fedebongio** [comment]
+1 
Employer: Google

**Comment by alaypatel07** [comment]
+1 

Employer: Nvidia

**Comment by aojea** [comment]
+1
Employer: Red Hat

**Comment by tamalsaha** [comment]
💯 

Employer: AppsCode

**Comment by jagosan** [comment]
+1
Employer: Google

**Comment by droslean** [comment]
+1
Employer: Red Hat

**Comment by natalisucks** [comment]
+1
Employer: Wayfair

**Comment by mtaufen** [comment]
+1
Employer: Google

**Comment by hongkailiu** [comment]
+1
Employer: Red Hat

**Comment by gnufied** [comment]
+1
Employer: Red Hat

**Comment by stlaz** [comment]
+1
Employer: Red Hat

**Comment by savitharaghunathan** [comment]
+1
Red Hat

**Comment by JoelSpeed** [comment]
+1
Employer: Red Hat

**Comment by Elbehery** [comment]
+1
Employer: Red Hat

**Comment by smg247** [comment]
+1
Employer: Red Hat

**Comment by tkashem** [comment]
+1

**Comment by awgreene** [comment]
+1

**Comment by sjenning** [comment]
+1
Employer: Red Hat

**Comment by mkumatag** [comment]
+1
Employer: IBM

**Comment by dobsonj** [comment]
+1
Employer: Red Hat

**Comment by elmiko** [comment]
+1
Employer: Red Hat

**Comment by Karthik-K-N** [comment]
+1
Employer: IBM

**Comment by kwiesmueller** [comment]
+1
Employer: Google

**Comment by cici37** [comment]
+1 
Employer: Google

**Comment by reylejano** [comment]
+1
Employer: SUSE

**Comment by RainbowMango** [comment]
+1
Employer: Huawei

**Comment by pacoxu** [comment]
+1
Employer: DaoCloud

**Comment by astraw99** [comment]
+1
Employer: Tencent

**Comment by sxllwx** [comment]
+1!

**Comment by soltysh** [comment]
+1
Employer: Red Hat

**Comment by ydFu** [comment]
+1 👍🏻

**Comment by pigletfly** [comment]
+1

**Comment by droslean** [comment]
+1

**Comment by seans3** [comment]
+1
Employer: Google

**Comment by chaitanyaenr** [comment]
+1
Employer: Red Hat

**Comment by jqmichael** [comment]
+1

**Comment by jasonbraganza** [comment]
+1

**Comment by aravindhp** [comment]
+1

**Comment by lavalamp** [comment]
+1
Employer: Google

**Comment by Jefftree** [comment]
+1
Employer: Google

**Comment by benluddy** [comment]
+1
Employer: Red Hat

**Comment by humblec** [comment]
+1
Employer: Red Hat

**Comment by Huang-Wei** [comment]
+1
Employer: Apple

**Comment by coderanger** [comment]
Per the requirements of the [candidate process](https://github.com/kubernetes/community/tree/41289f0f7e1fdc559c24e09c8e66c1f805fdfd52/elections/steering/2022#candidacy-process), I have verified that David Eads has the necessary endorsements to qualify to run for steering committee.
