### ISSUE TITLE
Steering Committee Nomination: Benjamin Elder (@BenTheElder)

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/community#6826]
Copying from the [mailinglist thread](https://groups.google.com/a/kubernetes.io/d/msgid/dev/CAHXsEpxmdQZZfWtTNsd5oFi2TW-Kmdrjg%2BgD81nYb-ODAAHQew%40mail.gmail.com?utm_medium=email&utm_source=footer) @ameukam started, to file an issue here for [the candidacy process](https://github.com/kubernetes/community/tree/master/elections/steering/2022#candidacy-process) 😅 

> I would like to nominate Benjamin Elder as Steering Committee member. Ben is an awesome person who is very clearly passionate about the Kubernetes community and has deep technical knowledge of Kubernetes. He's been involved in almost every level of the Project and  I think he would make an excellent addition to the Steering Committee.

I do intend to run; will follow up on the thread to redirect here.

/committee steering

**Comment by ameukam** [comment]
+1
Employer: VMware

**Comment by chaodaiG** [comment]
+1
Employer: Google

**Comment by tamalsaha** [comment]
💯 

Employer: AppsCode

**Comment by mtaufen** [comment]
+1
Employer: Google

**Comment by cjwagner** [comment]
+1
Employer: Google

**Comment by rikatz** [comment]
+1 
Employer: VMware

**Comment by dobsonj** [comment]
+1
Employer: Red Hat

**Comment by michelle192837** [comment]
+1
Employer: Google

**Comment by aojea** [comment]
+1
Red Hat

**Comment by upodroid** [comment]
+1
Employer: Rackspace Technology

**Comment by cpanato** [comment]
+1
Employer: Chainguard

**Comment by puerco** [comment]
+1
Employer: Chainguard

**Comment by endocrimes** [comment]
the biggest of +1's.
Employer: VMware

**Comment by stmcginnis** [comment]
+1
Employer: Amazon

**Comment by detiber** [comment]
+1
Employer: Cisco

**Comment by eddiezane** [comment]
+1
Employer: Chainguard

**Comment by Riaankl** [comment]
+1

**Comment by cici37** [comment]
+1
Employer: Google

**Comment by xing-yang** [comment]
+1

**Comment by savitharaghunathan** [comment]
+1
Employer: Red Hat

**Comment by reylejano** [comment]
+1
Employer: SUSE

**Comment by RainbowMango** [comment]
+1
Employer: Huawei

**Comment by pacoxu** [comment]
+1
Employer: DaoCloud

**Comment by chendave** [comment]
+1

Employer:  arm

**Comment by MadhavJivrajani** [comment]
Huge +1
Employer - VMware

**Comment by nikhita** [comment]
Big +1
Employer: VMware

**Comment by pohly** [comment]
+ 1
Employer: Intel

**Comment by saad-ali** [comment]
+1 
Employer: Google

**Comment by soltysh** [comment]
+1
Employer: Red Hat

**Comment by ydFu** [comment]
+1 👍🏻

**Comment by sbueringer** [comment]
+1
Employer: VMware

**Comment by mkumatag** [comment]
+1
Employer: IBM

**Comment by MrHohn** [comment]
+1
Employer: Google

**Comment by jeefy** [comment]
Massive +1 here. Ben embodies this community/project in everything he does. He is articulate, well-spoken, and has been helping this project longer than many of us. With that experience comes a wealth of opinions and knowledge I think will move Kubernetes forward.

Employer: CNCF/LF

**Comment by seans3** [comment]
+1
Employer: Google

**Comment by jasonbraganza** [comment]
+1

**Comment by vinaykul** [comment]
+1
Employer: Futurewei (Huawei)

**Comment by RinkiyaKeDad** [comment]
+1 
Employer: Okteto

**Comment by lavalamp** [comment]
+1
Employer: Google

**Comment by Jefftree** [comment]
+1
Employer: Google

**Comment by humblec** [comment]
+1
Employer: Red Hat

**Comment by Huang-Wei** [comment]
+1
Employer: Apple

**Comment by uablrek** [comment]
+1
Employer: Ericsson

**Comment by coderanger** [comment]
Per the requirements of the [candidate process](https://github.com/kubernetes/community/tree/41289f0f7e1fdc559c24e09c8e66c1f805fdfd52/elections/steering/2022#candidacy-process), I have verified that Benjamin Elder has the necessary endorsements to qualify to run for steering committee.

Please prepare a bio for yourself based on the [nomination-template](https://github.com/kubernetes/community/blob/master/elections/steering/2022/nomination-template.md) file in the election directory and submit a PR before EoD September 2nd.
