### ISSUE TITLE
Steering Committee Nomination: Bob Killen (@mrbobbytables)

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#6827]
### Describe the issue

I would like to self-nominate for a 2nd and final term on the Steering Committee.

I've served the community in various roles since mid 2017; mainly in contribex, the past two years on steering, and have spent time on the release team in addition to several other roles & subprojects throughout the project. If elected, I'd love the opportunity to continue representing the community by pushing more sustainable practices & policies to build a more sustainable future. 

It's been an honor and pleasure serving the project these past two years and I'd love to continue to represent you for the two to come :)

/committee steering

**Comment by puerco** [comment]
+1 !!!!
Employer: Chainguard

**Comment by devdattakulkarni** [comment]
+1

**Comment by markyjackson-taulia** [comment]
+1
Employer: Independent

**Comment by alculquicondor** [comment]
+1

**Comment by endocrimes** [comment]
+1
Employer: VMware

**Comment by jagosan** [comment]
+1 
Employer: Google

**Comment by ameukam** [comment]
+1
Employer: VMware

**Comment by detiber** [comment]
+1
Employer: Cisco

**Comment by eddiezane** [comment]
+1
Employer: Chainguard

**Comment by kwiesmueller** [comment]
+1
Employer: Google

**Comment by karenhchu** [comment]
+1 
Employer: Microsoft

**Comment by xing-yang** [comment]
+1

**Comment by cici37** [comment]
+1
Google

**Comment by dobsonj** [comment]
+1
Employer: Red Hat

**Comment by fedebongio** [comment]
+1
Employer: Google

**Comment by aojea** [comment]
+1
Employer: Red Hat

**Comment by savitharaghunathan** [comment]
+1
Employer: Red Hat

**Comment by reylejano** [comment]
+1
Employer: SUSE

**Comment by elmiko** [comment]
+1
Employer: Red Hat

**Comment by rikatz** [comment]
+1 
VMware

**Comment by nikhita** [comment]
+1
VMware

**Comment by MadhavJivrajani** [comment]
Huge +1
Employer - VMware

**Comment by natalisucks** [comment]
+1 ❤️ 
Employer: Wayfair

**Comment by saad-ali** [comment]
+1
Employer: Google

**Comment by cpanato** [comment]
+1
Employer: Chainguard

**Comment by ydFu** [comment]
+1 👍🏻

**Comment by swatisehgal** [comment]
+1
Employer: Red Hat

**Comment by salaxander** [comment]
+ 💯 
Employer: Microsoft

**Comment by jasonbraganza** [comment]
+1

**Comment by ahg-g** [comment]
+1

Employer: Google

**Comment by samos123** [comment]
+1

Employer: Google

**Comment by Debanitrkl** [comment]
+ 1

Employer:  Harness

**Comment by JeremyOT** [comment]
+1
Employer: Google

**Comment by chaodaiG** [comment]
+1
Employer: Google

**Comment by jeefy** [comment]
I am, of course, the biggest +1 of them all. But I won't write a long-winded Chaucer-esque support/hype speech this time. His actions this past term have spoken more than I can.

Employer: CNCF/LF

**Comment by tokt** [comment]
+1
Employer: Independent

**Comment by palnabarun** [comment]
Huge +1!!! ❤️ 
Employer: VMware

**Comment by qedrakmar** [comment]
+1
Employer: Oracle

**Comment by seans3** [comment]
+1
Employer: Google

**Comment by vinaykul** [comment]
+1
Employer: Futurewei (Huawei)

**Comment by RinkiyaKeDad** [comment]
+1 
Employer: Okteto

**Comment by lavalamp** [comment]
+1
Employer: Google

**Comment by humblec** [comment]
+1
Employer: Red Hat

**Comment by uablrek** [comment]
+1
Employer: Ericsson

**Comment by coderanger** [comment]
Per the requirements of the [candidate process](https://github.com/kubernetes/community/tree/41289f0f7e1fdc559c24e09c8e66c1f805fdfd52/elections/steering/2022#candidacy-process), I have verified that Bob Killen has the necessary endorsements to qualify to run for steering committee.

Please prepare a bio for yourself based on the [nomination-template](https://github.com/kubernetes/community/blob/master/elections/steering/2022/nomination-template.md) file in the election directory and submit a PR before EoD September 2nd.
