### ISSUE TITLE
Steering Committee Nomination: Cici Huang (@cici37) 

### ISSUE THREAD

**Issue by cici37** [kubernetes/community#6836]
### Describe the issue

Hi Kubernetes Community,

I am self-nominating for the upcoming Steering Committee election.

My involvement with Kubernetes community is crossing multiple areas including sig-cloud provider, sig-apimachinery, release etc. I served as Kubernetes 1.25 release lead recently and would love to contribute on the steering committee.

/committee steering

**Comment by markyjackson-taulia** [comment]
+1 
@cici37 was a great leader on the 1.25 release and would be great in this role.

**Comment by reylejano** [comment]
+1
Employer: SUSE

**Comment by leonardpahlke** [comment]
+1

**Comment by orsenthil** [comment]
+1 
Employer: AWS

**Comment by fedebongio** [comment]
+1
Employer: Google

**Comment by aojea** [comment]
+1
Employer: Red Hat

**Comment by dobsonj** [comment]
+1
Employer: Red Hat

**Comment by jiahuif** [comment]
+1
Employer: Google

**Comment by sudlo** [comment]
+1

**Comment by qedrakmar** [comment]
+1
Employer: Oracle

**Comment by varshaprasad96** [comment]
+1
Employer: Red Hat
I was a part of the K8s release team along with @cici37.

**Comment by seans3** [comment]
+1
Employer: Google

**Comment by elmiko** [comment]
+1
Employer: Red Hat

**Comment by jagosan** [comment]
+1
Employer: Google

**Comment by jasonbraganza** [comment]
+1
@cici37 was my release lead for the v1.25 release. she was warm and empathic. big +1.

**Comment by MadhavJivrajani** [comment]
+1
Employer: VMware

**Comment by palnabarun** [comment]
+1
Employer: VMware

**Comment by vinaykul** [comment]
+1
Employer: Futurewei (Huawei)

**Comment by soltysh** [comment]
+1
Employer: Red Hat

**Comment by RinkiyaKeDad** [comment]
+1 
Employer: Okteto

**Comment by cpanato** [comment]
+1
Employer: Chainguard

**Comment by lavalamp** [comment]
+1
Employer: Google

**Comment by Jefftree** [comment]
+1
Employer: Google

**Comment by benluddy** [comment]
+1
Employer: Red Hat

**Comment by humblec** [comment]
+1
Employer: Red Hat

**Comment by coderanger** [comment]
Per the requirements of the [candidate process](https://github.com/kubernetes/community/tree/41289f0f7e1fdc559c24e09c8e66c1f805fdfd52/elections/steering/2022#candidacy-process), I have verified that Cici Huang has the necessary endorsements to qualify to run for steering committee.

Please prepare a bio for yourself based on the [nomination-template](https://github.com/kubernetes/community/blob/master/elections/steering/2022/nomination-template.md) file in the election directory and submit a PR before EoD September 2nd.

**Comment by leilajal** [comment]
+1
Employer: Google

**Comment by puerco** [comment]
+1 !
Employer: Chainguard

**Comment by cc4i** [comment]
+1
Employer: Google
