### ISSUE TITLE
Steering Committee Nomination: Noah Abrahams (@qedrakmar)

### ISSUE THREAD

**Issue by qedrakmar** [kubernetes/community#6837]
### Describe the issue

Hello Kubernetes community,

I would like to self-nominate for the Kubernetes Steering Committee.

I have been involved with this project since 2016, primarily in a community growth role.  My most visible work has been with SIG Contributor Experience, where I drive the Non-Code Contributors project, as well as some time on the Release Team.  You may have encountered me helping or mentoring all over the project, while I focus on the behind-the-scenes work that doesn’t make a GitHub profile any greener.  

Recognizing the types of work that Steering takes on, I intend to bring to the Steering Committee even more of the culture that’s made this community so successful, and highlight the priorities of People first, Project second, and Company third.

/committee steering

**Comment by markyjackson-taulia** [comment]
+1
@qedrakmar and I met in 2016 and he has been a vital part of the contribex.

**Comment by reylejano** [comment]
+1
Employer: SUSE

**Comment by palnabarun** [comment]
+1
Employer: VMware

**Comment by jasonbraganza** [comment]
+1

**Comment by humblec** [comment]
+1
Employer: Red Hat

**Comment by thecrudge** [comment]
+1

**Comment by coderanger** [comment]
Per the requirements of the [candidate process](https://github.com/kubernetes/community/tree/41289f0f7e1fdc559c24e09c8e66c1f805fdfd52/elections/steering/2022#candidacy-process), I have verified that Noah Abrahams has the necessary endorsements to qualify to run for steering committee.

Please prepare a bio for yourself based on the [nomination-template](https://github.com/kubernetes/community/blob/master/elections/steering/2022/nomination-template.md) file in the election directory and submit a PR before EoD September 2nd.

**Comment by puerco** [comment]
+1
Employer: Chainguard
