### ISSUE TITLE
Steering Committee Nomination: Daniel Smith (@lavalamp)

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/community#6839]
I'd like to nominate myself for the Steering Committee.

I have been working on Kubernetes since before it was open source. I was the top contributor for the first few years of its existence. I specialized on things I felt would enable an ecosystem to form around Kubernetes (I think that has paid off). I initiated and continue to co-run the API Machinery SIG. I would be honored to serve the community in this capacity as well.

/committee steering

**Comment by seans3** [comment]
+1

**Comment by deads2k** [comment]
+1

Employer: Red Hat

**Comment by alculquicondor** [comment]
+1
Employer: Google

**Comment by aojea** [comment]
+1
Employer: Red Hat

**Comment by minzhuogoogle** [comment]
+1

**Comment by tkashem** [comment]
+1

**Comment by kwiesmueller** [comment]
+1
Employer: Google

**Comment by ahg-g** [comment]
+1 
Employer: Google

**Comment by MushuEE** [comment]
+1 
Employer: Google

**Comment by jagosan** [comment]
+1
Employer: Google

**Comment by fedebongio** [comment]
+1
Employer: Google

**Comment by saad-ali** [comment]
+1
Employer: Google

**Comment by pacoxu** [comment]
+1
Employer: DaoCloud

**Comment by MadhavJivrajani** [comment]
+1 

Employer: VMware

**Comment by jqmichael** [comment]
+1

Employer: AWS

**Comment by iamprashant** [comment]
+1

**Comment by 44past4** [comment]
+1
Employer: Google

**Comment by soltysh** [comment]
+1
Employer: Red Hat

**Comment by wojtek-t** [comment]
+1
Employer: Google

**Comment by mm4tt** [comment]
+1 
Employer: Google

**Comment by sjenning** [comment]
+1
Employer: Red Hat

**Comment by cpanato** [comment]
+1
Employer: Chainguard

**Comment by Jefftree** [comment]
+1
Employer: Google

**Comment by tamalsaha** [comment]
:100: 

Employer: AppsCode

**Comment by humblec** [comment]
+1
Employer: Red Hat

**Comment by MrHohn** [comment]
+1
Employer: Google

**Comment by Huang-Wei** [comment]
+1
Employer: Apple

**Comment by coderanger** [comment]
Per the requirements of the [candidate process](https://github.com/kubernetes/community/tree/41289f0f7e1fdc559c24e09c8e66c1f805fdfd52/elections/steering/2022#candidacy-process), I have verified that Daniel Smith has the necessary endorsements to qualify to run for steering committee.

Please prepare a bio for yourself based on the [nomination-template](https://github.com/kubernetes/community/blob/master/elections/steering/2022/nomination-template.md) file in the election directory and submit a PR before EoD September 2nd.
