### ISSUE TITLE
Cluster autoscaler improvements for AI workloads

### ISSUE THREAD

**Issue by asm582** [kubernetes/community#6840]
### Describe the issue

We see that the current cluster autoscaler (CA) reacts to pending pods, this may not work well for AI/HPC workloads, we outline the scenarios below:

- CA reacts to pending pods, When a large number of pods are being co-scheduled it can wait tens of minutes with pending pods before triggering scale-up, stressing the control plane.
- When multiple AI/HPC workloads are submitted to the cluster, none of the jobs may progress even after scale-up by CA due to its inability to understand gang scheduling.
  - Example: user submitted 10 AI/HPC jobs (with 10 * N pods), based on N pending pods, lets's assume  CA scaled to 10 nodes, and worst case only the head nodes of all the jobs got scheduled, such partial jobs will cause no user workloads to make progress.
- CA reactive scaling can hamper cluster scale-up when a user does not have sufficient quota to create pods in a namespace.
- CA performs termination based on traditional compute (i.e. CPU and memory ) utilization threshold which may not work for AI workload(s).
  - AI workload which uses GPU with large GPU memory may cause low CPU and memory utilization on the node which could lead to premature termination.
  - Setting the termination threshold to a very low value will cause CA to not evict any nodes.
- CA terminates nodes one at a time, scaling down a cluster that uses tens or hundreds of nodes will take time.
- Selection of Machineset(s) to scale cluster is random (or complex via expander) and periodically it causes over-provisioning.

Looking for feedback on a better solution to have holistic autoscaling for large AI/HPC workloads

**Comment by elmiko** [comment]
@asm582 and i have talked offline about this issue, i'm very curious about this work. thanks for sharing!

**Comment by mrbobbytables** [comment]
IMO - I would send this to the autoscaling mailing list, this repo is not really for answering general questions.^^;;; It's more of a meta repo for how the project self manages.

**Comment by asm582** [comment]
> IMO - I would send this to the autoscaling mailing list, this repo is not really for answering general questions.^^;;; It's more of a meta repo for how the project self manages.

Thank you, I am new to this sig and believe the above are shortcomings of the current autoscaler and not general questions. I am happing to hop on the mailing list or post in another repository that you can recommend if that is a better way to get a review of the shortcomings.

**Comment by enxebre** [comment]
thanks @asm582, please let's move this here https://github.com/kubernetes/autoscaler/issues

**Comment by asm582** [comment]
Thanks @enxebre. Closing this issue, the issue opened in another repository: https://github.com/kubernetes/autoscaler/issues/5170
