### ISSUE TITLE
slack bots are down

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/community#6841]
### Describe the issue

due to the slack.k8s.io => community inviter redirect, the slack tools were also on slack.k8s.io/foo and are being redirected to the inviter, which means none of our moderation tools work ...

/assign
/priority critical-urgent
/sig contributor-experience

**Comment by BenTheElder** [comment]
slack thread: https://kubernetes.slack.com/archives/CCK68P2Q2/p1661887032869249

**Comment by dims** [comment]
ugh! my bad @BenTheElder

**Comment by BenTheElder** [comment]
OK so slack-infra.k8s.io / slack-infra.kubernetes.io are live, we are just waiting on:
- certificate provisioning
- katharine updating the slack app configs to point to the new URL

then hopefully the bots / moderation tools should be good to go 🤞

**Comment by BenTheElder** [comment]
certs are up, and katharine is updating the configs.

**Comment by BenTheElder** [comment]
most of them are back up, but post-message and moderator-words still need updating, Katharine doesn't have access to those https://kubernetes.slack.com/archives/CCK68P2Q2/p1661900038920049?thread_ts=1661887032.869249&cid=CCK68P2Q2

not sure who does ... (I'm also not a slack admin)

**Comment by jberkus** [comment]
Confirmed that Reporter is working again.

**Comment by dims** [comment]
`slack-moderator-words` bot/app is now working

**Comment by dims** [comment]
`slack-post-message` bot/app is now working

**Comment by jberkus** [comment]
This issue is resolved.

/close
