### ISSUE TITLE
Document joining the Kubernetes org

### ISSUE THREAD

**Issue by sftim** [kubernetes/community#6848]
### Describe the issue

Document how to join the organization in this repo, so that that information gets published into https://k8s.dev/docs/

**Comment by ADITYADAS1999** [comment]
hey [sftim](https://github.com/sftim) can i work on this documentation ? It's seems easy for me 😊

**Comment by sftim** [comment]
No objection from me!

**Comment by mrbobbytables** [comment]
It's documented in the [community membership](https://github.com/kubernetes/community/blob/master/community-membership.md) doc at the root of the repo, would just need hugo metadata header and a some other info added to be published over there

**Comment by ADITYADAS1999** [comment]
> It's documented in the [community membership](https://github.com/kubernetes/community/blob/master/community-membership.md) doc at the root of the repo, would just need hugo metadata header and a some other info added to be published over there


all the Hugo Shortcodes  are present here I thing it is helpful 
https://kubernetes.io/docs/contribute/style/hugo-shortcodes/

**Comment by Debanitrkl** [comment]
/sig contributor-experience
/area developer-guide
@ADITYADAS1999 are you still working on this? or I can put quick PR for this

**Comment by ADITYADAS1999** [comment]
@Debanitrkl  you can feel free to make a PR  , I right now working on another issue

**Comment by Debanitrkl** [comment]
Here's the draft with hugo headers and adequate changes, will make a PR soon after few reviews on this. https://hackmd.io/@XzECIhDGRqCtGVrLiJFzxQ/rkszHbMbi/edit

**Comment by mrbobbytables** [comment]
Please don't include any hugo shortcodes, just the metadata at the top should do it. The page needs to be fully readable in both locations.

**Comment by jberkus** [comment]
@Debanitrkl please go ahead and create the PR.

**Comment by kunreddyshyam3** [comment]
hey i am new here, could you assign the task so i can make pr

**Comment by aojea** [comment]
You don't have to be assigned to submit a PR
