### ISSUE TITLE
Broken link need to fix

### ISSUE THREAD

**Issue by amolmote** [kubernetes/community#6868]
**This is a Bug Report**

**Problem:**
visit this page [pull-requests](https://www.kubernetes.dev/docs/guide/pull-requests/)
when we click on this `Kubernetes Enhancement Proposal process` it returns 404 not found page,so this needs to be fix.

**Proposed Solution:**
correct link of md file require to provide.

**Page to Update:**
https://www.kubernetes.dev/docs/guide/pull-requests/

/sig docs
/assign
/kind bug

**Comment by souravsk** [comment]
The link is working fine.Can you recheck it.

**Comment by amolmote** [comment]
This link is working fine which I provided in issue but link of KEP is not working properly

**Comment by amolmote** [comment]
I have checked it multiple times then I have raised this issue

**Comment by souravsk** [comment]
It's not working for the desktop Brower previously when I checked it was working it opened in the GitHub mobile application.

**Comment by souravsk** [comment]
i'm working on this

**Comment by amolmote** [comment]
I have assigned it to myself already

**Comment by souravsk** [comment]
okay let me if need any help

**Comment by amolmote** [comment]
yes sure I am waiting for the sig, once it is approved by any member i will the pr.

**Comment by souravsk** [comment]
can you give me the file location of page

**Comment by dims** [comment]
`https://github.com/kubernetes/enhancements/blob/master/keps/0001-kubernetes-enhancement-proposal-process.md` should be replaced with 
`https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/0000-kep-process/README.md`

**Comment by amolmote** [comment]
yes will do this changes thank you @dims
