### ISSUE TITLE
Create my own plugin for scheduler

### ISSUE THREAD

**Issue by Daghashk** [kubernetes/community#6882]
### Describe the issue

I would like to write my own plugin for example, taking the latency of nodes into consideration when score the nodes?
if there are any document that can guide me as fresh learner, please help me.
/sig Scheduling

**Comment by jberkus** [comment]
Howdy @Daghashk!  This issue page is not going to help you to learn how to write Scheduler plugins.  I suggest instead joining [Kubernetes Slack](https://slack.k8s.io) and posting your question in the `#sig-scheduling` channel.
