### ISSUE TITLE
Development for Building Kubernetes is inaccurate

### ISSUE THREAD

**Issue by vitorfhc** [kubernetes/community#6888]
### Describe the issue

The [documentation suggests](https://github.com/kubernetes/community/blob/002ec4b213ba3b00bc456dc8e2eaa1643de4bff0/contributors/devel/development.md?plain=1#L360-L364) using `GOGCFLAGS="-N -l"`.

In the Makefile we have [another way to set debug mode](https://github.com/kubernetes/kubernetes/blob/299e65cdc5799b982b6af69858c14bfe41463540/build/root/Makefile#L78-L79), which is using `DBG=1`.

If we check the code for `hack/lib/golang.sh`([link](https://github.com/kubernetes/kubernetes/blob/299e65cdc5799b982b6af69858c14bfe41463540/hack/lib/golang.sh#L840-L845)), it sets `-N -l` for us when `DBG=1`. Otherwise, it sets `goldflags="${goldflags} -s -w"`.

Having `goldflags="${goldflags} -s -w"` and `gogcflags="${GOGCFLAGS:-} all=-N -l"` is going to make a succesful build, but when trying to use [Delve](https://github.com/go-delve/delve) for debugging we get this error: `could not launch process: could not open debug info - debuggee must not be built with 'go run' or -ldflags='-s -w', which strip debug info`.

We should change this documentation to suggest using `DBG` instead.

**Comment by sreekaransrinath** [comment]
```diff
diff --git a/contributors/devel/development.md b/contributors/devel/development.md
index 527b5d77..00ebe0a3 100644
--- a/contributors/devel/development.md
+++ b/contributors/devel/development.md
@@ -357,10 +357,10 @@ The Kubernetes build system defaults to limiting the number of reported Go compi
 make WHAT="cmd/kubectl" GOGCFLAGS="-e"
 
-If you need to use debugging inspection tools on your compiled Kubernetes executables, add `-N -l` to `GOGCFLAGS`. For example:
+If you need to use debugging inspection tools on your compiled Kubernetes executables, set DBG=1. For example:
 
-make WHAT="cmd/kubectl" GOGCFLAGS="-N -l"
+make WHAT="cmd/kubectl" DBG=1
 
 To cross-compile Kubernetes for all platforms, run the following  #command:
```

Hey, 

@mrbobbytables - do you think this doc change makes sense?
@Pro-Coder04 Are you working on this or do you mind if I submit a quick PR?

**Comment by Pro-Coder04** [comment]
@sreekaransrinath you can go ahead with your PR

**Comment by vitorfhc** [comment]
Any updates on this merge?
