### ISSUE TITLE
KubeCon NA 2022 - K8s Meet and Greet volunteers

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#6899]
### Describe the issue

The meet and greet will take place Friday October 28th @ 12:30pm ET

If you would like to volunteer to represent your SIG/WG - please post below 👍 

/area contributor-summit
/sig contributor-experience

**Comment by natalisucks** [comment]
Myself and @divya-mohan0209 volunteer to represent SIG Docs 👋 🐱

**Comment by thockin** [comment]
Interested for sig-net and/or sig-arch

**Comment by xing-yang** [comment]
I'll be there for SIG-Storage.

**Comment by MadhavJivrajani** [comment]
I can help with ContribEx and/or API Machinery :)

**Comment by helayoty** [comment]
I can help with SIG-Apps, Virtual-Kubelet, and a little bit about SIG-Scheduling.

**Comment by jpbetz** [comment]
I can be there for SIG api-machinery

**Comment by cailynse** [comment]
I'd like to volunteer for SIG Security!

**Comment by alculquicondor** [comment]
Me for SIG-Scheduling, SIG-Apps and WG-Batch

**Comment by dims** [comment]
Me for SIG-Arch

**Comment by soltysh** [comment]
I'll do that for SIG-Apps and SIG-CLI

**Comment by dashpole** [comment]
I'll be there for SIG instrumentation

**Comment by JimBugwadia** [comment]
I would like to volunteer for WG-Policy and WG-Multitenancy

**Comment by charleszheng44** [comment]
I'd like to volunteer for wg-multitenancy and sig cluster-api.

**Comment by elmiko** [comment]
i'm happy to volunteer for sig cloud-provider and/or sig autoscaling

**Comment by KnVerey** [comment]
I volunteer for SIG CLI

**Comment by dcbw** [comment]
I volunteer for SIG-Net

**Comment by robscott** [comment]
I can be around for SIG Net and Gateway API

**Comment by aojea** [comment]
I can be around for SIG Net and SIG Testing

**Comment by cpanato** [comment]
I volunteer for SIG-Release

**Comment by jrsapi** [comment]
I volunteer for SIG-Release.

**Comment by varshaprasad96** [comment]
I can be around for SIG-Apimachinery (for Kubebuilder/controller-runtime/controller-tools) projects.

**Comment by BenTheElder** [comment]
I volunteer for Testing and Infra

**Comment by puerco** [comment]
I'll be there for SIG Release :tada:

**Comment by thockin** [comment]
Do we have a room assignment for this?

**Comment by mrbobbytables** [comment]
Room 411ABC 12:30-1:30, we do have hte room till 2:30 if folks want to go longer.

**Comment by marosset** [comment]
I volunteer SIG Windows

**Comment by dgrisonnet** [comment]
I'll be there for SIG Instrumentation

**Comment by mrbobbytables** [comment]
Here is the sched url for the meet & greet session: https://sched.co/1CZy3

**Comment by krmayankk** [comment]
I will try to be there for sig-apps, but potentially have a talk on 28th at 4:00 PM. Not sure what is the time for this ?

**Comment by pohly** [comment]
I can help @aojea with SIG testing and @dgrisonnet  / @dashpole for SIG instrumentation - assuming that I can travel (COVID...).

**Comment by enj** [comment]
I will be there for SIG Auth but I might be late as I have a talk right before this slot.

**Comment by jberkus** [comment]
I will be there for SIG-Beard.

**Comment by ritazh** [comment]
I'll be there for SIG Auth after the sig auth talk. Looking forward to meeting everyone!

**Comment by bobbypage** [comment]
I can help with SIG-Node, looking forward to meeting everyone!

**Comment by benzaidfoued** [comment]
I'd like to volunteer for wg-multitenancy and sig cluster-api

**Comment by mrbobbytables** [comment]
The event was last week^^;; going to go ahead and close this out. Thanks everyone!

/close
