### ISSUE TITLE
Link not found error

### ISSUE THREAD

**Issue by ADITYADAS1999** [kubernetes/community#6901]
### Describe the issue

At contact section github team links are not found

https://github.com/kubernetes/community/tree/master/sig-instrumentation

![8888](https://user-images.githubusercontent.com/58718316/193031515-3327ebf4-2103-454e-af23-72d89ae1c412.PNG)

**Comment by sreekaransrinath** [comment]
Hey @ADITYADAS1999, team pages can be viewed only by org members.

<img width="772" alt="image" src="https://user-images.githubusercontent.com/50989977/193377972-81fb8174-3a75-480f-8f55-86ec247236cf.png">

https://docs.github.com/en/organizations/organizing-members-into-teams/about-teams#team-visibility

**Comment by ADITYADAS1999** [comment]
Thanks for informing @sreekaransrinath
