### ISSUE TITLE
API Conventions: Document use of finalizers

### ISSUE THREAD

**Issue by pmorie** [kubernetes/community#691]
Discovered in https://github.com/kubernetes-incubator/service-catalog/pull/894; there is no document that shows correct use of finalizers in the API.  While not purely an API convention, this should be documented somewhere and the API conventions document seems like a reasonable place to do so.

**Comment by mrbobbytables** [comment]
Is this still relevant? It's been open and frozen for some time now.
I'm going to mark it as rotten for now, if it should be left open please update or re-freeze it 👍  

/remove-lifecycle frozen
/lifecycle rotten
