### ISSUE TITLE
Update SIG Testing chairs and tech leads

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#6913]
### Describe the issue

We've reached lazy consensus on some chair and tech lead additions
- Add @michelle192837 as chair ([mailing list thread](https://groups.google.com/g/kubernetes-sig-testing/c/1p4_YnsKhsk))
- Add @aojea and @pohly as tech leads ([mailing list thread](https://groups.google.com/g/kubernetes-sig-testing/c/Ey7oQdJkEgI))

This issue is to track the sundry PRs and onboarding tasks that need to happen:
- [x] Update sigs.yaml in kubernetes/community: https://github.com/kubernetes/community/pull/6914
- [ ] Update OWNERS_ALIASES
  - [x] kubernetes/enhancements: https://github.com/kubernetes/enhancements/pull/3607
  - [x] kubernetes/k8s.io: https://github.com/kubernetes/k8s.io/pull/4330
  - [x] kubernetes/org: https://github.com/kubernetes/org/pull/3757
  - [x] kubernetes/test-infra: https://github.com/kubernetes/test-infra/pull/27720
- [x] Update mailing list memberships: https://github.com/kubernetes/k8s.io/pull/4331
- [x] Update sig-testing-leads GitHub team: https://github.com/kubernetes/org/pull/3820
- [ ] Update 1password memberships 

Anything else?

/sig testing

**Comment by MadhavJivrajani** [comment]
/remove-lifecycle stale
I see that updating 1password memberships is remaining. @spiffxp @BenTheElder do you know if this was done and this can be closed out?

**Comment by BenTheElder** [comment]
yes, sorry abotut that
/close
