### ISSUE TITLE
SURVEY REQUEST: kubectl localization

### ISSUE THREAD

**Issue by brianpursley** [kubernetes/community#6915]
### Group Requesting

SIG-CLI

### Title of Survey

Kubectl Localization Survey

### Goal of Survey

Kubectl's language translations are incomplete, with some languages have less than 10% of the output translated.  The untranslated text remains in English, resulting in the output having a mix of two languages.

We think this experience is probably not good enough for those who use kubectl in one of the supported non-English languages, but we want to hear from people who actually use it to better understand whether we should attempt to improve translation coverage, or potentially remove it (entirely or specific languages), if it is so incomplete that it is not helpful at all.

I'm open to any suggestions or improvements to the survey, so please feel free to provide feedback.  I am also interested in whether a community survey is the right place for something like this and whether we would be able to reach people whose primary language is not English, as they are the people who use the translations provided in kubectl.

### Target Audience

kubectl users whose primary language is not English

### Results Recipients

Brian Pursley, Katrina Verey, Maciej Szulik, Sean Sullivan, Eddie Zaneski

### Date Survey Starts

TBD

### Date Survey Ends

TBD

### Publicity Help Wanted?

Yes

### Data Analysis Wanted?

Yes

### Link to Draft Questions

https://hackmd.io/r3lxGEcSTO608K6E2P380w

**Comment by henvic** [comment]
Please consider adding `Not Applicable / prefer to use English` to the question "How satisfied are you with kubectl’s support for your language?".

**Comment by jberkus** [comment]
So this survey has one critical issue: we want to reach audiences that don't speak English as their primary language, which suggests that we need the survey itself to be available in all eight languages.  We do not have any specific infrastructure for translating surveys, and I'm not entirely certain what SurveyMonkey's support of multilingual surveys is.

I can investigate the technical support, but SIG-CLI (and possibly SIG-Docs) is going to need to see if we have community translators who can translate the survey.

**Comment by jberkus** [comment]
Surveymonkey supports multilingual surveys, so we just need the translations.

**Comment by jberkus** [comment]
Our SurveyMonkey account does **_not_** support multilingual surveys.  It's unlikely that the CNCF wants to upgrade, so let's discuss this on Slack.

**Comment by jberkus** [comment]
Ping!  Has SIG-CLI had a chance to discuss this at all?

**Comment by jberkus** [comment]
Closing this; we can reopen if y'all come up with some ideas for how we're going to reach our target audience.  I'm available by slack if you want to brainstorm.

/close
