### ISSUE TITLE
I’d like to help maintain external-dns

### ISSUE THREAD

**Issue by sepulworld** [kubernetes/community#6928]
### Describe the issue

Hi, looks like the external-dns project is in need of maintainers. I’m familiar with the code base and would like to help maintain the aws-sd provider to start. Could I be added to a codeowners file for this portion of the project? Please consider me for help as I’d like to see this project succeed.

**Comment by dims** [comment]
@sepulworld `external-dns` comes under https://github.com/kubernetes/community/tree/master/sig-network#subprojects so you should probably go talk to them (drop an email on the sig-network mailing list and follow up in one of their meetings).

**Comment by sepulworld** [comment]
Thanks @dims!! Can I switch this issue/request over to their sig? Instead of using email?

**Comment by mrbobbytables** [comment]
FWIW - I'd still follow up with the mailing list / slack / meeting. Requests like this aren't often seen by other groups here in k/community.
