### ISSUE TITLE
REQUEST: New Slack channel #kwok

### ISSUE THREAD

**Issue by wzshiming** [kubernetes/community#6967]
### GitHub Username

@wzshiming

### Slack Username

@wzshiming

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

Channel

### Name of Requested Resource

kwok

### Description of Request

Need a slack channel for discussion around the https://github.com/kubernetes-sigs/kwok.

**Comment by ibilalkayy** [comment]
Hey @wzshiming the request should have to come from the project maintainer itself, not a third party. As a maintainer, you would generally have to make the PR. You'll have to file a PR adding your channel to the config file. Please see https://github.com/kubernetes/community/blob/master/communication/slack-guidelines.md#requesting-a-channel for details. Thanks!
