### ISSUE TITLE
REQUEST: New Private Slack channel #steering-gb-rep-private

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/community#6975]
### GitHub Username

@justaugustus

### Slack Username

@justaugustus

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

channel

### Name of Requested Resource

#steering-gb-rep-private

### Description of Request

At times, it is necessary for the @kubernetes/steering-committee to discuss matters privately with our CNCF Governing Board representative.

With our GB rep (@parispittman) stepping down from the Steering Committee, we need a new private channel to continue these communications.

cc: @kubernetes/community-admins

**Comment by jberkus** [comment]
+1

BUT can Steering please list the private channels y'all have?  Not necessarily to me, but somewhere in the Steering docs?  Since there's necessarily no oversight once created, it's helpful for the community to know what exists.

**Comment by tpepper** [comment]
> BUT can Steering please list the private channels y'all have? Not necessarily to me, but somewhere in the Steering docs? Since there's necessarily no oversight once created, it's helpful for the community to know what exists.

That list plus clarification of what is suggested for “may be private” and “must be public” would be beneficial.

**Comment by justaugustus** [comment]
> BUT can Steering please list the private channels y'all have? Not necessarily to me, but somewhere in the Steering docs? Since there's necessarily no oversight once created, it's helpful for the community to know what exists.

Filed a tracking issue here: https://github.com/kubernetes/steering/issues/262

For reference:

- Email: steering-private@
- Slack:
  - #steering-private (committee-only discussion)
  - [To be created pending https://github.com/kubernetes/community/issues/6975] #steering-gb-rep-private (Steering + CNCF Governing Board representative for Kubernetes)

**Comment by mrbobbytables** [comment]
channel has been created 👍

**Comment by jberkus** [comment]
Closing this, since we have the other issue for listing the channels.

/close

**Comment by BenTheElder** [comment]
Closing the loop: https://github.com/kubernetes/steering#private-communication-channels
