### ISSUE TITLE
License Scan report

### ISSUE THREAD

**Issue by dims** [kubernetes/community#6992]
```
Project: cncf
Subproject: kubernetes
Snapshot on: 2022-10-13
```

Please see url:
https://lfscanning.org/reports/cncf/kubernetes-2022-10-13-19a6e7e7-4f53-4c58-9dcb-6ab28ebf194d.html

Report was forwarded by @mrbobbytables to sig-arch mailing list:
https://groups.google.com/g/kubernetes-sig-architecture/c/dsMVIdPPUK8/m/u3ZjJtcnBwAJ

**Comment by dims** [comment]
for our k/k based releases, just these are applicable

```
kubernetes-2022-10-13.zip/kubernetes/vendor/[github.com/mindprince/gonvml/NVML_NOTICE](http://github.com/mindprince/gonvml/NVML_NOTICE)
kubernetes-2022-10-13.zip/kubernetes/vendor/[github.com/mindprince/gonvml/nvml.h](http://github.com/mindprince/gonvml/nvml.h)
kubernetes-2022-10-13.zip/kubernetes/vendor/[github.com/cilium/ebpf/syscalls.go](http://github.com/cilium/ebpf/syscalls.go)
```

the syscalls.go is spurious, there's a string check "GPL" which triggers the warning:
https://github.com/cilium/ebpf/blob/master/syscalls.go#L239

the first two, we are just vendoring in, and the warning says "This file contains a license notice originating from a non-OSS SDK from NVIDIA. It permits use of the software, but does not appear to permit modification, redistribution, etc. " so we can just disregard this as well.

**Comment by dims** [comment]
opened a bug report for spurious report in a cilium file:
https://github.com/lfscanning/scaffold/issues/47

**Comment by liggitt** [comment]
> the first two, we are just vendoring in, and the warning says "This file contains a license notice originating from a non-OSS SDK from NVIDIA. It permits use of the software, but does not appear to permit modification, redistribution, etc. " so we can just disregard this as well.

how can we file a bug to fix this false positive?

**Comment by dims** [comment]
> 

Done! https://github.com/lfscanning/scaffold/issues/48

**Comment by mrbobbytables** [comment]
The heketi reference looks valid
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/vendor/github.com/heketi/heketi/LICENSE

> Heketi code is released under various licenses:
> The REST API client code (in go and python) is released
> under a dual license of Apache 2.0 or LGPLv3+.
>
> The other parts of heketi (server, cli, tests, ...) are released
> under a dual license of LGPLv3+ or GPLv2.

**Comment by liggitt** [comment]
I don't think that's an *actual* issue, since the bits that are used are the go client/API bits which are licensed under Apache 2.0. However, since k/k dropped heketi during 1.26 dev cycle, updating to 1.26 rc.0 libraries lets that repo drop heketi entirely - opened https://github.com/kubernetes/autoscaler/pull/5336 to do that

**Comment by liggitt** [comment]
cadvisor has dropped nvml in https://github.com/google/cadvisor/pull/3206, will be in next tag, WIP k/k PR in https://github.com/kubernetes/kubernetes/pull/114254 to pick that up

**Comment by gjtempleton** [comment]
Just to be sure we're covering everything we need to from the Autoscaling side, from my understanding the only requirement on our part is cutting a 1.26.0 release:

1. gonvml - Affects CA and VPA. We're pulling this in as part of vendoring k/k, and we're not making modifications, as per dims' [comment](https://github.com/kubernetes/community/issues/6992#issuecomment-1331004437) so **no action required on our part**. Will pull in the dropping of this once k/k is updated anyway.

1. Cilium ebpf syscalls - Affects CA and VPA. False alarm based on dims' comment, **no action required on our part**.

1.  Heketi - Affects CA
    * Thanks to @liggitt for the PR to autoscaler to drop this, that's now merged, we should be cutting a new release for 1.26.0 soon. **Assuming we don't need to backport this to prior release branches?**

1. hashicorp/golang-lru - Already has an [exception approved](https://github.com/cncf/foundation/blob/ae2f009a1295646a9c9b01561e86358495758160/license-exceptions/cncf-exceptions-2019-11-01.json#L28), **no action required**.
