### ISSUE TITLE
Request to create a kubernetes-sigs/windows-service-proxy

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/community#7001]
### Describe the issue

Per sig-windows meeting last wk, we'd like to make a windows-service-proxy/ that maintaines its own lifecycle for the windows kube-proxy implementation, as part of a broader effort to have custom developer tooling, powershell script installers , deliverables, and faster patching.

Existing out of tree impl lives here for now  https://github.com/kubernetes-sigs/kpng/tree/master/backends/windows/kernelspace 

cc @marosset @jsturtevant @luthermonson @knabben @nikhita @palnabarun

**Comment by palnabarun** [comment]
IIUC, this is a repository creation request?

**Comment by knabben** [comment]
+1

**Comment by palnabarun** [comment]
Can you please file a request through [k/org](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-repo&template=repo-create.yml&title=REQUEST%3A+%3CCreate+or+Migrate%3E+%3Cgithub+repo%3E) ? The issue template has a few more questions to be answered.

**Comment by marosset** [comment]
I'll do that

/close
