### ISSUE TITLE
KCSEU 2023 Summit Team Staffing

### ISSUE THREAD

**Issue by qedrakmar** [kubernetes/community#7002]
### Describe the issue

The 2023 EU Contributor Summit in Amsterdam will need staffing for its roles and shadows.

Leads will be @puja108 and @qedrakmar, with a lead shadow of @pnbrown.  For this summit we will need leads for registration, comms, content, the social event, and day-of operations.  We will also need shadows that could potentially take on leading those roles in the future.  Roles and shadows will be listed below when they are filled out:

- [Registration](https://github.com/kubernetes/community/blob/master/events/events-team/registration/README.md)
  - Lead: @tokt 
  - Shadows: @Atharva-Shinde , @kendallnelson , @Priyankasaggu11929 , @natalisucks
  - Emeritus: @ameukam
- [Content](https://github.com/kubernetes/community/blob/master/events/events-team/content/README.md)
  - Lead: @detiber 
  - Shadows: @palnabarun , @jrsapi , @cailynse , @Rishit-dagli , @meghanajangi
  - Helpers: @harshitasao , @RishabhKodes , @akshat5302 , @kishorerj , @VamshiReddy02
- [Comms](https://github.com/kubernetes/community/blob/master/events/events-team/marketing/README.md)
  - Lead: @chris-short 
  - Shadows: @NitishKumar06 , @VibhorChinda , @gracenng , @shivanshu1333
  - Emeritus: @kaslin 
- Social Event
  - Lead: @salaxander 
  - Shadows: @stealthybox , @freddie400
- Day-of Operations
  - Lead: @fsmunoz 
  - Shadows: @chris-short , @ameukam , @MadhavJivrajani , @rgunaseknokia , @cpanato , @rayandas
- SIG Meet & Greet 
  - Lead: @KimMcMahon 
  - Shadows: @nimbinatus
  - Emeritus: @jberkus

- - - -
(Umbrella issue not created yet)
/assign @qedrakmar @puja108 @pnbrown 
/sig contributor-experience
/area contributor-summit
/area eu-summit

**Comment by detiber** [comment]
Happy to help out with Content

**Comment by mrbobbytables** [comment]
Happy to serve as emeritus :) if theres a specific role that can't be filled for whatever reason, I can fill.

**Comment by Rishit-dagli** [comment]
I'd love to shadow for Content

**Comment by tokt** [comment]
I'll (probably) skip the EU event, but happy to help in any role.

**Comment by gracenng** [comment]
Would love to shadow comms :)

**Comment by ameukam** [comment]
Happy to be shadow for operations. :)

**Comment by shivanshu1333** [comment]
I'd love to shadow for Social Event!!

**Comment by SubhasmitaSw** [comment]
I'd be more than happy to shadow for commns 🙂

**Comment by sachinkumarsingh092** [comment]
Shadow for anything.

**Comment by VibhorChinda** [comment]
Happy to shadow for comms :))
But happy to help in any role.

**Comment by AvineshTripathi** [comment]
Happy to help with reg this time. If needed i can shadow for other roles as well based on req

**Comment by RishabhKodes** [comment]
I can help out being the shadow for content. 👋🏼 
(open to other roles as well)

**Comment by harshitasao** [comment]
I'd love to shadow for content!

**Comment by meghanajangi** [comment]
I would like to shadow for Social Event or Content!

**Comment by MadhavJivrajani** [comment]
I would love to help out with Day-of operations ❤️

**Comment by natalisucks** [comment]
I'd love the opportunity to shadow for registrations ✌️

**Comment by chris-short** [comment]
I will be on ground day of so you can pencil me in as a shadow for Day of Ops too.

**Comment by rajaskakodkar** [comment]
I'd love to help out with registration

**Comment by lauralorenz** [comment]
I can shadow for anything

**Comment by cailynse** [comment]
Hello! I'm up for shadowing where ever needed!

**Comment by Atharva-Shinde** [comment]
happy to help with registrations :)

**Comment by chris-short** [comment]
I'll take all three Comms shadows (@gracenng, **@SubhasmitaSw** and **@VibhorChinda**), the more minds the better when it comes to words to humans (also redundancy because life does indeed happen). I'll start a Slack with us to talk about how to work with timezones and such.

cc @kaslin (I wonder if Comms should have a GH handle)

**Comment by kaslin** [comment]
I want to help out too! I'll help out with Comms but also whatevah. Especially since Chris is taking point on Comms. Maybe I could shadow lead? I know you've already got one @qedrakmar but interested, if it makes sense!

**Comment by freddie400** [comment]
Hi There, I am up for shadowing for Social events or anything else too.

**Comment by palnabarun** [comment]
Happy to shadow with the content team!

**Comment by rayandas** [comment]
I'd like to help out with registrations as a shadow.

**Comment by rgunaseknokia** [comment]
I would love to shadow for anything! be it social events, contents, registrations, information desk, etc.,

**Comment by stealthybox** [comment]
I would be happy to shadow for the Social Event.
I can help in other areas if needed.

**Comment by stealthybox** [comment]
This is roughly what sign-ups look like right now:

Leads:  @puja108 @qedrakmar
Lead Shadow: @pnbrown

Registration
Lead: 
Shadows: @Priyankasaggu11929 @natalisucks @rajaskakodkar @Atharva-Shinde @rayandas

Content
Lead: @detiber
Shadows: @rishit-dagli @jrsapi @RishabhKodes @HarshitaSao @cailynse @palnabarun

Comms
Lead: @chris-short
Shadows: @gracenng @SubhasmitaSw @VibhorChinda @kaslin @shivanshu1333

Social Event
Lead: 
Shadows: @meghanajangi @freddie400

Day-of Operations
Lead: 
Shadows: @chris-short @ameukam @MadhavJivrajani


Anything:
Shadows: @lauralorenz @rgunaseknokia

Emeritus: @mrbobbytables @tokt

**Comment by rgunaseknokia** [comment]
I can shadow for Day of Operations!!

**Comment by NitishKumar06** [comment]
I'd love to shadow for the Comms.

**Comment by SD-13** [comment]
You can count on me too for shadow comms.

**Comment by fsmunoz** [comment]
I'll be in Amsterdam, I'm happy to participate in any capacity required. I've never participated in previous organising teams, but that aside I can step up if useful.

**Comment by kishorerj** [comment]
You can count me as shadow for content.. However I will not be able to attend the event in person

**Comment by salaxander** [comment]
happy to take @stealthybox as a shadow for the social! I can potentially take more too, with the understanding that the workload for this role is actually quite low :)

**Comment by rgunaseknokia** [comment]
i would love to shadow for the social as well! please count me in!

**Comment by akshat5302** [comment]
I would love to be in social event,content or anything else based on requirement

**Comment by detiber** [comment]
Happy to take on @palnabarun @meghanajangi @harshitasao @RishabhKodes @jrsapi @Rishit-dagli @akshat5302 @kishorerj and @cailynse as shadows for content

**Comment by cpanato** [comment]
would like to help as shadow for Operations

**Comment by VamshiReddy02** [comment]
I'd love to shadow for content!

**Comment by nimbinatus** [comment]
I'm happy to help out where I can if there's still space to help. Just got confirmation on attendance :)

**Comment by detiber** [comment]
I'm still working on finalizing the content shadows for the event.

So far I have confirmation in slack from  from @palnabarun @meghanajangi @harshitasao @RishabhKodes @jrsapi @cailynse and @Rishit-dagli

I have what I'm taking as emoji confirmation on this issue from @akshat5302, please confirm with me via Slack or with a written comment here

I'm still waiting on confirmation from @kishorerj, please confirm with me via Slack or with a written comment here

@VamshiReddy02 happy to have you as a shadow for content, please confirm with me via Slack or with a written comment here.

**Comment by VamshiReddy02** [comment]
Hey @detiber   I would love to be in shadow for content, already messaged you in slack.

**Comment by rgunaseknokia** [comment]
Hey @detiber! I would love to pickup as a Shadow for Content! Can you please count me in!?

**Comment by kendallnelson** [comment]
I would be happy to shadow you @tokt if you wanted help :)

**Comment by sandipanpanda** [comment]
Hi @chris-short, if it's not too late, I would love to shadow Comms.

**Comment by fsmunoz** [comment]
Hello,

I think the following is the updated list of everyone that volunteered for Operations, which I will gladly take in as shadows:

- @chris-short 
- @ameukam 
- @opMoperadhavJivrajani 
- @rgunaseknokia 
- @cpanato 

I think everyone confirmed it in their comments, but just in case I've missed it: shadowing in Ops requires being on-site for the event.

**Comment by salaxander** [comment]
Final shadow list for social event is @stealthybox and @freddie400 :)

**Comment by rayandas** [comment]
Hello @fsmunoz, earlier I wanted to help with Registrations but @tokt suggested, as I will be there in-person, I should consider helping with Day-of Operations. Happy to help if you’re still taking shadows for Day-of Operations.

**Comment by chris-short** [comment]
Final shadow list for Comms is @NitishKumar06, @VibhorChinda, @gracenng, and @shivanshu1333 (with the occassional help from @kaslin).

**Comment by fsmunoz** [comment]
@rayandas I am indeed, happy to have you in the team!

**Comment by tokt** [comment]
Confirming shadows for registration: @Atharva-Shinde @kendallnelson @Priyankasaggu11929 @natalisucks 
Emeritus shadow: @ameukam

**Comment by rajankumary2k** [comment]
Hi @salaxander -- I am Rajan and working as a Kubernetes administrator. I would like to volunteer as a social event shadow.

**Comment by qedrakmar** [comment]
I believe at this point we have plenty of volunteers, and the Leads will be selecting from among the existing raised hands.  Thank you all for your eagerness to help out!

**Comment by freddie400** [comment]
> Final shadow list for social event is @stealthybox and @freddie400 :)

Hi there @salaxander, looking forward to it. Cheers !

**Comment by freddie400** [comment]
Hi @salaxander, do `social events` have a group on slack or somewhere else?

**Comment by detiber** [comment]
@qedrakmar Final Content Team:

Shadows:
- @palnabarun 
- @jrsapi 
- @cailynse 
- @Rishit-dagli 
- @meghanajangi 
Helpers:
- @harshitasao 
- @RishabhKodes 
- @akshat5302 
- @kishorerj 
- @VamshiReddy02

**Comment by qedrakmar** [comment]
Closing this issue, as the event is now complete.

/close
