### ISSUE TITLE
Requirements for SIG API Machinery reviewers, approvers, and TLs

### ISSUE THREAD

**Issue by vincepri** [kubernetes/community#7006]
### Describe the issue

We've had some offline discussions in SIG API Machinery back in June on understanding what's needed to become a reviewer/approver and ultimately Tech Lead within this group.

This issue is to track that effort and discuss what should be in the process and ladder, the outcome of this issue should be in the form of a PR to this SIG's readme or charter documents.

**Comment by dims** [comment]
cc @fedebongio as i believe he may have already started?

some inspiration can be the one from sig-node https://github.com/kubernetes/community/blob/master/sig-node/sig-node-contributor-ladder.md

**Comment by ibilalkayy** [comment]
Hey @vincepri I don't what you want to achieve. It's my first time contributing to open source and I just want to help. Can you please guide me? Thank you!
