### ISSUE TITLE
REQUEST: New Slack channel #k8s-image-swapper

### ISSUE THREAD

**Issue by estahn** [kubernetes/community#7007]
### GitHub Username

@estahn

### Slack Username

@estahn

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

channel

### Name of Requested Resource

#k8s-image-swapper

### Description of Request

Similar to other tools to help and support the community using https://github.com/estahn/k8s-image-swapper

**Comment by ibilalkayy** [comment]
Hey @estahn, this is my first time contributing to open source. Do you want a contributor to create a new slack channel for your k8s-image-swapper project? What kind of request is this? I just want to help. Thank you!

**Comment by estahn** [comment]
@ibilalkayy 

> Do you want a contributor to create a new slack channel for your k8s-image-swapper project?

Correct.

**Comment by ibilalkayy** [comment]
@estahn Let me create it for you. Will you assign me this task?

**Comment by estahn** [comment]
@ibilalkayy Sure, if you have permission in Slack to create channels. How do I assign the task to you?

**Comment by ibilalkayy** [comment]
Here is the blog that you should read. https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users

**Comment by estahn** [comment]
@ibilalkayy 

> Here is the [blog](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users) that you should read. It will help to assign an issue.

Thanks, I do know how to use GitHub. I do not have permission in GitHub to assign issues in this repository. Some repositories (e.g. `kubernetes/kubernetes` have bot-commands (e.g. `/assign @...`). Thus my question.

**Comment by coderanger** [comment]
@estahn You'll have to file a PR adding your channel to the config file. Please see https://github.com/kubernetes/community/blob/master/communication/slack-guidelines.md#requesting-a-channel for details. Thanks!

/close
