### ISSUE TITLE
pull request docs should discourage giant multi-SIG PRs

### ISSUE THREAD

**Issue by danwinship** [kubernetes/community#7008]
### Describe the issue

New contributors often try to help kubernetes by fixing some minor problem through the entire k/k tree all at once. Eg, using a new function from the latest golang release, replacing a deprecated function with its replacement, fixing a common spelling error in comments, applying the results of some linter or security scanner, etc.

These PRs tend to get ignored for long periods and eventually auto-closed because (a) no SIG considers the PR to be their own, and (b) they require either 17 approvers or a single top-level approver to get merged (and none of the top-level approvers has time to deal with this sort of PR).

(eg, https://github.com/kubernetes/kubernetes/pull/111654/files is an example I just came across.)

So `/contributors/guide/pull-requests.md` should point this out as something not to do; instead, break the PR up into multiple PRs divided by SIG. (Which, it probably needs to explain how to figure out by reading OWNERS files.)

**Comment by ibilalkayy** [comment]
> So `/contributors/guide/pull-requests.md` should point this out as something not to do; instead, break the PR up into multiple PRs divided by SIG. (Which, it probably needs to explain how to figure out by reading OWNERS files.)

Hey, @danwinship I didn't understand this last message and what you want to achieve. It's my first time contributing and I just want to help. Thank you!

**Comment by danwinship** [comment]
I'm not sure if this is a good first-time-issue...

I meant, we should encourage people to break up large PRs into smaller chunks where each chunk only touches code owned by a single SIG, so that it can be approved by the approvers for just that SIG. But doing that requires you to figure out which modules are owned by which SIG, which requires looking at the OWNERS files, and the doc will probably have to explain how to do that.

**Comment by Sajiyah-Salat** [comment]
Hello I understand this issue and faced the same things while contributing. we beginners have to spend hours to fix a small bug as it's new for us and then reviewers are not ready or busy to suggest some changes. We know that this is small issue but its the starting point for us. hence I would like to add some lines in readme.md.
