### ISSUE TITLE
sig doc generator should list the kubernetes teams applicable to the sig

### ISSUE THREAD

**Issue by cblecker** [kubernetes/community#702]
Similar to how sig-cli did it here:
https://github.com/kubernetes/community/blob/709d7bf026075b1ef0092947381932eac7c6e9af/sig-cli/README.md#sig-cli-teams

This is helpful to non-org members who wouldn't be able to see them by default.

Thoughts?

cc: @jamiehannaford

**Comment by cblecker** [comment]
@kubernetes/sig-contributor-experience-misc

**Comment by jdumars** [comment]
+1 from me on adding it.  These teams should eventually exist for all SIGs per the community document, so in theory it will be a simple text substitution for the SIG name.  Right now, I don't think the names are uniform, however.

**Comment by jamiehannaford** [comment]
Yeah, I agree they should be there. We actually do provide those team links if the `full_github_teams ` field for the SIG is set to true, like [here](https://github.com/kubernetes/community/blob/master/sigs.yaml#L388). The generator will expect that the SIG abides by the standard team names. See:

https://github.com/kubernetes/community/blob/master/generator/app.go#L41
https://github.com/kubernetes/community/blob/master/generator/app.go#L198-L200
https://github.com/kubernetes/community/blob/master/generator/sig_index.tmpl#L20-L24
https://github.com/kubernetes/community/tree/master/sig-openstack

**Comment by idvoretskyi** [comment]
+1 on this initiative.

**Comment by cblecker** [comment]
@jamiehannaford: a few things there..
- there is no guarantee that a sig will have all the teams listed. for example, contributor experience has no need for an api-reviews or test-failures team
- the sig names should have the format `@kubernetes/team-name` rather than just `@team-name` as you need the org to be able to mention them.
- the links are broken at the moment as you're missing the `/orgs/` part in the URL. For example, `sig-openstack-misc` is `https://github.com/orgs/kubernetes/teams/sig-openstack-misc`

**Comment by xiangpengzhao** [comment]
+1
ref: Document team list more clearly (#677)
