### ISSUE TITLE
Broken Github Team Links

### ISSUE THREAD

**Issue by Janvi-Thakkar** [kubernetes/community#7023]
### Describe the issue

All the provided team links under the section **[sig-release](https://github.com/kubernetes/community/blob/master/sig-release/README.md#release-team) > Release Team > Contact > GitHub Teams** are broken.

**Comment by mrbobbytables** [comment]
It's not broken, you must be a member of the org to view it.  👍

/close

**Comment by Janvi-Thakkar** [comment]
> It's not broken, you must be a member of the org to view it. 👍
> 
> /close

Thank you @mrbobbytables for the information.
