### ISSUE TITLE
sig name consistency

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#703]
There are a number of places where sig names are ever-so-slightly inconsistent.  I'd like us to link back to this issue when we identify those areas.  Update docs, preferably adjust what we can.

For a sig foo, I expect:
- a sig-foo entry in kubernetes/community/sigs.yaml
- kubernetes/community/sig-foo/README.md
- sig-foo google group
- sig-foo-* teams in https://github.com/orgs/kubernetes/teams
- sig-foo-* google groups
- k8s-mirror-sig-foo-* github users
- #sig-foo in kubernetes.slack.com
- sig/foo labels
- sig-foo to appear in [the list of valid test job owners](https://github.com/kubernetes/test-infra/blob/master/jobs/validOwners.json)

Examples of where we've hit inconsistencies:
- https://groups.google.com/forum/#!topic/kubernetes-wg-contribex/Bo0TnJEljoA
- https://github.com/kubernetes/test-infra/pull/2846#discussion_r121193390

EDIT: Is it reasonable to expect the same for working groups as well?

**Comment by spiffxp** [comment]
FYI @kubernetes/sig-contributor-experience-misc

**Comment by spiffxp** [comment]
FYI @xiangpengzhao

**Comment by xiangpengzhao** [comment]
+1000

It would be good to also have our sig meeting channels follow the name consistency.

In the page [SIGs and Working Groups](https://github.com/kubernetes/community/blob/master/sig-list.md), we use `hangouts` or `zoom` to hold meetings. And some meeting channels use number as id and others use name string.

@spiffxp

**Comment by idvoretskyi** [comment]
big +1

**Comment by castrojo** [comment]
So what I was thinking was proposing something to the SIG governance document that reads something like "The entry `dir: sig-api-machinery` in sigs.yaml becomes the machine-consumable naming convention that all your other resources inherit."

Then we make sure the slack channels, etc. align up. Renaming the slack channels is easy, we just renamed #sig-scale without problems. Not sure on how disruptive renaming google groups. I think the annoying bit will be the Zoom channels and calendars, which seems to be a mixture of numbers and shortcuts. 

However I think we can make the argument to all the leads that being able to just guess the channel name based on convention will be very useful for people, for example I would be able to guess that `zoom.us/j/sig-ui` is the right room. Calendars will be annoying but making SIGs follow this convention will lead to improved tooling and consistency.

**Comment by cblecker** [comment]
we can change/update sigs.yaml as needed.. there's actually three lines in there (dir, name, label) that are all similar. Having one as the source of truth, and then changing around the generator as needed would work

**Comment by bgrant0607** [comment]
Zoom channels should be prefixed with "k8s-"

Other open-source communities are adopting SIGs

**Comment by spiffxp** [comment]
re: zoom-channels, you only get one vanity url aka "Personal Link" via https://zoom.us/profile

>Personal Link is an alias of your personal meeting URL https://zoom.us/j/REDACTED.
>It must be 5 to 40 characters.
>It must start with a letter and can contain only letters (a-z), numbers (0-9) and periods (".")

Couldn't use a dash, so now I've got https://zoom.us/my/k8s.sig.testing, WDYT?

Only other URL I've seen is https://zoom.us/my/kubernetescommunity

**Comment by idvoretskyi** [comment]
Dots look weird, IMO.

**Comment by bgrant0607** [comment]
dots are better than no punctuation.

An existing example:
https://zoom.us/my/sig.apps

k8s.sig.testing seems fine.

**Comment by spiffxp** [comment]
Fun (annoying) facts discovered while trying to reconcile for sig-contributor-experience
- renaming a google group will break anything that attempts to use the old name
- slack channel names are limited to 21 characters (sig-contributor-experience is 27)

So we're back to kuberenetes-wg-contribex and #sig-contribex for now

**Comment by spiffxp** [comment]
/lifecycle frozen
As a "known issue".  

I'm not sure I ever foresee this getting fixed if the definition of done is "make everything the same".  I think instead a successful answer to these questions would do it:

- How could these conventions (and deviations from them) best be documented?
  - ie: I'm guessing somewhere in the docs around sig goverenance and sig creation there would be a list of all the things
- Where should a person go to find out about these different things for a given SIG?
  - ie: maybe use sigs.yaml to hold this info and generate it into SIG READMEs?

**Comment by parispittman** [comment]
[sig-wg-lifecycle.md](https://github.com/kubernetes/community/blob/master/sig-wg-lifecycle.md) should cover most of these conventions along with the other governance doc updates recently. most of the naming convention information is included in each relevant section. do you think this is good @spiffxp?

contribex ml has also been changed to kubernetes-sig-contribex@

**Comment by spiffxp** [comment]
/close
Yes, I think between sigs.yaml evolving to hold much of this contact info, and the lifecycle doc spelling out how to implement most of the conventions, we're good here
