### ISSUE TITLE
Revisiting the Need for the Community Meeting - Amending Governance

### ISSUE THREAD

**Issue by nimbinatus** [kubernetes/community#7051]
After a couple years of trying to revisit the community meeting and keep it going during the pandemic, we've come to realize that the community meeting isn't working as expected. Topics are being duplicated between meetings, it's difficult to find useful topics (as KEPs are typically discussed more in GitHub regardless) and experts to talk on those topics, and generally most contributors don't get involved. We also are experiencing a drop in attendance over the past couple years with most calls, not just the community meeting.

Currently, the community meeting as a monthly video call is part of our governance requirements (ref: https://github.com/kubernetes/community/blob/master/governance.md#community-group-annual-reports, https://github.com/kubernetes/community/blob/master/events/community-meeting.md, https://github.com/kubernetes/community/blob/master/sig-contributor-experience/charter.md#code-binaries-and-services, as some examples). Let's discuss how we can meet the spirit of the governance need in a better way.

A suggestion that came up was to tie the community meeting to the release cadence rather than having it be monthly (e.g., one contributor community meeting per release cycle), and partner with SIG Release to highlight important topics for discussion in relation to each release. This choice would address video call fatigue issues, would narrow down the scope a bit for the meeting to reduce the "not me!" reactions, and would help get major long-running discussions resolved in time for code freezes.

All discussion on this issue welcome.

cc @mrbobbytables @jberkus

ref: #6544

/assign @nimbinatus
/sig contributor-experience

**Comment by salaxander** [comment]
I think this is interesting! The main thing to address (at least initially in my mind) would be how to differentiate this from the typical webinars and such that coincide with the release in a similar way, but I think there's opportunity there

**Comment by mrbobbytables** [comment]
IMO I don't think there would be significant overlap with the webinars as long as we keep it "internally focused" like, here are some changes to be aware of, potentially new workflows that might be introduced etc.

**Comment by jberkus** [comment]
So I'm going to observe that two other kinds of meetings have superceded the kinds of discussions we used to have at Community Meetings in the past:

- Public Steering Committee meetings
- SIG-Leads monthly sync
- Written Annual Reports

So the need to chat about community-wide topics hasn't gone away, it's just being done in different places.

So I think our *first* question should be: is the Community Meeting still necessary?  Or should we focus 100% on the other channels, maybe improving them?  If the Community Meeting is EOL, we can amend the governance to remove it.

**Comment by parispittman** [comment]
+1 to amending the governance. that was something I wanted to work on and never got to it.

**Comment by nimbinatus** [comment]
It might be worthwhile to consider a different format altogether with a focus on a different audience or even split this out into two things:
* A news report for contributors about things like @mrbobbytables mentioned, and then
* I think one of the main issues is that there are a lot of contributors on the fringes who don't (or don't know to) attend the new meetings, and the community meeting is one way a lot of people get introduced to the project or find out what thing they want to work on based on discussions happening at the meeting. Would a video or blog post done per release that highlights every SIG and what they're working on this release (not an update from each chair, but more of a video/written overview done by a couple people) as an introduction should a contributor want to know where they can work this release cycle? And then concluding with "here's where you meet for more info." Sure, it might get a bit redundant at the end, but we have to remember that a lot of people aren't plugged in all the time and might forget how to find information.

**Comment by chris-short** [comment]
If the decisions for this ticket is scoped to keep the Community Meeting? yes/no

I would be voting no. I would propose a new issue to discuss where gaps exist in existing places would be beneficial to forming a new thing, if one is deemed necessary after that analysis.  
  
This issue would be to discuss the Governance changes.

**Comment by nimbinatus** [comment]
All right; I'll amend the title to reflect that.

**Comment by mrbobbytables** [comment]
+1 to remove
We can continue convo on what it should be (if we should continue to have it), but still overall +1 to remove it in its current form.

**Comment by qedrakmar** [comment]
I'm +1 here, especially separating the issues.  In its current form, the Community Meeting is not fulfilling the purpose I believe most people see for it, and it should be removed.  What fills that void becomes a follow-up question that we can discuss separately.

**Comment by jrsapi** [comment]
Community meeting was very valuable in the early days of Kubernetes but it has served it purpose. +1 to remove.

**Comment by nimbinatus** [comment]
Opened https://github.com/kubernetes/community/issues/7078 to split this issue into the governance question (this issue) and the discussion about whether there are gaps (7078).

**Comment by nimbinatus** [comment]
Closing now that #7068 merged. Further discussion on what, if anything, is missing in our community needs in #7078.

/close
