### ISSUE TITLE
[SLACK-ADMIN] archive #garden

### ISSUE THREAD

**Issue by worldofgeese** [kubernetes/community#7058]
### GitHub Username

@worldofgeese

### Slack Username

@worldofgeese

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

Channel

### Name of Requested Resource

#garden

### Description of Request

Garden has moved all community channels to our own Discord server. Please permanently archive the channel. If possible, with a notice we've moved to Discord so users don't think we've closed shop.

**Comment by sarthaksarthak9** [comment]
please assign this issue to me
