### ISSUE TITLE
GitHub Team's Clickable Links displays 404 Error. 

### ISSUE THREAD

**Issue by thebarshablog** [kubernetes/community#7067]
### Describe the issue

All the clickable links shows 404 Error. Requires update. I would like to take on the issue, if possible. Thank you. 

![Screenshot (830)](https://user-images.githubusercontent.com/103309340/214357960-9bcb70a5-0c3c-4da4-9a66-59acfb5d38df.png)

**Comment by mrbobbytables** [comment]
Thanks, but that is the expected behavior^^;;;

The teams are ONLY visible to other org members. If you are not an org member they will return GitHub's default..which is their 404 page.

/close

**Comment by mrbobbytables** [comment]
It's outlined in our community membership guidelines 👍 
https://github.com/kubernetes/community/blob/master/community-membership.md#member

**Comment by thebarshablog** [comment]
> It's outlined in our community membership guidelines 👍 https://github.com/kubernetes/community/blob/master/community-membership.md#member

Thank you so much for directing. I look forward to contributing.
