### ISSUE TITLE
REQUEST: New Slack channel #cluster-api-comms-team

### ISSUE THREAD

**Issue by oscr** [kubernetes/community#7154]
### GitHub Username

oscr

### Slack Username

oscar

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

Channel

### Name of Requested Resource

cluster-api-comms-team

### Description of Request

Hi, 

I would like to request a private channel for the Communications group of the Cluster API release team in order to discuss topics related to the next release of Cluster API. You can either add me and I can add the rest or find everyone's slack username in the CAPI repo: https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/releases/release-1.4.md#release-team

Thank you for your help :pray: 

cc @joekr @sayantani11 @VibhorChinda

**Comment by coderanger** [comment]
Hi there, we only provide private channels when the topics discussed would have a material adverse impact on the project or its users. Could you explain why a public channel would be detrimental here?

**Comment by oscr** [comment]
For the psychological safety of our members. I want everyone to feel safe and be able to ask any question regardless of experience level, make suggestions etc. A public channel would make this harder. This is why we have a private chat today for discussing release team activities. But I would prefer to have a private channel instead.

**Comment by coderanger** [comment]
That's counter to the goals and social structure of Kubernetes as a project. You should be doing your SIG business in public so anyone can see it (and thus so anyone can help). If you feel like you have issues with community safety or toxicity, SIG-ContribEx would be happy to help out.

**Comment by jberkus** [comment]
@oscr where are y'all seeing issues with public chats being unsafe?  As a member of the slack-admins team, if that's an issue we'd like to resolve it.
