### ISSUE TITLE
Unconference Topics - KCEU Contributor Summit 2023 Amsterdam

### ISSUE THREAD

**Issue by cailynse** [kubernetes/community#7157]
Hello friends!

We're hosting an Unconference for the Contributor Summit this year in Amsterdam. We'd love to hear from you about topics in which you are interested. You can submit a topic, and upvote topics that seem interesting to you. We want to understand what is of general interest to the community, and not just for those who happen to be joining us in Amsterdam.

Topic: [Sample Topic Submission]
Description: [Sample Topic Description]
Moderator: [Will you be there in person and like to moderate? (yes or no)]

To upvote, please use the :+1: emote

Feel free to reach out to @detiber (@jdetiber in Slack) for any questions.

Thank you!
Cailyn Edwards, KCEU Contributor Summit 2023 Content Shadow

SESSION NOTES CAN BE FOUND HERE: [k8s.dev/summit/notes](https://drive.google.com/drive/u/0/folders/1f-GChvcrbGW4TOOz2RTV6wRKOAyJRO-j)

**Comment by kflynn** [comment]
Topic: GAMMA Gathering
Description: Meet the folks working on [GAMMA](https://gateway-api.sigs.k8s.io/contributing/gamma/)! Find out the latest and greatest! Offer feedback and get involved!
Moderator: I'll be there in person and can moderate, as long as this is scheduled after lunch.

**Comment by thschue** [comment]
Topic: Gain SRE Superpowers with [K8sGPT](https://k8sgpt.ai)
Description: In the last few weeks, we built this new project to make troubleshooting in k8s easier. Meet us there, get some information about the project and help us evolving!
Moderator: @roberthstrand and myself

**Comment by mrbobbytables** [comment]
@thschue these sessions are for k8s contributors and should be focused on aspects related to contributing.

**Comment by thschue** [comment]
@mrbobbytables: We've been asked to provide a talk here. If this is out of scope, it's okay for us.

**Comment by ivelichkovich** [comment]
Topic: Management Plane Persona/Role
Description: How can we better support the management plane/cluster provider persona to have the controls to keep clusters stable for end users. 
Moderator: @jpbetz and myself

**Comment by cailynse** [comment]
**Topic:** Fresh Air with SIG-Security
**Description:** Part of SIG-Security and want to hang IRL? Not a part of Security and want to hang IRL? We will be meeting at Contributor Summit and taking a wander outside to catch up and chat about what we have done, what we want to do and what we should do! Anyone and everyone welcome!
**Moderator:** @tabbysable @IanColdwater

**Comment by qedrakmar** [comment]
**Topic:** Non-Code Contributions to Kubernetes
**Description:** The original [Non-Code Contributors Guide](https://www.kubernetes.dev/docs/guide/non-code-contributions/) is now multiple years old and dormant.  It did significant analysis of the project and identified and enumerated places for contribution, but didn't get to go any further.  We would like to bring this project back out of hibernation to continue the original mission of enabling contributors who are doing anything other than writing and committing code, but there's a lot under the hood to make this work.
**Moderator:** Myself

**Comment by thockin** [comment]
**Topic**: Paying down the debt - engaging more contributors more successfully
**Description**: There are a LOT of people out there who would love to contribute to kubernetes, but we don't make it easy.  If we file actionable bugs with complete descriptions and then invest a little time in review/followup, we can make k/k (in particular but not exclusively) a better place to work.  It would be interesting to share strategies, success stories, and failure modes.
**Moderator**: @jpbetz or someone (I won't be there sadly)

**Comment by soltysh** [comment]
I'm happy to help moderating the topic from @thockin, that's what I was also thinking myself as well.

**Comment by KimMcMahon** [comment]
Topic: Building an engaging community

Description: [Sample Topic Description]
Building the community and providing high-value content and engagement are key components to the health and growth of open source projects. There are many approaches you can choose; the important thing is to listen, learn, and try new things. In this Unconference we'll talk about what worked, what could have worked better, how we measure, the value of personal connections, what type of events and how they fit into community growth, and share our experiences. 

Moderator: Kim McMahon and I'll be there in person.

**Comment by chris-short** [comment]
Topic: There are [about 1.5 million](https://github.com/raesene/public-k8s-censys) Kubernetes clusters publicly exposed on the internet.

What can we do as a community to help folks with this?

Suggestion: think non-code efforts before code changes

I will not be able to attend to lead this discussion sadly. But, I'd love the notes.

**Comment by aojea** [comment]
Topic: kubernetes network configuration, do we need an API?

Description: The kubernetes network configuration is spread over different componens of the cluster and some time it can be defined by external components like CNIs. Can we do better and offer a better user experience?
There is an ongoing conversation started by this doc https://docs.google.com/document/d/1Dx7Qu5rHGaqoWue-JmlwYO9g_kgOaQzwaeggUsLooKo/edit?usp=drivesdk but we can use some in person time to discuss it further and get more opinions

**Comment by atosatto** [comment]
Topic: Entertaining the idea of `PreferNoExecute` taints
Description: Kubernetes provides taints as a mechanism to provide both hints to the scheduler as well as evict workloads from nodes. [Taint Based Eviction](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions) is a powerful tool to allow operators to vacate workloads from Nodes in case of issues (e.g. Nodes being unreachable) allowing workloads to be re-scheduled to healthy nodes. However this comes with some surprises, despite the feature being advertised as "eviction" TaintManager is actually deleting Pods from the Node and not calling the evict API! The goal of this talk is to entertain the idea of a `PreferNoExecute` taint effect discussing its potential use-cases and implementation.
Moderator: @atosatto

**Comment by mfojtik** [comment]
**Topic**: How to argue business value of upstream involvement to managers

**Description**: Kind of ad-hoc, but inspired by morning session, it looka like many engineers struggle to sell the value of upstream contributions to their employers. It might be helpful to discuss strategies that help having these conversations with managers.

**Moderator**: @mfojtik (or anybody else, @soltysh or @sttts ;-)

**Comment by mrbobbytables** [comment]
/close

kubecon EU has passed.
