### ISSUE TITLE
KubeCon EU 2023 - SIG Meet and Greet

### ISSUE THREAD

**Issue by KimMcMahon** [kubernetes/community#7161]
HI all - reminder - the Meet and Greet is this afternoon! The room will open at noon for setup!

The SIG Meet and Greet will be a part of KubeCon EU. It is scheduled for Friday, April 21 from 12:30pm - 2:30pm. If your SIG is interested in having a table, please comment on this thread and I will update the list below

Current participating community groups:
SIG Apps - [soltysh](https://github.com/soltysh)
SIG CLI - [soltysh](https://github.com/soltysh), Katrina Verey | Eddie Zaneski
WG Batch - [soltysh](https://github.com/soltysh) , Aldo Culquicondor
SIG-Network - [aojea](https://github.com/aojea), Shane Utt
SIG-Testing -  [aojea](https://github.com/aojea)
SIG-Docs - [natalisucks](https://github.com/natalisucks) and [divya-mohan0209](https://github.com/divya-mohan0209)
SIG Instrumentation - [pohly](https://github.com/pohly), Damien Grisonnet
SIG Testing - [pohly](https://github.com/pohly), Antonio Ojea
SIG Auth - [enj](https://github.com/enj), Rita Zhang | Jordan Liggitt / liggitt@google.com
SIG Security Response Committee - [enj](https://github.com/enj), Rita Zhang
SIG Storage and Data Protection WG - [xing-yang](https://github.com/xing-yang), Jan Šafránek
SIG-Release - [jrsapi](https://github.com/jrsapi)
WG-Policy [JimBugwadia](https://github.com/JimBugwadia), Robert Ficcaglia
K8s Infra [jeefy](https://github.com/jeefy)
SIG-Security - [cailynse](https://github.com/cailynse)
sig cloud provider and sig beard - [elmiko](https://github.com/elmiko)
Contributor Comms Subproject: Kaslin
Contributor Experience: Kaslin, Killen, Berkus
Scheduling: Aldo Culquicondor

/assign @KimMcMahon @nimbinatus 
/area contributor-summit
/sig contributor-experience

**Comment by soltysh** [comment]
I'll be there to represent sig-apps, sig-cli and wg-batch :sweat_smile:

**Comment by aojea** [comment]
sig-network and sig-testing here

**Comment by natalisucks** [comment]
I can be there for the first half to represent SIG Docs (Our maintainer track talk is at 2pm on Friday)

**Comment by MadhavJivrajani** [comment]
I'll be there for SIG ContribEx

**Comment by pohly** [comment]
SIG Instrumentation and SIG Testing

**Comment by enj** [comment]
SIG Auth and Security Response Committee

cc @ritazh

**Comment by divya-mohan0209** [comment]
SIG Docs represent here too!

**Comment by JimBugwadia** [comment]
I will be there for WG-Policy.

**Comment by jeefy** [comment]
K8s Infra :)

**Comment by cailynse** [comment]
I'll be there for at least part of it representing SIG-Security - will try and rope another person in!

**Comment by elmiko** [comment]
happy to represent sig cloud provider and sig beard =D

**Comment by brasmith-ms** [comment]
I'll be there for SIG-Windows!

**Comment by jpbetz** [comment]
I'll be there for SIG-api-machinery.

**Comment by varshaprasad96** [comment]
I can be there for SIG-Api-machinery too.

**Comment by matthyx** [comment]
I can represent Node if needed 👍

**Comment by MaciekPytel** [comment]
I can be there for sig-autoscaling, though I may need to leave a few minutes early to catch my plane

**Comment by jberkus** [comment]
This is over

/close
