### ISSUE TITLE
Will Kubernetes participate in the Project Team Gathering at the OpenInfra Summit? 

### ISSUE THREAD

**Issue by kendallnelson** [kubernetes/community#7169]
Hello! 

I wanted to take a moment to invite the Kubernetes community to participate with other open source projects in the Project Team Gathering (PTG)[1] taking place during the Open nfra Summit[2] in Vancouver, BC June 13-15. 

The Project Team Gathering is a place for open source project teams to gather and discuss with one another the future of open source collaboration - features, integration, etc. 

Since there is an overlap in the OpenInfra (OpenStack, Kata Containers, StarlingX) and Kubernetes communities - we've already been collaborating in different ways- I wanted to extend the invitation to the k8s community!

To participate, I will need a representative - preferably one that would be attending in person- to fill out the survey here[3].

Registration for the summit includes access to the PTG; registration is open and prices go up early May. 

[1] https://openinfra.dev/ptg/
[2] https://openinfra.dev/summit/vancouver-2023
[3] https://openinfrafoundation.formstack.com/forms/june2023_ptg_survey
[4] https://vancouver2023.openinfra.dev/

/sig contributor-experience
/sig cloud-provider
/committee steering

**Comment by kendallnelson** [comment]
Sad to close it, but it seems there isn't enough interest. Hopefully next time!!

**Comment by jberkus** [comment]
@kendallnelson we had a bunch of folks who were interested, and then everybody got their travel budgets cut :-(

**Comment by kendallnelson** [comment]
@jberkus I know how that goes. The same unfortunately has been happening to some of our previously confirmed speakers even. Its tough out there these days!
