### ISSUE TITLE
Unknown CLA label state. Rechecking for CLA labels.

### ISSUE THREAD

**Issue by wzshiming** [kubernetes/community#7174]
### Describe the issue

https://github.com/kubernetes-sigs/kwok/pull/368

**Comment by MadhavJivrajani** [comment]
There seems to be an issue with EasyCLA, there's a filed issue: https://github.com/communitybridge/easycla/issues/3843

Upstream threads:
- https://kubernetes.slack.com/archives/C1TU9EB9S/p1678351853346579
- https://kubernetes.slack.com/archives/C01672LSZL0/p1678333533824339

**Comment by DavidXU12345** [comment]
Same issue happens in aws-efs-csi-driver repo

<img width="1282" height="381" alt="Image" src="https://github.com/user-attachments/assets/878baca2-d760-490a-bef3-795e22e5cacf" />
