### ISSUE TITLE
SURVEY REQUEST: Is the CI Signal weekly report email useful to you?

### ISSUE THREAD

**Issue by lauralorenz** [kubernetes/community#7176]
### Group Requesting

SIG-Release

### Title of Survey

CI Signal Weekly Report Feedback survey

### Goal of Survey

To determine if the CI Signal Weekly report is useful to the general dev mailing list and #release-ci-signal slack participants and whether the CI Signal subteam should continue producing it in future release cycles.

### Target Audience

All of k-dev and #release-ci-signal Slack channel

### Results Recipients

Laura Lorenz (1.27 CI Signal team lead), Xander Grzywinski (1.27 Release Lead),  Jeremy Rickard /Stephen Augustus / Sascha Grunert (SIG-Release leads)

### Date Survey Starts

ASAP

### Date Survey Ends

4/11/2023 (end of 1.27 release)

### Publicity Help Wanted?

Yes

### Data Analysis Wanted?

No

### Link to Draft Questions

https://hackmd.io/@on2gXqykTESI4N6quhc9pw/rkKylZuy3

**Comment by markyjackson-taulia** [comment]
I personally find it useful

**Comment by dims** [comment]
YES! i watch this to know when to pitch in

**Comment by chris-short** [comment]
It's helpful. I greatly appreciate it.

**Comment by jberkus** [comment]
Pinging y'all over Slack; I think this needs some discussion.

**Comment by jberkus** [comment]
Laura and I chatted over Slack; we're going to discuss this next SIG-Release meeting.

**Comment by jberkus** [comment]
We discussed this in SIG-release; the survey in not required.

/close
