### ISSUE TITLE
REQUEST: New Slack channel kubernetes-docs-bg

### ISSUE THREAD

**Issue by OrlinVasilev** [kubernetes/community#7183]
### GitHub Username

OrlinVasilev

### Slack Username

Orlix

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

Cahnnel

### Name of Requested Resource

new slack channel for Kubernets docs in Bulgarian

### Description of Request

Create a Slack channel for Български (Bulgarian) docs localization.

/sig docs
/language bg

**Comment by coderanger** [comment]
/assign @kubernetes/sig-docs-leads 

This is a delegated channel space so anyone in SIG-Docs can put up a PR and the SIG leads can approve it. Happy to help if you have any questions!

**Comment by sftim** [comment]
Thanks for the PR. @OrlinVasilev, did you already run this past the SIG Docs localization group meeting?

**Comment by OrlinVasilev** [comment]
@sftim I've asked into the slack channel https://kubernetes.slack.com/archives/C0191RDKHU1/p1678816497063709 and openned these as is described here : https://kubernetes.io/docs/contribute/localization/

**Comment by natalisucks** [comment]
@OrlinVasilev Thanks for your request! It can sometimes be hard to attend the localization meetings, which is where we explain the basics for setting up a localization group and the associated work. We'd just be looking for from you, either in this PR or in one of our meetings, acknowledgement and understanding of the [minimum docs](https://kubernetes.io/docs/contribute/localization/#minimum-required-content) required to be translated, as well as the requirement for two owners/maintainers for any localization group to be official.

I think express acknowledgement of the above in this PR would be fine to approve channel creation, so you can get started with building community to meet those requirements!

cc. @a-mccarthy, @divya-mohan0209 and @reylejano for visibility.

**Comment by OrlinVasilev** [comment]
Hi @natalisucks thank you so much :) will do my best to join the next localization meeting!  We have already a small group of people ready to put the initial effort to get things started! we are me, @nickolaev and @iliyan-s-petkov for now waiting few others to confirm as well! My idea is to grow that beyond and already addressed the topic with local offices to a companies in Sofia! And especially with local universities to involve the students into the OS world and in particular to expose them to CNCF and K8s!

**Comment by natalisucks** [comment]
Great, thanks @OrlinVasilev. With your answer above and acknowledgement of the work, I'm good to approve channel creation from SIG Docs and the Localization subproject.

You can follow the latest channel creation PR example from our Tamil community folks (who attended a localization meeting) [here](https://github.com/kubernetes/community/pull/7170) to get things going.

**Comment by reylejano** [comment]
Hi @OrlinVasilev ,

The next localization meeting is [April 1 at 15:00 UTC](https://docs.google.com/document/d/1NwO1AN8Ea2zlK8uAdaDAKf1-LZDAFvSewIfrKqfl5No/) 
Here are the [meeting notes and agenda](https://docs.google.com/document/d/1NwO1AN8Ea2zlK8uAdaDAKf1-LZDAFvSewIfrKqfl5No/). The zoom link is in the agenda

Is there another contributor to begin the localization?
See the [tart a new localization section](https://kubernetes.io/docs/contribute/localization/#start-a-new-localization) for more info

**Comment by seokho-son** [comment]
PTAL: PR to resolve this issue #7200 :)

**Comment by OrlinVasilev** [comment]
also this one : https://github.com/kubernetes/org/issues/4092

**Comment by OrlinVasilev** [comment]
@reylejano - https://github.com/kubernetes/org/pull/4104 for the team members
