### ISSUE TITLE
Consider how to use team nesting on GitHub organization

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/community#720]
With 244 teams and still going strong, it's getting increasingly more difficult to navigate https://github.com/orgs/kubernetes/teams.

GitHub has just introduced nested teams (https://github.com/blog/2378-nested-teams-add-depth-to-your-team-structure) this allows categorizing the teams and permissions inheritance etc. Opening this issue to discuss whether we can leverage this feature or not.

**Comment by enj** [comment]
Nested group membership in Active Directory was a nightmare to deal with.  It was impossible to tell what rights a user would have.  That being said, nested teams in GitHub seem significantly constrained and thus may actually be useful and auditable.

**Comment by idvoretskyi** [comment]
cc @kubernetes/sig-contributor-experience-misc

**Comment by cblecker** [comment]
From @spiffxp in [#sig-contribex](https://kubernetes.slack.com/archives/C1TU9EB9S/p1497382619722762) on Slack:
> well the counter arg is it looks like all the sub-teams all get notified if you notify the broader team
> where I think the intent was to have oversubscribed folks on high-signal low-noise teams w/ specific purpose

**Comment by bgrant0607** [comment]
Note that we plan to sync most/all the github teams from files checked in to some repo.

**Comment by bgrant0607** [comment]
People also need to be org members in order to belong to teams, so finalizing the policies around org membership and automating member maintenance is more important, as well.

**Comment by cblecker** [comment]
Closing in favour of #2323
