### ISSUE TITLE
[SIG Node] Improve CONTRIBUTING.md 

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/community#7223]
As discussed at the SIG Node meeting today we need to improve SIG Node contributing.md file.

Some ideas:

- [ ] Break down components beyond kubelet
- [ ] Link to the SIG Node related test-infra folders and code
- [ ] Links on documentation for e2e tests and e2e_node tests
- [ ] Link to general code organization document (explaining things like vendor/, staging/, etc.)
- [ ] Link contributors ladder `sig-node-contributor-ladder.md`

/sig node
/help

**Comment by pacoxu** [comment]
I would like to help with this task. I was recently working on a topic like `Kubelet Intro & Deep Dive`.

https://github.com/kubernetes/community/blob/master/sig-node/CONTRIBUTING.md
/assign

**Comment by manishd17** [comment]
I wanna work on this issue

**Comment by pacoxu** [comment]
@manishd17  have you started your work on this? 

I just get some time to start this work.

**Comment by manishd17** [comment]
Ok!!
