### ISSUE TITLE
[SIG Node] review OWNERS files

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/community#7234]
As a follow up from https://github.com/kubernetes/community/pull/7220 we need to review and update OWNER files.

Key feedback - make it clear who is reviewing what and who to ask for approval.

Breaking down into smaller components is an additional bonus

/sig node
/assign 
/assign @mrunalp

**Comment by pacoxu** [comment]
Just an idea that we may add some tags/feature-names for approvers and reviewers in the owner file like
- gpu/numa; cadvisor; cri; image; cpu-manager; cni; npd, API, eviction, gracefulshutdown, cgroupv2.

**Comment by SergeyKanzhelev** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/119566

**Comment by SergeyKanzhelev** [comment]
More reviewers:
- https://github.com/kubernetes/kubernetes/pull/113333
- https://github.com/kubernetes/kubernetes/pull/120272
