### ISSUE TITLE
SIG Autoscaling Leads Mailing List and Associated Zoom Setup

### ISSUE THREAD

**Issue by gjtempleton** [kubernetes/community#7238]
### Describe the issue

The existing @kubernetes/sig-autoscaling-leads don't have access to the existing Google groups mailing list ([kubernetes-sig-autoscaling-leads@googlegroups.com](mailto:kubernetes-sig-autoscaling-leads@googlegroups.com)). As this is also the email address tied to our SIG's Zoom meeting this presents a problem given that 2FA auth codes for login are also sent to this address. We can currently still run meetings off the correct zoom when one of the leads is in attendance due to an existing login on a mobile phone, however are forced to fall back to a different zoom meeting when this lead is unable to attend.

We've made attempts to track down any previous leads who may have still had access to the group without success.

**Comment by mrbobbytables** [comment]
/sig contributor-experience
@gjtempleton we can't recover that group, but we can switch zoom to a new one. We want everyone to migrate over to k8s.io managed groups anyway so this is a good excuse to start.

**Comment by gjtempleton** [comment]
That was what I expected, no problem at all with that. 

Just let us know what you need from the SIG to get this done.

**Comment by gjtempleton** [comment]
Hi @mrbobbytables, is there anything I can do from the SIG side to help getting this moving?

**Comment by mrbobbytables** [comment]
Sorry - fell off my radar - I'll reach out in slack

**Comment by gjtempleton** [comment]
Now created the new list (`sig-autoscaling-leads@kubernetes.io`) and updated settings as per Slack conversation with @mrbobbytables, do I need to raise a separate ticket to get the Zoom ownership switched over to the new email?

**Comment by mrbobbytables** [comment]
I'll log the ticket with zoom 👍

**Comment by mrbobbytables** [comment]
this has been resolved 🎉 

/close
