### ISSUE TITLE
SIG Testing: Rotating Chairs

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/community#7239]
See: https://groups.google.com/a/kubernetes.io/g/dev/c/86rTYK7i7BE

Below is copied from `contributors/chairs-and-techleads/leadership-changes.md`.

# Leadership Changes

This document covers steps needed to propose changes to SIG/WG/UG leadership.

- [x] Discuss the proposed changes with the current leadership.

- [x] Send an email to the SIG/WG/UG mailing list and cc the [kubernetes-dev]
mailing list. At a minimum, the email should contain:
  - [x] intent to step down as the current lead
  - [x] if nominating another lead
    - [x] 1-2 lines about why they are being nominated
    - [x] contacts to privately reach out to for questions (current leads)
          or concerns (current leads + [steering-private]) about the nomination
  - [x] if this was discussed in a meeting, link to meeting notes
  - [x] lazy consensus deadline of at least one week
  - This is done at: https://groups.google.com/a/kubernetes.io/g/dev/c/86rTYK7i7BE

- [x] If nominating another lead, ensure that they
  - [x] are a Kubernetes GitHub org [member]
    - Yes, https://github.com/kubernetes/org/issues/3828
  - [x] have completed the [Inclusive Open Source Community Orientation course]
    - Confirmed https://github.com/kubernetes/community/issues/7239#issuecomment-1495281283

- [x] Once lazy consensus has been achieved, update the following
      files in the respective repos:
  - [x] [kubernetes/community]: [`sigs.yaml`] and use the [generator doc]
        to update `README.md` and `OWNERS_ALIASES` files
      - PR: https://github.com/kubernetes/community/pull/7240
  - [x] [kubernetes/org]: `OWNERS_ALIASES`, [milestone-maintainers team],
        kubernetes and kubernetes-sigs [team configs]
  - [x] [kubernetes/enhancements]: `OWNERS_ALIASES`
  - [x] [kubernetes/k8s.io](https://github.com/kubernetes/k8s.io): `groups/groups.yaml` - leads email group members

- [ ] Update all communication properties used by the community group.
      See [sig-wg-lifecycle.md] for details.

Note: If multiple candidates are running for an open lead position and
lazy consensus cannot be achieved, an election should be held.
SIG Contributor Experience should be contacted to assist with the
administration of the election.

[kubernetes-dev]: https://groups.google.com/a/kubernetes.io/g/dev
[steering-private]: steering-private@kubernetes.io
[member]: /community-membership.md#member
[`sigs.yaml`]: /sigs.yaml
[generator doc]: /generator
[kubernetes/community]: https://github.com/kubernetes/community
[kubernetes/org]: https://github.com/kubernetes/org
[kubernetes/enhancements]: https://github.com/kubernetes/enhancements
[milestone-maintainers team]: https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml
[team configs]: https://git.k8s.io/org/config
[Inclusive Open Source Community Orientation course]: https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/
[sig-wg-lifecycle.md]: /sig-wg-lifecycle.md

-----

Addendum: We also need to:
- [x] Add to the SIG Testing 1Password vault (zoom account etc)
- [x] ...?

cc @xmcqueen @michelle192837

**Comment by BenTheElder** [comment]
Working on the k/community PR now.

Also: We should make this into an issue template
/sig testing

**Comment by BenTheElder** [comment]
@xmcqueen we need to follow-up on:
> have completed the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

Can you assert that here / upload your certificate? We've done this previously for existing leads and for steering for example. ref: https://github.com/kubernetes/steering/issues/256

**Comment by xmcqueen** [comment]
I will do the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) thanks

**Comment by xmcqueen** [comment]
Here's an image of the certificate @BenTheElder 

<img width="739" alt="Screenshot 2023-04-03 at 8 08 44 PM" src="https://user-images.githubusercontent.com/48169401/229676974-45844f02-c2c7-4c27-9cc3-0f3e8217e111.png">

**Comment by BenTheElder** [comment]
Thank you! I've updated the checklist. We'll get some more reviews on #7240 and start merging PRs tomorrow hopefully :-)

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/community/pull/7240 is merged, but we still have several follow-up PRs to do.

**Comment by xmcqueen** [comment]
The updates for the kubernetes/org: kubernetes/org#4144

**Comment by xmcqueen** [comment]
The updates for kubernetes/enhancements: kubernetes/enhancements#3941

**Comment by xmcqueen** [comment]
The updates for kubernetes/k8s.io: kubernetes/k8s.io#5082

**Comment by BenTheElder** [comment]
this is done (including 1password finally 😅 , thanks @mrbobbytables)
