### ISSUE TITLE
Non-UTC major timezones to be added to sig.yaml

### ISSUE THREAD

**Issue by idvoretskyi** [kubernetes/community#724]
Today, [sig.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml) includes UTC timezone slots for the SIG-meetings.

It is likely to have other major timezones mentioned in the SIG README - to avoid the necessity of conversion.

Major timezones (with the largest number of attendees) are:
- Pacific (UTC−8)
- Eastern (UTC−05:00)
- Central European (UTC +1)
- other (optional)

**Comment by idvoretskyi** [comment]
cc @jamiehannaford @kubernetes/sig-contributor-experience-misc

**Comment by jamiehannaford** [comment]
@idvoretskyi Good idea. What do you think is the best way we can format that on the README?

**Comment by cblecker** [comment]
The thing that gets tricky with non-UTC is you would also have to either list or compensate for Daylight Savings Time.

**Comment by idvoretskyi** [comment]
@jamiehannaford just as we do for `utc`?

**Comment by chrislovecnm** [comment]
An we include a website link that will do the tz conversion for us? We had a link on the aws sig page awhile back.

**Comment by idvoretskyi** [comment]
@chrislovecnm it can be an option.

**Comment by jamiehannaford** [comment]
Links for conversion are already populated on the READMEs, see [here](https://github.com/kubernetes/community/tree/master/sig-api-machinery#meetings). A PR to fix this issue would just add a few more common timezones to the default view.

**Comment by cblecker** [comment]
sigs.yaml is now time zone enabled!
/close
