### ISSUE TITLE
Create issue template for leadership updates

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/community#7241]
### Describe the issue

We have a nice checklist at `contributors/chairs-and-techleads/leadership-changes.md`, can we help ensure this checklist is run through in a tracking issue instead?

I've done this manually in https://github.com/kubernetes/community/issues/7239 for SIG Testing

**Comment by SergeyKanzhelev** [comment]
I have a document for sig node. I will try to merge things.

One note here is whether we need to add distinction between TL and Chairs. For example, charter for Chairs is not declaring all chairs to be approvers of enhancements. But Enhancements repository has no distinction between chairs and leads. Should it be created?

cc @mrbobbytables

**Comment by mrbobbytables** [comment]
this has been done - just forgot about the issue itself XD

/close
