### ISSUE TITLE
Remove Kubefed from sig-multicluster README

### ISSUE THREAD

**Issue by maximveksler** [kubernetes/community#7248]
### Describe the issue

Hello,

As kubefed SIG has been sunset it makes sense to remove the reference to it from sig-multicluster README and related docs. This to reduce confusion from newly k8s community members regarding the status of the effort, other alternatives would be to add a note in the README however this IMHO a lesser effective and suitable solution for case of SIG EOL.

This given that a "SIG archive" does not exists, if such policy does exists and I'm not aware of it I support following it instead.

**Comment by mrbobbytables** [comment]
That will be taken care of when the repo itself is archived - open issue here:  https://github.com/kubernetes/org/issues/4122

/close
