### ISSUE TITLE
kubectl delete doesn't account for list/watch permissions on resource being deleted since Kubernetes 1.25

### ISSUE THREAD

**Issue by narendramadanapalli** [kubernetes/community#7252]
### Describe the issue

With the introduction of https://github.com/kubernetes/kubectl/commit/77c921aa92d548d261fcfcf777d975000fb402d9 the kubectl delete operation will indefinitely wait on the "resource deleted?" condition by means of list and watch when the user doesn't have permissions on the verb list and watch.

For example, if user is not given privilege to list or watch resources of kind "kind-foo", `kubectl delete kind-foo resource-foo` operation will never terminate even after resource-foo is removed from the server.

Not certain if the above change is intentional, however, the delete operation should account for the the case where user is forbidden to list and watch resources to resolve above side-effects.

**Comment by mrbobbytables** [comment]
@narendramadanapalli this repo is a meta repo for managing the project itself and not likely to be seen by anyone who could triage it - you probably want to open an issue on https://github.com/kubernetes/kubectl directly

**Comment by narendramadanapalli** [comment]
Thanks @mrbobbytables! Opened an issue https://github.com/kubernetes/kubectl/issues/1411

**Comment by mrbobbytables** [comment]
Np, will go ahead and close this one 👍

/close
