### ISSUE TITLE
Revive WG-LTS

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes/community#7259]
### Describe the issue

Microsoft recently announced that the Azure Kubernetes Service would being offering [long term support](https://aka.ms/aks/upgrades-and-lts) (LTS) for Kubernets 1.27. Some individuals at KubeConEU 2023 Contributor Summit indicated that they were either working on something similar or planned to do so, which resulted in a lively a unconference session discussing [Kubernetes LTS](https://docs.google.com/document/d/1C7utWMjGpDcBc5TB_ooddERsid59sFLC7gqLzyS5aKY/).

There appeared to be general agreement from those in attendance that "longer" support would be beneficial to the community and that some of the issues that were blockers/limitations to the previous iteration of [wg-lts](https://github.com/kubernetes/community/pull/5240) are no longer as impactful as they once were, but that additional work remains and there are still things to work through. The general consensus was also that the #1 action item from that unconference session was that we should revive WG-LTS to work on a new charter and to collaborate on the outstanding issues to try and identify a more detailed vision for what a community supported LTS would entail.

The [working group governance](https://github.com/kubernetes/community/blob/master/committee-steering/governance/wg-governance.md) covers creating and disbanding a WG, but not necessarily reviving a previously disbanded working group, so I'm opening this issue as a placeholder to discuss reviving the WG and for tracking potential items outline in the SIG/WG Lifecycle Doc (https://github.com/kubernetes/community/blob/master/sig-wg-lifecycle.md). I assume we'd just treat this as creation of a new WG, so I'll also send an email to [dev@kubernetes.io](mailto:dev@kubernetes.io) per the lifecycle doc. 

This is a topic that requires input from a number of SIGs, I've included a few of them below. 

/sig architecture release k8s-infra testing

**Comment by kmova** [comment]
> we should revive WG-LTS to work on a new charter and to collaborate on the outstanding issues to try and identify a more detailed vision for what a community supported LTS would entail.

💯

**Comment by liggitt** [comment]
I'm happy to help with this.

The first wg-lts identified an annual support period as being valuable to a wide range of users, and identified go as a particularly important dependency that didn't match Kubernetes' support window. Focusing on those pain points, we drove improvements over the past few years ([KEP-1498](https://github.com/kubernetes/enhancements/blob/master/keps/sig-release/1498-kubernetes-yearly-support-period/README.md) expanded Kubernetes support from 9 to 14 months, [KEP-3744](https://github.com/kubernetes/enhancements/issues/3744) resolved k8s/go support drift) in ways that benefited everyone without significantly increasing community costs.

Another iteration of the working group to reassess wants/needs of end users and people supporting Kubernetes and the costs/blockers to the community or vendors supporting those wants/needs seems valuable and timely.

While I'm personally skeptical that the community can _afford_ to support additional versions, and I think a "same thing but for longer" approach mostly just time-shifts issues people currently have N months into the future, I'm on board with identifying/driving efforts that provide broad benefit to users, specifically improve the lives of users/vendors that need to support Kubernetes longer than OSS currently does, and can be afforded by the community.

**Comment by ShashankGirish** [comment]
I'd be happy to help with this effort too.

**Comment by hakman** [comment]
I would be interested in this topic also.
Should upgrade be supported from one LTS to the next, without going through intermediate releases?
/cc

**Comment by hakman** [comment]
@liggitt Btw, maybe sig-cluster-lifecycle should be involved also
/cc @justinsb

**Comment by ritazh** [comment]
I'm excited about this!

On the tactical side, for folks who are following this issue at home, how can they start getting more involved? Specifically when is the next WG meeting? Can we use any of the old mailing list, Google docs, Zoom meeting, GitHub directory? Since this is a revival of an old WG, the existing docs didn't cover this case (yet).

**Comment by mrbobbytables** [comment]
Just wanted to chime in and +1 Jordan's comments on next steps as a steering committee member.

Folks can freely talk about it, but to get things going officially the charter/PR/acks from sponsoring sigs need to happen first.

**Comment by pacoxu** [comment]
We start a similar project https://github.com/klts-io/kubernetes-lts last year and focus on CVEs and critical issues only.

**Comment by ChaoyiHuang** [comment]
> > If Kubernets provide LTS release, then, all telecom application vendors, k8s distribution vendors, operators can be aligned to the Kubernetes LTS release, the compatibility test cost will be reduced greatly to every player in telecom industry, 66% reduction.
> 
> is the telecom industry planning to add resources (as in money and people) to the project to make it happen ?

yes, planning to add resources

**Comment by detiber** [comment]
> > @liggitt Btw, maybe sig-cluster-lifecycle should be involved also
> 
> I think this touches pretty much _every_ sig :-)

Just adding agreement here that SIG Cluster Lifecycle should be one of the key stakeholders/sponsors for this effort.
/cc @vincepri @neolit123 @CecileRobertMichon @fabriziopandini

**Comment by jeremyrickard** [comment]
I sent a message to k-dev: https://groups.google.com/a/kubernetes.io/g/dev/c/qWsMPMDqCFQ

**Comment by jberkus** [comment]
As one of the leads of the former WG-LTS, +1 on restarting the WG under new leadership.

**Comment by logicalhan** [comment]
Also interested.

**Comment by youngnick** [comment]
As another lead of the former WG-LTS, I'm also +1, and would definitely like to be involved.

**Comment by neoaggelos** [comment]
I'd be very happy to join this effort and contribute to the best of my abilities.

**Comment by dims** [comment]
+1 from myself and on behalf of sig-arch

**Comment by vincepri** [comment]
+1 from SIG Cluster Lifecycle, today's community meeting ([recording](https://www.youtube.com/watch?v=gOs1_JLGFaE)): chairs and tech leads were overall very supportive of the effort, and would like to be one of the primary stakeholders and sponsors.

**Comment by chris-short** [comment]
Strong +1.

How does one get plugged in to help?

**Comment by munnerz** [comment]
I would also like to participate/help to represent Apple's interests in the LTS discussion :)

**Comment by reylejano** [comment]
+1 
I'm interested in helping

**Comment by sftim** [comment]
@reylejano do you have capacity to also represent SIG Docs for LTS (at least the WG kickoff)?

**Comment by hannibalhuang** [comment]
+1

**Comment by reylejano** [comment]
> @reylejano do you have capacity to also represent SIG Docs for LTS (at least the WG kickoff)?

@sftim , yes I capacity

**Comment by bharitwal** [comment]
+1

I would like to be involved as well.

**Comment by arthur-r-oliveira** [comment]
+1

I would like to be involved as well.

**Comment by ramrodo** [comment]
+1
Interesed in helping :)

**Comment by bryan-strassner** [comment]
+1, Very interested in the aspects of getting 3rd party community (e.g., CNI) support aligned with LTS timelines as well.
