### ISSUE TITLE
Issue with k8s.io/releases/release/

### ISSUE THREAD

**Issue by dockerhk1203** [kubernetes/community#7273]
Release cycle diagram is not aligned with the release and at the bottom of the diagram release version should be upcoming next but still old is written.
For example:
if it starts with 1.24 then it should be: 1.24, .125, 1.26 and then last should be 1.27, but in the document 1.26 is written.

Release plan should be described in more details because current description doesn't talk much about life cycle. At one place it says 14 months patch support but in diagram only 8 months are visible.

**Comment by reylejano** [comment]
I agree with Tim that the diagram does not need to be current but it's an example. If the diagram is to be current (which I'm not suggesting) I prefer a programmatic way like using a mermaid diagram with a short code for the release version

**Comment by Princesso** [comment]
Since this issue has been transferred to a different repo, do we need to close it here?

**Comment by Ritikaa96** [comment]
> Since this issue has been transferred to a different repo, do we need to close it here?

No we can't close this issue as this exist only in this repo after the transfer
