### ISSUE TITLE
Typo in keps/sig-api-machinery/1281-network-proxy

### ISSUE THREAD

**Issue by gonzalovazquez** [kubernetes/community#7274]
### Describe the issue

Small typo from on the documentation for 1281 network-proxy

Currently:
 We assume that for HTTP URL request,s it will be the proxy which does the DNS lookup. 

Expected:
We assume that for HTTP URL requests it will be the proxy which does the DNS lookup.

**Comment by Swapnil-2502** [comment]
> ### Describe the issue
> Small typo from on the documentation for 1281 network-proxy
> 
> Currently: We assume that for HTTP URL request,s it will be the proxy which does the DNS lookup.
> 
> Expected: We assume that for HTTP URL requests it will be the proxy which does the DNS lookup.

Please could you give the exact file path because I cannot find the typo.

**Comment by Swapnil-2502** [comment]
lease could you give the exact file path because I cannot find the typo.

**Comment by Swapnil-2502** [comment]
Please could you give the exact file path because I cannot find the typo.

**Comment by Swapnil-2502** [comment]
Okay so the typo is in kubernetes/enhancements not in kubernetes/community

**Comment by T-Lakshmi** [comment]
@gonzalovazquez, @Swapnil-2502,
Can you provide the exact file path/url for this issue.

/triage needs-information

**Comment by T-Lakshmi** [comment]
**Page to update:** [keps/sig-api-machinery/1281-network-proxy](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1281-network-proxy#proposal)

Moving it to `kubernetes/enhancents` as this issue is related to enhancements repository.

/transfer enhancements

**Comment by Swapnil-2502** [comment]
@T-Lakshmi Just ignore this issue and move to another issue.

**Comment by satyampsoni** [comment]
Is the issue still open to work on?

**Comment by Swapnil-2502** [comment]
@satyampsoni Don't think so this issue is still open.

**Comment by T-Lakshmi** [comment]
Hey @satyampsoni, @Swapnil-2502,
I still see this issue exist [Here](https://github.com/kubernetes/enhancements/edit/master/keps/sig-api-machinery/1281-network-proxy/README.md#proposal). 

[PR](https://github.com/kubernetes/enhancements/pull/4024) that addressed this issue got closed without merge the changes.
So welcome to anyone if you are interested to fix this issue.
