### ISSUE TITLE
Hyperlink for `in-place-updates` under API changes is broken

### ISSUE THREAD

**Issue by sarkar-deb** [kubernetes/community#7283]
### Describe the issue

Hyperlink for `in-place-updates` under API changes is broken
Currently 'in-place-update' under [API changes](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md) is been routed to an invalid url address (https://kubernetes.io/docs/user-guide/managing-deployments/#in-place-updates-of-resources) which gives 404 error.

**Comment by satyampsoni** [comment]
What is the status of this issue?

**Comment by sarkar-deb** [comment]
Fixed but not merged yet.

**Comment by dipesh-rawat** [comment]
Fix merged as part of https://github.com/kubernetes/community/pull/7284

/close
