### ISSUE TITLE
Incorrect links in contributors/devel

### ISSUE THREAD

**Issue by vaibhav2107** [kubernetes/community#7302]
### Describe the issue

There are some incorrect links in different folders under the [contributors/devel](https://github.com/kubernetes/community/tree/master/contributors/devel)

These are listed as:

Under [sig-cli,](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-cli/kubectl-conventions.md)
> but this is a nice convention so try to be compliant with it. As an example, have a look at how [kubectl logs](https://git.k8s.io/kubernetes/pkg/kubectl/cmd/logs/logs.go) is implemented.

Under [sig-scheduling](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-scheduling/scheduling_code_hierarchy_overview.md),
> Or custom plugins may be provided instead of the default ones. Known consumers of the scheduling framework:
> 
> [cluster-autoscaler](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/simulator/scheduler_based_predicates_checker.go#L48-L79)

Under [sig-testing](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/writing-good-e2e-tests.md):
> The framework provides some [common timeouts](https://github.com/kubernetes/kubernetes/blob/eba98af1d8b19b120e39f3/test/e2e/framework/timeouts.go#L44-L109) through the [framework instance](https://github.com/kubernetes/kubernetes/blob/1e84987baccbccf929eba98af1d8b19b120e39f3/test/e2e/framework/framework.go#L122-L123). When writing a test, check whether one of those fits before defining a custom timeout in the test.

**Comment by divya-mohan0209** [comment]
Hello @kumiDa and @vaibhav2107 , please note that this issue is not related to the official Kubernetes documentation or SIG Docs. The changes need to be made in the files for the respective SIGs. Untagging SIG Docs from this issue since changes aren't being made to our SIG's files.
/remove-sig docs
