### ISSUE TITLE
Request: Create a new repository as Github actions home across all sigs

### ISSUE THREAD

**Issue by helayoty** [kubernetes/community#7316]
### Describe the issue

There is a frequent ask across many sigs to use Github actions. While enabling Github actions in the k/k repo has some obstacles, sigs started to create their repos to host them, i.e., [sig-auth-tools](https://github.com/kubernetes-sigs/sig-auth-tools), [sig-release request](https://github.com/kubernetes/org/issues/4170#issuecomment-1562242396), and [sig-scheduling request](https://github.com/kubernetes/org/issues/4218#issuecomment-1561794301). 

Therefore, we propose creating one repo in the `Kubernetes-sigs` org to host all sigs Github actions across all sigs. This will be a huge step toward making the efforts from all sigs reusable with no redundant work, and it also will be better to maintain this effort in one place.

The proposed repo,aka `sigs-github-actions`, structure can be:
 
- .gitbub
  - sig-auth
     - OWNERS.  //sig-leads, github-admins
     - sample.yaml
  - sig-scheduling
  - ...
- pkg
  - general 
  - sig-auth
    - OWNERS   //sig-leads, github-admins
    - sample.go
  - sig-scheduling
  - ...

@kubernetes/sig-contributor-experience-leads @mrbobbytables @nikhita 

CC: @kubernetes/sig-auth-leads @kubernetes/sig-scheduling-leads @kubernetes/sig-release-leads

**Comment by alculquicondor** [comment]
/sig contributor-experience

+1 from SIG Scheduling

**Comment by alculquicondor** [comment]
Actually, I think this is the wrong repo for this issue. It should be in https://github.com/kubernetes/org

**Comment by helayoty** [comment]
@alculquicondor I created it here based on [this](https://kubernetes.slack.com/archives/C1TU9EB9S/p1684986264317809?thread_ts=1684984449.453749&cid=C1TU9EB9S) slack conversation.

**Comment by Priyankasaggu11929** [comment]
@helayoty, thanks for starting the discussion.

Considering how (re-usable) GH actions are currently being used & maintained in different SIG repos, bringing them together into a single repo makes a lot of sense.

This also lines up with the reasons mentioned in https://github.com/kubernetes/org/issues/4218#issuecomment-1563133382

> I do think consolidating makes sense - it also means the repo owners (likely github admins) could rapidly make a change if one is implemented in an insecure way

+1 from SIG Contribex.

The next step would be to update the [already open issue description](https://github.com/kubernetes/org/issues/4218) to reflect the request for a new repo owned by contribex. Thank you!

**Comment by helayoty** [comment]
> +1 from SIG Contribex.
> 
> The next step would be to update the [already open issue description](https://github.com/kubernetes/org/issues/4218) to reflect the request for a new repo owned by contribex. Thank you!

The issue has been updated :) https://github.com/kubernetes/org/issues/4218

**Comment by MadhavJivrajani** [comment]
+1 
This would indeed make things simpler and more secure to maintain, thank you @helayoty!

**Comment by Priyankasaggu11929** [comment]
The repo has been created here: https://github.com/kubernetes-sigs/sigs-github-actions

Ref: https://github.com/kubernetes/org/issues/4218#issuecomment-1592401322

Closing this issue. Thanks!

/close
