### ISSUE TITLE
Migrate various Zapier jobs to new contributors@ account

### ISSUE THREAD

**Issue by chris-short** [kubernetes/community#7334]
Myself and Nigel (maybe others?) are hosting several Zapier tasks for the project that need to be migrated into the "official" Zapier account.

**Comment by chris-short** [comment]
/assign pnbrown

Nigel offered to take a look at everything the other day. I want to make sure that gets tracked somewhere.

**Comment by pnbrown** [comment]
The Zoom Automation is moved over and functioning as of this morning for SIG ContribEx

**Comment by chris-short** [comment]
Yes!

Thank you for polishing it up and getting it moving.
