### ISSUE TITLE
SIG Testing: Leadership Change

### ISSUE THREAD

**Issue by michelle192837** [kubernetes/community#7346]
### SIG/WG name:

Testing

### Onboarding Lead(s):

jbpratt

### Offboarding Lead(s):

stevekuznetsov

### Link to discussion:

https://groups.google.com/a/kubernetes.io/g/dev/c/Tmr4c_O7fTA

### Prerequisites for new leads:

- [X] Are a [Kubernetes Org member](https://git.k8s.io/community/community-membership.md)
- [X] Have completed the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Onboarding / Offboarding tasks:

- [x] Updated [sigs.yaml](https://git.k8s.io/community/sigs.yaml) and associated [generated files](https://git.k8s.io/community/generator) (ran `make`). **NOTE:** If offboarding, remember to add to emeritus.
- [x] Updated [OWNERS_ALIASES](https://git.k8s.io/org/OWNERS_ALIASES) in [kubernetes/org](https://git.k8s.io/org/).
- [x] Updated [milestone maintainers team](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml) in [kubernetes/org](https://git.k8s.io/org/).
- [x] Checked for and updated any other potential teams in [kubernetes/org](https://git.k8s.io/org/).
- [ ] Updated [OWNERS_ALIASES](https://git.k8s.io/enhancements/OWNERS_ALIASES) in [kubernetes/enhancements](https://github.com/kubernetes/enhancements).
- [x] Updated [OWNERS_ALIASES](https://git.k8s.io/k8s.io/OWNERS_ALIASES) in [kubernetes/k8s.io](https://git.k8s.io/k8s.io/).
- [x] Updated [membership](https://git.k8s.io/k8s.io//groups/groups.yaml) of the [leads mailing list](https://groups.google.com/a/kubernetes.io/g/leads)
- [x] Updated membership for any other [mailing list / groups](https://git.k8s.io/k8s.io//groups/).
- [x] Added to `#chairs-and-techleads` slack channel.
- [x] Updated ownership of group leads mailing list.
- [x] Updated ownership of group mailing list.
- [x] Updated ownership of group calendar.
- [ ] Updated access/teams in 1password. (Contact ContribEx leads to complete)

### Labels:

/sig testing
/assign me
/cc @jbpratt @xmcqueen

**Comment by xmcqueen** [comment]
Thanks M, Is this waiting on some action from me, or is this an informational cc?

**Comment by michelle192837** [comment]
Mostly informational, though if you can and want to approve some of these PRs that'd be excellent ^^

**Comment by michelle192837** [comment]
The linked PRs should cover everything in the checklist now, except the group calendar and 1Password.
