### ISSUE TITLE
REQUEST: New Slack <[channel|usergroup|bot|token|webhook]> <[channel|usergroup|bot|token|webhook] name>

### ISSUE THREAD

**Issue by kaiyee0** [kubernetes/community#7348]
### GitHub Username

@kaiyee0

### Slack Username

Kay Lin

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

Channel

### Name of Requested Resource

kubernetes-docs-tw

### Description of Request

Create a Slack channel for Traditional Chinese (zh-tw) docs localiztion.

/sig docs
/language zh-tw

**Comment by coderanger** [comment]
Closing this as the associated PRs was rejected by SIG-Docs.

/close
