### ISSUE TITLE
KubeCon Contributor Summit NA 2023 - Team Staffing

### ISSUE THREAD

**Issue by pnbrown** [kubernetes/community#7354]
The 2023 NA Contributor Summit in Chicago will need staffing for its roles and shadows. The Contributor Summit will take place on Monday, November 6, 2023 at McCormick Place West in Chicago, Illinois, USA. Planning meetings occur on Mondays at [9 AM Pacific/11 AM Central](https://dateful.com/convert/pst-pdt-pacific-time?t=09). Meeting notes can be found [here](https://docs.google.com/document/d/1-NOX5KBi3aKHkNrdXoHg8zWHAcargYaqjhsttkQmmRY/edit).

Event Leads will be @pnbrown and @jberkus with help from @qedrakmar. The Lead Shadow position is currently vacant.

We will also need shadows that could potentially take on leading those roles in the future. Roles and shadows will be listed below when they are filled out. With limited exception, shadows must have Kubernetes org membership. Shadows will be accepted at the discretion of the lead.

Edit: 
1. To clarify roles and responsibilities we are adding a role of "Volunteer" under each area. The Shadow bears expectations to lead one of the events-team roles in an upcoming summit and to handle all lead related activities in the absence of the Lead. It may be helpful to think of the Shadow role as an understudy position. Volunteers are helpers that may be assigned tasks from the Lead. Shadows and Volunteers, with limited exception, must be members of the Kubernetes GitHub organization. Leads are still responsible for accepting shadows and volunteers for their area. Volunteers, please communicate your desire to be a Shadow to the Lead of your area. Leads will inform me of their Shadows and I will update the issue.

2. We have a strong preference that participants as Leads, Shadows, and Volunteers be present at the Contributor Summit to help on site. This does not mean you cannot help virtually. There will be opportunities and we encourage you to come to the planning meetings in order to find virtual opportunities.
Thank you for your willingness to help out. We could not hold these events without you.

- [Registration](https://github.com/kubernetes/community/blob/master/events/events-team/registration/README.md)
  - Lead: @tokt 
  - Shadow: @reylejano @stmcginnis
  - Volunteers: 
  - Emeritus Lead: @palnabarun 
- [Awards](https://github.com/kubernetes/community/blob/master/events/awards/playbook.md)
  - Lead: @jrsapi 
  - Shadow: @salaxander 
  - Volunteers:
  - Emeritus Lead: @reylejano 
- [Content](https://github.com/kubernetes/community/blob/master/events/events-team/content/README.md)
  - Lead: @cailynse 
  - Shadow: @fykaa 
  - Volunteers: 
- [Comms](https://github.com/kubernetes/community/blob/master/events/events-team/marketing/README.md)
  - Lead: @AvineshTripathi 
  - Shadow: @SD-13 @chris-short
  - Volunteers: 
- Social Event
  - Lead:  @nitishfy
  - Shadow: @kendallnelson 
  - Volunteers: 
- Day-of Operations
  - Lead: @natalisucks 
  - Shadow: @savitharaghunathan @ameukam @qnetter
  - Volunteers: @cpanato @kaslin @puja108 @a-mccarthy @kendallnelson 
- [SIG Meet & Greet](https://github.com/kubernetes/community/blob/master/events/events-team/content/meet-and-greet.md)
  - Lead: @nimbinatus 
  - Shadow: @kaslin @chris-short 
  - Volunteers: @RA489

(Umbrella issue not created yet)
/assign @pnbrown @jberkus @qedrakmar 
/sig contributor-experience
/area contributor-summit
/area na-summit

**Comment by reylejano** [comment]
I can be emeritus for Awards and would like to shadow Registration

**Comment by natalisucks** [comment]
I'd be happy to take on the lead for Day-of Operations, after having chatted with @fsmunoz (who was lead for Day-of Operations in Amsterdam '23).

@pnbrown Can we get a link to the handbook for that role?

**Comment by pnbrown** [comment]
Thanks so much for leading that section, @natalisucks. 

If I recall correctly, one of the gaps we found last time was that we did not have a Day-of-Operations playbook. We're hoping to work with the Ops lead and leads of past to create one this time.

**Comment by pnbrown** [comment]
> I can be emeritus for Awards and would like to shadow Registration

I've added you as Emeritus for awards and inform whoever the Reg lead is that you are interested in shadowing there. Thank you!

**Comment by qedrakmar** [comment]
> @pnbrown Can we get a link to the handbook for that role?

I am in the process of writing that handbook, @natalisucks

**Comment by RA489** [comment]
I can be sig Meet and greet shadow.

**Comment by pnbrown** [comment]
Thank you @RA489. We will let the lead know once we have one.

**Comment by jberkus** [comment]
Hmmm.  Apparently we need a Social Event Handbook too.  I can write that, it'll be short.

**Comment by jberkus** [comment]
Meet & Greet has a handbook, @pnbrown please link it?  

https://github.com/kubernetes/community/blob/master/events/events-team/content/meet-and-greet.md

**Comment by pnbrown** [comment]
That's now linked @jberkus!

**Comment by tokt** [comment]
Will be happy to help with Registration or Awards or shadow anywhere else. )

**Comment by nitishfy** [comment]
Hi, I'd love to work with Content and Comms:)

**Comment by ameukam** [comment]
Happy to be a shadow for Operations. :-)

**Comment by nimbinatus** [comment]
I can lead the M&G as the co-lead from Amsterdam if no one else would rather step up (if someone wants to take lead and let me be emeritus, I'll happily shadow PM).

**Comment by jrsapi** [comment]
@tokt and I both shadowed under Awards with @reylejano in Detroit. I would like to suggest Mars or myself lead Awards in Chicago. 
I'm also interested in shadowing for Day of Ops or SIG Meet and Greet depending on who leads Awards.

**Comment by cailynse** [comment]
I can lead Content this time around after shadowing in Amsterdam

**Comment by ronitblenz** [comment]
@pnbrown I would love to shadow for Registration

**Comment by pnbrown** [comment]
Hi @ronitblenz, thank you for volunteering. With limited exception, shadows must be members of the Kubernetes organization. When the planning meetings start up, join us there or in the regular [Sig-ContribEx Bi-weekly call](https://docs.google.com/document/d/1CBz8qV_mD6rbDmTsMuosTOQGRXGhN3d8UrcULUI6Vkw/edit) and let's chat.

**Comment by ronitblenz** [comment]
Thanks @pnbrown I am an active contributor at cncf. Where can I get the planning meet details? I will definitely be joining that.

**Comment by pnbrown** [comment]
We're looking forward to seeing you there. The planning meetings have not begun yet. I will update the issue when they do.

**Comment by rgunaseknokia** [comment]
Happy to be shadow for Day of Operations

**Comment by pnbrown** [comment]
Hi @rgunaseknokia, thank you for volunteering. With limited exception, shadows must be members of the Kubernetes organization. When the planning meetings start up, join us there or in the regular [Sig-ContribEx Bi-weekly call](https://docs.google.com/document/d/1CBz8qV_mD6rbDmTsMuosTOQGRXGhN3d8UrcULUI6Vkw/edit) and let's chat.

**Comment by nitishfy** [comment]
> @nitishfy are you volunteering for lead or wanting to shadow?

wanting to be shadow

**Comment by rgunaseknokia** [comment]
Hi @pnbrown Thank you for your response! 
FYI - I was part of Day of Operations team with Federico Munoz during KubeCon EU 2023!

**Comment by savitharaghunathan** [comment]
I'd like to be shadow for content and help with Day-of Operations.

**Comment by sandipanpanda** [comment]
Hi, I'd like to be a shadow for Comms and help with Content.

**Comment by Ileriayo** [comment]
Hi. Is there any opportunity for virtual contributors? 👀

**Comment by Kikiodazie** [comment]
Hey @cailynse, 

I am a Technical writer, and I would love to be one of the helpers for the Content team.

**Comment by pnbrown** [comment]
Hi Folks,
After the SIG-Contributor Experience meeting yesterday, we are rolling out a couple updates.

1. To clarify roles and responsibilities we are adding a role of "Volunteer" under each area. The Shadow bears expectations to lead one of the events-team roles in an upcoming summit and to handle all lead related activities in the absence of the Lead. It may be helpful to think of the Shadow role as an understudy position. Volunteers are helpers that may be assigned tasks from the Lead. Shadows and Volunteers, with limited exception, must be members of the Kubernetes GitHub organization. Leads are still responsible for accepting shadows and volunteers for their area. Volunteers, please communicate your desire to be a Shadow to the Lead of your area. Leads will inform me of their Shadows and I will update the issue.
2. We have a strong preference that participants as Leads, Shadows, and Volunteers be present at the Contributor Summit to help on site. This does not mean you cannot help virtually. There will be opportunities and we encourage you to come to the planning meetings in order to find virtual opportunities.

Thank you for your willingness to help out. We could not hold these events without you.

**Comment by ronitblenz** [comment]
@pnbrown I am open to work as a volunteer to any suitable role the Admins and you want. I am willing to work on site in summit as well if needed. Given that, I will be available virtually too. I tried to join yesterday's meeting but unfortunately I missed it due to timezone miscalculations. Looking forward to join the next meeting and contribute.

**Comment by palnabarun** [comment]
I can be emeritus to registrations if needed.

**Comment by Kikiodazie** [comment]
Hey @cailynse, @pnbrown, 

I am a Technical writer, and I would love to be one of the volunteers for the Content team. I will be On-site in Chicago.

**Comment by chris-short** [comment]
I will happily shadow comms

**Comment by kaslin** [comment]
Happy to lead comms. @chris-short if you want to co-lead, that's probably a thing.

**Comment by AvineshTripathi** [comment]
Happy to lead comms!

**Comment by amirrmonfared** [comment]
I will be happy to contribute with remote opportunities for this summit where shadows available 🙂

**Comment by amirrmonfared** [comment]
I would gladly participate in remote opportunities for this summit, making the most of the available resources and contributing my skills and knowledge with enthusiasm 🙂

**Comment by kaslin** [comment]
> Happy to lead comms!   

@chris-short and I would be happy for Avinesh to take on comms! We can be there to help him if he needs anything but he knows what he's doing.

**Comment by pnbrown** [comment]
I will make that adjustment

**Comment by RohanSasne** [comment]
Hey @pnbrown , I am interested in volunteering for KubeCon, If there are any virtual opportunities available then please consider my application :)

**Comment by jberkus** [comment]
If someone wants to be the Social Event Lead, I can advise/support you

**Comment by tokt** [comment]
Confirming @reylejano and @stmcginnis as shadows for Registration with @palnabarun as emeritus.

**Comment by geojaz** [comment]
I'd be happy to help out with the Summit if there's a place I can slot in! I'm planning to be on site

**Comment by fykaa** [comment]
Grateful to have stumbled upon this open issue, thanks to @kaslin for directing me here. 

I am enthusiastically interested in take the shadow role within the content creation or communications team. But, I remain open to exploring other shadowing roles too.

**Comment by nitishfy** [comment]
> If someone wants to be the Social Event Lead, I can advise/support you

I'd like to take up the responsibility for the Social Event lead.

**Comment by stmcginnis** [comment]
Happy to just be volunteer for Registration, but also willing to take on Shadow.

**Comment by pnbrown** [comment]
Oh goodness. I put those on the wrong line. Will adjust.

**Comment by pnbrown** [comment]
Hi folks!
We're going to be starting planning meetings on Monday July 10th.

Planning meetings occur on Mondays at [9 AM Pacific/11 AM Central](https://dateful.com/convert/pst-pdt-pacific-time?t=09). Meeting details and notes can be found [here](https://docs.google.com/document/d/1-NOX5KBi3aKHkNrdXoHg8zWHAcargYaqjhsttkQmmRY/edit). Please also join the #summit-staff channel in the Kubernetes workspace.

**Comment by Nageshbansal** [comment]
I'd like to volunteer or shadow for the registration or awards.

**Comment by SD-13** [comment]
Update: I would like to shadow comms

**Comment by natalisucks** [comment]
Confirming @savitharaghunathan and @ameukam as shadows for Day-of Operations – would be happy to accept further help from Kubernetes org members on site during the summit 😸 ✨

**Comment by natalisucks** [comment]
Adding @qnetter as another shadow for Day-of Operations!

**Comment by rgunaseknokia** [comment]
@natalisucks Happy to shadow for Day-of-Ops

**Comment by natalisucks** [comment]
> @natalisucks Happy to shadow for Day-of-Ops

Hey Rajesh! Once you've been able to secure org membership, then we can get you signed up to contribute for the event. I want to note that Day-of Ops folks especially need to be org members, and while I understand you were on-site for the last event, the requirements have slightly changed this time around. Feel free to go through some of the SIG channels on Slack to see where your contributions would be needed and what good first issues you'd be able to help with 👍

**Comment by natalisucks** [comment]
Me again! Am confirming that @cpanato has expressed their interest in being a volunteer for Day-of Ops, lets goooo

**Comment by Kikiodazie** [comment]
Hey @natalisucks,

I would love to volunteer for Content. Would that be possible?

**Comment by pnbrown** [comment]
Hi @Kikiodazie,
Thank you for your interest. I see your request to volunteer for content higher in the thread. Please allow the content lead @cailynse some more time to process the request. Note that we have a preference that folks who are volunteering and shadowing have Kubernetes org membership. Feel free to join us in the planning meetings linked in the issue as well to find more ways to get involved.

**Comment by cailynse** [comment]
Confirming @savitharaghunathan and @fykaa for Content shadows!

@Kikiodazie - for shadows we need org membership, but feel free to join the next planning meeting to learn more about volunteering opportunities! You can the invite by joining the [contributor experience mailing list](https://groups.google.com/g/kubernetes-sig-contribex).

**Comment by Kikiodazie** [comment]
> Confirming @savitharaghunathan and @fykaa for Content shadows!
> 
> @Kikiodazie - for shadows we need org membership, but feel free to join the next planning meeting to learn more about volunteering opportunities! You can the invite by joining the [contributor experience mailing list](https://groups.google.com/g/kubernetes-sig-contribex).

Thank you very much for this feedback @cailynse, I have joined the mailing list. Looking forward to learning more.

**Comment by Kikiodazie** [comment]
> Hi @Kikiodazie, Thank you for your interest. I see your request to volunteer for content higher in the thread. Please allow the content lead @cailynse some more time to process the request. Note that we have a preference that folks who are volunteering and shadowing have Kubernetes org membership. Feel free to join us in the planning meetings linked in the issue as well to find more ways to get involved.

Thank you @pnbrown.

**Comment by AvineshTripathi** [comment]
Confirming @SD-13, @chris-short for comms shadow(Chris as Super shadow). Anyone interested in helping us feel free to ping.

**Comment by chris-short** [comment]
Super Shadow in the sense of shadowing two things to make sure both happen now and in the future.

**Comment by ronitblenz** [comment]
> Confirming @SD-13, @chris-short for comms shadow(Chris as Super shadow). Anyone interested in helping us feel free to ping.

I am interested to help in any way possible.

**Comment by krmayankk** [comment]
I can help in any ways possible, including co-host, comms, or any other help you need

**Comment by AvineshTripathi** [comment]
Lets do this then @ronitblenz! Would love to have you as volunteer

**Comment by ronitblenz** [comment]
> Lets do this then @ronitblenz! Would love to have you as volunteer 

Great! Would love to know the tasks and the next steps.

**Comment by Rishit-dagli** [comment]
Hey @cailynse, if you need another pair of hands for content, I was volunteering as a shadow at the last contrib summit which was really interesting and I would love to help out again.

**Comment by khareyash05** [comment]
Hi @jrsapi  I would love to volunteer in the Awards Section for the Kubecon

**Comment by khareyash05** [comment]
> Confirming @SD-13, @chris-short for comms shadow(Chris as Super shadow). Anyone interested in helping us feel free to ping.

Hi @AvineshTripathi i I would love to volunteer for the Kubecon in anyway possible. I was working as a volunteer for GDG Noida(India), GDSC WOW Delhi NCR and will be working as a volunteer at Pycon 2023

**Comment by rgunaseknokia** [comment]
> > @natalisucks Happy to shadow for Day-of-Ops
> 
> Hey Rajesh! Once you've been able to secure org membership, then we can get you signed up to contribute for the event. I want to note that Day-of Ops folks especially need to be org members, and while I understand you were on-site for the last event, the requirements have slightly changed this time around. Feel free to go through some of the SIG channels on Slack to see where your contributions would be needed and what good first issues you'd be able to help with 👍

Hey @natalisucks @pnbrown 
I am happy to volunteer for Day-Of-Ops as I was volunteering as a shadow at the last contrib summit @ Amsterdam... I thoroughly enjoyed it and love to do it once again!

**Comment by cailynse** [comment]
@Rishit-dagli confirmed as shadow for content - ty!!

We are now full!

**Comment by jberkus** [comment]
@pnbrown please add @cici37 as co-leading the Social with @nitishfy

**Comment by natalisucks** [comment]
Confirming further volunteers for Day-of Operations: @kaslin and @puja108 🎉 Also noting that @mrbobbytables is a stand-in for Day-of Ops needs, should we require more hands on deck

**Comment by olivercodes** [comment]
Didn't see any confirmations on my offer to shadow wherever needed, if anyone still needs help let me know!

**Comment by shivanshu1333** [comment]
Can shadow for comms

**Comment by a-mccarthy** [comment]
Hey all, I'd like to volunteer to help with Registration or day off operations :) (i'm also open to helping other areas if those groups have enough volunteers)

**Comment by pnbrown** [comment]
> Didn't see any confirmations on my offer to shadow wherever needed, if anyone still needs help let me know!

Thanks @olivercodes. I will mention that in today's meeting

**Comment by khareyash05** [comment]
hi @pnbrown I can also volunteer for any shadow position.Kindly let me know

**Comment by craiglpeters** [comment]
I'm happy to volunteer for the social event!

**Comment by kendallnelson** [comment]
Happy to shadow for registration!

**Comment by nitishfy** [comment]
Hi, anyone would be interested in shadowing for Social Lead?
cc: @craiglpeters @kendallnelson

**Comment by khareyash05** [comment]
hi @nitishfy I would like to shadow

**Comment by pnbrown** [comment]
@kendallnelson I put you down for both :)
