### ISSUE TITLE
Add some examples of improper submitted issues

### ISSUE THREAD

**Issue by satyampsoni** [kubernetes/community#7382]
### Describe the issue

While going through the "development.md" file on GitHub (link: https://github.com/kubernetes/community/blob/master/contributors/devel/development.md), I came across the guidelines on how to raise performance improvement issues. The document provides information on three specific issues that are considered proper for raising performance-related concerns. After reviewing these issues, I gained a rough understanding of how such problems should be reported for performance testing. However, I couldn't find any information regarding the improper ways to publish these issues. It would be helpful to have a list of improper issues as well, as it would provide clarity to readers.
That can be added below this section
![image](https://github.com/kubernetes/community/assets/94950988/25c5637f-dc2a-4dce-9db8-337281e6dbe4)

**Comment by divya-mohan0209** [comment]
This is not related to the official Kubernetes documentation or SIG Docs and is related to contributor experience. Please tag the relevant SIG.
