### ISSUE TITLE
REQUEST: New Slack webhook for EKS Prow build cluster alerting

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/community#7383]
### GitHub Username

@xmudrii

### Slack Username

@xmudrii

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

Webhook

### Name of Requested Resource

Alertmanager for EKS Prow build cluster

### Description of Request

We implemented alerting for EKS Prow build cluster owned by SIG K8s infra in https://github.com/kubernetes/k8s.io/pull/5516

The alerting stack is currently pointing to Kubermatic's internal Slack in order to unblock the progress, but as this is a community cluster, alerts should be going to the community (Kubernetes) Slack.

Alertmanager requires a webhook so that it can send alerts to. Here's an example of configuring such a webhook: https://docs.kubermatic.com/kubermatic/v2.23/tutorials-howtos/monitoring-logging-alerting/user-cluster/setting-up-alertmanager-with-slack-notifications/

cc @kubernetes/sig-k8s-infra-leads

**Comment by ameukam** [comment]
cc @jberkus @coderanger @mrbobbytables

**Comment by ameukam** [comment]
+1 with k8s-infra hat.

**Comment by jeefy** [comment]
+1 with slack-admin hat on :) 

/assign

**Comment by ameukam** [comment]
@jeefy @xmudrii Is it possible to have this stored in an 1password vault ?

**Comment by xmudrii** [comment]
@ameukam I stored it in AWS Secrets Manager in Prow account, but I can add it to 1Password as well.

**Comment by ameukam** [comment]
> @ameukam I stored it in AWS Secrets Manager in Prow account, but I can add it to 1Password as well.

Preferable to have this in a 1password vault.

**Comment by dims** [comment]
Yes please add to the 1password vault.

**Comment by xmudrii** [comment]
@ameukam @dims Added to the Boskos Credentials vault. I don't have access to any other vault, so please move to better place if needed.

**Comment by dims** [comment]
i can access that one @xmudrii thanks! will leave it to @ameukam if that location is ok or needs to be moved
