### ISSUE TITLE
Slackbot is still broken

### ISSUE THREAD

**Issue by kaslin** [kubernetes/community#7389]
We had a convo in slack during the week of March 31st. Folks want to use the Slackbot for KubeCon comms, and we're once again noticing that we lack documentation on the Slackbot. #sig-contribex-comms in Slack. @SD-13 is taking on the investigation into this.

**Comment by kaslin** [comment]
These links probably have something to do with this: https://github.com/kubernetes/k8s.io/tree/main/apps/slack-infra/resources/slack-post-message
https://github.com/kubernetes-sigs/slack-infra/tree/main/slack-post-message https://github.com/kubernetes/k8s.io/tree/main/apps/slack-infra/resources/slack-post-message

**Comment by chris-short** [comment]
/sig contributor-experience

It seems the bot works, but it's not in all the channels we need it in.

**Comment by kaslin** [comment]
Thank you @SD-13 for tracking this information down and putting a good amount of work into getting it working again by adding it to all of the channels!
