### ISSUE TITLE
Create an "automation" folder in the Contributor Comms repo

### ISSUE THREAD

**Issue by kaslin** [kubernetes/community#7400]
### What do you want send out?(Please include a link to a draft)

Create a new folder called "Automation" for information about SlackBot, Zapier automation, etc. Owned by Contrib Comms subproject tech lead.

**Comment by kaslin** [comment]
@chris-short suggested making some cool diagrams! That would be great!

**Comment by chris-short** [comment]
Yes!
I've got to make some time to make diagrams.
