### ISSUE TITLE
REQUEST: New Private Slack Channel kustomize-training-cohort

### ISSUE THREAD

**Issue by annasong20** [kubernetes/community#7401]
### GitHub Username

@natasha41575

### Slack Username

@natasha41575

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

Channel

### Name of Requested Resource

kustomize-training-cohort

### Description of Request

The [kustomize](https://github.com/kubernetes-sigs/kustomize) team would like to request a Slack channel for our [maintainer-training cohort](https://groups.google.com/g/kubernetes-sig-cli/c/grJUVFKrOO4/m/CuYfrRlrBQAJ?utm_medium=email&utm_source=footer).

**Comment by mrbobbytables** [comment]
@annasong20 if you'd like, please go ahead and open a PR to add the channel. SIG requests pretty much have blanket approval unless its REALLY out there.

**Comment by rayandas** [comment]
@annasong20 would you mind if I go ahead and quickly raise a PR to add the channel?

**Comment by natasha41575** [comment]
@rayandas Thanks for the offer, we really appreciate the enthusiasm. However, I think creation of the private channel should probably come from an existing kustomize maintainer/cohort lead. @annasong20 please go ahead and create the PR whenever you can.

**Comment by mrbobbytables** [comment]
One FYI - private channels are broadly a 'no' unless there is an extremely good reason to create them with the exception that we DO create them for mentor cohorts with the intention of spinning them down once its done.

**Comment by annasong20** [comment]
@mrbobbytables Really appreciate the context.
@natasha41575 Will do.

**Comment by mrbobbytables** [comment]
To confirm - this is a private channel request for the knative mentor cohort?

If yes, lgtm from me as a slack admin, would just need another slack admin to +1 as well.

**Comment by natasha41575** [comment]
> To confirm - this is a private channel request for the knative mentor cohort?

Kustomize, not knative, but yes. Who are the other slack admins? Should we try to reach out to someone?

**Comment by mrbobbytables** [comment]
er yeah, sorry - brainfart

**Comment by annasong20** [comment]
> Just a note, we should probably call it kustomize-training-cohort instead of kustomize-maintainers

Just changed title and description of this issue.

**Comment by annasong20** [comment]
> To confirm - this is a private channel request for the knative mentor cohort?
> 
> If yes, lgtm from me as a slack admin, would just need another slack admin to +1 as well.

@mrbobbytables added you as reviewer to #7411

**Comment by coderanger** [comment]
Slash approve from me :) Just make sure to notify us when you are done with the training sessions.

**Comment by mrbobbytables** [comment]
Channel has been created - @natasha41575 @annasong20 you both have been added 👍

**Comment by annasong20** [comment]
Thank you so much @mrbobbytables!
