### ISSUE TITLE
Mentorship cohort for ExternalDNS subproject

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#7402]
### Describe the issue

Opening an issue so that we don't let this go forever:

The four maintainers of ExternalDNS are largely working on other things these days.  We really need to look at getting group mentorship going for them so that the outgoing maintainers can train some successors.

/sig network
/sig contributor experience
/area mentoring

attn: @Raffo @szuecs

**Comment by Raffo** [comment]
Thank you for opening this @jberkus , I appreciate it. Let me know if there is anything I can add here.

**Comment by sandipanpanda** [comment]
Hi, I would like to be a mentee in this effort given the opportunity.

**Comment by satyampsoni** [comment]
Hi @jberkus, are you still looking for interns?
