### ISSUE TITLE
Incorrect "More about this" link in CKA Simulator Answers

### ISSUE THREAD

**Issue by cyril-ui-developer** [kubernetes/community#7428]
### Describe the issue

The. Question 23 - Kubelet client/server cert info "More about this" link redirects to the 404 page.  See attached:

![Screenshot 2023-07-28 at 6 46 54 PM](https://github.com/kubernetes/community/assets/15249132/a6381b2d-61bf-4094-9a83-d5530e73c88d)
![Screenshot 2023-07-28 at 6 57 06 PM](https://github.com/kubernetes/community/assets/15249132/a7b540e2-7d54-4336-a8d9-9d266ab47003)

I would like to fix this issue.

**Comment by mrbobbytables** [comment]
We have no control over the CKA simulator,  you should reach out to whoever owns it to fix.

/close
