### ISSUE TITLE
Broken links in running-locally.md

### ISSUE THREAD

**Issue by vaibhav2107** [kubernetes/community#7434]
### Describe the issue

Related to the community docs, In [contributors/devel/running-locally.md](https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md) under section **[Running a user defined pod](https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md#running-a-user-defined-pod)** contains the broken link:

> Note the difference between a [container](https://kubernetes.io/docs/user-guide/containers/) and a [pod](https://kubernetes.io/docs/user-guide/pods/). Since you only asked for the former, Kubernetes will create a wrapper pod for you. However, you cannot view the nginx start page on localhost

Page to update: https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md

**Comment by divya-mohan0209** [comment]
This is not related to SIG Docs and/or the official Kubernetes documentation. Please tag the relevant SIG.
/remove-sig docs

**Comment by mrbobbytables** [comment]
/sig contributor-experience
PR is about to be merged so going to go ahead and close this.

/close
