### ISSUE TITLE
Steering Committee Nomination : Divya Mohan (@divya-mohan0209)

### ISSUE THREAD

**Issue by divya-mohan0209** [kubernetes/community#7447]
### Describe the issue

Hi Kubernetes Community,

My name is Divya Mohan & I’m self-nominating for the upcoming Steering Committee elections in 2023.

I’ve had the wonderful opportunity to learn from all of you in the course of my day-to-day work over the last three years.

Some of my work, in the context of the Kubernetes community, is listed below.

- [SIG Docs co-chair](https://github.com/kubernetes/community/tree/master/sig-docs#chairs)
- [Co-organizer of Kubernetes Community Days, Mumbai](https://kcdmumbai.com/)
- [Co-led the creation & review of Kubernetes and Cloud Native Associate (KCNA) Certification Exam](https://github.com/cncf/curriculum/issues/50)
- [CNCF Ambassador](https://www.cncf.io/people/ambassadors/?p=divya-mohan)
- [Curator of the Kubeweekly newsletter](https://www.cncf.io/kubeweekly/)
- Served on program committees for KubeCon + CloudNativeCon  (community, 101, observability, student) as track chair & reviewer (2021 - present day)
- [Speaker at various Kubernetes Community Days and KubeCon + CloudNativeCon](https://github.com/divya-mohan0209/talks)
- Ex-release team [lead shadow](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.22/release-team.md), [comms lead](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.21/release-team.md), [comms shadow](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.20/release_team.md), and [docs shadow](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.19/release_team.md)

I would be honored to continue helping improve governance, contributor sustainability and nurture an inclusive, diverse, and open community by serving as a Steering Committee member.

Thanks,
Divya

/committee steering

**Comment by nikhita** [comment]
+100 🚀 

Employer: VMware

**Comment by reylejano** [comment]
+1
Employer: SUSE

Among the many contributions Divya listed above, Divya has led Cloud Native Wasm day on multiple occasions

**Comment by MadhavJivrajani** [comment]
Huge +1! ♥️
Employer: VMware

**Comment by natalisucks** [comment]
The easiest +1 ever! ❤️ 
Employer: Cisco

**Comment by aojea** [comment]
+1
Employer: Google

**Comment by rikatz** [comment]
+1
Employer:VMware

**Comment by savitharaghunathan** [comment]
+1
Employer: Red Hat

**Comment by RinkiyaKeDad** [comment]
Huge +1

Employer: Okteto

**Comment by bridgetkromhout** [comment]
Divya Mohan has the necessary endorsements and is eligible to run in the Steering Committee election.  The candidate should prepare their candidate profile as a PR and submit it, per the instructions at: https://github.com/kubernetes/community/blob/master/elections/steering/2023/README.md#candidacy-process

**Comment by endocrimes** [comment]
+1

Employer: Independent

**Comment by divya-mohan0209** [comment]
Thank you everyone for your +1's.

@bridgetkromhout : Thank you so much for your confirmation. I've linked the PR to this issue per instructions.

**Comment by ydFu** [comment]
+1 for @divya-mohan0209 
We are partners contributing to SIG Docs together.

**Comment by Atharva-Shinde** [comment]
Late here,
But still a big +1!

**Comment by gracenng** [comment]
+1 and hugs
Employer: independent

**Comment by xing-yang** [comment]
+1
Employer: VMware
