### ISSUE TITLE
Fix typo in mentoring readme

### ISSUE THREAD

**Issue by letmerecall** [kubernetes/community#7452]
### Describe the issue

# What's the issue?

There's a small TODO comment that's not rendered correctly.

https://github.com/kubernetes/community/blob/7a0e1f6c8276f884bd789a0eba9e3d6935027c04/mentoring/README.md#L21

# How to fix it?

To use markdown comment syntax: `<!-- string.... -->`

**Comment by mrbobbytables** [comment]
It's desired that the TODO is visible. That sort of style has been used elsewhere, it was just a marker to show there's a separation there.

/close

**Comment by letmerecall** [comment]
Oops, apologies for that :(

**Comment by letmerecall** [comment]
At least that helped me get started with the CLA. :)
