### ISSUE TITLE
Steering Committee Nomination: Noah Abrahams (@qedrakmar)

### ISSUE THREAD

**Issue by qedrakmar** [kubernetes/community#7456]
### Describe the issue

Hello kubernetes community,

I would like to self-nominate for the Kubernetes Steering Committee election in 2023.

I have been involved with this project since 2016, focused almost entirely on community growth and contributor health.  I want to do even more for this community, leaning into the culture that makes this project so successful.  Recognizing the type of work that Steering does, I feel this is the most impactful place for me to do that work for all of you.

Many of you know me, and you’ve seen me working behind the scenes, enabling others and doing the work that helps you get ahead.  I have done that work in many places in the project, but mostly with SIG ContibEx.  You’ve seen me running the Contributor Summit, leading the Non-Code Contributors initiative, and really anything else I can do to make you and the project as successful as possible.

/committee steering

**Comment by MadhavJivrajani** [comment]
+1!

Employer: VMware

**Comment by jeremyrickard** [comment]
+1

Employer: Microsoft

**Comment by bridgetkromhout** [comment]
Noah Abrahams has the necessary endorsements and is eligible to run in the Steering Committee election. The candidate should prepare their candidate profile as a PR and submit it, per the instructions at: https://github.com/kubernetes/community/blob/master/elections/steering/2023/README.md#candidacy-process

**Comment by savitharaghunathan** [comment]
+1
