### ISSUE TITLE
Steering Committee Nomination: Maciej Szulik (@soltysh)

### ISSUE THREAD

**Issue by eddiezane** [kubernetes/community#7457]
Hi Kuberfriendos,

I am privileged to nominate Maciej Szulik, aka @soltysh, for the 2023 Steering Committee election. This is the 3rd time I've asked Maciej if I may nominate him, and he has finally obliged 😅.

You may know Maciej as the second tallest member of SIG-CLI, where he has served as a leader since 2018, or the Cron Job guy from SIG-Apps and WG-Batch, but did you know his [first PR](https://github.com/kubernetes/kubernetes/pull/3065) to the project was in December of 2014? It was to bump the version of spf13/cobra, which has since become a rite of passage among SIG-CLI.

I first met Maciej at KubeCon EU 2018 in Copenhagen, and over the past 5 years, he has gone from someone I was afraid to talk to about contributing, to an incredible mentor, to a co-lead, to a true friend.

To me, Maciej is a true representative of the culture of the project. Finding new contributors to take under his wing, elevating voices, hosting mentorship cohorts, advocating for inclusion, or making the correct decisions over the easy ones.

I believe Maciej will be an exceptional service leader to the community, and I look forward to the positive impact he will have.

If you agree, please +1 this issue.

/committee steering

**Comment by jeefy** [comment]
A hearty +1 from me

**Comment by endocrimes** [comment]
+1 from me

Employer: independent

**Comment by jeremyrickard** [comment]
+1 from me

Employer: Microsoft

**Comment by brianpursley** [comment]
+1 without a doubt!

**Comment by rikatz** [comment]
+1 * 100000!!
Employer: VMware

**Comment by shivanshu1333** [comment]
+1 from me

**Comment by dgrisonnet** [comment]
+1
Employer: Red Hat

**Comment by soltysh** [comment]
I accept the nomination :smile:

**Comment by erikgb** [comment]
+1

**Comment by mpuckett159** [comment]
+1

**Comment by feloy** [comment]
+1
Red Hat

**Comment by dinhxuanvu** [comment]
+1

**Comment by alculquicondor** [comment]
+1
Google

**Comment by reylejano** [comment]
+1
Employer: SUSE

**Comment by helayoty** [comment]
A huge hearty +1 from me. Maciej is just amazing, helpful, knowledgeable, too much experienced lead that you will learn a lot from working with him. 

Employer: Microsoft

**Comment by bridgetkromhout** [comment]
Maciej Szulik has the necessary endorsements and is eligible to run in the Steering Committee election. The candidate should prepare their candidate profile as a PR and submit it, per the instructions at: https://github.com/kubernetes/community/blob/master/elections/steering/2023/README.md#candidacy-process

**Comment by aojea** [comment]
+1
Employer:Google

**Comment by atiratree** [comment]
+1
Employer: Red Hat

**Comment by seans3** [comment]
+1
Employer: Google

**Comment by Atharva-Shinde** [comment]
Huge +1!

**Comment by MadhavJivrajani** [comment]
Huge +1!
Maciej embodies our community's values to the highest level ♥️

Employer: VMware

**Comment by mehabhalodiya** [comment]
Big +1!
Maciej put so much effort into SIG CLI and in other ways too (especially I love how he actively participates in the mentoring cohorts and share his valuable experience and knowledge with the newbies); speaking on what I have learned from him. 
Thank you so much @soltysh for what you have done for the community ❤️ 

Employer: Red Hat

**Comment by natalisucks** [comment]
+1!
Employer: Cisco

**Comment by droslean** [comment]
+1

Employer: Red hat

**Comment by p0lyn0mial** [comment]
+1
Employer: Red Hat

**Comment by ardaguclu** [comment]
+1
Employer: Red Hat

**Comment by varshaprasad96** [comment]
Huge +1
Employer: RedHat

**Comment by sbueringer** [comment]
+1
Employer: VMware

**Comment by stlaz** [comment]
+1
Employer: Red Hat

**Comment by s-urbaniak** [comment]
+1
Red Hat

**Comment by elmiko** [comment]
+1
Employer: Red Hat

**Comment by rphillips** [comment]
+1
Red Hat

**Comment by jberkus** [comment]
+1 (even though it doesn't count).

I've been trying to get Maciej to run for a couple years.

**Comment by mengjiao-liu** [comment]
+1
DaoCloud

**Comment by ydFu** [comment]
+1 thanks

**Comment by nikhita** [comment]
Very big +1
Employer: VMware

**Comment by a-hilaly** [comment]
+1

**Comment by savitharaghunathan** [comment]
+1

**Comment by TommyStarK** [comment]
+1

**Comment by Huang-Wei** [comment]
+1
Employer: Apple
