### ISSUE TITLE
Update the sig docs

### ISSUE THREAD

**Issue by kumarankit999** [kubernetes/community#7467]
### Describe the issue

In the below Picture, as you can see that the Contact list is appearing but is not accessible and the GitHub team is not reachable.

![image](https://github.com/kubernetes/community/assets/111564362/6276b3dc-a31e-4af7-a2dc-ef3eb3ac2285)

We Can either Update the list or we can Remove completely the GitHub team list

```[tasklist]
### Tasks
```

**Comment by mrbobbytables** [comment]
The team memberships are visible to other k8s org members 👍 
For their intended purpose the teams can be pinged on github.

/clsoe
