### ISSUE TITLE
Steering Committee Nomination: Patrick Ohly (@pohly)

### ISSUE THREAD

**Issue by pohly** [kubernetes/community#7473]
### Describe the issue

Hello Kubernetes community,

I would like to self-nominate for the Kubernetes Steering Committee election in 2023.

I have been involved with Kubernetes since 2018. I’ve worked on a variety of topics covering several different SIGs (Storage, Testing, Instrumentation, Node, Scheduling). Enhancements that I have designed and implemented include:
-  Generic Ephemeral Volumes (GA)
- Storage Capacity Tracking (GA)
- Contextual Logging (alpha)
- Dynamic Resource Allocation (alpha)

As tech lead in SIG Testing for the E2E framework and working group lead for structured logging I am responsible for changes that [affect all contributors](https://www.kubernetes.dev/blog/2023/04/12/e2e-testing-best-practices-reloaded/) of Kubernetes. I care about code quality and some of you might remember my initiative to enable [stricter pre-merge linting](https://groups.google.com/a/kubernetes.io/g/dev/c/myGiml72IbM/m/QdO5bgQiAQAJ) (coming real soon now, I promise!).

I have presented at KubeCon ([2019](https://kccncosschn19eng.sched.com/event/NrmX/e2e-testing-real-developers-dont-test-but-they-should-patrick-ohly-intel), [2020](https://kccncna20.sched.com/event/ekFE/persistent-memory-in-kubernetes-patrick-ohly-intel), [2023](https://kccnceu2023.sched.com/event/1Hzcr/keeping-the-lights-on-and-the-bugs-away-patrick-ohly-intel)), contributed to the Kubernetes blogs ([2022](https://www.kubernetes.dev/blog/2022/05/25/contextual-logging/ ), [2023](https://www.kubernetes.dev/blog/2023/04/12/e2e-testing-best-practices-reloaded/))  and received awards for my contributions to Kubernetes ([2021](https://www.kubernetes.dev/community/awards/2021/), [2022](https://www.kubernetes.dev/community/awards/2022/), [2023](https://opensource.googleblog.com/2023/05/google-open-source-peer-bonus-program-announces-first-group-of-winners-2023.html)). I am working with the maintainers of components that Kubernetes depends on (Ginkgo/Gomega, golangci-lint, forbidigo, and last but not least Go itself) to ensure that they meet the needs of Kubernetes.

The conversion of logging to contextual, structured logging is an area where I have helped various new developers with their first contributions to Kubernetes. Finding and retaining new contributors is an on-going challenge. My goal is that by joining the steering committee I’ll be able to serve the project also in a less technical role.

/committee steering

**Comment by szuecs** [comment]
+1

**Comment by Xunzhuo** [comment]
+1

**Comment by gyohuangxin** [comment]
+1

**Comment by shivanshu1333** [comment]
A big +1
for all the contributions and hardwork Patrick has been putting into kubernetes and mentoring the new contributors!

**Comment by askervin** [comment]
+1

**Comment by yuzhiquan** [comment]
+1

**Comment by erikgb** [comment]
+1

**Comment by MadhavJivrajani** [comment]
Huge +1 ♥️
Employer: VMware

**Comment by aojea** [comment]
+1
Employer: Google

**Comment by mengjiao-liu** [comment]
+1
DaoCloud

**Comment by chendave** [comment]
+1 for @pohly !

**Comment by klueska** [comment]
+1
Employer: NVIDIA

**Comment by mowangdk** [comment]
+1
Employer: AlibabaCloud

**Comment by cofyc** [comment]
+1

**Comment by soltysh** [comment]
+1
Employer: Red Hat

**Comment by a-hilaly** [comment]
+1

**Comment by savitharaghunathan** [comment]
+1

**Comment by coulof** [comment]
+1
Employer: Dell Technologies

**Comment by sbueringer** [comment]
+1
Employer: VMware

**Comment by reylejano** [comment]
+1
Employer: SUSE

**Comment by charles-chenzz** [comment]
big +1

**Comment by dobsonj** [comment]
+1
Red Hat

**Comment by chrishenzie** [comment]
+1
Employer: Google

**Comment by SergeyKanzhelev** [comment]
+1
Employer: Google

**Comment by ydFu** [comment]
+1

**Comment by Huang-Wei** [comment]
+1
Employer: Apple

**Comment by bridgetkromhout** [comment]
Patrick Ohly has the necessary endorsements and is eligible to run in the Steering Committee election. The candidate should prepare their candidate profile as a PR and submit it, per the instructions at: https://github.com/kubernetes/community/blob/master/elections/steering/2023/README.md#candidacy-process

**Comment by atiratree** [comment]
+1
Employer: Red Hat

**Comment by elmiko** [comment]
+1
Employer: Red Hat

**Comment by saad-ali** [comment]
+1
Employer: Google

**Comment by aimuz** [comment]
+1

**Comment by humblec** [comment]
Huge +1

**Comment by rjsadow** [comment]
+1
Employer: iCR

**Comment by pacoxu** [comment]
+1
Employer: DaoCloud

**Comment by lalitasy29** [comment]
+1
