### ISSUE TITLE
Steering Committee Nomination: Arnaud Meukam (@ameukam)

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes/community#7497]
### Describe the issue

Hello kubefolx!

I would like to nominate Arnaud Meukam (@ameukam) for the 2023 Steering Committee election! 

Arnaud does a lot for the project across a bunch of different areas. I first got to know Arnaud in *2018* when [we shadowed Bug Triage on the Kubernetes 1.12 Release Team](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.12/release_team.md)! Since then, I've had the pleasure of working  with him in [SIG Release](https://kubernetes.io/releases/release-managers/) and have had the opportunity to see him grow in [SIG K8s Infra](https://github.com/kubernetes/community/blob/master/sig-k8s-infra/README.md). You might also know him from the recent [move to registry.k8s.io](https://www.youtube.com/watch?v=9CdzisDQkjE) or may have seen him working at the [contributor summit](https://github.com/kubernetes/community/issues/6734)!  

I believe that Arnaud cares deeply about the sustainability of the Kubernetes project, has a history of working across SIGs on important issues and I think that he would make an excellent member of the steering committee. 

Please join me in nominating Arnaud to the Steering Committee by adding a +1 to this issue! 

/committee steering

**Comment by rikatz** [comment]
+1
Employer: VMware

**Comment by endocrimes** [comment]
a thousand +1's.

Employer: Independent

**Comment by xing-yang** [comment]
+1
Employer: VMware

**Comment by qedrakmar** [comment]
+1
Employer: Oracle

**Comment by detiber** [comment]
+1
Employer: Cisco

**Comment by reylejano** [comment]
+1
Employer: SUSE

**Comment by bridgetkromhout** [comment]
Arnaud Meukam has the necessary endorsements and is eligible to run in the Steering Committee election (but does need to accept this nomination explicitly in a comment from @ameukam or implicitly by submitting the profile PR). The candidate should prepare their candidate profile as a PR and submit it, per the instructions at: https://github.com/kubernetes/community/blob/master/elections/steering/2023/README.md#candidacy-process

**Comment by aojea** [comment]
+1
Employer: Google

**Comment by rjsadow** [comment]
+1
Employer: iCR

**Comment by upodroid** [comment]
+1 

Employer: Cisco

**Comment by natalisucks** [comment]
+1
Employer: Cisco

**Comment by ameukam** [comment]
I accept the nomination!

**Comment by jimangel** [comment]
+1 (Google)

**Comment by savitharaghunathan** [comment]
+1 
Red Hat

**Comment by soltysh** [comment]
+1
Employer: Red Hat

**Comment by sbueringer** [comment]
+1
Employer: VMware

**Comment by chrischdi** [comment]
+1
Employer: VMware
