### ISSUE TITLE
Steering Committee Nomination: Stephen Augustus (@justaugustus)

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/community#7498]
Hey Kubernetes Community,

I'd like to self-nominate to continue my service on the Kubernetes Steering Committee.

I have had the honor of holding governance roles within this project since 2018 (Kubernetes 1.11), across a variety of areas including Steering Committee, SIG Release, SIG PM, SIG Azure, and Working Group Naming.

In that time, I've been mentored by paragons of servant leadership and have endeavored to model that behavior for the governance groups I help maintain, as well as the emerging leaders I have the great opportunity to collaborate with.

Some highlights of my community resume:

- Senior Release Manager
- Served on multiple Release Teams
- Recruited for multiple Release Teams
- Co-creator of the:
  - Release Team role handbooks (which have modeled roles & responsibilities for several areas of the project)
  - Kubernetes Enhancement Proposals (KEP)
  - Release Engineering subproject
  - Working Group Naming
- Facilitator of multiple project donations including Cluster API Azure
- Former New Membership Coordinator

Outside of Kubernetes, I have established myself as a trusted leader across multiple open source projects and initiatives including:

- Co-founder of Inclusive Naming Initiative
- Former Chair for CNCF TAG Contributor Strategy
- Former Program Chair of KubeCon/CloudNativeCon
- Former Steering Committee member for TODO Group
- Current OpenSSF Governing Board member
- Current OpenAPI Initiative Board member
- Current maintainer for OpenSSF Scorecard and CNCF's Dex
- International keynote speaker

All that said, Kubernetes is my first love and I would be delighted to be considered to continue my work here.

If you are an eligible voter interested in endorsing me, you can do so by replying to this nomination issue saying something like "I endorse this nominee, and I work for " or "+1". Please state that you are an eligible voter, and include your employer's name so that Election Officers can recognize qualified endorsements.

Best,
Stephen

/committee steering

**Comment by jeremyrickard** [comment]
+1 

Employer: Microsoft

**Comment by detiber** [comment]
+1 from me as a qualified voter, my employer is Cisco

**Comment by droslean** [comment]
+1 

I am a qualified voter and my employer is Redhat.

**Comment by xing-yang** [comment]
+1
I am a qualified voter and my employer is VMware.

**Comment by qedrakmar** [comment]
+1
I am a qualified voter and my employer is Oracle.

**Comment by reylejano** [comment]
+1 from me. I am a qualified voter and my employer is SUSE

**Comment by celestehorgan** [comment]
+1 I hear that Stephen guy is cool!

**Comment by bridgetkromhout** [comment]
Stephen Augustus has the necessary endorsements and is eligible to run in the Steering Committee election. The candidate should prepare their candidate profile as a PR and submit it, per the instructions at: https://github.com/kubernetes/community/blob/master/elections/steering/2023/README.md#candidacy-process

**Comment by a-hilaly** [comment]
+1

I am a qualified voter and my employer is AWS.

**Comment by upodroid** [comment]
+1

I am a qualified voter and my employer is Cisco

**Comment by natalisucks** [comment]
+1 ❤️ 
I am a qualified voter and my employer is Cisco

**Comment by jimangel** [comment]
+1 (Google)

**Comment by savitharaghunathan** [comment]
+1
Red Hat

**Comment by soltysh** [comment]
+1
Employer: Red Hat

**Comment by justaugustus** [comment]
Thanks for the endorsements, everyone!
