### ISSUE TITLE
Steering Committee Nomination: Jason DeTiberus (@detiber)

### ISSUE THREAD

**Issue by detiber** [kubernetes/community#7500]
Hello kubernetes community,

I would like to self-nominate for the Kubernetes Steering Committee election in 2023.

I have been involved in the greater Kubernetes community since 2015. Most folks likely know me through the work that I've done in SIG Cluster Lifecycle and Cluster API, where I helped drive features and improvements to enable real world production use. More importantly, I helped build the community around Cluster API, including breaking down barriers between competing projects and companies, enabling wide scale adoption of Cluster API as the default solution for building Kubernetes lifecycle management tooling.

Throughout my time in the community, I've also tried to find additional ways to give back to the community that has provided so many opportunities for me. From work in SIG Contributor Experience, where I have helped with staffing for the Contributor Summit, to most recently serving on the Code of Conduct Committee.

Just has my career has evolved from product engineering towards open source program management, my community involvement has also followed a similar arc, moving from serving in more engineering oriented roles towards more community and governance work. 

If you are an eligible voter interested in endorsing me, you can do so by replying to this nomination issue saying something like "I endorse this nominee, and I work for " or "+1". Please state that you are an eligible voter, and include your employer's name so that Election Officers can recognize qualified endorsements.

Thank you,
Jason DeTiberus

/committee steering

**Comment by qedrakmar** [comment]
+1
I am an eligible voter and my employer is Oracle.

**Comment by celestehorgan** [comment]
Not sure what my org status is these days but +1! :D

**Comment by bridgetkromhout** [comment]
> Not sure what my org status is these days but +1! :D

@celestehorgan You appear in the voters file for this year, so you are eligible to vote without needing to apply for an exception: https://github.com/kubernetes/community/blob/master/elections/steering/2023/voters.yaml#L107

**Comment by bridgetkromhout** [comment]
Jason DeTiberus has the necessary endorsements and is eligible to run in the Steering Committee election. The candidate should prepare their candidate profile as a PR and submit it, per the instructions at: https://github.com/kubernetes/community/blob/master/elections/steering/2023/README.md#candidacy-process

**Comment by upodroid** [comment]
+1 

Employer: Cisco

**Comment by celestehorgan** [comment]
Thanks @bridgetkromhout 😻

**Comment by natalisucks** [comment]
+1 ❤️ 
I am a qualified voter and my employer is Cisco

**Comment by ameukam** [comment]
+1

Employer: VMware

**Comment by jimangel** [comment]
+1 (Google)

**Comment by savitharaghunathan** [comment]
+1 
Red Hat

**Comment by soltysh** [comment]
+1
Employer: Red Hat

**Comment by elmiko** [comment]
i know it's closed, but happy to see the nomination!
+1
Red Hat

**Comment by detiber** [comment]
Thanks folks, I'm truly honored to have your support :)
