### ISSUE TITLE
Steering Committee Nomination: Natali Vlatko (@natalisucks)

### ISSUE THREAD

**Issue by natalisucks** [kubernetes/community#7503]
Hi Kubernetes folks,

I’m choosing to self-nominate for the Kubernetes Steering Committee.

I’ve been publicly vocal about the lack of global representation on the Steering Committee several times in the past, as well as there being very little gender diversity. I want to make sure I’m showing a bias to action with the feedback I’m giving and my own expectations of our community and leadership. In short, I’m attempting to live up to my own expectations by running this cycle.

So, who is Natali?

I’m one of the chairs of SIG Docs, and am admittedly newer to the community than most. I helped launch the official Localization Subproject after the amazing work of our emeritus and current localization leads. Today, Kubernetes documentation is available in 15 different languages, with more on the way. I’ve also been involved in staffing the Kubernetes Contributor Summits, and have helped SIG Auth with bug triage and the prep work needed for gathering contributors to various KEPs.

In the larger cloud native landscape, I’ve been on the Program Committee for KubeCon/CloudNativeCon and Open Source Summit for several years, as well as being recently featured in the [2023 Kubernetes Project Journey Report](https://www.cncf.io/reports/kubernetes-project-journey-report/). I like having the stage hand role, where I help the star achieve their best – that star is the Kubernetes project and its community of contributors and maintainers. I want you to put me to work.

If you’re awake at this incredibly inconvenient time in IST, CET, CST (and others!), or hanging out in North America during daylight hours, and you’d like to endorse me, please do so by replying to this nomination issue. Please state that you are an eligible voter, and include your employer's name and a "+1" so that Election Officers can recognize qualified endorsements. A big thanks in advance for your plus ones and thumbs up.

Cheers,
Natali

/committee steering

**Comment by detiber** [comment]
+1

I am a qualified voter employed by Cisco

**Comment by qedrakmar** [comment]
+1

I am an eligible voter, and my employer is Oracle.

**Comment by reylejano** [comment]
+1 from me and I am eligible to vote
Employer: SUSE

**Comment by bridgetkromhout** [comment]
Natali Vlatko has the necessary endorsements and is eligible to run in the Steering Committee election. The candidate should prepare their candidate profile as a PR and submit it, per the instructions at: https://github.com/kubernetes/community/blob/master/elections/steering/2023/README.md#candidacy-process

**Comment by jimangel** [comment]
+1 (Google)

**Comment by savitharaghunathan** [comment]
+1 
Red Hat

**Comment by soltysh** [comment]
+1
Employer: Red Hat

**Comment by divya-mohan0209** [comment]
Huugggeee +1 💜
Employer: SUSE

**Comment by mtardy** [comment]
+1 😃
Employer: Isovalent

**Comment by celestehorgan** [comment]
Natali is incredibly cool! +1

**Comment by upodroid** [comment]
+1
Employer: Cisco

**Comment by Raffo** [comment]
+1
Employer: GitHub
