### ISSUE TITLE
Does  sig-architecture still owns sippy?

### ISSUE THREAD

**Issue by chansuke** [kubernetes/community#7504]
### Describe the issue

In the README of [k8s.iio](https://github.com/chansuke/k8s.io#k8sio), `sippy` is described as:

> owned by [sig-architecture](https://git.k8s.io/community/sig-architecture)

However, in the [subprojects](https://github.com/kubernetes/community/tree/master/sig-architecture#subprojects) section of `sig-architecture`, there is no mention of `sippy`.

Is `sippy` still owned by `sig-architecture`?

**Comment by mrbobbytables** [comment]
@chansuke your question is unlikely to get answered in this repo. I'd email the sig-arch list, ask in their slack or ask in the k8s.io repo.

**Comment by chansuke** [comment]
@mrbobbytables  Thank you for your comment.I will ask in the k8s.io repo.
