### ISSUE TITLE
feat: Updating the pull request template

### ISSUE THREAD

**Issue by Viveksati5143** [kubernetes/community#7522]
### Describe the issue

On my way to make my first contribution in CNCF under 0 to merge cohort by @onlydole, while navigating I found out that the pull request template has been outdated and the last activity was 4 years ago in this community repo itself
https://github.com/kubernetes/community/blob/master/.github/PULL_REQUEST_TEMPLATE.md

So, it can be updated to provide more information on many aspects.

Also, I would like to work in this issue as my first contribution in cloud native
/assign @Viveksati5143
```[tasklist]
### Tasks
```

**Comment by Viveksati5143** [comment]
Hey @liggitt @cblecker 
Can you please have a quick look at this issue?

**Comment by cblecker** [comment]
I don't understand the ask. Why do we need to update the PR template for this repo?

cc @MadhavJivrajani @Priyankasaggu11929 @nikhita

**Comment by Viveksati5143** [comment]
Why not? would love to heear from you...

**Comment by cblecker** [comment]
We typically try to identify the problem, before proposing a solution. If there is a problem you're aware of, please let us know. If there isn't a problem, then there's no need for an update simply because the file hasn't been updated.

**Comment by Viveksati5143** [comment]
Not really a problem but trying to make it better
.
Maybe we can add like What new changes does this pr do?
&
Screenshot of change or something?

**Comment by mrbobbytables** [comment]
I don't think there's really anything to make it better.^^;;
 The community repo is pretty light weight in terms of PR needs.

**Comment by cblecker** [comment]
Yeah, we don't need any changes unless there's a specific need/request.
/close

**Comment by Viveksati5143** [comment]
Sure, thanks for the suggestions.
