### ISSUE TITLE
Multiple broken links at README.md file of sig-docs repo

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/community#7528]
### Describe the issue

Line 69 to 85, all links are broken and redirecting to 404 error page.

![Screenshot (676)](https://github.com/kubernetes/community/assets/116108975/482d6084-e82b-43b4-b2b6-be4a88712d9e)

**Comment by mrbobbytables** [comment]
They are not broken, you must be a member of the kubernetes org to view them.

/close
