### ISSUE TITLE
KubeCon NA 2023: Meet the Kubernetes Contributor Community signups (previously SIG Meet & Greet)

### ISSUE THREAD

**Issue by nimbinatus** [kubernetes/community#7541]
Since SIG Meet and Greet has been added to KubeCon proper, we have had difficulty being discovered in the overall KubeCon schedule. For KubeCon NA 2023, we are renaming SIG Meet and Greet to Meet the Kubernetes Contributor Community (MKCC) to help with discoverability.

Accordingly, MKCC is scheduled for Thursday, November 9 from 12:00pm - 3:00pm.

If your SIG is interested in having a table, please comment on this thread. We will update this top post as time goes by with participating groups.

Current participating community groups (alphabetical by committee, then by SIG, then by WG):
- SIG API Machinery - @jpbetz
- SIG Apps - @soltysh 
- SIG Auth - @enj @liggitt @deads2k @aramase
- SIG Autoscaling - @gjtempleton
- SIG CLI - @soltysh 
- SIG Cloud Provider - @elmiko
- SIG Cluster Lifecycle - @fabriziopandini @CecileRobertMichon @nrb @sbueringer
- SIG Contributor Experience - @kaslin @nimbinatus @chris-short @MadhavJivrajani 
- SIG Docs - @reylejano @divya-mohan0209 (after maintainer session) @natalisucks (after maintainer session)
- SIG etcd - @serathius @jmhbnz
- SIG Instrumentation - @logicalhan
- SIG Kubernetes Infrastructure - @thockin @BenTheElder @ameukam @upodroid 
- SIG Network - @thockin @danwinship @youngnick
- SIG Node - @SergeyKanzhelev (after 12:45p or so)
- SIG Release - @jrsapi @ameukam @jeremyrickard @katcosgrove
- SIG Scheduling - @Huang-Wei
- SIG Storage - @xing-yang  (maybe @msau42)
- SIG Testing - @BenTheElder @aojea @upodroid 
- WG Batch - @soltysh
- WG Data Protection - @xing-yang
- WG LTS -@jeremyrickard @youngnick
- WG Policy - @JimBugwadia @rajkrishnamurthy @brandtkeller @JonZeolla @sudermanjr

/assign @nimbinatus @chris-short @kaslin
/sig contributor-experience
/area contributor-summit
/area na-summit

**Comment by jpbetz** [comment]
I'll be there to represent SIG API Machinery

**Comment by kaslin** [comment]
I plan to be there for SIG ContribEx.

**Comment by nimbinatus** [comment]
I'll be there for ContribEx, too :)

**Comment by aojea** [comment]
add SIG Network and SIG Testing please,

**Comment by enj** [comment]
Add @enj @liggitt @deads2k @aramase for SIG Auth 😁

**Comment by thockin** [comment]
I'll be there, but I am not sure if the whole time is free or not, yet.

**Comment by thockin** [comment]
Is there a location assigned?  I don't see this on the main schedule site

**Comment by nimbinatus** [comment]
@thockin it will be in W-470AB - Level 4. A hiccup happened when the name was getting changed and it fell off the Sched somehow. CNCF is looking into it.

**Comment by SergeyKanzhelev** [comment]
I will be part of time for SIG-Node. Have a talk till 12:30-ish

**Comment by divya-mohan0209** [comment]
I intend to be there for SIG Docs.
Cc: @reylejano @natalisucks

**Comment by reylejano** [comment]
I'll be there for SIG Docs also
cc @divya-mohan0209 @natalisucks

**Comment by JimBugwadia** [comment]
I'll be there for WG Policy - @JimBugwadia 

cc: @rficcaglia

**Comment by rajkrishnamurthy** [comment]
I will be there for WG Policy - Raj Krishnamurthy 
cc: @JimBugwadia @rficcaglia

**Comment by brandtkeller** [comment]
I'll be there for WG Policy - @brandtkeller
cc: @JimBugwadia @rficcaglia

**Comment by JonZeolla** [comment]
I'll be there for WG Policy - @jonzeolla

cc: @JimBugwadia @rficcaglia 😀

**Comment by natalisucks** [comment]
I'll be there for the second half of the event to represent SIG Docs (my maintainer track talk with @divya-mohan0209 is at the same time, hence the broken up availability).
@reylejano will be there so that there is always a chair/TL for the entire session – thanks Rey! ❤️

**Comment by divya-mohan0209** [comment]
> I intend to be there for SIG Docs. Cc: @reylejano @natalisucks

I intend to be there for SIG Docs after the maintainer session as mentioned in [this comment](https://github.com/kubernetes/community/issues/7541#issuecomment-1741720103) by @natalisucks

**Comment by chris-short** [comment]
I _should_ be there for SIG ContribEx

**Comment by nimbinatus** [comment]
Update: The CNCF fixed the Sched to include the event on the schedule, so if you need to bookmark it: https://sched.co/1T2qK

**Comment by fabriziopandini** [comment]
I will be there for SIG Cluster Lifecycle

**Comment by logicalhan** [comment]
I will be there for SIG Instrumentation.

**Comment by jrsapi** [comment]
In for SIG-Release.

**Comment by CecileRobertMichon** [comment]
I'll be there for SIG Cluster Lifecycle as well

**Comment by nrb** [comment]
I will also be there for SIG Cluster Lifecycle

**Comment by elmiko** [comment]
i'll be there for SIG Cloud Provider

**Comment by serathius** [comment]
I will be there from SIG etcd

**Comment by BenTheElder** [comment]
I will be there for Testing/Infra.

**Comment by ameukam** [comment]
I will there for Infra/Release

**Comment by upodroid** [comment]
I'll be there for Infra/Testing

**Comment by sbueringer** [comment]
I will be there for SIG Cluster Lifecycle

**Comment by gjtempleton** [comment]
I'll be there for SIG Autoscaling

**Comment by jeremyrickard** [comment]
I'll be there for Release and happy to be there for WG-LTS too.

**Comment by youngnick** [comment]
I will be there to talk SIG-Network Gateway API stuff and WG-LTS if need be.

**Comment by jmhbnz** [comment]
I will be there for SIG etcd

**Comment by MadhavJivrajani** [comment]
Will be there for ContribEx! ❤️

**Comment by katcosgrove** [comment]
I'll be there for SIG Release!

**Comment by elmiko** [comment]
sadly, due to unexpected circumstances i won't be able to attend. :sob:

**Comment by nimbinatus** [comment]
We're sorry we missed you, @elmiko!

**Comment by nimbinatus** [comment]
This event has concluded. Thank you, everyone, for coming out!
