### ISSUE TITLE
<Broken link> sig-release folder

### ISSUE THREAD

**Issue by satyampsoni** [kubernetes/community#7548]
### Describe the issue

![image](https://github.com/kubernetes/community/assets/94950988/2d0095a3-97b3-4de8-9f08-274ead8b31e9)
The above Hyperlinks mentioned in the image are not working.

Page to fix : https://github.com/kubernetes/community/tree/master/sig-release

/sig-release

**Comment by mrbobbytables** [comment]
They work,  you must be an org member to view them.

/close
