### ISSUE TITLE
The Atlassian git tutorial link not works 

### ISSUE THREAD

**Issue by kumarankit999** [kubernetes/community#7578]
### Describe the issue

The Atlassian git tutorial is not working in English, It goes on a 404 page, while it works on another localization.

Source: https://github.com/kubernetes/community/blob/master/contributors/guide/contributor-cheatsheet/README.md

```[tasklist]
### Tasks
```

**Comment by AmarNathChary** [comment]
I opened the exact site from Atlassian by searching in Google it was working fine. but don't know why this hyperlink from GitHub is not working. I checked both URLs from the hyperlink and from direct Google both were the same.

**Comment by AmarNathChary** [comment]
It is only not working from the source of GitHub. it is working fine in the actual documentation.

**Comment by kumarankit999** [comment]
Yes, you are right @AmarNathChary

**Comment by AmarNathChary** [comment]
Yeah. you can close this issue I think there is nothing to fix.
