### ISSUE TITLE
Disable kind: Endpoints, use kind: EndpointSlices instead

### ISSUE THREAD

**Issue by ChristianBieri1995** [kubernetes/community#7594]
Dear SIG Network community,

Since K8s V1.21, EndpointSlices are stable. According to my understanding, they replace/extend the Endpoints object in order to solve the scalability issues which resulted from using Endpoints. Therefore, I strongly assume that Endpoints are no longer needed anymore. As a result, I guess (based on the fact that EndpointSlices are stable/in use) that one could disable the Endpoints object within the K8s cluster? Not having both objects anymore results in reduced complexity/lesser objects and hopefully lesser traffic within the cluster (since Endpoints no longer need updates).

To do so, I stumbled over https://kubernetes.io/docs/tasks/administer-cluster/enable-disable-api/ to disable K8s APIs. Unfortunately, though, it seems that one only can disable /v1 (core API group which consists of Endpoints). Since I would also disable many other K8s APIs, this does not make sense. 

Is there a possibility to solve this issue? How do other K8s administrators handle this? Does it even make sense to disable Endpoints or can one simply ignore their creation/existence?

I am really looking forward to your questions/solutions.

Wishes,
Chris

**Comment by aojea** [comment]
See Rule 4a of https://kubernetes.io/docs/reference/using-api/deprecation-policy/ , we maintain backwards compatibility and  Endpoint functionality is there and there is people and projects that still use them, removing them will break them.

What I don't understand what you want to disable them , what is the problem that is causing? The cluster has other objects that you may not be using, what is the benefit of disabling API objects?

**Comment by ChristianBieri1995** [comment]
> See Rule 4a of https://kubernetes.io/docs/reference/using-api/deprecation-policy/ , we maintain backwards compatibility and Endpoint functionality is there and there is people and projects that still use them, removing them will break them.
> 
> What I don't understand what you want to disable them , what is the problem that is causing? The cluster has other objects that you may not be using, what is the benefit of disabling API objects?

Thank you for your reply, this helps a lot. Since we are facing performance issues in our cluster, we are searching for different root-causes. But most probably then, we'll leave the Endpoints as-is. Thanks a lot!

**Comment by aojea** [comment]
> Since we are facing performance issues in our cluster, we are searching for different root-causes. 

What performance issues?
