### ISSUE TITLE
For the version skew policy. Why the kubectl just support minor versions N+1, N and N-1? Is there any plan to support N-2 or N-3 minor versions like kubelet?

### ISSUE THREAD

**Issue by qing-chi-2013** [kubernetes/community#7602]
### Describe the issue

Hi team,

In our production, we are using the Kubectl to drain nodes automatically. Recently, we want to support the version skew policy. It is said, that we upgrade Kubernetes master nodes only and keep the old version of worker nodes. However, according to the Kubectl policy, it just supported minor versions N+1, N, and N-1. Is there any plan to support N-2 or N-3 minor versions for Kubectl like Kubelet? Or, is there any solution to replace Kubectl?

Thanks,
-qing

**Comment by YanzhaoLi** [comment]
Can anyone help look at this request?  Why does `kubectl`  only support N-1 version against the control plane?

**Comment by hariscats** [comment]
Compared to `kubelet` though, `kubectl` needs to maintain compatibility with a wide range of API resources and operations, which explains a stricter version skew policy. 

Supporting a larger version skew would require more extensive testing to ensure compatibility across a wider range of versions, which would increase the complexity and resources needed for testing.
