### ISSUE TITLE
KubeCon Contributor Summit EU 2024 - Team Staffing

### ISSUE THREAD

**Issue by salaxander** [kubernetes/community#7611]
### Describe the issue

The 2024 EU Contributor Summit in Paris will need staffing for its roles and shadows. The Contributor Summit date and location is to be determined. Planning meetings occur on Mondays at [9 AM Pacific/11 AM Central](https://dateful.com/convert/pst-pdt-pacific-time?t=09).

Event Leads will be @ameukam and @salaxander, with @qedrakmar serving as emeritus advisor. The Lead Shadow position is currently vacant.

We will also need shadows that could potentially take on leading those roles in the future. Roles and shadows will be listed below when they are filled out. With limited exception, shadows must have Kubernetes org membership. Shadows will be accepted at the discretion of the lead.

To clarify roles and responsibilities we are adding a role of "Volunteer" under each area. The Shadow bears expectations to lead one of the events-team roles in an upcoming summit and to handle all lead related activities in the absence of the Lead. It may be helpful to think of the Shadow role as an understudy position. Volunteers are helpers that may be assigned tasks from the Lead. Shadows and Volunteers, with limited exception, must be members of the Kubernetes GitHub organization. Leads are still responsible for accepting shadows and volunteers for their area. Volunteers, please communicate your desire to be a Shadow to the Lead of your area. Leads will inform me of their Shadows and I will update the issue.

We have a strong preference that participants as Leads, Shadows, and Volunteers be present at the Contributor Summit to help on site. This does not mean you cannot help virtually. There will be opportunities and we encourage you to come to the planning meetings in order to find virtual opportunities.
Thank you for your willingness to help out. We could not hold these events without you.

[**Registration**](https://github.com/kubernetes/community/blob/master/events/events-team/registration/README.md)
Lead: @reylejano 
Shadow: @savitharaghunathan, @Namanl2001  
Volunteers: @SD-13 
Emeritus Lead: @tokt    
 
[**Content**](https://github.com/kubernetes/community/blob/master/events/events-team/content/README.md)
Lead: @fykaa 
Shadow: @sreeram-venkitesh, @nitishfy. @kmova   
Volunteers:
Emeritus Advisor: @cailynse    

[**Comms**](https://github.com/kubernetes/community/blob/master/events/events-team/marketing/README.md)
Lead: @natalisucks 
Shadow: @AvineshTripathi
Volunteers: @kendallnelson, @sandipanpanda  
Website: @moficodes, @mfahlandt      

**Social Event (Required onsite in Paris)**
Lead: @cailynse 
Shadow: @ronitblenz  
Volunteers:  

[**Day-of Operations (Required onsite in Paris)**](https://github.com/kubernetes/community/tree/master/events/events-team/operations)
Lead: @mfahlandt 
Shadow: @cpanato, @upodroid, @jrsapi  
Volunteers:  @puja108
Emeritus Advisor: @natalisucks  

[**SIG Meet & Greet (Preferred onsite in Paris)**](https://github.com/kubernetes/community/blob/master/events/events-team/content/meet-and-greet.md)
Lead: @kaslin 
Shadow: @RA489, @Princesso 
Volunteers: @a-mccarthy 
Emeritus Advisor: @nimbinatus 

**Floating Volunteers (Preferred onsite in Paris)**
@celestehorgan 
@puerco 
@parispittman  

/assign @ameukam @salaxander 
/sig contributor-experience
/area contributor-summit
/area eu-summit

**Comment by reylejano** [comment]
I shadowed Registration for KubeCon NA 2023, I can either lead Registration or shadow another area like Content or Ops or MKCC / SIG Meet & Greet.

**Comment by natalisucks** [comment]
I graciously accept the lead role for Comms and I welcome any shadows and volunteers who would like to work with me ❤️

**Comment by jberkus** [comment]
Can we add a line for "Website" under Comms?

**Comment by salaxander** [comment]
> Can we add a line for "Website" under Comms?

Done!

**Comment by savitharaghunathan** [comment]
Raising my hand up to shadow registration this time.

**Comment by nimbinatus** [comment]
I don't know yet whether I'll be attending, but I can at least support whoever decides to take on MKCC/Meet & Greet. Once I have a better sense whether I'll be there, I'm happy to fill another role if I'll be present.

**Comment by pwalters04** [comment]
I would love to volunteer.  Currently looking for documentation on how /check if I am a member of the Kubernetes GitHub organization

**Comment by fykaa** [comment]
Would love to lead Communications this time!

**Comment by nitishfy** [comment]
I'd love to lead Registration this time!

**Comment by sreeram-venkitesh** [comment]
I'd love to help as a volunteer for Comms!

**Comment by jberkus** [comment]
@pwalters04  [here](https://github.com/kubernetes/org/blob/main/config/kubernetes/org.yaml) and [here](https://github.com/kubernetes/org/blob/main/config/kubernetes-sigs/org.yaml).  Looks like "no", but there's still time for you to apply for org membership, if you have contributions.

**Comment by tokt** [comment]
Strong +1 on @reylejano  leading Registration.
(Will be happy to be Emeritus  for Registration and/or help anywhere else I can)

**Comment by salaxander** [comment]
> I'd love to lead Registration this time! (If this is not possible, I'm up for shadowing for content).

@nitishfy Would you be open to shadowing on registration? I think for this one we're going to reserve it for someone that's shadowed that role recently.

**Comment by natalisucks** [comment]
@salaxander @ameukam It looks like Awards is missing a category!

**Comment by salaxander** [comment]
> @salaxander @ameukam It looks like Awards is missing as a category!

No awards at the EU event :)

**Comment by natalisucks** [comment]
@salaxander and that's why you're the lead 😸

**Comment by kaslin** [comment]
As discussed in Slack, I would be happy to lead comms with @natalisucks as a shadow. @fykaa has also mentioned interest in shadowing.

**Comment by Namanl2001** [comment]
happy to shadowing on Registration/ content

**Comment by ndixita** [comment]
I would love to shadow comms or content, wherever the help is needed.

**Comment by RA489** [comment]
I will be happy to Lead for SIG meet and Greet.

**Comment by AvineshTripathi** [comment]
I would like to shadow comms this time!

**Comment by cpanato** [comment]
I would like to help in the day operations as a volunteer or shadow if possible

**Comment by abhijeetgauravm** [comment]
I'd love to help as a volunteer for Comms/Content!

**Comment by puja108** [comment]
I will definitely be onsite again, so happy to volunteer with day-of-ops. I'm not sure how busy I'll be in the coming months, but if we can't find anyone else I could alternatively do website.

**Comment by cailynse** [comment]
I can lead social, and emeritus for content. Also happy to shadow lead.

**Comment by nitishfy** [comment]
> @nitishfy Would you be open to shadowing on registration? I think for this one we're going to reserve it for someone that's shadowed that role recently.

Definitely! I'm up to shadow for Registration.

**Comment by pwalters04** [comment]
> @pwalters04 [here](https://github.com/kubernetes/org/blob/main/config/kubernetes/org.yaml) and [here](https://github.com/kubernetes/org/blob/main/config/kubernetes-sigs/org.yaml). Looks like "no", but there's still time for you to apply for org membership, if you have contributions.

@jberkus  Thank you for the information!

**Comment by salaxander** [comment]
> I'd love to help as a volunteer for Comms/Content!

Hey @sreeram-venkitesh! Both roles are open, do you have a preference between the two?

**Comment by salaxander** [comment]
> I'd love to help as a volunteer for Comms/Content!

Hey @abhijeetgauravm - We do have a requirement that you're a member of the Kubernetes GitHub organization. More information on that can be found [here](https://github.com/kubernetes/org)

**Comment by sandipanpanda** [comment]
I am interested in shadowing Comms.

**Comment by sreeram-venkitesh** [comment]
> Hey @sreeram-venkitesh! Both roles are open, do you have a preference between the two?

@salaxander I'd like to work on the Comms team!

**Comment by ndixita** [comment]
@kaslin @salaxander I would like to volunteers for comms.

**Comment by ronitblenz** [comment]
@salaxander I was a Comms Volunteer for KubeCon NA 2023. 
I'm open to shadow for Registration/Social Event

**Comment by qedrakmar** [comment]
I'll be your emeritus lead advisor.

**Comment by Princesso** [comment]
I'd like to be a shadow for SIG-Meet & Greet

**Comment by salaxander** [comment]
Thanks for volunteering to shadow everyone! Once we have the leads in place, we'll go through and make all confirmations for shadows.

**Comment by kmova** [comment]
Happy to shadow SIG Meet & Greet or volunteer for Registration.

**Comment by mfahlandt** [comment]
I would love to Shadow Day-of Operations or Social Event - generally happy to help on-site

**Comment by upodroid** [comment]
I would like to volunteer for Registration or Day of Ops

**Comment by kaslin** [comment]
I would also like to volunteer to lead the Meet & Greet, as I shadowed @nimbinatus on that for NA.

**Comment by kendallnelson** [comment]
@natalisucks I can review any comms before they go out to the ML if that's helpful? I guess that makes me a volunteer :)

**Comment by kaslin** [comment]
I was chatting with him and @mfahlandt is up for the challenge of at least co-leading day-of-ops!

**Comment by natalisucks** [comment]
I'd like to confirm the following volunteers for Comms:

Website: @moficodes and @mfahlandt 
Volunteers: @kendallnelson and @sandipanpanda

I may have more to add after as I reach out to other folks who've indicated their interest on the thread 👍

**Comment by jrsapi** [comment]
I'm up to shadow for content and day of operations.

**Comment by stmcginnis** [comment]
I shadowed registration for the US summit. It looks like their are several volunteers for that already, so I'm happy to either support their or any other area that needs the help. Not sure yet if I will be onsite. If I am, happy to support with onsite activities, otherwise will do whatever I can from afar.

**Comment by fykaa** [comment]
Confirming @sreeram-venkitesh, @nitishfy and @Namanl2001 as shadows for content.

**Comment by SD-13** [comment]
I would like to volunteer Registration under @reylejano if that's still not taken :)

**Comment by natalisucks** [comment]
@ndixita are you still interesting in shadowing comms? if not, i'd recommend many of the other areas that still need help 😸

**Comment by reylejano** [comment]
@Namanl2001 , do you have a preference to shadow Registration or Content?

**Comment by reylejano** [comment]
@nitishfy , I see you're a shadow for Content already. Do you still have interest to shadow Registration?

**Comment by Namanl2001** [comment]
> @Namanl2001 , do you have a preference to shadow Registration or Content?

Yes @reylejano, I'd prefer shadowing registration. Thanks for asking!

**Comment by mfahlandt** [comment]
Confirming @cpanato @upodroid @jrsapi as shadows for Ops - Thank you for sticking around!

**Comment by a-mccarthy** [comment]
hi! I'd like to volunteer, or possibly shadow, for registration. Looking forward to helping out again

**Comment by ndixita** [comment]
> @ndixita are you still interesting in shadowing comms? if not, i'd recommend many of the other areas that still need help 😸

I am happy to help in other areas :D 
Comms being my priority

**Comment by natalisucks** [comment]
I'd like to confirm @ndixita for comms as a shadow, meaning that Comms is full for all roles at this time! Thanks everyone for your interest 👏 

As a note, I'd like comms folks to try and attend as many meetings as possible, and I will reach out via a group DM to start coordinating work. Thanks!

**Comment by cailynse** [comment]
Happy to have you as shadows for social @mfahlandt and @ronitblenz! Let me know if you are still interested!

**Comment by mfahlandt** [comment]
> Happy to have you as shadows for social @mfahlandt and @ronitblenz! Let me know if you are still interested!

as discussed in slack, sorry to decline, but otherwhise it is to much - anyway thanks for the consideration :)

**Comment by reylejano** [comment]
Confirming @Namanl2001 and @SD-13 to shadow registration

**Comment by ronitblenz** [comment]
> Happy to have you as shadows for social @mfahlandt and @ronitblenz! Let me know if you are still interested!

Confirming my interest for being a shadow for social. Looking forward!

**Comment by ameukam** [comment]
> Happy to shadow SIG Meet & Greet or volunteer for Registration.

@reylejano Is it possible for @kmova to be your shadow ?

**Comment by reylejano** [comment]
@ameukam , yes @kmova can shadow for Registration

**Comment by ndixita** [comment]
> I'd like to confirm @ndixita for comms as a shadow, meaning that Comms is full for all roles at this time! Thanks everyone for your interest 👏
> 
> As a note, I'd like comms folks to try and attend as many meetings as possible, and I will reach out via a group DM to start coordinating work. Thanks!

@natalisucks I wanted to check if there were any meetings scheduled that I might have missed out. Also I don't see my name in the issue description which has the list of people in each department. Just want to make sure I am not missing anything.

**Comment by natalisucks** [comment]
@ndixita Hi Dixita – yes, there have been 2-3 meetings now already, as stated in first sentence of this issue, which I will quote below:

> The 2024 EU Contributor Summit in Paris will need staffing for its roles and shadows. The Contributor Summit date and location is to be determined. Planning meetings occur on Mondays at [9 AM Pacific/11 AM Central](https://dateful.com/convert/pst-pdt-pacific-time?t=09).

Please ensure that you've joined the SIG Contributor Experience Google Group so that you can have the required meeting invite. You should also join the #summit-staff Slack channel in the Kubernetes Slack so you can access meeting notes and updates on things our group is already doing. The #contributor-summit Slack channel is also worth joining as a comms shadow.

@salaxander @ameukam if you could please add Dixita to my volunteers list under comms, that would be great.

**Comment by a-mccarthy** [comment]
Hi all, still possible to sign up to be a shadow/volunteer? Looking at the issue, are there any spots to help with the meet & greet? thanks!

**Comment by celestehorgan** [comment]
I'm happy to float to whatever y'all need a volunteer for :D I'll be in Paris!

**Comment by puerco** [comment]
Hey I think I will be able to be in Paris, I'd love to help out in person :)

**Comment by ameukam** [comment]
cc @parispittman to help as a volunteer.

**Comment by kaslin** [comment]
I have accepted @RA489 and @Princesso as shadows.

**Comment by natalisucks** [comment]
@salaxander @ameukam hi leads! unfortunately this time around @ndixita isn't able to shadow, so if you could please remove their name from the Comms shadows list, that would be great (in order to have an exact reflection for swag, etc)

**Comment by stmcginnis** [comment]
> I shadowed registration for the US summit. It looks like there are several volunteers for that already, so I'm happy to either support there or any other area that needs the help. Not sure yet if I will be onsite. If I am, happy to support with onsite activities, otherwise will do whatever I can from afar.

My travel is approved and I'm all set now to be on site for the event. Still happy to help out wherever needed.

**Comment by mfahlandt** [comment]
I would like to add and confirm @stmcginnis @celestehorgan @parispittman as volunteers for Day of Ops. Thank you!

**Comment by salaxander** [comment]
Closing this now that we're past the event. Thank so much again everyone for all your wonderful work!

/close
