### ISSUE TITLE
Leadership change: amim sig-windows

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/community#7614]
Hi folks! My personal laptop is dead so filing this issue for someone else (amim?) To help me with following up on the email to sig-windows for transitioning amim to replace me as sig windows lead!

,cc @knabben  @marosset @jsturtevant @aravindhp @claudiubelu

**Comment by knabben** [comment]
Opened the PRs following the directions from: https://github.com/kubernetes/community/blob/master/contributors/chairs-and-techleads/leadership-changes.md

**Comment by marosset** [comment]
/sig windows
/approve
Welcome @knabben!
