### ISSUE TITLE
Request: create vpa and ca icons

### ISSUE THREAD

**Issue by sysnet4admin** [kubernetes/community#7617]
### Describe the issue
In the icons set, there is HPA but no provide VPA and CA. 
So I made temporary icons using by HPA concept. 

[ **vpa** ]
<img src="https://user-images.githubusercontent.com/29163931/284109366-14e9484c-5def-4fa1-a8da-4f23b49c2cce.png" width=20% height=20%>

[ **ca** ]
<img src="https://user-images.githubusercontent.com/29163931/284109354-853d8457-ec9c-4be6-b6e0-f701c22aceda.png" width=20% height=20%>

How about new vpa, ca icons for users?
This case is related to #7322 (Request: create a coredns icon)
 
Regards, 
Hoon Jo. :)

**Comment by fharper** [comment]
@sysnet4admin: do you have a vector version of those?

**Comment by sysnet4admin** [comment]
@fharper I don't create by myself from the scratch. so I don't have svg at this time unfortunately. 
Probably if it accepted, it will create by `svg` later.
