### ISSUE TITLE
ContribEx: Leadership Change - cblecker, nikhita, mrbobbytables

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#7623]
### SIG/WG name:

SIG Contributor Experience

### Offboarding Lead(s):

 cblecker, nikhita, mrbobbytables

### Link to discussion:

https://github.com/kubernetes/community/pull/7603

### Prerequisites for new leads:

- [x] Are a [Kubernetes Org member](https://git.k8s.io/community/community-membership.md)
- [x] Have completed the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Onboarding / Offboarding tasks:

- [x] Updated [sigs.yaml](https://git.k8s.io/community/sigs.yaml) and associated [generated files](https://git.k8s.io/community/generator) (ran `make`). **NOTE:** If offboarding, remember to add to emeritus.
- [x] Updated [OWNERS_ALIASES](https://git.k8s.io/org/OWNERS_ALIASES) in [kubernetes/org](https://git.k8s.io/org/).
- [x] Updated [milestone maintainers team](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml) in [kubernetes/org](https://git.k8s.io/org/).
- [x] Checked for and updated any other potential teams in [kubernetes/org](https://git.k8s.io/org/).
- [x] Updated [OWNERS_ALIASES](https://git.k8s.io/enhancements/OWNERS_ALIASES) in [kubernetes/enhancements](https://github.com/kubernetes/enhancements).
- [x] Updated [OWNERS_ALIASES](https://git.k8s.io/k8s.io/OWNERS_ALIASES) in [kubernetes/k8s.io](https://git.k8s.io/k8s.io/).
- [x] Updated [membership](https://git.k8s.io/k8s.io//groups/groups.yaml) of the [leads mailing list](https://groups.google.com/a/kubernetes.io/g/leads)
- [x] Updated membership for any other [mailing list / groups](https://git.k8s.io/k8s.io//groups/).
- [x] Added to `#chairs-and-techleads` slack channel.
- [x] Updated ownership of group leads mailing list.
- [x] Updated ownership of group mailing list.
- [x] Updated ownership of group calendar.
- [x] Updated access/teams in 1password. (Contact ContribEx leads to complete)

### Labels:

/sig contributor-experience

**Comment by cblecker** [comment]
Opened the following OWNERS_ALIASES updates:
https://github.com/kubernetes/enhancements/pull/4344
https://github.com/kubernetes/k8s.io/pull/6115
https://github.com/kubernetes/org/pull/4599

**Comment by MadhavJivrajani** [comment]
Created:
- https://github.com/kubernetes/test-infra/pull/31304
- https://github.com/kubernetes/org/pull/4600
- https://github.com/kubernetes/k8s.io/pull/6117

**Comment by mrbobbytables** [comment]
I updated the tasks that I know about, I think theres a few group memberships that ownership should be updated on (e.g. leads list)

**Comment by palnabarun** [comment]
`leads@` is upto date.

**Comment by cblecker** [comment]
Anything else left on this? I checked off the last few items that I know are done and don't see anything further.

**Comment by kaslin** [comment]
I guess this never got closed. I'm closing it.
/remove-lifecycle rotten
