### ISSUE TITLE
Broken links to DevStats in Issue Triage Guidelines

### ISSUE THREAD

**Issue by ricardoapl** [kubernetes/community#7626]
### Describe the issue

It seems the following links in [Issue Triage Guidelines](https://www.kubernetes.dev/docs/guide/issue-triage/) are broken
- https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md?plain=1#L116
- https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md?plain=1#L117

Whenever I click those, my web browser gets redirected to
- https://kubernetes.devstats-grafana-kubernetes-6c985bdb7f-lnhgn:3000/d/12/dashboards?from=1587157094179&orgId=1&refresh=15m&to=1587758294179&viewPanel=8
- https://kubernetes.devstats-grafana-kubernetes-6c985bdb7f-lnhgn:3000/d/12/dashboards?from=1587157166022&orgId=1&refresh=15m&to=1587758366022&viewPanel=9

![Screenshot 2023-11-24 at 12 29 45](https://github.com/kubernetes/community/assets/48807108/8fe181b0-3ba2-4335-a885-49342343bf04)

I believe these links should point to the following URLs instead
- Issue Velocity - https://k8s.devstats.cncf.io/d/12/dashboards?from=1587157094179&orgId=1&refresh=15m&to=1587758294179&viewPanel=8
- PR Velocity - https://k8s.devstats.cncf.io/d/12/dashboards?from=1587157166022&orgId=1&refresh=15m&to=1587758366022&viewPanel=9

/sig contributor-experience
/area contributor-guide
/kind documentation

**Comment by ShivangShandilya** [comment]
I would like to resolve this issue ASAP

**Comment by ricardoapl** [comment]
Sure

/assign @ShivangShandilya

**Comment by ShivangShandilya** [comment]
I'll soon create a PR for this @tamilselvan1102
