### ISSUE TITLE
Reference to Gubernator in Issue Triage Guidelines

### ISSUE THREAD

**Issue by ricardoapl** [kubernetes/community#7635]
### Describe the issue

Gubernator has been discontinued https://groups.google.com/a/kubernetes.io/g/dev/c/SIpSxGqu_3Q and https://gubernator.k8s.io/pr now returns HTTP 404

References to Gubernator have been removed from the Contributor Cheatsheet in https://github.com/kubernetes/community/pull/7567, but there's still at least one reference in the Issue Triage Guidelines https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md?plain=1#L82

/sig contributor-experience
/area contributor-guide
/kind documentation

**Comment by sandipanpanda** [comment]
I can help with the clean up.
/assign
