### ISSUE TITLE
REQUEST: New communication about Cloud Native Security Slam

### ISSUE THREAD

**Issue by puerco** [kubernetes/community#7640]
SIG Release together with CNCF and the Security Slam organizers are running an event for new folks who want to try their hand contributing to kubernetes (details in [this announcement I sent to the community](https://groups.google.com/a/kubernetes.io/g/dev/c/SbSrJckE1iI)).

We would like to get some support with a tweet from k8s contributors account with this message:

> Join CNCF on Dec 15th in a unique event for NEW Kubernetes contributors!
> 
> Select registrants from varying experience levels will be invited to strike teams to implement specific security improvements  across the ecosystem!
> 
> Registration closes on Dec 10th!
> https://community.cncf.io/events/details/cncf-cloud-native-security-slam-presents-2023-security-slam-lightning-round/

**Comment by eddie-knight** [comment]
The window of opportunity for this request has passed

**Comment by puerco** [comment]
I'm closing this one as the registration is now closed
/close
