### ISSUE TITLE
SIG-network mailing list has been taken over by spammers

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#7641]
### Describe the issue

The official kubernetes-sig-network mailing list seems to belong to the spammers now:

https://groups.google.com/g/kubernetes-sig-network

If this is the old list, because we now have one belonging to kubernetes.io, we should shut it down and update the SIG-network charter.

/sig network
/area moderation

**Comment by aojea** [comment]
AFAIK an alternative is to moderate the lists, it puts more work on the moderators, but this list is very low traffic , I can step up to help moderate it

cc @shaneutt @thockin @MikeZappa87

**Comment by jberkus** [comment]
I don't know where we are with moving the mailing lists over to the kubernetes.io org?  Having the list be org-owned would allow us to have a moderator pool.

@mrbobbytables ?

**Comment by MikeZappa87** [comment]
I didn’t think any of us had permissions to moderate the Google group. How do we go about getting those permissions back? Also +1 if @aojea wants to help

**Comment by MikeZappa87** [comment]
I deleted the messages.

**Comment by dims** [comment]
@aojea i already moderate a bunch, so feel free to add me as a moderator

**Comment by MikeZappa87** [comment]
Should we close this issue or is work remaining?

**Comment by mrbobbytables** [comment]
I'd go ahead and close it for now. Theres a bit more work involved to get everything over to a kubernetes.io mailing list. That one will probably be tackled when we try and do it with more sigs and will require a bit more coordination

**Comment by aojea** [comment]
found the spammer 
![image](https://github.com/kubernetes/community/assets/6450081/27eb31c5-746c-49bc-9bef-bac842e248f4)

let's close and iterate
