### ISSUE TITLE
SIG Network: Leadership Change

### ISSUE THREAD

**Issue by shaneutt** [kubernetes/community#7650]
### SIG/WG name:

SIG Network

### Onboarding Lead(s):

aojea

### Link to discussion:

https://groups.google.com/g/kubernetes-sig-network/c/eXWpR97fSWc

### Prerequisites for new leads:

- [X] Are a [Kubernetes Org member](https://git.k8s.io/community/community-membership.md)
- [x] Have completed the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Onboarding / Offboarding tasks:

- [x] Updated [sigs.yaml](https://git.k8s.io/community/sigs.yaml) and associated [generated files](https://git.k8s.io/community/generator) (ran `make`). **NOTE:** If offboarding, remember to add to emeritus.
- [x] Updated [OWNERS_ALIASES](https://git.k8s.io/org/OWNERS_ALIASES) in [kubernetes/org](https://git.k8s.io/org/).
- [x] Updated [milestone maintainers team](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml) in [kubernetes/org](https://git.k8s.io/org/).
- [x] Checked for and updated any other potential teams in [kubernetes/org](https://git.k8s.io/org/).
- [x] Updated [OWNERS_ALIASES](https://git.k8s.io/enhancements/OWNERS_ALIASES) in [kubernetes/enhancements](https://github.com/kubernetes/enhancements).
- [x] Updated [OWNERS_ALIASES](https://git.k8s.io/k8s.io/OWNERS_ALIASES) in [kubernetes/k8s.io](https://git.k8s.io/k8s.io/).
- [x] Updated [membership](https://git.k8s.io/k8s.io//groups/groups.yaml) of the [leads mailing list](https://groups.google.com/a/kubernetes.io/g/leads)
- [x] Updated membership for any other [mailing list / groups](https://git.k8s.io/k8s.io//groups/).
- [x] Added to `#chairs-and-techleads` slack channel.
- [x] Updated ownership of group leads mailing list.
- [x] Updated ownership of group mailing list.
- [x] Updated ownership of group calendar.
- [x] Updated access/teams in 1password. (Contact ContribEx leads to complete)
- [x] Updated feature-approvers in [OWNERS_ALIASES](https://git.k8s.io/k8s.io/OWNERS_ALIASES) in [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes)

### Labels:

/sig network
/assign @mrbobbytables 
/cc @thockin @MikeZappa87 @danwinship

**Comment by aojea** [comment]
### Prerequisites for new leads:
 * [x]  Are a [Kubernetes Org member](https://git.k8s.io/community/community-membership.md)
 * [x]  Have completed the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
 https://www.credly.com/badges/5a918494-f3cd-4633-9c83-be66e8068d33/linked_in_profile
 ### Onboarding / Offboarding tasks:
 * [ ]  Updated [sigs.yaml](https://git.k8s.io/community/sigs.yaml) and associated [generated files](https://git.k8s.io/community/generator) (ran `make`). **NOTE:** If offboarding, remember to add to emeritus. https://github.com/kubernetes/community/pull/7651
 * [ ]  Updated [OWNERS_ALIASES](https://git.k8s.io/org/OWNERS_ALIASES) in [kubernetes/org](https://git.k8s.io/org/). https://github.com/kubernetes/org/pull/4627
 * [x]  Updated [milestone maintainers team](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml) in [kubernetes/org](https://git.k8s.io/org/). https://github.com/kubernetes/org/blob/48a59bca3030928bdb57ddc29c35d3eccdb3ea72/config/kubernetes/sig-release/teams.yaml#L30
 * [x]  Checked for and updated any other potential teams in [kubernetes/org](https://git.k8s.io/org/).
 * [x]  Updated [OWNERS_ALIASES](https://git.k8s.io/enhancements/OWNERS_ALIASES) in [kubernetes/enhancements](https://github.com/kubernetes/enhancements). https://github.com/kubernetes/enhancements/pull/4362
 * [ ]  Updated [OWNERS_ALIASES](https://git.k8s.io/k8s.io/OWNERS_ALIASES) in [kubernetes/k8s.io](https://git.k8s.io/k8s.io/). https://github.com/kubernetes/k8s.io/pull/6199
 * [x]  Updated [membership](https://git.k8s.io/k8s.io//groups/groups.yaml) of the [leads mailing list](https://groups.google.com/a/kubernetes.io/g/leads) https://github.com/kubernetes/k8s.io/blob/9e4b6ccb2b128baed4ef24ebfe579202a0f191b0/groups/groups.yaml#L37
 * [x]  Updated membership for any other [mailing list / groups](https://git.k8s.io/k8s.io//groups/).
 * [x]  Added to `#chairs-and-techleads` slack channel.
 * [x]  Updated ownership of group leads mailing list.
 * [x]  Updated ownership of group mailing list.
 * [ ]  Updated ownership of group calendar.
 * [ ]  Updated access/teams in 1password. (Contact ContribEx leads to complete)

**Comment by danwinship** [comment]
> Onboarding / Offboarding tasks:

This template is missing an item for "`[ ] Updated feature-approvers in OWNERS_ALIASES in kubernetes/kubernetes`"

**Comment by shaneutt** [comment]
> This template is missing an item for "`[ ] Updated feature-approvers in OWNERS_ALIASES in kubernetes/kubernetes`"

Added the item manually for this issue, and then created https://github.com/kubernetes/community/pull/7661 to add it permanently to the template.

**Comment by shaneutt** [comment]
I've asked contribex to add @aojea to the 1password, @thockin I think I'll need your help with the mailing list and calendar updates, as I don't appear to be able to update those.

Also @aojea just need a confirmation that you've taken https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/

Once that's done I'll send out the final mailing list updates!

**Comment by aojea** [comment]
> Also @aojea just need a confirmation that you've taken https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/

it is here https://www.credly.com/badges/5a918494-f3cd-4633-9c83-be66e8068d33/linked_in_profile

**Comment by aojea** [comment]
![image](https://github.com/kubernetes/community/assets/6450081/649bcdd2-2cad-4fee-8204-294323f41248)


> * [x]   Have completed the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
>   https://www.credly.com/badges/5a918494-f3cd-4633-9c83-be66e8068d33/linked_in_profile

**Comment by shaneutt** [comment]
Announced: https://groups.google.com/a/kubernetes.io/g/dev/c/Yj0NIS0yRlI/m/ZEoyizt2BgAJ

Just waiting on someone who can do the calendar/group updates at some point and then all set.

**Comment by thockin** [comment]
Antonio is an owner of the sig-net ML and calendar now.

Unfortunately, the leads group has no Owners.  I have tried to get support internally and not succeeded so far.  If we want to "recover" it, we may need to make a new group and change the Zoom and other things over to it.

**Comment by mrbobbytables** [comment]
Creating a managed one isn't too difficult, several SIGs have gone that way already. Just need to ping slack admins when ready to change the account email address over

**Comment by aojea** [comment]
I think we can close this now @mrbobbytables @shaneutt

**Comment by shaneutt** [comment]
Yep, we're all set I think.
