### ISSUE TITLE
wg-policy: YouTube playlist and help with automating uploads

### ISSUE THREAD

**Issue by JimBugwadia** [kubernetes/community#7653]
### Describe the issue

Please help create a YouTube playlist for the Policy WG and automate uploads.

Here are our 2023 videos:
- [Dec 6th 2023
](https://zoom.us/rec/share/nKjxUjr4oqczFbzgUadyq4CEfHWJ-PurU9HSaPdmyLKHBcHbOtiIy4afqq4CyEET.j4nv52Ba6fqLwnbt)
- [Sep 27 2023](https://zoom.us/rec/share/FxOHs6seLwhgWyQ5L0ZBRHbMNQxRYN3-Abj4BnUkZCkvGWddbaOnrd64oc9x0tBU.6dm8hsLBJ9WDFUBx)
- [Sep 13 2023
](https://zoom.us/rec/share/DV5S2_yLd4gWiE4Z8GjW7DVd8xG-KybWIx-fctOUfpwJmxylrguK1GOkBnFHLmH3.oo1Mt4bbFTp0DjmI)
- [Aug 30 2023](https://zoom.us/rec/share/WIRmOiPL8yayYloCloGyC1UWng1mkZRlNlqQ-Udm4Dcy6X9ZRUha4pX5CC4MhXns.-mVk7O-IS3THxkb_)
- [Aug 2 2023](https://zoom.us/rec/share/gjvSiLxLuTlQnG6qjsAZYSsDiQvXwrtkYx2BhMFG520GIJyqk0ImXVD589yygW8.nL8EoXhGJRZh2031)
- [Jul 19 2023](https://zoom.us/rec/share/ycTdcyz0QvdwupMdysGXiqIa8anEm61xmrCVtg-Ae49hIWhIKNOSLTxip-v7LdLx.XCgw6IMPgZ9XgsRd)
- [Jul 5 2023](https://zoom.us/rec/share/GXVzaCdnpVPe2MxtlkqZprRR-LTfXevkizOC8ezRKkOTIS-XKEPD9lSz6MSqQjQ5.RAi4AUDVsvJY0QWt)
- [Jun 7 2023
](https://zoom.us/rec/share/ZiyISHAFDC421uIzNNy6z52Gi2eP2T7EyoydWEDvngqUOEA3XiMuW2Q5z6kVvGfC.3BYKVzAqkaLhidvw)
- [May 10 2023
](https://zoom.us/rec/share/SQw9cvorI_Mc1MxXIgZTra7UiStrS57ihqZg9D3z7eIz13xfy85ps0h01SKRHmE.20ZpOoFGn-PI9hFB)
-  [Apr 26 2023](https://zoom.us/rec/share/RnVN4PfeHNQ_zvvEjVtLXT7k9M9wfaRcBD9JkFjbzazKf2Mi6ORZdRJbREeQNU9t.ZR3P_s8lwWAwJOEa)
- [Apr 12 2023
](https://zoom.us/rec/share/abvpjpWbspoVdr7GZ82mHVYEBLQtUUZ43kx4qMSDBQU0EqwoTK0IGptCz0-TFSjj.24Ztv1UCr0q8HKVu)
- [Mar 29 2023
](https://zoom.us/rec/share/CGcyt3YPJ7VxkWWdreci8qbLgx95CIcnd4vjUV_AKpwLc3HWhK05lmGKvn-8Cu4i.TQhDegy-hi-7z6CG)
- [Mar 15 2023](https://zoom.us/rec/share/hM_ciUXOJf84cmustwWRbF0nBnouPcmvs_OAI8s1_FMCA-t3BpVH-Uch0FzFgrqJ.BHi25_Mo8v0V2vBh)
- [Mar 1 2023
](https://zoom.us/rec/share/QdCuKFD6tBm4--3RHZT6WesKLZGUeYX7FosZrKPVREPX4c0MXPefR5EbQAYb1VPs.riL1q7UqUE_QwsMN)
- [Feb 15 2023
](https://zoom.us/rec/share/CVOGsxAJ8-ELnqdoxrCcz5Y6ufsovBhya5BngeXDHy1iY3MTgmnzqEEL1YDsbRUD.ZnjYIDqDAEjxR45m)
- [Jan 18 2023](https://zoom.us/rec/share/tjglENw8wJojoHb0yrErMN61pUqeNFWYGMdpQv3xW3nUqvTcMzyMZyybUnJpb6Wa.HcurUS5sKGj0LR8a)
- [Jan 4 2023](https://zoom.us/rec/share/72KTUEnBiVaHTpcMMoVc88lCfsCLWjEwNPCPt6cSI7yZVZh0akouwSD3DAIXsB53.dXkGRfZ4t8wyBzs8)

**Comment by Surajkumar98012** [comment]
Hey @JimBugwadia.I am new to open source and I just want to contribute. Can you please guide me? Thank you!
