### ISSUE TITLE
Community docs improvement

### ISSUE THREAD

**Issue by haripriya9647** [kubernetes/community#7654]
### Describe the issue

I have identified a few corrections in the docs :

Page - https://www.kubernetes.dev/docs/guide/non-code-contributions/
* [Find CNCF meetups near you](https://www.meetup.com/pro/cncf) link is broken
* "[Management of communication tools](https://www.kubernetes.dev/docs/comms/moderation) (at the discretion of project maintainers)
[Mailing list moderation](https://www.kubernetes.dev/docs/comms/moderation)
[Slack](https://www.kubernetes.dev/docs/comms/moderation) or [Discourse management](https://www.kubernetes.dev/docs/comms/moderation)" all the links are redirecting to the same page

Page - https://www.kubernetes.dev/docs/guide/issue-triage/#gubernator
* [Gubernator](https://gubernator.k8s.io/pr) link is broken

Page - https://www.kubernetes.dev/docs/guide/first-contribution/#sig-structure
* [weekly meetings](https://docs.google.com/document/d/1qf-02B7EOrItQgwXFxgqZ5qjW0mtfu5qkYIF1Hl4ZLI/edit) link is broken

**Comment by haripriya9647** [comment]
@kumarankit999 I need your help in finding correct links

**Comment by kumarankit999** [comment]
Hey @haripriya9647, Thanks for raising this issue!
what specific kind of help do you need?
