### ISSUE TITLE
Add monthly WG-Batch meeting for US-west+APAC

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/community#7659]
### Describe the issue

We currently have a meeting every other Thursday at 3PM UTC, which is within working hours for European and East North American cities, where the coordinators are.
However, the slot is too late for APAC and too early for West NA.

Given the interest for people from these places to participate, we can consider adding a monthly meeting outside of the working hours of the existing coordinators.

An initial survey was sent by @vsoch https://doodle.com/meeting/participate/id/e02w44Lb, but it didn't gather any votes from APAC. I'm wondering whether there was enough outreach or the proposed slots are too early.

**Comment by stackedsax** [comment]
I'd be able to join at either, but certainly could stomach 9am PST a little easier.

**Comment by KunWuLuan** [comment]
Thanks aldo. For me, maybe 9am is too late because it is 1:00 am in Beijing time.

**Comment by bg-furiosa** [comment]
PST 3PM(8AM in my time zone) works for me.

**Comment by bg-chun** [comment]
PST 3PM(8AM in my time zone) works for me.

**Comment by kerthcet** [comment]
Just my situations, not represent anyone from APAC:

Wonder whether 2PM UTC fit for all the attendees joined before, to me, yes, it's 10 at night.
<img width="1040" alt="image" src="https://github.com/kubernetes/community/assets/18364341/7d5b2e4b-20f5-4387-9917-84a5c905fa59">

PST 6pm would be great, PST 5pm, still yes.
<img width="1046" alt="image" src="https://github.com/kubernetes/community/assets/18364341/c7bec52e-004f-42cf-8ad7-42f0c09e6237">

**Comment by alculquicondor** [comment]
I see that I wasn't clear:

> Is 8am an acceptable time or should we target 9am?

I meant whether 8am, in your respective timezones, is acceptable. This could help define a time window.

@kerthcet I don't think we can do 6am PST, as the current one is 7am PST and people in PST say it's too early :)

**Comment by kerthcet** [comment]
Understood.

**Comment by alculquicondor** [comment]
Could something like this be acceptable? 
![image](https://github.com/kubernetes/community/assets/1299064/24a54e7a-d584-4c89-bb27-9d8a6c5ae938)

**Comment by alculquicondor** [comment]
Another possibility could be this, but then it means that I would be the only organizer available to host.
![image](https://github.com/kubernetes/community/assets/1299064/8d564c94-b58f-409e-a22e-1a4f58c8f049)

**Comment by vsoch** [comment]
@alculquicondor and others, do you want another doodle / way to vote? What would be best to help choose this?

**Comment by vsoch** [comment]
Again:

cc @soltysh @mwielgus @swatisehgal as coordinators.
cc @kerthcet @tenzen-y @bg-chun @KunWuLuan @B1F030 @Gekko0114 @BinL233 @denkensk 

Please vote here with your preferred (now actual day and time) for the week of the 22nd! Times are in PST.

https://doodle.com/meeting/participate/id/eEKlnM0b

Thank you!

**Comment by kerthcet** [comment]
Thanks @vsoch for the effort, I checked the time slots, but the time still a little earlier to me, I can pick the latest slot but I can't guarantee that I can attend all the time, which may misleading the votes, so I gave up in the end. 

Glad to see the final result satisfying most of the people.

**Comment by vsoch** [comment]
@kerthcet thank you for filling it out! It's definitely really hard to find "one time that fits them all" - I do hope if we chose a later time in the set that you can show up once in a while (and I totally understand, I'm not one to wake up too early). I think likely we will have it open through this week then @alculquicondor and I will sync to decide on the final time.

**Comment by kerthcet** [comment]
We usually sync with the open source community at night, so it's usually hard to get up early in the morning. And 9-10 am we usually on our way to the office in China. 🙃

**Comment by vsoch** [comment]
> We usually sync with the open source community at night, so it's usually hard to get up early in the morning. And 9-10 am we usually on our way to the office in China. 🙃

See I don't even have that good a reason, I just irresponsibly stay up late programming like a goblin in a cave and then wake up... eventually! :laughing: :upside_down_face: :bat:

**Comment by tenzen-y** [comment]
I voted it. It's probably hard to adjust Time to my location since my timezone may be the most eastern zone.

**Comment by alculquicondor** [comment]
> We usually sync with the open source community at night, so it's hard to get up early in the morning

I wonder if it would make sense to change the time for the existing meeting to be 1 or 2h earlier. It sounds like it would work for people in China. Would that work for Japan @tenzen-y?

**Comment by tenzen-y** [comment]
> > We usually sync with the open source community at night, so it's hard to get up early in the morning
> 
> I wonder if it would make sense to change the time for the existing meeting to be 1 or 2h earlier. It sounds like it would work for people in China. Would that work for Japan @tenzen-y?

@alculquicondor Yes, I usually sync with the community at night, too. Moving the existing meeting to 2 hours earlier would be helpful to me. Once moving the existing meeting to 2 hours earlier, the starting time is 10pm on my local time (JST).

@kerthcet WDYT?

**Comment by kerthcet** [comment]
> I'm also ok with 1h earlier.

That would be great!

**Comment by alculquicondor** [comment]
Opened PR #7684
