### ISSUE TITLE
No architecture diagram in "Kubernetes Design and Architecture"

### ISSUE THREAD

**Issue by tauqeerhassan** [kubernetes/community#767]
Amazed to see no diagrams under a section named Architecture. It become easy to understand the whole thing if it has some logical or actual diagrammatic representation.

**Comment by cblecker** [comment]
We're in the process of forming a formalized sig-architecture to oversee this kind of thing. The thread about it is [here](https://groups.google.com/d/msg/kubernetes-dev/T-5zfRZmM50/XoecI06lAAAJ), and there is a number of good resources including a presentation and diagrams.

**Comment by bgrant0607** [comment]
One possible source is this slide:
https://docs.google.com/presentation/d/1oPZ4rznkBe86O4rPwD2CWgqgMuaSXguIBHIE7Y0TKVc/edit#slide=id.g21b1f16809_1_79

cc @kubernetes/sig-architecture-bugs

**Comment by xiangpengzhao** [comment]
There are arch diagrams (https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture.png , also dia/svg format diagrams), but seems like none of them is linked and shown in https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture.md

**Comment by bgrant0607** [comment]
@xiangpengzhao I removed links to that picture because it has numerous problems. For instance, I'd like to remove mention of cadvisor, which isn't a separate component. There is also no "scheduling actuator", the proxy is misleading, it doesn't mention the apiserver, it doesn't mention CRI and other more recent developments, etc.

And it's not very attractive.

**Comment by xiangpengzhao** [comment]
@bgrant0607 yeah :)

**Comment by vishakhanihore** [comment]
@cblecker @nikhita I found this architecture diagram in the `K8 Website`, Will the following diagram work for same?
<img width="701" alt="Screenshot 2019-12-19 at 7 03 56 PM" src="https://user-images.githubusercontent.com/54327666/71177614-67c8bd80-2292-11ea-8a14-e1980ac424c0.png">

**Comment by mrbobbytables** [comment]
Is this still relevant? It's been open and frozen for some time now.
I'm going to mark it as rotten for now, if it should be left open please update or re-freeze it 👍  

/remove-lifecycle frozen
/lifecycle rotten
