### ISSUE TITLE
Shared Google Drive for SIG Cluster Lifecycle

### ISSUE THREAD

**Issue by vincepri** [kubernetes/community#7671]
### Describe the issue

To streamline the process of storing and owning meeting notes for the entire SIG and subprojects, @mrbobbytables was [kind to point out](https://kubernetes.slack.com/archives/C1TU9EB9S/p1704731554379089) that there is a way for the SIG to own the documents in the community's shared google drive by creating the documents there.

/sig contributor-experience

**Comment by vincepri** [comment]
cc @sbueringer @fabriziopandini @MadhavJivrajani

**Comment by MadhavJivrajani** [comment]
/assign

Thanks!
Will create a sub-folder for `sig-cluster-lifecycle`

**Comment by fabriziopandini** [comment]
Thanks @MadhavJivrajani!
