### ISSUE TITLE
Calendar says "Could not open requested event" for SIG-Windows meetings

### ISSUE THREAD

**Issue by mloskot** [kubernetes/community#7673]
### Describe the issue

https://www.kubernetes.dev/resources/calendar/ lists two SIG-Windows meetings on Tuesday, but none of them can be opened and accessed e.g. to add to personal calendars

This screencast shows the problem in action:

https://github.com/kubernetes/community/assets/80741/f1725552-0c63-4ece-894b-717a8c188281

**Comment by mloskot** [comment]
On the screencast above, I access the http://k8s.dev/calendar being signed in to my Google Workspace (fka G Suite) account with custom domain i.e. masteusz@loskot.net, but if I switch to plain Google account i.e. mloskot@gmail.com, then I can access the SIG-Windows events without any problem:

![image](https://github.com/kubernetes/community/assets/80741/b34347d9-8f2e-47bc-a858-1c0d4f09675f)

**Comment by aravindhp** [comment]
/assign @marosset 

I think Mark already fixed this issue.

**Comment by mloskot** [comment]
Yes, @aravindhp , let's close this.
