### ISSUE TITLE
Automation: Use the Zapier Code tool to eliminate manual labor on YouTube when uploading SIG videos

### ISSUE THREAD

**Issue by chris-short** [kubernetes/community#7688]
Currently, we have an automation setup in Zapier to take video from Zoom and dump it into Google Drive. Then, another Zap takes it from Google Drive to YouTube. But there are a few manual steps that need to happen on YouTube after the upload, and right now, @pnbrown is the only one doing that work.

```mermaid
graph LR
    RS1("SIG-ContribEx Zoom") --> Zapier
    RS2("SIG-Docs Zoom") --> Zapier
    RS3("SIG-K8s-Infra Zoom") --> Zapier
    RS4("WG-LTS Zoom") --> Zapier
    Zapier --> |$TOPIC for $TIME| D("Google Drive")
    D --> E("YouTube")
    E --> F("Nigel")
    F --> E
```

Ideally, using Zapier Code, we can write a Python or JS script to accomplish the metadata tweaks needed on YouTube to eliminate this problem. @mfahlandt has taken the task of writing a JS script to update video metadata on YouTube. This means the above diagram becomes this:

```mermaid
graph LR
    RS1("SIG-ContribEx Zoom") --> Zapier
    RS2("SIG-Docs Zoom") --> Zapier
    RS3("SIG-K8s-Infra Zoom") --> Zapier
    RS4("WG-LTS Zoom") --> Zapier
    Zapier --> |$TOPIC for $TIME| D("Google Drive")
    D --> E("YouTube")
    E --> F("Zapier Code")
    F --> E
```

**Comment by pnbrown** [comment]
It looks good to me. I'd have to see what other onboarding has been done or if it's all captured
