### ISSUE TITLE
Unconference Topics - Kubernetes Contributor Summit 2024 Paris

### ISSUE THREAD

**Issue by fykaa** [kubernetes/community#7692]
### Describe the issue

Bonjour Kubernetes friends! 🇫🇷

Exciting news – we're organizing **Unconference** for this year's **Kubernetes Contributor Summit in Paris** and we'd love to know what topics interest you. Feel free to suggest a topic or give a thumbs up to ones that catch your eye. Our goal is to gauge the community's general interests, not just those attending in person :)

You can suggest by dropping a comment with -
**Topic**: [Your Topic]
**Description**: [Brief Description]
**Moderator**: [Planning to attend in person and want to moderate? (yes, maybe or no)]

To upvote, simply use the :+1: emoji.

If you have any questions, reach out to me @fykaa (fyka in Slack).

Thanks a bunch!
– Faeka Ansari, KCEU K8s Contributor Summit 2024 Content Lead

You can find session notes here: [k8s.dev/summit/notes](https://drive.google.com/drive/folders/1lRuFvfvbTt0qdYBYzsLn-CIquJZeenDX?usp=drive_link)

**Comment by intUnderflow** [comment]
**Topic:** Future of Events on Kubernetes
**Description:** Events in Kubernetes are sometimes the only source of information that users find helpful (such as exit codes returned by health checks). End-users consistently treat events as a reliable delivery bus for this information and many articles imply that they are this, but in truth this is not guaranteed by us, in fact we actually intentionally fail to deliver them under very strict rate limits. We also currently make no guarantees that events won't be removed in future versions, breaking potential underlying implementations.
Is there anything we can do to help these folks? Do we want to revisit events in the long term as concept? Come to this session to discuss our current approach and brainstorm what we'd like to change about events over the next few years, if anything.
**Moderator: ** @intUnderflow as a fallback, but I would prefer someone with a more deeper understanding than me

**Comment by skitt** [comment]
**Topic**: ClusterInventory API access/credentials

**Description**:
[KEP-4322: Inventory Cluster API](https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/4322-cluster-inventory) is a proposal to establish a standardized inventory cluster API to represent clusters in a multicluster deployment. We have use cases to use this to facilitate API access to each of the various clusters, but its [not currently in scope](https://docs.google.com/document/d/1sUWbe81BTclQ4Uax3flnCoKtEWngH-JA9MyCqljJCBM/edit#bookmark=id.9u2mf8v4djq3) of the first phase of the API.

A subgroup of SIG-MC has however started discussions on the topic of representing/storing access credentials and the relevant access patterns; see https://docs.google.com/document/d/18USWROcJcjjKH1O0-bsaL1txx1UXDXkaBEJ2OdI1-EQ/edit for details. The target audience is controllers needing access to all the clusters in a clusterset, or at least some pattern providing access to all the clusters in a clusterset. As usual for SIG-MC, we want to avoid locking in certain implementation choices, but we do want to ensure the spec is useful and usable without (much) extension.

A number of people are interested in continuing the discussion face to face at the contributor summit.

**Moderator**: @skitt, other volunteers are welcome!

**Comment by qedrakmar** [comment]
**Topic:** Enabling SIGs to acknowledge, recognize, and manage Non-Code contributions.

**Description:** 
We all know that there are more contributions to open source than just lines of code, but how do we deal with them? 
 We're addressing questions like:

- What types of non-code roles exist today?
- How do we Identify them?  How are these types of roles and tasks seen today?
- Are these contributions tracked?  How are they/could they be tracked? 
- How do we Publicize them and make them Actionable?  
- How do you attract new contributors to these roles and tasks?
- What could a contributor ladder look like for these?

We really need additional SIGs onboard with this initiative to help us to help you.  We will be visiting many SIGs in the near future to talk about these topics, but early commitment from SIG leadership will help our research and help us define a framework for all SIGs and WGs, and eventually all CNCF projects to use, as mentioned here: https://github.com/cncf/tag-contributor-strategy/issues/82 

**Moderator:**
@qedrakmar

**Comment by Priyankasaggu11929** [comment]
KCSEU 2024 event is over. :slightly_smiling_face: 

@fykaa, are we good to close this issue now? Thanks!

**Comment by ameukam** [comment]
Retro - part 2 is done.

/close
