### ISSUE TITLE
Munge script is missing

### ISSUE THREAD

**Issue by johscheuer** [kubernetes/community#770]
Hi,

I wanted to update some docs but the munge script is missing in the main repository (https://github.com/kubernetes/kubernetes/tree/master/hack). I wanted to ask where I can find the `hack/update-munge-docs.sh` in the current setup? 

Probably the [docs](https://github.com/kubernetes/community/blob/master/contributors/devel/how-to-doc.md#how-to-include-an-example) need some adjustment.

Thanks!

**Comment by MHBauer** [comment]
Deprecated at the end of 2016 and doesn't exist anymore.

I think everything is done in https://github.com/kubernetes/kubernetes.github.io now, so it might be best to link there or just kill this doc.
