### ISSUE TITLE
REQUEST: New Slack #sig-network-kni

### ISSUE THREAD

**Issue by shaneutt** [kubernetes/community#7703]
### GitHub Username

@MikeZappa87, @shaneutt, @thockin 

### Slack Username

"Michael Zappa", "shane", "thockin"

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

channel

### Name of Requested Resource

#sig-network-kni

### Description of Request

Kubernetes Networking reImagined (KNI) is an initiative within SIG Network with the following KEP:

https://github.com/kubernetes/enhancements/pull/4477

We would like a Slack channel for discussion of the KEP and topic please.

Thank you!

**Comment by coderanger** [comment]
Hi there, do you need assistance creating the PR for this?
