### ISSUE TITLE
KubeCon EU 2024: Kubernetes Meet & Greet signups (Previously SIG Meet & Greet or MKCC)

### ISSUE THREAD

**Issue by kaslin** [kubernetes/community#7715]
### Describe the issue

Since SIG Meet and Greet has been added to KubeCon proper, we have had difficulty being discovered in the overall KubeCon schedule. For KubeCon EU 2024, we are renaming SIG Meet and Greet to Kubernetes Meet & Greet to help with discoverability.

Accordingly, the Kubernetes Meet & Greet will be Friday, March 22 from 12:00pm - 3:00pm. Here it is on the KubeCon EU schedule: https://sched.co/1a6v5

If your SIG is interested in having a table, please comment on this thread. We will update this top post as time goes by with participating groups.

A preliminary list of potentially participating community groups is listed here (alphabetical by committee, then by SIG, then by WG). If no one signs up to represent a group, it will be removed from the list before the event:

SIG API Machinery - 
SIG Apps - 
SIG Auth - 
SIG Autoscaling - 
SIG CLI - 
SIG Cloud Provider - 
SIG Cluster Lifecycle - 
SIG Contributor Experience - 
SIG Docs - 
SIG etcd - 
SIG Instrumentation - 
SIG Kubernetes Infrastructure - 
SIG Network - 
SIG Node - 
SIG Release - 
SIG Scheduling - 
SIG Storage - 
SIG Testing - 
WG Batch - 
WG Data Protection - 
WG LTS -
WG Policy - 
/assign @kaslin @Princesso @RA489 
/sig contributor-experience
/area contributor-summit
/area eu-summit

**Comment by reylejano** [comment]
SIG Docs is interested in having a table
We'll be there

**Comment by eddiezane** [comment]
SIG CLI will be there.

cc @soltysh

**Comment by jmhbnz** [comment]
I can be there to represent SIG etcd.

cc @serathius, @ahrtr, @wenjiaswe

**Comment by pohly** [comment]
I can be there for SIG Testing and SIG Instrumentation (= WG Structure Logging).

**Comment by soltysh** [comment]
> SIG CLI will be there.
> 
> cc @soltysh

yeah, and SIG-Apps and WG-Batch with my single presence :sweat_smile:

**Comment by shaneutt** [comment]
There will be representatives from SIG Network there.

**Comment by logicalhan** [comment]
SIG-Instrumentation and SIG etcd will be there.

**Comment by JimBugwadia** [comment]
@sudermanjr and I will be there for Policy WG!

**Comment by divya-mohan0209** [comment]
I will be there for SIG Docs. 
cc: @natalisucks @reylejano @sftim

**Comment by enj** [comment]
I will be there for SIG Auth and WG LTS

**Comment by gjtempleton** [comment]
I'll be there for SIG Autoscaling!

**Comment by ameukam** [comment]
Event happened during KubeCon.

Thanks to everyone for showing up!

/close
