### ISSUE TITLE
List projects under kubernetes org in alphabetical order

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/community#773]
By what order are the projects listed, importance? popularity? or other rules? They look like in random order currently. This makes them somewhat in a mess. Can we list them in alphabetical order. It will make contributors/users easier to find a project.

/cc @bgrant0607

**Comment by cblecker** [comment]
Which page are you talking about exactly? https://github.com/kubernetes ? Or somewhere else?

**Comment by xiangpengzhao** [comment]
Thanks @cblecker for so quick response! I meant https://github.com/kubernetes

**Comment by cblecker** [comment]
It's sorted by "Last updated". It's a Github thing, and I don't believe there is a knob to change it to anything different. An org owner like Brian would have to 100% confirm.

**Comment by xiangpengzhao** [comment]
@cblecker Thanks for explanation!
@bgrant0607 Could you please check the org settings and confirm this? Thanks!

**Comment by eparis** [comment]
An organization (like a user) can ping repositories at the top. Kube has pinned `kuberetes`, `community`, and `features`. Otherwise than pinning (which we seem to have already done appropriately) there is no option.

**Comment by xiangpengzhao** [comment]
Thanks @eparis!

**Comment by xiangpengzhao** [comment]
FYI, if I visit github on mobile phone, that will be mobile version of github. The projects under kubernetes org are listed by alphabetical order.
