### ISSUE TITLE
SURVEY REQUEST: Kubenetes Contributor Summit EU 2024

### ISSUE THREAD

**Issue by ameukam** [kubernetes/community#7736]
### Group Requesting

Summit Staff team

### Title of Survey

Kubecon Europe Contributor Summit 2024 Attendee Survey

### Goal of Survey

To collect your feedback on the Contributor Summit and pass it along to future Summit teams

### Target Audience

Kubenetes Contributor Summit EU 2024 attendees

### Results Recipients

ameukam,salaxander

### Date Survey Starts

03/20/2024

### Date Survey Ends

04/20/2024

### Publicity Help Wanted?

Yes

### Data Analysis Wanted?

Yes

### Link to Draft Questions

N/A

**Comment by ameukam** [comment]
/area eu/summit
cc @salaxander

**Comment by jberkus** [comment]
I can take on generating the survey.

**Comment by ameukam** [comment]
We are done here. 
Survey was provided to the summit staff team.

/close
