### ISSUE TITLE
Create `etcd-security@kubernetes.io` group

### ISSUE THREAD

**Issue by ahrtr** [kubernetes/community#7739]
### Describe the issue

Currently users can report etcd vulnerabilities via `security@etcd.io` (refer to [here](https://github.com/etcd-io/etcd/blob/main/security/README.md)) which is hosted under `etcd.io` google workspace.

The pricing for the Google Workspace Business Standard subscription will change beginning March 19, 2024. So we (including sig-etcd leads, maintainers, K8s Steering Committee members @BenTheElder @mrbobbytables  and CNCF staff @idvoretskyi) agreed to terminate the etcd.io Google workspace as long as we can find an alternative for the security@etcd.io.

So requesting to setup `etcd-security@kubernetes.io` (suggested by @BenTheElder ), to replace the `security@etcd.io` with `etcd-security@kubernetes.io`.

cc
@jmhbnz 
@serathius 
@spzala 
@wenjiaswe 
@mrbobbytables 
@BenTheElder 
@idvoretskyi 
 
```[tasklist]
### Tasks
```

**Comment by ahrtr** [comment]
Could you advise the next step? @mrbobbytables @BenTheElder

**Comment by MadhavJivrajani** [comment]
@ahrtr I believe you'll have to PR it in, create a dir here for `sig-etcd`: https://github.com/kubernetes/k8s.io/tree/main/groups 

After that, you can create a group in there similar to 
https://github.com/kubernetes/k8s.io/blob/2a49f086c136c95eb219a4ba7a8c10f3839fc48a/groups/sig-security/groups.yaml#L2

And once the PR merges, the post submit should pick it up and create the group accordingly.

**Comment by ahrtr** [comment]
Thanks @MadhavJivrajani . Just created https://github.com/kubernetes/k8s.io/pull/6542

**Comment by mrbobbytables** [comment]
sorry I missed this @ahrtr my notifications are 💩 for pings >_<
sounds like its moving forward though, and I'm cc'ed on the other thread 👍
