### ISSUE TITLE
some Group map error while using Kubectl commands in Jenkinsfile on a conatiner

### ISSUE THREAD

**Issue by Ramuimmadi** [kubernetes/community#776]
[sample-app_canary-BTNON2ANXDYAVLIOVE655HRPGQPTQMEIL3SOYOZ6LNOQWL2O5JVA] Running shell script
+ kubectl --namespace=production apply -f k8s/services/
error: group map[autoscaling:0xc820374cb0 componentconfig:0xc820374d90 extensions:0xc820374e00 federation:0xc820374af0 :0xc820374b60 apps:0xc820374bd0 authorization.k8s.io:0xc820374c40 batch:0xc820374d20 policy:0xc820374e70 rbac.authorization.k8s.io:0xc820374ee0 authentication.k8s.io:0xc820374fc0 certificates.k8s.io:0xc8202cd030] is already registered
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE

**Comment by cblecker** [comment]
Hi @Ramuimmadi,
I'm sorry, but this isn't the right place for this issue.

You may wish to check our documentation and user support channels to see if someone has run into the same issue:
  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

If you've checked those sources, and still think it's a bug, you can open an [issue](https://github.com/kubernetes/kubernetes/issues/new) against our main code repository. If you do, please follow the issue template closely to ensure that all the information required is provided for someone to review and triage your potential bug.

Thanks for using Kubernetes!

The Kubernetes Team

---
/close

**Comment by Ramuimmadi** [comment]
Thank you for responding
