### ISSUE TITLE
REQUEST: need event's icon

### ISSUE THREAD

**Issue by KeyOfSpectator** [kubernetes/community#7793]
### Maybe we need Event's icon. 

Maybe we need Event's icon. 
It is not exist in icon set: https://github.com/kubernetes/community/blob/master/icons/README.md

**Comment by palnabarun** [comment]
Hi, which event's icon are you talking about? Please add more context to the issue.

**Comment by KeyOfSpectator** [comment]
Sorry, my bad. I m looking for the logo of the Event entity in Kubernetes.
