### ISSUE TITLE
CrashLoopBack goes to container log to be view in Kibana

### ISSUE THREAD

**Issue by bamb00** [kubernetes/community#780]
Would it be helpful or have value for monitoring when a pod terminate (terminationMessagePath) for some unknown reason, for example the "CrashLoopBackOff" and the user can use Kibana to locate the Kubernetes node that has the app crash?  This would help out the user trying to identified which Kubernetes nodes with the crash error when there are hundreds of nodes.  In Kibana, I can see the information about the pod with the "CrashLoopBack" but cannot see the actual value "CrashLoopBack" in the log and message. 

***********************************************************************************************************
      **containerStatuses**:
          - containerID: docker://9649c26527cf0e1cd3bd67ba9c606c0b78e6b4f08bacf96175627ddc7d250772
           image: debian
           imageID: docker-pullable://docker.io/debian@sha256:7d067f77d2ae5a23fe6920f8fbc2936c4b0d417e9d01b26372561860750815f0
          **lastState**:
          terminated:
          containerID: docker://9649c26527cf0e1cd3bd67ba9c606c0b78e6b4f08bacf96175627ddc7d250772
          exitCode: 0
          finishedAt: 2017-07-05T17:00:22Z
          **message: |
                 Sleep expired**
          reason: Completed
          startedAt: 2017-07-05T17:00:12Z
          name: dt-termination-demo
         ready: false
         restartCount: 30
         state:
         waiting:
           **message**: Back-off 5m0s restarting failed container=dt-termination-demo pod=dt-
                        termination-demo-2814930607-8kshj_default(8c247b15-6190-11e7-acb7-00505691210d)
           **reason**: CrashLoopBackOff
***********************************************************************************************************

**Comment by cblecker** [comment]
Hi @bamb00,
I'm sorry, but this isn't the right place for this issue.

You may wish to check our documentation and user support channels to see if someone has run into the same issue:
  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

If you've checked those sources, and still think there is a feature request that hasn't already been asked, you can open an [issue](https://github.com/kubernetes/kubernetes/issues/) against our main code repository. If you do, please follow the issue template closely to ensure that all the information required is provided for someone to review and triage your feature request.

Thanks for using Kubernetes!

The Kubernetes Team

---
/close
