### ISSUE TITLE
SIG CLI: Leadership Change

### ISSUE THREAD

**Issue by soltysh** [kubernetes/community#7803]
### SIG/WG name:

SIG CLI

### Onboarding Lead(s):

@ardaguclu

### Offboarding Lead(s):

@KnVerey

### Link to discussion:

https://groups.google.com/g/kubernetes-sig-cli/c/HVga6JFj7mQ/m/8sfERjerAAAJ

### Prerequisites for new leads:

- [x] Are a [Kubernetes Org member](https://git.k8s.io/community/community-membership.md)
- [x] Have completed the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Onboarding / Offboarding tasks:

- [ ] Updated [sigs.yaml](https://git.k8s.io/community/sigs.yaml) and associated [generated files](https://git.k8s.io/community/generator) (ran `make`). **NOTE:** If offboarding, remember to add to emeritus. https://github.com/kubernetes/community/pull/7829
- [ ] Updated [OWNERS_ALIASES](https://git.k8s.io/org/OWNERS_ALIASES) in [kubernetes/org](https://git.k8s.io/org/). https://github.com/kubernetes/org/pull/4891
- [ ] Updated [milestone maintainers team](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml) in [kubernetes/org](https://git.k8s.io/org/). https://github.com/kubernetes/org/pull/4891
- [ ] Checked for and updated any other potential teams in [kubernetes/org](https://git.k8s.io/org/). https://github.com/kubernetes/org/pull/4891
- [ ] Updated [OWNERS_ALIASES](https://git.k8s.io/enhancements/OWNERS_ALIASES) in [kubernetes/enhancements](https://github.com/kubernetes/enhancements). https://github.com/kubernetes/enhancements/pull/4587
- [ ] Updated [OWNERS_ALIASES](https://git.k8s.io/k8s.io/OWNERS_ALIASES) in [kubernetes/k8s.io](https://git.k8s.io/k8s.io/). https://github.com/kubernetes/k8s.io/pull/6738
- [ ] Updated feature-approvers in [OWNERS_ALIASES](https://git.k8s.io/kubernetes/OWNERS_ALIASES) in [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes) (when applicable) https://github.com/kubernetes/kubernetes/pull/124416
- [ ] Updated [membership](https://git.k8s.io/k8s.io//groups/groups.yaml) of the [leads mailing list](https://groups.google.com/a/kubernetes.io/g/leads) https://github.com/kubernetes/k8s.io/pull/6738
- [ ] Updated membership for any other [mailing list / groups](https://git.k8s.io/k8s.io//groups/).
- [x] Added to `#chairs-and-techleads` slack channel.
- [ ] Updated ownership of group leads mailing list.
- [ ] Updated ownership of group mailing list.
- [ ] Updated ownership of group calendar.
- [ ] Updated access/teams in 1password. (Contact ContribEx leads to complete)

**Comment by pacoxu** [comment]
All PR are merged. 
/close
