### ISSUE TITLE
annual report KEP listings are very very wrong

### ISSUE THREAD

**Issue by danwinship** [kubernetes/community#7847]
### Describe the issue

Looking at https://raw.githubusercontent.com/kubernetes/community/88d47c125f9340f6d7733a3b61191591371963e9/sig-network/annual-report-2023.md, there is a big problem with the KEPs. The generator seems to have assumed that the `milestone` sections of `kep.yaml` were authoritative about what has shipped, but the documentation for that field in [the template `kep.yaml`](https://github.com/kubernetes/enhancements/blob/fb9265b6fb3f5b19b1bc0d61df506f3e8aebb2c4/keps/NNNN-kep-template/kep.yaml#L32) says that it is "The milestone at which this feature was, _or is targeted to be_, at each stage", implying that it's more about hopes and dreams. In particular, whatever generated the list of KEPs appears to have not compared `milestone` to `stage` or `latest-milestone`, and so just cheerfully declared that things like [Dual Stack API Server](https://github.com/kubernetes/enhancements/blob/3feb698013b4c227686a972e1da7e93e5fd0dcee/keps/sig-network/2438-dual-stack-apiserver/kep.yaml) (currently pre-alpha) and [AdminNetworkPolicy](https://github.com/kubernetes/enhancements/blob/3feb698013b4c227686a972e1da7e93e5fd0dcee/keps/sig-network/2091-admin-network-policy/kep.yaml) (currently alpha) are now GA, merely because they had _originally_ been targeted at being GA by now.

(Also, the "this was autogenerated" comment appears in the wrong section of the template...)

**Comment by palnabarun** [comment]
The generated data is also suggestive and is designed to help SIG leads have a pre-fetched list of KEPs that they can edit when they update the Annual Report for final submission. Many leads had mentioned earlier that Annual Reports were heavy and needed to trim this and help them with information. We will make that more explicit in the section.

> "The milestone at which this feature was, or is targeted to be, at each stage", implying that it's more about hopes and dreams.

Separate discussion: Like the milestone section, which is suggestive and not authoritative, the annual report is also a draft one unless SIG leads submit an updated PR. It is reviewed first inside the SIG and then reviewed by the steering liaisons.

> (Also, the "this was autogenerated" comment appears in the wrong section of the template...)

I've taken feedback on this. We will correct it for the next cycle.

**Comment by danwinship** [comment]
> the annual report is also a draft one unless SIG leads submit an updated PR

Are you going to remove the ones that don't get updated? Or will the incorrect info just stay there in that case?

Adding the autogenerated data inside a comment might be better, to prevent it from being "exposed" if the report never gets updated.

**Comment by palnabarun** [comment]
> Are you going to remove the ones that don't get updated? Or will the incorrect info just stay there in that case?

That is on the cards actually. A few months back we (steering) discussed to remove annual report drafts that were never updated. It makes more sense to not keep them.

> Adding the autogenerated data inside a comment might be better, to prevent it from being "exposed" if the report never gets updated.

This is a good feedback. We can do that update for the next cycle. Thanks @danwinship 🙌🏽

**Comment by Priyankasaggu11929** [comment]
Hi @danwinship @palnabarun, 

Commit https://github.com/kubernetes/community/commit/11d1a666706342cdfa558beaa7c21613a041e2dd addressed the following two feedback:


> the "this was autogenerated" comment appears in the wrong section of the template

> Adding the autogenerated data inside a comment might be better, to prevent it from being "exposed" if the report never gets updated.

Is it ok to close this issue as completed? OR,
we need to keep this open to track further improvements in the autogeneration of KEP list?
