### ISSUE TITLE
WG Serving: Group creation

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/community#7850]
### SIG/WG name:

WG Serving

### Onboarding Lead(s):

@ArangoGutierrez,@SergeyKanzhelev,@terrytangyuan

### Link to discussion:

https://groups.google.com/g/kubernetes-sig-architecture/c/-DvFBA0805k

### Prerequisites for new leads:

- [X] Are a [Kubernetes Org member](https://git.k8s.io/community/community-membership.md)
- [x] Have completed the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Onboarding / Offboarding tasks:

- [x] Updated [sigs.yaml](https://git.k8s.io/community/sigs.yaml) and associated [generated files](https://git.k8s.io/community/generator) (ran `make`). https://github.com/kubernetes/community/pull/7823
- [x] Updated [OWNERS_ALIASES](https://git.k8s.io/org/OWNERS_ALIASES) in [kubernetes/org](https://git.k8s.io/org/): https://github.com/kubernetes/org/pull/4919
- [X] Updated [milestone maintainers team](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml) in [kubernetes/org](https://git.k8s.io/org/): **N/A, will follow up if needed**
- [X] Checked for and updated any other potential teams in [kubernetes/org](https://git.k8s.io/org/):  **N/A, will follow up if needed**
- [X] Updated [OWNERS_ALIASES](https://git.k8s.io/enhancements/OWNERS_ALIASES) in [kubernetes/enhancements](https://github.com/kubernetes/enhancements): **not needed, will be auto-synced. No KEPs may be owned by WG**
- [x] Updated [OWNERS_ALIASES](https://git.k8s.io/k8s.io/OWNERS_ALIASES) in [kubernetes/k8s.io](https://git.k8s.io/k8s.io/): part of https://github.com/kubernetes/k8s.io/pull/6758
- [X] Updated feature-approvers in [OWNERS_ALIASES](https://git.k8s.io/kubernetes/OWNERS_ALIASES) in [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes) (when applicable): **N/A**
- [X] Updated [membership](https://git.k8s.io/k8s.io//groups/groups.yaml) of the [leads mailing list](https://groups.google.com/a/kubernetes.io/g/leads): **N/A**
- [X] Updated membership for any other [mailing list / groups](https://git.k8s.io/k8s.io//groups/): **N/A**
- [X] Added to `#chairs-and-techleads` slack channel: [added](https://kubernetes.slack.com/archives/CD6LAC15M/p1714163284648569)
- [x] Updated ownership of group leads mailing list: https://github.com/kubernetes/k8s.io/pull/6758
- [x] Updated ownership of group mailing list: https://github.com/kubernetes/community/pull/7830
- [X] Updated ownership of group calendar: [Calendar created](https://calendar.google.com/calendar/u/0?cid=ZTg5NmI3Njk3NDNmMzg3N2VkZmFiMmQ0YzZhMTQxMzJiMmFhNTMyODcwMjFlOWJiZjExM2NhYjY3NmRhNTRiYUBncm91cC5jYWxlbmRhci5nb29nbGUuY29t)
- [ ] Updated access/teams in 1password. (Contact ContribEx leads to complete)
- [x] Update permissions for the corresponding Youtube playlists. (Contact [YouTube moderators](https://github.com/kubernetes/community/blob/master/communication/moderators.md#youtube-channel)): https://github.com/kubernetes/community/pull/7862

### Labels:

/sig apps

**Comment by terrytangyuan** [comment]
> Have completed the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

I have taken this course.

**Comment by SergeyKanzhelev** [comment]
> > Have completed the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
> 
> I have taken this course.

Me too. @ArangoGutierrez?

**Comment by ArangoGutierrez** [comment]
> > > Have completed the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
> > 
> > 
> > I have taken this course.
> 
> Me too. @ArangoGutierrez?

I have taken the course

**Comment by terrytangyuan** [comment]
> Have completed the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

@Jeffwan Can you confirm that you've taken this course?

**Comment by Jeffwan** [comment]
@terrytangyuan this is done on my side. the progress was tracked in a separate issue https://github.com/kubernetes/community/issues/7876.

**Comment by terrytangyuan** [comment]
We only have one item remaining, not sure if it's needed though:
> Updated access/teams in 1password. (Contact ContribEx leads to complete)

**Comment by SergeyKanzhelev** [comment]
I asked about it and never got any response. Also there is no documentation about it. So I think we can jsut disregard this.
