### ISSUE TITLE
WG-Device-Management: Creation

### ISSUE THREAD

**Issue by johnbelamaric** [kubernetes/community#7863]
### SIG/WG name:

WG Device Management

### Onboarding Lead(s):

johnbelamaric, klueska, pohly

### Prerequisites for new leads:

- [X] Are a [Kubernetes Org member](https://git.k8s.io/community/community-membership.md)
- [ ] Have completed the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Onboarding / Offboarding tasks:

- [X] Updated [sigs.yaml](https://git.k8s.io/community/sigs.yaml) and associated [generated files](https://git.k8s.io/community/generator) (ran `make`). **NOTE:** If offboarding, remember to add to emeritus.
- [x] Updated [OWNERS_ALIASES](https://git.k8s.io/org/OWNERS_ALIASES) in [kubernetes/org](https://git.k8s.io/org/) - https://github.com/kubernetes/org/pull/4927
- [X] Updated [milestone maintainers team](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml) in [kubernetes/org](https://git.k8s.io/org/) - *N/A*
- [x] Checked for and updated any other potential teams in [kubernetes/org](https://git.k8s.io/org/) - https://github.com/kubernetes/org/pull/4927
- [X] Updated [OWNERS_ALIASES](https://git.k8s.io/enhancements/OWNERS_ALIASES) in [kubernetes/enhancements](https://github.com/kubernetes/enhancements) *N/A*
- [x] Updated [OWNERS_ALIASES](https://git.k8s.io/k8s.io/OWNERS_ALIASES) in [kubernetes/k8s.io](https://git.k8s.io/k8s.io/) - https://github.com/kubernetes/k8s.io/pull/6770
- [X] Updated feature-approvers in [OWNERS_ALIASES](https://git.k8s.io/kubernetes/OWNERS_ALIASES) in [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes) - *N/A*
- [X] Updated [membership](https://git.k8s.io/k8s.io//groups/groups.yaml) of the [leads mailing list](https://groups.google.com/a/kubernetes.io/g/leads) - *N/A*
- [X] Updated membership for any other [mailing list / groups](https://git.k8s.io/k8s.io//groups/).
- [X] Added to `#chairs-and-techleads` slack channel.
- [x] Updated ownership of group leads mailing list - https://github.com/kubernetes/k8s.io/pull/6770
- [x] Updated ownership of group mailing list - https://github.com/kubernetes/k8s.io/pull/6770
- [x] Updated ownership of group calendar.
- [ ] Updated access/teams in 1password. (Contact ContribEx leads to complete)
- [x] Update permissions for the corresponding Youtube playlists. (Contact [YouTube moderators](https://github.com/kubernetes/community/blob/master/communication/moderators.md#youtube-channel))

### Labels:

/sig architecture

**Comment by CIPHERTron** [comment]
New playlist created ➡️  https://www.youtube.com/playlist?list=PL69nYSiGNLP1kac4zsH0INEWEZlPhOhlp

**Comment by johnbelamaric** [comment]
> New playlist created ➡️ https://www.youtube.com/playlist?list=PL69nYSiGNLP1kac4zsH0INEWEZlPhOhlp

Thanks!
