### ISSUE TITLE
Broken links in sig-scalability README file

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes/community#7869]
### Describe the issue

The following links under `Contact/GitHub-Teams`in [sig-scalability README](https://github.com/kubernetes/community/blob/master/sig-scalability/README.md) don't exist and return `404` errors.

[@kubernetes/sig-scalability-api-reviews](https://github.com/orgs/kubernetes/teams/sig-scalability-api-reviews) - API Changes and Reviews
[@kubernetes/sig-scalability-bugs](https://github.com/orgs/kubernetes/teams/sig-scalability-bugs) - Bug Triage and Troubleshooting
[@kubernetes/sig-scalability-feature-requests](https://github.com/orgs/kubernetes/teams/sig-scalability-feature-requests) - Feature Requests
[@kubernetes/sig-scalability-misc](https://github.com/orgs/kubernetes/teams/sig-scalability-misc) - General Discussion
[@kubernetes/sig-scalability-proprosals](https://github.com/orgs/kubernetes/teams/sig-scalability-proprosals) - Design Proposals
[@kubernetes/sig-scalability-test-failures](https://github.com/orgs/kubernetes/teams/sig-scalability-test-failures) - Test Failures and Triag

**Comment by vaibhav2107** [comment]
It is because that these links are redirecting to the github teams but that teams are not defined. There are only [three teams](https://github.com/orgs/kubernetes/teams?query=scalability) for sig-scalability

**Comment by yuanchen8911** [comment]
> @yuanchen8911 The team for PR reviews is there and hence the link [@kubernetes/sig-scalability-pr-reviews](https://github.com/orgs/kubernetes/teams/sig-scalability-pr-reviews) is working. You can update the issue description to remove this one.

Updated the description. Here's the PR to fix it: https://github.com/kubernetes/community/pull/7873
