### ISSUE TITLE
WG Serving: add Jeffwan as a chair

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/community#7876]
### SIG/WG name:

WG Serving

### Onboarding Lead(s):

Jeffwan

### Link to discussion:

https://docs.google.com/document/d/1aExJFtaLnO-TM6_2uILgI8NI0IjOm7FcwLABBKEMEo0/edit#bookmark=id.3c8m1rmc4z45

### Prerequisites for new leads:

- [x] Are a [Kubernetes Org member](https://git.k8s.io/community/community-membership.md)
- [x] Have completed the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Onboarding / Offboarding tasks:

- [ ] Updated [sigs.yaml](https://git.k8s.io/community/sigs.yaml) and associated [generated files](https://git.k8s.io/community/generator) (ran `make`). https://github.com/kubernetes/community/pull/7877
- [ ] Updated [OWNERS_ALIASES](https://git.k8s.io/org/OWNERS_ALIASES) in [kubernetes/org](https://git.k8s.io/org/): https://github.com/kubernetes/org/pull/4932
- [x] Updated [milestone maintainers team](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml) in [kubernetes/org](https://git.k8s.io/org/): **N/A**.
- [x] Checked for and updated any other potential teams in [kubernetes/org](https://git.k8s.io/org/): **N/A**.
- [x] Updated [OWNERS_ALIASES](https://git.k8s.io/enhancements/OWNERS_ALIASES) in [kubernetes/enhancements](https://github.com/kubernetes/enhancements): **N/A**.
- [ ] Updated [OWNERS_ALIASES](https://git.k8s.io/k8s.io/OWNERS_ALIASES) in [kubernetes/k8s.io](https://git.k8s.io/k8s.io/): https://github.com/kubernetes/k8s.io/pull/6782
- [x] Updated feature-approvers in [OWNERS_ALIASES](https://git.k8s.io/kubernetes/OWNERS_ALIASES) in [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes) (when applicable): **N/A**.
- [ ] Updated [membership](https://git.k8s.io/k8s.io//groups/groups.yaml) of the [leads mailing list](https://groups.google.com/a/kubernetes.io/g/leads): https://github.com/kubernetes/k8s.io/pull/6782/
- [x] Updated membership for any other [mailing list / groups](https://git.k8s.io/k8s.io//groups/): **N/A**.
- [X] Added to `#chairs-and-techleads` slack channel: added
- [ ] Updated ownership of group leads mailing list:  https://github.com/kubernetes/k8s.io/pull/6782
- [ ] Updated ownership of group mailing list:  https://github.com/kubernetes/k8s.io/pull/6782
- [X] Updated ownership of group calendar.
- [ ] Updated access/teams in 1password. (Contact ContribEx leads to complete)
- [X] Update permissions for the corresponding Youtube playlists. (Contact [YouTube moderators](https://github.com/kubernetes/community/blob/master/communication/moderators.md#youtube-channel))

### Labels:

/wg serving

**Comment by Jeffwan** [comment]
> Have completed the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

@SergeyKanzhelev I finish the training and I am a member of kubernetes org so you can check first two boxed. Thanks!

**Comment by pacoxu** [comment]
> - [ ] Updated access/teams in 1password. (Contact ContribEx leads to complete)

All PR are merged.
We may close this issue if the 1password team is updated.

Congrats. 🎉

**Comment by SergeyKanzhelev** [comment]
> We may close this issue if the 1password team is updated.

We will probably manage it old way. Nobody replies on questions about 1password and there is no documentation on a website that I can find
