### ISSUE TITLE
REQUEST: Boost communication about Etcd Operator Survey

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#7897]
### What do you want send out?(Please include a link to a draft)

Please [share out this survey](https://forms.gle/5gBpzaxYtuQPWdBo9) with the Kubernetes community:

Sample text:

```
Kubernetes SIG-Etcd and SIG-Cluster-Lifecycle are planning to develop an official etcd operator. This operator is specifically for people who run etcd clusters in addition to the one embedded in Kubernetes. In the first step, we'd like to collect feedback from the community. Please kindly fill in the following survey when you get a couple of minutes. Thanks.

https://forms.gle/5gBpzaxYtuQPWdBo9
```

The survey has already been shared with etcd-dev, kubernetes-dev, and #sig-etcd and #surveys channels.  Appropriate additional shares would include #announcements, social media, and LWKD.

**Comment by jberkus** [comment]
Added to LWKD draft

**Comment by chris-short** [comment]
So etcd has a Twitter account, it would make sense for us to boost that in addition to the Comms posting about the it directly.

@jberkus Do we want this going to LinkedIn? I think that's a more end user audience at the moment but, I'm not going to exclude it unless you want us too (which means we should probably have some kind of network selection mechanism in our template cc @mfahlandt).

**Comment by jberkus** [comment]
Yes, we want it on Linkedin.  We're trying to reach end users.

**Comment by jberkus** [comment]
This survey is over.

/close
