### ISSUE TITLE
Is Kubernetes Icon missing in Icon Set ?

### ISSUE THREAD

**Issue by omuomugin** [kubernetes/community#7905]
### Describe the issue

https://github.com/kubernetes/community/tree/master/icons 
Thank you for those wide variety of icons and this is saving my days to draw system diagrams.
However I could not find Kubernetes Icon it self here but am I missing something or is it intended ?

**Comment by MadhavJivrajani** [comment]
@omuomugin you should be able to find that here: https://github.com/kubernetes/kubernetes/tree/master/logo 

Feel free to link this in the page you mentioned!

/close
