### ISSUE TITLE
Create agenda doc, folder for incoming WG-Etcd-Operator

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#7937]
Per #7917, please create a folder and a blank agenda doc for WG-Etcd-Operator on the multi-sig shared drive (I don't have access).

Owners should be Benjamin Wang, Ciprian Hacman, James Blair, and me.  Will share email addresses via Slack.

/assign @palnabarun

**Comment by ahrtr** [comment]
The PR (creation of etcd-operator) has already been merged, could we get this resolved asap? Thanks .

@palnabarun @soltysh

> Owners should be Benjamin Wang, Ciprian Hacman, James Blair, and me.

Please add @justinsb as well.

**Comment by jberkus** [comment]
The working group has been approve, please proceed.

**Comment by ahrtr** [comment]
ping @palnabarun @soltysh

The first regular meeting will be held next Tuesday (Aug 6th), could you please get this resolved?

**Comment by mrbobbytables** [comment]
The directory is created, but before we can really share it out the mailing list groups need to be created (for permissions purposes)

**Comment by mrbobbytables** [comment]
> Note WG etcd-operator will reuse some of the SIG-etcd's resources,
> 
>     * mailing list: https://groups.google.com/g/etcd-dev

Just saw this, that is okay for the general user list - but we need to create a leads list to own the share

**Comment by kvaps** [comment]
In case if WG will decide to take our etcd-operator code base, we can transfer ownership of our mailing list:
```
https://groups.google.com/g/etcd-operator-dev/
```

**Comment by ahrtr** [comment]
> but we need to create a leads list to own the share

Thanks @mrbobbytables .  Please add all organizers https://github.com/kubernetes/community/tree/master/wg-etcd-operator#organizers

**Comment by mrbobbytables** [comment]
@ahrtr I'm not really involved in the process anymore^^;;
Here is an example PR of how to add it:
https://github.com/kubernetes/k8s.io/pull/6758

The settings you want to have are:
```
AllowWebPosting: "true"
ReconcileMembers: "true"
WhoCanPostMessage: "ANYONE_CAN_POST"
WhoCanModerateContent: "OWNERS_AND_MANAGERS"
```

There are also some settings that need to be set manually:
Posting policies - > Conversation history -> On
Posting policies -> Who can reply privately to authors -> Group Members
Posting policies -> Who can moderate metadata -> Group Managers

**Comment by ahrtr** [comment]
Thanks @mrbobbytables for the guide.  

Just created https://github.com/kubernetes/k8s.io/pull/7125

**Comment by ahrtr** [comment]
https://github.com/kubernetes/k8s.io/pull/7125 has been merged. @Priyankasaggu11929

**Comment by ahrtr** [comment]
The google doc has been created https://docs.google.com/document/d/1ey4zTTRvtCVJJP2vjF95VjG-sAKlNTcqB2HdmC18Lfc/edit#heading=h.7hqjndol0olh, thanks all for the help. Please feel free to close this ticket.
