### ISSUE TITLE
container finished log does not include pod name - this makes it difficult to identify out of memory kills

### ISSUE THREAD

**Issue by allen-ziegenfus** [kubernetes/community#7955]
### Describe the issue

When a container dies due to OOMKill, there are these types of logs generated: 

`kubelet.go:2447] "SyncLoop (PLEG): event for pod" pod="<namespace/pod template hash>"`

`generic.go:334] "Generic (PLEG): container finished" podID="<podid....>" containerID="<containerid...>" exitCode=137`

Would it be possible to consistently log the pod name (namespace/template hash) in the container finished log message (https://github.com/kubernetes/kubernetes/blob/57645002432c52aa743e69739613ca337616441a/pkg/kubelet/pleg/generic.go#L334) ? 

From the definition of the Pod struct it appears that this information would also be available in `generic.go`

This would make the log messages more consistent and make it easier to find OOM kills by pod name. Currently it involves having to find the podID which makes it difficult to find these messages.

**Comment by moatorres** [comment]
Accurate. I second @allen-ziegenfus on that. Although we can dig deep into kubelet logs to find this information, it could simply be more explicit and user friendly.

**Comment by aojea** [comment]
/sig node
/kind feature

I don't know if this will be better open in kubernetes/kubernetes

**Comment by vunnamkowsik** [comment]
can I work on this feature.

**Comment by allen-ziegenfus** [comment]
Thanks @aojea   - I should have done that. Create it now: https://github.com/kubernetes/kubernetes/issues/125785

@vunnamkowsik  thanks for your interest! If you could help me figure out how to change this that'd be great
