### ISSUE TITLE
Add credits list for KCS designs

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#7964]
### Describe the issue

Now that a bunch of the KCS designs are uploaded to this repo, we need a README giving credit for the creators of each design.  Filing this issue so that we don't forget to do it.

/sig contributor-experience
/area events

cc @kas

**Comment by aakankshabhende** [comment]
@jberkus I'm interested in working on this. Could you please assign me this?

**Comment by jberkus** [comment]
Oh!  Sorry, someone already did the credits list.  Closing this issue.  I'm sure you can find something else?

/close
