### ISSUE TITLE
Limits around the number of CRs

### ISSUE THREAD

**Issue by fabiand** [kubernetes/community#798]
We - KubeVirt - are using, like others, currently TPRs, but will move to UAS/AAS for our custom APi extensions. But even with UAS we can [hopefully rely on Kubernetes](kubernetes/kubernetes/issues/46351) for storing our objects i.e. in CRDs.
With this coming up I actually wondered if there could be official limits for the number of CRD or TPR objects in Kubernetes.

Those limits should be part of https://github.com/kubernetes/community/blob/master/sig-scalability/goals.md

**Comment by cblecker** [comment]
@kubernetes/sig-scalability-misc

**Comment by spiffxp** [comment]
Maybe https://github.com/kubernetes/community/blob/master/sig-scalability/thresholds.md instead of goals.md but yeah it's missing TPR's or CRD's.  There's probably an open question of whether we wait for a resource to be alpha/beta/GA before attempting to declare or hold to such a limit.

@kubernetes/sig-scalability-misc any thoughts?

**Comment by lavalamp** [comment]
I think this is bigger than just CRDs. I am thinking about object count quotas in general.

**Comment by nikhita** [comment]
xref https://github.com/kubernetes/kubernetes/issues/53777

**Comment by khatamnejad** [comment]
Is someone working on this issue and/or quota [support for custom resources](https://github.com/kubernetes/kubernetes/issues/53777) actively? If no one is working on them, I think I should be able to do so.

**Comment by liggitt** [comment]
see the referenced issue: https://github.com/kubernetes/kubernetes/issues/53777#ref-pullrequest-325716240

PR open: https://github.com/kubernetes/kubernetes/pull/64201

currently blocked on generic lister/informer support (see https://github.com/kubernetes/kubernetes/pull/64201#issuecomment-392086703)

**Comment by fabiand** [comment]
Thanks for finding this incosnsitency - As you said: It's about hte number of CRs

**Comment by bukzor** [comment]
@nikhita I was hoping to use CRD quotas to model our cluster-scoped limited resource: software licenses. Is there a better way I should do this? Or does this provide a valid use case of cluster-scoped quotas?

**Comment by ktrOpenSource** [comment]
@nikhita 
Can resource quota be used to apply Hard limits on number of objects - across the cluster - irrespective of namespace.

Eg: Can I say max 10k objects of CRD type "example.com/toys" across namespace a,b,c,d,e ?

**Comment by lavalamp** [comment]
This issue should probably be in k/k. I recommend closing and opening a new one (or finding an existing dup).

I don't think there's a clusterwide option like that, @yliaog can correct me if I'm wrong.

**Comment by yliaog** [comment]
correct, that is not supported today

**Comment by mrbobbytables** [comment]
Going to go with lavalamp's suggestion. This won't really get any visibility here in the community repo. =/ 

If this is something you'd still like to see, please go ahead and open an issue in [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes).

/close
