### ISSUE TITLE
Re-activating my Slack account

### ISSUE THREAD

**Issue by alongchamps** [kubernetes/community#7982]
### Describe the issue

My Slack account on the Kubernetes workspace has been deactivated for a while and I can't reactivate it myself because the invite page says Error: user_disabled.

Please reactivate `a.j.longchamps@gmail.com` for me. Thanks!

**Comment by jberkus** [comment]
/hold

Please do not act on this, contacting the requestor.

**Comment by jberkus** [comment]
I have been attempting to contact the requestor, who has several accounts, some of them active.  I have been unable to contact them.  As such, I am closing this issue.  alongchamps, if you come back, you can re-request.

/close
