### ISSUE TITLE
SIG Node: Leadership Change

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/community#8011]
### SIG/WG name:

SIG Node

### Onboarding Lead(s):

haircommander

### Link to discussion:

https://groups.google.com/g/kubernetes-sig-node/c/Vc2DgfLM1Aw/m/sw8twhW4AwAJ

### Prerequisites for new leads:

- [x] Are a [Kubernetes Org member](https://git.k8s.io/community/community-membership.md)
- [x] Have completed the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Onboarding / Offboarding tasks:

- [x] Updated [sigs.yaml](https://git.k8s.io/community/sigs.yaml) and associated [generated files](https://git.k8s.io/community/generator) (ran `make`). https://github.com/kubernetes/community/pull/8014
- [x] Updated [OWNERS_ALIASES](https://git.k8s.io/org/OWNERS_ALIASES) in [kubernetes/org](https://git.k8s.io/org/). https://github.com/kubernetes/org/pull/5104
- [x] Updated [milestone maintainers team](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml) in [kubernetes/org](https://git.k8s.io/org/). https://github.com/kubernetes/org/pull/5104
- [x] Checked for and updated any other potential teams in [kubernetes/org](https://git.k8s.io/org/). https://github.com/kubernetes/org/pull/5104
- [x] Updated [OWNERS_ALIASES](https://git.k8s.io/enhancements/OWNERS_ALIASES) in [kubernetes/enhancements](https://github.com/kubernetes/enhancements). https://github.com/kubernetes/enhancements/pull/4790
- [x] Updated [OWNERS_ALIASES](https://git.k8s.io/k8s.io/OWNERS_ALIASES) in [kubernetes/k8s.io](https://git.k8s.io/k8s.io/). https://github.com/kubernetes/k8s.io/pull/7174
- [x] Updated feature-approvers in [OWNERS_ALIASES](https://git.k8s.io/kubernetes/OWNERS_ALIASES) in [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes) (when applicable) https://github.com/kubernetes/kubernetes/pull/126696
- [x] Updated [membership](https://git.k8s.io/k8s.io//groups/groups.yaml) of the [leads mailing list](https://groups.google.com/a/kubernetes.io/g/leads) https://github.com/kubernetes/k8s.io/pull/7174
- [x] Updated membership for any other [mailing list / groups](https://git.k8s.io/k8s.io//groups/). https://github.com/kubernetes/k8s.io/pull/7160
- [x] Added to `#chairs-and-techleads` slack channel.
- [x] Updated ownership of group leads mailing list (switching to kubernetes.io lists, N/A)
- [x] Updated ownership of group mailing list.
- [x] Updated ownership of group calendar.
- [x] Updated access/teams in 1password. (Contact ContribEx leads to complete)
- [x] Update permissions for the corresponding Youtube playlists. (Contact [YouTube moderators](https://github.com/kubernetes/community/blob/master/communication/moderators.md#youtube-channel))

### Labels:

/sig node
/assign
/cc @haircommander @dchen1107 @derekwaynecarr @mrunalp

**Comment by SergeyKanzhelev** [comment]
> * Have completed the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

@haircommander can you please confirm this is done?

**Comment by haircommander** [comment]
Yup i've done it!

**Comment by SergeyKanzhelev** [comment]
this is now complete

**Comment by haircommander** [comment]
Thanks @SergeyKanzhelev ! I'm honored to be here
