### ISSUE TITLE
Steering Committee Nomination: Sascha Grunert (@saschagrunert)

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/community#8015]
Hello Kubefriends,

I would like to self-nominate for the Kubernetes Steering Committee election in 2024.

Being able to work within this community for over the past 5 years was a true honor to me. I started my journey in SIG Release by working in the Release Notes subteam of the v1.15 release cycle. This experience was so exciting to me that I immediately decided to continue my path in SIG Release, while still working on lower level SIG Node and container runtime related topics. I truly believe that this strategy still provides me with a great overview about this project and its outstanding community! Over the past years, I was working hard on shaping the future of SIG Release, implementing features for Kubernetes and speaking at conferences like KubeCon about everything new and shiny.

Right now I’m serving as chair for SIG Release, SIG Node approver for certain areas as well as CNCF ambassador. I feel that the time is right to do the next big step and would like to positively impact the community by being part of the Kubernetes Steering Committee.

From my perspective, it’s more important to define what we, as a community, want to do in the future of this project as well as how we behave right now rather than speaking about what we did in the past. As part of the Steering Committee, I would stand for shaping the long term goals of the committee while actively working on them. Beside that, I would invest my time to evolve the overall vision of the project by standing for its goals and values. All of that should be done by providing a low and welcoming entry level for new community members as well as outlining a healthy environment for our long term contributors.

Steering Kubernetes into that direction would be a personal honor to me and I’m kindly asking for your vote.

All the best,
Sascha

> [!NOTE] 
> If you are an eligible voter interested in endorsing me, you can do so by replying to this nomination issue saying something like "I endorse this nominee, and I work for " or "+1". Please state that you are an eligible voter, and include your employer's name so that Election Officers can recognize qualified endorsements.

**Comment by kwilczynski** [comment]
+1 from me (Red Hat).

Thank you @saschagrunert for your work!

**Comment by klueska** [comment]
+1 from me at NVIDIA
I am an eligible voter

**Comment by aojea** [comment]
+1
Antonio Ojea (Google)
Elegible voter

**Comment by xmudrii** [comment]
+1 from me (Kubermatic). I'm an eligible voter.

**Comment by rikatz** [comment]
+1 from me (Broadcom). I'm an elegible voter.

**Comment by ameukam** [comment]
+1. I'm an eligible voter.

**Comment by kannon92** [comment]
+1 from me (Red Hat). I'm an eligible voter.

**Comment by Priyankasaggu11929** [comment]
Sascha Grunert has the necessary endorsements and is eligible to run in the Steering Committee election.

The candidate should prepare their candidate profile as a PR and submit it, per the instructions at: https://github.com/kubernetes/community/blob/master/elections/steering/2024/README.md#candidacy-process

**Comment by aojea** [comment]
+1 Antonio Ojea (Google). I'm an eligible voter.

**Comment by ardaguclu** [comment]
+1
Arda Guclu (Red Hat)
Eligible voter

**Comment by mrunalp** [comment]
+1 (Red Hat), eligible voter

**Comment by jeremyrickard** [comment]
+1. My employer is Microsoft, I am an eligible voter.

**Comment by SergeyKanzhelev** [comment]
+1 from me (Google)

I'm an eligible voter.

**Comment by ydFu** [comment]
+1.(cht)
I'm an eligible voter.

thanks @saschagrunert

**Comment by saschagrunert** [comment]
Thank y'all! :heart: 

Opened #8017 to add the profile.

**Comment by puerco** [comment]
I am returning from vacation and just saw this, wholehearted (and late) +1000 from me :tada:

**Comment by jasonbraganza** [comment]
+1. A bit late, hopefully not too late

I am self employed and an eligible voter

**Comment by savitharaghunathan** [comment]
+1, Red Hat. I am an eligible voter.
