### ISSUE TITLE
Steering Committee Nomination: Antonio Ojea (@aojea)

### ISSUE THREAD

**Issue by rikatz** [kubernetes/community#8016]
Hey folks,

I would like to nominate Antonio Ojea for the Kubernetes Steering Committee election 2024.

I think we all know who Antonio is and what a huge impact he had on Kubernetes for the at least the last 6 years, going from the Dual Stack implementation, being always looking into having stable tests, chasing bugs, co-maintaining KinD, floating between SIGs always being available to help and always with the commitment to raise the quality bar of code and features.

Today Antonio is one of the SIG Network and SIG Testing TL, maintainer of KinD + he has won multiple contributor awards over the years, showing his huge commitment with the Kubernetes project.

I think this is a great opportunity to have him in a different role, and additionally bring a different perspective to the Steering Committee and I would like to invite you all to show your support to Antonio.

If you are an eligible voter interested in endorsing Antonio, you can do so by replying to this nomination issue saying something like "I endorse this nominee, and I work for " or "+1". Please state that you are an eligible voter, and include your employer's name so that Election Officers can recognize qualified endorsements.

**Comment by ameukam** [comment]
+1. I'm an eligible voter.

/committee steering

**Comment by klueska** [comment]
+1 from me (NVIDIA)
I am an eligible voter

**Comment by kannon92** [comment]
+1 from me (Red Hat).
I am an eligible voter.

**Comment by Priyankasaggu11929** [comment]
Antonio Ojea has the necessary endorsements and is eligible to run in the Steering Committee election.

But @aojea does need to accept this nomination explicitly in a comment or implicitly by submitting the profile PR.

Please announce this nomination by sending an email to [dev@kubernetes.io](mailto:dev@kubernetes.io) with a link to the issue. The subject line of the email should be same as the title of the issue.

The candidate should prepare their candidate profile as a PR and submit it, per the instructions at: https://github.com/kubernetes/community/blob/master/elections/steering/2024/README.md#candidacy-process

**Comment by aojea** [comment]
I happily accept the nomination 
Thanks folks, appreciate your support

**Comment by endocrimes** [comment]
+1 from me (Fermyon).

Also an eligible voter.

**Comment by ardaguclu** [comment]
+1
Arda Guclu (Red Hat)
Eligible voter

**Comment by elmiko** [comment]
+1
Michael McCune (Red Hat)
eligible voter

**Comment by mrunalp** [comment]
+1 (Red Hat), eligible voter

**Comment by fedebongio** [comment]
+1 (Google), eligible voter

**Comment by johnbelamaric** [comment]
+1 from me, at Google

I am an eligible voter.

**Comment by SergeyKanzhelev** [comment]
+1 from me (Google)

I'm an eligible voter.

**Comment by thockin** [comment]
+1 (Google)
I'm an eligible voter.

**Comment by ydFu** [comment]
+1.(cht)
I'm an eligible voter.

thanks @rikatz

**Comment by serathius** [comment]
+1 (Google) 
I'm an eligible voter.

**Comment by jasonbraganza** [comment]
+1. A bit late, hopefully not too late

I am self employed and an eligible voter
