### ISSUE TITLE
Steering Committee Nomination: Natali Vlatko (@natalisucks)

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#8025]
I’d like to nominate Natali Vlatko, @natalisucks, to be a member of the Kubernetes Steering Committee. She is a leader whom I highly respect, admire, and trust—qualities that are essential for anyone serving on this important body.

I first met Natali at the Valencia KubeCon when she was just beginning her participation in the community. We were seatmates on a bus heading to a governance networking event, and I quickly realized that she is a good listener, inspiring storyteller, and a strong advocate for those around her. I was excited and hopeful that she would continue her involvement. Since then, I’ve watched Natali grow as a leader within SIG Docs, Kubernetes, and the broader cloud native community. 

Serving on the Steering Committee is a significant responsibility. The community is the population size of a small city, and conflicts inevitably arise. Other open source communities watch us and take notes. Her approachable personality brings calm to situations that ease people naturally. I've watched it first hand at in-person events, specifically the Contributor Summits, that Natali has played several roles in. 

Natali has consistently demonstrated the dedication and leadership qualities expected of someone in this role. She demonstrates this through elevating others within SIG Docs, SIG ContribEx, and SIG Auth by creating roles and opportunities, and her persistence in driving localization efforts has helped ensure that Kubernetes reaches communities around the world. 

I wholeheartedly support Natali’s nomination and hope you do as well.

(From the election guide) 
If you are an eligible voter and think Natali should run, please add your +1 as a comment on this issue and mention the organization you work for.

**Comment by jeremyrickard** [comment]
+1.

My employer is Microsoft.

I am an eligible voter.

**Comment by endocrimes** [comment]
+1 (Fermyon)

There are very few people I'd like to see on the steering committee as much as Natali.

After working with her in multiple capacities in the project - I have nothing but great things to say.

**Comment by ameukam** [comment]
+1

I'm an eligible voter.

**Comment by divya-mohan0209** [comment]
Easiest +1 ever 💜

My employee is SUSE.

I'm an eligible voter.

**Comment by Priyankasaggu11929** [comment]
Natali Vlatko has the necessary endorsements and is eligible to run in the Steering Committee election.

But @natalisucks does need to accept this nomination explicitly in a comment or implicitly by submitting the profile PR.

The candidate should prepare their candidate profile as a PR and submit it, per the instructions at: https://github.com/kubernetes/community/blob/master/elections/steering/2024/README.md#candidacy-process

**Comment by natalisucks** [comment]
Thank you @parispittman and everyone on this thread for your endorsements! I accept the nomination 🙏

**Comment by mbianchidev** [comment]
+1 

My employer is SyncTune.

I (should be) an eligible voter according to [my contrib score](https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=All) (119 out of the 50 required)

**Comment by Priyankasaggu11929** [comment]
> +1
> 
> My employer is SyncTune.
> 
> I (should be) an eligible voter according to [my contrib score](https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=All) (109 out of the 50 required)

Hi @mbianchidev, yes, [you are eligible](https://github.com/kubernetes/community/blob/97526afbde0a6384e3465d13f8590271a8e16229/elections/steering/2024/voters.yaml#L370).

FYI, full list of eligible voters for 2024 steering committee election is here – https://github.com/kubernetes/community/blob/master/elections/steering/2024/voters.yaml#L370

**Comment by mbianchidev** [comment]
> > +1
> > My employer is SyncTune.
> > I (should be) an eligible voter according to [my contrib score](https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=All) (109 out of the 50 required)
> 
> Hi @mbianchidev, yes, [you are eligible](https://github.com/kubernetes/community/blob/97526afbde0a6384e3465d13f8590271a8e16229/elections/steering/2024/voters.yaml#L370).
> 
> FYI, full list of eligible voters for 2024 steering committee election is here – https://github.com/kubernetes/community/blob/master/elections/steering/2024/voters.yaml

Thanks Priyanka and apologies, I didn't know about this file yet!

**Comment by strongjz** [comment]
+1

My employee is Isovalant at Cisco

I'm an eligible voter.

**Comment by eddiezane** [comment]
+1

My employer is Defense Unicorns.

I am an elgible voter.

**Comment by salaxander** [comment]
+1 

My employer is Defense Unicorns, and I'm an eligible voter.

I work with Natali on SIG docs, and there are few others that I would endorse as highly as her.

**Comment by tabbysable** [comment]
+1

I'm an eligible voter and my employer is Datadog.

**Comment by youngnick** [comment]
+1

I'm an eligible voter and my employer is Isovalent at Cisco.

**Comment by rikatz** [comment]
+1 (Broadcom)
I am an eligible voter

**Comment by jasonbraganza** [comment]
+1. I admire Natali’s contributions to the community!
I am self employed and an eligible voter

**Comment by upodroid** [comment]
+1 

I'm an eligible voter and I work at Cisco.
