### ISSUE TITLE
Steering Committee Nomination: Kat Cosgrove (@katcosgrove)

### ISSUE THREAD

**Issue by eddiezane** [kubernetes/community#8039]
Hi Kuberfriendos,

I am excited to nominate Kat Cosgrove (@katcosgrove) for the 2024 Steering Committee election.

I knew of Kat long before she knew of me -- she's kinda hard to miss. When I finally met her face-to-face, she was kind, caring, welcoming, and most importantly real and down to Earth. She pulls others around her into conversation like an orbit. You genuinely want to be her friend so she shouts your name from across the room when you walk through the door at summit. You can count on Kat to call you out when you're wrong and tell you what you actually need to hear.

Kat's first contribution to the project was helping to [ease the concerns](https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/) of the Dockershim deprecation in 2020. She eventually found a home on the release team for 1.23, and she's been an indispensable part of it ever since. With 9 Kubernetes releases under her belt (soon to be 10 as the Emeritus Advisor for 1.32), her impact is undeniable.

During the release of 1.28, Kat stepped up to address critical gaps and spearheaded policy changes that have since become cornerstones of the release process. Her contributions were recognized with a [SIG Release Contributor Award](https://www.kubernetes.dev/community/awards/2023/#release), and she now serves as a Subproject Owner of the Release Team and a Tech Lead for SIG Docs.

Release 1.30, under Kat's leadership, is widely praised as one of the smoothest releases in recent history. But don't just take my word for it:

> Kat brought a new level of accountability to the release team that has lead to a dramatic increase in the stability of releases.

\- @salaxander, 1.27 Release Lead & SIG Docs Tech Lead

> Kat has been responsible for a multitude of improvements to the release team including improvements to both the Docs (and the Docs Freeze process) and Comms subteams, and has driven meaningful changes to make the release process more efficient in terms of major themes and release notes and the unification of bug triage and ci signal. She also helped write the formal shadow and subteam lead removal guidelines to improve transparency and governance for the release teams.

\- @jeremyrickard, 1.20 Release Lead & SIG Release Co-Chair

> Kat's work on the release team has leveled up not only that team, but the whole Kubernetes project. The structures she's built have improved efficiency, transparency, and alignment, and made internal and external communication stronger. She's also done it all in a way that brings people in and helps grow future leaders!

\- @IanColdwater, SIG Security Co-Chair

Kat's proven track record of fostering stability, transparency, and community growth makes her the ideal candidate for the Steering Committee. I have no doubt that she will bring the same transformative energy to Steering that she brought to the Release Team, ultimately improving the health of the entire Kubernetes project.

If you agree, please comment a +1 on this issue and share the organization you work for.

/committee steering

**Comment by jeremyrickard** [comment]
I think it is implied by my endorsement in the issue above, but I'd like to drop an explicit +1 for @katcosgrove here. 

+1

My employer is Microsoft. 

I am an eligible voter.

**Comment by salaxander** [comment]
+1 

Last I checked I was an eligible voter. I think Kat would make a fantastic addition to the steering committee

**Comment by mpuckett159** [comment]
+1

My employer is Integral Ad Science

Hope I'm eligible since I'm a cochair.

**Comment by natalisucks** [comment]
+1!

I'm an eligible voter and my employer is Cisco.

I enthusiastically endorse Kat and think they'd continue steering our project in exactly the right direction via this role.

**Comment by ameukam** [comment]
+1

I'm eligible voter.

**Comment by tabbysable** [comment]
+1!

I'm an eligible voter and my employer is Datadog.

**Comment by youngnick** [comment]
+1

I'm an eligible voter and my employer is Isovalent at Cisco.

**Comment by endocrimes** [comment]
+1, eligible voter (Fermyon)

**Comment by katcosgrove** [comment]
Thank you so much to @eddiezane, @salaxander, @jeremyrickard, @IanColdwater, and everyone who gave this a +1. I will admit to tearing up a little. <3

I accept the nomination.

**Comment by Priyankasaggu11929** [comment]
Kat Cosgrove has the necessary endorsements and is eligible to run in the Steering Committee election.

The candidate should prepare their candidate profile as a PR and submit it, per the instructions at: https://github.com/kubernetes/community/blob/master/elections/steering/2024/README.md#candidacy-process

**Comment by JamesLaverack** [comment]
A bit late, but also +1 🎉 

I'm an eligible voter (according to Elekto). My employer is Cisco.

**Comment by divya-mohan0209** [comment]
A bit late, but +1.

I'm an eligible voter. My employer is SUSE.

**Comment by mbianchidev** [comment]
Also late but definitely a +1!

My employer is SyncTune.

**Comment by savitharaghunathan** [comment]
+1, Red Hat. I am an eligible voter
