### ISSUE TITLE
Reactivate the slack account

### ISSUE THREAD

**Issue by logica0419** [kubernetes/community#8054]
### Describe the issue

I’m eager to contribute to K8s and tried to join the K8s Slack with my main-use email address as a first step.
However, I remembered that I had once joined the workspace with the email address just for fun and disabled my account as I thought it redundant at that time.

Could you reactivate my Slack account?

My email address: `logica0419@gmail.com`

Thank you!

**Comment by jberkus** [comment]
Your account as been reactivated.  You should be able to access it via normal password recovery.
