### ISSUE TITLE
Better sig description for storage

### ISSUE THREAD

**Issue by kargakis** [kubernetes/community#806]
Forked from https://github.com/kubernetes/community/issues/441#issuecomment-285339847

@kubernetes/sig-storage-misc

**Comment by zhangxiaoyu-zidif** [comment]
Great, I like sig-storage. Hope better storage description~

**Comment by zhangxiaoyu-zidif** [comment]
Maybe we can list a 2017 plan like sig-network.
That will help us to know what could we do for k8s storge.

**Comment by kargakis** [comment]
https://github.com/kubernetes/community/tree/master/sig-storage
