### ISSUE TITLE
Export data from Surveymonkey

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#8101]
### Describe the issue

We are no longer using SurveyMonkey for surveys.  Our account there expires in one month.

The one thing we need to do before it expires is download data for most of our old surveys and store it on the ContribEx drive in a leads-only folder.

I can set you up with the necessary permissions, if anyone is available to do this.

/sig contributor-experience
/help
/area communications

**Comment by jberkus** [comment]
Aravind, thanks for taking this.  Per call today, steps:

1. Log into SurveyMonke
2. Go to My Surveys
3. Select a survey 
4. Go to "Analyze Data"
5. Select the Save As at the top (not the ones on the individual questions)
6. Export Files
7. Save "Summary Data" as PDF
8. Save "All Indivudal Responses" as CSV
9. Re-name the files or put them in a folder named after the survey
10. Track that the survey is done, and move on to the next.

**Comment by jberkus** [comment]
Surveys that don't need to be exported:

*  TEST/DRAFT/DNU Kubernetes OWNERs Survey 
*  Pick The Graphics for Contributor Summit 2021 
* [DRAFT] Cloud Native Maintainer Circle: Sign up!
* Kubernetes 2020 Steering Election Replacement Ballot Request
* Kubernetes Steering Committee Voting Exception 2020
* CNCF Projects Contributor Growth and Governance Survey
* Kubernetes Steering Committee Voting Exemption 2019

**Comment by aakankshabhende** [comment]
@jberkus I'm interested in working on this. Could you please assign me this?

**Comment by jberkus** [comment]
Hey @aakankshabhende Aravind picked it up, and unfortunately we can't share access, which is why we're leaving SM in the first place.

**Comment by ArvindParekh** [comment]
Thank you @jberkus for the steps!
> Surveys that don't need to be exported:

Noted 👍🏻

**Comment by ArvindParekh** [comment]
Update: The survey data has been exported from SurveyMonkey, organized into folders by their respective creation dates, and uploaded to the designated folder.

**Comment by jberkus** [comment]
I just need to spot-check it and then we can close the account.

**Comment by jberkus** [comment]
The account is now deleted.

/close
