### ISSUE TITLE
Unable to run heat on openstack

### ISSUE THREAD

**Issue by paddyvishnubhatt** [kubernetes/community#813]
[INFO] Create stack KubernetesStack
ERROR: The template version is invalid: Unknown version (heat_template_version: 2016-10-14). Should be one of: 2012-12-12, 2013-05-23, 2010-09-09

**Comment by bgrant0607** [comment]
@paddyvishnubhatt 
Advice on how to debug and how to get help:
https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/
