### ISSUE TITLE
API conventions should contain a maximum length for object names

### ISSUE THREAD

**Issue by pmorie** [kubernetes/community#814]
The API conventions doc should contain a maximum length for object names.  [This page](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/) says the limit is 253 characters, but this is not defined anywhere else (or by any validation) that I can see.

**Comment by cblecker** [comment]
@kubernetes/sig-architecture-api-reviews Is this still relevant?

**Comment by bgrant0607** [comment]
Yes

/remove-lifecycle rotten

deliberately not freezing so that it pops up again

**Comment by mrbobbytables** [comment]
This is documented here: 
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/identifiers.md#identifiers-and-names-in-kubernetes

If there are no objections, I think this can be closed 👍

**Comment by mrbobbytables** [comment]
I'm going to go ahead and close this out. If more info is needed, can reopen or create a new issue 👍 

/close
