### ISSUE TITLE
Can we our self configure high availability of Kubernetes Master on kube-adm beta version. 

### ISSUE THREAD

**Issue by teotia39** [kubernetes/community#829]
Wanted to use kubeadm beta for production cluster , the only limitation i see is that we have single point of failure , i.e. we cant have multiple master, Wanted to know , if there's way to make master node highly available , some workaround in current beta version , or we cannot do this at all????

**Comment by castrojo** [comment]
Please post this question to SIG cluster-lifecycle, you can find their mailing list here: https://groups.google.com/forum/#!forum/kubernetes-sig-cluster-lifecycle

Thanks!
