### ISSUE TITLE
"Kubernetes Development Automation" is outdated

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/community#834]
[Kubernetes Development Automation](https://github.com/kubernetes/community/blob/master/contributors/devel/automation.md) has some outdated contents, e.g. in "Ready to merge status", we now
- use `cncf-cla` instead of `cla`
- label `lgtm` by `/lgtm` instead of `LGTM`
- allow PR to be ready to merge when it has both `lgtm` and `approved`

We should go through the doc to find all that needs to be updated. We will also have to update all the associated docs when we change the contribution process in future, including PR/issue reporting/automation but not limited.

**Comment by xiangpengzhao** [comment]
[Pull Request Process](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md#the-testing-and-merge-workflow) also need to update.

e.g.:
>If the failure is a flake, a member can comment @k8s-bot [e2e|unit] test this issue: #<flake issue>

**Comment by bgrant0607** [comment]
cc @spiffxp

**Comment by spiffxp** [comment]
Not much bandwidth for this right now, but if/when I can contribute I will.  Happy to review if someone else takes a crack at this.

**Comment by xiangpengzhao** [comment]
cc @kirs
