### ISSUE TITLE
broken link in docs persistent-storage.md

### ISSUE THREAD

**Issue by henning** [kubernetes/community#854]
in  contributors/design-proposals/persistent-storage.md the Link to "Persisten Volumes Guide" is leading to a 404.

Maybe it's intended to lead to https://kubernetes.io/docs/concepts/storage/persistent-volumes/ - but i'm not sure, therefore I don't feel able to provide a patch / Pull Request right now.
Just thought it might be nice to tell.

**Comment by bgrant0607** [comment]
Yep, fixed. Thanks
