### ISSUE TITLE
Doc filenames should use dashes rather than underscores

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/community#856]
[Directory and file conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/coding-conventions.md#directory-and-file-conventions)

>Document directories and filenames should use dashes rather than underscores

Many docs in community repo don't follow the conventions. Should they?

e.g.: https://github.com/kubernetes/community/blob/master/contributors/devel/api_changes.md

/sig contributor-experience

**Comment by cblecker** [comment]
Future docs? Sure. All the existing docs? Not sure it's worth updating all the links for something so minor. Open to other opinions though :)

**Comment by xiangpengzhao** [comment]
Yeah this is just a minor enhancement (if any) but it may potentially break many links referenced to these docs. So it's not a very necessary TODO. Maybe it's even a should-not-do for the existing docs :)

**Comment by bgrant0607** [comment]
This is covered by #651
