### ISSUE TITLE
Document the label "cla: human-approved"

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/community#857]
There is only something about `cla: human-approved` as below in [Kubernetes Development Automation](https://github.com/kubernetes/community/blob/master/contributors/devel/automation.md)

>A PR is considered "ready for merging" if it matches the following:
The PR must have the label "cla: yes" or "cla: human-approved"

We'd better document
- why we need this
- who can label this
- when to label this
- what if the PR is labeled this but the author doesn't sign cla now and never

xref: 
https://github.com/kubernetes/test-infra/issues/3724 
https://github.com/kubernetes/community/issues/834 

/sig contributor-experience

**Comment by eparis** [comment]
It used to be (not sure if it is still true) that if person1 (who signed the CLA) created a commit and person2 (who also signed the CLA) sent a PR containing person1's commit the bot could never add `cla: yes`.  A human needed to approve it. (Very common for picks to old releses).

I'm trying to think of other times this was really required....

**Comment by bgrant0607** [comment]
In addition to the problem with multiple committers, which I believe still happens for large numbers of committers, such as for some release-branch cherrypick PRs, there were some problems with PRs from specific contributors in the past that took weeks to debug.

**Comment by cblecker** [comment]
This label is being deprecated.
/close

**Comment by spiffxp** [comment]
/assign
Base on the query: [is:pr user:kubernetes label:"cla: human-approved" -label:"cncf-cla: yes"](https://github.com/issues?utf8=%E2%9C%93&q=is%3Apr+user%3Akubernetes+label%3A%22cla%3A+human-approved%22+sort%3Aupdated-desc+-label%3A%22cncf-cla%3A+yes%22)
- this was used 14 times in the last year
- there is only one open PR with it that's going to be closed and done against another repo

So while the use cases above may be valid, they really aren't happening much anymore.  I'll be opening a PR to remove this label
