### ISSUE TITLE
Contributor experience "kubernetes/community/SIG-foo" directory doesn't exist

### ISSUE THREAD

**Issue by idvoretskyi** [kubernetes/community#86]
Contributor experience WG/SIG doesn't have a specified directory with README ("kubernetes/community/SIG-foo"); and the heading link within the SIG table in Community README (https://github.com/kubernetes/community/blob/master/README.md) redirects to the Meeting Agenda directly.

Please, create the SIG directory and fix the link.

**Comment by idvoretskyi** [comment]
cc @grodrigues3 @pwittrock

**Comment by pwittrock** [comment]
@grodrigues3 Will you take care of creating this?

**Comment by idvoretskyi** [comment]
Solved with https://github.com/kubernetes/community/pull/89

@grodrigues3 @pwittrock thank you!
