### ISSUE TITLE
help-wanted label suggestion

### ISSUE THREAD

**Issue by cblecker** [kubernetes/community#860]
I had a thought for better use of the `help-wanted` label..
- A slash command like /help-wanted to apply the label (this command should only apply to issues)
- Once someone is assigned the issue (either directly or by assigning @k8s-external-contributor), the bot automatically removes the label.

This would keep the label more relevant, allow its addition/removal by a wider group outside of just k/k maintainers, and provide more start points for new contributors.

We should also decide if `for-new-contributors` is still useful, and if perhaps it could be used in a similar way.

cc: @kubernetes/sig-contributor-experience-misc @kubernetes/sig-contributor-experience-proposals

**Comment by xiangpengzhao** [comment]
I like this idea! I have two cents.

- who will be allowed to add this label to issues, org members? issues reporters? or anyone? I'm afraid that there may be guys misreading `help-wanted`, i.e. they may label the issues which are requesting for support as `help-wanted`.

- I don't know exactly why non-org members can't be assigned issues but at least, it'd be good for the `help-wanted` issues can be assigned to non-org members directly. BTW, I don't think `@k8s-external-contributor` is such a useful placeholder, please see my comment: https://github.com/kubernetes/community/pull/787/files#r128890014

Thanks!

**Comment by cblecker** [comment]
On the second point:
The reason we can't assign issues to non-org members is a Github restriction:
https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/
> If you have write access to a repository, you can assign issues and pull requests to yourself, collaborators on personal projects, or members of your organization with read permissions on the repository.

**Comment by xiangpengzhao** [comment]
Thanks @cblecker for explanation!

**Comment by cblecker** [comment]
I've submitted https://github.com/kubernetes/test-infra/pull/3952 to implement this. Still open to any other design thoughts. :)

**Comment by bgrant0607** [comment]
It's been challenging to make help-wanted useful in the past. 

We need to ensure that the items in the list are:
* Sufficiently actionable: they clearly describe what should be done
* Tractable for new/casual contributors: there is documentation how that type of change should be made
* Goldilocks priority: Not so high in priority that it would be done by a core contributor, but useful enough that a core contributor would spend time to review it, answer questions, help get it into a release (e.g., follow features process if necessary), etc.
* Up to date: Often these issues become obsolete and have already been done, are no longer desirable, no longer make sense, change in priority, change in difficulty, etc. At one point, I declared bankruptcy, deleted the label, and re-created it.

**Comment by bgrant0607** [comment]
The above requirements should be documented somewhere.

**Comment by zhangxiaoyu-zidif** [comment]
I like the first suggestion, use /help-wanted
By the way, whether only member of kubernetes can add "help-wanted" label?
