### ISSUE TITLE
Membership Reporting Tool

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/community#874]
@spiffxp 

Lots of people ask about membership and it'd be nice to have a consistent report (to send the  kubernetes-membership@googlegroups.com ) to demonstrate justification for promotion up the contributor ladder.

I'm imagining something where you could type in your gh handle, and it'd automatically generate a list of the PRs you authored across repos, issues you've opened and closed, and PRs you've reviewed.    WDYT? 

This is aligned with the contribx q3 OKR:

@kubernetes/sig-contributor-experience-feature-requests

**Comment by resouer** [comment]
One quick question is is Github API is enough to get all the information?

**Comment by grodrigues3** [comment]
Yes, but not necessarily directly.  For example, getting PRs reviewed by someone who is not the "reviewer" or "assignee" in the gh usage of the word is not directly available.

**Comment by k82cn** [comment]
That'll be great if we have such tools! Will this be the official records? Someone uses http://stackalytics.com, which count by commit instead of PR and use email instead of gh.

**Comment by xiangpengzhao** [comment]
+1 cool!

This tool will be a web thing, right?

We may provide a script in K/community at first step. I'm imagining this script can generate the report. Contributors can run some command like `make contrib WHO=gh` which will invoke the script.

**Comment by grodrigues3** [comment]
@k82cn 

> Will this be the official records? 

I'm not sure what official records means here, but I think we can use it to help out with the contributor ladder.

@resouer

> This tool will be a web thing, right?

If web thing means dashboard, that sounds ideal to me.  I'm hoping to not build something new but rather to integrate with one the tools from ContribX (Sapho, Velodrome) that already pulls data from Gh.

**Comment by xiangpengzhao** [comment]
>If web thing means dashboard, that sounds ideal to me. I'm hoping to not build something new but rather to integrate with one the tools from ContribX (Sapho, Velodrome) that already pulls data from Gh.

Yeah. Agreed.

**Comment by zhangxiaoyu-zidif** [comment]
That sounds good. Does the tool work now?

**Comment by grodrigues3** [comment]
This is a feature request.  If you'd like to work on this please self-assign and reach out to ContribX or me for help getting started.

**Comment by nikhita** [comment]
@grodrigues3 If no one is working on this, I'd like to do so!

I had recently written a similar tool for generating the following list, taking the organization and contributor's github handle as the input.

- Pull Requests created
- Issues created
- Pull Requests reviewed

(It was not for applying for the membership but for my Google Summer of Code project report).

Here is the output it generates: https://github.com/nikhita/gsoc-meta-k8s#pull-requests-and-issues and this is the code: .https://github.com/nikhita/github-contrib.

I can work to create something more suitable for kubernetes like `make contrib WHO=gh` too. :+1: Let me know if it's ok for me to take this up! :)

One question:

> Yes, but not necessarily directly. For example, getting PRs reviewed by someone who is not the "reviewer" or "assignee" in the gh usage of the word is not directly available.

@grodrigues3 I am not sure I follow this. What is the other "meaning" of a reviewer, if not in the GH usage of the word?

**Comment by grodrigues3** [comment]
@nikhita awesome, yes we'd love the help.

> For example, getting PRs reviewed by someone who is not the "reviewer" or "assignee" in the gh usage of the word is not directly available.

Github ACLs don't allow someone who is not a collaborator or in the org to be assigned to issues or PRs.  However, they can still comment (like you just did on this issue) and give feedback.  I think those people should be credited with PR reviews even though they are not listed as the assignee or reviewer on the PR itself.   In other words, if they wrote comments but they are not assigned to the PR, we should still consider that as code review.

**Comment by nikhita** [comment]
>  In other words, if they wrote comments but they are not assigned to the PR, we should still consider that as code review.

Oh, the Github API already supports this! :)

However, it also lists the PRs that were _authored_ by the contributor. (Do we want to show this as well? IMHO it's counter-intuitive to say that someone reviewed their own PR).

But this is not really a problem and can be solved using another API call (I do that in my code).

Example:

- In this list - https://github.com/nikhita/gsoc-meta-k8s#pull-requests-and-issues - I still get pull requests I commented/reviewed on even though I am not a member.
- On the website: https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr%20reviewed-by%3Anikhita.


Please let me know if I'm missing something here.

**Comment by grodrigues3** [comment]
>  IMHO it's counter-intuitive to say that someone reviewed their own PR

Yeah, we should filter this.  More than likely they are just responding to other people's comments :)

> Please let me know if I'm missing something here.

Nope, I think you have a pretty good handle of this.  Let me know if you get stuck at all.

**Comment by resouer** [comment]
@bgrant0607 I've tried @nikhita 's tool and it's awesome, +1 for this contribute!

**Comment by grodrigues3** [comment]
So the tool does quite a bit of the work for us, but it still seems like a pull-not-push interface.  Meaning I need to look up individual contributors.

Instead, I'd like something that always displayed contributors that should be up for ladder promotion or infrequently alerted a list or the user that they should self-nominate.  The project is too large for any one person to regularly identify who should be moving up the contrib ladder.

**Comment by nikhita** [comment]
Closing this because it was decided in https://github.com/kubernetes/org/issues/10 that we don't need this now. We can revisit it, if needed.

/close
