### ISSUE TITLE
sig-release isn't in SIG list

### ISSUE THREAD

**Issue by jbeda** [kubernetes/community#891]
@calebamiles Can you make sure that sig-release is in sigs.yaml?

This is the system of record for all metadata about SIGs.  Feel free to point to a separate repo for other documents.  We can also expand the schema to include a SIG meta-repo.  But, regardless, the standard info should be there.

**Comment by cblecker** [comment]
Fixed in https://github.com/kubernetes/community/pull/917
/sig release
