### ISSUE TITLE
sig-contributor-experience Meeting agenda minutes are not publicly accessible.

### ISSUE THREAD

**Issue by hyakuhei** [kubernetes/community#912]
Hi Guys,

The agenda minutes linked from the contributor experience SIG page on Github don't seem to be publicly accessible, perhaps they should be ?

[Agenda minutes](https://docs.google.com/document/d/1qf-02B7EOrItQgwXFxgqZ5qjW0mtfu5qkYIF1Hl4ZLI/) linked from 
[sig-contributor-experience/README.md](https://github.com/kubernetes/community/blob/master/sig-contributor-experience/README.md)

Cheers
-Rob

**Comment by cblecker** [comment]
/sig contributor-experience
/assign @grodrigues3 @Phillels
@grodrigues3 @Phillels perhaps we can add kubernetes-dev@ as a viewer to the minutes doc too, so that people don't have to join contribex to read them?

**Comment by grodrigues3** [comment]
Shared with K8s-dev mailing list.
Thanks for letting me know.

/close
