### ISSUE TITLE
Disambiguate "design-proposals" and accepted designs

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/community#914]
This came up in a sig. Someone asked whether a merged doc in contributors/design-proposals/ was an accepted design or still a proposal.
* Is there documentation anywhere explaining that merged docs are accepted?
* Would contributors/designs/ be a better name for the contributors/design-proposals/? Are docs proposals when they are PRs and become designs after they merge?
* If not, then when should a design proposal graduate to design? After implementation? Should the doc move at that point?

**Comment by bgrant0607** [comment]
This is being discussed in SIG Architecture as we formalize the proposal process.

Related: #651

**Comment by grodrigues3** [comment]
@k8s-mirror-architecture-feature-request

**Comment by bgrant0607** [comment]
Almost all of these were written prior to implementation and so are "proposals" in that sense. A few were never implemented -- those should be marked, and possibly moved.

In general, we're trying to clarify this type of thing with the new KEP process.

**Comment by rhuss** [comment]
We have a similar question, especially for this accepted design proposal for service discovery by @KurtStam --> https://github.com/kubernetes/community/blob/master/contributors/design-proposals/network/service-discovery.md

This proposal introduces new annotations with a prefix "api.service.kubernetes.io/" (e.g. "api.service.kubernetes.io/description-path"). As this is an accepted design proposal (but not implemented, however there is very likely no implementation, just that spec), is it safe to assume that these annotations can be safely used in applications and tooling ? 

That open the general question whether there is a comprehensive list of "official" and reservied annotations. Afaik there is none, the only pointers I found were  https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints and the one mentioned within https://kubernetes.io/docs/concepts/services-networking/service.

**Comment by nikhita** [comment]
> Someone asked whether a merged doc in contributors/design-proposals/ was an accepted design or still a proposal.

@justaugustus is this still relevant given that we have the KEP status field today?

**Comment by mrbobbytables** [comment]
Closing this as it is no longer relevant with the KEP process 👍 
/close
