### ISSUE TITLE
Steering Committee Label?

### ISSUE THREAD

**Issue by cblecker** [kubernetes/community#921]
There are issues like https://github.com/kubernetes/community/issues/402 that need a sig label, but they fit under the steering committee more than one sig. Should we add a label for them?

cc: @kubernetes/steering-committee @grodrigues3

**Comment by grodrigues3** [comment]
yeah, I think governance falls under the steering committee rather than contribx.  let me confirm with a few steering committee members and then i'll get the label created

**Comment by bgrant0607** [comment]
Yes, we need a steering label. I suggest `committee/steering` and `committee/conduct`.

**Comment by cblecker** [comment]
Side note: if we are using a non `sig/` format, then we probably have to train the needs sig munger on it too

**Comment by grodrigues3** [comment]
@cblecker yeah, though I imagine these labels will have fewer use cases and will be specific to this repo.  I'll create the two labels for now and we can modify as needed later

**Comment by grodrigues3** [comment]
created both

/close

**Comment by spiffxp** [comment]
We should probably add support for a `/committee` command to add these committee labels?

Personally I would have been fine with `sig/committee-foo` and fewer code changes but we can do this too.
