### ISSUE TITLE
Process for becoming lead of a sig

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/community#93]
Hi all

We would like to assist with the aws sig. What is the process? I know the @justinsb would like the help, but I have not talked with @mfburnett. I know there have not been any meetings and we would love to help!

Thanks

Chris

**Comment by kris-nova** [comment]
I would also like to help out as much as possible! Where is a good place to get involved?

**Comment by foxish** [comment]
@sarahnovotny can you take a look at this?

**Comment by chrislovecnm** [comment]
@foxish I pinged her on slack and she is reaching out to @mfburnett

**Comment by chrislovecnm** [comment]
@sarahnovotny I assigned this to you, let me know if that is incorrect.  Thanks for your help!

**Comment by sarahnovotny** [comment]
thanks, @chrislovecnm!  i've just talked with @justinsb and we're game to add you as a lead.  PRs are welcome on the kubernetes/kubernetes/community/README.md to add you to the leads list.  I'll additionally add you to the SIG-leads mailing list.

@kris-nova ping me on slack and we can talk about your interests and find the right place for you to get started and help.

**Comment by chrislovecnm** [comment]
@sarahnovotny thanks ... @kris-nova is one of my partners in crime as well.  I will work with @justinsb and figure out a date for our meetings!

**Comment by kris-nova** [comment]
Thanks for getting back to me @sarahnovotny! I will reach out to you tomorrow during the waking hours just to introduce myself. @chrislovecnm is right - I am his partner in crime ;)

Just want to be apart of the community and help out as much as I can. Nice to meet everyone.
