### ISSUE TITLE
waitforattach definition in flexvolume spec is not clear - how long to wait?

### ISSUE THREAD

**Issue by mykaul** [kubernetes/community#982]
It's not clear from the spec for how long should the driver wait in waitforattach API. Forever? Fail after X seconds / retries? Something else?

**Comment by mykaul** [comment]
@kubernetes/sig-storage

**Comment by mykaul** [comment]
@kuberenetes/sig-storage-bugs

**Comment by dims** [comment]
Looks like 10 mins - https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/volume_manager.go#L88

**Comment by mykaul** [comment]
Sent https://github.com/kubernetes/community/pull/986 to clarify according to the code above.
