### ISSUE TITLE
http://slack.k8s.io redirector should speak https

### ISSUE THREAD

**Issue by justinsb** [kubernetes/community#992]
slack.k8s.io currently only listens on http, not https.  We should turn on KubeLego for it :-)

**Comment by cblecker** [comment]
@thockin @ixdy is this something you guys might be able to help with?

**Comment by ixdy** [comment]
/assign @grodrigues3 @roberthbailey 
who are the owners of this AFAIK.

Depending how it's running, an integration with lego (to use LetsEncrypt) or something equivalent might be doable, but I don't really know how it's set up.

**Comment by bgrant0607** [comment]
https://github.com/kubernetes/k8s.io

**Comment by bgrant0607** [comment]
Hmm. It's not listed there.

Perhaps @goltermann remembers how it was set up.

**Comment by bgrant0607** [comment]
We used:
https://github.com/rauchg/slackin

**Comment by spiffxp** [comment]
Is this something we run? ref: https://github.com/kubernetes/test-infra/issues/5085

**Comment by ixdy** [comment]
yes, it is.

**Comment by Katharine** [comment]
I fixed this!

https://slack.k8s.io
https://slack.kubernetes.io

**Comment by nikhita** [comment]
Thank you so much, Katharine!!

/pony yay
