### ISSUE TITLE
sig-scheduling meeting time

### ISSUE THREAD

**Issue by guangxuli** [kubernetes/community#993]
A little confusing, why sig-scheduling meeting time plan described in different places are not consistent?

1.[place 1](https://docs.google.com/document/d/13mwye7nvrmV11q9_Eg77z-1w3X7Q1GTbslpml4J7F3A/edit)
2.[place 2](https://github.com/kubernetes/community/tree/master/sig-scheduling#meetings)
which is the right one? Any difference? :(
/cc @k82cn

**Comment by guangxuli** [comment]
ping @davidopp @bsalamat

**Comment by guangxuli** [comment]
Any guys provide some feedback?

**Comment by k82cn** [comment]
please check group dicussion

**Comment by guangxuli** [comment]
okay, got it, thanks @k82cn
